In [1]:
import pandas as pd

In [2]:
cim = pd.read_csv("https://data.colorado.gov/resource/xi5f-mkzt.csv")

In [3]:
cim.columns

Index(['agency', 'ori', 'year', 'aggravatedassault',
       'allotheroffensesexcepttraffic', 'arson', 'burglary',
       'curfewloiteringlawviolations', 'disorderlyconduct',
       'drivingundertheinfluence', 'drugabuseviolationsgrandtotal',
       'drunkenness', 'embezzlement', 'forgeryandcounterfeiting', 'fraud',
       'gamblingtotal', 'humantraffickingcommerci', 'humantraffickinginvolunt',
       'larcenytheft', 'liquorlaws', 'manslaughterbynegligence',
       'motorvehicletheft', 'murderandnonnegligentman',
       'offensesagainstthefamily', 'prostitutionandcommercia', 'rape',
       'robbery', 'sexoffensesexceptrapeand', 'simpleassault',
       'stolenpropertybuyingrece', 'suspicion', 'vagrancy', 'vandalism',
       'weaponscarryingpossessingetc'],
      dtype='object')

In [8]:
cde = pd.read_excel("Colorado_Offense_Type_by_Agency_2022.xlsx",header=4,engine='openpyxl')

In [10]:
cde.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Assault\nOffenses,Aggravated\nAssault,Simple\nAssault,...,Betting/\nWagering,Operating/\nPromoting/\nAssisting\nGambling,Gambling\nEquipment\nViolations,Sports\nTampering,Por-\nnography/\nObscene\nMaterial,Pros-\ntitution\nOffenses,Pros-\ntitution,Assisting or\nPromoting\nProstitution,Purchasing\nProstitution,Weapon\nLaw\nViolations
0,Cities,Alamosa,9874.0,1346.0,259.0,958.0,129.0,227.0,56.0,65.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0
1,NaN,Arvada,122403.0,7650.0,799.0,5956.0,895.0,697.0,226.0,452.0,...,0.0,0.0,0.0,0.0,33.0,1.0,0.0,1.0,0.0,115.0
2,NaN,Aspen,6910.0,432.0,91.0,332.0,9.0,82.0,8.0,63.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
3,NaN,Ault,2913.0,24.0,13.0,11.0,0.0,13.0,2.0,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,NaN,Aurora,392134.0,35854.0,8430.0,25523.0,1901.0,7616.0,3130.0,4330.0,...,0.0,0.0,0.0,0.0,176.0,23.0,15.0,8.0,0.0,746.0

In [15]:
cols = list(cde.columns)

In [16]:
cols

['Unnamed: 0',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Assault\nOffenses',
 'Aggravated\nAssault',
 'Simple\nAssault',
 'Intimidation',
 'Homicide\nOffenses',
 'Murder and\nNonnegligent\nManslaughter',
 'Negligent\nMan-\nslaughter',
 'Justifiable\nHomicide',
 'Human\nTrafficking\nOffenses',
 'Commercial\nSex Acts',
 'Involuntary\nServitude',
 'Kidnapping/\nAbduction',
 'Sex\nOffenses',
 'Rape',
 'Sodomy',
 'Sexual\nAssault\nWith an\nObject',
 'Fondling',
 'Incest',
 'Statutory\nRape',
 'Arson',
 'Bribery',
 'Burglary/\nBreaking &\nEntering',
 'Counter-\nfeiting/\nForgery',
 'Destruction/\nDamage/\nVandalism\nof Property',
 'Embezzle-\nment',
 'Extortion/\nBlackmail',
 'Fraud\nOffenses',
 'False\nPretenses/\nSwindle/\nConfidence\nGame',
 'Credit\nCard/\nAutomated\nTeller\nMachine\nFraud',
 'Imper-\nsonation',
 'Welfare\nFraud',
 'Wire\nFraud',
 'Identity \nTheft',
 'Hacking/\nComputer \nInvasion',
 'Larceny/\nTheft\nOffenses',
 'Pocket-\npicking',
 'Purse-\nsnatching',
 'Shop-\nlifting',
 'Theft\nFrom\nBuilding',
 'Theft\nFrom\nCoin Op-\nerated\nMachine\nor Device',
 'Theft\nFrom\nMotor\nVehicle',
 'Theft of \nMotor \nVehicle\nParts or\nAcces-\nsories',
 'All\nOther\nLarceny',
 'Motor\nVehicle\nTheft',
 'Robbery',
 'Stolen\nProperty\nOffenses',
 'Animal \nCruelty',
 'Drug/\nNarcotic\nOffenses',
 'Drug/\nNarcotic\nViolations',
 'Drug\nEquipment\nViolations',
 'Gambling\nOffenses',
 'Betting/\nWagering',
 'Operating/\nPromoting/\nAssisting\nGambling',
 'Gambling\nEquipment\nViolations',
 'Sports\nTampering',
 'Por-\nnography/\nObscene\nMaterial',
 'Pros-\ntitution\nOffenses',
 'Pros-\ntitution',
 'Assisting or\nPromoting\nProstitution',
 'Purchasing\nProstitution',
 'Weapon\nLaw\nViolations']

In [22]:
for col in sorted(cim.columns):
    print(col)

agency
aggravatedassault
allotheroffensesexcepttraffic
arson
burglary
curfewloiteringlawviolations
disorderlyconduct
drivingundertheinfluence
drugabuseviolationsgrandtotal
drunkenness
embezzlement
forgeryandcounterfeiting
fraud
gamblingtotal
humantraffickingcommerci
humantraffickinginvolunt
larcenytheft
liquorlaws
manslaughterbynegligence
motorvehicletheft
murderandnonnegligentman
offensesagainstthefamily
ori
prostitutionandcommercia
rape
robbery
sexoffensesexceptrapeand
simpleassault
stolenpropertybuyingrece
suspicion
vagrancy
vandalism
weaponscarryingpossessingetc
year

In [26]:
cols[0] = "Agency Type"
cols[1] = "Agency Name"
cols[2] = "Population"
cols[3] = "Total Offenses"
cols[4] = "Crimes Against Persons"
cols[5] = "Crimes Against Property"
cols[6] = "Crimes Against Society"

for col in sorted(cols):
    col=col.replace("\n"," ")
    print(col)
    print("----")
#cde.columns=cols

Agency Name
----
Agency Type
----
Aggravated Assault
----
All Other Larceny
----
Animal  Cruelty
----
Arson
----
Assault Offenses
----
Assisting or Promoting Prostitution
----
Betting/ Wagering
----
Bribery
----
Burglary/ Breaking & Entering
----
Commercial Sex Acts
----
Counter- feiting/ Forgery
----
Credit Card/ Automated Teller Machine Fraud
----
Crimes Against Persons
----
Crimes Against Property
----
Crimes Against Society
----
Destruction/ Damage/ Vandalism of Property
----
Drug Equipment Violations
----
Drug/ Narcotic Offenses
----
Drug/ Narcotic Violations
----
Embezzle- ment
----
Extortion/ Blackmail
----
False Pretenses/ Swindle/ Confidence Game
----
Fondling
----
Fraud Offenses
----
Gambling Equipment Violations
----
Gambling Offenses
----
Hacking/ Computer  Invasion
----
Homicide Offenses
----
Human Trafficking Offenses
----
Identity  Theft
----
Imper- sonation
----
Incest
----
Intimidation
----
Involuntary Servitude
----
Justifiable Homicide
----
Kidnapping/ Abduction
----
Larceny/ Theft Offenses
----
Motor Vehicle Theft
----
Murder and Nonnegligent Manslaughter
----
Negligent Man- slaughter
----
Operating/ Promoting/ Assisting Gambling
----
Pocket- picking
----
Population
----
Por- nography/ Obscene Material
----
Pros- titution
----
Pros- titution Offenses
----
Purchasing Prostitution
----
Purse- snatching
----
Rape
----
Robbery
----
Sex Offenses
----
Sexual Assault With an Object
----
Shop- lifting
----
Simple Assault
----
Sodomy
----
Sports Tampering
----
Statutory Rape
----
Stolen Property Offenses
----
Theft From Building
----
Theft From Coin Op- erated Machine or Device
----
Theft From Motor Vehicle
----
Theft of  Motor  Vehicle Parts or Acces- sories
----
Total Offenses
----
Weapon Law Violations
----
Welfare Fraud
----
Wire Fraud
----

In [18]:
cde.head()

,Agency Type,Agency Name,Population,Total Offenses,Crimes Against Persons,Crimes Against Property,Crimes Against Society,Assault\nOffenses,Aggravated\nAssault,Simple\nAssault,...,Betting/\nWagering,Operating/\nPromoting/\nAssisting\nGambling,Gambling\nEquipment\nViolations,Sports\nTampering,Por-\nnography/\nObscene\nMaterial,Pros-\ntitution\nOffenses,Pros-\ntitution,Assisting or\nPromoting\nProstitution,Purchasing\nProstitution,Weapon\nLaw\nViolations
0,Cities,Alamosa,9874.0,1346.0,259.0,958.0,129.0,227.0,56.0,65.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0
1,NaN,Arvada,122403.0,7650.0,799.0,5956.0,895.0,697.0,226.0,452.0,...,0.0,0.0,0.0,0.0,33.0,1.0,0.0,1.0,0.0,115.0
2,NaN,Aspen,6910.0,432.0,91.0,332.0,9.0,82.0,8.0,63.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
3,NaN,Ault,2913.0,24.0,13.0,11.0,0.0,13.0,2.0,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,NaN,Aurora,392134.0,35854.0,8430.0,25523.0,1901.0,7616.0,3130.0,4330.0,...,0.0,0.0,0.0,0.0,176.0,23.0,15.0,8.0,0.0,746.0

In [21]:
for col in sorted(list(cde.columns)):
    print(col)

Agency Name
Agency Type
Aggravated
Assault
All
Other
Larceny
Animal
Cruelty
Arson
Assault
Offenses
Assisting or
Promoting
Prostitution
Betting/
Wagering
Bribery
Burglary/
Breaking &
Entering
Commercial
Sex Acts
Counter-
feiting/
Forgery
Credit
Card/
Automated
Teller
Machine
Fraud
Crimes Against Persons
Crimes Against Property
Crimes Against Society
Destruction/
Damage/
Vandalism
of Property
Drug
Equipment
Violations
Drug/
Narcotic
Offenses
Drug/
Narcotic
Violations
Embezzle-
ment
Extortion/
Blackmail
False
Pretenses/
Swindle/
Confidence
Game
Fondling
Fraud
Offenses
Gambling
Equipment
Violations
Gambling
Offenses
Hacking/
Computer
Invasion
Homicide
Offenses
Human
Trafficking
Offenses
Identity
Theft
Imper-
sonation
Incest
Intimidation
Involuntary
Servitude
Justifiable
Homicide
Kidnapping/
Abduction
Larceny/
Theft
Offenses
Motor
Vehicle
Theft
Murder and
Nonnegligent
Manslaughter
Negligent
Man-
slaughter
Operating/
Promoting/
Assisting
Gambling
Pocket-
picking
Population
Por-
nography/
Obscene
Material
Pros-
titution
Pros-
titution
Offenses
Purchasing
Prostitution
Purse-
snatching
Rape
Robbery
Sex
Offenses
Sexual
Assault
With an
Object
Shop-
lifting
Simple
Assault
Sodomy
Sports
Tampering
Statutory
Rape
Stolen
Property
Offenses
Theft
From
Building
Theft
From
Coin Op-
erated
Machine
or Device
Theft
From
Motor
Vehicle
Theft of
Motor
Vehicle
Parts or
Acces-
sories
Total Offenses
Weapon
Law
Violations
Welfare
Fraud
Wire
Fraud

In [20]:
for col in sorted(cim.columns):
    print(col)

agency
aggravatedassault
allotheroffensesexcepttraffic
arson
burglary
curfewloiteringlawviolations
disorderlyconduct
drivingundertheinfluence
drugabuseviolationsgrandtotal
drunkenness
embezzlement
forgeryandcounterfeiting
fraud
gamblingtotal
humantraffickingcommerci
humantraffickinginvolunt
larcenytheft
liquorlaws
manslaughterbynegligence
motorvehicletheft
murderandnonnegligentman
offensesagainstthefamily
ori
prostitutionandcommercia
rape
robbery
sexoffensesexceptrapeand
simpleassault
stolenpropertybuyingrece
suspicion
vagrancy
vandalism
weaponscarryingpossessingetc
year