In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r'\\wsl.localhost\Ubuntu-24.04\home\joe\work\tmp\Main Parcel Table.csv')

C:\Users\scien\AppData\Local\Temp\ipykernel_30672\628720020.py:1: DtypeWarning: Columns (10,14,21,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'\\wsl.localhost\Ubuntu-24.04\home\joe\work\tmp\Main Parcel Table.csv')

In [4]:
df.head()

,TaxYear,Pin,AssessmentYear,AIN,LegalDescr,PropertyClassDescr,TaxRollDescr,TAGId,TAGShortDescr,SAAddrNumber,...,CurCountry,SubdivisionCd,SubdivisionName,NAICSCd,ImprovementActual,LandActual,TotalActual,TotalAssessed,StateUseCd,OwnerList
0,2024,31000050,2025,1971-28-2-01-006,SubdivisionCd 054850 SubdivisionName SHERIDAN ...,Real,Real,1243330,10,1940,...,NaN,54850.0,SHERIDAN HEIGHTS,NaN,0.0,125000.0,125000.0,33750.0,400.0,JOHN H. VANDER HORST TRUST
1,2024,31000084,2025,1971-28-2-02-003,SubdivisionCd 054850 SubdivisionName SHERIDAN ...,Improvement,Real,1243330,10,2151,...,NaN,54850.0,SHERIDAN HEIGHTS,NaN,384000.0,150000.0,534000.0,33375.0,1112.0,"DEZAUCHE THOMAS JAMES Jr, BOBB QUINTON RAYMOND"
2,2024,31000092,2025,1971-28-2-02-004,SubdivisionCd 054850 SubdivisionName SHERIDAN ...,Improvement,Real,1243330,10,2135,...,NaN,54850.0,SHERIDAN HEIGHTS,NaN,357500.0,150000.0,507500.0,31719.0,1112.0,VO SACH Q
3,2024,31000106,2025,1971-28-2-02-005,SubdivisionCd 054850 SubdivisionName SHERIDAN ...,Improvement,Real,1243330,10,2121,...,NaN,54850.0,SHERIDAN HEIGHTS,NaN,263700.0,112500.0,376200.0,23512.0,1112.0,"ROCHA JOSEPH R, ROCHA JESUS ROBERTO, ROCHA JOSE R"
4,2024,31000114,2025,1971-28-2-02-006,SubdivisionCd 054850 SubdivisionName SHERIDAN ...,Improvement,Real,1243330,10,2101,...,NaN,54850.0,SHERIDAN HEIGHTS,NaN,258100.0,112500.0,370600.0,23162.0,1112.0,HOLMAN BROOKE

In [5]:
df.columns

Index(['TaxYear', 'Pin', 'AssessmentYear', 'AIN', 'LegalDescr',
       'PropertyClassDescr', 'TaxRollDescr', 'TAGId', 'TAGShortDescr',
       'SAAddrNumber', 'SAStreetNumberSfx', 'SAPredirectional', 'SAStreetName',
       'SAStreetType', 'SAPostdirectional', 'SAUnitNumber', 'SACity',
       'SAState', 'SAPostalCd', 'SAFreeFormAddr', 'SAUnitType',
       'SAAddlAddrLine', 'CurOwnerName', 'CurAttentionLine', 'CurRecipient',
       'CurAddlAddrLine', 'CurDeliveryAddr', 'CurPrimeAddrNumber',
       'CurLastLine', 'CurPredirectional', 'CurStreetName', 'CurStreetType',
       'CurPostdirectional', 'CurSecondAddrUnit', 'CurSecondAddrRange',
       'CurCity', 'CurState', 'CurPostalCd', 'CurCountry', 'SubdivisionCd',
       'SubdivisionName', 'NAICSCd', 'ImprovementActual', 'LandActual',
       'TotalActual', 'TotalAssessed', 'StateUseCd', 'OwnerList'],
      dtype='object')

In [9]:
a =  df['OwnerList'].value_counts().to_dict()

In [16]:
single=[]
for k,v in a.items():
    if v < 2:
       single.append(k)

In [19]:
df.loc[df['OwnerList'].isin(single)].head()

,TaxYear,Pin,AssessmentYear,AIN,LegalDescr,PropertyClassDescr,TaxRollDescr,TAGId,TAGShortDescr,SAAddrNumber,...,CurCountry,SubdivisionCd,SubdivisionName,NAICSCd,ImprovementActual,LandActual,TotalActual,TotalAssessed,StateUseCd,OwnerList
1,2024,31000084,2025,1971-28-2-02-003,SubdivisionCd 054850 SubdivisionName SHERIDAN ...,Improvement,Real,1243330,10,2151,...,NaN,54850.0,SHERIDAN HEIGHTS,NaN,384000.0,150000.0,534000.0,33375.0,1112.0,"DEZAUCHE THOMAS JAMES Jr, BOBB QUINTON RAYMOND"
2,2024,31000092,2025,1971-28-2-02-004,SubdivisionCd 054850 SubdivisionName SHERIDAN ...,Improvement,Real,1243330,10,2135,...,NaN,54850.0,SHERIDAN HEIGHTS,NaN,357500.0,150000.0,507500.0,31719.0,1112.0,VO SACH Q
3,2024,31000106,2025,1971-28-2-02-005,SubdivisionCd 054850 SubdivisionName SHERIDAN ...,Improvement,Real,1243330,10,2121,...,NaN,54850.0,SHERIDAN HEIGHTS,NaN,263700.0,112500.0,376200.0,23512.0,1112.0,"ROCHA JOSEPH R, ROCHA JESUS ROBERTO, ROCHA JOSE R"
4,2024,31000114,2025,1971-28-2-02-006,SubdivisionCd 054850 SubdivisionName SHERIDAN ...,Improvement,Real,1243330,10,2101,...,NaN,54850.0,SHERIDAN HEIGHTS,NaN,258100.0,112500.0,370600.0,23162.0,1112.0,HOLMAN BROOKE
5,2024,31000122,2025,1971-28-2-02-007,SubdivisionCd 054850 SubdivisionName SHERIDAN ...,Improvement,Real,1243330,10,2087,...,NaN,54850.0,SHERIDAN HEIGHTS,NaN,216100.0,112500.0,328600.0,20537.0,1112.0,GARCIA STEPHANIE

In [20]:
df.columns

Index(['TaxYear', 'Pin', 'AssessmentYear', 'AIN', 'LegalDescr',
       'PropertyClassDescr', 'TaxRollDescr', 'TAGId', 'TAGShortDescr',
       'SAAddrNumber', 'SAStreetNumberSfx', 'SAPredirectional', 'SAStreetName',
       'SAStreetType', 'SAPostdirectional', 'SAUnitNumber', 'SACity',
       'SAState', 'SAPostalCd', 'SAFreeFormAddr', 'SAUnitType',
       'SAAddlAddrLine', 'CurOwnerName', 'CurAttentionLine', 'CurRecipient',
       'CurAddlAddrLine', 'CurDeliveryAddr', 'CurPrimeAddrNumber',
       'CurLastLine', 'CurPredirectional', 'CurStreetName', 'CurStreetType',
       'CurPostdirectional', 'CurSecondAddrUnit', 'CurSecondAddrRange',
       'CurCity', 'CurState', 'CurPostalCd', 'CurCountry', 'SubdivisionCd',
       'SubdivisionName', 'NAICSCd', 'ImprovementActual', 'LandActual',
       'TotalActual', 'TotalAssessed', 'StateUseCd', 'OwnerList'],
      dtype='object')

In [ ]:
df['OwnerList'].value_counts()

OwnerList
MELCOR/TC AURORA LLC                                 797
AURORA CITY OF                                       722
MELODY HOMES INC                                     458
PUBLIC SVC CO OF COLORADO PROPERTY TAX DEPARTMENT    451
MILLROSE PROPERTIES COLORADO LLC                     381
                                                    ...
RODRIGUEZ MARCO, RUBIO ALENA                           1
CHAVEZ DOMINGUEZ ERIK R, CHAVEZ DOMINGUEZ JILL E       1
CHARACKY ALLIE E                                       1
NAVA AZUCENA                                           1
HOLCOMB RONALD E, SNELL JAMES MICHAEL Jr               1
Name: count, Length: 208328, dtype: int64

: