In [1]:
import pandas as pd

In [2]:
dfCIM = pd.read_csv("Gasoline_Prices_in_Colorado.csv")

In [3]:
dfCIM.head()

,date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice
0,01/04/2010,2.52,2.48,2.58,2.70
1,04/23/2018,2.72,2.61,2.89,3.18
2,06/29/2015,2.72,2.64,2.84,3.03
3,05/16/2005,2.20,2.16,2.27,2.37
4,07/22/2013,3.58,3.53,3.66,3.79

In [5]:
dfCIM.tail()

,date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice
1218,10/16/2023,3.67,3.52,3.92,4.23
1219,10/09/2023,3.84,3.68,4.10,4.41
1220,10/23/2023,3.74,3.59,3.99,4.28
1221,10/30/2023,3.58,3.43,3.83,4.14
1222,11/06/2023,3.40,3.26,3.65,3.95

In [8]:
dfTrn = pd.read_csv("/home/joe/bic_etl/ceo/useia/data_transformed/gas_prices.csv")

In [9]:
dfTrn.head()

,Date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice
0,2000-06-05,1.558,1.517,1.643,1.735
1,2000-06-12,1.600,1.557,1.688,1.782
2,2000-06-19,1.675,1.633,1.754,1.860
3,2000-06-26,1.709,1.668,1.788,1.892
4,2000-07-03,1.698,1.656,1.775,1.881

In [10]:
dfTrn.tail()

,Date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice
1221,2023-10-30,3.579,3.428,3.830,4.142
1222,2023-11-06,3.405,3.258,3.652,3.953
1223,2023-11-13,3.314,3.196,3.514,3.805
1224,2023-11-20,3.174,3.059,3.362,3.664
1225,2023-11-27,3.089,2.973,3.288,3.572

In [11]:
dfTrn = dfTrn.iloc[:1223]

In [12]:
dfTrn.tail()

,Date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice
1218,2023-10-09,3.837,3.682,4.098,4.408
1219,2023-10-16,3.672,3.524,3.915,4.228
1220,2023-10-23,3.736,3.587,3.987,4.283
1221,2023-10-30,3.579,3.428,3.830,4.142
1222,2023-11-06,3.405,3.258,3.652,3.953

In [13]:
dfCIM.shape

(1223, 5)

In [14]:
dfTrn.shape

(1223, 5)

In [15]:
df = dfCIM["allGradesGasPrice"] - dfTrn["allGradesGasPrice"]

In [16]:
df.head()

0    0.962
1    1.120
2    1.045
3    0.491
4    1.882
Name: allGradesGasPrice, dtype: float64

In [18]:
dfCIM.head()

,date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice
0,01/04/2010,2.52,2.48,2.58,2.70
1,04/23/2018,2.72,2.61,2.89,3.18
2,06/29/2015,2.72,2.64,2.84,3.03
3,05/16/2005,2.20,2.16,2.27,2.37
4,07/22/2013,3.58,3.53,3.66,3.79

In [19]:
dfTrn.head()

,Date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice
0,2000-06-05,1.558,1.517,1.643,1.735
1,2000-06-12,1.600,1.557,1.688,1.782
2,2000-06-19,1.675,1.633,1.754,1.860
3,2000-06-26,1.709,1.668,1.788,1.892
4,2000-07-03,1.698,1.656,1.775,1.881

dfCIM.sort_values(by="Date",axis=0)

In [21]:
dfCIM.head()

,date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice
0,01/04/2010,2.52,2.48,2.58,2.70
1,04/23/2018,2.72,2.61,2.89,3.18
2,06/29/2015,2.72,2.64,2.84,3.03
3,05/16/2005,2.20,2.16,2.27,2.37
4,07/22/2013,3.58,3.53,3.66,3.79

In [32]:
dfCIM["Date"] = pd.to_datetime(dfCIM["date"],format="%m/%d/%Y")

In [33]:
dfCIM.dtypes

date                         object
allGradesGasPrice           float64
regularGasPrice             float64
midgradeGasPrice            float64
premiumGasPrice             float64
Date                 datetime64[ns]
dtype: object

In [40]:
dfCIM.sort_values(by="Date",axis=0,inplace=True)

In [45]:
dfCIM.head()

,date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice,Date
508,06/05/2000,1.56,1.52,1.64,1.74,2000-06-05
755,06/12/2000,1.60,1.56,1.69,1.78,2000-06-12
915,06/19/2000,1.68,1.63,1.75,1.86,2000-06-19
668,06/26/2000,1.71,1.67,1.79,1.89,2000-06-26
337,07/03/2000,1.70,1.66,1.78,1.88,2000-07-03

In [55]:
df = dfCIM["allGradesGasPrice"] - dfTrn["allGradesGasPrice"]

In [47]:
dfCIM.head()

,date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice,Date
508,06/05/2000,1.56,1.52,1.64,1.74,2000-06-05
755,06/12/2000,1.60,1.56,1.69,1.78,2000-06-12
915,06/19/2000,1.68,1.63,1.75,1.86,2000-06-19
668,06/26/2000,1.71,1.67,1.79,1.89,2000-06-26
337,07/03/2000,1.70,1.66,1.78,1.88,2000-07-03

In [58]:
df.min()

-0.005000000000000782

In [49]:
dfTrn.head()

,Date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice
0,2000-06-05,1.558,1.517,1.643,1.735
1,2000-06-12,1.600,1.557,1.688,1.782
2,2000-06-19,1.675,1.633,1.754,1.860
3,2000-06-26,1.709,1.668,1.788,1.892
4,2000-07-03,1.698,1.656,1.775,1.881

In [50]:
dfCIM.head()

,date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice,Date
508,06/05/2000,1.56,1.52,1.64,1.74,2000-06-05
755,06/12/2000,1.60,1.56,1.69,1.78,2000-06-12
915,06/19/2000,1.68,1.63,1.75,1.86,2000-06-19
668,06/26/2000,1.71,1.67,1.79,1.89,2000-06-26
337,07/03/2000,1.70,1.66,1.78,1.88,2000-07-03

In [53]:
dfCIM.reset_index(inplace=True)

In [54]:
dfCIM.head()

,index,date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice,Date
0,508,06/05/2000,1.56,1.52,1.64,1.74,2000-06-05
1,755,06/12/2000,1.60,1.56,1.69,1.78,2000-06-12
2,915,06/19/2000,1.68,1.63,1.75,1.86,2000-06-19
3,668,06/26/2000,1.71,1.67,1.79,1.89,2000-06-26
4,337,07/03/2000,1.70,1.66,1.78,1.88,2000-07-03

In [62]:
dfTrn = dfTrn.round(decimals=2)

In [61]:
dfTrn.head()

,Date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice
0,2000-06-05,1.558,1.517,1.643,1.735
1,2000-06-12,1.600,1.557,1.688,1.782
2,2000-06-19,1.675,1.633,1.754,1.860
3,2000-06-26,1.709,1.668,1.788,1.892
4,2000-07-03,1.698,1.656,1.775,1.881

In [63]:
df = dfCIM["allGradesGasPrice"] - dfTrn["allGradesGasPrice"]

In [64]:
df.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: allGradesGasPrice, dtype: float64

In [65]:
df.max()

0.010000000000000231

In [66]:
df.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: allGradesGasPrice, dtype: float64

In [67]:
dfTrn.head()

,Date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice
0,2000-06-05,1.56,1.52,1.64,1.74
1,2000-06-12,1.60,1.56,1.69,1.78
2,2000-06-19,1.68,1.63,1.75,1.86
3,2000-06-26,1.71,1.67,1.79,1.89
4,2000-07-03,1.70,1.66,1.78,1.88

In [68]:
dfTrn["all diff"] = dfCIM["allGradesGasPrice"] - dfTrn["allGradesGasPrice"]

In [69]:
dfTrn["reg diff"] = dfCIM["regularGasPrice"] - dfTrn["regularGasPrice"]
dfTrn["mid diff"] = dfCIM["midgradeGasPrice"] - dfTrn["midgradeGasPrice"]
dfTrn["prm diff"] = dfCIM["premiumGasPrice"] - dfTrn["premiumGasPrice"]

In [70]:
dfTrn.head()

,Date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice,all diff,reg diff,mid diff,prm diff
0,2000-06-05,1.56,1.52,1.64,1.74,0.0,0.0,0.0,0.0
1,2000-06-12,1.60,1.56,1.69,1.78,0.0,0.0,0.0,0.0
2,2000-06-19,1.68,1.63,1.75,1.86,0.0,0.0,0.0,0.0
3,2000-06-26,1.71,1.67,1.79,1.89,0.0,0.0,0.0,0.0
4,2000-07-03,1.70,1.66,1.78,1.88,0.0,0.0,0.0,0.0

In [74]:
dfTrn.loc[dfTrn["prm diff"] != 0]

,Date,allGradesGasPrice,regularGasPrice,midgradeGasPrice,premiumGasPrice,all diff,reg diff,mid diff,prm diff
209,2004-06-07,2.03,1.98,2.10,2.19,0.0,0.0,0.0,0.01
811,2015-12-21,1.97,1.88,2.13,2.37,0.0,0.0,0.0,-0.01
814,2016-01-11,1.93,1.83,2.09,2.33,0.0,0.0,0.0,-0.01
1169,2022-10-31,3.56,3.42,3.78,4.11,0.0,0.0,0.0,-0.01