## Imports

In [3]:
import pandas as pd
import requests
import json
from pathlib import Path
from zipfile import ZipFile
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)
api_key = "iuEO68Q3WH3VppVcdQkMIjb6OSnEJuh4aFkU9cK8"

files = ["CO-2021.zip","CO-2010.zip","CO-2000.zip","CO-1992.zip"]

In [ ]:


for file in files:
    f=f"data/{file}"
    year = file[3:7]
    with ZipFile(f, 'r') as zipObj:
        for entry in zipObj.infolist():
            print(year,entry.filename, ' : ', entry.file_size, ' : ')
            # store filename and size in dictionary

In [3]:
byFile = {}
byColumn = {}

f="data/CO-2021.zip"
with ZipFile(f, 'r') as zipObj:
    for entry in zipObj.infolist():
        file = entry.filename
        if file[-3:].lower() == "csv":
           print(file)
           byFile[file]={}
           with zipObj.open(file) as myfile:
              df = pd.read_csv(myfile)
              for col in df.columns:
                if col not in byColumn:
                    byColumn[col]={}
                byColumn[col][file]=1
                byFile[file][col]=1
                
                
print("DONE")

agencies.csv
NIBRS_ACTIVITY_TYPE.csv
NIBRS_AGE.csv
NIBRS_ARREST_TYPE.csv
NIBRS_ARRESTEE.csv
NIBRS_ARRESTEE_WEAPON.csv
NIBRS_ASSIGNMENT_TYPE.csv
NIBRS_BIAS_LIST.csv
NIBRS_BIAS_MOTIVATION.csv
NIBRS_CIRCUMSTANCES.csv
NIBRS_CLEARED_EXCEPT.csv
NIBRS_CRIMINAL_ACT.csv
NIBRS_CRIMINAL_ACT_TYPE.csv
NIBRS_DRUG_MEASURE_TYPE.csv
NIBRS_ETHNICITY.csv
NIBRS_incident.csv
NIBRS_INJURY.csv
NIBRS_JUSTIFIABLE_FORCE.csv
NIBRS_LOCATION_TYPE.csv
NIBRS_month.csv
NIBRS_OFFENDER.csv
NIBRS_OFFENSE.csv
NIBRS_OFFENSE_TYPE.csv
NIBRS_PROP_DESC_TYPE.csv
NIBRS_PROP_LOSS_TYPE.csv
NIBRS_PROPERTY.csv
NIBRS_PROPERTY_DESC.csv
NIBRS_RELATIONSHIP.csv
NIBRS_SUSPECT_USING.csv
NIBRS_SUSPECTED_DRUG.csv
NIBRS_SUSPECTED_DRUG_TYPE.csv
NIBRS_USING_LIST.csv
NIBRS_VICTIM.csv
NIBRS_VICTIM_CIRCUMSTANCES.csv
NIBRS_VICTIM_INJURY.csv
NIBRS_VICTIM_OFFENDER_REL.csv
NIBRS_VICTIM_OFFENSE.csv
NIBRS_VICTIM_TYPE.csv
NIBRS_WEAPON.csv
NIBRS_WEAPON_TYPE.csv
REF_RACE.csv
REF_STATE.csv
DONE

In [3]:
for col,vals in sorted(byColumn.items()):
    print(col)
    for file in sorted(vals.keys()):
        print("    ",file)

activity_type_code
     NIBRS_ACTIVITY_TYPE.csv
activity_type_id
     NIBRS_ACTIVITY_TYPE.csv
     NIBRS_VICTIM.csv
activity_type_name
     NIBRS_ACTIVITY_TYPE.csv
age_code
     NIBRS_AGE.csv
age_code_range_high
     NIBRS_VICTIM.csv
age_id
     NIBRS_AGE.csv
     NIBRS_ARRESTEE.csv
     NIBRS_OFFENDER.csv
     NIBRS_VICTIM.csv
age_name
     NIBRS_AGE.csv
age_num
     NIBRS_ARRESTEE.csv
     NIBRS_OFFENDER.csv
     NIBRS_VICTIM.csv
age_range_high_num
     NIBRS_ARRESTEE.csv
     NIBRS_OFFENDER.csv
age_range_low_num
     NIBRS_ARRESTEE.csv
     NIBRS_OFFENDER.csv
     NIBRS_VICTIM.csv
agency_id
     NIBRS_incident.csv
     NIBRS_month.csv
     agencies.csv
agency_status
     agencies.csv
agency_type_name
     agencies.csv
arrest_date
     NIBRS_ARRESTEE.csv
arrest_type_code
     NIBRS_ARREST_TYPE.csv
arrest_type_id
     NIBRS_ARRESTEE.csv
     NIBRS_ARREST_TYPE.csv
arrest_type_name
     NIBRS_ARREST_TYPE.csv
arrestee_id
     NIBRS_ARRESTEE.csv
     NIBRS_ARRESTEE_WEAPON.csv
arrestee_seq_num
     NIBRS_ARRESTEE.csv
assignment_type_code
     NIBRS_ASSIGNMENT_TYPE.csv
assignment_type_id
     NIBRS_ASSIGNMENT_TYPE.csv
     NIBRS_VICTIM.csv
assignment_type_name
     NIBRS_ASSIGNMENT_TYPE.csv
attempt_complete_flag
     NIBRS_OFFENSE.csv
bias_category
     NIBRS_BIAS_LIST.csv
bias_code
     NIBRS_BIAS_LIST.csv
bias_desc
     NIBRS_BIAS_LIST.csv
bias_id
     NIBRS_BIAS_LIST.csv
     NIBRS_BIAS_MOTIVATION.csv
cargo_theft_flag
     NIBRS_incident.csv
change_user
     REF_STATE.csv
circumstance_code
     NIBRS_CIRCUMSTANCES.csv
circumstance_name
     NIBRS_CIRCUMSTANCES.csv
circumstance_type
     NIBRS_CIRCUMSTANCES.csv
circumstances_id
     NIBRS_CIRCUMSTANCES.csv
     NIBRS_VICTIM_CIRCUMSTANCES.csv
clearance_ind
     NIBRS_ARRESTEE.csv
cleared_except_code
     NIBRS_CLEARED_EXCEPT.csv
cleared_except_date
     NIBRS_incident.csv
cleared_except_desc
     NIBRS_CLEARED_EXCEPT.csv
cleared_except_id
     NIBRS_CLEARED_EXCEPT.csv
     NIBRS_incident.csv
cleared_except_name
     NIBRS_CLEARED_EXCEPT.csv
county_name
     agencies.csv
covered_by_legacy_ori
     agencies.csv
covered_flag
     agencies.csv
crime_against
     NIBRS_OFFENSE_TYPE.csv
criminal_act_code
     NIBRS_CRIMINAL_ACT_TYPE.csv
criminal_act_desc
     NIBRS_CRIMINAL_ACT_TYPE.csv
criminal_act_id
     NIBRS_CRIMINAL_ACT.csv
     NIBRS_CRIMINAL_ACT_TYPE.csv
criminal_act_name
     NIBRS_CRIMINAL_ACT_TYPE.csv
ct_flag
     NIBRS_OFFENSE_TYPE.csv
data_home
     NIBRS_incident.csv
     NIBRS_month.csv
data_year
     NIBRS_ARRESTEE.csv
     NIBRS_ARRESTEE_WEAPON.csv
     NIBRS_BIAS_MOTIVATION.csv
     NIBRS_CRIMINAL_ACT.csv
     NIBRS_OFFENDER.csv
     NIBRS_OFFENSE.csv
     NIBRS_PROPERTY.csv
     NIBRS_PROPERTY_DESC.csv
     NIBRS_SUSPECTED_DRUG.csv
     NIBRS_SUSPECT_USING.csv
     NIBRS_VICTIM.csv
     NIBRS_VICTIM_CIRCUMSTANCES.csv
     NIBRS_VICTIM_INJURY.csv
     NIBRS_VICTIM_OFFENDER_REL.csv
     NIBRS_VICTIM_OFFENSE.csv
     NIBRS_WEAPON.csv
     NIBRS_incident.csv
     NIBRS_month.csv
     agencies.csv
date_recovered
     NIBRS_PROPERTY_DESC.csv
ddocname
     NIBRS_month.csv
did
     NIBRS_incident.csv
     NIBRS_month.csv
direct_contributor_flag
     agencies.csv
division_code
     agencies.csv
division_id
     REF_STATE.csv
division_name
     agencies.csv
dormant_flag
     agencies.csv
dormant_year
     agencies.csv
drug_measure_code
     NIBRS_DRUG_MEASURE_TYPE.csv
drug_measure_name
     NIBRS_DRUG_MEASURE_TYPE.csv
drug_measure_type_id
     NIBRS_DRUG_MEASURE_TYPE.csv
     NIBRS_SUSPECTED_DRUG.csv
employee_rate
     agencies.csv
end_year
     REF_RACE.csv
est_drug_qty
     NIBRS_SUSPECTED_DRUG.csv
ethnicity_code
     NIBRS_ETHNICITY.csv
ethnicity_id
     NIBRS_ARRESTEE.csv
     NIBRS_ETHNICITY.csv
     NIBRS_OFFENDER.csv
     NIBRS_VICTIM.csv
ethnicity_name
     NIBRS_ETHNICITY.csv
female_civilian
     agencies.csv
female_officer
     agencies.csv
female_officer+female_civilian
     agencies.csv
hc_code
     NIBRS_OFFENSE_TYPE.csv
hc_flag
     NIBRS_OFFENSE_TYPE.csv
inc_data_year
     NIBRS_month.csv
incident_date
     NIBRS_incident.csv
incident_hour
     NIBRS_incident.csv
incident_id
     NIBRS_ARRESTEE.csv
     NIBRS_OFFENDER.csv
     NIBRS_OFFENSE.csv
     NIBRS_PROPERTY.csv
     NIBRS_VICTIM.csv
     NIBRS_incident.csv
incident_status
     NIBRS_incident.csv
injury_code
     NIBRS_INJURY.csv
injury_id
     NIBRS_INJURY.csv
     NIBRS_VICTIM_INJURY.csv
injury_name
     NIBRS_INJURY.csv
justifiable_force_code
     NIBRS_JUSTIFIABLE_FORCE.csv
justifiable_force_id
     NIBRS_VICTIM_CIRCUMSTANCES.csv
justifiable_force_name
     NIBRS_JUSTIFIABLE_FORCE.csv
justifiable_fore_id
     NIBRS_JUSTIFIABLE_FORCE.csv
legacy_ori
     agencies.csv
location_code
     NIBRS_LOCATION_TYPE.csv
location_id
     NIBRS_LOCATION_TYPE.csv
     NIBRS_OFFENSE.csv
location_name
     NIBRS_LOCATION_TYPE.csv
male_civilian
     agencies.csv
male_officer
     agencies.csv
male_officer+male_civilian
     agencies.csv
method_entry_code
     NIBRS_OFFENSE.csv
mip_flag
     agencies.csv
month_num
     NIBRS_month.csv
month_pub_status
     NIBRS_month.csv
msa_name
     agencies.csv
multiple_indicator
     NIBRS_ARRESTEE.csv
ncic_agency_name
     agencies.csv
nibrs_arrestee_weapon_id
     NIBRS_ARRESTEE_WEAPON.csv
nibrs_cert_date
     agencies.csv
nibrs_ct_start_date
     agencies.csv
nibrs_leoka_start_date
     agencies.csv
nibrs_month_id
     NIBRS_incident.csv
     NIBRS_month.csv
nibrs_multi_bias_start_date
     agencies.csv
nibrs_off_eth_start_date
     agencies.csv
nibrs_participated
     agencies.csv
nibrs_prop_desc_id
     NIBRS_PROPERTY_DESC.csv
nibrs_start_date
     agencies.csv
nibrs_suspected_drug_id
     NIBRS_SUSPECTED_DRUG.csv
nibrs_victim_offender_id
     NIBRS_VICTIM_OFFENDER_REL.csv
nibrs_weapon_id
     NIBRS_WEAPON.csv
notes
     REF_RACE.csv
num_premises_entered
     NIBRS_OFFENSE.csv
offender_id
     NIBRS_OFFENDER.csv
     NIBRS_VICTIM_OFFENDER_REL.csv
offender_seq_num
     NIBRS_OFFENDER.csv
offense_category_name
     NIBRS_OFFENSE_TYPE.csv
offense_code
     NIBRS_ARRESTEE.csv
     NIBRS_OFFENSE.csv
     NIBRS_OFFENSE_TYPE.csv
offense_group
     NIBRS_OFFENSE_TYPE.csv
offense_id
     NIBRS_BIAS_MOTIVATION.csv
     NIBRS_CRIMINAL_ACT.csv
     NIBRS_OFFENSE.csv
     NIBRS_SUSPECT_USING.csv
     NIBRS_VICTIM_OFFENSE.csv
     NIBRS_WEAPON.csv
offense_name
     NIBRS_OFFENSE_TYPE.csv
officer_rate
     agencies.csv
ori
     agencies.csv
orig_format
     NIBRS_incident.csv
     NIBRS_month.csv
outside_agency_id
     NIBRS_VICTIM.csv
parent_pop_group_code
     agencies.csv
parent_pop_group_desc
     agencies.csv
participated
     agencies.csv
pe_reported_flag
     agencies.csv
pop_sort_order
     agencies.csv
population
     agencies.csv
population_group_code
     agencies.csv
population_group_desc
     agencies.csv
population_group_id
     agencies.csv
prop_desc_code
     NIBRS_PROP_DESC_TYPE.csv
prop_desc_id
     NIBRS_PROPERTY_DESC.csv
     NIBRS_PROP_DESC_TYPE.csv
prop_desc_name
     NIBRS_PROP_DESC_TYPE.csv
prop_loss_desc
     NIBRS_PROP_LOSS_TYPE.csv
prop_loss_id
     NIBRS_PROPERTY.csv
     NIBRS_PROP_LOSS_TYPE.csv
prop_loss_name
     NIBRS_PROP_LOSS_TYPE.csv
property_id
     NIBRS_PROPERTY.csv
     NIBRS_PROPERTY_DESC.csv
     NIBRS_SUSPECTED_DRUG.csv
property_value
     NIBRS_PROPERTY_DESC.csv
pub_agency_name
     agencies.csv
pub_agency_unit
     agencies.csv
publishable_flag
     agencies.csv
race_code
     REF_RACE.csv
race_desc
     REF_RACE.csv
race_id
     NIBRS_ARRESTEE.csv
     NIBRS_OFFENDER.csv
     NIBRS_VICTIM.csv
     REF_RACE.csv
recovered_count
     NIBRS_PROPERTY.csv
region_code
     agencies.csv
region_desc
     agencies.csv
region_name
     agencies.csv
relationship_code
     NIBRS_RELATIONSHIP.csv
relationship_id
     NIBRS_RELATIONSHIP.csv
     NIBRS_VICTIM_OFFENDER_REL.csv
relationship_name
     NIBRS_RELATIONSHIP.csv
report_date
     NIBRS_month.csv
report_date_flag
     NIBRS_incident.csv
reported_status
     NIBRS_month.csv
reporting_type
     agencies.csv
resident_code
     NIBRS_ARRESTEE.csv
resident_status_code
     NIBRS_VICTIM.csv
sai
     agencies.csv
sex_code
     NIBRS_ARRESTEE.csv
     NIBRS_OFFENDER.csv
     NIBRS_VICTIM.csv
shr_flag
     NIBRS_WEAPON_TYPE.csv
sort_order
     REF_RACE.csv
start_year
     REF_RACE.csv
state_abbr
     REF_STATE.csv
     agencies.csv
state_code
     REF_STATE.csv
state_fips_code
     REF_STATE.csv
state_id
     REF_STATE.csv
     agencies.csv
state_name
     REF_STATE.csv
     agencies.csv
state_postal_abbr
     REF_STATE.csv
     agencies.csv
state_pub_freq_months
     REF_STATE.csv
stolen_count
     NIBRS_PROPERTY.csv
submission_date
     NIBRS_incident.csv
submitting_agency_id
     agencies.csv
submitting_agency_name
     agencies.csv
suburban_area_flag
     agencies.csv
summary_rape_def
     agencies.csv
suspect_using_code
     NIBRS_USING_LIST.csv
suspect_using_id
     NIBRS_SUSPECT_USING.csv
     NIBRS_USING_LIST.csv
suspect_using_name
     NIBRS_USING_LIST.csv
suspected_drug_code
     NIBRS_SUSPECTED_DRUG_TYPE.csv
suspected_drug_name
     NIBRS_SUSPECTED_DRUG_TYPE.csv
suspected_drug_type_id
     NIBRS_SUSPECTED_DRUG.csv
     NIBRS_SUSPECTED_DRUG_TYPE.csv
ucr_agency_name
     agencies.csv
under_18_disposition_code
     NIBRS_ARRESTEE.csv
update_flag
     NIBRS_month.csv
victim_id
     NIBRS_VICTIM.csv
     NIBRS_VICTIM_CIRCUMSTANCES.csv
     NIBRS_VICTIM_INJURY.csv
     NIBRS_VICTIM_OFFENDER_REL.csv
     NIBRS_VICTIM_OFFENSE.csv
victim_seq_num
     NIBRS_VICTIM.csv
victim_type_code
     NIBRS_VICTIM_TYPE.csv
victim_type_id
     NIBRS_VICTIM.csv
     NIBRS_VICTIM_TYPE.csv
victim_type_name
     NIBRS_VICTIM_TYPE.csv
weapon_code
     NIBRS_WEAPON_TYPE.csv
weapon_id
     NIBRS_ARRESTEE_WEAPON.csv
     NIBRS_WEAPON.csv
     NIBRS_WEAPON_TYPE.csv
weapon_name
     NIBRS_WEAPON_TYPE.csv
yearly_agency_id
     agencies.csv

In [4]:
for col,vals in sorted(byColumn.items()):
    print(col)
    for file in sorted(vals.keys()):
        print("    ",file)
        for cc in byFile[file].keys():
            print("          ",cc)

for file,vals in sorted(byFile.items()):
    print(file)
    for col in sorted(vals.keys()):
        print("    ",col)

In [9]:
byFile[file].keys()

dict_keys(['data_year', 'offense_id', 'incident_id', 'offense_code', 'attempt_complete_flag', 'location_id', 'num_premises_entered', 'method_entry_code'])

In [11]:
file="NIBRS_OFFENSE.csv"
# for vals in sorted(byFile[file].values()):
#     print(file)
for col in sorted(byFile[file].keys()):
    print("    ",col)
    for cc in byColumn[col].keys():
        print("          ",cc)
        for cc2 in byFile[cc].keys():
            print("                ",cc2)

     attempt_complete_flag
           NIBRS_OFFENSE.csv
                 data_year
                 offense_id
                 incident_id
                 offense_code
                 attempt_complete_flag
                 location_id
                 num_premises_entered
                 method_entry_code
     data_year
           agencies.csv
                 yearly_agency_id
                 agency_id
                 data_year
                 ori
                 legacy_ori
                 covered_by_legacy_ori
                 direct_contributor_flag
                 dormant_flag
                 dormant_year
                 reporting_type
                 ucr_agency_name
                 ncic_agency_name
                 pub_agency_name
                 pub_agency_unit
                 agency_status
                 state_id
                 state_name
                 state_abbr
                 state_postal_abbr
                 division_code
                 division_name
                 region_code
                 region_name
                 region_desc
                 agency_type_name
                 population
                 submitting_agency_id
                 sai
                 submitting_agency_name
                 suburban_area_flag
                 population_group_id
                 population_group_code
                 population_group_desc
                 parent_pop_group_code
                 parent_pop_group_desc
                 mip_flag
                 pop_sort_order
                 summary_rape_def
                 pe_reported_flag
                 male_officer
                 male_civilian
                 male_officer+male_civilian
                 female_officer
                 female_civilian
                 female_officer+female_civilian
                 officer_rate
                 employee_rate
                 nibrs_cert_date
                 nibrs_start_date
                 nibrs_leoka_start_date
                 nibrs_ct_start_date
                 nibrs_multi_bias_start_date
                 nibrs_off_eth_start_date
                 covered_flag
                 county_name
                 msa_name
                 publishable_flag
                 participated
                 nibrs_participated
           NIBRS_ARRESTEE.csv
                 data_year
                 arrestee_id
                 incident_id
                 arrestee_seq_num
                 arrest_date
                 arrest_type_id
                 multiple_indicator
                 offense_code
                 age_id
                 age_num
                 sex_code
                 race_id
                 ethnicity_id
                 resident_code
                 under_18_disposition_code
                 clearance_ind
                 age_range_low_num
                 age_range_high_num
           NIBRS_ARRESTEE_WEAPON.csv
                 data_year
                 arrestee_id
                 nibrs_arrestee_weapon_id
                 weapon_id
           NIBRS_BIAS_MOTIVATION.csv
                 data_year
                 bias_id
                 offense_id
           NIBRS_CRIMINAL_ACT.csv
                 data_year
                 criminal_act_id
                 offense_id
           NIBRS_incident.csv
                 data_year
                 agency_id
                 incident_id
                 nibrs_month_id
                 cargo_theft_flag
                 submission_date
                 incident_date
                 report_date_flag
                 incident_hour
                 cleared_except_id
                 cleared_except_date
                 incident_status
                 data_home
                 orig_format
                 did
           NIBRS_month.csv
                 data_year
                 nibrs_month_id
                 agency_id
                 month_num
                 inc_data_year
                 reported_status
                 report_date
                 update_flag
                 orig_format
                 data_home
                 ddocname
                 did
                 month_pub_status
           NIBRS_OFFENDER.csv
                 data_year
                 offender_id
                 incident_id
                 offender_seq_num
                 age_id
                 age_num
                 sex_code
                 race_id
                 ethnicity_id
                 age_range_low_num
                 age_range_high_num
           NIBRS_OFFENSE.csv
                 data_year
                 offense_id
                 incident_id
                 offense_code
                 attempt_complete_flag
                 location_id
                 num_premises_entered
                 method_entry_code
           NIBRS_PROPERTY.csv
                 data_year
                 property_id
                 incident_id
                 prop_loss_id
                 stolen_count
                 recovered_count
           NIBRS_PROPERTY_DESC.csv
                 data_year
                 property_id
                 prop_desc_id
                 property_value
                 date_recovered
                 nibrs_prop_desc_id
           NIBRS_SUSPECT_USING.csv
                 data_year
                 suspect_using_id
                 offense_id
           NIBRS_SUSPECTED_DRUG.csv
                 data_year
                 suspected_drug_type_id
                 property_id
                 est_drug_qty
                 drug_measure_type_id
                 nibrs_suspected_drug_id
           NIBRS_VICTIM.csv
                 data_year
                 victim_id
                 incident_id
                 victim_seq_num
                 victim_type_id
                 assignment_type_id
                 activity_type_id
                 outside_agency_id
                 age_id
                 age_num
                 sex_code
                 race_id
                 ethnicity_id
                 resident_status_code
                 age_range_low_num
                 age_code_range_high
           NIBRS_VICTIM_CIRCUMSTANCES.csv
                 data_year
                 victim_id
                 circumstances_id
                 justifiable_force_id
           NIBRS_VICTIM_INJURY.csv
                 data_year
                 victim_id
                 injury_id
           NIBRS_VICTIM_OFFENDER_REL.csv
                 data_year
                 victim_id
                 offender_id
                 relationship_id
                 nibrs_victim_offender_id
           NIBRS_VICTIM_OFFENSE.csv
                 data_year
                 victim_id
                 offense_id
           NIBRS_WEAPON.csv
                 data_year
                 weapon_id
                 offense_id
                 nibrs_weapon_id
     incident_id
           NIBRS_ARRESTEE.csv
                 data_year
                 arrestee_id
                 incident_id
                 arrestee_seq_num
                 arrest_date
                 arrest_type_id
                 multiple_indicator
                 offense_code
                 age_id
                 age_num
                 sex_code
                 race_id
                 ethnicity_id
                 resident_code
                 under_18_disposition_code
                 clearance_ind
                 age_range_low_num
                 age_range_high_num
           NIBRS_incident.csv
                 data_year
                 agency_id
                 incident_id
                 nibrs_month_id
                 cargo_theft_flag
                 submission_date
                 incident_date
                 report_date_flag
                 incident_hour
                 cleared_except_id
                 cleared_except_date
                 incident_status
                 data_home
                 orig_format
                 did
           NIBRS_OFFENDER.csv
                 data_year
                 offender_id
                 incident_id
                 offender_seq_num
                 age_id
                 age_num
                 sex_code
                 race_id
                 ethnicity_id
                 age_range_low_num
                 age_range_high_num
           NIBRS_OFFENSE.csv
                 data_year
                 offense_id
                 incident_id
                 offense_code
                 attempt_complete_flag
                 location_id
                 num_premises_entered
                 method_entry_code
           NIBRS_PROPERTY.csv
                 data_year
                 property_id
                 incident_id
                 prop_loss_id
                 stolen_count
                 recovered_count
           NIBRS_VICTIM.csv
                 data_year
                 victim_id
                 incident_id
                 victim_seq_num
                 victim_type_id
                 assignment_type_id
                 activity_type_id
                 outside_agency_id
                 age_id
                 age_num
                 sex_code
                 race_id
                 ethnicity_id
                 resident_status_code
                 age_range_low_num
                 age_code_range_high
     location_id
           NIBRS_LOCATION_TYPE.csv
                 location_id
                 location_code
                 location_name
           NIBRS_OFFENSE.csv
                 data_year
                 offense_id
                 incident_id
                 offense_code
                 attempt_complete_flag
                 location_id
                 num_premises_entered
                 method_entry_code
     method_entry_code
           NIBRS_OFFENSE.csv
                 data_year
                 offense_id
                 incident_id
                 offense_code
                 attempt_complete_flag
                 location_id
                 num_premises_entered
                 method_entry_code
     num_premises_entered
           NIBRS_OFFENSE.csv
                 data_year
                 offense_id
                 incident_id
                 offense_code
                 attempt_complete_flag
                 location_id
                 num_premises_entered
                 method_entry_code
     offense_code
           NIBRS_ARRESTEE.csv
                 data_year
                 arrestee_id
                 incident_id
                 arrestee_seq_num
                 arrest_date
                 arrest_type_id
                 multiple_indicator
                 offense_code
                 age_id
                 age_num
                 sex_code
                 race_id
                 ethnicity_id
                 resident_code
                 under_18_disposition_code
                 clearance_ind
                 age_range_low_num
                 age_range_high_num
           NIBRS_OFFENSE.csv
                 data_year
                 offense_id
                 incident_id
                 offense_code
                 attempt_complete_flag
                 location_id
                 num_premises_entered
                 method_entry_code
           NIBRS_OFFENSE_TYPE.csv
                 offense_code
                 offense_name
                 crime_against
                 ct_flag
                 hc_flag
                 hc_code
                 offense_category_name
                 offense_group
     offense_id
           NIBRS_BIAS_MOTIVATION.csv
                 data_year
                 bias_id
                 offense_id
           NIBRS_CRIMINAL_ACT.csv
                 data_year
                 criminal_act_id
                 offense_id
           NIBRS_OFFENSE.csv
                 data_year
                 offense_id
                 incident_id
                 offense_code
                 attempt_complete_flag
                 location_id
                 num_premises_entered
                 method_entry_code
           NIBRS_SUSPECT_USING.csv
                 data_year
                 suspect_using_id
                 offense_id
           NIBRS_VICTIM_OFFENSE.csv
                 data_year
                 victim_id
                 offense_id
           NIBRS_WEAPON.csv
                 data_year
                 weapon_id
                 offense_id
                 nibrs_weapon_id

In [7]:
columns = {}
agencies = {}
for file in files:
    f=f"data/{file}"
    year = int(file[3:7])
    columns[year] = []
    
    
    with ZipFile(f, 'r') as zipObj:
        if year < 2021: 
           fw = "cde_agencies.csv"
        else:
           fw = "agencies.csv"
            
        with zipObj.open(fw) as myfile:
            df = pd.read_csv(myfile)
            columns[year].append(list(df.columns))
            print(year,df.columns)
            for index,row in df.iterrows():
                ori = row["ori"]
                if year < 2021: 
                   name = row["agency_name"] 
                else:
                   name = row["ucr_agency_name"] 
                if ori in agencies:
                  agencies[ori][year] = name
                else:
                  agencies[ori] = {}
                  agencies[ori][year] = name

2021 Index(['yearly_agency_id', 'agency_id', 'data_year', 'ori', 'legacy_ori',
       'covered_by_legacy_ori', 'direct_contributor_flag', 'dormant_flag',
       'dormant_year', 'reporting_type', 'ucr_agency_name', 'ncic_agency_name',
       'pub_agency_name', 'pub_agency_unit', 'agency_status', 'state_id',
       'state_name', 'state_abbr', 'state_postal_abbr', 'division_code',
       'division_name', 'region_code', 'region_name', 'region_desc',
       'agency_type_name', 'population', 'submitting_agency_id', 'sai',
       'submitting_agency_name', 'suburban_area_flag', 'population_group_id',
       'population_group_code', 'population_group_desc',
       'parent_pop_group_code', 'parent_pop_group_desc', 'mip_flag',
       'pop_sort_order', 'summary_rape_def', 'pe_reported_flag',
       'male_officer', 'male_civilian', 'male_officer+male_civilian',
       'female_officer', 'female_civilian', 'female_officer+female_civilian',
       'officer_rate', 'employee_rate', 'nibrs_cert_date', 'nibrs_start_date',
       'nibrs_leoka_start_date', 'nibrs_ct_start_date',
       'nibrs_multi_bias_start_date', 'nibrs_off_eth_start_date',
       'covered_flag', 'county_name', 'msa_name', 'publishable_flag',
       'participated', 'nibrs_participated'],
      dtype='object')
2010 Index(['agency_id', 'ori', 'legacy_ori', 'agency_name', 'short_name',
       'agency_type_id', 'agency_type_name', 'tribe_id', 'campus_id',
       'city_id', 'city_name', 'state_id', 'state_abbr', 'primary_county_id',
       'primary_county', 'primary_county_fips', 'agency_status',
       'submitting_agency_id', 'submitting_sai', 'submitting_name',
       'submitting_state_abbr', 'start_year', 'dormant_year', 'current_year',
       'revised_rape_start', 'current_nibrs_start_year', 'population',
       'population_group_code', 'population_group_desc',
       'population_source_flag', 'suburban_area_flag', 'core_city_flag',
       'months_reported', 'nibrs_months_reported', 'past_10_years_reported',
       'covered_by_id', 'covered_by_ori', 'covered_by_name', 'staffing_year',
       'total_officers', 'total_civilians', 'icpsr_zip', 'icpsr_lat',
       'icpsr_lng'],
      dtype='object')
2000 Index(['agency_id', 'ori', 'legacy_ori', 'agency_name', 'short_name',
       'agency_type_id', 'agency_type_name', 'tribe_id', 'campus_id',
       'city_id', 'city_name', 'state_id', 'state_abbr', 'primary_county_id',
       'primary_county', 'primary_county_fips', 'agency_status',
       'submitting_agency_id', 'submitting_sai', 'submitting_name',
       'submitting_state_abbr', 'start_year', 'dormant_year', 'current_year',
       'revised_rape_start', 'current_nibrs_start_year', 'population',
       'population_group_code', 'population_group_desc',
       'population_source_flag', 'suburban_area_flag', 'core_city_flag',
       'months_reported', 'nibrs_months_reported', 'past_10_years_reported',
       'covered_by_id', 'covered_by_ori', 'covered_by_name', 'staffing_year',
       'total_officers', 'total_civilians', 'icpsr_zip', 'icpsr_lat',
       'icpsr_lng'],
      dtype='object')
1992 Index(['agency_id', 'ori', 'legacy_ori', 'agency_name', 'short_name',
       'agency_type_id', 'agency_type_name', 'tribe_id', 'campus_id',
       'city_id', 'city_name', 'state_id', 'state_abbr', 'primary_county_id',
       'primary_county', 'primary_county_fips', 'agency_status',
       'submitting_agency_id', 'submitting_sai', 'submitting_name',
       'submitting_state_abbr', 'start_year', 'dormant_year', 'current_year',
       'revised_rape_start', 'current_nibrs_start_year', 'population',
       'population_group_code', 'population_group_desc',
       'population_source_flag', 'suburban_area_flag', 'core_city_flag',
       'months_reported', 'nibrs_months_reported', 'past_10_years_reported',
       'covered_by_id', 'covered_by_ori', 'covered_by_name', 'staffing_year',
       'total_officers', 'total_civilians', 'icpsr_zip', 'icpsr_lat',
       'icpsr_lng'],
      dtype='object')

In [52]:
counts = {}
stats = {}
for ori,vals in agencies.items():
    il = len(vals)
    if il not in stats:
        stats[il] = 0
    stats[il]+=1
    for year,name in vals.items():
        if year not in counts:
            counts[year] = 0
        counts[year]+=1

In [53]:
counts
print(stats)

{4: 207, 2: 11, 3: 72, 1: 16}

In [45]:
'ori','ori'
'ucr_agency_name',  'agency_name',

columns

{2021: [['yearly_agency_id',
   'agency_id',
   'data_year',
   'ori',
   'legacy_ori',
   'covered_by_legacy_ori',
   'direct_contributor_flag',
   'dormant_flag',
   'dormant_year',
   'reporting_type',
   'ucr_agency_name',
   'ncic_agency_name',
   'pub_agency_name',
   'pub_agency_unit',
   'agency_status',
   'state_id',
   'state_name',
   'state_abbr',
   'state_postal_abbr',
   'division_code',
   'division_name',
   'region_code',
   'region_name',
   'region_desc',
   'agency_type_name',
   'population',
   'submitting_agency_id',
   'sai',
   'submitting_agency_name',
   'suburban_area_flag',
   'population_group_id',
   'population_group_code',
   'population_group_desc',
   'parent_pop_group_code',
   'parent_pop_group_desc',
   'mip_flag',
   'pop_sort_order',
   'summary_rape_def',
   'pe_reported_flag',
   'male_officer',
   'male_civilian',
   'male_officer+male_civilian',
   'female_officer',
   'female_civilian',
   'female_officer+female_civilian',
   'officer_rate',
   'employee_rate',
   'nibrs_cert_date',
   'nibrs_start_date',
   'nibrs_leoka_start_date',
   'nibrs_ct_start_date',
   'nibrs_multi_bias_start_date',
   'nibrs_off_eth_start_date',
   'covered_flag',
   'county_name',
   'msa_name',
   'publishable_flag',
   'participated',
   'nibrs_participated']],
 2010: [['agency_id',
   'ori',
   'legacy_ori',
   'agency_name',
   'short_name',
   'agency_type_id',
   'agency_type_name',
   'tribe_id',
   'campus_id',
   'city_id',
   'city_name',
   'state_id',
   'state_abbr',
   'primary_county_id',
   'primary_county',
   'primary_county_fips',
   'agency_status',
   'submitting_agency_id',
   'submitting_sai',
   'submitting_name',
   'submitting_state_abbr',
   'start_year',
   'dormant_year',
   'current_year',
   'revised_rape_start',
   'current_nibrs_start_year',
   'population',
   'population_group_code',
   'population_group_desc',
   'population_source_flag',
   'suburban_area_flag',
   'core_city_flag',
   'months_reported',
   'nibrs_months_reported',
   'past_10_years_reported',
   'covered_by_id',
   'covered_by_ori',
   'covered_by_name',
   'staffing_year',
   'total_officers',
   'total_civilians',
   'icpsr_zip',
   'icpsr_lat',
   'icpsr_lng']],
 2000: [['agency_id',
   'ori',
   'legacy_ori',
   'agency_name',
   'short_name',
   'agency_type_id',
   'agency_type_name',
   'tribe_id',
   'campus_id',
   'city_id',
   'city_name',
   'state_id',
   'state_abbr',
   'primary_county_id',
   'primary_county',
   'primary_county_fips',
   'agency_status',
   'submitting_agency_id',
   'submitting_sai',
   'submitting_name',
   'submitting_state_abbr',
   'start_year',
   'dormant_year',
   'current_year',
   'revised_rape_start',
   'current_nibrs_start_year',
   'population',
   'population_group_code',
   'population_group_desc',
   'population_source_flag',
   'suburban_area_flag',
   'core_city_flag',
   'months_reported',
   'nibrs_months_reported',
   'past_10_years_reported',
   'covered_by_id',
   'covered_by_ori',
   'covered_by_name',
   'staffing_year',
   'total_officers',
   'total_civilians',
   'icpsr_zip',
   'icpsr_lat',
   'icpsr_lng']],
 1992: [['agency_id',
   'ori',
   'legacy_ori',
   'agency_name',
   'short_name',
   'agency_type_id',
   'agency_type_name',
   'tribe_id',
   'campus_id',
   'city_id',
   'city_name',
   'state_id',
   'state_abbr',
   'primary_county_id',
   'primary_county',
   'primary_county_fips',
   'agency_status',
   'submitting_agency_id',
   'submitting_sai',
   'submitting_name',
   'submitting_state_abbr',
   'start_year',
   'dormant_year',
   'current_year',
   'revised_rape_start',
   'current_nibrs_start_year',
   'population',
   'population_group_code',
   'population_group_desc',
   'population_source_flag',
   'suburban_area_flag',
   'core_city_flag',
   'months_reported',
   'nibrs_months_reported',
   'past_10_years_reported',
   'covered_by_id',
   'covered_by_ori',
   'covered_by_name',
   'staffing_year',
   'total_officers',
   'total_civilians',
   'icpsr_zip',
   'icpsr_lat',
   'icpsr_lng']]}

## Read Data

In [4]:
col = "INCIDENT_ID"
off = pd.read_csv("data/NIBRS_OFFENSE.csv")
icd = pd.read_csv("data/NIBRS_incident.csv")

In [38]:
print(off.shape)
print(icd.shape)

(328469, 8)
(285514, 15)

## Merge Offenses and Incidents

In [5]:
off = off.merge(icd,on=col,how="left")

In [6]:
off.shape

(328469, 22)

In [27]:
off[col].nunique()

285514

In [28]:
seeCols(off)

AGENCY_ID
ATTEMPT_COMPLETE_FLAG
CARGO_THEFT_FLAG
CLEARED_EXCEPT_DATE
CLEARED_EXCEPT_ID
DATA_HOME
DATA_YEAR_x
DATA_YEAR_y
DID
INCIDENT_DATE
INCIDENT_HOUR
INCIDENT_ID
INCIDENT_STATUS
LOCATION_ID
METHOD_ENTRY_CODE
NIBRS_MONTH_ID
NUM_PREMISES_ENTERED
OFFENSE_ID
OFFENSE_TYPE_ID
ORIG_FORMAT
REPORT_DATE_FLAG
SUBMISSION_DATE

In [11]:
off["OFFENSE_TYPE_ID"].value_counts()

5     44538
45    37098
51    30330
14    29232
49    22141
23    22100
21    21682
16    20837
35    12364
47    10915
27    10337
7      8948
2      6314
41     5827
39     5773
46     5757
11     5592
63     4220
44     4033
40     3833
36     2606
28     2468
56     2265
29     1905
20     1048
43      681
8       656
62      567
4       528
64      492
37      488
50      473
30      462
26      390
17      314
18      225
13      221
32      203
3       144
15      137
57      136
55       69
59       47
1        17
38       15
24       11
12       11
60        7
54        6
61        4
31        2
Name: OFFENSE_TYPE_ID, dtype: int64

In [12]:
off["OFFENSE_TYPE_ID"].isna().sum()

0

## Get Name of Offense Committed

In [7]:
offType = pd.read_csv("data/NIBRS_OFFENSE_TYPE.csv")

In [8]:
offType.head()

,OFFENSE_TYPE_ID,OFFENSE_CODE,OFFENSE_NAME,CRIME_AGAINST,CT_FLAG,HC_FLAG,HC_CODE,OFFENSE_CATEGORY_NAME,OFFENSE_GROUP
0,58,23*,Not Specified,Property,N,Y,6.0,Larceny/Theft Offenses,A
1,1,09C,Justifiable Homicide,Person,N,N,NaN,Homicide Offenses,A
2,2,26A,False Pretenses/Swindle/Confidence Game,Property,Y,Y,NaN,Fraud Offenses,A
3,3,36B,Statutory Rape,Person,N,Y,NaN,Sex Offenses,A
4,4,11C,Sexual Assault With An Object,Person,N,Y,2.0,Sex Offenses,A

In [9]:
off["OFFENSE_TYPE_ID"].nunique()

51

In [10]:
offType["OFFENSE_TYPE_ID"].nunique()

64

## Merge Offense Name

In [11]:
off = off.merge(offType,on="OFFENSE_TYPE_ID",how="left")

In [12]:
off.shape

(328469, 30)

In [33]:
seeCols(off)

AGENCY_ID
ATTEMPT_COMPLETE_FLAG
CARGO_THEFT_FLAG
CLEARED_EXCEPT_DATE
CLEARED_EXCEPT_ID
CRIME_AGAINST
CT_FLAG
DATA_HOME
DATA_YEAR_x
DATA_YEAR_y
DID
HC_CODE
HC_FLAG
INCIDENT_DATE
INCIDENT_HOUR
INCIDENT_ID
INCIDENT_STATUS
LOCATION_ID
METHOD_ENTRY_CODE
NIBRS_MONTH_ID
NUM_PREMISES_ENTERED
OFFENSE_CATEGORY_NAME
OFFENSE_CODE
OFFENSE_GROUP
OFFENSE_ID
OFFENSE_NAME
OFFENSE_TYPE_ID
ORIG_FORMAT
REPORT_DATE_FLAG
SUBMISSION_DATE

In [34]:
off["OFFENSE_NAME"].nunique()

51

In [35]:
off["OFFENSE_NAME"].value_counts()

Destruction/Damage/Vandalism of Property       44538
All Other Larceny                              37098
Simple Assault                                 30330
Theft From Motor Vehicle                       29232
Burglary/Breaking & Entering                   22141
Shoplifting                                    22100
Motor Vehicle Theft                            21682
Drug/Narcotic Violations                       20837
Drug Equipment Violations                      12364
Theft From Building                            10915
Aggravated Assault                             10337
Theft of Motor Vehicle Parts or Accessories     8948
False Pretenses/Swindle/Confidence Game         6314
Credit Card/Automated Teller Machine Fraud      5827
Weapon Law Violations                           5773
Impersonation                                   5757
Counterfeiting/Forgery                          5592
Identity Theft                                  4220
Intimidation                                    4033
Robbery                                         3833
Rape                                            2606
Stolen Property Offenses                        2468
Fondling                                        2265
Kidnapping/Abduction                            1905
Arson                                           1048
Sodomy                                           681
Pornography/Obscene Material                     656
Animal Cruelty                                   567
Sexual Assault With An Object                    528
Hacking/Computer Invasion                        492
Embezzlement                                     488
Theft From Coin-Operated Machine or Device       473
Prostitution                                     462
Extortion/Blackmail                              390
Wire Fraud                                       314
Purse-snatching                                  225
Pocket-picking                                   221
Murder and Nonnegligent Manslaughter             203
Statutory Rape                                   144
Assisting or Promoting Prostitution              137
Bribery                                          136
Incest                                            69
Human Trafficking, Commercial Sex Acts            47
Justifiable Homicide                              17
Negligent Manslaughter                            15
Operating/Promoting/Assisting Gambling            11
Welfare Fraud                                     11
Human Trafficking, Involuntary Servitude           7
Gambling Equipment Violation                       6
Purchasing Prostitution                            4
Betting/Wagering                                   2
Name: OFFENSE_NAME, dtype: int64

In [37]:
off['OFFENSE_CODE'].value_counts()

290    44538
23H    37098
13B    30330
23F    29232
220    22141
23C    22100
240    21682
35A    20837
35B    12364
23D    10915
13A    10337
23G     8948
26A     6314
26B     5827
520     5773
26C     5757
250     5592
26F     4220
13C     4033
120     3833
11A     2606
280     2468
11D     2265
100     1905
200     1048
11B      681
370      656
720      567
11C      528
26G      492
270      488
23E      473
40A      462
210      390
26E      314
23B      225
23A      221
09A      203
36B      144
40B      137
510      136
36A       69
64A       47
09C       17
09B       15
39B       11
26D       11
64B        7
39C        6
40C        4
39A        2
Name: OFFENSE_CODE, dtype: int64

In [47]:
off["AGENCY_ID"].nunique()

215

## Agencies

In [13]:
agc = pd.read_csv("data/agencies.csv")

In [23]:
agc.head()

,YEARLY_AGENCY_ID,AGENCY_ID,DATA_YEAR,ORI,LEGACY_ORI,COVERED_BY_LEGACY_ORI,DIRECT_CONTRIBUTOR_FLAG,DORMANT_FLAG,DORMANT_YEAR,REPORTING_TYPE,...,NIBRS_LEOKA_START_DATE,NIBRS_CT_START_DATE,NIBRS_MULTI_BIAS_START_DATE,NIBRS_OFF_ETH_START_DATE,COVERED_FLAG,COUNTY_NAME,MSA_NAME,PUBLISHABLE_FLAG,PARTICIPATED,NIBRS_PARTICIPATED
0,18262017,1826,2017,CO0010000,CO0010000,NaN,N,N,NaN,I,...,01-MAR-03,01-FEB-14,01-JAN-16,01-APR-13,N,ADAMS,"Denver-Aurora-Lakewood, CO",Y,Y,Y
1,18272017,1827,2017,CO0010100,CO0010100,NaN,N,N,NaN,I,...,01-MAR-03,01-FEB-14,01-JAN-16,01-APR-13,N,DOUGLAS; ADAMS; ARAPAHOE,"Denver-Aurora-Lakewood, CO",Y,Y,Y
2,18282017,1828,2017,CO0010200,CO0010200,NaN,N,N,NaN,I,...,01-JAN-06,01-FEB-14,01-JAN-16,01-APR-13,N,WELD; ADAMS,"Denver-Aurora-Lakewood, CO; Greeley, CO",Y,Y,Y
3,18292017,1829,2017,CO0010300,CO0010300,NaN,N,N,NaN,I,...,01-MAR-03,01-FEB-14,01-JAN-16,01-APR-13,N,ADAMS,"Denver-Aurora-Lakewood, CO",Y,Y,Y
4,18302017,1830,2017,CO0010400,CO0010400,NaN,N,N,NaN,I,...,01-SEP-12,01-JUL-14,01-FEB-16,01-APR-13,N,ADAMS,"Denver-Aurora-Lakewood, CO",Y,Y,Y

In [50]:
seeCols(agc)

0
0.1
AGENCY_ID
AGENCY_STATUS
AGENCY_TYPE_NAME
COUNTY_NAME
COVERED_BY_LEGACY_ORI
COVERED_FLAG
DATA_YEAR
DIRECT_CONTRIBUTOR_FLAG
DIVISION_CODE
DIVISION_NAME
DORMANT_FLAG
DORMANT_YEAR
FEMALE_CIVILIAN
FEMALE_OFFICER
LEGACY_ORI
MALE_CIVILIAN
MALE_OFFICER
MIP_FLAG
MSA_NAME
NCIC_AGENCY_NAME
NIBRS_CERT_DATE
NIBRS_CT_START_DATE
NIBRS_LEOKA_START_DATE
NIBRS_MULTI_BIAS_START_DATE
NIBRS_OFF_ETH_START_DATE
NIBRS_PARTICIPATED
NIBRS_START_DATE
ORI
PARENT_POP_GROUP_CODE
PARENT_POP_GROUP_DESC
PARTICIPATED
PED.FEMALE_CIVILIAN+PED.FEMALE_OFFICER
PED.MALE_OFFICER+PED.MALE_CIVILIAN
PE_REPORTED_FLAG
POPULATION
POPULATION_GROUP_CODE
POPULATION_GROUP_DESC
POPULATION_GROUP_ID
POP_SORT_ORDER
PUBLISHABLE_FLAG
PUB_AGENCY_NAME
PUB_AGENCY_UNIT
REGION_CODE
REGION_DESC
REGION_NAME
REPORTING_TYPE
SAI
STATE_ABBR
STATE_ID
STATE_NAME
STATE_POSTAL_ABBR
SUBMITTING_AGENCY_ID
SUBMITTING_AGENCY_NAME
SUBURBAN_AREA_FLAG
SUMMARY_RAPE_DEF
UCR_AGENCY_NAME
YEARLY_AGENCY_ID

In [27]:
#agc["NCIC_AGENCY_NAME"].value_counts()
#agc["MSA_NAME"].value_counts()
agc["PUB_AGENCY_NAME"].value_counts()
#agc["DIVISION_NAME"].value_counts()
#agc["SUBMITTING_AGENCY_NAME"].value_counts()
#agc["SUBMITTING_AGENCY_NAME"].value_counts()
#agc["UCR_AGENCY_NAME"].value_counts()
#agc["SAI"].value_counts()
#agc["AGENCY_TYPE_NAME"].value_counts()
#agc["0.1"].value_counts()
#agc["COVERED_BY_LEGACY_ORI"].value_counts()

University of Colorado:    4
Alamosa                    2
Yuma                       2
Eagle                      2
Boulder                    2
                          ..
Silverthorne               1
Log Lane Village           1
Estes Park                 1
Larimer                    1
Palisade                   1
Name: PUB_AGENCY_NAME, Length: 209, dtype: int64

In [65]:
for col in sorted(agc.columns):
    print(col)
    print(agc[col].value_counts())
    print("-------------------------------")

0
0    220
Name: 0, dtype: int64
-------------------------------
0.1
0    220
Name: 0.1, dtype: int64
-------------------------------
AGENCY_ID
2047    1
1832    1
1844    1
1843    1
1842    1
       ..
1940    1
1938    1
1937    1
1936    1
2050    1
Name: AGENCY_ID, Length: 220, dtype: int64
-------------------------------
AGENCY_STATUS
A    220
Name: AGENCY_STATUS, dtype: int64
-------------------------------
AGENCY_TYPE_NAME
City                     142
County                    58
University or College     14
Other                      3
Other State Agency         2
State Police               1
Name: AGENCY_TYPE_NAME, dtype: int64
-------------------------------
COUNTY_NAME
WELD                19
JEFFERSON           10
EL PASO              9
ARAPAHOE             9
GARFIELD             7
                    ..
JEFFERSON; ADAMS     1
SEDGWICK             1
PITKIN; EAGLE        1
HINSDALE             1
ADAMS; WELD          1
Name: COUNTY_NAME, Length: 74, dtype: int64
-------------------------------
COVERED_BY_LEGACY_ORI
Series([], Name: COVERED_BY_LEGACY_ORI, dtype: int64)
-------------------------------
COVERED_FLAG
N    220
Name: COVERED_FLAG, dtype: int64
-------------------------------
DATA_YEAR
2017    220
Name: DATA_YEAR, dtype: int64
-------------------------------
DIRECT_CONTRIBUTOR_FLAG
N    220
Name: DIRECT_CONTRIBUTOR_FLAG, dtype: int64
-------------------------------
DIVISION_CODE
8    220
Name: DIVISION_CODE, dtype: int64
-------------------------------
DIVISION_NAME
Mountain    220
Name: DIVISION_NAME, dtype: int64
-------------------------------
DORMANT_FLAG
N    220
Name: DORMANT_FLAG, dtype: int64
-------------------------------
DORMANT_YEAR
Series([], Name: DORMANT_YEAR, dtype: int64)
-------------------------------
FEMALE_CIVILIAN
1      39
0      37
3      18
2      15
4       9
6       8
7       8
8       7
5       6
19      6
15      5
11      4
14      3
17      3
13      3
10      3
9       3
23      3
16      2
55      2
18      2
45      2
22      2
32      2
24      1
20      1
21      1
237     1
25      1
213     1
179     1
169     1
161     1
158     1
127     1
124     1
119     1
110     1
103     1
100     1
99      1
89      1
78      1
64      1
61      1
58      1
54      1
52      1
49      1
43      1
40      1
30      1
Name: FEMALE_CIVILIAN, dtype: int64
-------------------------------
FEMALE_OFFICER
0      69
1      52
2      21
3      10
5       9
4       8
7       7
10      4
13      4
6       3
9       3
69      2
35      2
32      2
8       2
11      2
100     2
14      1
12      1
191     1
15      1
17      1
21      1
22      1
23      1
25      1
29      1
37      1
40      1
42      1
44      1
50      1
51      1
87      1
20      1
Name: FEMALE_OFFICER, dtype: int64
-------------------------------
LEGACY_ORI
CO0390100    1
CO0450000    1
CO0320000    1
CO0621100    1
CO0300000    1
            ..
CO0340300    1
CO0590300    1
CO0020000    1
CO0622000    1
CO0070300    1
Name: LEGACY_ORI, Length: 220, dtype: int64
-------------------------------
MALE_CIVILIAN
0      94
1      25
4       9
3       8
8       7
2       7
5       7
10      6
6       5
11      4
9       4
12      3
13      3
14      3
50      2
7       2
77      2
28      2
17      2
18      2
20      1
15      1
16      1
148     1
21      1
56      1
116     1
96      1
89      1
87      1
76      1
60      1
58      1
51      1
143     1
43      1
39      1
36      1
33      1
32      1
27      1
23      1
22      1
Name: MALE_CIVILIAN, dtype: int64
-------------------------------
MALE_OFFICER
7     15
4     13
3     11
9      9
5      9
      ..
82     1
85     1
86     1
90     1
44     1
Name: MALE_OFFICER, Length: 78, dtype: int64
-------------------------------
MIP_FLAG
N    205
Y     15
Name: MIP_FLAG, dtype: int64
-------------------------------
MSA_NAME
Non-MSA                                    118
Denver-Aurora-Lakewood, CO                  45
Greeley, CO                                 19
Colorado Springs, CO                        12
Fort Collins, CO                             6
Boulder, CO                                  6
Grand Junction, CO                           4
Denver-Aurora-Lakewood, CO; Greeley, CO      3
Pueblo, CO                                   3
Fort Collins, CO; Greeley, CO                2
Boulder, CO; Greeley, CO                     2
Name: MSA_NAME, dtype: int64
-------------------------------
NCIC_AGENCY_NAME
EAGLE               2
GUNNISON            2
BOULDER             2
YUMA                2
ALAMOSA             2
                   ..
ADAMS               1
HINSDALE            1
SNOWMASS VILLAGE    1
CHEYENNE            1
FOWLER              1
Name: NCIC_AGENCY_NAME, Length: 211, dtype: int64
-------------------------------
NIBRS_CERT_DATE
01-JAN-92    220
Name: NIBRS_CERT_DATE, dtype: int64
-------------------------------
NIBRS_CT_START_DATE
01-FEB-14    138
01-MAR-14     25
01-APR-14     14
01-MAY-14      8
01-JUN-14      8
01-JUL-14      6
01-AUG-14      4
01-JAN-15      4
01-FEB-15      2
01-OCT-14      2
01-SEP-16      1
01-SEP-15      1
01-OCT-15      1
01-OCT-13      1
01-JAN-16      1
01-NOV-15      1
01-MAR-15      1
01-FEB-17      1
Name: NIBRS_CT_START_DATE, dtype: int64
-------------------------------
NIBRS_LEOKA_START_DATE
01-MAR-03    101
01-APR-03     10
01-JUL-12      8
01-OCT-12      7
01-JUN-12      5
01-SEP-12      5
01-AUG-12      4
01-FEB-11      4
01-OCT-05      4
01-MAR-10      4
01-JUL-03      4
01-DEC-13      3
01-AUG-04      3
01-SEP-06      2
01-FEB-06      2
01-FEB-15      2
01-JUN-05      2
01-JAN-06      2
01-MAY-13      2
01-NOV-03      2
01-MAY-05      2
01-DEC-12      2
01-AUG-06      2
01-JAN-04      2
01-SEP-03      2
01-JAN-13      2
01-NOV-12      2
01-NOV-06      1
01-FEB-13      1
01-FEB-04      1
01-JUN-06      1
01-OCT-14      1
01-JUN-14      1
01-MAR-07      1
01-JUL-06      1
01-APR-06      1
01-DEC-10      1
01-JAN-14      1
01-JUN-03      1
01-JAN-15      1
01-APR-04      1
01-MAY-03      1
01-NOV-05      1
01-MAY-04      1
01-MAR-05      1
01-JAN-05      1
01-AUG-13      1
01-NOV-04      1
01-SEP-04      1
01-SEP-10      1
01-JAN-11      1
01-JUN-10      1
01-JAN-09      1
01-NOV-15      1
01-AUG-11      1
01-SEP-15      1
01-FEB-14      1
Name: NIBRS_LEOKA_START_DATE, dtype: int64
-------------------------------
NIBRS_MULTI_BIAS_START_DATE
01-JAN-16    194
01-FEB-16     14
01-MAR-16      3
01-FEB-17      1
01-JAN-17      1
01-JAN-15      1
01-JAN-18      1
01-SEP-16      1
01-MAR-17      1
01-AUG-16      1
Name: NIBRS_MULTI_BIAS_START_DATE, dtype: int64
-------------------------------
NIBRS_OFF_ETH_START_DATE
01-APR-13    166
01-FEB-14     28
01-MAY-14      4
01-APR-14      4
01-FEB-15      2
01-JAN-15      2
01-MAR-14      2
01-JUL-14      2
01-AUG-14      1
01-SEP-15      1
01-FEB-13      1
01-OCT-14      1
01-MAR-17      1
01-MAR-15      1
01-NOV-15      1
01-JUN-14      1
01-FEB-17      1
Name: NIBRS_OFF_ETH_START_DATE, dtype: int64
-------------------------------
NIBRS_PARTICIPATED
Y    220
Name: NIBRS_PARTICIPATED, dtype: int64
-------------------------------
NIBRS_START_DATE
01-JAN-97    125
01-JAN-12     27
01-JAN-05      8
01-JAN-06      6
01-JAN-11      6
01-JAN-02      3
01-JAN-09      3
01-JAN-04      3
01-JAN-13      2
01-JAN-00      2
01-NOV-98      2
01-JAN-15      2
01-JAN-99      2
01-OCT-98      1
01-FEB-13      1
01-JAN-10      1
01-APR-00      1
01-JAN-08      1
01-JUN-97      1
01-OCT-04      1
01-JUL-03      1
01-MAY-12      1
01-JUL-13      1
01-DEC-14      1
01-JAN-98      1
01-JAN-01      1
01-APR-03      1
01-MAY-97      1
01-SEP-04      1
01-DEC-12      1
01-DEC-97      1
01-AUG-95      1
01-JAN-92      1
01-FEB-14      1
01-FEB-09      1
01-AUG-97      1
01-JAN-03      1
01-JUL-97      1
01-JUL-09      1
01-JAN-14      1
01-JAN-85      1
01-JUL-04      1
Name: NIBRS_START_DATE, dtype: int64
-------------------------------
ORI
CO0390100    1
CO0450000    1
CO0320000    1
CO0621100    1
CO0300000    1
            ..
CO0590300    1
CO0020000    1
CO0622000    1
CO0480100    1
CO0070300    1
Name: ORI, Length: 220, dtype: int64
-------------------------------
PARENT_POP_GROUP_CODE
7    65
6    50
8    44
5    20
9    15
2     9
4     7
3     7
1     3
Name: PARENT_POP_GROUP_CODE, dtype: int64
-------------------------------
PARENT_POP_GROUP_DESC
Cities under 2,500                  65
Cities from 2,500 thru 9,999        50
Non-MSA Counties                    44
Cities from 10,000 thru 24,999      20
MSA Counties                        15
Cities from 100,000 thru 249,000     9
Cities from 50,000 thru 99,000       7
Cities from 25,000 thru 49,999       7
All cities 250,000 or over           3
Name: PARENT_POP_GROUP_DESC, dtype: int64
-------------------------------
PARTICIPATED
Y    220
Name: PARTICIPATED, dtype: int64
-------------------------------
PED.FEMALE_CIVILIAN+PED.FEMALE_OFFICER
1      30
0      26
2      17
4      16
3      15
6       9
5       7
14      7
7       6
9       5
10      5
13      4
23      4
15      4
8       4
29      3
24      3
22      3
11      2
31      2
34      2
25      2
12      2
19      2
18      2
71      2
16      2
75      2
21      2
17      1
26      1
27      1
245     1
196     1
39      1
193     1
176     1
169     1
152     1
147     1
139     1
137     1
370     1
110     1
288     1
99      1
90      1
89      1
80      1
78      1
72      1
69      1
60      1
313     1
53      1
52      1
45      1
44      1
261     1
Name: PED.FEMALE_CIVILIAN+PED.FEMALE_OFFICER, dtype: int64
-------------------------------
PED.MALE_OFFICER+PED.MALE_CIVILIAN
8      12
4      11
7      10
3      10
5       8
       ..
329     1
87      1
90      1
182     1
46      1
Name: PED.MALE_OFFICER+PED.MALE_CIVILIAN, Length: 83, dtype: int64
-------------------------------
PE_REPORTED_FLAG
Y    212
N      8
Name: PE_REPORTED_FLAG, dtype: int64
-------------------------------
POPULATION
0         20
1432       2
912        2
25238      1
2815       1
          ..
1348       1
1858       1
70977      1
111416     1
745        1
Name: POPULATION, Length: 199, dtype: int64
-------------------------------
POPULATION_GROUP_CODE
7     65
6     50
8D    34
5     20
2      9
3      7
9B     7
8C     7
4      7
9A     3
8B     3
9C     3
9D     2
1C     2
1B     1
Name: POPULATION_GROUP_CODE, dtype: int64
-------------------------------
POPULATION_GROUP_DESC
Cities under 2,500                          65
Cities from 2,500 thru 9,999                50
Non-MSA counties under 10,000               34
Cities from 10,000 thru 24,999              20
Cities from 100,000 thru 249,000             9
Non-MSA counties from 10,000 thru 24,999     7
Cities from 25,000 thru 49,999               7
Cities from 50,000 thru 99,000               7
MSA counties from 25,000 thru 99,999         7
MSA counties from 10,000 thru 24,999         3
MSA counties 100,000 or over                 3
Non-MSA counties from 25,000 thru 99,999     3
Cities from 250,000 thru 499,999             2
MSA counties under 10,000                    2
Cities from 500,000 thru 999,999             1
Name: POPULATION_GROUP_DESC, dtype: int64
-------------------------------
POPULATION_GROUP_ID
11    65
10    50
16    34
9     20
6      9
20     7
15     7
8      7
7      7
21     3
19     3
14     3
22     2
5      2
4      1
Name: POPULATION_GROUP_ID, dtype: int64
-------------------------------
POP_SORT_ORDER
2    149
3     59
1     12
Name: POP_SORT_ORDER, dtype: int64
-------------------------------
PUBLISHABLE_FLAG
Y    220
Name: PUBLISHABLE_FLAG, dtype: int64
-------------------------------
PUB_AGENCY_NAME
University of Colorado:     4
Delta                       2
Alamosa                     2
Montrose                    2
Boulder                     2
                           ..
Idaho Springs               1
Wray                        1
Mountain View               1
Colorado School of Mines    1
Hotchkiss                   1
Name: PUB_AGENCY_NAME, Length: 209, dtype: int64
-------------------------------
PUB_AGENCY_UNIT
Boulder                   1
Colorado Springs          1
Health Sciences Center    1
Denver                    1
Name: PUB_AGENCY_UNIT, dtype: int64
-------------------------------
REGION_CODE
4    220
Name: REGION_CODE, dtype: int64
-------------------------------
REGION_DESC
Region IV    220
Name: REGION_DESC, dtype: int64
-------------------------------
REGION_NAME
West    220
Name: REGION_NAME, dtype: int64
-------------------------------
REPORTING_TYPE
I    220
Name: REPORTING_TYPE, dtype: int64
-------------------------------
SAI
COUCR0001    220
Name: SAI, dtype: int64
-------------------------------
STATE_ABBR
CO    220
Name: STATE_ABBR, dtype: int64
-------------------------------
STATE_ID
7    220
Name: STATE_ID, dtype: int64
-------------------------------
STATE_NAME
Colorado    220
Name: STATE_NAME, dtype: int64
-------------------------------
STATE_POSTAL_ABBR
CO    220
Name: STATE_POSTAL_ABBR, dtype: int64
-------------------------------
SUBMITTING_AGENCY_ID
23358    220
Name: SUBMITTING_AGENCY_ID, dtype: int64
-------------------------------
SUBMITTING_AGENCY_NAME
Colorado Bureau of Investigation Uniform Crime Reporting    220
Name: SUBMITTING_AGENCY_NAME, dtype: int64
-------------------------------
SUBURBAN_AREA_FLAG
N    137
Y     83
Name: SUBURBAN_AREA_FLAG, dtype: int64
-------------------------------
SUMMARY_RAPE_DEF
R    220
Name: SUMMARY_RAPE_DEF, dtype: int64
-------------------------------
UCR_AGENCY_NAME
BOULDER       2
ALAMOSA       2
GUNNISON      2
YUMA          2
MONTROSE      2
             ..
MINERAL       1
ROCKY FORD    1
ARAPAHOE      1
ADAMS         1
FOWLER        1
Name: UCR_AGENCY_NAME, Length: 212, dtype: int64
-------------------------------
YEARLY_AGENCY_ID
20102017    1
20972017    1
20622017    1
18772017    1
18682017    1
           ..
19192017    1
19102017    1
18802017    1
19572017    1
20372017    1
Name: YEARLY_AGENCY_ID, Length: 220, dtype: int64
-------------------------------

In [36]:
wcols = ["UCR_AGENCY_NAME","AGENCY_TYPE_NAME","ORI"]

display(agc.loc[:,wcols])
#agc.loc[agc["LEGACY_ORI"] != agc["ORI"]]

              UCR_AGENCY_NAME       AGENCY_TYPE_NAME        ORI
0                       ADAMS                 County  CO0010000
1                      AURORA                   City  CO0010100
2                    BRIGHTON                   City  CO0010200
3               COMMERCE CITY                   City  CO0010300
4                    THORNTON                   City  CO0010400
5                 WESTMINSTER                   City  CO0010500
6                  NORTHGLENN                   City  CO0010600
7             FEDERAL HEIGHTS                   City  CO0010800
8          UNIV OF CO: DENVER  University or College  CO0011100
9                     ALAMOSA                 County  CO0020000
10                    ALAMOSA                   City  CO0020100
11     ADAMS STATE UNIVERSITY  University or College  CO0020200
12                   ARAPAHOE                 County  CO0030000
13                  ENGLEWOOD                   City  CO0030100
14                  LITTLETON                   City  CO0030200
15                   SHERIDAN                   City  CO0030300
16                   GLENDALE                   City  CO0030400
17       CHERRY HILLS VILLAGE                   City  CO0030500
18                    BOW MAR                   City  CO0030600
19          GREENWOOD VILLAGE                   City  CO0030700
20           COLUMBINE VALLEY                   City  CO0030800
21      ARAPAHOE COMM COLLEGE  University or College  CO0030900
22                 CENTENNIAL                   City  CO0031100
23                  ARCHULETA                 County  CO0040000
24             PAGOSA SPRINGS                   City  CO0040100
25                       BACA                 County  CO0050000
26                      WALSH                   City  CO0050700
27                       BENT                 County  CO0060000
28                    BOULDER                 County  CO0070000
29                    BOULDER                   City  CO0070100
30                  LAFAYETTE                   City  CO0070300
31                   LONGMONT                   City  CO0070400
32        UNIV OF CO: BOULDER  University or College  CO0070500
33                 LOUISVILLE                   City  CO0070600
34                  NEDERLAND                   City  CO0070800
35                    CHAFFEE                 County  CO0080000
36                BUENA VISTA                   City  CO0080100
37                     SALIDA                   City  CO0080200
38                   CHEYENNE                 County  CO0090000
39                CLEAR CREEK                 County  CO0100000
40              IDAHO SPRINGS                   City  CO0100100
41                    CONEJOS                 County  CO0110000
42                    CROWLEY                 County  CO0130000
43                     CUSTER                 County  CO0140000
44                      DELTA                 County  CO0150000
45                      DELTA                   City  CO0150100
46                  HOTCHKISS                   City  CO0150300
47   AURARIA HIGHER EDUC CNTR  University or College  CO0160200
48   UN OF CO:HLTH SCIENCES C  University or College  CO0160400
49                    DOLORES                 County  CO0170000
50                    DOUGLAS                 County  CO0180000
51                CASTLE ROCK                   City  CO0180100
52                     PARKER                   City  CO0180500
53                  LONE TREE                   City  CO0180700
54                      EAGLE                 County  CO0190000
55                       VAIL                   City  CO0190100
56                      EAGLE                   City  CO0190200
57                     BASALT                   City  CO0190400
58                       AVON                   City  CO0190600
59                     ELBERT                 County  CO0200000
60                  ELIZABETH                   City  CO0200100
61                      KIOWA                   City  CO0200300
62                    EL PASO                 County  CO0210000
63           COLORADO SPRINGS                   City  CO0210100
64                   FOUNTAIN                   City  CO0210200
65            MANITOU SPRINGS                   City  CO0210300
66   U OF CO: COLORADO SPRNGS  University or College  CO0210400
67   PIKES PEAK COMMUNITY COL  University or College  CO0210500
68                PALMER LAKE                   City  CO0210600
69                   MONUMENT                   City  CO0210700
70                     CALHAN                   City  CO0211000
71                    FREMONT                 County  CO0220000
72                 CANON CITY                   City  CO0220100
73                   FLORENCE                   City  CO0220200
74                   GARFIELD                 County  CO0230000
75           GLENWOOD SPRINGS                   City  CO0230100
76                  PARACHUTE                   City  CO0230200
77                      RIFLE                   City  CO0230300
78                 CARBONDALE                   City  CO0230400
79                       SILT                   City  CO0230500
80                 NEW CASTLE                   City  CO0230600
81                     GILPIN                 County  CO0240000
82                 BLACK HAWK                   City  CO0240200
83                      GRAND                 County  CO0250000
84                     GRANBY                   City  CO0250100
85         FRASER/WINTER PARK                   City  CO0250400
86                   GUNNISON                 County  CO0260000
87                   GUNNISON                   City  CO0260100
88        MOUNT CRESTED BUTTE                   City  CO0260200
89              CRESTED BUTTE                   City  CO0260300
90                   HINSDALE                 County  CO0270000
91                   HUERFANO                 County  CO0280000
92                    JACKSON                 County  CO0290000
93                  JEFFERSON                 County  CO0300000
94                     ARVADA                   City  CO0300100
95                     GOLDEN                   City  CO0300200
96                  EDGEWATER                   City  CO0300300
97                   LAKEWOOD                   City  CO0300400
98                WHEAT RIDGE                   City  CO0300500
99                   LAKESIDE                   City  CO0300600
100                  MORRISON                   City  CO0300700
101        CO SCHOOL OF MINES  University or College  CO0300800
102             MOUNTAIN VIEW                   City  CO0300900
103  RED ROCKS COMMUNITY COLL  University or College  CO0301000
104                KIT CARSON                 County  CO0320000
105                BURLINGTON                   City  CO0320100
106                      LAKE                 County  CO0330000
107                 LEADVILLE                   City  CO0330100
108                  LA PLATA                 County  CO0340000
109                   DURANGO                   City  CO0340100
110                   IGNACIO                   City  CO0340300
111                  BAYFIELD                   City  CO0340400
112        FORT LEWIS COLLEGE  University or College  CO034019E
113  SOUTHWEST DRUG TASK FORC                  Other  CO0348000
114                   LARIMER                 County  CO0350000
115                ESTES PARK                   City  CO0350200
116              FORT COLLINS                   City  CO0350300
117                  LOVELAND                   City  CO0350400
118  CO ST UNIV, FORT COLLINS  University or College  CO0350500
119                   TIMNATH                   City  CO0351000
120                  TRINIDAD                   City  CO0360100
121                   LINCOLN                 County  CO0370000
122                     LIMON                   City  CO0370100
123                      HUGO                   City  CO0370200
124                     LOGAN                 County  CO0380000
125                  STERLING                   City  CO0380100
126                      MESA                 County  CO0390000
127            GRAND JUNCTION                   City  CO0390100
128                    FRUITA                   City  CO0390200
129                  PALISADE                   City  CO0390300
130                   MINERAL                 County  CO0400000
131                    MOFFAT                 County  CO0410000
132                     CRAIG                   City  CO0410100
133                 MONTEZUMA                 County  CO0420000
134                    CORTEZ                   City  CO0420100
135                    MANCOS                   City  CO0420200
136                  MONTROSE                 County  CO0430000
137                  MONTROSE                   City  CO0430100
138                    OLATHE                   City  CO0430400
139   DELTA MONTROSE DRUG TSK                  Other  CO0438000
140                    MORGAN                 County  CO0440000
141                     BRUSH                   City  CO0440100
142               FORT MORGAN                   City  CO0440200
143          LOG LANE VILLAGE                   City  CO0440400
144                     OTERO                 County  CO0450000
145                  LA JUNTA                   City  CO0450100
146                ROCKY FORD                   City  CO0450200
147                    FOWLER                   City  CO0450400
148                     OURAY                   City  CO0460100
149                      PARK                 County  CO0470000
150                  PHILLIPS                 County  CO0480000
151                   HOLYOKE                   City  CO0480100
152                    HAXTUN                   City  CO0480200
153                    PITKIN                 County  CO0490000
154                     ASPEN                   City  CO0490100
155          SNOWMASS VILLAGE                   City  CO0490200
156                   PROWERS                 County  CO0500000
157                     LAMAR                   City  CO0500100
158                    PUEBLO                 County  CO0510000
159                    PUEBLO                   City  CO0510100
160  CO MENTAL HEALTH INSTITU     Other State Agency  CO0510200
161                RIO BLANCO                 County  CO0520000
162                    MEEKER                   City  CO0520100
163                   RANGELY                   City  CO0520200
164                RIO GRANDE                 County  CO0530000
165               MONTE VISTA                   City  CO0530100
166                 DEL NORTE                   City  CO0530200
167                     ROUTT                 County  CO0540000
168         STEAMBOAT SPRINGS                   City  CO0540100
169                    HAYDEN                   City  CO0540200
170                 OAK CREEK                   City  CO0540300
171                  SAGUACHE                 County  CO0550000
172                    CENTER                   City  CO0550100
173                  SAN JUAN                 County  CO0560000
174                SAN MIGUEL                 County  CO0570000
175                 TELLURIDE                   City  CO0570100
176                  SEDGWICK                 County  CO0580000
177                    SUMMIT                 County  CO0590000
178              BRECKENRIDGE                   City  CO0590100
179                    DILLON                   City  CO0590200
180              SILVERTHORNE                   City  CO0590300
181                    FRISCO                   City  CO0590400
182                BLUE RIVER                   City  CO0590500
183                    TELLER                 County  CO0600000
184             WOODLAND PARK                   City  CO0600100
185             CRIPPLE CREEK                   City  CO0600200
186                WASHINGTON                 County  CO0610000
187                      WELD                 County  CO0620000
188               FORT LUPTON                   City  CO0620100
189                   GREELEY                   City  CO0620200
190                     EATON                   City  CO0620300
191                     EVANS                   City  CO0620400
192                  LA SALLE                   City  CO0620500
193                   WINDSOR                   City  CO0620600
194                      ERIE                   City  CO0620700
195                    DACONO                   City  CO0620800
196                    KERSEY                   City  CO0620900
197                 JOHNSTOWN                   City  CO0621000
198                  MILLIKEN                   City  CO0621100
199                      AULT                   City  CO0621200
200               PLATTEVILLE                   City  CO0621300
201  UNIV OF NORTHERN COLORAD  University or College  CO0621600
202                 FREDERICK                   City  CO0621700
203                 FIRESTONE                   City  CO0621800
204                  LOCHBUIE                   City  CO0622000
205                      YUMA                 County  CO0630000
206                      WRAY                   City  CO0630100
207                      YUMA                   City  CO0630200
208                BROOMFIELD                   City  CO0640100
209  COLORADO BUREAU OF INVES     Other State Agency  COCBI0000
210     COLORADO STATE PATROL           State Police  COCSP0000
211                    DENVER                   City  CODPD0000
212                      MEAD                   City  CO0622600
213               GARDEN CITY                   City  CO0622700
214    AIMS COMMUNITY COLLEGE  University or College  CO0622900
215                 SEVERANCE                   City  CO0622800
216                    HUDSON                   City  CO0622400
217          MOUNTAIN VILLAGE                   City  CO0570300
218  ALL CRIMES ENFORCEMENT T                  Other  CO0418000
219                    GYPSUM                   City  CO0191000

In [31]:
display(agc["PUB_AGENCY_NAME"].value_counts())

University of Colorado:                    4
Alamosa                                    2
Yuma                                       2
Eagle                                      2
Boulder                                    2
Montrose                                   2
Gunnison                                   2
Pueblo                                     2
Delta                                      2
Limon                                      1
Federal Heights                            1
Mancos                                     1
Edgewater                                  1
Morgan                                     1
La Salle                                   1
Burlington                                 1
Brighton                                   1
Lincoln                                    1
Lamar                                      1
Durango                                    1
Louisville                                 1
Pikes Peak Community College               1
Centennial                                 1
Greenwood Village                          1
Bow Mar                                    1
Montezuma                                  1
Gilpin                                     1
Fort Lewis College                         1
Center                                     1
Commerce City                              1
Red Rocks Community College                1
Cheyenne                                   1
Fraser/Winter Park                         1
Adams State University                     1
Snowmass Village                           1
Golden                                     1
Auraria Higher Education Center            1
Garfield                                   1
Buena Vista                                1
Colorado Mental Health Institute           1
Longmont                                   1
Walsh                                      1
Adams                                      1
Gypsum                                     1
Timnath                                    1
Canon City                                 1
Grand                                      1
San Juan                                   1
Saguache                                   1
Cripple Creek                              1
San Miguel                                 1
Ignacio                                    1
Glenwood Springs                           1
Hotchkiss                                  1
Conejos                                    1
Silt                                       1
Phillips                                   1
Nederland                                  1
Fountain                                   1
Lakeside                                   1
Haxtun                                     1
Logan                                      1
Salida                                     1
Fruita                                     1
Arapahoe                                   1
Loveland                                   1
Monte Vista                                1
Mountain Village                           1
Columbine Valley                           1
Blue River                                 1
All Crimes Enforcement Team                1
Pagosa Springs                             1
Kit Carson                                 1
Arvada                                     1
Colorado State University, Fort Collins    1
Vail                                       1
Moffat                                     1
El Paso                                    1
Arapahoe Community College                 1
Thornton                                   1
Hugo                                       1
Otero                                      1
Mesa                                       1
Lake                                       1
Windsor                                    1
Basalt                                     1
Calhan                                     1
Jackson                                    1
Florence                                   1
Douglas                                    1
Crowley                                    1
Hudson                                     1
Dacono                                     1
Sedgwick                                   1
Eaton                                      1
Sterling                                   1
Severance                                  1
Aims Community College                     1
Fowler                                     1
State Patrol                               1
Rio Blanco                                 1
Northglenn                                 1
Fort Morgan                                1
Summit                                     1
Hinsdale                                   1
Meeker                                     1
Avon                                       1
Pitkin                                     1
Mount Crested Butte                        1
Ouray                                      1
Grand Junction                             1
Delta Montrose Drug Task Force             1
Breckenridge                               1
Elizabeth                                  1
Holyoke                                    1
Lafayette                                  1
Frisco                                     1
Huerfano                                   1
Fort Lupton                                1
Oak Creek                                  1
Castle Rock                                1
Telluride                                  1
Woodland Park                              1
Kersey                                     1
Erie                                       1
Manitou Springs                            1
Prowers                                    1
Bayfield                                   1
Black Hawk                                 1
Washington                                 1
Mountain View                              1
Wray                                       1
Steamboat Springs                          1
Aurora                                     1
Del Norte                                  1
La Plata                                   1
Johnstown                                  1
Crested Butte                              1
Cortez                                     1
Park                                       1
Westminster                                1
Rangely                                    1
Wheat Ridge                                1
Parker                                     1
Fremont                                    1
Custer                                     1
Routt                                      1
Trinidad                                   1
Leadville                                  1
Morrison                                   1
Dolores                                    1
Bent                                       1
University of Northern Colorado            1
Granby                                     1
Elbert                                     1
Colorado School of Mines                   1
Englewood                                  1
Greeley                                    1
Carbondale                                 1
Fort Collins                               1
Firestone                                  1
Teller                                     1
Ault                                       1
Frederick                                  1
Denver                                     1
Jefferson                                  1
La Junta                                   1
Lakewood                                   1
Dillon                                     1
Olathe                                     1
New Castle                                 1
Brush                                      1
Mineral                                    1
Colorado Bureau of Investigation           1
Parachute                                  1
Aspen                                      1
Rocky Ford                                 1
Palmer Lake                                1
Colorado Springs                           1
Platteville                                1
Lone Tree                                  1
Kiowa                                      1
Craig                                      1
Evans                                      1
Sheridan                                   1
Hayden                                     1
Rio Grande                                 1
Baca                                       1
Clear Creek                                1
Littleton                                  1
Broomfield                                 1
Glendale                                   1
Monument                                   1
Weld                                       1
Archuleta                                  1
Garden City                                1
Rifle                                      1
Cherry Hills Village                       1
Mead                                       1
Milliken                                   1
Idaho Springs                              1
Southwest Drug Task Force                  1
Chaffee                                    1
Lochbuie                                   1
Silverthorne                               1
Log Lane Village                           1
Estes Park                                 1
Larimer                                    1
Palisade                                   1
Name: PUB_AGENCY_NAME, dtype: int64

In [45]:
off.shape

(328469, 30)

## Merge Agency info

In [14]:
off = off.merge(agc[["UCR_AGENCY_NAME","AGENCY_TYPE_NAME","ORI","AGENCY_ID"]],on="AGENCY_ID",how="left")

In [15]:
off.shape

(328469, 33)

In [48]:
for col in sorted(off.columns):
    print(col)

AGENCY_ID
AGENCY_TYPE_NAME
ATTEMPT_COMPLETE_FLAG
CARGO_THEFT_FLAG
CLEARED_EXCEPT_DATE
CLEARED_EXCEPT_ID
CRIME_AGAINST
CT_FLAG
DATA_HOME
DATA_YEAR_x
DATA_YEAR_y
DID
HC_CODE
HC_FLAG
INCIDENT_DATE
INCIDENT_HOUR
INCIDENT_ID
INCIDENT_STATUS
LOCATION_ID
METHOD_ENTRY_CODE
NIBRS_MONTH_ID
NUM_PREMISES_ENTERED
OFFENSE_CATEGORY_NAME
OFFENSE_CODE
OFFENSE_GROUP
OFFENSE_ID
OFFENSE_NAME
OFFENSE_TYPE_ID
ORI
ORIG_FORMAT
REPORT_DATE_FLAG
SUBMISSION_DATE
UCR_AGENCY_NAME

### Fix Dupe Date Columns

In [18]:
print(off["DATA_YEAR_x"].value_counts())
print(off["DATA_YEAR_y"].value_counts())

2017    328469
Name: DATA_YEAR_x, dtype: int64
2017    328469
Name: DATA_YEAR_y, dtype: int64

In [21]:
off.rename(columns={"DATA_YEAR_x":"YEAR"},inplace=True)
off.drop(axis=1,columns="DATA_YEAR_y",inplace=True)
off.head()

,YEAR,OFFENSE_ID,INCIDENT_ID,OFFENSE_TYPE_ID,ATTEMPT_COMPLETE_FLAG,LOCATION_ID,NUM_PREMISES_ENTERED,METHOD_ENTRY_CODE,AGENCY_ID,NIBRS_MONTH_ID,CARGO_THEFT_FLAG,SUBMISSION_DATE,INCIDENT_DATE,REPORT_DATE_FLAG,INCIDENT_HOUR,CLEARED_EXCEPT_ID,CLEARED_EXCEPT_DATE,INCIDENT_STATUS,DATA_HOME,ORIG_FORMAT,DID,OFFENSE_CODE,OFFENSE_NAME,CRIME_AGAINST,CT_FLAG,HC_FLAG,HC_CODE,OFFENSE_CATEGORY_NAME,OFFENSE_GROUP,UCR_AGENCY_NAME,AGENCY_TYPE_NAME,ORI
0,2017,120579056,97509596,14,C,13,NaN,NaN,1840,7795544,N,20-AUG-18,07-OCT-17,NaN,9.0,6,NaN,0,C,F,20353233,23F,Theft From Motor Vehicle,Property,Y,N,NaN,Larceny/Theft Offenses,A,ENGLEWOOD,City,CO0030100
1,2017,120579059,97509596,5,C,13,NaN,NaN,1840,7795544,N,20-AUG-18,07-OCT-17,NaN,9.0,6,NaN,0,C,F,20353233,290,Destruction/Damage/Vandalism of Property,Property,N,Y,11.0,Destruction/Damage/Vandalism of Property,A,ENGLEWOOD,City,CO0030100
2,2017,120579086,97509608,21,C,30,NaN,NaN,1840,7891921,N,20-AUG-18,22-DEC-17,NaN,17.0,6,NaN,0,C,F,20353293,240,Motor Vehicle Theft,Property,Y,Y,7.0,Motor Vehicle Theft,A,ENGLEWOOD,City,CO0030100
3,2017,119761875,96802224,45,C,20,NaN,NaN,1828,7564685,N,20-AUG-18,11-JAN-17,NaN,14.0,6,NaN,0,C,F,19019056,23H,All Other Larceny,Property,Y,N,NaN,Larceny/Theft Offenses,A,BRIGHTON,City,CO0010200
4,2017,119761953,96802320,23,C,8,NaN,NaN,1828,7564685,NaN,20-AUG-18,21-JAN-17,NaN,19.0,6,NaN,0,C,F,19019142,23C,Shoplifting,Property,N,N,NaN,Larceny/Theft Offenses,A,BRIGHTON,City,CO0010200

### Merge Cleared Except descriptions

In [24]:
clearExcept = pd.read_csv("data/2017/NIBRS_CLEARED_EXCEPT.csv")

In [25]:
clearExcept.head()

,CLEARED_EXCEPT_ID,CLEARED_EXCEPT_CODE,CLEARED_EXCEPT_NAME,CLEARED_EXCEPT_DESC
0,1,A,Death of Offender,Death of Offender
1,2,B,Prosecution Declined,Prosecution Declined (by the prosecutor for a ...
2,3,C,In Custody of Other Jurisdiction,In Custody of Other Jurisdiction
3,4,D,Victim Refused to Cooperate,Victim Refused to Cooperate (in the prosecution)
4,5,E,Juvenile/No Custody,Juvenile/No Custody (the handling of a juvenil...

In [26]:
off.shape

(328469, 32)

In [27]:
off = off.merge(clearExcept[["CLEARED_EXCEPT_DESC","CLEARED_EXCEPT_ID"]],on="CLEARED_EXCEPT_ID",how="left")

In [28]:
off.shape

(328469, 33)

In [30]:
off["CLEARED_EXCEPT_DESC"].isna().sum()

0

In [29]:
off["CLEARED_EXCEPT_DESC"].value_counts()

Not Applicable (not cleared exceptionally)                                                                                                                                                                                      319282
Victim Refused to Cooperate (in the prosecution)                                                                                                                                                                                  4332
Prosecution Declined (by the prosecutor for a reason other than lack of probable cause)                                                                                                                                           3533
In Custody of Other Jurisdiction                                                                                                                                                                                                   869
Juvenile/No Custody (the handling of a juvenile without taking him/her into custody, but rather by oral or written notice given to the parents or legal guardian in a case involving a minor offense, such as petty larceny)       286
Death of Offender                                                                                                                                                                                                                  167
Name: CLEARED_EXCEPT_DESC, dtype: int64

In [34]:
off.drop(axis=1,columns="CLEARED_EXCEPT_ID",inplace=True)

In [35]:
off.shape

(328469, 32)

### Hate Crime Codes

In [36]:
## HC CODE - in description for this data, it is noted that this comes from 
## Hate Crime Technical Specification, and this is only available by request from 
## ucr@fbi.gov - so this is on hold
print(off["HC_CODE"].value_counts())
print(off["HC_FLAG"].value_counts())

11.0    44538
9.0     30330
5.0     22141
7.0     21682
4.0     10337
2.0      6080
10.0     4033
3.0      3833
8.0      1048
1.0       203
12.0       47
13.0        7
Name: HC_CODE, dtype: int64
Y    218673
N    109796
Name: HC_FLAG, dtype: int64

### Location ID

In [38]:
locType = pd.read_csv("data/2017/NIBRS_LOCATION_TYPE.csv")

In [41]:
off.shape

(328469, 32)

In [42]:
off = off.merge(locType[["LOCATION_ID","LOCATION_NAME"]],on="LOCATION_ID",how="left")

In [43]:
off.shape

(328469, 33)

In [ ]:
off["LOCATION_NAME"].value_counts()

In [46]:
off.drop(axis=1,columns="LOCATION_ID",inplace=True)
off.shape

(328469, 32)

### Method Entry

In [ ]:
methodEntry = pd.read_csv("data/2017/NIBRS_LOCATION_TYPE.csv")

In [47]:
off["METHOD_ENTRY_CODE"].value_counts()

F    11952
N    10189
Name: METHOD_ENTRY_CODE, dtype: int64

### NIBRS Month ID

In [ ]:
# This ties to table NIBRS_month.csv, and this
# table has 15 columns, and it mostly looks like interncally
# usefull info.  I will include this as a table in the dataset
# but NOT merge it into this data.

In [49]:
off["NIBRS_MONTH_ID"].value_counts()

7745845    4879
7725940    4633
7697315    4588
7758078    4532
7781362    4496
           ...
7757929       1
7667921       1
7581037       1
7579290       1
7798361       1
Name: NIBRS_MONTH_ID, Length: 2385, dtype: int64

## OUTPUT DATA

In [50]:
off.head()

,YEAR,OFFENSE_ID,INCIDENT_ID,OFFENSE_TYPE_ID,ATTEMPT_COMPLETE_FLAG,NUM_PREMISES_ENTERED,METHOD_ENTRY_CODE,AGENCY_ID,NIBRS_MONTH_ID,CARGO_THEFT_FLAG,SUBMISSION_DATE,INCIDENT_DATE,REPORT_DATE_FLAG,INCIDENT_HOUR,CLEARED_EXCEPT_DATE,INCIDENT_STATUS,DATA_HOME,ORIG_FORMAT,DID,OFFENSE_CODE,OFFENSE_NAME,CRIME_AGAINST,CT_FLAG,HC_FLAG,HC_CODE,OFFENSE_CATEGORY_NAME,OFFENSE_GROUP,UCR_AGENCY_NAME,AGENCY_TYPE_NAME,ORI,CLEARED_EXCEPT_DESC,LOCATION_NAME
0,2017,120579056,97509596,14,C,NaN,NaN,1840,7795544,N,20-AUG-18,07-OCT-17,NaN,9.0,NaN,0,C,F,20353233,23F,Theft From Motor Vehicle,Property,Y,N,NaN,Larceny/Theft Offenses,A,ENGLEWOOD,City,CO0030100,Not Applicable (not cleared exceptionally),Highway/Road/Alley/Street/Sidewalk
1,2017,120579059,97509596,5,C,NaN,NaN,1840,7795544,N,20-AUG-18,07-OCT-17,NaN,9.0,NaN,0,C,F,20353233,290,Destruction/Damage/Vandalism of Property,Property,N,Y,11.0,Destruction/Damage/Vandalism of Property,A,ENGLEWOOD,City,CO0030100,Not Applicable (not cleared exceptionally),Highway/Road/Alley/Street/Sidewalk
2,2017,120579086,97509608,21,C,NaN,NaN,1840,7891921,N,20-AUG-18,22-DEC-17,NaN,17.0,NaN,0,C,F,20353293,240,Motor Vehicle Theft,Property,Y,Y,7.0,Motor Vehicle Theft,A,ENGLEWOOD,City,CO0030100,Not Applicable (not cleared exceptionally),Auto Dealership New/Used
3,2017,119761875,96802224,45,C,NaN,NaN,1828,7564685,N,20-AUG-18,11-JAN-17,NaN,14.0,NaN,0,C,F,19019056,23H,All Other Larceny,Property,Y,N,NaN,Larceny/Theft Offenses,A,BRIGHTON,City,CO0010200,Not Applicable (not cleared exceptionally),Residence/Home
4,2017,119761953,96802320,23,C,NaN,NaN,1828,7564685,NaN,20-AUG-18,21-JAN-17,NaN,19.0,NaN,0,C,F,19019142,23C,Shoplifting,Property,N,N,NaN,Larceny/Theft Offenses,A,BRIGHTON,City,CO0010200,Not Applicable (not cleared exceptionally),Department/Discount Store

In [51]:
off.to_csv("incidents-2017.csv",index=False)

In [49]:
display(off.head())

,DATA_YEAR_x,OFFENSE_ID,INCIDENT_ID,OFFENSE_TYPE_ID,ATTEMPT_COMPLETE_FLAG,LOCATION_ID,NUM_PREMISES_ENTERED,METHOD_ENTRY_CODE,DATA_YEAR_y,AGENCY_ID,NIBRS_MONTH_ID,CARGO_THEFT_FLAG,SUBMISSION_DATE,INCIDENT_DATE,REPORT_DATE_FLAG,INCIDENT_HOUR,CLEARED_EXCEPT_ID,CLEARED_EXCEPT_DATE,INCIDENT_STATUS,DATA_HOME,ORIG_FORMAT,DID,OFFENSE_CODE,OFFENSE_NAME,CRIME_AGAINST,CT_FLAG,HC_FLAG,HC_CODE,OFFENSE_CATEGORY_NAME,OFFENSE_GROUP,UCR_AGENCY_NAME,AGENCY_TYPE_NAME,ORI
0,2017,120579056,97509596,14,C,13,NaN,NaN,2017,1840,7795544,N,20-AUG-18,07-OCT-17,NaN,9.0,6,NaN,0,C,F,20353233,23F,Theft From Motor Vehicle,Property,Y,N,NaN,Larceny/Theft Offenses,A,ENGLEWOOD,City,CO0030100
1,2017,120579059,97509596,5,C,13,NaN,NaN,2017,1840,7795544,N,20-AUG-18,07-OCT-17,NaN,9.0,6,NaN,0,C,F,20353233,290,Destruction/Damage/Vandalism of Property,Property,N,Y,11.0,Destruction/Damage/Vandalism of Property,A,ENGLEWOOD,City,CO0030100
2,2017,120579086,97509608,21,C,30,NaN,NaN,2017,1840,7891921,N,20-AUG-18,22-DEC-17,NaN,17.0,6,NaN,0,C,F,20353293,240,Motor Vehicle Theft,Property,Y,Y,7.0,Motor Vehicle Theft,A,ENGLEWOOD,City,CO0030100
3,2017,119761875,96802224,45,C,20,NaN,NaN,2017,1828,7564685,N,20-AUG-18,11-JAN-17,NaN,14.0,6,NaN,0,C,F,19019056,23H,All Other Larceny,Property,Y,N,NaN,Larceny/Theft Offenses,A,BRIGHTON,City,CO0010200
4,2017,119761953,96802320,23,C,8,NaN,NaN,2017,1828,7564685,NaN,20-AUG-18,21-JAN-17,NaN,19.0,6,NaN,0,C,F,19019142,23C,Shoplifting,Property,N,N,NaN,Larceny/Theft Offenses,A,BRIGHTON,City,CO0010200

In [27]:
df = pd.read_csv("crimeCO-1974-2023.csv")
df.loc[(df["ori"] == "CO0010000") & (df["year"] == 2021)].head()

,agency,ori,year,aggravatedAssault,allOtherOffensesExceptTraffic,arson,burglary,curfewLoiteringLawViolations,disorderlyConduct,drivingUnderTheInfluence,...,prostitutionAndCommercializedVice,rape,robbery,sexOffensesExceptRapeAndProstitutionAndCommercializedVice,simpleAssault,stolenPropertyBuyingReceivingPossessing,suspicion,vagrancy,vandalism,weaponsCarryingPossessingEtc
42,Adams County Sheriff's Office,CO0010000,2021,137,4979,2,42,0,36,174,...,0,2,12,10,185,26,0,0,73,58

In [23]:
off.groupby(["UCR_AGENCY_NAME","OFFENSE_NAME"]).count()

                                                             DATA_YEAR_x  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                   301
                All Other Larceny                                    467
                Animal Cruelty                                        12
                Arson                                                 36
                Assisting or Promoting Prostitution                    6
...                                                                  ...
YUMA            Theft From Building                                    8
                Theft From Coin-Operated Machine or Device             1
                Theft From Motor Vehicle                               1
                Theft of Motor Vehicle Parts or Accessories            1
                Weapon Law Violations                                  1

                                                             OFFENSE_ID  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                  301
                All Other Larceny                                   467
                Animal Cruelty                                       12
                Arson                                                36
                Assisting or Promoting Prostitution                   6
...                                                                 ...
YUMA            Theft From Building                                   8
                Theft From Coin-Operated Machine or Device            1
                Theft From Motor Vehicle                              1
                Theft of Motor Vehicle Parts or Accessories           1
                Weapon Law Violations                                 1

                                                             INCIDENT_ID  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                   301
                All Other Larceny                                    467
                Animal Cruelty                                        12
                Arson                                                 36
                Assisting or Promoting Prostitution                    6
...                                                                  ...
YUMA            Theft From Building                                    8
                Theft From Coin-Operated Machine or Device             1
                Theft From Motor Vehicle                               1
                Theft of Motor Vehicle Parts or Accessories            1
                Weapon Law Violations                                  1

                                                             OFFENSE_TYPE_ID  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                       301
                All Other Larceny                                        467
                Animal Cruelty                                            12
                Arson                                                     36
                Assisting or Promoting Prostitution                        6
...                                                                      ...
YUMA            Theft From Building                                        8
                Theft From Coin-Operated Machine or Device                 1
                Theft From Motor Vehicle                                   1
                Theft of Motor Vehicle Parts or Accessories                1
                Weapon Law Violations                                      1

                                                             ATTEMPT_COMPLETE_FLAG  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                             301
                All Other Larceny                                              467
                Animal Cruelty                                                  12
                Arson                                                           36
                Assisting or Promoting Prostitution                              6
...                                                                            ...
YUMA            Theft From Building                                              8
                Theft From Coin-Operated Machine or Device                       1
                Theft From Motor Vehicle                                         1
                Theft of Motor Vehicle Parts or Accessories                      1
                Weapon Law Violations                                            1

                                                             LOCATION_ID  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                   301
                All Other Larceny                                    467
                Animal Cruelty                                        12
                Arson                                                 36
                Assisting or Promoting Prostitution                    6
...                                                                  ...
YUMA            Theft From Building                                    8
                Theft From Coin-Operated Machine or Device             1
                Theft From Motor Vehicle                               1
                Theft of Motor Vehicle Parts or Accessories            1
                Weapon Law Violations                                  1

                                                             NUM_PREMISES_ENTERED  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                              0
                All Other Larceny                                               0
                Animal Cruelty                                                  0
                Arson                                                           0
                Assisting or Promoting Prostitution                             0
...                                                                           ...
YUMA            Theft From Building                                             0
                Theft From Coin-Operated Machine or Device                      0
                Theft From Motor Vehicle                                        0
                Theft of Motor Vehicle Parts or Accessories                     0
                Weapon Law Violations                                           0

                                                             METHOD_ENTRY_CODE  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                           0
                All Other Larceny                                            0
                Animal Cruelty                                               0
                Arson                                                        0
                Assisting or Promoting Prostitution                          0
...                                                                        ...
YUMA            Theft From Building                                          0
                Theft From Coin-Operated Machine or Device                   0
                Theft From Motor Vehicle                                     0
                Theft of Motor Vehicle Parts or Accessories                  0
                Weapon Law Violations                                        0

                                                             DATA_YEAR_y  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                   301
                All Other Larceny                                    467
                Animal Cruelty                                        12
                Arson                                                 36
                Assisting or Promoting Prostitution                    6
...                                                                  ...
YUMA            Theft From Building                                    8
                Theft From Coin-Operated Machine or Device             1
                Theft From Motor Vehicle                               1
                Theft of Motor Vehicle Parts or Accessories            1
                Weapon Law Violations                                  1

                                                             AGENCY_ID  ...  \
UCR_AGENCY_NAME OFFENSE_NAME                                            ...
ADAMS           Aggravated Assault                                 301  ...
                All Other Larceny                                  467  ...
                Animal Cruelty                                      12  ...
                Arson                                               36  ...
                Assisting or Promoting Prostitution                  6  ...
...                                                                ...  ...
YUMA            Theft From Building                                  8  ...
                Theft From Coin-Operated Machine or Device           1  ...
                Theft From Motor Vehicle                             1  ...
                Theft of Motor Vehicle Parts or Accessories          1  ...
                Weapon Law Violations                                1  ...

                                                             NIBRS_LEOKA_START_DATE  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                              301
                All Other Larceny                                               467
                Animal Cruelty                                                   12
                Arson                                                            36
                Assisting or Promoting Prostitution                               6
...                                                                             ...
YUMA            Theft From Building                                               8
                Theft From Coin-Operated Machine or Device                        1
                Theft From Motor Vehicle                                          1
                Theft of Motor Vehicle Parts or Accessories                       1
                Weapon Law Violations                                             1

                                                             NIBRS_CT_START_DATE  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                           301
                All Other Larceny                                            467
                Animal Cruelty                                                12
                Arson                                                         36
                Assisting or Promoting Prostitution                            6
...                                                                          ...
YUMA            Theft From Building                                            8
                Theft From Coin-Operated Machine or Device                     1
                Theft From Motor Vehicle                                       1
                Theft of Motor Vehicle Parts or Accessories                    1
                Weapon Law Violations                                          1

                                                             NIBRS_MULTI_BIAS_START_DATE  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                                   301
                All Other Larceny                                                    467
                Animal Cruelty                                                        12
                Arson                                                                 36
                Assisting or Promoting Prostitution                                    6
...                                                                                  ...
YUMA            Theft From Building                                                    8
                Theft From Coin-Operated Machine or Device                             1
                Theft From Motor Vehicle                                               1
                Theft of Motor Vehicle Parts or Accessories                            1
                Weapon Law Violations                                                  1

                                                             NIBRS_OFF_ETH_START_DATE  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                                301
                All Other Larceny                                                 467
                Animal Cruelty                                                     12
                Arson                                                              36
                Assisting or Promoting Prostitution                                 6
...                                                                               ...
YUMA            Theft From Building                                                 8
                Theft From Coin-Operated Machine or Device                          1
                Theft From Motor Vehicle                                            1
                Theft of Motor Vehicle Parts or Accessories                         1
                Weapon Law Violations                                               1

                                                             COVERED_FLAG  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                    301
                All Other Larceny                                     467
                Animal Cruelty                                         12
                Arson                                                  36
                Assisting or Promoting Prostitution                     6
...                                                                   ...
YUMA            Theft From Building                                     8
                Theft From Coin-Operated Machine or Device              1
                Theft From Motor Vehicle                                1
                Theft of Motor Vehicle Parts or Accessories             1
                Weapon Law Violations                                   1

                                                             COUNTY_NAME  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                   301
                All Other Larceny                                    467
                Animal Cruelty                                        12
                Arson                                                 36
                Assisting or Promoting Prostitution                    6
...                                                                  ...
YUMA            Theft From Building                                    8
                Theft From Coin-Operated Machine or Device             1
                Theft From Motor Vehicle                               1
                Theft of Motor Vehicle Parts or Accessories            1
                Weapon Law Violations                                  1

                                                             MSA_NAME  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                301
                All Other Larceny                                 467
                Animal Cruelty                                     12
                Arson                                              36
                Assisting or Promoting Prostitution                 6
...                                                               ...
YUMA            Theft From Building                                 8
                Theft From Coin-Operated Machine or Device          1
                Theft From Motor Vehicle                            1
                Theft of Motor Vehicle Parts or Accessories         1
                Weapon Law Violations                               1

                                                             PUBLISHABLE_FLAG  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                        301
                All Other Larceny                                         467
                Animal Cruelty                                             12
                Arson                                                      36
                Assisting or Promoting Prostitution                         6
...                                                                       ...
YUMA            Theft From Building                                         8
                Theft From Coin-Operated Machine or Device                  1
                Theft From Motor Vehicle                                    1
                Theft of Motor Vehicle Parts or Accessories                 1
                Weapon Law Violations                                       1

                                                             PARTICIPATED  \
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                    301
                All Other Larceny                                     467
                Animal Cruelty                                         12
                Arson                                                  36
                Assisting or Promoting Prostitution                     6
...                                                                   ...
YUMA            Theft From Building                                     8
                Theft From Coin-Operated Machine or Device              1
                Theft From Motor Vehicle                                1
                Theft of Motor Vehicle Parts or Accessories             1
                Weapon Law Violations                                   1

                                                             NIBRS_PARTICIPATED
UCR_AGENCY_NAME OFFENSE_NAME
ADAMS           Aggravated Assault                                          301
                All Other Larceny                                           467
                Animal Cruelty                                               12
                Arson                                                        36
                Assisting or Promoting Prostitution                           6
...                                                                         ...
YUMA            Theft From Building                                           8
                Theft From Coin-Operated Machine or Device                    1
                Theft From Motor Vehicle                                      1
                Theft of Motor Vehicle Parts or Accessories                   1
                Weapon Law Violations                                         1

[4538 rows x 86 columns]

## CIM Data

### Crime Offenses by Police District 2001-2016 in Colorado

In [70]:
offCIM = pd.read_csv("https://data.colorado.gov/api/views/ya69-n6ta/rows.csv?accessType=DOWNLOAD")

In [74]:
offCIM.columns

Index(['year', 'policeDistrict', 'type', 'subType', 'count'], dtype='object')

In [75]:
offCIM["subType"].value_counts()

Attempted                   7815
Knife/Cutting Instrument    6898
Other Dangerous Weapon      6898
Hands/Feet/Fist             3449
Firearm                     3449
Unlawful Entry              3449
Other                       3449
By Firearm                  3449
Truck                       3449
Forced Entry                3449
Auto                        3449
StrongArm                   3449
Other Assaults              3449
By Force                     917
Name: subType, dtype: int64

In [73]:
df.columns

Index(['Agency', 'data_year', 'Aggravated Assault',
       'All Other Offenses (Except Traffic)', 'Arson', 'Burglary',
       'Curfew and Loitering Law Violations', 'Disorderly Conduct',
       'Driving Under the Influence', 'Drug Abuse Violations - Grand Total',
       'Drunkenness', 'Embezzlement', 'Forgery and Counterfeiting', 'Fraud',
       'Gambling - Total', 'Human Trafficking - Commercial Sex Acts',
       'Human Trafficking - Involuntary Servitude', 'Larceny - Theft',
       'Liquor Laws', 'Manslaughter by Negligence', 'Motor Vehicle Theft',
       'Murder and Nonnegligent Manslaughter',
       'Offenses Against the Family and Children',
       'Prostitution and Commercialized Vice', 'Rape', 'Robbery',
       'Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)',
       'Simple Assault', 'Stolen Property: Buying, Receiving, Possessing',
       'Suspicion', 'Vagrancy', 'Vandalism',
       'Weapons: Carrying, Possessing, Etc.'],
      dtype='object')

In [55]:
offCIM["policeDistrict"].value_counts()

Montezuma County Sheriff      410
Pueblo PD                     410
Summit County Sheriff         387
Bent County Sheriff           364
Baca County Sheriff           364
                             ...
Colorado Attorney General       3
Collbran PD                     2
Univ. Southern Colorado PD      2
Sanford PD                      2
Summit County Task Force        1
Name: policeDistrict, Length: 284, dtype: int64

In [42]:
offCIM["subType"].value_counts()

Attempted                   7815
Other Dangerous Weapon      6898
Knife/Cutting Instrument    6898
Auto                        3449
Truck                       3449
Other Assaults              3449
Forced Entry                3449
By Firearm                  3449
Other                       3449
Hands/Feet/Fist             3449
Firearm                     3449
Unlawful Entry              3449
StrongArm                   3449
By Force                     917
Name: subType, dtype: int64

### Crime Arrests by Police District 2001-2016 in Colorado

In [76]:
offArrCIM = pd.read_csv("https://data.colorado.gov/api/views/2e5i-5hfy/rows.csv?accessType=DOWNLOAD")

In [77]:
offArrCIM.head()

,year,adultCount,juvenileCount,type,policeDistrict
0,2015,0.0,0.0,Murder Non Negligent Manslaughter,7th Judicial District Drug Task Force
1,2015,0.0,0.0,Rape,7th Judicial District Drug Task Force
2,2015,0.0,0.0,Robbery,7th Judicial District Drug Task Force
3,2015,0.0,0.0,Aggravated Assault,7th Judicial District Drug Task Force
4,2015,0.0,0.0,Burglary,7th Judicial District Drug Task Force

In [81]:
offArrCIM["policeDistrict"].value_counts()

Montezuma County Sheriff      486
Pueblo PD                     486
Summit County Sheriff         459
Lafayette PD                  432
Grand Junction PD             432
                             ...
La Veta Marshal                 2
Collbran PD                     2
Sanford PD                      2
Univ. Southern Colorado PD      2
Summit County Task Force        1
Name: policeDistrict, Length: 284, dtype: int64

In [84]:
offArrCIM.loc[offArrCIM[["policeDistrict","type"]].str.contains("Adams County")]

,year,adultCount,juvenileCount,type,policeDistrict
594,2015,6.0,0.0,Murder Non Negligent Manslaughter,Adams County Sheriff
595,2015,11.0,2.0,Rape,Adams County Sheriff
596,2015,25.0,7.0,Robbery,Adams County Sheriff
597,2015,133.0,5.0,Aggravated Assault,Adams County Sheriff
598,2015,46.0,2.0,Burglary,Adams County Sheriff
...,...,...,...,...,...
92618,2016,36.0,0.0,Prostitution,Adams County Sheriff
92651,2016,1.0,0.0,Embezzlement,Adams County Sheriff
92870,2005,46.0,1.0,Other Family Offenses,Adams County Sheriff
92953,2016,3.0,NaN,Vagrancy,Adams County Sheriff
93106,2003,0.0,2.0,Forgery,Adams County Sheriff

In [90]:
offArrCIM.groupby(["policeDistrict","type"]).count()

                                                     year  adultCount  \
policeDistrict                   type
22nd Judical District Task Force Aggravated Assault     6           6
                                 All Other Offenses     6           6
                                 Arson                  6           6
                                 Burglary               6           6
                                 Curfew Violations      6           0
...                                                   ...         ...
Yuma PD                          Runaways              16           0
                                 Stolen Property       16          16
                                 Vagrancy              16          16
                                 Vandalism             16          16
                                 Weapons               16          16

                                                     juvenileCount
policeDistrict                   type
22nd Judical District Task Force Aggravated Assault              6
                                 All Other Offenses              6
                                 Arson                           6
                                 Burglary                        6
                                 Curfew Violations               6
...                                                            ...
Yuma PD                          Runaways                       16
                                 Stolen Property                16
                                 Vagrancy                        0
                                 Vandalism                      16
                                 Weapons                        16

[7474 rows x 3 columns]

In [91]:
df.head()

,Agency,data_year,Aggravated Assault,All Other Offenses (Except Traffic),Arson,Burglary,Curfew and Loitering Law Violations,Disorderly Conduct,Driving Under the Influence,Drug Abuse Violations - Grand Total,...,Prostitution and Commercialized Vice,Rape,Robbery,"Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)",Simple Assault,"Stolen Property: Buying, Receiving, Possessing",Suspicion,Vagrancy,Vandalism,"Weapons: Carrying, Possessing, Etc."
0,Adams County Sheriff's Office,2000,152,4557,9,49,6,63,607,212,...,1,9,10,14,386,37,0,0,107,32
1,Adams County Sheriff's Office,2001,127,4497,7,68,16,169,619,223,...,0,8,25,17,405,46,0,1,118,26
2,Adams County Sheriff's Office,2002,106,4629,6,66,11,132,538,251,...,2,5,10,31,404,87,0,0,99,21
3,Adams County Sheriff's Office,2003,107,5547,2,67,4,76,559,228,...,7,4,11,42,369,57,0,0,117,38
4,Adams County Sheriff's Office,2004,113,6019,4,71,12,108,500,328,...,4,4,19,43,350,68,0,0,103,38

In [82]:
df.head()

,Agency,data_year,Aggravated Assault,All Other Offenses (Except Traffic),Arson,Burglary,Curfew and Loitering Law Violations,Disorderly Conduct,Driving Under the Influence,Drug Abuse Violations - Grand Total,...,Prostitution and Commercialized Vice,Rape,Robbery,"Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)",Simple Assault,"Stolen Property: Buying, Receiving, Possessing",Suspicion,Vagrancy,Vandalism,"Weapons: Carrying, Possessing, Etc."
0,Adams County Sheriff's Office,2000,152,4557,9,49,6,63,607,212,...,1,9,10,14,386,37,0,0,107,32
1,Adams County Sheriff's Office,2001,127,4497,7,68,16,169,619,223,...,0,8,25,17,405,46,0,1,118,26
2,Adams County Sheriff's Office,2002,106,4629,6,66,11,132,538,251,...,2,5,10,31,404,87,0,0,99,21
3,Adams County Sheriff's Office,2003,107,5547,2,67,4,76,559,228,...,7,4,11,42,369,57,0,0,117,38
4,Adams County Sheriff's Office,2004,113,6019,4,71,12,108,500,328,...,4,4,19,43,350,68,0,0,103,38

In [92]:
df.head()

,Agency,data_year,Aggravated Assault,All Other Offenses (Except Traffic),Arson,Burglary,Curfew and Loitering Law Violations,Disorderly Conduct,Driving Under the Influence,Drug Abuse Violations - Grand Total,...,Prostitution and Commercialized Vice,Rape,Robbery,"Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)",Simple Assault,"Stolen Property: Buying, Receiving, Possessing",Suspicion,Vagrancy,Vandalism,"Weapons: Carrying, Possessing, Etc."
0,Adams County Sheriff's Office,2000,152,4557,9,49,6,63,607,212,...,1,9,10,14,386,37,0,0,107,32
1,Adams County Sheriff's Office,2001,127,4497,7,68,16,169,619,223,...,0,8,25,17,405,46,0,1,118,26
2,Adams County Sheriff's Office,2002,106,4629,6,66,11,132,538,251,...,2,5,10,31,404,87,0,0,99,21
3,Adams County Sheriff's Office,2003,107,5547,2,67,4,76,559,228,...,7,4,11,42,369,57,0,0,117,38
4,Adams County Sheriff's Office,2004,113,6019,4,71,12,108,500,328,...,4,4,19,43,350,68,0,0,103,38