## Imports

In [1]:
import pandas as pd
import requests
import json
from pathlib import Path
from zipfile import ZipFile
api_key = "iuEO68Q3WH3VppVcdQkMIjb6OSnEJuh4aFkU9cK8"

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.18) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  RequestsDependencyWarning)

## API

### Get Agency Codes

In [2]:
url=f"https://api.usa.gov/crime/fbi/cde/agency/byStateAbbr/CO?API_KEY={api_key}"
response_API = requests.get(url
)
#print(response_API.status_code)
data = response_API.text
parse_json = json.loads(data)

In [3]:
agencies = {}
for agc in parse_json:
   # print(agc)
 #   print(agc['ori'],agc["agency_name"],agc["agency_id"],agc["county_name"])
    agencies[agc['ori']] = agc["agency_name"]
    
print(agencies)

{'CO0010000': "Adams County Sheriff's Office", 'CO0010100': 'Aurora Police Department', 'CO0010200': 'Brighton Police Department', 'CO0010300': 'Commerce City Police Department', 'CO0010400': 'Thornton Police Department', 'CO0010500': 'Westminster Police Department', 'CO0010600': 'Northglenn Police Department', 'CO0010800': 'Federal Heights Police Department', 'CO0011100': 'University of Colorado: Denver', 'CO0020000': "Alamosa County Sheriff's Office", 'CO0020100': 'Alamosa Police Department', 'CO0020200': 'Adams State University', 'CO0030000': "Arapahoe County Sheriff's Office", 'CO0030100': 'Englewood Police Department', 'CO0030200': 'Littleton Police Department', 'CO0030300': 'Sheridan Police Department', 'CO0030400': 'Glendale Police Department', 'CO0030500': 'Cherry Hills Village Police Department', 'CO0030600': 'Bow Mar Police Department', 'CO0030700': 'Greenwood Village Police Department', 'CO0030800': 'Columbine Valley Police Department', 'CO0030900': 'Arapahoe Community College', 'CO0031100': 'Centennial Police Department', 'CO0040000': "Archuleta County Sheriff's Office", 'CO0040100': 'Pagosa Springs Police Department', 'CO0050000': "Baca County Sheriff's Office", 'CO0050100': 'Springfield Police Department', 'CO0050700': 'Walsh Police Department', 'CO0060000': "Bent County Sheriff's Office", 'CO0070000': "Boulder County Sheriff's Office", 'CO0070100': 'Boulder Police Department', 'CO0070300': 'Lafayette Police Department', 'CO0070400': 'Longmont Police Department', 'CO0070500': 'University of Colorado: Boulder', 'CO0070600': 'Louisville Police Department', 'CO0070800': 'Nederland Police Department', 'CO0080000': "Chaffee County Sheriff's Office", 'CO0080100': 'Buena Vista Police Department', 'CO0080200': 'Salida Police Department', 'CO0090000': "Cheyenne County Sheriff's Office", 'CO0100000': "Clear Creek County Sheriff's Office", 'CO0100100': 'Idaho Springs Police Department', 'CO0100200': 'Georgetown Police Department', 'CO0100300': 'Empire Police Department', 'CO0110000': "Conejos County Sheriff's Office", 'CO0110500': 'Sanford Police Department', 'CO0120000': "Costilla County Sheriff's Office", 'CO0130000': "Crowley County Sheriff's Office", 'CO0140000': "Custer County Sheriff's Office", 'CO0150000': "Delta County Sheriff's Office", 'CO0150100': 'Delta Police Department', 'CO0150200': 'Paonia Police Department', 'CO0150300': 'Hotchkiss Police Department', 'CO0150400': 'Cedaredge Police Department', 'CO0160200': 'Auraria Higher Education Center', 'CO0170000': "Dolores County Sheriff's Office", 'CO0180000': "Douglas County Sheriff's Office", 'CO0180100': 'Castle Rock Police Department', 'CO0180500': 'Parker Police Department', 'CO0180700': 'Lone Tree Police Department', 'CO0190000': "Eagle County Sheriff's Office", 'CO0190100': 'Vail Police Department', 'CO0190200': 'Eagle Police Department', 'CO0190400': 'Basalt Police Department', 'CO0190600': 'Avon Police Department', 'CO0191000': 'Gypsum Police Department', 'CO0200000': "Elbert County Sheriff's Office", 'CO0200100': 'Elizabeth Police Department', 'CO0200200': 'Simla Police Department', 'CO0210000': "El Paso County Sheriff's Office", 'CO0210100': 'Colorado Springs Police Department', 'CO0210200': 'Fountain Police Department', 'CO0210300': 'Manitou Springs Police Department', 'CO0210400': 'University of Colorado: Colorado Springs', 'CO0210500': 'Pikes Peak Community College', 'CO0210600': 'Palmer Lake Police Department', 'CO0210700': 'Monument Police Department', 'CO0210900': 'Green Mountain Falls Police Department', 'CO0211000': 'Calhan Police Department', 'CO0220000': "Fremont County Sheriff's Office", 'CO0220100': 'Canon City Police Department', 'CO0220200': 'Florence Police Department', 'CO0230000': "Garfield County Sheriff's Office", 'CO0230100': 'Glenwood Springs Police Department', 'CO0230200': 'Parachute Police Department', 'CO0230300': 'Rifle Police Department', 'CO0230400': 'Carbondale Police Department', 'CO0230500': 'Silt Police Department', 'CO0230600': 'New Castle Police Department', 'CO0240000': "Gilpin County Sheriff's Office", 'CO0240200': 'Black Hawk Police Department', 'CO0250000': "Grand County Sheriff's Office", 'CO0250100': 'Granby Police Department', 'CO0250300': 'Kremmling Police Department', 'CO0250400': 'Fraser/Winter Park Police Department', 'CO0260000': "Gunnison County Sheriff's Office", 'CO0260100': 'Gunnison Police Department', 'CO0260200': 'Mount Crested Butte Police Department', 'CO0260300': 'Crested Butte Police Department', 'CO0270000': "Hinsdale County Sheriff's Office", 'CO0280000': "Huerfano County Sheriff's Office", 'CO0280200': 'La Veta Police Department', 'CO0290000': "Jackson County Sheriff's Office", 'CO0300000': "Jefferson County Sheriff's Office", 'CO0300100': 'Arvada Police Department', 'CO030015Y': 'Division of Gaming Criminal Enforcement and Investigations Section,', 'CO0300200': 'Golden Police Department', 'CO0300300': 'Edgewater Police Department', 'CO0300400': 'Lakewood Police Department', 'CO0300500': 'Wheat Ridge Police Department', 'CO0300600': 'Lakeside Police Department', 'CO0300700': 'Morrison Police Department', 'CO0300800': 'Colorado School of Mines', 'CO0300900': 'Mountain View Police Department', 'CO0301000': 'Red Rocks Community College', 'CO0310000': "Kiowa County Sheriff's Office", 'CO0320000': "Kit Carson County Sheriff's Office", 'CO0320100': 'Burlington Police Department', 'CO0330000': "Lake County Sheriff's Office", 'CO0330100': 'Leadville Police Department', 'CO0340000': "La Plata County Sheriff's Office", 'CO0340100': 'Durango Police Department', 'CO034019E': 'Fort Lewis College', 'CO0340200': 'Southern Ute Tribal', 'CO0340300': 'Ignacio Police Department', 'CO0340400': 'Bayfield Police Department', 'CO0348000': 'Southwest Drug Task Force', 'CO0350000': "Larimer County Sheriff's Office", 'CO0350200': 'Estes Park Police Department', 'CO0350300': 'Fort Collins Police Department', 'CO0350400': 'Loveland Police Department', 'CO0350500': 'Colorado State University, Fort Collins', 'CO0350900': 'Northern Colorado Drug Task Force', 'CO0351000': 'Timnath Police Department', 'CO0360000': "Las Animas County Sheriff's Office", 'CO0360100': 'Trinidad Police Department', 'CO0370000': "Lincoln County Sheriff's Office", 'CO0370100': 'Limon Police Department', 'CO0370200': 'Hugo Police Department', 'CO0380000': "Logan County Sheriff's Office", 'CO0380100': 'Sterling Police Department', 'CO0390000': "Mesa County Sheriff's Office", 'CO0390100': 'Grand Junction Police Department', 'CO0390200': 'Fruita Police Department', 'CO0390300': 'Palisade Police Department', 'CO0390400': 'De Beque Police Department', 'CO0390900': 'Collbran Police Department', 'CO0400000': "Mineral County Sheriff's Office", 'CO0410000': "Moffat County Sheriff's Office", 'CO0410100': 'Craig Police Department', 'CO0410200': 'Dinosaur Police Department', 'CO0418000': 'All Crimes Enforcement Team', 'CO0420000': "Montezuma County Sheriff's Office", 'CO0420100': 'Cortez Police Department', 'CO0420200': 'Mancos Police Department', 'CO0430000': "Montrose County Sheriff's Office", 'CO0430100': 'Montrose Police Department', 'CO0430400': 'Olathe Police Department', 'CO0438000': 'Delta Montrose Drug Task Force', 'CO0440000': "Morgan County Sheriff's Office", 'CO0440100': 'Brush Police Department', 'CO0440200': 'Fort Morgan Police Department', 'CO0440300': 'Wiggins Police Department', 'CO0440400': 'Log Lane Village Police Department', 'CO0450000': "Otero County Sheriff's Office", 'CO0450100': 'La Junta Police Department', 'CO0450200': 'Rocky Ford Police Department', 'CO0450300': 'Manzanola Police Department', 'CO0450400': 'Fowler Police Department', 'CO0460000': "Ouray County Sheriff's Office", 'CO0460100': 'Ouray Police Department', 'CO0460200': 'Ridgway Police Department', 'CO0470000': "Park County Sheriff's Office", 'CO0470100': 'Fairplay Police Department', 'CO0480000': "Phillips County Sheriff's Office", 'CO0480100': 'Holyoke Police Department', 'CO0480200': 'Haxtun Police Department', 'CO0490000': "Pitkin County Sheriff's Office", 'CO0490100': 'Aspen Police Department', 'CO0490200': 'Snowmass Village Police Department', 'CO0500000': "Prowers County Sheriff's Office", 'CO0500100': 'Lamar Police Department', 'CO0500400': 'Granada Police Department', 'CO0510000': "Pueblo County Sheriff's Office", 'CO0510100': 'Pueblo Police Department', 'CO0510200': 'Colorado Mental Health Institute', 'CO0520000': "Rio Blanco County Sheriff's Office", 'CO0520100': 'Meeker Police Department', 'CO0520200': 'Rangely Police Department', 'CO0530000': "Rio Grande County Sheriff's Office", 'CO0530100': 'Monte Vista Police Department', 'CO0530200': 'Del Norte Police Department', 'CO0530300': 'South Fork Police Department', 'CO0540000': "Routt County Sheriff's Office", 'CO0540100': 'Steamboat Springs Police Department', 'CO0540200': 'Hayden Police Department', 'CO0540300': 'Oak Creek Police Department', 'CO0550000': "Saguache County Sheriff's Office", 'CO0550100': 'Center Police Department', 'CO0560000': "San Juan County Sheriff's Office", 'CO0570000': "San Miguel County Sheriff's Office", 'CO0570100': 'Telluride Police Department', 'CO0570300': 'Mountain Village Police Department', 'CO0580000': "Sedgwick County Sheriff's Office", 'CO0590000': "Summit County Sheriff's Office", 'CO0590100': 'Breckenridge Police Department', 'CO0590200': 'Dillon Police Department', 'CO0590300': 'Silverthorne Police Department', 'CO0590400': 'Frisco Police Department', 'CO0590500': 'Blue River Police Department', 'CO0600000': "Teller County Sheriff's Office", 'CO0600100': 'Woodland Park Police Department', 'CO060015Y': 'Division of Gaming Criminal Enforcement and Investigations Section,', 'CO0600200': 'Cripple Creek Police Department', 'CO0610000': "Washington County Sheriff's Office", 'CO0620000': "Weld County Sheriff's Office", 'CO0620100': 'Fort Lupton Police Department', 'CO0620200': 'Greeley Police Department', 'CO0620300': 'Eaton Police Department', 'CO0620400': 'Evans Police Department', 'CO0620500': 'La Salle Police Department', 'CO0620600': 'Windsor Police Department', 'CO0620700': 'Erie Police Department', 'CO0620800': 'Dacono Police Department', 'CO0620900': 'Kersey Police Department', 'CO0621000': 'Johnstown Police Department', 'CO0621100': 'Milliken Police Department', 'CO0621200': 'Ault Police Department', 'CO0621300': 'Platteville Police Department', 'CO0621600': 'University of Northern Colorado', 'CO0621700': 'Frederick Police Department', 'CO0621800': 'Firestone Police Department', 'CO0621900': 'Keenesburg Police Department', 'CO0622000': 'Lochbuie Police Department', 'CO0622300': 'Nunn', 'CO0622400': 'Hudson Police Department', 'CO0622600': 'Mead Police Department', 'CO0622700': 'Garden City Police Department', 'CO0622800': 'Severance Police Department', 'CO0622900': 'Aims Community College', 'CO0628000': 'Weld County Drug Task Force ', 'CO0630000': "Yuma County Sheriff's Office", 'CO0630100': 'Wray Police Department', 'CO0630200': 'Yuma Police Department', 'CO0640100': 'Broomfield Police Department', 'COCBI0000': 'Colorado Bureau of Investigation', 'COCSP0000': 'State Patrol', 'CODI01100': 'Ute Mountain Tribal', 'CODPD0000': 'Denver Police Department'}

### Get Crimes by Agency

In [25]:
# ori = Orginating Agency Identifier

def decodeCrime(parse_json,ori):
    columns = ["data_year"]
    columns[1:] = [key for key in parse_json["keys"]]
    dd = {}
    for col in columns:
        dd[col] = []
    for val in parse_json["data"]:
#        print(ori,val["data_year"])
        for k,v in val.items():

            dd[k].append(v)
    df = pd.DataFrame(dd)
    df.insert(0,column="Agency",value=agencies[ori])
    df.insert(1,column="ori",value=ori)
    
    return df

nagc=0
for ori in agencies:
    nagc+=1
    print(f"{nagc} of {len(agencies)} -  {ori}")
    url=f"https://api.usa.gov/crime/fbi/cde/arrest/agency/{ori}/all?from=1970&to=2023&API_KEY={api_key}"
    response_API = requests.get(url)
    #print(response_API.status_code)
    data = response_API.text
    parse_json = json.loads(data)
#    print(parse_json)
    tmp = decodeCrime(parse_json,ori)
    if nagc > 1:
        crime = pd.concat([crime,tmp])
    else:
        crime=tmp
 
print("DONE ")

1 of 249 -  CO0010000
2 of 249 -  CO0010100
3 of 249 -  CO0010200
4 of 249 -  CO0010300
5 of 249 -  CO0010400
6 of 249 -  CO0010500
7 of 249 -  CO0010600
8 of 249 -  CO0010800
9 of 249 -  CO0011100
10 of 249 -  CO0020000
11 of 249 -  CO0020100
12 of 249 -  CO0020200
13 of 249 -  CO0030000
14 of 249 -  CO0030100
15 of 249 -  CO0030200
16 of 249 -  CO0030300
17 of 249 -  CO0030400
18 of 249 -  CO0030500
19 of 249 -  CO0030600
20 of 249 -  CO0030700
21 of 249 -  CO0030800
22 of 249 -  CO0030900
23 of 249 -  CO0031100
24 of 249 -  CO0040000
25 of 249 -  CO0040100
26 of 249 -  CO0050000
27 of 249 -  CO0050100
28 of 249 -  CO0050700
29 of 249 -  CO0060000
30 of 249 -  CO0070000
31 of 249 -  CO0070100
32 of 249 -  CO0070300
33 of 249 -  CO0070400
34 of 249 -  CO0070500
35 of 249 -  CO0070600
36 of 249 -  CO0070800
37 of 249 -  CO0080000
38 of 249 -  CO0080100
39 of 249 -  CO0080200
40 of 249 -  CO0090000
41 of 249 -  CO0100000
42 of 249 -  CO0100100
43 of 249 -  CO0100200
44 of 249 -  CO0100300
45 of 249 -  CO0110000
46 of 249 -  CO0110500
47 of 249 -  CO0120000
48 of 249 -  CO0130000
49 of 249 -  CO0140000
50 of 249 -  CO0150000
51 of 249 -  CO0150100
52 of 249 -  CO0150200
53 of 249 -  CO0150300
54 of 249 -  CO0150400
55 of 249 -  CO0160200
56 of 249 -  CO0170000
57 of 249 -  CO0180000
58 of 249 -  CO0180100
59 of 249 -  CO0180500
60 of 249 -  CO0180700
61 of 249 -  CO0190000
62 of 249 -  CO0190100
63 of 249 -  CO0190200
64 of 249 -  CO0190400
65 of 249 -  CO0190600
66 of 249 -  CO0191000
67 of 249 -  CO0200000
68 of 249 -  CO0200100
69 of 249 -  CO0200200
70 of 249 -  CO0210000
71 of 249 -  CO0210100
72 of 249 -  CO0210200
73 of 249 -  CO0210300
74 of 249 -  CO0210400
75 of 249 -  CO0210500
76 of 249 -  CO0210600
77 of 249 -  CO0210700
78 of 249 -  CO0210900
79 of 249 -  CO0211000
80 of 249 -  CO0220000
81 of 249 -  CO0220100
82 of 249 -  CO0220200
83 of 249 -  CO0230000
84 of 249 -  CO0230100
85 of 249 -  CO0230200
86 of 249 -  CO0230300
87 of 249 -  CO0230400
88 of 249 -  CO0230500
89 of 249 -  CO0230600
90 of 249 -  CO0240000
91 of 249 -  CO0240200
92 of 249 -  CO0250000
93 of 249 -  CO0250100
94 of 249 -  CO0250300
95 of 249 -  CO0250400
96 of 249 -  CO0260000
97 of 249 -  CO0260100
98 of 249 -  CO0260200
99 of 249 -  CO0260300
100 of 249 -  CO0270000
101 of 249 -  CO0280000
102 of 249 -  CO0280200
103 of 249 -  CO0290000
104 of 249 -  CO0300000
105 of 249 -  CO0300100
106 of 249 -  CO030015Y
107 of 249 -  CO0300200
108 of 249 -  CO0300300
109 of 249 -  CO0300400
110 of 249 -  CO0300500
111 of 249 -  CO0300600
112 of 249 -  CO0300700
113 of 249 -  CO0300800
114 of 249 -  CO0300900
115 of 249 -  CO0301000
116 of 249 -  CO0310000
117 of 249 -  CO0320000
118 of 249 -  CO0320100
119 of 249 -  CO0330000
120 of 249 -  CO0330100
121 of 249 -  CO0340000
122 of 249 -  CO0340100
123 of 249 -  CO034019E
124 of 249 -  CO0340200
125 of 249 -  CO0340300
126 of 249 -  CO0340400
127 of 249 -  CO0348000
128 of 249 -  CO0350000
129 of 249 -  CO0350200
130 of 249 -  CO0350300
131 of 249 -  CO0350400
132 of 249 -  CO0350500
133 of 249 -  CO0350900
134 of 249 -  CO0351000
135 of 249 -  CO0360000
136 of 249 -  CO0360100
137 of 249 -  CO0370000
138 of 249 -  CO0370100
139 of 249 -  CO0370200
140 of 249 -  CO0380000
141 of 249 -  CO0380100
142 of 249 -  CO0390000
143 of 249 -  CO0390100
144 of 249 -  CO0390200
145 of 249 -  CO0390300
146 of 249 -  CO0390400
147 of 249 -  CO0390900
148 of 249 -  CO0400000
149 of 249 -  CO0410000
150 of 249 -  CO0410100
151 of 249 -  CO0410200
152 of 249 -  CO0418000
153 of 249 -  CO0420000
154 of 249 -  CO0420100
155 of 249 -  CO0420200
156 of 249 -  CO0430000
157 of 249 -  CO0430100
158 of 249 -  CO0430400
159 of 249 -  CO0438000
160 of 249 -  CO0440000
161 of 249 -  CO0440100
162 of 249 -  CO0440200
163 of 249 -  CO0440300
164 of 249 -  CO0440400
165 of 249 -  CO0450000
166 of 249 -  CO0450100
167 of 249 -  CO0450200
168 of 249 -  CO0450300
169 of 249 -  CO0450400
170 of 249 -  CO0460000
171 of 249 -  CO0460100
172 of 249 -  CO0460200
173 of 249 -  CO0470000
174 of 249 -  CO0470100
175 of 249 -  CO0480000
176 of 249 -  CO0480100
177 of 249 -  CO0480200
178 of 249 -  CO0490000
179 of 249 -  CO0490100
180 of 249 -  CO0490200
181 of 249 -  CO0500000
182 of 249 -  CO0500100
183 of 249 -  CO0500400
184 of 249 -  CO0510000
185 of 249 -  CO0510100
186 of 249 -  CO0510200
187 of 249 -  CO0520000
188 of 249 -  CO0520100
189 of 249 -  CO0520200
190 of 249 -  CO0530000
191 of 249 -  CO0530100
192 of 249 -  CO0530200
193 of 249 -  CO0530300
194 of 249 -  CO0540000
195 of 249 -  CO0540100
196 of 249 -  CO0540200
197 of 249 -  CO0540300
198 of 249 -  CO0550000
199 of 249 -  CO0550100
200 of 249 -  CO0560000
201 of 249 -  CO0570000
202 of 249 -  CO0570100
203 of 249 -  CO0570300
204 of 249 -  CO0580000
205 of 249 -  CO0590000
206 of 249 -  CO0590100
207 of 249 -  CO0590200
208 of 249 -  CO0590300
209 of 249 -  CO0590400
210 of 249 -  CO0590500
211 of 249 -  CO0600000
212 of 249 -  CO0600100
213 of 249 -  CO060015Y
214 of 249 -  CO0600200
215 of 249 -  CO0610000
216 of 249 -  CO0620000
217 of 249 -  CO0620100
218 of 249 -  CO0620200
219 of 249 -  CO0620300
220 of 249 -  CO0620400
221 of 249 -  CO0620500
222 of 249 -  CO0620600
223 of 249 -  CO0620700
224 of 249 -  CO0620800
225 of 249 -  CO0620900
226 of 249 -  CO0621000
227 of 249 -  CO0621100
228 of 249 -  CO0621200
229 of 249 -  CO0621300
230 of 249 -  CO0621600
231 of 249 -  CO0621700
232 of 249 -  CO0621800
233 of 249 -  CO0621900
234 of 249 -  CO0622000
235 of 249 -  CO0622300
236 of 249 -  CO0622400
237 of 249 -  CO0622600
238 of 249 -  CO0622700
239 of 249 -  CO0622800
240 of 249 -  CO0622900
241 of 249 -  CO0628000
242 of 249 -  CO0630000
243 of 249 -  CO0630100
244 of 249 -  CO0630200
245 of 249 -  CO0640100
246 of 249 -  COCBI0000
247 of 249 -  COCSP0000
248 of 249 -  CODI01100
249 of 249 -  CODPD0000
DONE

In [26]:
crime.shape

(9685, 34)

In [27]:
crime['data_year'].value_counts().sort_index()

1970.0     71
1971.0     70
1972.0     76
1973.0     69
1974.0    102
1975.0    108
1976.0    129
1977.0    156
1978.0    172
1979.0    173
1980.0    173
1981.0    182
1982.0    176
1983.0    186
1984.0    193
1985.0    195
1986.0    193
1987.0    199
1988.0    198
1989.0    194
1990.0    189
1991.0    199
1992.0    196
1993.0    190
1994.0    190
1995.0    190
1996.0    178
1997.0    194
1998.0    188
1999.0    196
2000.0    182
2001.0    176
2002.0    173
2003.0    180
2004.0    185
2005.0    193
2006.0    208
2007.0    201
2008.0    205
2009.0    210
2010.0    206
2011.0    210
2012.0    214
2013.0    215
2014.0    220
2015.0    224
2016.0    218
2017.0    218
2018.0    221
2019.0    222
2020.0    225
2021.0    233
2022.0    221
Name: data_year, dtype: int64

In [32]:
crime.rename(columns={"data_year":"year"},inplace=True)

In [33]:
columns = crime.columns

In [34]:
for col in columns[2:]:
    crime[col] = crime[col].astype(int)

In [35]:
crime.dtypes

Agency                                                                  object
ori                                                                     object
year                                                                     int64
Aggravated Assault                                                       int64
All Other Offenses (Except Traffic)                                      int64
Arson                                                                    int64
Burglary                                                                 int64
Curfew and Loitering Law Violations                                      int64
Disorderly Conduct                                                       int64
Driving Under the Influence                                              int64
Drug Abuse Violations - Grand Total                                      int64
Drunkenness                                                              int64
Embezzlement                                                             int64
Forgery and Counterfeiting                                               int64
Fraud                                                                    int64
Gambling - Total                                                         int64
Human Trafficking - Commercial Sex Acts                                  int64
Human Trafficking - Involuntary Servitude                                int64
Larceny - Theft                                                          int64
Liquor Laws                                                              int64
Manslaughter by Negligence                                               int64
Motor Vehicle Theft                                                      int64
Murder and Nonnegligent Manslaughter                                     int64
Offenses Against the Family and Children                                 int64
Prostitution and Commercialized Vice                                     int64
Rape                                                                     int64
Robbery                                                                  int64
Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)     int64
Simple Assault                                                           int64
Stolen Property: Buying, Receiving, Possessing                           int64
Suspicion                                                                int64
Vagrancy                                                                 int64
Vandalism                                                                int64
Weapons: Carrying, Possessing, Etc.                                      int64
dtype: object

In [36]:
columnMap = {
 'Aggravated Assault':'aggravatedAssault',
 'All Other Offenses (Except Traffic)':'allOtherOffensesExceptTraffic',
 'Arson': 'arson',
 'Burglary':'burglary',
 'Curfew and Loitering Law Violations': 'curfewLoiteringLawViolations',
 'Disorderly Conduct':'disorderlyConduct',
 'Driving Under the Influence':'drivingUnderTheInfluence',
 'Drug Abuse Violations - Grand Total':'drugAbuseViolationsGrandTotal',
 'Drunkenness':'drunkenness',
 'Embezzlement':'embezzlement',
 'Forgery and Counterfeiting':'forgeryAndCounterfeiting',
 'Fraud':'fraud',
 'Gambling - Total':'gamblingTotal',
 'Human Trafficking - Commercial Sex Acts':'humanTraffickingCommercialSexActs',
 'Human Trafficking - Involuntary Servitude':'humanTraffickingInvoluntaryServitude',
 'Larceny - Theft':'larcenyTheft',
 'Liquor Laws':'liquorLaws',
 'Manslaughter by Negligence':'manslaughterByNegligence',
 'Motor Vehicle Theft':'motorVehicleTheft',
 'Murder and Nonnegligent Manslaughter': 'murderAndNonnegligentManslaughter',
 'Offenses Against the Family and Children': 'offensesAgainstTheFamilyAndChildren',
 'Prostitution and Commercialized Vice': 'prostitutionAndCommercializedVice',
 'Rape':'rape',
 'Robbery':'robbery',
 'Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)':'sexOffensesExceptRapeAndProstitutionAndCommercializedVice',
 'Simple Assault':'simpleAssault',
 'Stolen Property: Buying, Receiving, Possessing':'stolenPropertyBuyingReceivingPossessing',
 'Suspicion':'suspicion',
 'Vagrancy':'vagrancy',
 'Vandalism':'vandalism',
 'Weapons: Carrying, Possessing, Etc.':'weaponsCarryingPossessingEtc'
}  

crime.rename(columns=columnMap,inplace=True)

In [37]:
crime.rename(columns={'Agency':'agency'},inplace=True)

In [38]:
for col in crime.columns:
    print(col)

agency
ori
year
aggravatedAssault
allOtherOffensesExceptTraffic
arson
burglary
curfewLoiteringLawViolations
disorderlyConduct
drivingUnderTheInfluence
drugAbuseViolationsGrandTotal
drunkenness
embezzlement
forgeryAndCounterfeiting
fraud
gamblingTotal
humanTraffickingCommercialSexActs
humanTraffickingInvoluntaryServitude
larcenyTheft
liquorLaws
manslaughterByNegligence
motorVehicleTheft
murderAndNonnegligentManslaughter
offensesAgainstTheFamilyAndChildren
prostitutionAndCommercializedVice
rape
robbery
sexOffensesExceptRapeAndProstitutionAndCommercializedVice
simpleAssault
stolenPropertyBuyingReceivingPossessing
suspicion
vagrancy
vandalism
weaponsCarryingPossessingEtc

In [39]:
crime.to_csv("crimeCO-1970-2022.csv",index=False)

In [40]:
crime.shape

(9685, 34)

In [17]:
crime.head()

,agency,ori,year,aggravatedAssault,allOtherOffensesExceptTraffic,arson,burglary,curfewLoiteringLawViolations,disorderlyConduct,drivingUnderTheInfluence,...,prostitutionAndCommercializedVice,rape,robbery,sexOffensesExceptRapeAndProstitutionAndCommercializedVice,simpleAssault,stolenPropertyBuyingReceivingPossessing,suspicion,vagrancy,vandalism,weaponsCarryingPossessingEtc
0,Adams County Sheriff's Office,CO0010000,1970,57,576,0,214,0,60,31,...,17,12,15,36,135,9,0,0,32,8
1,Adams County Sheriff's Office,CO0010000,1971,85,767,12,184,0,59,31,...,3,13,23,17,123,1,0,0,41,10
2,Adams County Sheriff's Office,CO0010000,1972,61,742,4,170,0,54,16,...,1,20,17,12,133,11,0,0,64,4
3,Adams County Sheriff's Office,CO0010000,1974,73,803,4,199,0,55,43,...,0,16,20,12,140,0,0,3,38,11
4,Adams County Sheriff's Office,CO0010000,1975,62,843,9,206,1,80,35,...,0,14,67,27,109,11,0,1,52,5

### Check Output File

In [41]:
df = pd.read_csv("crimeCO-1970-2022.csv")

In [43]:
df.shape

(9685, 34)

In [ ]:
df.columns

Index(['agency', 'ori', 'year', 'aggravatedAssault',
       'allOtherOffensesExceptTraffic', 'arson', 'burglary',
       'curfewLoiteringLawViolations', 'disorderlyConduct',
       'drivingUnderTheInfluence', 'drugAbuseViolationsGrandTotal',
       'drunkenness', 'embezzlement', 'forgeryAndCounterfeiting', 'fraud',
       'gamblingTotal', 'humanTraffickingCommercialSexActs',
       'humanTraffickingInvoluntaryServitude', 'larcenyTheft', 'liquorLaws',
       'manslaughterByNegligence', 'motorVehicleTheft',
       'murderAndNonnegligentManslaughter',
       'offensesAgainstTheFamilyAndChildren',
       'prostitutionAndCommercializedVice', 'rape', 'robbery',
       'sexOffensesExceptRapeAndProstitutionAndCommercializedVice',
       'simpleAssault', 'stolenPropertyBuyingReceivingPossessing', 'suspicion',
       'vagrancy', 'vandalism', 'weaponsCarryingPossessingEtc'],
      dtype='object')

### More Granularity

In [18]:

response_API = requests.get(
'https://api.usa.gov/crime/fbi/cde/nibrs/state/CO/all/offense/count?API_KEY=iuEO68Q3WH3VppVcdQkMIjb6OSnEJuh4aFkU9cK8')
#print(response_API.status_code)
data = response_API.text
parse_json = json.loads(data)

In [ ]:
parse_json

In [21]:
types = [
"count",
# "age",    
# "sex",    
# "race",    
# "ethnicity",    
# #"relationship",   on available for victim 
"location",    
"linkedoffense",    
"weapons"  
]

offenses = [
"all",    
"violent-crime",    
"aggravated-assault",
"burglary",    
"larceny",    
"motor-vehicle-theft",    
"homicide",    
"rape",    
"robbery",    
"arson",    
"property-crime",    

]

In [22]:

#url = f'https://api.usa.gov/crime/fbi/cde/nibrs/agency/CO0010000/{offen}/offender/{typ}?from=2016&to=2021&API_KEY==iuEO68Q3WH3VppVcdQkMIjb6OSnEJuh4aFkU9cK8'

In [ ]:
ori = "CO0010000"
dataAll = {}
dataAll[ori] = {}
# dataAll[ori]["data"] = []
# dataAll[ori]["what"] = []
cat = "offense"
fails=[]
for typ in types:
    for offen in offenses:
        try:
            url = f'https://api.usa.gov/crime/fbi/cde/nibrs/agency/{ori}/{offen}/{cat}/{typ}?from=2016&to=2021&API_KEY=iuEO68Q3WH3VppVcdQkMIjb6OSnEJuh4aFkU9cK8'        
          #  print(url)
            response_API = requests.get(url)
            print(ori,typ,offen,response_API)
            string = f"{cat},{typ},{offen}"
            data = response_API.text
            parse_json = json.loads(data)
            # dataAll[ori]["data"].append(parse_json)
            # dataAll[ori]["what"].append(string)
            if string not in dataAll[ori]:
                dataAll[ori][string] = []
            dataAll[ori][string].append(parse_json)
        except:
            print("FAIL ",string)
            fails.append(string)
        
print("DONE")

In [ ]:
dataAll['CO0010000']

In [34]:
dataAll['CO0010000']['data'][0]

{'keys': ['Incident Count', 'Offense Count'],
 'data': [{'data_year': 2017, 'Incident Count': 91, 'Offense Count': 100},
  {'data_year': 2019, 'Incident Count': 666, 'Offense Count': 666},
  {'data_year': 2020, 'Incident Count': 3, 'Offense Count': 3},
  {'data_year': 2020, 'Incident Count': 66, 'Offense Count': 72},
  {'data_year': 2017, 'Incident Count': 8, 'Offense Count': 8},
  {'data_year': 2018, 'Incident Count': 793, 'Offense Count': 824},
  {'data_year': 2021, 'Incident Count': 4, 'Offense Count': 4},
  {'data_year': 2018, 'Incident Count': 100, 'Offense Count': 100},
  {'data_year': 2021, 'Incident Count': 429, 'Offense Count': 486},
  {'data_year': 2017, 'Incident Count': 36, 'Offense Count': 36},
  {'data_year': 2021, 'Incident Count': 536, 'Offense Count': 536},
  {'data_year': 2021, 'Incident Count': 44, 'Offense Count': 45},
  {'data_year': 2020, 'Incident Count': 18, 'Offense Count': 18},
  {'data_year': 2017, 'Incident Count': 113, 'Offense Count': 113},
  {'data_year': 2021, 'Incident Count': 364, 'Offense Count': 364},
  {'data_year': 2018, 'Incident Count': 4, 'Offense Count': 4},
  {'data_year': 2021, 'Incident Count': 43, 'Offense Count': 43},
  {'data_year': 2019, 'Incident Count': 898, 'Offense Count': 947},
  {'data_year': 2020, 'Incident Count': 335, 'Offense Count': 454},
  {'data_year': 2016, 'Incident Count': 7, 'Offense Count': 7},
  {'data_year': 2018, 'Incident Count': 421, 'Offense Count': 421},
  {'data_year': 2020, 'Incident Count': 11, 'Offense Count': 11},
  {'data_year': 2016, 'Incident Count': 643, 'Offense Count': 702},
  {'data_year': 2019, 'Incident Count': 62, 'Offense Count': 64},
  {'data_year': 2016, 'Incident Count': 33, 'Offense Count': 35},
  {'data_year': 2016, 'Incident Count': 146, 'Offense Count': 146},
  {'data_year': 2018, 'Incident Count': 37, 'Offense Count': 39},
  {'data_year': 2020, 'Incident Count': 1092, 'Offense Count': 1149},
  {'data_year': 2021, 'Incident Count': 8, 'Offense Count': 9},
  {'data_year': 2021, 'Incident Count': 38, 'Offense Count': 38},
  {'data_year': 2016, 'Incident Count': 1, 'Offense Count': 1},
  {'data_year': 2017, 'Incident Count': 43, 'Offense Count': 43},
  {'data_year': 2018, 'Incident Count': 96, 'Offense Count': 98},
  {'data_year': 2021, 'Incident Count': 92, 'Offense Count': 92},
  {'data_year': 2021, 'Incident Count': 10, 'Offense Count': 10},
  {'data_year': 2019, 'Incident Count': 46, 'Offense Count': 51},
  {'data_year': 2017, 'Incident Count': 1, 'Offense Count': 1},
  {'data_year': 2019, 'Incident Count': 32, 'Offense Count': 32},
  {'data_year': 2018, 'Incident Count': 289, 'Offense Count': 289},
  {'data_year': 2016, 'Incident Count': 4, 'Offense Count': 4},
  {'data_year': 2018, 'Incident Count': 1, 'Offense Count': 1},
  {'data_year': 2017, 'Incident Count': 37, 'Offense Count': 43},
  {'data_year': 2018, 'Incident Count': 6, 'Offense Count': 6},
  {'data_year': 2016, 'Incident Count': 9, 'Offense Count': 9},
  {'data_year': 2020, 'Incident Count': 4, 'Offense Count': 4},
  {'data_year': 2016, 'Incident Count': 263, 'Offense Count': 327},
  {'data_year': 2020, 'Incident Count': 315, 'Offense Count': 315},
  {'data_year': 2020, 'Incident Count': 12, 'Offense Count': 13},
  {'data_year': 2020, 'Incident Count': 615, 'Offense Count': 615},
  {'data_year': 2021, 'Incident Count': 8, 'Offense Count': 8},
  {'data_year': 2017, 'Incident Count': 6, 'Offense Count': 6},
  {'data_year': 2019, 'Incident Count': 2, 'Offense Count': 2},
  {'data_year': 2019, 'Incident Count': 1, 'Offense Count': 1},
  {'data_year': 2017, 'Incident Count': 60, 'Offense Count': 62},
  {'data_year': 2018, 'Incident Count': 108, 'Offense Count': 108},
  {'data_year': 2021, 'Incident Count': 10, 'Offense Count': 10},
  {'data_year': 2017, 'Incident Count': 30, 'Offense Count': 30},
  {'data_year': 2021, 'Incident Count': 67, 'Offense Count': 74},
  {'data_year': 2018, 'Incident Count': 846, 'Offense Count': 846},
  {'data_year': 2020, 'Incident Count': 527, 'Offense Count': 527},
  {'data_year': 2021, 'Incident Count': 1, 'Offense Count': 1},
  {'data_year': 2021, 'Incident Count': 9, 'Offense Count': 11},
  {'data_year': 2020, 'Incident Count': 163, 'Offense Count': 163},
  {'data_year': 2017, 'Incident Count': 3, 'Offense Count': 4},
  {'data_year': 2016, 'Incident Count': 923, 'Offense Count': 944},
  {'data_year': 2018, 'Incident Count': 1, 'Offense Count': 1},
  {'data_year': 2018, 'Incident Count': 6, 'Offense Count': 6},
  {'data_year': 2021, 'Incident Count': 7, 'Offense Count': 7},
  {'data_year': 2017, 'Incident Count': 1, 'Offense Count': 1},
  {'data_year': 2020, 'Incident Count': 1, 'Offense Count': 1},
  {'data_year': 2018, 'Incident Count': 36, 'Offense Count': 41},
  {'data_year': 2018, 'Incident Count': 557, 'Offense Count': 605},
  {'data_year': 2016, 'Incident Count': 49, 'Offense Count': 58},
  {'data_year': 2017, 'Incident Count': 80, 'Offense Count': 80},
  {'data_year': 2019, 'Incident Count': 322, 'Offense Count': 322},
  {'data_year': 2021, 'Incident Count': 3, 'Offense Count': 3},
  {'data_year': 2017, 'Incident Count': 991, 'Offense Count': 991},
  {'data_year': 2016, 'Incident Count': 112, 'Offense Count': 112},
  {'data_year': 2021, 'Incident Count': 95, 'Offense Count': 95},
  {'data_year': 2019, 'Incident Count': 2, 'Offense Count': 2},
  {'data_year': 2016, 'Incident Count': 14, 'Offense Count': 14},
  {'data_year': 2018, 'Incident Count': 1, 'Offense Count': 1},
  {'data_year': 2016, 'Incident Count': 8, 'Offense Count': 8},
  {'data_year': 2021, 'Incident Count': 8, 'Offense Count': 8},
  {'data_year': 2017, 'Incident Count': 378, 'Offense Count': 378},
  {'data_year': 2019, 'Incident Count': 7, 'Offense Count': 7},
  {'data_year': 2021, 'Incident Count': 29, 'Offense Count': 32},
  {'data_year': 2019, 'Incident Count': 328, 'Offense Count': 328},
  {'data_year': 2021, 'Incident Count': 526, 'Offense Count': 564},
  {'data_year': 2018, 'Incident Count': 11, 'Offense Count': 11},
  {'data_year': 2017, 'Incident Count': 122, 'Offense Count': 122},
  {'data_year': 2018, 'Incident Count': 321, 'Offense Count': 321},
  {'data_year': 2020, 'Incident Count': 462, 'Offense Count': 462},
  {'data_year': 2019, 'Incident Count': 286, 'Offense Count': 347},
  {'data_year': 2018, 'Incident Count': 6, 'Offense Count': 6},
  {'data_year': 2017, 'Incident Count': 468, 'Offense Count': 468},
  {'data_year': 2020, 'Incident Count': 154, 'Offense Count': 154},
  {'data_year': 2020, 'Incident Count': 2, 'Offense Count': 2},
  {'data_year': 2017, 'Incident Count': 11, 'Offense Count': 11},
  {'data_year': 2018, 'Incident Count': 405, 'Offense Count': 405},
  {'data_year': 2017, 'Incident Count': 785, 'Offense Count': 785},
  {'data_year': 2016, 'Incident Count': 3, 'Offense Count': 3},
  {'data_year': 2017, 'Incident Count': 629, 'Offense Count': 685},
  {'data_year': 2019, 'Incident Count': 43, 'Offense Count': 46},
  {'data_year': 2018, 'Incident Count': 5, 'Offense Count': 5},
  {'data_year': 2017, 'Incident Count': 148, 'Offense Count': 148},
  {'data_year': 2020, 'Incident Count': 6, 'Offense Count': 6},
  {'data_year': 2017, 'Incident Count': 298, 'Offense Count': 298},
  {'data_year': 2016, 'Incident Count': 3, 'Offense Count': 3},
  {'data_year': 2020, 'Incident Count': 6, 'Offense Count': 6},
  {'data_year': 2016, 'Incident Count': 278, 'Offense Count': 278},
  {'data_year': 2019, 'Incident Count': 2, 'Offense Count': 2},
  {'data_year': 2016, 'Incident Count': 94, 'Offense Count': 94},
  {'data_year': 2016, 'Incident Count': 6, 'Offense Count': 6},
  {'data_year': 2019, 'Incident Count': 9, 'Offense Count': 9},
  {'data_year': 2020, 'Incident Count': 34, 'Offense Count': 41},
  {'data_year': 2017, 'Incident Count': 1, 'Offense Count': 1},
  {'data_year': 2016, 'Incident Count': 35, 'Offense Count': 35},
  {'data_year': 2019, 'Incident Count': 7, 'Offense Count': 7},
  {'data_year': 2021, 'Incident Count': 1114, 'Offense Count': 1114},
  {'data_year': 2021, 'Incident Count': 471, 'Offense Count': 471},
  {'data_year': 2017, 'Incident Count': 5, 'Offense Count': 5},
  {'data_year': 2018, 'Incident Count': 7, 'Offense Count': 7},
  {'data_year': 2016, 'Incident Count': 65, 'Offense Count': 66},
  {'data_year': 2021, 'Incident Count': 59, 'Offense Count': 66},
  {'data_year': 2019, 'Incident Count': 117, 'Offense Count': 117},
  {'data_year': 2017, 'Incident Count': 1, 'Offense Count': 1},
  {'data_year': 2017, 'Incident Count': 6, 'Offense Count': 7},
  {'data_year': 2020, 'Incident Count': 494, 'Offense Count': 523},
  {'data_year': 2019, 'Incident Count': 135, 'Offense Count': 135},
  {'data_year': 2017, 'Incident Count': 13, 'Offense Count': 13},
  {'data_year': 2021, 'Incident Count': 600, 'Offense Count': 600},
  {'data_year': 2021, 'Incident Count': 2, 'Offense Count': 2},
  {'data_year': 2019, 'Incident Count': 498, 'Offense Count': 498},
  {'data_year': 2019, 'Incident Count': 842, 'Offense Count': 842},
  {'data_year': 2019, 'Incident Count': 76, 'Offense Count': 76},
  {'data_year': 2018, 'Incident Count': 9, 'Offense Count': 9},
  {'data_year': 2019, 'Incident Count': 566, 'Offense Count': 613},
  {'data_year': 2018, 'Incident Count': 8, 'Offense Count': 8},
  {'data_year': 2020, 'Incident Count': 7, 'Offense Count': 7},
  {'data_year': 2019, 'Incident Count': 23, 'Offense Count': 23},
  {'data_year': 2018, 'Incident Count': 1, 'Offense Count': 1},
  {'data_year': 2017, 'Incident Count': 409, 'Offense Count': 409},
  {'data_year': 2017, 'Incident Count': 5, 'Offense Count': 5},
  {'data_year': 2020, 'Incident Count': 11, 'Offense Count': 11},
  {'data_year': 2016, 'Incident Count': 3, 'Offense Count': 3},
  {'data_year': 2016, 'Incident Count': 314, 'Offense Count': 314},
  {'data_year': 2021, 'Incident Count': 10, 'Offense Count': 10},
  {'data_year': 2016, 'Incident Count': 523, 'Offense Count': 523},
  {'data_year': 2017, 'Incident Count': 906, 'Offense Count': 933},
  {'data_year': 2021, 'Incident Count': 44, 'Offense Count': 44},
  {'data_year': 2016, 'Incident Count': 131, 'Offense Count': 131},
  {'data_year': 2017, 'Incident Count': 301, 'Offense Count': 354},
  {'data_year': 2021, 'Incident Count': 195, 'Offense Count': 195},
  {'data_year': 2019, 'Incident Count': 76, 'Offense Count': 76},
  {'data_year': 2018, 'Incident Count': 365, 'Offense Count': 365},
  {'data_year': 2021, 'Incident Count': 522, 'Offense Count': 522},
  {'data_year': 2018, 'Incident Count': 76, 'Offense Count': 76},
  {'data_year': 2020, 'Incident Count': 45, 'Offense Count': 47},
  {'data_year': 2016, 'Incident Count': 9, 'Offense Count': 10},
  {'data_year': 2018, 'Incident Count': 64, 'Offense Count': 70},
  {'data_year': 2019, 'Incident Count': 340, 'Offense Count': 340},
  {'data_year': 2017, 'Incident Count': 11, 'Offense Count': 11},
  {'data_year': 2020, 'Incident Count': 10, 'Offense Count': 10},
  {'data_year': 2021, 'Incident Count': 594, 'Offense Count': 594},
  {'data_year': 2018, 'Incident Count': 701, 'Offense Count': 701},
  {'data_year': 2017, 'Incident Count': 16, 'Offense Count': 17},
  {'data_year': 2021, 'Incident Count': 455, 'Offense Count': 455},
  {'data_year': 2019, 'Incident Count': 14, 'Offense Count': 14},
  {'data_year': 2021, 'Incident Count': 12, 'Offense Count': 12},
  {'data_year': 2017, 'Incident Count': 2, 'Offense Count': 2},
  {'data_year': 2016, 'Incident Count': 432, 'Offense Count': 432},
  {'data_year': 2017, 'Incident Count': 92, 'Offense Count': 92},
  {'data_year': 2016, 'Incident Count': 4, 'Offense Count': 4},
  {'data_year': 2017, 'Incident Count': 475, 'Offense Count': 475},
  {'data_year': 2019, 'Incident Count': 99, 'Offense Count': 99},
  {'data_year': 2018, 'Incident Count': 5, 'Offense Count': 5},
  {'data_year': 2018, 'Incident Count': 278, 'Offense Count': 328},
  {'data_year': 2017, 'Incident Count': 720, 'Offense Count': 720},
  {'data_year': 2017, 'Incident Count': 3, 'Offense Count': 3},
  {'data_year': 2016, 'Incident Count': 2, 'Offense Count': 2},
  {'data_year': 2018, 'Incident Count': 18, 'Offense Count': 18},
  {'data_year': 2016, 'Incident Count': 78, 'Offense Count': 83},
  {'data_year': 2020, 'Incident Count': 74, 'Offense Count': 78},
  {'data_year': 2016, 'Incident Count': 56, 'Offense Count': 56},
  {'data_year': 2019, 'Incident Count': 5, 'Offense Count': 5},
  {'data_year': 2019, 'Incident Count': 8, 'Offense Count': 8},
  {'data_year': 2019, 'Incident Count': 557, 'Offense Count': 557},
  {'data_year': 2020, 'Incident Count': 341, 'Offense Count': 341},
  {'data_year': 2016, 'Incident Count': 1, 'Offense Count': 1},
  {'data_year': 2020, 'Incident Count': 33, 'Offense Count': 33},
  {'data_year': 2021, 'Incident Count': 91, 'Offense Count': 91},
  {'data_year': 2019, 'Incident Count': 8, 'Offense Count': 8},
  {'data_year': 2021, 'Incident Count': 1, 'Offense Count': 1},
  {'data_year': 2021, 'Incident Count': 1264, 'Offense Count': 1264},
  {'data_year': 2020, 'Incident Count': 2, 'Offense Count': 2},
  {'data_year': 2017, 'Incident Count': 244, 'Offense Count': 244},
  {'data_year': 2019, 'Incident Count': 203, 'Offense Count': 203},
  {'data_year': 2018, 'Incident Count': 258, 'Offense Count': 258},
  {'data_year': 2020, 'Incident Count': 982, 'Offense Count': 982},
  {'data_year': 2018, 'Incident Count': 6, 'Offense Count': 6},
  {'data_year': 2021, 'Incident Count': 4, 'Offense Count': 5},
  {'data_year': 2019, 'Incident Count': 14, 'Offense Count': 14},
  {'data_year': 2016, 'Incident Count': 77, 'Offense Count': 77},
  {'data_year': 2020, 'Incident Count': 373, 'Offense Count': 373},
  {'data_year': 2019, 'Incident Count': 7, 'Offense Count': 7},
  {'data_year': 2018, 'Incident Count': 4, 'Offense Count': 4},
  {'data_year': 2018, 'Incident Count': 60, 'Offense Count': 60},
  {'data_year': 2019, 'Incident Count': 3, 'Offense Count': 3},
  {'data_year': 2018, 'Incident Count': 2, 'Offense Count': 2},
  {'data_year': 2020, 'Incident Count': 67, 'Offense Count': 67},
  {'data_year': 2020, 'Incident Count': 90, 'Offense Count': 90},
  {'data_year': 2016, 'Incident Count': 688, 'Offense Count': 688},
  {'data_year': 2020, 'Incident Count': 136, 'Offense Count': 136},
  {'data_year': 2016, 'Incident Count': 7, 'Offense Count': 9},
  {'data_year': 2016, 'Incident Count': 236, 'Offense Count': 236},
  {'data_year': 2016, 'Incident Count': 1078, 'Offense Count': 1078},
  {'data_year': 2016, 'Incident Count': 678, 'Offense Count': 678},
  {'data_year': 2018, 'Incident Count': 32, 'Offense Count': 32},
  {'data_year': 2018, 'Incident Count': 9, 'Offense Count': 9},
  {'data_year': 2018, 'Incident Count': 111, 'Offense Count': 111},
  {'data_year': 2020, 'Incident Count': 14, 'Offense Count': 14},
  {'data_year': 2018, 'Incident Count': 754, 'Offense Count': 754},
  {'data_year': 2020, 'Incident Count': 16, 'Offense Count': 16},
  {'data_year': 2019, 'Incident Count': 4, 'Offense Count': 4},
  {'data_year': 2019, 'Incident Count': 5, 'Offense Count': 5},
  {'data_year': 2019, 'Incident Count': 863, 'Offense Count': 863},
  {'data_year': 2020, 'Incident Count': 81, 'Offense Count': 81},
  {'data_year': 2019, 'Incident Count': 9, 'Offense Count': 10},
  {'data_year': 2020, 'Incident Count': 47, 'Offense Count': 47},
  {'data_year': 2016, 'Incident Count': 3, 'Offense Count': 3},
  {'data_year': 2020, 'Incident Count': 5, 'Offense Count': 5},
  {'data_year': 2021, 'Incident Count': 10, 'Offense Count': 10},
  {'data_year': 2016, 'Incident Count': 33, 'Offense Count': 33},
  {'data_year': 2021, 'Incident Count': 102, 'Offense Count': 102},
  {'data_year': 2017, 'Incident Count': 12, 'Offense Count': 12},
  {'data_year': 2016, 'Incident Count': 503, 'Offense Count': 503},
  {'data_year': 2020, 'Incident Count': 488, 'Offense Count': 488},
  {'data_year': 2019, 'Incident Count': 78, 'Offense Count': 84}],
 'title': '',
 'ui_type': 'text'}

In [33]:
print(dataAll['CO0010000']['what'][1])
print(type(dataAll['CO0010000']['data'][1]))
for val in dataAll['CO0010000']['data'][1]['title']:
    print(val)

offense,count,violent-crime
<class 'dict'>

In [100]:
response_API = requests.get('https://api.usa.gov/crime/fbi/cde/nibrs/agency/CO0010000/all/offender/count?from=2016&to=2021&API_KEY=iuEO68Q3WH3VppVcdQkMIjb6OSnEJuh4aFkU9cK8')
data = response_API.text
parse_json = json.loads(data)
print(parse_json)

{'keys': ['Count'], 'data': [{'data_year': 2016, 'Count': 301}, {'data_year': 2016, 'Count': 551}, {'data_year': 2016, 'Count': 34}, {'data_year': 2016, 'Count': 12}, {'data_year': 2016, 'Count': 1}, {'data_year': 2016, 'Count': 468}, {'data_year': 2016, 'Count': 153}, {'data_year': 2016, 'Count': 127}, {'data_year': 2016, 'Count': 1132}, {'data_year': 2016, 'Count': 881}, {'data_year': 2016, 'Count': 921}, {'data_year': 2016, 'Count': 2}, {'data_year': 2016, 'Count': 10}, {'data_year': 2016, 'Count': 15}, {'data_year': 2016, 'Count': 33}, {'data_year': 2016, 'Count': 3}, {'data_year': 2016, 'Count': 305}, {'data_year': 2016, 'Count': 4}, {'data_year': 2016, 'Count': 50}, {'data_year': 2016, 'Count': 73}, {'data_year': 2016, 'Count': 1035}, {'data_year': 2016, 'Count': 16}, {'data_year': 2016, 'Count': 3}, {'data_year': 2016, 'Count': 8}, {'data_year': 2016, 'Count': 41}, {'data_year': 2016, 'Count': 6}, {'data_year': 2016, 'Count': 87}, {'data_year': 2016, 'Count': 133}, {'data_year': 2016, 'Count': 7}, {'data_year': 2016, 'Count': 99}, {'data_year': 2016, 'Count': 705}, {'data_year': 2016, 'Count': 7}, {'data_year': 2016, 'Count': 3}, {'data_year': 2016, 'Count': 82}, {'data_year': 2016, 'Count': 256}, {'data_year': 2016, 'Count': 3}, {'data_year': 2016, 'Count': 532}, {'data_year': 2016, 'Count': 320}, {'data_year': 2016, 'Count': 177}, {'data_year': 2016, 'Count': 1}, {'data_year': 2017, 'Count': 336}, {'data_year': 2017, 'Count': 496}, {'data_year': 2017, 'Count': 13}, {'data_year': 2017, 'Count': 39}, {'data_year': 2017, 'Count': 8}, {'data_year': 2017, 'Count': 2}, {'data_year': 2017, 'Count': 448}, {'data_year': 2017, 'Count': 146}, {'data_year': 2017, 'Count': 117}, {'data_year': 2017, 'Count': 1035}, {'data_year': 2017, 'Count': 1013}, {'data_year': 2017, 'Count': 967}, {'data_year': 2017, 'Count': 8}, {'data_year': 2017, 'Count': 12}, {'data_year': 2017, 'Count': 47}, {'data_year': 2017, 'Count': 3}, {'data_year': 2017, 'Count': 351}, {'data_year': 2017, 'Count': 31}, {'data_year': 2017, 'Count': 1}, {'data_year': 2017, 'Count': 38}, {'data_year': 2017, 'Count': 1}, {'data_year': 2017, 'Count': 67}, {'data_year': 2017, 'Count': 1006}, {'data_year': 2017, 'Count': 7}, {'data_year': 2017, 'Count': 5}, {'data_year': 2017, 'Count': 5}, {'data_year': 2017, 'Count': 20}, {'data_year': 2017, 'Count': 1}, {'data_year': 2017, 'Count': 107}, {'data_year': 2017, 'Count': 119}, {'data_year': 2017, 'Count': 5}, {'data_year': 2017, 'Count': 109}, {'data_year': 2017, 'Count': 690}, {'data_year': 2017, 'Count': 16}, {'data_year': 2017, 'Count': 1}, {'data_year': 2017, 'Count': 18}, {'data_year': 2017, 'Count': 268}, {'data_year': 2017, 'Count': 484}, {'data_year': 2017, 'Count': 391}, {'data_year': 2017, 'Count': 186}, {'data_year': 2018, 'Count': 323}, {'data_year': 2018, 'Count': 470}, {'data_year': 2018, 'Count': 10}, {'data_year': 2018, 'Count': 33}, {'data_year': 2018, 'Count': 2}, {'data_year': 2018, 'Count': 8}, {'data_year': 2018, 'Count': 315}, {'data_year': 2018, 'Count': 113}, {'data_year': 2018, 'Count': 82}, {'data_year': 2018, 'Count': 906}, {'data_year': 2018, 'Count': 937}, {'data_year': 2018, 'Count': 901}, {'data_year': 2018, 'Count': 5}, {'data_year': 2018, 'Count': 18}, {'data_year': 2018, 'Count': 39}, {'data_year': 2018, 'Count': 5}, {'data_year': 2018, 'Count': 2}, {'data_year': 2018, 'Count': 383}, {'data_year': 2018, 'Count': 12}, {'data_year': 2018, 'Count': 38}, {'data_year': 2018, 'Count': 68}, {'data_year': 2018, 'Count': 861}, {'data_year': 2018, 'Count': 9}, {'data_year': 2018, 'Count': 1}, {'data_year': 2018, 'Count': 2}, {'data_year': 2018, 'Count': 8}, {'data_year': 2018, 'Count': 5}, {'data_year': 2018, 'Count': 7}, {'data_year': 2018, 'Count': 106}, {'data_year': 2018, 'Count': 85}, {'data_year': 2018, 'Count': 6}, {'data_year': 2018, 'Count': 124}, {'data_year': 2018, 'Count': 597}, {'data_year': 2018, 'Count': 9}, {'data_year': 2018, 'Count': 6}, {'data_year': 2018, 'Count': 1}, {'data_year': 2018, 'Count': 286}, {'data_year': 2018, 'Count': 4}, {'data_year': 2018, 'Count': 417}, {'data_year': 2018, 'Count': 376}, {'data_year': 2018, 'Count': 146}, {'data_year': 2019, 'Count': 326}, {'data_year': 2019, 'Count': 546}, {'data_year': 2019, 'Count': 8}, {'data_year': 2019, 'Count': 23}, {'data_year': 2019, 'Count': 2}, {'data_year': 2019, 'Count': 387}, {'data_year': 2019, 'Count': 129}, {'data_year': 2019, 'Count': 84}, {'data_year': 2019, 'Count': 884}, {'data_year': 2019, 'Count': 1076}, {'data_year': 2019, 'Count': 845}, {'data_year': 2019, 'Count': 8}, {'data_year': 2019, 'Count': 41}, {'data_year': 2019, 'Count': 47}, {'data_year': 2019, 'Count': 4}, {'data_year': 2019, 'Count': 374}, {'data_year': 2019, 'Count': 11}, {'data_year': 2019, 'Count': 2}, {'data_year': 2019, 'Count': 45}, {'data_year': 2019, 'Count': 69}, {'data_year': 2019, 'Count': 985}, {'data_year': 2019, 'Count': 9}, {'data_year': 2019, 'Count': 2}, {'data_year': 2019, 'Count': 8}, {'data_year': 2019, 'Count': 14}, {'data_year': 2019, 'Count': 1}, {'data_year': 2019, 'Count': 5}, {'data_year': 2019, 'Count': 82}, {'data_year': 2019, 'Count': 107}, {'data_year': 2019, 'Count': 116}, {'data_year': 2019, 'Count': 598}, {'data_year': 2019, 'Count': 9}, {'data_year': 2019, 'Count': 7}, {'data_year': 2019, 'Count': 17}, {'data_year': 2019, 'Count': 226}, {'data_year': 2019, 'Count': 5}, {'data_year': 2019, 'Count': 572}, {'data_year': 2019, 'Count': 334}, {'data_year': 2019, 'Count': 182}, {'data_year': 2019, 'Count': 3}, {'data_year': 2020, 'Count': 398}, {'data_year': 2020, 'Count': 587}, {'data_year': 2020, 'Count': 5}, {'data_year': 2020, 'Count': 48}, {'data_year': 2020, 'Count': 2}, {'data_year': 2020, 'Count': 408}, {'data_year': 2020, 'Count': 93}, {'data_year': 2020, 'Count': 106}, {'data_year': 2020, 'Count': 1050}, {'data_year': 2020, 'Count': 606}, {'data_year': 2020, 'Count': 592}, {'data_year': 2020, 'Count': 1}, {'data_year': 2020, 'Count': 7}, {'data_year': 2020, 'Count': 15}, {'data_year': 2020, 'Count': 47}, {'data_year': 2020, 'Count': 12}, {'data_year': 2020, 'Count': 361}, {'data_year': 2020, 'Count': 27}, {'data_year': 2020, 'Count': 35}, {'data_year': 2020, 'Count': 78}, {'data_year': 2020, 'Count': 1195}, {'data_year': 2020, 'Count': 3}, {'data_year': 2020, 'Count': 7}, {'data_year': 2020, 'Count': 16}, {'data_year': 2020, 'Count': 15}, {'data_year': 2020, 'Count': 79}, {'data_year': 2020, 'Count': 120}, {'data_year': 2020, 'Count': 9}, {'data_year': 2020, 'Count': 160}, {'data_year': 2020, 'Count': 542}, {'data_year': 2020, 'Count': 13}, {'data_year': 2020, 'Count': 5}, {'data_year': 2020, 'Count': 43}, {'data_year': 2020, 'Count': 174}, {'data_year': 2020, 'Count': 12}, {'data_year': 2020, 'Count': 642}, {'data_year': 2020, 'Count': 346}, {'data_year': 2020, 'Count': 218}, {'data_year': 2020, 'Count': 3}, {'data_year': 2021, 'Count': 476}, {'data_year': 2021, 'Count': 650}, {'data_year': 2021, 'Count': 11}, {'data_year': 2021, 'Count': 54}, {'data_year': 2021, 'Count': 395}, {'data_year': 2021, 'Count': 51}, {'data_year': 2021, 'Count': 101}, {'data_year': 2021, 'Count': 1188}, {'data_year': 2021, 'Count': 644}, {'data_year': 2021, 'Count': 675}, {'data_year': 2021, 'Count': 9}, {'data_year': 2021, 'Count': 11}, {'data_year': 2021, 'Count': 50}, {'data_year': 2021, 'Count': 12}, {'data_year': 2021, 'Count': 8}, {'data_year': 2021, 'Count': 491}, {'data_year': 2021, 'Count': 12}, {'data_year': 2021, 'Count': 1}, {'data_year': 2021, 'Count': 29}, {'data_year': 2021, 'Count': 75}, {'data_year': 2021, 'Count': 1373}, {'data_year': 2021, 'Count': 11}, {'data_year': 2021, 'Count': 5}, {'data_year': 2021, 'Count': 10}, {'data_year': 2021, 'Count': 1}, {'data_year': 2021, 'Count': 64}, {'data_year': 2021, 'Count': 120}, {'data_year': 2021, 'Count': 4}, {'data_year': 2021, 'Count': 100}, {'data_year': 2021, 'Count': 557}, {'data_year': 2021, 'Count': 8}, {'data_year': 2021, 'Count': 3}, {'data_year': 2021, 'Count': 48}, {'data_year': 2021, 'Count': 109}, {'data_year': 2021, 'Count': 11}, {'data_year': 2021, 'Count': 607}, {'data_year': 2021, 'Count': 489}, {'data_year': 2021, 'Count': 240}, {'data_year': 2021, 'Count': 2}], 'title': '', 'ui_type': 'text'}

In [12]:
parse_json

{'message': 'Missing Authentication Token'}

In [25]:
def seeCols(df):
    for col in sorted(df.columns):
        print(col)

# NIBRS

## Read Data

In [18]:
col = "incident_id"
off = pd.read_csv("data/NIBRS_OFFENSE.csv")
icd = pd.read_csv("data/NIBRS_incident.csv")

In [19]:
off.columns

Index(['data_year', 'offense_id', 'incident_id', 'offense_code',
       'attempt_complete_flag', 'location_id', 'num_premises_entered',
       'method_entry_code'],
      dtype='object')

In [20]:
print(off.shape)
print(icd.shape)

(382636, 8)
(327646, 15)

## Merge Offenses and Incidents

In [21]:
off = off.merge(icd,on=col,how="left")

In [22]:
off.shape

(382636, 22)

In [23]:
off[col].nunique()

327646

In [26]:
seeCols(off)

agency_id
attempt_complete_flag
cargo_theft_flag
cleared_except_date
cleared_except_id
data_home
data_year_x
data_year_y
did
incident_date
incident_hour
incident_id
incident_status
location_id
method_entry_code
nibrs_month_id
num_premises_entered
offense_code
offense_id
orig_format
report_date_flag
submission_date

In [38]:
#off["OFFENSE_TYPE_ID".lower()].value_counts()
len(off["OFFENSE_code".lower()].value_counts())

51

In [30]:
#off["OFFENSE_TYPE_ID"].isna().sum()
off["OFFENSE_CODE".lower()].isna().sum()

0

## Get Name of Offense Committed

In [31]:
offType = pd.read_csv("data/NIBRS_OFFENSE_TYPE.csv")

In [35]:
offType.columns

Index(['offense_code', 'offense_name', 'crime_against', 'ct_flag', 'hc_flag',
       'hc_code', 'offense_category_name', 'offense_group'],
      dtype='object')

In [37]:
#off["OFFENSE_TYPE_ID"].nunique()
off["OFFENSE_CODE".lower()].nunique()

51

In [36]:
#offType["OFFENSE_TYPE_ID"].nunique()
offType["OFFENSE_CODE".lower()].nunique()

86

## Merge Offense Name

In [31]:
off = off.merge(offType,on="OFFENSE_TYPE_ID",how="left")

In [32]:
off.shape

(328469, 30)

In [33]:
seeCols(off)

AGENCY_ID
ATTEMPT_COMPLETE_FLAG
CARGO_THEFT_FLAG
CLEARED_EXCEPT_DATE
CLEARED_EXCEPT_ID
CRIME_AGAINST
CT_FLAG
DATA_HOME
DATA_YEAR_x
DATA_YEAR_y
DID
HC_CODE
HC_FLAG
INCIDENT_DATE
INCIDENT_HOUR
INCIDENT_ID
INCIDENT_STATUS
LOCATION_ID
METHOD_ENTRY_CODE
NIBRS_MONTH_ID
NUM_PREMISES_ENTERED
OFFENSE_CATEGORY_NAME
OFFENSE_CODE
OFFENSE_GROUP
OFFENSE_ID
OFFENSE_NAME
OFFENSE_TYPE_ID
ORIG_FORMAT
REPORT_DATE_FLAG
SUBMISSION_DATE

In [34]:
off["OFFENSE_NAME"].nunique()

51

In [35]:
off["OFFENSE_NAME"].value_counts()

Destruction/Damage/Vandalism of Property       44538
All Other Larceny                              37098
Simple Assault                                 30330
Theft From Motor Vehicle                       29232
Burglary/Breaking & Entering                   22141
Shoplifting                                    22100
Motor Vehicle Theft                            21682
Drug/Narcotic Violations                       20837
Drug Equipment Violations                      12364
Theft From Building                            10915
Aggravated Assault                             10337
Theft of Motor Vehicle Parts or Accessories     8948
False Pretenses/Swindle/Confidence Game         6314
Credit Card/Automated Teller Machine Fraud      5827
Weapon Law Violations                           5773
Impersonation                                   5757
Counterfeiting/Forgery                          5592
Identity Theft                                  4220
Intimidation                                    4033
Robbery                                         3833
Rape                                            2606
Stolen Property Offenses                        2468
Fondling                                        2265
Kidnapping/Abduction                            1905
Arson                                           1048
Sodomy                                           681
Pornography/Obscene Material                     656
Animal Cruelty                                   567
Sexual Assault With An Object                    528
Hacking/Computer Invasion                        492
Embezzlement                                     488
Theft From Coin-Operated Machine or Device       473
Prostitution                                     462
Extortion/Blackmail                              390
Wire Fraud                                       314
Purse-snatching                                  225
Pocket-picking                                   221
Murder and Nonnegligent Manslaughter             203
Statutory Rape                                   144
Assisting or Promoting Prostitution              137
Bribery                                          136
Incest                                            69
Human Trafficking, Commercial Sex Acts            47
Justifiable Homicide                              17
Negligent Manslaughter                            15
Operating/Promoting/Assisting Gambling            11
Welfare Fraud                                     11
Human Trafficking, Involuntary Servitude           7
Gambling Equipment Violation                       6
Purchasing Prostitution                            4
Betting/Wagering                                   2
Name: OFFENSE_NAME, dtype: int64

In [37]:
off['OFFENSE_CODE'].value_counts()

290    44538
23H    37098
13B    30330
23F    29232
220    22141
23C    22100
240    21682
35A    20837
35B    12364
23D    10915
13A    10337
23G     8948
26A     6314
26B     5827
520     5773
26C     5757
250     5592
26F     4220
13C     4033
120     3833
11A     2606
280     2468
11D     2265
100     1905
200     1048
11B      681
370      656
720      567
11C      528
26G      492
270      488
23E      473
40A      462
210      390
26E      314
23B      225
23A      221
09A      203
36B      144
40B      137
510      136
36A       69
64A       47
09C       17
09B       15
39B       11
26D       11
64B        7
39C        6
40C        4
39A        2
Name: OFFENSE_CODE, dtype: int64

In [47]:
off["AGENCY_ID"].nunique()

215

## Agencies

In [2]:
agc = pd.read_csv("data/agencies.csv")

In [44]:
agc.head()

,YEARLY_AGENCY_ID,AGENCY_ID,DATA_YEAR,ORI,LEGACY_ORI,COVERED_BY_LEGACY_ORI,DIRECT_CONTRIBUTOR_FLAG,DORMANT_FLAG,DORMANT_YEAR,REPORTING_TYPE,...,NIBRS_LEOKA_START_DATE,NIBRS_CT_START_DATE,NIBRS_MULTI_BIAS_START_DATE,NIBRS_OFF_ETH_START_DATE,COVERED_FLAG,COUNTY_NAME,MSA_NAME,PUBLISHABLE_FLAG,PARTICIPATED,NIBRS_PARTICIPATED
0,18262017,1826,2017,CO0010000,CO0010000,NaN,N,N,NaN,I,...,01-MAR-03,01-FEB-14,01-JAN-16,01-APR-13,N,ADAMS,"Denver-Aurora-Lakewood, CO",Y,Y,Y
1,18272017,1827,2017,CO0010100,CO0010100,NaN,N,N,NaN,I,...,01-MAR-03,01-FEB-14,01-JAN-16,01-APR-13,N,DOUGLAS; ADAMS; ARAPAHOE,"Denver-Aurora-Lakewood, CO",Y,Y,Y
2,18282017,1828,2017,CO0010200,CO0010200,NaN,N,N,NaN,I,...,01-JAN-06,01-FEB-14,01-JAN-16,01-APR-13,N,WELD; ADAMS,"Denver-Aurora-Lakewood, CO; Greeley, CO",Y,Y,Y
3,18292017,1829,2017,CO0010300,CO0010300,NaN,N,N,NaN,I,...,01-MAR-03,01-FEB-14,01-JAN-16,01-APR-13,N,ADAMS,"Denver-Aurora-Lakewood, CO",Y,Y,Y
4,18302017,1830,2017,CO0010400,CO0010400,NaN,N,N,NaN,I,...,01-SEP-12,01-JUL-14,01-FEB-16,01-APR-13,N,ADAMS,"Denver-Aurora-Lakewood, CO",Y,Y,Y

In [50]:
seeCols(agc)

0
0.1
AGENCY_ID
AGENCY_STATUS
AGENCY_TYPE_NAME
COUNTY_NAME
COVERED_BY_LEGACY_ORI
COVERED_FLAG
DATA_YEAR
DIRECT_CONTRIBUTOR_FLAG
DIVISION_CODE
DIVISION_NAME
DORMANT_FLAG
DORMANT_YEAR
FEMALE_CIVILIAN
FEMALE_OFFICER
LEGACY_ORI
MALE_CIVILIAN
MALE_OFFICER
MIP_FLAG
MSA_NAME
NCIC_AGENCY_NAME
NIBRS_CERT_DATE
NIBRS_CT_START_DATE
NIBRS_LEOKA_START_DATE
NIBRS_MULTI_BIAS_START_DATE
NIBRS_OFF_ETH_START_DATE
NIBRS_PARTICIPATED
NIBRS_START_DATE
ORI
PARENT_POP_GROUP_CODE
PARENT_POP_GROUP_DESC
PARTICIPATED
PED.FEMALE_CIVILIAN+PED.FEMALE_OFFICER
PED.MALE_OFFICER+PED.MALE_CIVILIAN
PE_REPORTED_FLAG
POPULATION
POPULATION_GROUP_CODE
POPULATION_GROUP_DESC
POPULATION_GROUP_ID
POP_SORT_ORDER
PUBLISHABLE_FLAG
PUB_AGENCY_NAME
PUB_AGENCY_UNIT
REGION_CODE
REGION_DESC
REGION_NAME
REPORTING_TYPE
SAI
STATE_ABBR
STATE_ID
STATE_NAME
STATE_POSTAL_ABBR
SUBMITTING_AGENCY_ID
SUBMITTING_AGENCY_NAME
SUBURBAN_AREA_FLAG
SUMMARY_RAPE_DEF
UCR_AGENCY_NAME
YEARLY_AGENCY_ID

In [63]:
#agc["NCIC_AGENCY_NAME"].value_counts()
#agc["MSA_NAME"].value_counts()
#agc["PUB_AGENCY_NAME"].value_counts()
#agc["DIVISION_NAME"].value_counts()
#agc["SUBMITTING_AGENCY_NAME"].value_counts()
#agc["SUBMITTING_AGENCY_NAME"].value_counts()
#agc["UCR_AGENCY_NAME"].value_counts()
#agc["SAI"].value_counts()
#agc["AGENCY_TYPE_NAME"].value_counts()
agc["0.1"].value_counts()

0    220
Name: 0.1, dtype: int64

In [65]:
for col in sorted(agc.columns):
    print(col)
    print(agc[col].value_counts())
    print("-------------------------------")

0
0    220
Name: 0, dtype: int64
-------------------------------
0.1
0    220
Name: 0.1, dtype: int64
-------------------------------
AGENCY_ID
2047    1
1832    1
1844    1
1843    1
1842    1
       ..
1940    1
1938    1
1937    1
1936    1
2050    1
Name: AGENCY_ID, Length: 220, dtype: int64
-------------------------------
AGENCY_STATUS
A    220
Name: AGENCY_STATUS, dtype: int64
-------------------------------
AGENCY_TYPE_NAME
City                     142
County                    58
University or College     14
Other                      3
Other State Agency         2
State Police               1
Name: AGENCY_TYPE_NAME, dtype: int64
-------------------------------
COUNTY_NAME
WELD                19
JEFFERSON           10
EL PASO              9
ARAPAHOE             9
GARFIELD             7
                    ..
JEFFERSON; ADAMS     1
SEDGWICK             1
PITKIN; EAGLE        1
HINSDALE             1
ADAMS; WELD          1
Name: COUNTY_NAME, Length: 74, dtype: int64
-------------------------------
COVERED_BY_LEGACY_ORI
Series([], Name: COVERED_BY_LEGACY_ORI, dtype: int64)
-------------------------------
COVERED_FLAG
N    220
Name: COVERED_FLAG, dtype: int64
-------------------------------
DATA_YEAR
2017    220
Name: DATA_YEAR, dtype: int64
-------------------------------
DIRECT_CONTRIBUTOR_FLAG
N    220
Name: DIRECT_CONTRIBUTOR_FLAG, dtype: int64
-------------------------------
DIVISION_CODE
8    220
Name: DIVISION_CODE, dtype: int64
-------------------------------
DIVISION_NAME
Mountain    220
Name: DIVISION_NAME, dtype: int64
-------------------------------
DORMANT_FLAG
N    220
Name: DORMANT_FLAG, dtype: int64
-------------------------------
DORMANT_YEAR
Series([], Name: DORMANT_YEAR, dtype: int64)
-------------------------------
FEMALE_CIVILIAN
1      39
0      37
3      18
2      15
4       9
6       8
7       8
8       7
5       6
19      6
15      5
11      4
14      3
17      3
13      3
10      3
9       3
23      3
16      2
55      2
18      2
45      2
22      2
32      2
24      1
20      1
21      1
237     1
25      1
213     1
179     1
169     1
161     1
158     1
127     1
124     1
119     1
110     1
103     1
100     1
99      1
89      1
78      1
64      1
61      1
58      1
54      1
52      1
49      1
43      1
40      1
30      1
Name: FEMALE_CIVILIAN, dtype: int64
-------------------------------
FEMALE_OFFICER
0      69
1      52
2      21
3      10
5       9
4       8
7       7
10      4
13      4
6       3
9       3
69      2
35      2
32      2
8       2
11      2
100     2
14      1
12      1
191     1
15      1
17      1
21      1
22      1
23      1
25      1
29      1
37      1
40      1
42      1
44      1
50      1
51      1
87      1
20      1
Name: FEMALE_OFFICER, dtype: int64
-------------------------------
LEGACY_ORI
CO0390100    1
CO0450000    1
CO0320000    1
CO0621100    1
CO0300000    1
            ..
CO0340300    1
CO0590300    1
CO0020000    1
CO0622000    1
CO0070300    1
Name: LEGACY_ORI, Length: 220, dtype: int64
-------------------------------
MALE_CIVILIAN
0      94
1      25
4       9
3       8
8       7
2       7
5       7
10      6
6       5
11      4
9       4
12      3
13      3
14      3
50      2
7       2
77      2
28      2
17      2
18      2
20      1
15      1
16      1
148     1
21      1
56      1
116     1
96      1
89      1
87      1
76      1
60      1
58      1
51      1
143     1
43      1
39      1
36      1
33      1
32      1
27      1
23      1
22      1
Name: MALE_CIVILIAN, dtype: int64
-------------------------------
MALE_OFFICER
7     15
4     13
3     11
9      9
5      9
      ..
82     1
85     1
86     1
90     1
44     1
Name: MALE_OFFICER, Length: 78, dtype: int64
-------------------------------
MIP_FLAG
N    205
Y     15
Name: MIP_FLAG, dtype: int64
-------------------------------
MSA_NAME
Non-MSA                                    118
Denver-Aurora-Lakewood, CO                  45
Greeley, CO                                 19
Colorado Springs, CO                        12
Fort Collins, CO                             6
Boulder, CO                                  6
Grand Junction, CO                           4
Denver-Aurora-Lakewood, CO; Greeley, CO      3
Pueblo, CO                                   3
Fort Collins, CO; Greeley, CO                2
Boulder, CO; Greeley, CO                     2
Name: MSA_NAME, dtype: int64
-------------------------------
NCIC_AGENCY_NAME
EAGLE               2
GUNNISON            2
BOULDER             2
YUMA                2
ALAMOSA             2
                   ..
ADAMS               1
HINSDALE            1
SNOWMASS VILLAGE    1
CHEYENNE            1
FOWLER              1
Name: NCIC_AGENCY_NAME, Length: 211, dtype: int64
-------------------------------
NIBRS_CERT_DATE
01-JAN-92    220
Name: NIBRS_CERT_DATE, dtype: int64
-------------------------------
NIBRS_CT_START_DATE
01-FEB-14    138
01-MAR-14     25
01-APR-14     14
01-MAY-14      8
01-JUN-14      8
01-JUL-14      6
01-AUG-14      4
01-JAN-15      4
01-FEB-15      2
01-OCT-14      2
01-SEP-16      1
01-SEP-15      1
01-OCT-15      1
01-OCT-13      1
01-JAN-16      1
01-NOV-15      1
01-MAR-15      1
01-FEB-17      1
Name: NIBRS_CT_START_DATE, dtype: int64
-------------------------------
NIBRS_LEOKA_START_DATE
01-MAR-03    101
01-APR-03     10
01-JUL-12      8
01-OCT-12      7
01-JUN-12      5
01-SEP-12      5
01-AUG-12      4
01-FEB-11      4
01-OCT-05      4
01-MAR-10      4
01-JUL-03      4
01-DEC-13      3
01-AUG-04      3
01-SEP-06      2
01-FEB-06      2
01-FEB-15      2
01-JUN-05      2
01-JAN-06      2
01-MAY-13      2
01-NOV-03      2
01-MAY-05      2
01-DEC-12      2
01-AUG-06      2
01-JAN-04      2
01-SEP-03      2
01-JAN-13      2
01-NOV-12      2
01-NOV-06      1
01-FEB-13      1
01-FEB-04      1
01-JUN-06      1
01-OCT-14      1
01-JUN-14      1
01-MAR-07      1
01-JUL-06      1
01-APR-06      1
01-DEC-10      1
01-JAN-14      1
01-JUN-03      1
01-JAN-15      1
01-APR-04      1
01-MAY-03      1
01-NOV-05      1
01-MAY-04      1
01-MAR-05      1
01-JAN-05      1
01-AUG-13      1
01-NOV-04      1
01-SEP-04      1
01-SEP-10      1
01-JAN-11      1
01-JUN-10      1
01-JAN-09      1
01-NOV-15      1
01-AUG-11      1
01-SEP-15      1
01-FEB-14      1
Name: NIBRS_LEOKA_START_DATE, dtype: int64
-------------------------------
NIBRS_MULTI_BIAS_START_DATE
01-JAN-16    194
01-FEB-16     14
01-MAR-16      3
01-FEB-17      1
01-JAN-17      1
01-JAN-15      1
01-JAN-18      1
01-SEP-16      1
01-MAR-17      1
01-AUG-16      1
Name: NIBRS_MULTI_BIAS_START_DATE, dtype: int64
-------------------------------
NIBRS_OFF_ETH_START_DATE
01-APR-13    166
01-FEB-14     28
01-MAY-14      4
01-APR-14      4
01-FEB-15      2
01-JAN-15      2
01-MAR-14      2
01-JUL-14      2
01-AUG-14      1
01-SEP-15      1
01-FEB-13      1
01-OCT-14      1
01-MAR-17      1
01-MAR-15      1
01-NOV-15      1
01-JUN-14      1
01-FEB-17      1
Name: NIBRS_OFF_ETH_START_DATE, dtype: int64
-------------------------------
NIBRS_PARTICIPATED
Y    220
Name: NIBRS_PARTICIPATED, dtype: int64
-------------------------------
NIBRS_START_DATE
01-JAN-97    125
01-JAN-12     27
01-JAN-05      8
01-JAN-06      6
01-JAN-11      6
01-JAN-02      3
01-JAN-09      3
01-JAN-04      3
01-JAN-13      2
01-JAN-00      2
01-NOV-98      2
01-JAN-15      2
01-JAN-99      2
01-OCT-98      1
01-FEB-13      1
01-JAN-10      1
01-APR-00      1
01-JAN-08      1
01-JUN-97      1
01-OCT-04      1
01-JUL-03      1
01-MAY-12      1
01-JUL-13      1
01-DEC-14      1
01-JAN-98      1
01-JAN-01      1
01-APR-03      1
01-MAY-97      1
01-SEP-04      1
01-DEC-12      1
01-DEC-97      1
01-AUG-95      1
01-JAN-92      1
01-FEB-14      1
01-FEB-09      1
01-AUG-97      1
01-JAN-03      1
01-JUL-97      1
01-JUL-09      1
01-JAN-14      1
01-JAN-85      1
01-JUL-04      1
Name: NIBRS_START_DATE, dtype: int64
-------------------------------
ORI
CO0390100    1
CO0450000    1
CO0320000    1
CO0621100    1
CO0300000    1
            ..
CO0590300    1
CO0020000    1
CO0622000    1
CO0480100    1
CO0070300    1
Name: ORI, Length: 220, dtype: int64
-------------------------------
PARENT_POP_GROUP_CODE
7    65
6    50
8    44
5    20
9    15
2     9
4     7
3     7
1     3
Name: PARENT_POP_GROUP_CODE, dtype: int64
-------------------------------
PARENT_POP_GROUP_DESC
Cities under 2,500                  65
Cities from 2,500 thru 9,999        50
Non-MSA Counties                    44
Cities from 10,000 thru 24,999      20
MSA Counties                        15
Cities from 100,000 thru 249,000     9
Cities from 50,000 thru 99,000       7
Cities from 25,000 thru 49,999       7
All cities 250,000 or over           3
Name: PARENT_POP_GROUP_DESC, dtype: int64
-------------------------------
PARTICIPATED
Y    220
Name: PARTICIPATED, dtype: int64
-------------------------------
PED.FEMALE_CIVILIAN+PED.FEMALE_OFFICER
1      30
0      26
2      17
4      16
3      15
6       9
5       7
14      7
7       6
9       5
10      5
13      4
23      4
15      4
8       4
29      3
24      3
22      3
11      2
31      2
34      2
25      2
12      2
19      2
18      2
71      2
16      2
75      2
21      2
17      1
26      1
27      1
245     1
196     1
39      1
193     1
176     1
169     1
152     1
147     1
139     1
137     1
370     1
110     1
288     1
99      1
90      1
89      1
80      1
78      1
72      1
69      1
60      1
313     1
53      1
52      1
45      1
44      1
261     1
Name: PED.FEMALE_CIVILIAN+PED.FEMALE_OFFICER, dtype: int64
-------------------------------
PED.MALE_OFFICER+PED.MALE_CIVILIAN
8      12
4      11
7      10
3      10
5       8
       ..
329     1
87      1
90      1
182     1
46      1
Name: PED.MALE_OFFICER+PED.MALE_CIVILIAN, Length: 83, dtype: int64
-------------------------------
PE_REPORTED_FLAG
Y    212
N      8
Name: PE_REPORTED_FLAG, dtype: int64
-------------------------------
POPULATION
0         20
1432       2
912        2
25238      1
2815       1
          ..
1348       1
1858       1
70977      1
111416     1
745        1
Name: POPULATION, Length: 199, dtype: int64
-------------------------------
POPULATION_GROUP_CODE
7     65
6     50
8D    34
5     20
2      9
3      7
9B     7
8C     7
4      7
9A     3
8B     3
9C     3
9D     2
1C     2
1B     1
Name: POPULATION_GROUP_CODE, dtype: int64
-------------------------------
POPULATION_GROUP_DESC
Cities under 2,500                          65
Cities from 2,500 thru 9,999                50
Non-MSA counties under 10,000               34
Cities from 10,000 thru 24,999              20
Cities from 100,000 thru 249,000             9
Non-MSA counties from 10,000 thru 24,999     7
Cities from 25,000 thru 49,999               7
Cities from 50,000 thru 99,000               7
MSA counties from 25,000 thru 99,999         7
MSA counties from 10,000 thru 24,999         3
MSA counties 100,000 or over                 3
Non-MSA counties from 25,000 thru 99,999     3
Cities from 250,000 thru 499,999             2
MSA counties under 10,000                    2
Cities from 500,000 thru 999,999             1
Name: POPULATION_GROUP_DESC, dtype: int64
-------------------------------
POPULATION_GROUP_ID
11    65
10    50
16    34
9     20
6      9
20     7
15     7
8      7
7      7
21     3
19     3
14     3
22     2
5      2
4      1
Name: POPULATION_GROUP_ID, dtype: int64
-------------------------------
POP_SORT_ORDER
2    149
3     59
1     12
Name: POP_SORT_ORDER, dtype: int64
-------------------------------
PUBLISHABLE_FLAG
Y    220
Name: PUBLISHABLE_FLAG, dtype: int64
-------------------------------
PUB_AGENCY_NAME
University of Colorado:     4
Delta                       2
Alamosa                     2
Montrose                    2
Boulder                     2
                           ..
Idaho Springs               1
Wray                        1
Mountain View               1
Colorado School of Mines    1
Hotchkiss                   1
Name: PUB_AGENCY_NAME, Length: 209, dtype: int64
-------------------------------
PUB_AGENCY_UNIT
Boulder                   1
Colorado Springs          1
Health Sciences Center    1
Denver                    1
Name: PUB_AGENCY_UNIT, dtype: int64
-------------------------------
REGION_CODE
4    220
Name: REGION_CODE, dtype: int64
-------------------------------
REGION_DESC
Region IV    220
Name: REGION_DESC, dtype: int64
-------------------------------
REGION_NAME
West    220
Name: REGION_NAME, dtype: int64
-------------------------------
REPORTING_TYPE
I    220
Name: REPORTING_TYPE, dtype: int64
-------------------------------
SAI
COUCR0001    220
Name: SAI, dtype: int64
-------------------------------
STATE_ABBR
CO    220
Name: STATE_ABBR, dtype: int64
-------------------------------
STATE_ID
7    220
Name: STATE_ID, dtype: int64
-------------------------------
STATE_NAME
Colorado    220
Name: STATE_NAME, dtype: int64
-------------------------------
STATE_POSTAL_ABBR
CO    220
Name: STATE_POSTAL_ABBR, dtype: int64
-------------------------------
SUBMITTING_AGENCY_ID
23358    220
Name: SUBMITTING_AGENCY_ID, dtype: int64
-------------------------------
SUBMITTING_AGENCY_NAME
Colorado Bureau of Investigation Uniform Crime Reporting    220
Name: SUBMITTING_AGENCY_NAME, dtype: int64
-------------------------------
SUBURBAN_AREA_FLAG
N    137
Y     83
Name: SUBURBAN_AREA_FLAG, dtype: int64
-------------------------------
SUMMARY_RAPE_DEF
R    220
Name: SUMMARY_RAPE_DEF, dtype: int64
-------------------------------
UCR_AGENCY_NAME
BOULDER       2
ALAMOSA       2
GUNNISON      2
YUMA          2
MONTROSE      2
             ..
MINERAL       1
ROCKY FORD    1
ARAPAHOE      1
ADAMS         1
FOWLER        1
Name: UCR_AGENCY_NAME, Length: 212, dtype: int64
-------------------------------
YEARLY_AGENCY_ID
20102017    1
20972017    1
20622017    1
18772017    1
18682017    1
           ..
19192017    1
19102017    1
18802017    1
19572017    1
20372017    1
Name: YEARLY_AGENCY_ID, Length: 220, dtype: int64
-------------------------------

In [46]:
agc["AGENCY_ID"].nunique()

220

In [ ]:
dfFinal = off[[]]

## Merge Agency info

In [48]:
off = off.merge(agc,on="AGENCY_ID",how="left")

In [49]:
off.shape

(328469, 88)

## CIM Data

### Crime Offenses by Police District 2001-2016 in Colorado

In [ ]:
offCIM = pd.read_csv("https://data.colorado.gov/api/views/ya69-n6ta/rows.csv?accessType=DOWNLOAD")

In [74]:
offCIM.columns

Index(['year', 'policeDistrict', 'type', 'subType', 'count'], dtype='object')

In [75]:
offCIM["subType"].value_counts()

Attempted                   7815
Knife/Cutting Instrument    6898
Other Dangerous Weapon      6898
Hands/Feet/Fist             3449
Firearm                     3449
Unlawful Entry              3449
Other                       3449
By Firearm                  3449
Truck                       3449
Forced Entry                3449
Auto                        3449
StrongArm                   3449
Other Assaults              3449
By Force                     917
Name: subType, dtype: int64

In [13]:
len(df.columns)

NameError: name 'df' is not defined

In [55]:
offCIM["policeDistrict"].value_counts()

Montezuma County Sheriff      410
Pueblo PD                     410
Summit County Sheriff         387
Bent County Sheriff           364
Baca County Sheriff           364
                             ...
Colorado Attorney General       3
Collbran PD                     2
Univ. Southern Colorado PD      2
Sanford PD                      2
Summit County Task Force        1
Name: policeDistrict, Length: 284, dtype: int64

In [42]:
offCIM["subType"].value_counts()

Attempted                   7815
Other Dangerous Weapon      6898
Knife/Cutting Instrument    6898
Auto                        3449
Truck                       3449
Other Assaults              3449
Forced Entry                3449
By Firearm                  3449
Other                       3449
Hands/Feet/Fist             3449
Firearm                     3449
Unlawful Entry              3449
StrongArm                   3449
By Force                     917
Name: subType, dtype: int64

### Crime Arrests by Police District 2001-2016 in Colorado

In [39]:
offArrCIM = pd.read_csv("https://data.colorado.gov/api/views/2e5i-5hfy/rows.csv?accessType=DOWNLOAD")

In [40]:
offArrCIM.head()

,year,adultCount,juvenileCount,type,policeDistrict
0,2015,0.0,0.0,Murder Non Negligent Manslaughter,7th Judicial District Drug Task Force
1,2015,0.0,0.0,Rape,7th Judicial District Drug Task Force
2,2015,0.0,0.0,Robbery,7th Judicial District Drug Task Force
3,2015,0.0,0.0,Aggravated Assault,7th Judicial District Drug Task Force
4,2015,0.0,0.0,Burglary,7th Judicial District Drug Task Force

In [41]:
for col in offArrCIM.columns:
    print(col)

year
adultCount
juvenileCount
type
policeDistrict

In [81]:
offArrCIM["policeDistrict"].value_counts()

Montezuma County Sheriff      486
Pueblo PD                     486
Summit County Sheriff         459
Lafayette PD                  432
Grand Junction PD             432
                             ...
La Veta Marshal                 2
Collbran PD                     2
Sanford PD                      2
Univ. Southern Colorado PD      2
Summit County Task Force        1
Name: policeDistrict, Length: 284, dtype: int64

In [84]:
offArrCIM.loc[offArrCIM[["policeDistrict","type"]].str.contains("Adams County")]

,year,adultCount,juvenileCount,type,policeDistrict
594,2015,6.0,0.0,Murder Non Negligent Manslaughter,Adams County Sheriff
595,2015,11.0,2.0,Rape,Adams County Sheriff
596,2015,25.0,7.0,Robbery,Adams County Sheriff
597,2015,133.0,5.0,Aggravated Assault,Adams County Sheriff
598,2015,46.0,2.0,Burglary,Adams County Sheriff
...,...,...,...,...,...
92618,2016,36.0,0.0,Prostitution,Adams County Sheriff
92651,2016,1.0,0.0,Embezzlement,Adams County Sheriff
92870,2005,46.0,1.0,Other Family Offenses,Adams County Sheriff
92953,2016,3.0,NaN,Vagrancy,Adams County Sheriff
93106,2003,0.0,2.0,Forgery,Adams County Sheriff

In [90]:
offArrCIM.groupby(["policeDistrict","type"]).count()

                                                     year  adultCount  \
policeDistrict                   type
22nd Judical District Task Force Aggravated Assault     6           6
                                 All Other Offenses     6           6
                                 Arson                  6           6
                                 Burglary               6           6
                                 Curfew Violations      6           0
...                                                   ...         ...
Yuma PD                          Runaways              16           0
                                 Stolen Property       16          16
                                 Vagrancy              16          16
                                 Vandalism             16          16
                                 Weapons               16          16

                                                     juvenileCount
policeDistrict                   type
22nd Judical District Task Force Aggravated Assault              6
                                 All Other Offenses              6
                                 Arson                           6
                                 Burglary                        6
                                 Curfew Violations               6
...                                                            ...
Yuma PD                          Runaways                       16
                                 Stolen Property                16
                                 Vagrancy                        0
                                 Vandalism                      16
                                 Weapons                        16

[7474 rows x 3 columns]

In [91]:
df.head()

,Agency,data_year,Aggravated Assault,All Other Offenses (Except Traffic),Arson,Burglary,Curfew and Loitering Law Violations,Disorderly Conduct,Driving Under the Influence,Drug Abuse Violations - Grand Total,...,Prostitution and Commercialized Vice,Rape,Robbery,"Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)",Simple Assault,"Stolen Property: Buying, Receiving, Possessing",Suspicion,Vagrancy,Vandalism,"Weapons: Carrying, Possessing, Etc."
0,Adams County Sheriff's Office,2000,152,4557,9,49,6,63,607,212,...,1,9,10,14,386,37,0,0,107,32
1,Adams County Sheriff's Office,2001,127,4497,7,68,16,169,619,223,...,0,8,25,17,405,46,0,1,118,26
2,Adams County Sheriff's Office,2002,106,4629,6,66,11,132,538,251,...,2,5,10,31,404,87,0,0,99,21
3,Adams County Sheriff's Office,2003,107,5547,2,67,4,76,559,228,...,7,4,11,42,369,57,0,0,117,38
4,Adams County Sheriff's Office,2004,113,6019,4,71,12,108,500,328,...,4,4,19,43,350,68,0,0,103,38

In [82]:
df.head()

,Agency,data_year,Aggravated Assault,All Other Offenses (Except Traffic),Arson,Burglary,Curfew and Loitering Law Violations,Disorderly Conduct,Driving Under the Influence,Drug Abuse Violations - Grand Total,...,Prostitution and Commercialized Vice,Rape,Robbery,"Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)",Simple Assault,"Stolen Property: Buying, Receiving, Possessing",Suspicion,Vagrancy,Vandalism,"Weapons: Carrying, Possessing, Etc."
0,Adams County Sheriff's Office,2000,152,4557,9,49,6,63,607,212,...,1,9,10,14,386,37,0,0,107,32
1,Adams County Sheriff's Office,2001,127,4497,7,68,16,169,619,223,...,0,8,25,17,405,46,0,1,118,26
2,Adams County Sheriff's Office,2002,106,4629,6,66,11,132,538,251,...,2,5,10,31,404,87,0,0,99,21
3,Adams County Sheriff's Office,2003,107,5547,2,67,4,76,559,228,...,7,4,11,42,369,57,0,0,117,38
4,Adams County Sheriff's Office,2004,113,6019,4,71,12,108,500,328,...,4,4,19,43,350,68,0,0,103,38

In [92]:
df.head()

,Agency,data_year,Aggravated Assault,All Other Offenses (Except Traffic),Arson,Burglary,Curfew and Loitering Law Violations,Disorderly Conduct,Driving Under the Influence,Drug Abuse Violations - Grand Total,...,Prostitution and Commercialized Vice,Rape,Robbery,"Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)",Simple Assault,"Stolen Property: Buying, Receiving, Possessing",Suspicion,Vagrancy,Vandalism,"Weapons: Carrying, Possessing, Etc."
0,Adams County Sheriff's Office,2000,152,4557,9,49,6,63,607,212,...,1,9,10,14,386,37,0,0,107,32
1,Adams County Sheriff's Office,2001,127,4497,7,68,16,169,619,223,...,0,8,25,17,405,46,0,1,118,26
2,Adams County Sheriff's Office,2002,106,4629,6,66,11,132,538,251,...,2,5,10,31,404,87,0,0,99,21
3,Adams County Sheriff's Office,2003,107,5547,2,67,4,76,559,228,...,7,4,11,42,369,57,0,0,117,38
4,Adams County Sheriff's Office,2004,113,6019,4,71,12,108,500,328,...,4,4,19,43,350,68,0,0,103,38

In [43]:
df = pd.read_csv("https://data.colorado.gov/resource/xi5f-mkzt.csv")

In [44]:
df.columns

Index(['agency', 'ori', 'year', 'aggravatedassault',
       'allotheroffensesexcepttraffic', 'arson', 'burglary',
       'curfewloiteringlawviolations', 'disorderlyconduct',
       'drivingundertheinfluence', 'drugabuseviolationsgrandtotal',
       'drunkenness', 'embezzlement', 'forgeryandcounterfeiting', 'fraud',
       'gamblingtotal', 'humantraffickingcommerci', 'humantraffickinginvolunt',
       'larcenytheft', 'liquorlaws', 'manslaughterbynegligence',
       'motorvehicletheft', 'murderandnonnegligentman',
       'offensesagainstthefamily', 'prostitutionandcommercia', 'rape',
       'robbery', 'sexoffensesexceptrapeand', 'simpleassault',
       'stolenpropertybuyingrece', 'suspicion', 'vagrancy', 'vandalism',
       'weaponscarryingpossessingetc'],
      dtype='object')

In [6]:
agc[['ncic_agency_name','pub_agency_name','population','county_name']].head()

  ncic_agency_name pub_agency_name  population
0            ADAMS           Adams      100212
1           AURORA          Aurora      392134
2         BRIGHTON        Brighton       41205
3    COMMERCE CITY   Commerce City       65817
4         THORNTON        Thornton      143055

In [4]:
agc.columns

Index(['yearly_agency_id', 'agency_id', 'data_year', 'ori', 'legacy_ori',
       'covered_by_legacy_ori', 'direct_contributor_flag', 'dormant_flag',
       'dormant_year', 'reporting_type', 'ucr_agency_name', 'ncic_agency_name',
       'pub_agency_name', 'pub_agency_unit', 'agency_status', 'state_id',
       'state_name', 'state_abbr', 'state_postal_abbr', 'division_code',
       'division_name', 'region_code', 'region_name', 'region_desc',
       'agency_type_name', 'population', 'submitting_agency_id', 'sai',
       'submitting_agency_name', 'suburban_area_flag', 'population_group_id',
       'population_group_code', 'population_group_desc',
       'parent_pop_group_code', 'parent_pop_group_desc', 'mip_flag',
       'pop_sort_order', 'summary_rape_def', 'pe_reported_flag',
       'male_officer', 'male_civilian', 'male_officer+male_civilian',
       'female_officer', 'female_civilian', 'female_officer+female_civilian',
       'officer_rate', 'employee_rate', 'nibrs_cert_date', 'nibrs_start_date',
       'nibrs_leoka_start_date', 'nibrs_ct_start_date',
       'nibrs_multi_bias_start_date', 'nibrs_off_eth_start_date',
       'covered_flag', 'county_name', 'msa_name', 'publishable_flag',
       'participated', 'nibrs_participated'],
      dtype='object')

In [11]:
agc
agc[["agency_id","ori",'ncic_agency_name','pub_agency_name','population','county_name',
    'agency_type_name']].to_csv("agency_short.csv",index=False)