In [2]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)

In [1]:
def missingAnal(df):
    nrows = df.shape[0]
    print("Total Rows: ",nrows)
    print(f"{'Column':30.30s}   missing   %-miss   Type")
    print(f"-------------------------------------------------------------")
    for col in sorted(df.columns):
        nc = df[col].isna().sum()
        pp = df[col].isna().sum()/nrows*100
        print(f"{col:30.30s}  {nc:8d}   %{pp:4.1f}   {df[col].dtype}")

## Trade Names

In [8]:
dfNew = pd.read_csv("~/bic_etl/cdos/business/business/data_transformed/tradenames-oldway.csv")

In [9]:
dfNew.isna().sum()

masterTradenameId              0
tradenameDescription           5
tradenameForm                828
effectiveDate                  0
firstName                 206836
middleName                234382
lastName                  206836
suffix                    273545
registrantOrganization     68776
address1                      32
address2                  233466
city                          27
state                         30
zipCode                   275612
zipCode4                  275612
country                       27
mailingAddress1           275612
mailingAddress2           257006
mailingCity               137723
mailingState              137728
mailingZipCode            275612
mailingZipCode4           275612
mailingCountry            133190
dateAdded                      0
entityStatus               73596
entityFormDate            275612
entityId                   73596
dtype: int64

In [10]:
for col in dfNew.columns:
    pp = dfNew[col].isna().sum()/dfNew.shape[0]*100
    if (pp > 90):
        print(f"{col:25s}  {pp:.2f}")

suffix                     99.25
zipCode                    100.00
zipCode4                   100.00
mailingAddress1            100.00
mailingAddress2            93.25
mailingZipCode             100.00
mailingZipCode4            100.00
entityFormDate             100.00

In [2]:
dfOrig = pd.read_csv("~/bic_etl/cdos/business/business/data_source/tradenames.tsv",sep="\t",encoding="latin")

In [3]:
dfOrig.columns

Index(['Mstr Trdnm Id', 'Trdnm Dscr', 'Tradename Form', 'Entity Status',
       'Entity Form Date', 'Effective Dtm', 'First Nm', 'Middle Nm', 'Last Nm',
       'Suffix', 'Registrant Organization', 'Address1', 'Address2', 'City',
       'State', 'Zip', 'Country', 'Mailing Address 1', 'Mailing Address 2',
       'Mailing City', 'Mailing State', 'Mailing Zip', 'Mailing Country',
       'Add Dtm', 'Entity ID'],
      dtype='object')

In [4]:
dfOrig.isna().sum()

Mstr Trdnm Id                   0
Trdnm Dscr                      5
Tradename Form                  0
Entity Status               73727
Entity Form Date            73727
Effective Dtm                   0
First Nm                   207031
Middle Nm                  234647
Last Nm                    207030
Suffix                     273865
Registrant Organization     68903
Address1                       32
Address2                   233803
City                           27
State                          30
Zip                            29
Country                        27
Mailing Address 1          137903
Mailing Address 2          257324
Mailing City               137901
Mailing State              137903
Mailing Zip                137901
Mailing Country            133364
Add Dtm                         0
Entity ID                   73727
dtype: int64

In [5]:
for col in dfOrig.columns:
    pp = dfOrig[col].isna().sum()/dfOrig.shape[0]*100
    print(f"{col:25s}  {pp:.2f}")

Mstr Trdnm Id              0.00
Trdnm Dscr                 0.00
Tradename Form             0.00
Entity Status              26.72
Entity Form Date           26.72
Effective Dtm              0.00
First Nm                   75.03
Middle Nm                  85.04
Last Nm                    75.03
Suffix                     99.25
Registrant Organization    24.97
Address1                   0.01
Address2                   84.73
City                       0.01
State                      0.01
Zip                        0.01
Country                    0.01
Mailing Address 1          49.98
Mailing Address 2          93.26
Mailing City               49.98
Mailing State              49.98
Mailing Zip                49.98
Mailing Country            48.33
Add Dtm                    0.00
Entity ID                  26.72

In [2]:
dfFixed = pd.read_csv("~/bic_etl/cdos/business/business/data_transformed/tradenames.csv")

In [3]:
for col in dfFixed.columns:
    pp = dfFixed[col].isna().sum()/dfFixed.shape[0]*100
    print(f"{col:25s}  {pp:.2f}")

masterTradenameId          0.00
tradenameDescription       0.00
tradenameForm              0.30
effectiveDate              0.00
firstName                  75.02
middleName                 85.03
lastName                   75.02
suffix                     99.25
registrantOrganization     24.98
address1                   0.01
address2                   84.73
city                       0.01
state                      0.01
zipCode                    0.01
zipCode4                   92.32
country                    0.01
mailingAddress1            49.98
mailingAddress2            93.25
mailingCity                49.98
mailingState               49.98
mailingZipCode             49.98
mailingZipCode4            96.42
mailingCountry             48.33
dateAdded                  0.00
entityStatus               26.73
entityFormDate             26.73
entityId                   26.73

In [22]:
dfCIMFixed = pd.read_csv("Colorado_Trade_Names.csv")

In [ ]:
dfCIMFixed.isna().sum()

## Trade marks

### Local File Created by Update Script

In [3]:
dfTMs = pd.read_csv("~/bic_etl/cdos/business/business/data_transformed/trademarks.csv")

In [4]:
dfTMs.head()

,masterTrademarkId,entityId,entityName,status,type,registrationDate,dateFirstUsed,expirationDate,goodServiceClass,goodServiceDetail,description,trademarkForm,entityStatus,entityFormDate
0,"""19851006498""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"""19851007191""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"""19851008767""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"""19851008974""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"""19851009395""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
dfTMs.isna().sum()

masterTrademarkId       0
entityId             5045
entityName              0
status                  0
type                    0
registrationDate        0
dateFirstUsed           3
expirationDate          0
goodServiceClass        0
goodServiceDetail       6
description             0
trademarkForm         312
entityStatus         5045
entityFormDate       5045
dtype: int64

In [21]:
dfTMs.columns

Index(['masterTrademarkId', 'entityId', 'entityName', 'status', 'type',
       'registrationDate', 'dateFirstUsed', 'expirationDate',
       'goodServiceClass', 'goodServiceDetail', 'description', 'trademarkForm',
       'entityStatus', 'entityFormDate'],
      dtype='object')

In [50]:
dfTMs.loc[dfTMs["entityFormDate"].notna(),"entityFormDate"].max()

'2023-04-15'

### CIM Dataset from Server

In [29]:
#dfTMCIM = pd.read_csv("Trademarks_for_Businesses_in_Colorado.csv")
dfTMCIM = pd.read_csv("https://data.colorado.gov/api/views/d3m2-b6we/rows.csv?accessType=DOWNLOAD")

In [30]:
dfTMCIM.columns

Index(['masterTrademarkId', 'entityId', 'entityName', 'description',
       'trademarkForm', 'entityStatus', 'entityFormDate', 'status', 'type',
       'registrationDate', 'dateFirstUsed', 'expirationDate',
       'goodServiceClass', 'goodServiceDetail'],
      dtype='object')

In [54]:
dfTMCIM.loc[dfTMCIM["entityformdate"].notna(),"entityformdate"].max()

'12/31/2021'

In [53]:
dfTMCIM.head()

,mastertrademarkid,entityid,entityname,description,trademarkform,entitystatus,entityformdate,status,type,registrationDate,dateFirstUsed,expirationDate,goodServiceClass,goodServiceDetail
0,20161124735,NaN,Judith L Thomas,Body Au Naturale,"Individual, Resident Of Colorado",NaN,NaN,Effective,Standard Character,02/23/2016,01/01/2015,02/23/2026,"044 Medical, Beauty and Agricultural",Health and Beauty products
1,20201282030,NaN,Amy Neary,PRIME IV HYDRATION & WELLNESS. I in Prime is a...,"Individual, Resident Of Colorado",NaN,NaN,Effective,Special Form,03/26/2020,02/20/2020,03/26/2025,"044 Medical, Beauty and Agricultural","Vitamins, minerals, amino acids, and hydration..."
2,20151735982,2.010118e+10,"The Green Solution, LLC",GOLDEN GOAT-M,Limited Liability Company,Good Standing,03/25/2010,Effective,Standard Character,11/17/2015,12/01/2010,11/17/2025,031 Natural Agricultural Products,Horticultural marijuana products including see...
3,20161543781,2.003115e+10,"SHEA PROPERTIES MANAGEMENT COMPANY, INC.",MONTANE,Foreign Corporation,Good Standing,05/09/2003,Effective,Standard Character,08/11/2016,02/01/2016,08/11/2026,037 Construction and Repair,To be used in conjunction with real estate dev...
4,20191901770,2.016161e+10,"Pinnacle Stainless, LLC",PINNACLE STAINLESS,Limited Liability Company,Good Standing,09/06/2016,Effective,Standard Character,11/13/2019,09/06/2016,11/13/2024,007 Machinery,"Centrifuges, batch extractors, and extractors ..."

In [10]:
dfTMCim = pd.read_csv("Trademarks_for_Businesses_in_Colorado_old.csv")

In [11]:
dfTMCim.columns

Index(['mastertrademarkid', 'entityid', 'entityname', 'description',
       'trademarkform', 'entitystatus', 'entityformdate', 'status', 'type',
       'registrationDate', 'dateFirstUsed', 'expirationDate',
       'goodServiceClass', 'goodServiceDetail'],
      dtype='object')

### Original

In [9]:
dfTmOrig = pd.read_csv("~/bic_etl/cdos/business/business/data_source/trademarks-old.tsv",sep="\t")

In [10]:
dfTmOrig.head()

,Master Trademark ID,Entity ID,Entity Status,Entity Form Date,Trademark Description,Registrant Name,Trademark Form,Trademark Status,Trademark Type,Registration Date,Date of First Use,Expiration Date,Goods and Services Class,Goods and Services Detail
0,19851006498,NaN,NaN,NaN,CHALLENGE,"CHALLENGE DAIRY PRODUCTS, INC.",OTH,Effective,Standard Character,12/09/1965 00:00:00,01/01/1930,12/09/2025,029 Meats and Processed Foods,Foods and ingredients of foods
1,19851007191,1.987141e+10,Good Standing,06/20/1980 0:0:0,CASH RESERVE,FIRSTBANK HOLDING COMPANY,Corporation,Effective,Standard Character,06/13/1967 00:00:00,04/12/1967,06/21/2027,036 Insurance and Financial,advertising and description of banking service
2,19851008767,NaN,NaN,NaN,HEAVENLY HASH,ELMER CANDY CORPORATION,OTH,Effective,Standard Character,08/27/1970 00:00:00,07/25/1922,08/27/2025,029 Meats and Processed Foods,CANDY
3,19851008974,1.997109e+10,Good Standing,06/10/1997 0:0:0,JOHNSON'S CORNER,TA Operating LLC,Foreign Limited Liability Company,Effective,Standard Character,06/12/1961 00:00:00,06/12/1961,06/12/2026,043 Hotels and Restaurants,"Resturant, Truck Stop, and Travel Center"
4,19851009395,1.987122e+10,Good Standing,10/26/1970 0:0:0,DINO'S ITALIAN FOOD,"DINO'S ITALIAN FOOD, INC.",Corporation,Effective,Standard Character,10/21/1971 00:00:00,09/30/1961,10/21/2026,043 Hotels and Restaurants,"advertising,signs,radio,tv,print material"

In [8]:
dfTmOrig.dtypes

Master Trademark ID            int64
Entity ID                    float64
Entity Status                 object
Entity Form Date              object
Trademark Description         object
Registrant Name               object
Trademark Form                object
Trademark Status              object
Trademark Type                object
Registration Date             object
Date of First Use             object
Expiration Date               object
Goods and Services Class      object
Goods and Services Detail     object
dtype: object

## Business Entitities

In [46]:
dfBus = pd.read_csv("~/bic_etl/cdos/business/business/data_transformed/business_entities.csv")

/tmp/ipykernel_1610/489019651.py:1: DtypeWarning: Columns (23,29,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfBus = pd.read_csv("~/bic_etl/cdos/business/business/data_transformed/business_entities.csv")

In [9]:
dfBus.isna().sum()

entityId                        0
entityName                      2
principalAddress1           84053
principalAddress2         2118697
principalCity               84181
principalState              84294
principalZipCode            84698
principalCountry            84339
mailingAddress1           1700476
mailingAddress2           2383103
mailingCity               1700437
mailingState              1700426
mailingZipCode            1700476
mailingCountry            1659440
entityStatus                    0
jurisdictonOfFormation          6
entityType                      0
agentFirstName             628749
agentMiddleName           1470053
agentLastName              628749
agentSuffix               2429553
agentOrganizationName     2012253
agentPrincipalAddress1     148971
agentPrincipalAddress2    2128987
agentPrincipalCity         148948
agentPrincipalState        148855
agentPrincipalZipCode      148941
agentPrincipalCountry      148855
agentMailingAddress1      1820648
agentMailingAddress2      2402123
agentMailingCity          1820638
agentMailingState         1820615
agentMailingZipCode       1820637
agentMailingCountry       1820599
entityFormDate                  0
dtype: int64

In [10]:
for col in dfBus.columns:
    print(f"{col:25s}  {dfBus[col].isna().sum()/dfBus.shape[0]*100:.0f}")

entityId                   0
entityName                 0
principalAddress1          3
principalAddress2          85
principalCity              3
principalState             3
principalZipCode           3
principalCountry           3
mailingAddress1            68
mailingAddress2            96
mailingCity                68
mailingState               68
mailingZipCode             68
mailingCountry             67
entityStatus               0
jurisdictonOfFormation     0
entityType                 0
agentFirstName             25
agentMiddleName            59
agentLastName              25
agentSuffix                97
agentOrganizationName      81
agentPrincipalAddress1     6
agentPrincipalAddress2     85
agentPrincipalCity         6
agentPrincipalState        6
agentPrincipalZipCode      6
agentPrincipalCountry      6
agentMailingAddress1       73
agentMailingAddress2       96
agentMailingCity           73
agentMailingState          73
agentMailingZipCode        73
agentMailingCountry        73
entityFormDate             0

In [15]:
dfTod = pd.read_csv("Colorado_Trade_Names.csv")

In [13]:
def percentMiss(df):
    for col in sorted(df.columns):
        print(f"{df[col].isna().sum()/df.shape[0]*100:5.1f}  {col:30s}")

In [25]:
percentMiss(dfTod)

  0.0  address1
 84.7  address2
  0.0  city
  0.0  country
  0.0  dateAdded
  0.0  effectiveDate
 75.0  firstName
 75.0  lastName
100.0  mailingAddress1
 93.3  mailingAddress2
 50.0  mailingCity
 48.3  mailingCountry
 50.0  mailingState
100.0  mailingZipCode
100.0  mailingZipCode4
  0.0  masterTradenameId
 85.0  middleName
 25.0  registrantOrganization
  0.0  state
 99.3  suffix
  0.0  tradenameDescription
  0.3  tradenameForm
100.0  zipCode
100.0  zipCode4

In [26]:
dfYes = pd.read_csv("Colorado_Trade_Names-0418.csv")

In [27]:
percentMiss(dfYes)

  0.0  address1
 84.7  address2
  0.0  city
  0.0  country
  0.0  dateAdded
  0.0  effectiveDate
 75.0  firstName
 75.0  lastName
100.0  mailingAddress1
 93.3  mailingAddress2
 50.0  mailingCity
 48.3  mailingCountry
 50.0  mailingState
100.0  mailingZipCode
100.0  mailingZipCode4
  0.0  masterTradenameId
 85.0  middleName
 25.0  registrantOrganization
  0.0  state
 99.3  suffix
  0.0  tradenameDescription
  0.3  tradenameForm
100.0  zipCode
100.0  zipCode4

In [28]:
dfNew = pd.read_csv("~/bic_etl/cdos/business/business/data_transformed/tradenames.csv")

In [29]:
percentMiss(dfNew)

  0.0  address1
 84.7  address2
  0.0  city
  0.0  country
  0.0  dateAdded
  0.0  effectiveDate
  0.0  entityFormDate
 26.7  entityId
 26.7  entityStatus
 75.0  firstName
 75.0  lastName
 50.0  mailingAddress1
 93.3  mailingAddress2
 50.0  mailingCity
 48.3  mailingCountry
 50.0  mailingState
 50.0  mailingZipCode
 96.4  mailingZipCode4
  0.0  masterTradenameId
 85.0  middleName
 25.0  registrantOrganization
  0.0  state
 99.3  suffix
  0.0  tradenameDescription
  0.3  tradenameForm
  0.0  zipCode
 92.3  zipCode4

In [31]:
sorted(dfYes.columns)

['address1',
 'address2',
 'city',
 'country',
 'dateAdded',
 'effectiveDate',
 'firstName',
 'lastName',
 'mailingAddress1',
 'mailingAddress2',
 'mailingCity',
 'mailingCountry',
 'mailingState',
 'mailingZipCode',
 'mailingZipCode4',
 'masterTradenameId',
 'middleName',
 'registrantOrganization',
 'state',
 'suffix',
 'tradenameDescription',
 'tradenameForm',
 'zipCode',
 'zipCode4']

In [36]:
print(dfYes["effectiveDate"].min())
print(dfYes["effectiveDate"].max())

01/01/1984
12/31/2022

In [32]:
sorted(dfNew.columns)

['address1',
 'address2',
 'city',
 'country',
 'dateAdded',
 'effectiveDate',
 'entityFormDate',
 'entityId',
 'entityStatus',
 'firstName',
 'lastName',
 'mailingAddress1',
 'mailingAddress2',
 'mailingCity',
 'mailingCountry',
 'mailingState',
 'mailingZipCode',
 'mailingZipCode4',
 'masterTradenameId',
 'middleName',
 'registrantOrganization',
 'state',
 'suffix',
 'tradenameDescription',
 'tradenameForm',
 'zipCode',
 'zipCode4']

In [38]:
dfNew["effectiveDate"].max()

'2023-04-18'

In [33]:
dfWhoKnows = pd.read_csv("Trade_Names_for_Businesses_in_Colorado.csv")

In [34]:
percentMiss(dfWhoKnows)

 26.7  Entity ID
  0.0  address1
 84.7  address2
  0.0  city
  0.0  country
  0.0  dateAdded
  0.0  effectiveDate
100.0  entityFormDate
 26.7  entityStatus
 75.0  firstName
 75.0  lastName
100.0  mailingAddress1
 93.3  mailingAddress2
 50.0  mailingCity
 48.3  mailingCountry
 50.0  mailingState
100.0  mailingZipCode
100.0  mailingZipCode4
  0.0  masterTradenameId
 85.0  middleName
 25.0  registrantOrganization
  0.0  state
 99.3  suffix
  0.0  tradenameDescription
  0.3  tradenameForm
100.0  zipCode
100.0  zipCode4

In [37]:
print(dfWhoKnows["effectiveDate"].max())

12/31/2022

In [39]:
dfYes["effectiveDate"] = pd.to_datetime(dfYes["effectiveDate"],format='%m/%d/%Y')

In [40]:
dfYes["effectiveDate"].head()

0   2023-02-28
1   2019-05-06
2   2014-07-14
3   2013-06-28
4   2019-09-13
Name: effectiveDate, dtype: datetime64[ns]

In [41]:
dfNew = pd.read_csv("~/bic_etl/cdos/business/business/data_transformed/tradenames.csv")

In [42]:
dfNew["effectiveDate"].max()

'2023-04-18'

In [11]:
dfCorp = pd.read_csv("~/bic_etl/cdos/business/business/data_transformed/corphist.csv")

/tmp/ipykernel_1455/648824548.py:1: DtypeWarning: Columns (0,1) have mixed types. Specify dtype option on import or set low_memory=False.
  dfCorp = pd.read_csv("~/bic_etl/cdos/business/business/data_transformed/corphist.csv")

In [14]:
percentMiss(dfCorp)

 55.9  comment
  0.0  effectiveDate
  0.0  entityId
  0.0  historyDes
 72.9  name
  0.0  receivedDate
  0.3  transactionId

In [15]:
dfCorp.head()

,entityId,transactionId,historyDes,comment,receivedDate,effectiveDate,name
0,19971190529,NaN,Statement of Renewal of Trademark Registration,"BIG ST, INC.",11/08/2007 12:11,11/08/2007 12:11,NaN
1,19971190528,NaN,Statement of Renewal of Trademark Registration,"BIG ST, INC.",11/08/2007 12:26,11/08/2007 12:26,NaN
2,19871284691,NaN,Statement of Older Periodic Report,CR87 - 02/18/87 - 8703325,12/19/1992 0:00,12/19/1992 0:00,NaN
3,19871373298,NaN,Statement of Older Periodic Report,NaN,12/13/1990 0:00,12/13/1990 0:00,NaN
4,19871074337,NaN,Clarification of entity form,Declare Entity Type,02/15/2005 7:27,02/15/2005 7:27,NaN

In [16]:
dfCorp.tail()

,entityId,transactionId,historyDes,comment,receivedDate,effectiveDate,name
17230917,20211527698,20231421114.0,Statement of Trade Name Renewal of a Person ot...,SHOREVIEW INSURANCE;,04/19/2023 23:30,04/19/2023 23:30,NaN
17230918,20231421115,20231421115.0,Form a Limited Liability Company (LLC),NaN,04/19/2023 23:30,04/19/2023 23:30,Sunray Lawn Care LLC
17230919,20211359108,20231421116.0,Dissolve a Limited Liability Company,NaN,04/19/2023 23:40,04/19/2023 23:40,"JNELS Ranches, LLC, Dissolved April 19, 2023"
17230920,20231421117,20231421117.0,Form a Limited Liability Company (LLC),NaN,04/19/2023 23:47,04/19/2023 23:47,MAM Photography LLC
17230921,20101200443,20231421118.0,File Report,"Principal address changed, Change in registere...",04/19/2023 23:48,04/19/2023 23:48,NaN

In [17]:
dfMast = pd.read_csv("~/bic_etl/cdos/business/business/data_transformed/masterlist.csv")

In [18]:
percentMiss(dfMast)

  8.4  additionalDebtorId
  8.4  additionalDebtors
 10.1  additionalFarmProduct
 14.3  amendmentId
 14.3  amendmentIdVerbatim
 95.6  assignee
 15.0  counties
  0.0  cropYear
  2.8  debtorAddress
  0.4  debtorId
  0.0  debtorName
 10.1  farmProduct
 52.9  recordCountyFiling
 52.9  recordCountyFilingId
  0.0  recordId
  0.0  recordIdDate
  0.0  recordIdVerbatim
  0.3  securedParty

In [19]:
dfMast.head()

,farmProduct,debtorName,debtorId,counties,cropYear,debtorAddress,additionalDebtors,additionalDebtorId,securedParty,assignee,additionalFarmProduct,recordIdVerbatim,recordId,recordIdDate,recordCountyFilingId,recordCountyFiling,amendmentIdVerbatim,amendmentId
0,Cattle And Calves; Hay; Other Field Crops (Spe...,AYARS KENYON K,1.259016e+09,Weld,ALL,"63456 WCR 76, GROVER, CO, 80729",AYARS KENYON K; ID #: 1259016118. AYARS NORMA ...,1259016118;4259017104,"FARMERS BANK, 119 1ST STREET, AULT, CO, 80610;...",NaN,Cattle And Calves;Hay;Other Field Crops (Specify),1999F020838 (277135 - WELD) - 04/19/1999,1999F020838,1999-04-19,277135,Weld,2004F002082 - 01/07/2004; 20182104277 - 11/27/...,2004F002082;20182104277;2000F014085;2008F12003...
1,Hay; Other Field Crops (Specify); Wheat,AYARS KENYON K,1.259016e+09,Weld,ALL,"63456 WCR 76, GROVER, CO, 80729",AYARS KENYON K; ID #: 1259016118. AYARS NORMA ...,1259016118;4259017104,"FARMERS BANK, 119 1ST STREET, AULT, CO, 80610;...",NaN,Hay;Other Field Crops (Specify);Wheat,1999F020838 (277135 - WELD) - 04/19/1999,1999F020838,1999-04-19,277135,Weld,2004F002082 - 01/07/2004; 20182104277 - 11/27/...,2004F002082;20182104277;2000F014085;2008F12003...
2,Cattle And Calves; Hay; Wheat,AYARS KENYON K,1.259016e+09,Weld,ALL,"63456 WCR 76, GROVER, CO, 80729",AYARS KENYON K; ID #: 1259016118. AYARS NORMA ...,1259016118;4259017104,"FARMERS BANK, 119 1ST STREET, AULT, CO, 80610;...",NaN,Cattle And Calves;Hay;Wheat,1999F020838 (277135 - WELD) - 04/19/1999,1999F020838,1999-04-19,277135,Weld,2004F002082 - 01/07/2004; 20182104277 - 11/27/...,2004F002082;20182104277;2000F014085;2008F12003...
3,Cattle And Calves; Hay; Wheat,AYARS KENYON K,1.259016e+09,Weld,ALL,"63456 WCR 76, GROVER, CO, 80729",AYARS KENYON K; ID #: 1259016118. AYARS NORMA ...,1259016118;4259017104,"FARMERS BANK, 119 1ST STREET, AULT, CO, 80610;...",NaN,Cattle And Calves;Hay;Wheat,1999F020838 (277135 - WELD) - 04/19/1999,1999F020838,1999-04-19,277135,Weld,2004F002082 - 01/07/2004; 20182104277 - 11/27/...,2004F002082;20182104277;2000F014085;2008F12003...
4,Cattle And Calves; Other Field Crops (Specify)...,AYARS KENYON K,1.259016e+09,Weld,ALL,"63456 WCR 76, GROVER, CO, 80729",AYARS KENYON K; ID #: 1259016118. AYARS NORMA ...,1259016118;4259017104,"FARMERS BANK, 119 1ST STREET, AULT, CO, 80610;...",NaN,Cattle And Calves;Other Field Crops (Specify);...,1999F020838 (277135 - WELD) - 04/19/1999,1999F020838,1999-04-19,277135,Weld,2004F002082 - 01/07/2004; 20182104277 - 11/27/...,2004F002082;20182104277;2000F014085;2008F12003...

In [20]:
dfMast["recordIdDate"].max()

'2023-03-31'

# Business Entities

### Original Source Data

In [2]:
#df = pd.read_csv("~/bic_etl/cdos/business/business/data_source/corphist-1.tsv",sep="\t",encoding="latin")
dfOrig= pd.read_csv("~/bic_etl/cdos/business/business/data_source/business_entities.tsv",sep="\t",encoding="latin")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (17,25,31,34) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [17]:
df.tail()
df.shape

(9064134, 7)

In [13]:
dfOrig.head()

NameError: name 'dfOrig' is not defined

In [18]:
a = df["Entity Form Date"].value_counts()

In [27]:
pd.set_option('display.max_rows', 5000)
a.shape

(21923,)

In [21]:
display(a)

01/01/2005    1473
01/03/2023    1325
01/05/2023    1320
01/01/2019    1278
01/01/2018    1265
              ...
10/12/1888       1
10/05/1961       1
03/02/1912       1
10/19/1906       1
01/19/1892       1
Name: Entity Form Date, Length: 21923, dtype: int64

In [ ]:
print(df.loc[df["Entity Form Date"] > "05/01/2023"])

In [ ]:
df.tail(100)

In [34]:
a = df["Entity Form Date"].value_counts().sort_index()

In [36]:
print(a.loc[)

01/01/1975      1
01/01/1978      1
01/01/1984      3
01/01/1985      3
01/01/1986     14
             ...
12/31/2018    395
12/31/2019    397
12/31/2020    439
12/31/2021    302
12/31/2022    295
Name: Entity Form Date, Length: 21923, dtype: int64

In [ ]:
df.loc[df["Entity Form Date"] == "05/01/2023"].count()

In [46]:
df.dtypes

Entity Id                     int64
Entity Name                  object
Principal Address 1          object
Principal Address 2          object
Principal City               object
Principal State              object
Principal Zip                object
Principal Country            object
Mailing Address 1            object
Mailing Address 2            object
Mailing City                 object
Mailing State                object
Mailing Zip                  object
Mailing Country              object
Entity Status                object
Jurisdiction of Formation    object
Perpetual Flag               object
Term Date                    object
Entity Type                  object
Agent First Name             object
Agent Middle Name            object
Agent Last Name              object
Agent Suffix                 object
Agent Organization Name      object
Agent Principal Address 1    object
Agent Principal Address 2    object
Agent Principal City         object
Agent Principal State        object
Agent Principal Zip          object
Agent Principal Country      object
Agent Mailing Address 1      object
Agent Mailing Address 2      object
Agent Mailing City           object
Agent Mailing State          object
Agent Mailing Zip            object
Agent Mailing Country        object
Entity Form Date             object
dtype: object

In [16]:
dfOrig.columns

Index(['Entity Id', 'Entity Name', 'Principal Address 1',
       'Principal Address 2', 'Principal City', 'Principal State',
       'Principal Zip', 'Principal Country', 'Mailing Address 1',
       'Mailing Address 2', 'Mailing City', 'Mailing State', 'Mailing Zip',
       'Mailing Country', 'Entity Status', 'Jurisdiction of Formation',
       'Perpetual Flag', 'Term Date', 'Entity Type', 'Agent First Name',
       'Agent Middle Name', 'Agent Last Name', 'Agent Suffix',
       'Agent Organization Name', 'Agent Principal Address 1',
       'Agent Principal Address 2', 'Agent Principal City',
       'Agent Principal State', 'Agent Principal Zip',
       'Agent Principal Country', 'Agent Mailing Address 1',
       'Agent Mailing Address 2', 'Agent Mailing City', 'Agent Mailing State',
       'Agent Mailing Zip', 'Agent Mailing Country', 'Entity Form Date'],
      dtype='object')

In [12]:
inv = invYrMo(dfOrig,"Entity Form Date",'%m/%d/%Y',1)

In [15]:
inv.tail()

,year,month,Day 1,Day 2,Day 3,Day 4,Day 5,Day 6,Day 7,Day 8,Day 9,Day 10,Day 11,Day 12,Day 13,Day 14,Day 15,Day 16,Day 17,Day 18,Day 19,Day 20,Day 21,Day 22,Day 23,Day 24,Day 25,Day 26,Day 27,Day 28,Day 29,Day 30,Day 31
0,2023,1,1096,531,1325,1149,1320,1046,553,294,1145,826,706,668,554,250,247,560,609,666,627,596,289,282,692,693,674,718,560,236,270,683,734
0,2023,2,780,655,633,293,239,748,711,668,734,552,212,209,692,644,724,665,585,242,286,576,662,717,677,739,276,191,793,801,0,0,0
0,2023,3,864,717,583,317,317,755,826,829,707,554,3,233,995,731,736,711,674,257,301,867,816,710,682,565,289,336,799,729,680,739,620
0,2023,4,301,268,766,769,756,575,454,226,220,909,788,694,628,571,325,260,715,684,817,1059,1142,568,317,1055,1101,821,802,781,245,248,0
0,2023,5,959,679,1104,814,940,579,451,1147,1138,1372,401,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
05/01    959
05/02    679
05/03  1,104
05/04     14

### CIM Data

In [3]:
dfBusCIM = pd.read_csv("https://data.colorado.gov/api/views/4ykn-tg5h/rows.csv?accessType=DOWNLOAD")

In [4]:
missingAnal(dfBusCIM)

Total Rows:  2498000
Column                           missing   %-miss   Type
-------------------------------------------------------------
agentfirstname                    630371   %25.2   object
agentlastname                     630378   %25.2   object
agentmailingaddress1             1851141   %74.1   object
agentmailingaddress2             2416290   %96.7   object
agentmailingcity                 1851131   %74.1   object
agentmailingcountry              1851093   %74.1   object
agentmailingstate                1851109   %74.1   object
agentmailingzipcode              1851130   %74.1   object
agentmiddlename                  1482482   %59.3   object
agentorganizationname            2016341   %80.7   object
agentprincipaladdress1            148763   % 6.0   object
agentprincipaladdress2           2146340   %85.9   object
agentprincipalcity                148742   % 6.0   object
agentprincipalcountry             148645   % 6.0   object
agentprincipalstate               148645   % 6.0   object
agentprincipalzipcode             148735   % 6.0   object
agentsuffix                      2435606   %97.5   object
entityformdate                         0   % 0.0   object
entityid                               0   % 0.0   int64
entityname                             2   % 0.0   object
entitystatus                           0   % 0.0   object
entitytype                             0   % 0.0   object
jurisdictonofformation                 6   % 0.0   object
mailingaddress1                  1724766   %69.0   object
mailingaddress2                  2393031   %95.8   object
mailingcity                      1724727   %69.0   object
mailingcountry                   1681849   %67.3   object
mailingstate                     1724718   %69.0   object
mailingzipcode                   1724767   %69.0   object
principaladdress1                  83915   % 3.4   object
principaladdress2                2137226   %85.6   object
principalcity                      84041   % 3.4   object
principalcountry                   84199   % 3.4   object
principalstate                     84154   % 3.4   object
principalzipcode                   84552   % 3.4   object

In [4]:
dfBusCIM.tail()

,entityid,entityname,principaladdress1,principaladdress2,principalcity,principalstate,principalzipcode,principalcountry,mailingaddress1,mailingaddress2,mailingcity,mailingstate,mailingzipcode,mailingcountry,entitystatus,jurisdictonofformation,entitytype,agentfirstname,agentmiddlename,agentlastname,agentsuffix,agentorganizationname,agentprincipaladdress1,agentprincipaladdress2,agentprincipalcity,agentprincipalstate,agentprincipalzipcode,agentprincipalcountry,agentmailingaddress1,agentmailingaddress2,agentmailingcity,agentmailingstate,agentmailingzipcode,agentmailingcountry,entityformdate
2479048,20221541408,RikWebMedia LLC,8108 Otis Ct,NaN,Fort Collins,CO,80528-9225,US,PO Box 272742,NaN,Fort Collins,CO,80527,US,Good Standing,CO,Limited Liability Company,NaN,NaN,NaN,NaN,RikWebMedia LLC,8108 Otis Ct,NaN,Fort Collins,CO,80528-9225,US,PO Box 272742,NaN,Fort Collins,CO,80527,US,05/27/2022
2479049,20221542555,Mindfulness Psychiatry PLLC,7535 East Hampden Ave,Suite 400 - #4617,Denver,CO,80231,US,264 McGregor Lane,NaN,Dawsonville,GA,30534,US,Good Standing,CO,Limited Liability Company,NaN,NaN,NaN,NaN,Werge & Corbin LLC,1627 Vine St,Suite 200,Denver,CO,80206,US,NaN,NaN,NaN,NaN,NaN,NaN,05/27/2022
2479050,20221543135,Save My Project LLC,12731 Stone Valley Dr,NaN,Peyton,CO,80831,US,6050 Stetson Hills Blvd,Suite 248,Colorado Springs,CO,80923,US,Good Standing,CO,Limited Liability Company,Na'Tima,Antyia,Harrison,NaN,NaN,12731 Stone Valley Dr,NaN,Peyton,CO,80831,US,NaN,NaN,NaN,NaN,NaN,NaN,05/27/2022
2479051,20221543948,"AL Locksmith, LLC",6934 Ryan Gulch Road #6934,NaN,Silverthorne,CO,80498,US,PO Box 2002,NaN,Dillon,CO,80435,US,Good Standing,CO,Limited Liability Company,Allen,NaN,Wisniewski,NaN,NaN,6934 Ryan Gulch Road #6934,NaN,Silverthorne,CO,80498,US,PO BOX 2002,NaN,Dillon,CO,80435,US,05/28/2022
2479052,20221544111,"Bountiful Patriot, LLC",98 Wadsworth Blvd.,#127-3393,Lakewood,CO,80226,US,PO Box 2125,NaN,Arvada,CO,80001,US,Good Standing,CO,Limited Liability Company,NaN,NaN,NaN,NaN,"Bountiful Patriot, LLC",98 Wadsworth Blvd.,#127-3393,Lakewood,CO,80226,US,PO Box 2125,NaN,Arvada,CO,80001,US,05/28/2022

In [5]:
dfBusCIM.columns

Index(['entityid', 'entityname', 'principaladdress1', 'principaladdress2',
       'principalcity', 'principalstate', 'principalzipcode',
       'principalcountry', 'mailingaddress1', 'mailingaddress2', 'mailingcity',
       'mailingstate', 'mailingzipcode', 'mailingcountry', 'entitystatus',
       'jurisdictonofformation', 'entitytype', 'agentfirstname',
       'agentmiddlename', 'agentlastname', 'agentsuffix',
       'agentorganizationname', 'agentprincipaladdress1',
       'agentprincipaladdress2', 'agentprincipalcity', 'agentprincipalstate',
       'agentprincipalzipcode', 'agentprincipalcountry',
       'agentmailingaddress1', 'agentmailingaddress2', 'agentmailingcity',
       'agentmailingstate', 'agentmailingzipcode', 'agentmailingcountry',
       'entityformdate'],
      dtype='object')

In [5]:
def invYrMo(df,colDate,formt,type=0):
    if type == 0:  # simple, quick format 
        a = df.copy()
        a["jlcDateInv"] = pd.to_datetime(df[colDate],format=formt)
        a["jlcYear"] = a["jlcDateInv"].dt.year
        a["jlcMonth"] = a["jlcDateInv"].dt.month
        inv = a.groupby(["jlcYear","jlcMonth"]).count()    
    elif type == 1:  # year-month-day, with year and month as columns and thne each day as column w/ a count
        stats = {}
        a = df.copy()
        a["jlcDateInv"] = pd.to_datetime(df[colDate],format=formt)
        a["jlcYear"] = a["jlcDateInv"].dt.year
        a["jlcMonth"] = a["jlcDateInv"].dt.month
        a["jlcDay"] = a["jlcDateInv"].dt.day
        b = a.groupby(["jlcYear","jlcMonth","jlcDay"],as_index=False).count()
        for yr in range(b["jlcYear"].min(),b["jlcYear"].max()+1):
            stats[yr] = {}
            monthLast = 12
            if yr == pd.Timestamp.today().year:
                monthLast = pd.Timestamp.today().month
            for mo in range(1,monthLast+1):
               stats[yr][mo] = {}
               for dy in range(1,32):
                stats[yr][mo][dy]=0

        for indx,row in b.iterrows():
            yr = row["jlcYear"]
            mo = row["jlcMonth"]
            dy = row["jlcDay"]
            cnt = row[colDate]
            stats[yr][mo][dy]=cnt

        nrec=0
        for yr in range(b["jlcYear"].min(),b["jlcYear"].max()+1):
             monthLast = 12
             if yr == pd.Timestamp.today().year:
                monthLast = pd.Timestamp.today().month
             for mo in range(1,monthLast+1):
                lu = {f"Day {nn}":[stats[yr][mo][nn]] for nn in range(1,32)}
                l = {"year":[yr],"month":[mo]}
                l.update(lu)
                tmp = pd.DataFrame(l)
                nrec+=1
                if nrec > 1:
                   inv = pd.concat([inv,tmp])
                else:
                   inv = tmp
    
    return inv

# inv = invYrMo(dfBusCIM,"entityformdate",'%m/%d/%Y',1)
# display(inv.head())
# display(inv.tail())

In [6]:
invCIM = invYrMo(dfBusCIM,"entityformdate",'%m/%d/%Y',1)

In [10]:
dfBusCIM.loc[dfBusCIM["entityformdate"] == "05/10/2023"].count()

entityid                  4
entityname                4
principaladdress1         4
principaladdress2         0
principalcity             4
principalstate            4
principalzipcode          4
principalcountry          4
mailingaddress1           1
mailingaddress2           0
mailingcity               1
mailingstate              1
mailingzipcode            1
mailingcountry            1
entitystatus              4
jurisdictonofformation    4
entitytype                4
agentfirstname            3
agentmiddlename           0
agentlastname             3
agentsuffix               0
agentorganizationname     1
agentprincipaladdress1    4
agentprincipaladdress2    0
agentprincipalcity        4
agentprincipalstate       4
agentprincipalzipcode     4
agentprincipalcountry     4
agentmailingaddress1      1
agentmailingaddress2      0
agentmailingcity          1
agentmailingstate         1
agentmailingzipcode       1
agentmailingcountry       1
entityformdate            4
dtype: int64

In [11]:
dfBusCIM.loc[dfBusCIM["entityformdate"] == "05/09/2023"].count()

entityid                  1138
entityname                1138
principaladdress1         1138
principaladdress2           60
principalcity             1138
principalstate            1138
principalzipcode          1138
principalcountry          1138
mailingaddress1            105
mailingaddress2             11
mailingcity                105
mailingstate               105
mailingzipcode             105
mailingcountry             105
entitystatus              1138
jurisdictonofformation    1138
entitytype                1138
agentfirstname             914
agentmiddlename            140
agentlastname              914
agentsuffix                  9
agentorganizationname      224
agentprincipaladdress1    1138
agentprincipaladdress2      75
agentprincipalcity        1138
agentprincipalstate       1138
agentprincipalzipcode     1138
agentprincipalcountry     1138
agentmailingaddress1       117
agentmailingaddress2        16
agentmailingcity           117
agentmailingstate          117
agentmailingzipcode        117
agentmailingcountry        117
entityformdate            1138
dtype: int64

### Converted

In [7]:
dfXen = pd.read_csv("~/bic_etl/cdos/business/business/data_transformed/business_entities.csv")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (23,29,32) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [19]:
dfXen.columns

Index(['entityId', 'entityName', 'principalAddress1', 'principalAddress2',
       'principalCity', 'principalState', 'principalZipCode',
       'principalCountry', 'mailingAddress1', 'mailingAddress2', 'mailingCity',
       'mailingState', 'mailingZipCode', 'mailingCountry', 'entityStatus',
       'jurisdictonOfFormation', 'entityType', 'agentFirstName',
       'agentMiddleName', 'agentLastName', 'agentSuffix',
       'agentOrganizationName', 'agentPrincipalAddress1',
       'agentPrincipalAddress2', 'agentPrincipalCity', 'agentPrincipalState',
       'agentPrincipalZipCode', 'agentPrincipalCountry',
       'agentMailingAddress1', 'agentMailingAddress2', 'agentMailingCity',
       'agentMailingState', 'agentMailingZipCode', 'agentMailingCountry',
       'entityFormDate'],
      dtype='object')

In [8]:
invXen = invYrMo(dfXen,"entityFormDate",'%Y/%m/%dT%H:%M:%S.%f',1)

In [28]:
inv.tail()

,year,month,Day 1,Day 2,Day 3,Day 4,Day 5,Day 6,Day 7,Day 8,Day 9,Day 10,Day 11,Day 12,Day 13,Day 14,Day 15,Day 16,Day 17,Day 18,Day 19,Day 20,Day 21,Day 22,Day 23,Day 24,Day 25,Day 26,Day 27,Day 28,Day 29,Day 30,Day 31
0,2023,1,1096,531,1325,1149,1320,1046,553,294,1145,826,706,668,554,250,247,560,609,666,627,596,289,282,692,693,674,718,560,236,270,683,734
0,2023,2,780,655,633,293,239,748,711,668,734,552,212,209,692,644,724,665,585,242,286,576,662,717,677,739,276,191,793,801,0,0,0
0,2023,3,864,717,583,317,317,755,826,829,707,554,3,233,995,731,736,711,674,257,301,867,816,710,682,565,289,336,799,729,680,739,620
0,2023,4,301,268,766,769,756,575,454,226,220,909,788,694,628,571,325,260,715,684,817,1059,1142,568,317,1055,1101,821,802,781,245,248,0
0,2023,5,959,679,1104,814,940,579,451,1147,1138,1372,401,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [29]:
dfXen.tail()

,entityId,entityName,principalAddress1,principalAddress2,principalCity,principalState,principalZipCode,principalCountry,mailingAddress1,mailingAddress2,mailingCity,mailingState,mailingZipCode,mailingCountry,entityStatus,jurisdictonOfFormation,entityType,agentFirstName,agentMiddleName,agentLastName,agentSuffix,agentOrganizationName,agentPrincipalAddress1,agentPrincipalAddress2,agentPrincipalCity,agentPrincipalState,agentPrincipalZipCode,agentPrincipalCountry,agentMailingAddress1,agentMailingAddress2,agentMailingCity,agentMailingState,agentMailingZipCode,agentMailingCountry,entityFormDate
2514436,20231512867,Humocolio Solutions LLC,2236 E 109th Dr,NaN,Northglenn,CO,80233,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,Marcio,NaN,Andrade,NaN,NaN,2236 E 109th Dr,NaN,Northglenn,CO,80233,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-11T00:00:00.000
2514437,20231512863,GONZALEZ LLC,16600 Washington St,NaN,Thornton,CO,80023,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,ATILANO,NaN,GONZALEZ,NaN,NaN,16600 Washington St,NaN,Thornton,CO,80023,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-11T00:00:00.000
2514438,20231512877,Holominsa Business LLC,2236 E 109th Dr,NaN,Northglenn,CO,80233,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,Marcio,NaN,Andrade,NaN,NaN,2236 E 109th Dr,NaN,Northglenn,CO,80233,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-11T00:00:00.000
2514439,20231512879,TASF FANI LLC,13395 Voyager Pkwy,STE 130 PMB 2198,Colorado Springs,CO,80921,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,NaN,NaN,NaN,NaN,ECOM AMAZONIC INC.,"13395 Voyager Pkwy Ste 130, Office 2084",NaN,Colorado Springs,CO,80921,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-11T00:00:00.000
2514440,20231512885,Dagny Store LLC,2236 E 109th Drive,NaN,Northglenn,CO,80233,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,MARCIO,NaN,GARCIA ANDRADE,NaN,NaN,2236 E 109th Drive,NaN,Northglenn,CO,80233,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-11T00:00:00.000

In [33]:
dfXen.shape

(2514441, 35)

In [96]:
a = dfBusCIM.isna().sum()
a = a.reset_index()
a.columns = ["entity","Cim"]

In [97]:
b = dfXen.isna().sum()
b = b.reset_index()
b.columns = ["entity","Xen"]

In [101]:
a["entity"] = a["entity"].str.lower()
b["entity"] = b["entity"].str.lower()

In [102]:
a

                    entity      Cim
0                 entityid        0
1               entityname        2
2        principaladdress1    83923
3        principaladdress2  2114255
4            principalcity    84051
5           principalstate    84164
6         principalzipcode    84560
7         principalcountry    84209
8          mailingaddress1  1706390
9          mailingaddress2  2373108
10             mailingcity  1706350
11            mailingstate  1706343
12          mailingzipcode  1706390
13          mailingcountry  1664625
14            entitystatus        0
15  jurisdictonofformation        6
16              entitytype        0
17          agentfirstname   624699
18         agentmiddlename  1466753
19           agentlastname   624697
20             agentsuffix  2416956
21   agentorganizationname  2002590
22  agentprincipaladdress1   148285
23  agentprincipaladdress2  2123575
24      agentprincipalcity   148264
25     agentprincipalstate   148169
26   agentprincipalzipcode   148257
27   agentprincipalcountry   148169
28    agentmailingaddress1  1828157
29    agentmailingaddress2  2394141
30        agentmailingcity  1828147
31       agentmailingstate  1828125
32     agentmailingzipcode  1828146
33     agentmailingcountry  1828109
34          entityformdate        0

In [103]:
b

                    entity      Xen
0                 entityid        0
1               entityname        2
2        principaladdress1    84045
3        principaladdress2  2143762
4            principalcity    84172
5           principalstate    84285
6         principalzipcode    84689
7         principalcountry    84330
8          mailingaddress1  1720528
9          mailingaddress2  2406030
10             mailingcity  1720486
11            mailingstate  1720479
12          mailingzipcode  1720528
13          mailingcountry  1678659
14            entitystatus        0
15  jurisdictonofformation        6
16              entitytype        0
17          agentfirstname   633640
18         agentmiddlename  1488294
19           agentlastname   633638
20             agentsuffix  2451605
21   agentorganizationname  2030031
22  agentprincipaladdress1   149280
23  agentprincipaladdress2  2154280
24      agentprincipalcity   149258
25     agentprincipalstate   149163
26   agentprincipalzipcode   149251
27   agentprincipalcountry   149163
28    agentmailingaddress1  1845315
29    agentmailingaddress2  2426952
30        agentmailingcity  1845305
31       agentmailingstate  1845283
32     agentmailingzipcode  1845304
33     agentmailingcountry  1845267
34          entityformdate        0

In [104]:
c = a.merge(b)

In [106]:
c["diff"] = c["Xen"] - c["Cim"]

In [107]:
display(c)

                    entity      Cim      Xen   diff
0                 entityid        0        0      0
1               entityname        2        2      0
2        principaladdress1    83923    84045    122
3        principaladdress2  2114255  2143762  29507
4            principalcity    84051    84172    121
5           principalstate    84164    84285    121
6         principalzipcode    84560    84689    129
7         principalcountry    84209    84330    121
8          mailingaddress1  1706390  1720528  14138
9          mailingaddress2  2373108  2406030  32922
10             mailingcity  1706350  1720486  14136
11            mailingstate  1706343  1720479  14136
12          mailingzipcode  1706390  1720528  14138
13          mailingcountry  1664625  1678659  14034
14            entitystatus        0        0      0
15  jurisdictonofformation        6        6      0
16              entitytype        0        0      0
17          agentfirstname   624699   633640   8941
18         agentmiddlename  1466753  1488294  21541
19           agentlastname   624697   633638   8941
20             agentsuffix  2416956  2451605  34649
21   agentorganizationname  2002590  2030031  27441
22  agentprincipaladdress1   148285   149280    995
23  agentprincipaladdress2  2123575  2154280  30705
24      agentprincipalcity   148264   149258    994
25     agentprincipalstate   148169   149163    994
26   agentprincipalzipcode   148257   149251    994
27   agentprincipalcountry   148169   149163    994
28    agentmailingaddress1  1828157  1845315  17158
29    agentmailingaddress2  2394141  2426952  32811
30        agentmailingcity  1828147  1845305  17158
31       agentmailingstate  1828125  1845283  17158
32     agentmailingzipcode  1828146  1845304  17158
33     agentmailingcountry  1828109  1845267  17158
34          entityformdate        0        0      0

In [108]:
dfXen.shape

(2514441, 35)

In [110]:
dfBusCIM.shape

(2479053, 35)

In [111]:
dfXen.shape[0] - dfBusCIM.shape[0]

35388

In [114]:
invXen

,year,month,Day 1,Day 2,Day 3,Day 4,Day 5,Day 6,Day 7,Day 8,Day 9,Day 10,Day 11,Day 12,Day 13,Day 14,Day 15,Day 16,Day 17,Day 18,Day 19,Day 20,Day 21,Day 22,Day 23,Day 24,Day 25,Day 26,Day 27,Day 28,Day 29,Day 30,Day 31
0,1864,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,1864,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,1864,3,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,1864,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,1864,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2023,1,1096,531,1325,1149,1320,1046,553,294,1145,826,706,668,554,250,247,560,609,666,627,596,289,282,692,693,674,718,560,236,270,683,734
0,2023,2,780,655,633,293,239,748,711,668,734,552,212,209,692,644,724,665,585,242,286,576,662,717,677,739,276,191,793,801,0,0,0
0,2023,3,864,717,583,317,317,755,826,829,707,554,3,233,995,731,736,711,674,257,301,867,816,710,682,565,289,336,799,729,680,739,620
0,2023,4,301,268,766,769,756,575,454,226,220,909,788,694,628,571,325,260,715,684,817,1059,1142,568,317,1055,1101,821,802,781,245,248,0
0,2023,5,959,679,1104,814,940,579,451,1147,1138,1372,401,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [115]:
invCIM

,year,month,Day 1,Day 2,Day 3,Day 4,Day 5,Day 6,Day 7,Day 8,Day 9,Day 10,Day 11,Day 12,Day 13,Day 14,Day 15,Day 16,Day 17,Day 18,Day 19,Day 20,Day 21,Day 22,Day 23,Day 24,Day 25,Day 26,Day 27,Day 28,Day 29,Day 30,Day 31
0,1864,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,1864,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,1864,3,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,1864,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,1864,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2023,1,1096,531,1325,1149,1320,1046,553,294,1145,826,706,668,554,250,247,560,609,666,627,596,289,282,692,693,675,718,560,236,270,684,734
0,2023,2,777,655,633,293,239,748,711,668,734,552,212,209,692,644,724,665,585,242,286,576,662,717,677,739,276,191,793,801,0,0,0
0,2023,3,864,717,583,317,317,755,826,829,707,554,3,233,995,731,736,711,674,257,301,867,816,710,682,565,289,336,799,729,680,739,620
0,2023,4,301,268,766,769,756,575,454,226,220,909,788,694,628,571,325,260,715,684,817,1059,1142,568,317,1055,1101,821,802,781,245,248,0
0,2023,5,959,679,1104,814,940,579,451,1147,1138,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [120]:
d = invXen["year"]
d["month"] = invXen["month"]

In [123]:
d = invXen - invCIM

In [124]:
d["year"] = invXen["year"]
d["month"] = invXen["month"]

In [125]:
d.head()

,year,month,Day 1,Day 2,Day 3,Day 4,Day 5,Day 6,Day 7,Day 8,Day 9,Day 10,Day 11,Day 12,Day 13,Day 14,Day 15,Day 16,Day 17,Day 18,Day 19,Day 20,Day 21,Day 22,Day 23,Day 24,Day 25,Day 26,Day 27,Day 28,Day 29,Day 30,Day 31
0,1864,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,1864,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,1864,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,1864,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,1864,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [126]:
d.tail()

,year,month,Day 1,Day 2,Day 3,Day 4,Day 5,Day 6,Day 7,Day 8,Day 9,Day 10,Day 11,Day 12,Day 13,Day 14,Day 15,Day 16,Day 17,Day 18,Day 19,Day 20,Day 21,Day 22,Day 23,Day 24,Day 25,Day 26,Day 27,Day 28,Day 29,Day 30,Day 31
0,2023,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,-1,0
0,2023,2,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,2023,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,2023,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,2023,5,0,0,0,0,0,0,0,0,0,1368,401,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [127]:
dfBusCIM.shape

(2479053, 35)

In [128]:
dfXen.shape

(2514441, 35)

In [129]:
dfXen.shape[0] - dfBusCIM.shape[0]

35388

In [142]:
dfXen.columns

Index(['entityId', 'entityName', 'principalAddress1', 'principalAddress2',
       'principalCity', 'principalState', 'principalZipCode',
       'principalCountry', 'mailingAddress1', 'mailingAddress2', 'mailingCity',
       'mailingState', 'mailingZipCode', 'mailingCountry', 'entityStatus',
       'jurisdictonOfFormation', 'entityType', 'agentFirstName',
       'agentMiddleName', 'agentLastName', 'agentSuffix',
       'agentOrganizationName', 'agentPrincipalAddress1',
       'agentPrincipalAddress2', 'agentPrincipalCity', 'agentPrincipalState',
       'agentPrincipalZipCode', 'agentPrincipalCountry',
       'agentMailingAddress1', 'agentMailingAddress2', 'agentMailingCity',
       'agentMailingState', 'agentMailingZipCode', 'agentMailingCountry',
       'entityFormDate'],
      dtype='object')

In [146]:
x = dfXen.copy()
x["entityFormDate"] = pd.to_datetime(x["entityFormDate"],format='%Y/%m/%dT%H:%M:%S.%f')

In [164]:
x.drop_duplicates(inplace=True)

In [165]:
x.shape

(2481249, 35)

In [166]:
c.shape

(2479053, 36)

In [167]:
x.shape[0] - c.shape[0]

2196

In [156]:
c = dfBusCIM.copy()
c["entityFormDate"] = pd.to_datetime(c["entityformdate"],format='%m/%d/%Y')
c["entityFormDate"].head()

0   1886-03-29
1   1888-12-29
2   1891-07-01
3   1891-05-23
4   1903-03-31
Name: entityFormDate, dtype: datetime64[ns]

In [162]:
#print(x.loc[x["entityFormDate"] == "1865-11-30",["entityId","entityName","entityFormDate"]])
#print(c.loc[c["entityFormDate"] == "1865-11-30",["entityid","entityname","entityFormDate"]])


display(x.loc[x["entityFormDate"] == "1865-11-30"])
display(c.loc[c["entityFormDate"] == "1865-11-30"])

,entityId,entityName,principalAddress1,principalAddress2,principalCity,principalState,principalZipCode,principalCountry,mailingAddress1,mailingAddress2,mailingCity,mailingState,mailingZipCode,mailingCountry,entityStatus,jurisdictonOfFormation,entityType,agentFirstName,agentMiddleName,agentLastName,agentSuffix,agentOrganizationName,agentPrincipalAddress1,agentPrincipalAddress2,agentPrincipalCity,agentPrincipalState,agentPrincipalZipCode,agentPrincipalCountry,agentMailingAddress1,agentMailingAddress2,agentMailingCity,agentMailingState,agentMailingZipCode,agentMailingCountry,entityFormDate
23221,19871000162,BIG THOMPSON AND PLATTE RIVER DITCH COMPANY,23143 WCR 21 3/4,NaN,Milliken,CO,80543,US,P.O. Box 181,NaN,Milliken,CO,80543,US,Good Standing,CO,Nonprofit Corporation,MICHELLE,NaN,ORWICK,NaN,NaN,23143 WCR 21 3/4,NaN,MILLIKEN,CO,80543,US,P.O. Box 181,NaN,Milliken,CO,80543,US,1865-11-30
23222,19871000162,BIG THOMPSON AND PLATTE RIVER DITCH COMPANY,23143 WCR 21 3/4,NaN,Milliken,CO,80543,US,P.O. Box 181,NaN,Milliken,CO,80543,US,Good Standing,CO,Nonprofit Corporation,MICHELLE,NaN,ORWICK,NaN,NaN,23143 WCR 21 3/4,NaN,MILLIKEN,CO,80543,US,P.O. Box 181,NaN,Milliken,CO,80543,US,1865-11-30

,entityid,entityname,principaladdress1,principaladdress2,principalcity,principalstate,principalzipcode,principalcountry,mailingaddress1,mailingaddress2,mailingcity,mailingstate,mailingzipcode,mailingcountry,entitystatus,jurisdictonofformation,entitytype,agentfirstname,agentmiddlename,agentlastname,agentsuffix,agentorganizationname,agentprincipaladdress1,agentprincipaladdress2,agentprincipalcity,agentprincipalstate,agentprincipalzipcode,agentprincipalcountry,agentmailingaddress1,agentmailingaddress2,agentmailingcity,agentmailingstate,agentmailingzipcode,agentmailingcountry,entityformdate,entityFormDate
2402357,19871000162,BIG THOMPSON AND PLATTE RIVER DITCH COMPANY,23143 WCR 21 3/4,NaN,Milliken,CO,80543,US,P.O. Box 181,NaN,Milliken,CO,80543,US,Good Standing,CO,Nonprofit Corporation,MICHELLE,NaN,ORWICK,NaN,NaN,23143 WCR 21 3/4,NaN,MILLIKEN,CO,80543,US,P.O. Box 181,NaN,Milliken,CO,80543,US,11/30/1865,1865-11-30

In [158]:
c.columns

Index(['entityid', 'entityname', 'principaladdress1', 'principaladdress2',
       'principalcity', 'principalstate', 'principalzipcode',
       'principalcountry', 'mailingaddress1', 'mailingaddress2', 'mailingcity',
       'mailingstate', 'mailingzipcode', 'mailingcountry', 'entitystatus',
       'jurisdictonofformation', 'entitytype', 'agentfirstname',
       'agentmiddlename', 'agentlastname', 'agentsuffix',
       'agentorganizationname', 'agentprincipaladdress1',
       'agentprincipaladdress2', 'agentprincipalcity', 'agentprincipalstate',
       'agentprincipalzipcode', 'agentprincipalcountry',
       'agentmailingaddress1', 'agentmailingaddress2', 'agentmailingcity',
       'agentmailingstate', 'agentmailingzipcode', 'agentmailingcountry',
       'entityformdate', 'entityFormDate'],
      dtype='object')

In [ ]:
totl=0
for index,row in d.iterrows():
    for day in range(1,32):
        if row[f"Day {day}"] != 0:
            print(row["year"],row["month"],day,row[f"Day {day}"])
            totl+=row[f"Day {day}"]
            
print(totl)

In [169]:
x.columns

Index(['entityId', 'entityName', 'principalAddress1', 'principalAddress2',
       'principalCity', 'principalState', 'principalZipCode',
       'principalCountry', 'mailingAddress1', 'mailingAddress2', 'mailingCity',
       'mailingState', 'mailingZipCode', 'mailingCountry', 'entityStatus',
       'jurisdictonOfFormation', 'entityType', 'agentFirstName',
       'agentMiddleName', 'agentLastName', 'agentSuffix',
       'agentOrganizationName', 'agentPrincipalAddress1',
       'agentPrincipalAddress2', 'agentPrincipalCity', 'agentPrincipalState',
       'agentPrincipalZipCode', 'agentPrincipalCountry',
       'agentMailingAddress1', 'agentMailingAddress2', 'agentMailingCity',
       'agentMailingState', 'agentMailingZipCode', 'agentMailingCountry',
       'entityFormDate'],
      dtype='object')

In [170]:
x["mailingAddress1"].isna().sum()

1708246

In [171]:
c["mailingaddress1"].isna().sum()

1706390

In [176]:
x.loc[x["entityFormDate"] == "2023-05-09","mailingAddress1"].isna().sum()

1033

In [181]:
c.loc[c["entityFormDate"] == "2023-05-09","mailingaddress1"].isna().sum()/c.loc[c["entityFormDate"] == "2023-05-09"].shape[0]

0.9077328646748682

In [180]:
c.loc[c["entityFormDate"] == "2023-05-09"].shape[0]

1138

In [199]:
dates = x["entityFormDate"].sort_values().unique()
dates

array(['1864-03-05T00:00:00.000000000', '1865-06-30T00:00:00.000000000',
       '1865-11-30T00:00:00.000000000', ...,
       '2023-05-09T00:00:00.000000000', '2023-05-10T00:00:00.000000000',
       '2023-05-11T00:00:00.000000000'], dtype='datetime64[ns]')

In [ ]:
dft=0
#for date in x.loc[x["entityFormDate"] >= "2023-01-01","entityFormDate"].sort_values().unique():

for date in dates:
#    cp = c.loc[c["entityFormDate"] == date,"mailingaddress1"].isna().sum()/c.loc[c["entityFormDate"] == date].shape[0]
#    xp = x.loc[x["entityFormDate"] == date,"mailingAddress1"].isna().sum()/x.loc[x["entityFormDate"] == date].shape[0]
    cp = c.loc[c["entityFormDate"] == date,"mailingaddress1"].isna().sum()
    xp = x.loc[x["entityFormDate"] == date,"mailingAddress1"].isna().sum()
    dif = abs(xp-cp)
    dft+=dif
    if (dif > 0):
      print(date,cp,xp,dif,dft)

In [202]:
x.columns

Index(['entityId', 'entityName', 'principalAddress1', 'principalAddress2',
       'principalCity', 'principalState', 'principalZipCode',
       'principalCountry', 'mailingAddress1', 'mailingAddress2', 'mailingCity',
       'mailingState', 'mailingZipCode', 'mailingCountry', 'entityStatus',
       'jurisdictonOfFormation', 'entityType', 'agentFirstName',
       'agentMiddleName', 'agentLastName', 'agentSuffix',
       'agentOrganizationName', 'agentPrincipalAddress1',
       'agentPrincipalAddress2', 'agentPrincipalCity', 'agentPrincipalState',
       'agentPrincipalZipCode', 'agentPrincipalCountry',
       'agentMailingAddress1', 'agentMailingAddress2', 'agentMailingCity',
       'agentMailingState', 'agentMailingZipCode', 'agentMailingCountry',
       'entityFormDate'],
      dtype='object')

In [203]:
c.columns

Index(['entityid', 'entityname', 'principaladdress1', 'principaladdress2',
       'principalcity', 'principalstate', 'principalzipcode',
       'principalcountry', 'mailingaddress1', 'mailingaddress2', 'mailingcity',
       'mailingstate', 'mailingzipcode', 'mailingcountry', 'entitystatus',
       'jurisdictonofformation', 'entitytype', 'agentfirstname',
       'agentmiddlename', 'agentlastname', 'agentsuffix',
       'agentorganizationname', 'agentprincipaladdress1',
       'agentprincipaladdress2', 'agentprincipalcity', 'agentprincipalstate',
       'agentprincipalzipcode', 'agentprincipalcountry',
       'agentmailingaddress1', 'agentmailingaddress2', 'agentmailingcity',
       'agentmailingstate', 'agentmailingzipcode', 'agentmailingcountry',
       'entityformdate', 'entityFormDate'],
      dtype='object')

In [204]:
x.columns = x.columns.str.lower()

In [206]:
c.drop("entityformdate",inplace=True,axis=1)

In [207]:
c.columns = c.columns.str.lower()

In [209]:
x.shape

(2481249, 35)

In [210]:
c.shape

(2479053, 35)

In [211]:
x.head()

,entityid,entityname,principaladdress1,principaladdress2,principalcity,principalstate,principalzipcode,principalcountry,mailingaddress1,mailingaddress2,mailingcity,mailingstate,mailingzipcode,mailingcountry,entitystatus,jurisdictonofformation,entitytype,agentfirstname,agentmiddlename,agentlastname,agentsuffix,agentorganizationname,agentprincipaladdress1,agentprincipaladdress2,agentprincipalcity,agentprincipalstate,agentprincipalzipcode,agentprincipalcountry,agentmailingaddress1,agentmailingaddress2,agentmailingcity,agentmailingstate,agentmailingzipcode,agentmailingcountry,entityformdate
0,20011001058,"DODGETON CREEK INN, LLC",137 CUCHARA AVE EAST,NaN,Cuchara,CO,81055,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,MICHAEL,R.,MOORE,NaN,NaN,137 CUCHARA AVE EAST,NaN,Cuchara,CO,81055,US,NaN,NaN,NaN,NaN,NaN,NaN,2001-01-03
1,20001243352,"THE MAIN EVENT MARKETING & PROMOTIONS, INC",1455 Manitou Avenue,NaN,Steamboat Springs,CO,80487,US,PO Box 771869,NaN,Steamboat Springs,CO,80477,US,Good Standing,CO,Corporation,Jill,NaN,Waldman,NaN,NaN,1455 Manitou Avenue,NaN,STEAMBOAT SPRINGS,CO,80477,US,PO BOX 771869,NaN,STEAMBOAT SPRINGS,CO,80477,US,2000-12-13
2,19961076960,"HAL-MAR INVESTMENTS, LLC",601 N. PERRY STREET,NaN,Denver,CO,80204,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,HAROLD,H.,JENSEN,NaN,NaN,601 N. PERRY STREET,NaN,DENVER,CO,80204,US,3127 W. Tanforan Dr,NaN,Englewood,CO,80110,US,1996-06-07
3,20001243280,"NUNET SOLUTIONS, INC.",7847 Jared Way,NaN,Littleton,CO,80125,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Corporation,JOHN,W.,DILLON,NaN,NaN,7847 Jared Way,NaN,Littleton,CO,80125,US,7847 Jared Way,NaN,Littleton,CO,80125,US,2000-12-13
4,20051121021,"Sundog Creative Carpentry, Delinquent May 1, 2006",0876 Six Lazy K Road,NaN,New Castle,CO,81647,US,NaN,NaN,NaN,NaN,NaN,NaN,Delinquent,CO,Limited Liability Company,Teran,NaN,Hughes,NaN,NaN,0876 Six Lazy K Road,NaN,New Castle,CO,81647,US,NaN,NaN,NaN,NaN,NaN,NaN,2005-03-22

In [213]:
xx=x.iloc[:2479053]

In [214]:
xx.shape

(2479053, 35)

In [215]:
xx.compare(c)

ValueError: Can only compare identically-labeled DataFrame objects

In [217]:
# customer_df_2020.set_index('customer_id',inplace=True)
# customer_df_2021.set_index('customer_id',inplace=True)

sameidx = xx.index.intersection(c.index)
len(sameidx)
# temp_df  = (customer_df_2020.loc[sameidx, BOOL_FIELDS] != 
#             customer_df_2021.loc[sameidx, BOOL_FIELDS])

2445919

In [219]:
xx.reset_index(inplace=True)

In [220]:
sameidx = xx.index.intersection(c.index)
len(sameidx)

2479053

In [222]:
xx.drop("index",axis=1,inplace=True)

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [223]:
xx.head()

,entityid,entityname,principaladdress1,principaladdress2,principalcity,principalstate,principalzipcode,principalcountry,mailingaddress1,mailingaddress2,mailingcity,mailingstate,mailingzipcode,mailingcountry,entitystatus,jurisdictonofformation,entitytype,agentfirstname,agentmiddlename,agentlastname,agentsuffix,agentorganizationname,agentprincipaladdress1,agentprincipaladdress2,agentprincipalcity,agentprincipalstate,agentprincipalzipcode,agentprincipalcountry,agentmailingaddress1,agentmailingaddress2,agentmailingcity,agentmailingstate,agentmailingzipcode,agentmailingcountry,entityformdate
0,20011001058,"DODGETON CREEK INN, LLC",137 CUCHARA AVE EAST,NaN,Cuchara,CO,81055,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,MICHAEL,R.,MOORE,NaN,NaN,137 CUCHARA AVE EAST,NaN,Cuchara,CO,81055,US,NaN,NaN,NaN,NaN,NaN,NaN,2001-01-03
1,20001243352,"THE MAIN EVENT MARKETING & PROMOTIONS, INC",1455 Manitou Avenue,NaN,Steamboat Springs,CO,80487,US,PO Box 771869,NaN,Steamboat Springs,CO,80477,US,Good Standing,CO,Corporation,Jill,NaN,Waldman,NaN,NaN,1455 Manitou Avenue,NaN,STEAMBOAT SPRINGS,CO,80477,US,PO BOX 771869,NaN,STEAMBOAT SPRINGS,CO,80477,US,2000-12-13
2,19961076960,"HAL-MAR INVESTMENTS, LLC",601 N. PERRY STREET,NaN,Denver,CO,80204,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,HAROLD,H.,JENSEN,NaN,NaN,601 N. PERRY STREET,NaN,DENVER,CO,80204,US,3127 W. Tanforan Dr,NaN,Englewood,CO,80110,US,1996-06-07
3,20001243280,"NUNET SOLUTIONS, INC.",7847 Jared Way,NaN,Littleton,CO,80125,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Corporation,JOHN,W.,DILLON,NaN,NaN,7847 Jared Way,NaN,Littleton,CO,80125,US,7847 Jared Way,NaN,Littleton,CO,80125,US,2000-12-13
4,20051121021,"Sundog Creative Carpentry, Delinquent May 1, 2006",0876 Six Lazy K Road,NaN,New Castle,CO,81647,US,NaN,NaN,NaN,NaN,NaN,NaN,Delinquent,CO,Limited Liability Company,Teran,NaN,Hughes,NaN,NaN,0876 Six Lazy K Road,NaN,New Castle,CO,81647,US,NaN,NaN,NaN,NaN,NaN,NaN,2005-03-22

In [224]:
xx.compare(c)

             entityid                \
                 self         other
0        2.001100e+10  1.886122e+10
1        2.000124e+10  1.888101e+10
2        1.996108e+10  1.891101e+10
3        2.000124e+10  1.891111e+10
4        2.005112e+10  1.903109e+10
...               ...           ...
2479048  2.023151e+10  2.022154e+10
2479049  2.023151e+10  2.022154e+10
2479050  2.023151e+10  2.022154e+10
2479051  2.023151e+10  2.022154e+10
2479052  2.023151e+10  2.022154e+10

                                                entityname  \
                                                      self
0                                  DODGETON CREEK INN, LLC
1               THE MAIN EVENT MARKETING & PROMOTIONS, INC
2                                 HAL-MAR INVESTMENTS, LLC
3                                    NUNET SOLUTIONS, INC.
4        Sundog Creative Carpentry, Delinquent May 1, 2006
...                                                    ...
2479048                           Manufacturing Ramsey LLC
2479049                             Palen Applications LLC
2479050                                     Artritualz LLC
2479051                                   Cretel Store LLC
2479052                                     Vectorizon LLC

                                                            \
                                                     other
0        DENVER UNION CORPROATION, Dissolved January 17...
1              The Colorado State Bee-Keepers' Association
2        GRADEN MERCANTILE COMPANY (THE), Dissolved May...
3        The Former Stearns-Roger Corporation, Dissolve...
4        A. CARBONE AND COMPANY, INC., Dissolved Decemb...
...                                                    ...
2479048                                    RikWebMedia LLC
2479049                        Mindfulness Psychiatry PLLC
2479050                                Save My Project LLC
2479051                                  AL Locksmith, LLC
2479052                             Bountiful Patriot, LLC

                  principaladdress1                              \
                               self                       other
0              137 CUCHARA AVE EAST    1512 LARIMER STREET #760
1               1455 Manitou Avenue       9250 Rector Leader Rd
2               601 N. PERRY STREET               777 Main Ave.
3                    7847 Jared Way        4500 Cherry Creek Dr
4              0876 Six Lazy K Road  846 East Eighteenth Avenue
...                             ...                         ...
2479048          2236 East 109th Dr                8108 Otis Ct
2479049             2236 E 109th Dr       7535 East Hampden Ave
2479050  1942 Broadway St. STE 314C       12731 Stone Valley Dr
2479051             2236 E 109th Dr  6934 Ryan Gulch Road #6934
2479052  1942 Broadway St. STE 314C          98 Wadsworth Blvd.

        principaladdress2                         principalcity                \
                     self              other               self         other
0                     NaN                NaN            Cuchara        Denver
1                     NaN                NaN  Steamboat Springs         Byers
2                     NaN                NaN             Denver       Durango
3                     NaN                NaN          Littleton      Glendale
4                     NaN                NaN         New Castle        Denver
...                   ...                ...                ...           ...
2479048               NaN                NaN         Northglenn  Fort Collins
2479049               NaN  Suite 400 - #4617         Northglenn        Denver
2479050               NaN                NaN            Boulder        Peyton
2479051               NaN                NaN         Northglenn  Silverthorne
2479052               NaN          #127-3393            Boulder      Lakewood

        principalstate       principalzipcode             principalcountry  \
                  self other             self       other             self
0                  NaN   NaN            81055       80202               US
1                  NaN   NaN            80487       80103              NaN
2                  NaN   NaN            80204      801302              NaN
3                  NaN   NaN            80125       80222              NaN
4                  NaN   NaN            81647       80218              NaN
...                ...   ...              ...         ...              ...
2479048            NaN   NaN            80233  80528-9225              NaN
2479049            NaN   NaN            80233       80231              NaN
2479050            NaN   NaN            80302       80831              NaN
2479051            NaN   NaN            80233       80498              NaN
2479052            NaN   NaN            80302       80226              NaN

              mailingaddress1                          mailingaddress2  \
        other            self                    other            self
0         NaN             NaN                      NaN             NaN
1         NaN   PO Box 771869                      NaN             NaN
2         NaN             NaN            P.O. Box Dr F             NaN
3         NaN             NaN                      NaN             NaN
4         NaN             NaN                      NaN             NaN
...       ...             ...                      ...             ...
2479048   NaN             NaN            PO Box 272742             NaN
2479049   NaN             NaN        264 McGregor Lane             NaN
2479050   NaN             NaN  6050 Stetson Hills Blvd             NaN
2479051   NaN             NaN              PO Box 2002             NaN
2479052   NaN             NaN              PO Box 2125             NaN

                          mailingcity                   mailingstate        \
             other               self             other         self other
0              NaN                NaN               NaN          NaN   NaN
1              NaN  Steamboat Springs               NaN           CO   NaN
2              NaN                NaN           Durango          NaN    CO
3              NaN                NaN               NaN          NaN   NaN
4              NaN                NaN               NaN          NaN   NaN
...            ...                ...               ...          ...   ...
2479048        NaN                NaN      Fort Collins          NaN    CO
2479049        NaN                NaN       Dawsonville          NaN    GA
2479050  Suite 248                NaN  Colorado Springs          NaN    CO
2479051        NaN                NaN            Dillon          NaN    CO
2479052        NaN                NaN            Arvada          NaN    CO

        mailingzipcode        mailingcountry         entitystatus  \
                  self  other           self other           self
0                  NaN    NaN            NaN   NaN  Good Standing
1                80477    NaN             US   NaN            NaN
2                  NaN  81201            NaN    US  Good Standing
3                  NaN    NaN            NaN   NaN  Good Standing
4                  NaN    NaN            NaN   NaN     Delinquent
...                ...    ...            ...   ...            ...
2479048            NaN  80527            NaN    US            NaN
2479049            NaN  30534            NaN    US            NaN
2479050            NaN  80923            NaN    US            NaN
2479051            NaN  80435            NaN    US            NaN
2479052            NaN  80001            NaN    US            NaN

                                    jurisdictonofformation        \
                              other                   self other
0             Voluntarily Dissolved                    NaN   NaN
1                               NaN                    NaN   NaN
2        Administratively Dissolved                    NaN   NaN
3             Voluntarily Dissolved                    NaN   NaN
4             Voluntarily Dissolved                    NaN   NaN
...                             ...                    ...   ...
2479048                         NaN                    NaN   NaN
2479049                         NaN                    NaN   NaN
2479050                         NaN                    NaN   NaN
2479051                         NaN                    NaN   NaN
2479052                         NaN                    NaN   NaN

                        entitytype              agentfirstname           \
                              self        other           self    other
0        Limited Liability Company  Corporation        MICHAEL     JOHN
1                              NaN          NaN           Jill  Kathryn
2        Limited Liability Company  Corporation         HAROLD    Susan
3                              NaN          NaN           JOHN      NaN
4        Limited Liability Company  Corporation          Teran      NaN
...                            ...          ...            ...      ...
2479048                        NaN          NaN         Marcio      NaN
2479049                        NaN          NaN         Marcio      NaN
2479050                        NaN          NaN            NaN  Na'Tima
2479051                        NaN          NaN         Marcio    Allen
2479052                        NaN          NaN            NaN      NaN

        agentmiddlename         agentlastname             agentsuffix        \
                   self   other          self       other        self other
0                    R.      F.         MOORE       O'DEA         NaN   NaN
1                   NaN     NaN       Waldman    Thompson         NaN   NaN
2                    H.       A        JENSEN      Davies         NaN   NaN
3                    W.     NaN        DILLON         NaN         NaN   NaN
4                   NaN     NaN        Hughes         NaN         NaN   NaN
...                 ...     ...           ...         ...         ...   ...
2479048             NaN     NaN        Garcia         NaN         NaN   NaN
2479049             NaN     NaN       Andrade         NaN         NaN   NaN
2479050             NaN  Antyia           NaN    Harrison         NaN   NaN
2479051             NaN     NaN       Andrade  Wisniewski         NaN   NaN
2479052             NaN     NaN           NaN         NaN         NaN   NaN

                  agentorganizationname                           \
                                   self                    other
0                                   NaN                      NaN
1                                   NaN                      NaN
2                                   NaN                      NaN
3                                   NaN  The Corporation Company
4                                   NaN                      NaN
...                                 ...                      ...
2479048                             NaN          RikWebMedia LLC
2479049                             NaN       Werge & Corbin LLC
2479050  Northwest Registered Agent LLC                      NaN
2479051                             NaN                      NaN
2479052  Northwest Registered Agent LLC   Bountiful Patriot, LLC

             agentprincipaladdress1                              \
                               self                       other
0              137 CUCHARA AVE EAST    1512 LARIMER STREET #760
1               1455 Manitou Avenue       9250 Rector Leader Rd
2               601 N. PERRY STREET                777 Main Ave
3                    7847 Jared Way  7700 E Arapahoe Rd Ste 220
4              0876 Six Lazy K Road                         NaN
...                             ...                         ...
2479048          2236 East 109th Dr                8108 Otis Ct
2479049             2236 E 109th Dr                1627 Vine St
2479050  1942 Broadway St. STE 314C       12731 Stone Valley Dr
2479051             2236 E 109th Dr  6934 Ryan Gulch Road #6934
2479052  1942 Broadway St. STE 314C          98 Wadsworth Blvd.

        agentprincipaladdress2            agentprincipalcity                \
                          self      other               self         other
0                          NaN        NaN            Cuchara        DENVER
1                          NaN        NaN  STEAMBOAT SPRINGS         Byers
2                          NaN        NaN             DENVER       Durango
3                          NaN        NaN          Littleton    Centennial
4                          NaN        NaN         New Castle           NaN
...                        ...        ...                ...           ...
2479048                    NaN        NaN         Northglenn  Fort Collins
2479049                    NaN  Suite 200         Northglenn        Denver
2479050                    NaN        NaN            Boulder        Peyton
2479051                    NaN        NaN         Northglenn  Silverthorne
2479052                    NaN  #127-3393            Boulder      Lakewood

        agentprincipalstate       agentprincipalzipcode              \
                       self other                  self       other
0                       NaN   NaN                 81055       80202
1                       NaN   NaN                 80477  80103-8609
2                       NaN   NaN                 80204       81301
3                       NaN   NaN                 80125  80112-1268
4                        CO   NaN                 81647         NaN
...                     ...   ...                   ...         ...
2479048                 NaN   NaN                 80233  80528-9225
2479049                 NaN   NaN                 80233       80206
2479050                 NaN   NaN                 80302       80831
2479051                 NaN   NaN                 80233       80498
2479052                 NaN   NaN                 80302       80226

        agentprincipalcountry       agentmailingaddress1                 \
                         self other                 self          other
0                         NaN   NaN                  NaN            NaN
1                         NaN   NaN        PO BOX 771869            NaN
2                         NaN   NaN  3127 W. Tanforan Dr            NaN
3                         NaN   NaN       7847 Jared Way            NaN
4                          US   NaN                  NaN            NaN
...                       ...   ...                  ...            ...
2479048                   NaN   NaN                  NaN  PO Box 272742
2479049                   NaN   NaN                  NaN            NaN
2479050                   NaN   NaN                  NaN            NaN
2479051                   NaN   NaN                  NaN    PO BOX 2002
2479052                   NaN   NaN                  NaN    PO Box 2125

        agentmailingaddress2         agentmailingcity                \
                        self other               self         other
0                        NaN   NaN                NaN           NaN
1                        NaN   NaN  STEAMBOAT SPRINGS           NaN
2                        NaN   NaN          Englewood           NaN
3                        NaN   NaN          Littleton           NaN
4                        NaN   NaN                NaN           NaN
...                      ...   ...                ...           ...
2479048                  NaN   NaN                NaN  Fort Collins
2479049                  NaN   NaN                NaN           NaN
2479050                  NaN   NaN                NaN           NaN
2479051                  NaN   NaN                NaN        Dillon
2479052                  NaN   NaN                NaN        Arvada

        agentmailingstate       agentmailingzipcode         \
                     self other                self  other
0                     NaN   NaN                 NaN    NaN
1                      CO   NaN               80477    NaN
2                      CO   NaN               80110    NaN
3                      CO   NaN               80125    NaN
4                     NaN   NaN                 NaN    NaN
...                   ...   ...                 ...    ...
2479048               NaN    CO                 NaN  80527
2479049               NaN   NaN                 NaN    NaN
2479050               NaN   NaN                 NaN    NaN
2479051               NaN    CO                 NaN  80435
2479052               NaN    CO                 NaN  80001

        agentmailingcountry       entityformdate
                       self other           self      other
0                       NaN   NaN     2001-01-03 1886-03-29
1                        US   NaN     2000-12-13 1888-12-29
2                        US   NaN     1996-06-07 1891-07-01
3                        US   NaN     2000-12-13 1891-05-23
4                       NaN   NaN     2005-03-22 1903-03-31
...                     ...   ...            ...        ...
2479048                 NaN    US     2023-05-09 2022-05-27
2479049                 NaN   NaN     2023-05-09 2022-05-27
2479050                 NaN   NaN     2023-05-09 2022-05-27
2479051                 NaN    US     2023-05-09 2022-05-28
2479052                 NaN    US     2023-05-09 2022-05-28

[2479046 rows x 70 columns]

In [225]:
xx.head()

,entityid,entityname,principaladdress1,principaladdress2,principalcity,principalstate,principalzipcode,principalcountry,mailingaddress1,mailingaddress2,mailingcity,mailingstate,mailingzipcode,mailingcountry,entitystatus,jurisdictonofformation,entitytype,agentfirstname,agentmiddlename,agentlastname,agentsuffix,agentorganizationname,agentprincipaladdress1,agentprincipaladdress2,agentprincipalcity,agentprincipalstate,agentprincipalzipcode,agentprincipalcountry,agentmailingaddress1,agentmailingaddress2,agentmailingcity,agentmailingstate,agentmailingzipcode,agentmailingcountry,entityformdate
0,20011001058,"DODGETON CREEK INN, LLC",137 CUCHARA AVE EAST,NaN,Cuchara,CO,81055,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,MICHAEL,R.,MOORE,NaN,NaN,137 CUCHARA AVE EAST,NaN,Cuchara,CO,81055,US,NaN,NaN,NaN,NaN,NaN,NaN,2001-01-03
1,20001243352,"THE MAIN EVENT MARKETING & PROMOTIONS, INC",1455 Manitou Avenue,NaN,Steamboat Springs,CO,80487,US,PO Box 771869,NaN,Steamboat Springs,CO,80477,US,Good Standing,CO,Corporation,Jill,NaN,Waldman,NaN,NaN,1455 Manitou Avenue,NaN,STEAMBOAT SPRINGS,CO,80477,US,PO BOX 771869,NaN,STEAMBOAT SPRINGS,CO,80477,US,2000-12-13
2,19961076960,"HAL-MAR INVESTMENTS, LLC",601 N. PERRY STREET,NaN,Denver,CO,80204,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,HAROLD,H.,JENSEN,NaN,NaN,601 N. PERRY STREET,NaN,DENVER,CO,80204,US,3127 W. Tanforan Dr,NaN,Englewood,CO,80110,US,1996-06-07
3,20001243280,"NUNET SOLUTIONS, INC.",7847 Jared Way,NaN,Littleton,CO,80125,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Corporation,JOHN,W.,DILLON,NaN,NaN,7847 Jared Way,NaN,Littleton,CO,80125,US,7847 Jared Way,NaN,Littleton,CO,80125,US,2000-12-13
4,20051121021,"Sundog Creative Carpentry, Delinquent May 1, 2006",0876 Six Lazy K Road,NaN,New Castle,CO,81647,US,NaN,NaN,NaN,NaN,NaN,NaN,Delinquent,CO,Limited Liability Company,Teran,NaN,Hughes,NaN,NaN,0876 Six Lazy K Road,NaN,New Castle,CO,81647,US,NaN,NaN,NaN,NaN,NaN,NaN,2005-03-22

In [227]:
c.sort_values(["entityformdate","entityid"],inplace=True)

In [228]:
c.head()

,entityid,entityname,principaladdress1,principaladdress2,principalcity,principalstate,principalzipcode,principalcountry,mailingaddress1,mailingaddress2,mailingcity,mailingstate,mailingzipcode,mailingcountry,entitystatus,jurisdictonofformation,entitytype,agentfirstname,agentmiddlename,agentlastname,agentsuffix,agentorganizationname,agentprincipaladdress1,agentprincipaladdress2,agentprincipalcity,agentprincipalstate,agentprincipalzipcode,agentprincipalcountry,agentmailingaddress1,agentmailingaddress2,agentmailingcity,agentmailingstate,agentmailingzipcode,agentmailingcountry,entityformdate
2474382,19871025787,UNIVERSITY OF DENVER,2199 S University Blvd.,NaN,Denver,CO,80208,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Nonprofit Corporation,Linda,NaN,Kosten,NaN,NaN,2199 S UNIVERSITY BLVD,NaN,DENVER,CO,80208,US,2199 S. University Blvd,"Mary Reed Bldg, Room 103",Denver,CO,80210,US,1864-03-05
1116,19871000125,EAST BOULDER DITCH COMPANY,1800 Larimer Street,Suite 1100,Denver,CO,80202,US,414 Nicollet Mall,401-9,Minneapolis,MN,55401,US,Good Standing,CO,Nonprofit Corporation,NaN,NaN,NaN,NaN,Corporation Service Company,1900 W. Littleton Boulevard,NaN,Littleton,CO,80120,US,414 Nicollet Mall,401-9,Minneapolis,CO,55401,US,1865-06-30
2402357,19871000162,BIG THOMPSON AND PLATTE RIVER DITCH COMPANY,23143 WCR 21 3/4,NaN,Milliken,CO,80543,US,P.O. Box 181,NaN,Milliken,CO,80543,US,Good Standing,CO,Nonprofit Corporation,MICHELLE,NaN,ORWICK,NaN,NaN,23143 WCR 21 3/4,NaN,MILLIKEN,CO,80543,US,P.O. Box 181,NaN,Milliken,CO,80543,US,1865-11-30
1118,19871000184,"NI WOT DITCH COMPANY, Dissolved February 1, 1866",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Voluntarily Dissolved,CO,Ditch Company,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1866-02-01
10279,19871214372,"THE FIRST UNITED METHODIST CHURCH OF PUEBLO, C...",310 W 11th St,NaN,Pueblo,CO,81003,US,310 W 11th St,NaN,Pueblo,CO,81003,US,Good Standing,CO,Nonprofit Corporation,Barbara,NaN,Grishow,NaN,NaN,51 Briargate Ter,NaN,Pueblo,CO,81001,US,310 W 11th St,NaN,Pueblo,CO,81003,US,1870-04-23

In [229]:
xx.sort_values(["entityformdate","entityid"],inplace=True)

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [230]:
xx.head()

,entityid,entityname,principaladdress1,principaladdress2,principalcity,principalstate,principalzipcode,principalcountry,mailingaddress1,mailingaddress2,mailingcity,mailingstate,mailingzipcode,mailingcountry,entitystatus,jurisdictonofformation,entitytype,agentfirstname,agentmiddlename,agentlastname,agentsuffix,agentorganizationname,agentprincipaladdress1,agentprincipaladdress2,agentprincipalcity,agentprincipalstate,agentprincipalzipcode,agentprincipalcountry,agentmailingaddress1,agentmailingaddress2,agentmailingcity,agentmailingstate,agentmailingzipcode,agentmailingcountry,entityformdate
1678288,19871025787,UNIVERSITY OF DENVER,2199 S University Blvd.,NaN,Denver,CO,80208,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Nonprofit Corporation,Linda,NaN,Kosten,NaN,NaN,2199 S UNIVERSITY BLVD,NaN,DENVER,CO,80208,US,2199 S. University Blvd,"Mary Reed Bldg, Room 103",Denver,CO,80210,US,1864-03-05
17063,19871000125,EAST BOULDER DITCH COMPANY,1800 Larimer Street,Suite 1100,Denver,CO,80202,US,414 Nicollet Mall,401-9,Minneapolis,MN,55401,US,Good Standing,CO,Nonprofit Corporation,NaN,NaN,NaN,NaN,Corporation Service Company,1900 W. Littleton Boulevard,NaN,Littleton,CO,80120,US,414 Nicollet Mall,401-9,Minneapolis,CO,55401,US,1865-06-30
22173,19871000162,BIG THOMPSON AND PLATTE RIVER DITCH COMPANY,23143 WCR 21 3/4,NaN,Milliken,CO,80543,US,P.O. Box 181,NaN,Milliken,CO,80543,US,Good Standing,CO,Nonprofit Corporation,MICHELLE,NaN,ORWICK,NaN,NaN,23143 WCR 21 3/4,NaN,MILLIKEN,CO,80543,US,P.O. Box 181,NaN,Milliken,CO,80543,US,1865-11-30
230073,19871000184,"NI WOT DITCH COMPANY, Dissolved February 1, 1866",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Voluntarily Dissolved,CO,Ditch Company,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1866-02-01
54830,19871214372,"THE FIRST UNITED METHODIST CHURCH OF PUEBLO, C...",310 W 11th St,NaN,Pueblo,CO,81003,US,310 W 11th St,NaN,Pueblo,CO,81003,US,Good Standing,CO,Nonprofit Corporation,Barbara,NaN,Grishow,NaN,NaN,51 Briargate Ter,NaN,Pueblo,CO,81001,US,310 W 11th St,NaN,Pueblo,CO,81003,US,1870-04-23

In [232]:
xx.reset_index(drop=True,inplace=True)
c.reset_index(drop=True,inplace=True)

In [233]:
c.head()

,entityid,entityname,principaladdress1,principaladdress2,principalcity,principalstate,principalzipcode,principalcountry,mailingaddress1,mailingaddress2,mailingcity,mailingstate,mailingzipcode,mailingcountry,entitystatus,jurisdictonofformation,entitytype,agentfirstname,agentmiddlename,agentlastname,agentsuffix,agentorganizationname,agentprincipaladdress1,agentprincipaladdress2,agentprincipalcity,agentprincipalstate,agentprincipalzipcode,agentprincipalcountry,agentmailingaddress1,agentmailingaddress2,agentmailingcity,agentmailingstate,agentmailingzipcode,agentmailingcountry,entityformdate
0,19871025787,UNIVERSITY OF DENVER,2199 S University Blvd.,NaN,Denver,CO,80208,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Nonprofit Corporation,Linda,NaN,Kosten,NaN,NaN,2199 S UNIVERSITY BLVD,NaN,DENVER,CO,80208,US,2199 S. University Blvd,"Mary Reed Bldg, Room 103",Denver,CO,80210,US,1864-03-05
1,19871000125,EAST BOULDER DITCH COMPANY,1800 Larimer Street,Suite 1100,Denver,CO,80202,US,414 Nicollet Mall,401-9,Minneapolis,MN,55401,US,Good Standing,CO,Nonprofit Corporation,NaN,NaN,NaN,NaN,Corporation Service Company,1900 W. Littleton Boulevard,NaN,Littleton,CO,80120,US,414 Nicollet Mall,401-9,Minneapolis,CO,55401,US,1865-06-30
2,19871000162,BIG THOMPSON AND PLATTE RIVER DITCH COMPANY,23143 WCR 21 3/4,NaN,Milliken,CO,80543,US,P.O. Box 181,NaN,Milliken,CO,80543,US,Good Standing,CO,Nonprofit Corporation,MICHELLE,NaN,ORWICK,NaN,NaN,23143 WCR 21 3/4,NaN,MILLIKEN,CO,80543,US,P.O. Box 181,NaN,Milliken,CO,80543,US,1865-11-30
3,19871000184,"NI WOT DITCH COMPANY, Dissolved February 1, 1866",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Voluntarily Dissolved,CO,Ditch Company,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1866-02-01
4,19871214372,"THE FIRST UNITED METHODIST CHURCH OF PUEBLO, C...",310 W 11th St,NaN,Pueblo,CO,81003,US,310 W 11th St,NaN,Pueblo,CO,81003,US,Good Standing,CO,Nonprofit Corporation,Barbara,NaN,Grishow,NaN,NaN,51 Briargate Ter,NaN,Pueblo,CO,81001,US,310 W 11th St,NaN,Pueblo,CO,81003,US,1870-04-23

In [234]:
xx.head()

,entityid,entityname,principaladdress1,principaladdress2,principalcity,principalstate,principalzipcode,principalcountry,mailingaddress1,mailingaddress2,mailingcity,mailingstate,mailingzipcode,mailingcountry,entitystatus,jurisdictonofformation,entitytype,agentfirstname,agentmiddlename,agentlastname,agentsuffix,agentorganizationname,agentprincipaladdress1,agentprincipaladdress2,agentprincipalcity,agentprincipalstate,agentprincipalzipcode,agentprincipalcountry,agentmailingaddress1,agentmailingaddress2,agentmailingcity,agentmailingstate,agentmailingzipcode,agentmailingcountry,entityformdate
0,19871025787,UNIVERSITY OF DENVER,2199 S University Blvd.,NaN,Denver,CO,80208,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Nonprofit Corporation,Linda,NaN,Kosten,NaN,NaN,2199 S UNIVERSITY BLVD,NaN,DENVER,CO,80208,US,2199 S. University Blvd,"Mary Reed Bldg, Room 103",Denver,CO,80210,US,1864-03-05
1,19871000125,EAST BOULDER DITCH COMPANY,1800 Larimer Street,Suite 1100,Denver,CO,80202,US,414 Nicollet Mall,401-9,Minneapolis,MN,55401,US,Good Standing,CO,Nonprofit Corporation,NaN,NaN,NaN,NaN,Corporation Service Company,1900 W. Littleton Boulevard,NaN,Littleton,CO,80120,US,414 Nicollet Mall,401-9,Minneapolis,CO,55401,US,1865-06-30
2,19871000162,BIG THOMPSON AND PLATTE RIVER DITCH COMPANY,23143 WCR 21 3/4,NaN,Milliken,CO,80543,US,P.O. Box 181,NaN,Milliken,CO,80543,US,Good Standing,CO,Nonprofit Corporation,MICHELLE,NaN,ORWICK,NaN,NaN,23143 WCR 21 3/4,NaN,MILLIKEN,CO,80543,US,P.O. Box 181,NaN,Milliken,CO,80543,US,1865-11-30
3,19871000184,"NI WOT DITCH COMPANY, Dissolved February 1, 1866",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Voluntarily Dissolved,CO,Ditch Company,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1866-02-01
4,19871214372,"THE FIRST UNITED METHODIST CHURCH OF PUEBLO, C...",310 W 11th St,NaN,Pueblo,CO,81003,US,310 W 11th St,NaN,Pueblo,CO,81003,US,Good Standing,CO,Nonprofit Corporation,Barbara,NaN,Grishow,NaN,NaN,51 Briargate Ter,NaN,Pueblo,CO,81001,US,310 W 11th St,NaN,Pueblo,CO,81003,US,1870-04-23

In [235]:
xx.compare(c)

             entityid                           entityname  \
                 self         other                   self
336               NaN           NaN                    NaN
866               NaN           NaN                    NaN
976               NaN           NaN                    NaN
1408              NaN           NaN                    NaN
1478              NaN           NaN                    NaN
...               ...           ...                    ...
2479048  2.023151e+10  2.023151e+10         Artritualz LLC
2479049  2.023151e+10  2.023151e+10       Cretel Store LLC
2479050  2.023151e+10  2.023151e+10         Vectorizon LLC
2479051  2.023151e+10  2.023151e+10  Breaking Barriers LLC
2479052  2.023151e+10  2.023151e+10         Techcrate, LLC

                                               principaladdress1  \
                               other                        self
336                              NaN                         NaN
866                              NaN                         NaN
976                              NaN                         NaN
1408                             NaN                         NaN
1478                             NaN                         NaN
...                              ...                         ...
2479048  Little Loves Consulting LLC  1942 Broadway St. STE 314C
2479049        Breaking Barriers LLC             2236 E 109th Dr
2479050               Techcrate, LLC  1942 Broadway St. STE 314C
2479051                    Bent Ltd.               4602 Genoa St
2479052        Future Foundation Ltd            11343 Newport St

                                    principaladdress2       principalcity  \
                              other              self other          self
336                             NaN               NaN   NaN           NaN
866                             NaN               NaN   NaN      Houston
976                             NaN               NaN   NaN      Houston
1408                            NaN               NaN   NaN      Houston
1478                            NaN               NaN   NaN      Houston
...                             ...               ...   ...           ...
2479048               1347 Doyle Pl               NaN   NaN       Boulder
2479049               4602 Genoa St               NaN   NaN    Northglenn
2479050            11343 Newport St               NaN   NaN       Boulder
2479051           250 N Murray Blvd               NaN   NaN        Denver
2479052  1312 17TH ST UNIT NUM 2955               NaN   NaN      Thornton

                          principalstate       principalzipcode         \
                    other           self other             self  other
336                   NaN            NaN   NaN              NaN    NaN
866               Houston            NaN   NaN              NaN    NaN
976               Houston            NaN   NaN              NaN    NaN
1408              Houston            NaN   NaN              NaN    NaN
1478              Houston            NaN   NaN              NaN    NaN
...                   ...            ...   ...              ...    ...
2479048  Colorado Springs            NaN   NaN            80302  80915
2479049            Denver            NaN   NaN            80233  80249
2479050          Thornton            NaN   NaN            80302  80233
2479051  Colorado Springs            NaN   NaN            80249  80916
2479052            Denver            NaN   NaN            80233  80202

        principalcountry       mailingaddress1                     \
                    self other            self              other
336                  NaN   NaN             NaN                NaN
866                  NaN   NaN             NaN                NaN
976                  NaN   NaN             NaN                NaN
1408                 NaN   NaN             NaN                NaN
1478                 NaN   NaN             NaN                NaN
...                  ...   ...             ...                ...
2479048              NaN   NaN             NaN                NaN
2479049              NaN   NaN             NaN                NaN
2479050              NaN   NaN             NaN                NaN
2479051              NaN   NaN             NaN  250 N Murray Blvd
2479052              NaN   NaN             NaN                NaN

        mailingaddress2       mailingcity                   mailingstate  \
                   self other        self             other         self
336                 NaN   NaN    Houston            Houston          NaN
866                 NaN   NaN         NaN               NaN          NaN
976                 NaN   NaN    Houston            Houston          NaN
1408                NaN   NaN    Houston            Houston          NaN
1478                NaN   NaN         NaN               NaN          NaN
...                 ...   ...         ...               ...          ...
2479048             NaN   NaN         NaN               NaN          NaN
2479049             NaN   NaN         NaN               NaN          NaN
2479050             NaN   NaN         NaN               NaN          NaN
2479051             NaN   NaN         NaN  Colorado Springs          NaN
2479052             NaN   NaN         NaN               NaN          NaN

              mailingzipcode        mailingcountry       entitystatus        \
        other           self  other           self other         self other
336       NaN            NaN    NaN            NaN   NaN          NaN   NaN
866       NaN            NaN    NaN            NaN   NaN          NaN   NaN
976       NaN            NaN    NaN            NaN   NaN          NaN   NaN
1408      NaN            NaN    NaN            NaN   NaN          NaN   NaN
1478      NaN            NaN    NaN            NaN   NaN          NaN   NaN
...       ...            ...    ...            ...   ...          ...   ...
2479048   NaN            NaN    NaN            NaN   NaN          NaN   NaN
2479049   NaN            NaN    NaN            NaN   NaN          NaN   NaN
2479050   NaN            NaN    NaN            NaN   NaN          NaN   NaN
2479051    CO            NaN  80916            NaN    US          NaN   NaN
2479052   NaN            NaN    NaN            NaN   NaN          NaN   NaN

        jurisdictonofformation                       entitytype               \
                          self other                       self        other
336                        NaN   NaN                        NaN          NaN
866                        NaN   NaN                        NaN          NaN
976                        NaN   NaN                        NaN          NaN
1408                       NaN   NaN                        NaN          NaN
1478                       NaN   NaN                        NaN          NaN
...                        ...   ...                        ...          ...
2479048                    NaN   NaN                        NaN          NaN
2479049                    NaN   NaN                        NaN          NaN
2479050                    NaN   NaN                        NaN          NaN
2479051                    NaN   NaN                        NaN          NaN
2479052                    NaN   NaN  Limited Liability Company  Corporation

        agentfirstname            agentmiddlename       agentlastname  \
                  self      other            self other          self
336                NaN        NaN             NaN   NaN           NaN
866                NaN        NaN             NaN   NaN           NaN
976                NaN        NaN             NaN   NaN           NaN
1408               NaN        NaN             NaN   NaN           NaN
1478               NaN        NaN             NaN   NaN           NaN
...                ...        ...             ...   ...           ...
2479048            NaN   Kathleen             NaN   NaN           NaN
2479049         Marcio  Christina             NaN   NaN       Andrade
2479050            NaN   Nickolas             NaN   NaN           NaN
2479051      Christina        NaN             NaN   NaN      Gonzales
2479052       Nickolas     LINHAO             NaN   NaN      Laughter

                  agentsuffix                 agentorganizationname  \
            other        self other                            self
336           NaN         NaN   NaN                             NaN
866           NaN         NaN   NaN                             NaN
976           NaN         NaN   NaN                             NaN
1408          NaN         NaN   NaN                             NaN
1478          NaN         NaN   NaN                             NaN
...           ...         ...   ...                             ...
2479048      Wise         NaN   NaN  Northwest Registered Agent LLC
2479049  Gonzales         NaN   NaN                             NaN
2479050  Laughter         NaN   NaN  Northwest Registered Agent LLC
2479051       NaN         NaN   NaN                             NaN
2479052       GUO         NaN   NaN                             NaN

                        agentprincipaladdress1                              \
             other                        self                       other
336            NaN                         NaN                         NaN
866            NaN                         NaN                         NaN
976            NaN                         NaN                         NaN
1408           NaN                         NaN                         NaN
1478           NaN                         NaN                         NaN
...            ...                         ...                         ...
2479048        NaN  1942 Broadway St. STE 314C               1347 Doyle Pl
2479049        NaN             2236 E 109th Dr               4602 Genoa St
2479050        NaN  1942 Broadway St. STE 314C            11343 Newport St
2479051  Bent Ltd.               4602 Genoa St           250 N Murray Blvd
2479052        NaN            11343 Newport St  1312 17TH ST UNIT NUM 2955

        agentprincipaladdress2       agentprincipalcity                    \
                          self other               self             other
336                        NaN   NaN                NaN               NaN
866                        NaN   NaN                NaN               NaN
976                        NaN   NaN                NaN               NaN
1408                       NaN   NaN                NaN               NaN
1478                       NaN   NaN                NaN               NaN
...                        ...   ...                ...               ...
2479048                    NaN   NaN            Boulder  Colorado Springs
2479049                    NaN   NaN         Northglenn            Denver
2479050                    NaN   NaN            Boulder          Thornton
2479051                    NaN   NaN             Denver  Colorado Springs
2479052                    NaN   NaN           Thornton            Denver

        agentprincipalstate       agentprincipalzipcode         \
                       self other                  self  other
336                     NaN   NaN                   NaN    NaN
866                     NaN   NaN                   NaN    NaN
976                     NaN   NaN                   NaN    NaN
1408                    NaN   NaN                   NaN    NaN
1478                    NaN   NaN                   NaN    NaN
...                     ...   ...                   ...    ...
2479048                 NaN   NaN                 80302  80915
2479049                 NaN   NaN                 80233  80249
2479050                 NaN   NaN                 80302  80233
2479051                 NaN   NaN                 80249  80916
2479052                 NaN   NaN                 80233  80202

        agentprincipalcountry       agentmailingaddress1                     \
                         self other                 self              other
336                       NaN   NaN                  NaN                NaN
866                       NaN   NaN                  NaN                NaN
976                       NaN   NaN                  NaN                NaN
1408                      NaN   NaN                  NaN                NaN
1478                      NaN   NaN                  NaN                NaN
...                       ...   ...                  ...                ...
2479048                   NaN   NaN                  NaN                NaN
2479049                   NaN   NaN                  NaN                NaN
2479050                   NaN   NaN                  NaN                NaN
2479051                   NaN   NaN                  NaN  250 N Murray Blvd
2479052                   NaN   NaN                  NaN                NaN

        agentmailingaddress2       agentmailingcity                    \
                        self other             self             other
336                      NaN   NaN              NaN               NaN
866                      NaN   NaN              NaN               NaN
976                      NaN   NaN              NaN               NaN
1408                     NaN   NaN              NaN               NaN
1478                     NaN   NaN              NaN               NaN
...                      ...   ...              ...               ...
2479048                  NaN   NaN              NaN               NaN
2479049                  NaN   NaN              NaN               NaN
2479050                  NaN   NaN              NaN               NaN
2479051                  NaN   NaN              NaN  Colorado Springs
2479052                  NaN   NaN              NaN               NaN

        agentmailingstate       agentmailingzipcode         \
                     self other                self  other
336                   NaN   NaN                 NaN    NaN
866                   NaN   NaN                 NaN    NaN
976                   NaN   NaN                 NaN    NaN
1408                  NaN   NaN                 NaN    NaN
1478                  NaN   NaN                 NaN    NaN
...                   ...   ...                 ...    ...
2479048               NaN   NaN                 NaN    NaN
2479049               NaN   NaN                 NaN    NaN
2479050               NaN   NaN                 NaN    NaN
2479051               NaN    CO                 NaN  80916
2479052               NaN   NaN                 NaN    NaN

        agentmailingcountry       entityformdate
                       self other           self      other
336                     NaN   NaN            NaT        NaT
866                     NaN   NaN            NaT        NaT
976                     NaN   NaN            NaT        NaT
1408                    NaN   NaN            NaT        NaT
1478                    NaN   NaN            NaT        NaT
...                     ...   ...            ...        ...
2479048                 NaN   NaN            NaT        NaT
2479049                 NaN   NaN     2023-05-09 2023-05-10
2479050                 NaN   NaN     2023-05-09 2023-05-10
2479051                 NaN    US            NaT        NaT
2479052                 NaN   NaN            NaT        NaT

[2471655 rows x 70 columns]

In [238]:
c.iloc[334]

entityid                                         19871028638
entityname                JOSH AMES IRRIGATION DITCH COMPANY
principaladdress1                                        NaN
principaladdress2                                        NaN
principalcity                                            NaN
principalstate                                           NaN
principalzipcode                                         NaN
principalcountry                                         NaN
mailingaddress1                                          NaN
mailingaddress2                                          NaN
mailingcity                                              NaN
mailingstate                                             NaN
mailingzipcode                                           NaN
mailingcountry                                           NaN
entitystatus                                          Exists
jurisdictonofformation                                    CO
entitytype                                     Ditch Company
agentfirstname                                           NaN
agentmiddlename                                          NaN
agentlastname                                            NaN
agentsuffix                                              NaN
agentorganizationname                                    NaN
agentprincipaladdress1                                   NaN
agentprincipaladdress2                                   NaN
agentprincipalcity                                       NaN
agentprincipalstate                                      NaN
agentprincipalzipcode                                    NaN
agentprincipalcountry                                    NaN
agentmailingaddress1                                     NaN
agentmailingaddress2                                     NaN
agentmailingcity                                         NaN
agentmailingstate                                        NaN
agentmailingzipcode                                      NaN
agentmailingcountry                                      NaN
entityformdate                           1899-08-01 00:00:00
Name: 334, dtype: object

In [237]:
c["entityid"].isna().sum()

0

In [240]:
xx[["entityid","entityname"]].compare(c[["entityid","entityname"]])

             entityid                \
                 self         other
4563     1.987114e+10  1.987114e+10
4564     1.987114e+10  1.987128e+10
4565     1.987128e+10  1.987125e+10
4566     1.987125e+10  1.987122e+10
4567     1.987122e+10  1.987114e+10
...               ...           ...
2479048  2.023151e+10  2.023151e+10
2479049  2.023151e+10  2.023151e+10
2479050  2.023151e+10  2.023151e+10
2479051  2.023151e+10  2.023151e+10
2479052  2.023151e+10  2.023151e+10

                                                entityname  \
                                                      self
4563                      FLOOD & PETERSON INSURANCE, INC.
4564                                  LUCERO DITCH COMPANY
4565     ST. NICHOLAS GREEK ORTHODOX CHURCH OF GRAND JU...
4566                 MOUNTAIN VIEW UNITED METHODIST CHURCH
4567     THE UNITED METHODIST CHURCH OF LA JUNTA, COLORADO
...                                                    ...
2479048                                     Artritualz LLC
2479049                                   Cretel Store LLC
2479050                                     Vectorizon LLC
2479051                              Breaking Barriers LLC
2479052                                     Techcrate, LLC


                                                     other
4563                                  LUCERO DITCH COMPANY
4564     ST. NICHOLAS GREEK ORTHODOX CHURCH OF GRAND JU...
4565                 MOUNTAIN VIEW UNITED METHODIST CHURCH
4566     THE UNITED METHODIST CHURCH OF LA JUNTA, COLORADO
4567                                         SLAVENS, INC.
...                                                    ...
2479048                        Little Loves Consulting LLC
2479049                              Breaking Barriers LLC
2479050                                     Techcrate, LLC
2479051                                          Bent Ltd.
2479052                              Future Foundation Ltd

[2471593 rows x 4 columns]

In [241]:
xx.tail()

,entityid,entityname,principaladdress1,principaladdress2,principalcity,principalstate,principalzipcode,principalcountry,mailingaddress1,mailingaddress2,mailingcity,mailingstate,mailingzipcode,mailingcountry,entitystatus,jurisdictonofformation,entitytype,agentfirstname,agentmiddlename,agentlastname,agentsuffix,agentorganizationname,agentprincipaladdress1,agentprincipaladdress2,agentprincipalcity,agentprincipalstate,agentprincipalzipcode,agentprincipalcountry,agentmailingaddress1,agentmailingaddress2,agentmailingcity,agentmailingstate,agentmailingzipcode,agentmailingcountry,entityformdate
2479048,20231507781,Artritualz LLC,1942 Broadway St. STE 314C,NaN,Boulder,CO,80302,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,NaN,NaN,NaN,NaN,Northwest Registered Agent LLC,1942 Broadway St. STE 314C,NaN,Boulder,CO,80302,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-09
2479049,20231507784,Cretel Store LLC,2236 E 109th Dr,NaN,Northglenn,CO,80233,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,Marcio,NaN,Andrade,NaN,NaN,2236 E 109th Dr,NaN,Northglenn,CO,80233,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-09
2479050,20231507785,Vectorizon LLC,1942 Broadway St. STE 314C,NaN,Boulder,CO,80302,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,NaN,NaN,NaN,NaN,Northwest Registered Agent LLC,1942 Broadway St. STE 314C,NaN,Boulder,CO,80302,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-09
2479051,20231505376,Breaking Barriers LLC,4602 Genoa St,NaN,Denver,CO,80249,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,Christina,NaN,Gonzales,NaN,NaN,4602 Genoa St,NaN,Denver,CO,80249,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-10
2479052,20231506080,"Techcrate, LLC",11343 Newport St,NaN,Thornton,CO,80233,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,Nickolas,NaN,Laughter,NaN,NaN,11343 Newport St,NaN,Thornton,CO,80233,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-10

In [242]:
c.tail()

,entityid,entityname,principaladdress1,principaladdress2,principalcity,principalstate,principalzipcode,principalcountry,mailingaddress1,mailingaddress2,mailingcity,mailingstate,mailingzipcode,mailingcountry,entitystatus,jurisdictonofformation,entitytype,agentfirstname,agentmiddlename,agentlastname,agentsuffix,agentorganizationname,agentprincipaladdress1,agentprincipaladdress2,agentprincipalcity,agentprincipalstate,agentprincipalzipcode,agentprincipalcountry,agentmailingaddress1,agentmailingaddress2,agentmailingcity,agentmailingstate,agentmailingzipcode,agentmailingcountry,entityformdate
2479048,20231508148,Little Loves Consulting LLC,1347 Doyle Pl,NaN,Colorado Springs,CO,80915,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,Kathleen,NaN,Wise,NaN,NaN,1347 Doyle Pl,NaN,Colorado Springs,CO,80915,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-09
2479049,20231505376,Breaking Barriers LLC,4602 Genoa St,NaN,Denver,CO,80249,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,Christina,NaN,Gonzales,NaN,NaN,4602 Genoa St,NaN,Denver,CO,80249,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-10
2479050,20231506080,"Techcrate, LLC",11343 Newport St,NaN,Thornton,CO,80233,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,Nickolas,NaN,Laughter,NaN,NaN,11343 Newport St,NaN,Thornton,CO,80233,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-10
2479051,20231508155,Bent Ltd.,250 N Murray Blvd,NaN,Colorado Springs,CO,80916,US,250 N Murray Blvd,NaN,Colorado Springs,CO,80916,US,Good Standing,CO,Limited Liability Company,NaN,NaN,NaN,NaN,Bent Ltd.,250 N Murray Blvd,NaN,Colorado Springs,CO,80916,US,250 N Murray Blvd,NaN,Colorado Springs,CO,80916,US,2023-05-10
2479052,20231508156,Future Foundation Ltd,1312 17TH ST UNIT NUM 2955,NaN,Denver,CO,80202,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Corporation,LINHAO,NaN,GUO,NaN,NaN,1312 17TH ST UNIT NUM 2955,NaN,Denver,CO,80202,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-10

In [243]:
xx["entityid"].nunique()

2478616

In [245]:
c["entityid"].nunique()

2479053

In [246]:
cids = c["entityid"].unique()

In [247]:
cids

array([19871025787, 19871000125, 19871000162, ..., 20231506080,
       20231508155, 20231508156])

In [252]:
xx.loc[~xx["entityid"].isin(cids)]

Empty DataFrame
Columns: [entityid, entityname, principaladdress1, principaladdress2, principalcity, principalstate, principalzipcode, principalcountry, mailingaddress1, mailingaddress2, mailingcity, mailingstate, mailingzipcode, mailingcountry, entitystatus, jurisdictonofformation, entitytype, agentfirstname, agentmiddlename, agentlastname, agentsuffix, agentorganizationname, agentprincipaladdress1, agentprincipaladdress2, agentprincipalcity, agentprincipalstate, agentprincipalzipcode, agentprincipalcountry, agentmailingaddress1, agentmailingaddress2, agentmailingcity, agentmailingstate, agentmailingzipcode, agentmailingcountry, entityformdate]
Index: []

In [253]:
xids = xx["entityid"].unique()

In [255]:
c.loc[~c["entityid"].isin(xids)].shape

(437, 35)

In [257]:
dfOrig.shape

(2514441, 37)

In [258]:
dfXen.shape

(2514441, 35)

In [259]:
dfOrig.columns

Index(['Entity Id', 'Entity Name', 'Principal Address 1',
       'Principal Address 2', 'Principal City', 'Principal State',
       'Principal Zip', 'Principal Country', 'Mailing Address 1',
       'Mailing Address 2', 'Mailing City', 'Mailing State', 'Mailing Zip',
       'Mailing Country', 'Entity Status', 'Jurisdiction of Formation',
       'Perpetual Flag', 'Term Date', 'Entity Type', 'Agent First Name',
       'Agent Middle Name', 'Agent Last Name', 'Agent Suffix',
       'Agent Organization Name', 'Agent Principal Address 1',
       'Agent Principal Address 2', 'Agent Principal City',
       'Agent Principal State', 'Agent Principal Zip',
       'Agent Principal Country', 'Agent Mailing Address 1',
       'Agent Mailing Address 2', 'Agent Mailing City', 'Agent Mailing State',
       'Agent Mailing Zip', 'Agent Mailing Country', 'Entity Form Date'],
      dtype='object')

In [260]:
oids = dfOrig["Entity Id"].unique()

In [261]:
len(oids)

2480806

In [262]:
c.loc[~c["entityid"].isin(oids)].shape

(17, 35)

In [263]:
c.loc[~c["entityid"].isin(oids)].shape

(17, 35)

In [264]:
xids = dfXen["entityId"].unique()

In [265]:
c.loc[~c["entityid"].isin(xids)].shape

(17, 35)

In [271]:
x = dfXen.copy()

In [267]:
x.shape

(2514441, 35)

In [269]:
x.drop_duplicates(inplace=True)

In [270]:
x.shape

(2481249, 35)

In [272]:
x.shape

(2514441, 35)

In [273]:
x = dfXen.copy()

In [274]:
x.shape

(2514441, 35)

In [278]:
x.loc[x.duplicated(keep="first")].shape

(33192, 35)

In [279]:
y = x.drop_duplicates()

In [280]:
y.shape

(2481249, 35)

In [283]:
yids = y["entityId"].unique()

In [284]:
len(yids)

2480806

In [286]:
c.loc[~c["entityid"].isin(yids)]

,entityid,entityname,principaladdress1,principaladdress2,principalcity,principalstate,principalzipcode,principalcountry,mailingaddress1,mailingaddress2,mailingcity,mailingstate,mailingzipcode,mailingcountry,entitystatus,jurisdictonofformation,entitytype,agentfirstname,agentmiddlename,agentlastname,agentsuffix,agentorganizationname,agentprincipaladdress1,agentprincipaladdress2,agentprincipalcity,agentprincipalstate,agentprincipalzipcode,agentprincipalcountry,agentmailingaddress1,agentmailingaddress2,agentmailingcity,agentmailingstate,agentmailingzipcode,agentmailingcountry,entityformdate
515178,20041117545,"THE RIDGE CLUB AT TELLURIDE, INC.",2 Coonskin Ridge Lane,PO Box 518,Mountain Village,CO,81435,US,PO Box 518,NaN,Telluride,CO,81435-0518,US,Good Standing,CO,Nonprofit Corporation,Greg,NaN,Pope,NaN,NaN,2 Coonskin Ridge Lane,PO Box 518,MOUNTAIN VILLAGE,CO,81435,US,PO Box 518,NaN,Telluride,CO,81435-0518,US,2004-03-31
892606,20091212550,"Live on Vacation Everyday, Inc., Delinquent Fe...",5022 MONTVIEW BLVD,NaN,Denver,CO,80207,US,5022 Montview Blvd,NaN,Denver,CO,80207,US,Delinquent,CO,Corporation,STACY,KAY,MCDONALD,NaN,NaN,5022 MONTVIEW BLVD,NaN,DENVER,CO,80207,US,5022 Montview Blvd,NaN,Denver,CO,80207,US,2009-04-14
1313710,20141422547,"Chef Micah K. Vincent, Delinquent December 1, ...",1385 Carr Street,NaN,Lakewood,CO,80214,US,NaN,NaN,NaN,NaN,NaN,NaN,Delinquent,CO,Limited Liability Company,Micah,Ka'aona,Vincent,NaN,NaN,1385 Carr street,NaN,Lakewood,CO,80214,US,NaN,NaN,NaN,NaN,NaN,NaN,2014-07-13
2002477,20201612052,"Carefree Trade Co., Ltd., Delinquent December ...",4690 Joliet St,NaN,Denver,CO,80239,US,NaN,NaN,NaN,NaN,NaN,NaN,Delinquent,CO,Corporation,WEI,NaN,DUAN,NaN,NaN,4690 Joliet St,NaN,Denver,CO,80239,US,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-17
2057369,20208049704,tectake inc,2116 S Ogden St,NaN,Denver,CO,80210,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Corporation,YUANXIAN,NaN,LV,NaN,NaN,2116 S Ogden St,NaN,Denver,CO,80210,US,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-02
2065165,20208093168,CHIHIROS INC,295 ECHO CREEK DR,NaN,Pagosa Springs,CO,81147,US,41-14B MAIN STREET STE B26,NaN,Flushing,NY,11355,US,Good Standing,CO,Corporation,XINXIN,NaN,GUO,NaN,NaN,295 ECHO CREEK DR,NaN,PAGOSA SPRINGS,CO,81147,US,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-22
2094735,20211184174,Brevino Industry Inc,1630 E 66TH AVE,NaN,Denver,CO,80229,US,NaN,NaN,NaN,NaN,NaN,NaN,Delinquent,CO,Corporation,ZHOUCHAO,NaN,ZENG,NaN,NaN,1630 E 66TH AVE,NaN,DENVER,CO,80229,US,NaN,NaN,NaN,NaN,NaN,NaN,2021-02-24
2144648,20211553987,Shunjia trading inc,1630 E 66TH AVE,NaN,Denver,CO,80229,US,NaN,NaN,NaN,NaN,NaN,US,Good Standing,CO,Corporation,WEIZHONG,NaN,CHEN,NaN,NaN,1630 E 66TH AVE,NaN,DENVER,CO,80229,US,NaN,NaN,NaN,NaN,NaN,NaN,2021-06-16
2210296,20218115291,Eakyhom,4690 Joliet St,NaN,Denver,CO,80239,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Corporation,JUNJIE,NaN,GE,NaN,NaN,4690 Joliet St,NaN,Denver,CO,80239,US,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-26
2236269,20221100983,DARN DARK Inc,2702 Cub Lake Dr,NaN,Loveland,CO,80538,US,NaN,NaN,NaN,NaN,NaN,NaN,Noncompliant,CO,Corporation,NaN,NaN,NaN,NaN,"LegalCorp Solutions, LLC",501 S. Cherry Street 11th Floor,NaN,Denver,CO,80246,US,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-26
2345174,20221912270,JEFFREYCONSULT LLC,14995 Pamela Way,NaN,Peyton,CO,80831,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,JEFFREY,T,HARTSHORN,NaN,NaN,14995 Pamela Way,NaN,Peyton,CO,80831,US,14995 Pamela Way,NaN,Peyton,CO,80831,US,2022-09-23
2353789,20228000046,"Jaakko Coloradoy LLC, Dissolved November 1, 2022",14995 Pamela Way,NaN,Peyton,CO,80831,US,NaN,NaN,NaN,NaN,NaN,NaN,Voluntarily Dissolved,CO,Limited Liability Company,Jeffrey,T,Hartshorn,NaN,NaN,14995 Pamela Way,NaN,Peyton,CO,80831,US,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-12
2373755,20228122330,UKG LLC,8799 E 54th Ave,NaN,Denver,CO,80238,US,9145 Las Vegas Blvd S 3017,NaN,Las Vegas,NV,80238,US,Good Standing,CO,Limited Liability Company,Julienne,NaN,Clarke-Hardy,NaN,NaN,8799 E 54th Ave,NaN,Denver,CO,80238,US,NaN,NaN,NaN,NaN,NaN,NaN,2022-11-18
2389635,20228231774,Mikeys K9 Training llc,6872 fox way,NaN,Denver,CO,80019,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,Michael,NaN,Gunderson,NaN,NaN,6872 fox way,NaN,Denver,CO,80019,US,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-20
2395594,20228284224,Cuzs Fresh Seafood & Poboys LLC,7410 Granada Rd,NaN,Denver,CO,80221,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,Christine,NaN,Barnes,NaN,NaN,7410 Granada Rd,NaN,Denver,CO,80221,US,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-29
2414205,20231106548,Blanc Service llc,1008 Nightingale Dr,NaN,Fort Collins,CO,80525,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,Ruben,NaN,Blanco,NaN,NaN,1008 Nightingale Dr,NaN,Fort Collins,CO,80525,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-01-25
2416364,20231122477,UBALDO LLC,1000 Bannock St,NaN,Denver,CO,80204,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,GILLIAN MADELIENNE,NaN,UBALDO,NaN,NaN,1000 Bannock St,NaN,Denver,CO,80204,US,NaN,NaN,NaN,NaN,NaN,NaN,2023-01-30

In [289]:
y.loc[~y["entityId"].isin(cids)].shape

(1770, 35)

In [291]:
x.columns = x.columns.str.lower()

In [321]:
import numpy as np

In [ ]:
nrec=0
nbad=0
for index,row in c.iterrows():
    id = row["entityid"]
    xx = x.loc[x["entityid"] == id].to_dict(orient="index")
    xxv = list(xx.values())
    
    try: 
        for kk,vv in xxv[0].items():
             
             if isinstance(vv,str) : 
                    if  kk != "entityformdate" and vv.strip() != row[kk].strip() :
                        print(id,row["entityformdate"],kk,vv,row[kk],file=open("compare.out","a+"))
             else:
                    if vv != row[kk] and kk != "entityformdate" and not np.isnan(vv) :
                        print(id,row["entityformdate"],kk,vv,row[kk],file=open("compare.out","a+"))


    except :
        nbad+=1
        print("Bad ",nbad,kk,vv,row[kk],type(vv),isinstance(vv,str))
    nrec+=1
    if nrec%1000 == 0:
        print("on record ",nrec)

on record  1000
on record  2000
on record  3000
on record  4000
on record  5000
on record  6000
on record  7000
on record  8000
on record  9000
on record  10000
on record  11000
on record  12000
on record  13000
on record  14000
Bad  1 mailingaddress1 1900 W Littleton Blvd nan <class 'str'> True
on record  15000
on record  16000
on record  17000
on record  18000
Bad  2 mailingaddress1 22518 county Road nan <class 'str'> True
on record  19000
on record  20000
on record  21000
Bad  3 mailingaddress1 5915 PONDEROSA WAY nan <class 'str'> True
on record  22000
on record  23000
Bad  4 principaladdress2 Suite 266 nan <class 'str'> True
on record  24000
on record  25000
on record  26000
on record  27000
on record  28000
on record  29000
Bad  5 agentmailingaddress2 Suite 201 nan <class 'str'> True
on record  30000
on record  31000
Bad  6 agentmailingaddress1 131 Fairway Ln nan <class 'str'> True
on record  32000
on record  33000
on record  34000
on record  35000
on record  36000
on record  37000
on record  38000
on record  39000
on record  40000
on record  41000
on record  42000
on record  43000
on record  44000
on record  45000
on record  46000
on record  47000
on record  48000
on record  49000
on record  50000
on record  51000
on record  52000
on record  53000
on record  54000
on record  55000
on record  56000
on record  57000
on record  58000
on record  59000
on record  60000
on record  61000
on record  62000
on record  63000
on record  64000
on record  65000
on record  66000
on record  67000
on record  68000
on record  69000
on record  70000
on record  71000
on record  72000
on record  73000
on record  74000
on record  75000
on record  76000
on record  77000
on record  78000
on record  79000
on record  80000
on record  81000
on record  82000
Bad  7 agentfirstname Alice nan <class 'str'> True
on record  83000
on record  84000
on record  85000
Bad  8 agentmailingaddress1 201 E. 4th Street #130 nan <class 'str'> True
on record  86000
on record  87000
on record  88000
on record  89000
Bad  9 mailingcountry US nan <class 'str'> True
on record  90000
on record  91000
on record  92000
on record  93000
on record  94000
on record  95000
on record  96000
on record  97000
on record  98000
on record  99000
on record  100000
Bad  10 mailingaddress1 2201 95th Avenue nan <class 'str'> True
on record  101000
on record  102000
on record  103000
on record  104000
on record  105000
on record  106000
on record  107000
Bad  11 mailingaddress1 1801 Broadway Ste 200 nan <class 'str'> True
on record  108000
on record  109000
on record  110000
on record  111000
on record  112000
on record  113000
on record  114000
on record  115000
Bad  12 mailingaddress1 2201 95th Avenue nan <class 'str'> True
on record  116000
Bad  13 principaladdress2 3146 S Cathay Cir nan <class 'str'> True
on record  117000
on record  118000
on record  119000
on record  120000
on record  121000
on record  122000
on record  123000
on record  124000
on record  125000
on record  126000
on record  127000
on record  128000
on record  129000
on record  130000
on record  131000
on record  132000
on record  133000
on record  134000
on record  135000
on record  136000
Bad  14 mailingaddress1 700 Main Ave nan <class 'str'> True
on record  137000
on record  138000
on record  139000
on record  140000
on record  141000
on record  142000
on record  143000
on record  144000
on record  145000
Bad  15 agentmailingaddress1 201 E. 4th Street #130 nan <class 'str'> True
on record  146000
on record  147000
on record  148000
on record  149000
on record  150000
Bad  16 mailingaddress1 24123 Running Deer Rd nan <class 'str'> True
on record  151000
on record  152000
on record  153000
on record  154000
on record  155000
on record  156000
on record  157000
on record  158000
on record  159000
on record  160000
Bad  17 agentmailingaddress2 149 N. San Roman Rd. nan <class 'str'> True
on record  161000
on record  162000
on record  163000
on record  164000
on record  165000
on record  166000
on record  167000
on record  168000
on record  169000
on record  170000
on record  171000
on record  172000
on record  173000
on record  174000
Bad  18 mailingcountry US nan <class 'str'> True
on record  175000
on record  176000
on record  177000
on record  178000
on record  179000
on record  180000
on record  181000
on record  182000
on record  183000
on record  184000
on record  185000
on record  186000
on record  187000
on record  188000
on record  189000
on record  190000
on record  191000
on record  192000
on record  193000
on record  194000
on record  195000
on record  196000
on record  197000
on record  198000
Bad  19 mailingaddress1 PO Box 897 nan <class 'str'> True
on record  199000
Bad  20 principaladdress2 1660 Lincoln St, Ste 2200 nan <class 'str'> True
on record  200000
on record  201000
on record  202000
on record  203000
on record  204000
on record  205000
on record  206000
on record  207000
on record  208000
on record  209000
on record  210000
on record  211000
on record  212000
on record  213000
on record  214000
on record  215000
on record  216000
on record  217000
on record  218000
on record  219000
on record  220000
on record  221000
on record  222000
on record  223000
on record  224000
on record  225000
on record  226000
on record  227000
on record  228000
on record  229000
on record  230000
on record  231000
on record  232000
on record  233000
on record  234000
on record  235000
on record  236000
on record  237000
Bad  21 agentmailingaddress1 4845 Pearl East Cir Ste 101 nan <class 'str'> True
on record  238000
on record  239000
on record  240000
on record  241000
on record  242000
on record  243000
on record  244000
Bad  22 mailingaddress1 P O BOX 1012 nan <class 'str'> True
on record  245000
on record  246000
on record  247000
on record  248000
on record  249000
on record  250000
on record  251000
on record  252000
on record  253000
on record  254000
Bad  23 principaladdress2 Ste. 100 nan <class 'str'> True
on record  255000
on record  256000
on record  257000
on record  258000
Bad  24 mailingaddress1 PO Box 125 nan <class 'str'> True
on record  259000
on record  260000
on record  261000
on record  262000
on record  263000
Bad  25 agentmailingaddress1 1597 Cole Blvd Ste 100 nan <class 'str'> True
on record  264000
on record  265000
on record  266000
on record  267000
on record  268000
on record  269000
on record  270000
Bad  26 agentmailingaddress2 Suite 100 nan <class 'str'> True
on record  271000
on record  272000
on record  273000
Bad  27 mailingaddress1 PO Box 110 nan <class 'str'> True
on record  274000
on record  275000
on record  276000
on record  277000
on record  278000
on record  279000
on record  280000
on record  281000
on record  282000
on record  283000
on record  284000
on record  285000
on record  286000
on record  287000
on record  288000
on record  289000
on record  290000
on record  291000
on record  292000
on record  293000
on record  294000
on record  295000
on record  296000
Bad  28 agentorganizationname Registered Agents Inc. nan <class 'str'> True
on record  297000
on record  298000
on record  299000
on record  300000
on record  301000
on record  302000
on record  303000
on record  304000
on record  305000
on record  306000
on record  307000
on record  308000
on record  309000
on record  310000
on record  311000
Bad  29 agentorganizationname C T Corporation System nan <class 'str'> True
on record  312000
on record  313000
on record  314000
on record  315000
on record  316000
Bad  30 agentmailingaddress1 1550 WEWATTA STREET nan <class 'str'> True
Bad  31 agentorganizationname MESSNER REEVES, LLP nan <class 'str'> True
on record  317000
on record  318000
on record  319000
Bad  32 mailingaddress1 PO Box 76120 nan <class 'str'> True
on record  320000
on record  321000
on record  322000
on record  323000
on record  324000
on record  325000
on record  326000
on record  327000
Bad  33 principaladdress2 301 nan <class 'str'> True
on record  328000
on record  329000
on record  330000
on record  331000
on record  332000
on record  333000
on record  334000
on record  335000
on record  336000
on record  337000
on record  338000
on record  339000
on record  340000
on record  341000
on record  342000
on record  343000
on record  344000
on record  345000
on record  346000
on record  347000
on record  348000
on record  349000
on record  350000
on record  351000
on record  352000
on record  353000
on record  354000
on record  355000
on record  356000
on record  357000
on record  358000
on record  359000
on record  360000
Bad  34 agentmailingaddress1 7040 Elizabeth St nan <class 'str'> True
on record  361000
on record  362000
on record  363000
Bad  35 agentprincipaladdress2 Suite 320S nan <class 'str'> True
on record  364000
Bad  36 agentmailingaddress1 3001 Brighton Blvd Ste 236 nan <class 'str'> True
on record  365000
on record  366000
on record  367000
on record  368000
on record  369000
on record  370000
on record  371000
on record  372000
on record  373000
on record  374000
on record  375000
on record  376000
on record  377000
on record  378000
on record  379000
on record  380000
on record  381000
on record  382000
on record  383000
on record  384000
on record  385000
on record  386000
on record  387000
on record  388000
on record  389000
on record  390000
on record  391000
on record  392000
on record  393000
on record  394000
on record  395000
on record  396000
on record  397000
on record  398000
on record  399000
on record  400000
on record  401000
on record  402000
on record  403000
on record  404000
on record  405000
on record  406000
on record  407000
on record  408000
Bad  37 principaladdress2 PO BOX 874 nan <class 'str'> True
on record  409000
on record  410000
on record  411000
on record  412000
on record  413000
on record  414000
Bad  38 agentprincipaladdress2 C/O Three Mile Creek B B & B Ltd nan <class 'str'> True
on record  415000
on record  416000
on record  417000
Bad  39 principaladdress2 Suite G nan <class 'str'> True
on record  418000
Bad  40 agentmailingaddress2 291 Main Street nan <class 'str'> True
on record  419000
on record  420000
on record  421000
on record  422000
on record  423000
on record  424000
on record  425000
on record  426000
on record  427000
on record  428000
on record  429000
on record  430000
on record  431000
on record  432000
Bad  41 mailingaddress1 2756 41st Ave nan <class 'str'> True
on record  433000
on record  434000
on record  435000
on record  436000
on record  437000
on record  438000
on record  439000
on record  440000
on record  441000
on record  442000
on record  443000
on record  444000
on record  445000
Bad  42 agentorganizationname C T Corporation System nan <class 'str'> True
on record  446000
on record  447000
on record  448000
on record  449000
on record  450000
on record  451000
on record  452000
on record  453000
on record  454000
on record  455000
on record  456000
on record  457000
Bad  43 mailingcountry US nan <class 'str'> True
on record  458000
on record  459000
on record  460000
on record  461000
on record  462000
Bad  44 mailingaddress1 33623 Smith Rd. nan <class 'str'> True
on record  463000
Bad  45 mailingaddress1 16671 W 74th  Ave nan <class 'str'> True
on record  464000
Bad  46 principaladdress2 Suite 105 nan <class 'str'> True
Bad  47 principaladdress2 Ste 505S nan <class 'str'> True
on record  465000
on record  466000
on record  467000
on record  468000
on record  469000
on record  470000
Bad  48 agentprincipaladdress2 SUITE D nan <class 'str'> True
Bad  49 mailingaddress1 19578 East 52nd Avenue nan <class 'str'> True
on record  471000
on record  472000
on record  473000
on record  474000
on record  475000
on record  476000
Bad  50 agentprincipaladdress2 SUITE102 nan <class 'str'> True
on record  477000
on record  478000
on record  479000
on record  480000
on record  481000
on record  482000
on record  483000
on record  484000
on record  485000
on record  486000
on record  487000
on record  488000
on record  489000
on record  490000
on record  491000
on record  492000
on record  493000
on record  494000
on record  495000
on record  496000
on record  497000
on record  498000
on record  499000
on record  500000
on record  501000
on record  502000
on record  503000
on record  504000
on record  505000
on record  506000
on record  507000
on record  508000
on record  509000
on record  510000
on record  511000
on record  512000
on record  513000
on record  514000
on record  515000
Bad  51 entityformdate 2004-03-31T00:00:00.000 2004-03-31 00:00:00 <class 'str'> True
on record  516000
Bad  52 agentprincipaladdress2 # 105 nan <class 'str'> True
on record  517000
on record  518000
on record  519000
on record  520000
on record  521000
on record  522000
on record  523000
on record  524000
on record  525000
on record  526000
on record  527000
on record  528000
Bad  53 mailingaddress1 2800 s syracuse way nan <class 'str'> True
on record  529000
on record  530000
on record  531000
on record  532000
on record  533000
on record  534000
on record  535000
on record  536000
on record  537000
on record  538000
on record  539000
on record  540000
on record  541000
on record  542000
on record  543000
on record  544000
on record  545000
on record  546000
on record  547000
on record  548000
on record  549000
on record  550000
on record  551000
on record  552000
on record  553000
on record  554000
on record  555000
on record  556000
on record  557000
on record  558000
on record  559000
on record  560000
on record  561000
on record  562000
on record  563000
Bad  54 principaladdress2 Suite 100 nan <class 'str'> True
on record  564000
on record  565000
on record  566000
on record  567000
on record  568000
on record  569000
on record  570000
Bad  55 agentprincipaladdress2 Suite A nan <class 'str'> True
on record  571000
on record  572000
on record  573000
on record  574000
on record  575000
on record  576000
on record  577000
on record  578000
on record  579000
on record  580000
on record  581000
on record  582000
on record  583000
on record  584000
on record  585000
on record  586000
on record  587000
on record  588000
on record  589000
on record  590000
on record  591000
on record  592000
on record  593000
on record  594000
on record  595000
on record  596000
on record  597000
on record  598000
on record  599000
on record  600000
on record  601000
on record  602000
on record  603000
on record  604000
on record  605000
on record  606000
Bad  56 principaladdress2 #635 nan <class 'str'> True
on record  607000
on record  608000
Bad  57 agentprincipaladdress2 Suite B-210 nan <class 'str'> True
on record  609000
on record  610000
on record  611000
on record  612000
on record  613000
on record  614000
on record  615000
on record  616000
Bad  58 agentmailingaddress1 496 S Broadway nan <class 'str'> True
on record  617000
on record  618000
on record  619000
on record  620000
on record  621000
on record  622000
on record  623000
on record  624000
on record  625000
on record  626000
on record  627000
on record  628000
on record  629000
on record  630000
on record  631000
on record  632000
on record  633000
on record  634000
Bad  59 agentmailingaddress2 5331 Lighthouse Point Court nan <class 'str'> True
on record  635000
on record  636000
on record  637000
on record  638000
on record  639000
on record  640000
Bad  60 mailingcountry US nan <class 'str'> True
on record  641000
on record  642000
on record  643000
on record  644000
on record  645000
on record  646000
on record  647000
on record  648000
on record  649000
on record  650000
on record  651000
on record  652000
on record  653000
on record  654000
Bad  61 agentprincipaladdress2 #2121 nan <class 'str'> True
on record  655000
on record  656000
on record  657000
Bad  62 agentmiddlename R. nan <class 'str'> True
on record  658000
on record  659000
on record  660000
Bad  63 agentmailingaddress1 201 E. 4th Street #130 nan <class 'str'> True
on record  661000
on record  662000
Bad  64 agentprincipaladdress2 Suite 180 nan <class 'str'> True
on record  663000
on record  664000
on record  665000
on record  666000
on record  667000
Bad  65 principaladdress2 1544 Benton St nan <class 'str'> True
on record  668000
on record  669000
on record  670000
on record  671000
on record  672000
on record  673000
on record  674000
on record  675000
on record  676000
Bad  66 mailingaddress1 130 E Washington St Ste 1100 nan <class 'str'> True
on record  677000
on record  678000
on record  679000
on record  680000
on record  681000
on record  682000
on record  683000
on record  684000
on record  685000
on record  686000
on record  687000
on record  688000
Bad  67 mailingcountry US nan <class 'str'> True
on record  689000
on record  690000
on record  691000
on record  692000
on record  693000
on record  694000
on record  695000
on record  696000
Bad  68 principaladdress2 Ste 505S nan <class 'str'> True
on record  697000
on record  698000
on record  699000
on record  700000
on record  701000
on record  702000
on record  703000
on record  704000
on record  705000
on record  706000
on record  707000
on record  708000
on record  709000
on record  710000
on record  711000
on record  712000
on record  713000
on record  714000
Bad  69 mailingaddress1 P.O. Box 1020 nan <class 'str'> True
on record  715000
on record  716000
on record  717000
on record  718000
on record  719000
on record  720000
on record  721000
on record  722000
on record  723000
Bad  70 agentmailingaddress1 2800 Cornerstone Drive nan <class 'str'> True
on record  724000
on record  725000
on record  726000
on record  727000
on record  728000
on record  729000
Bad  71 mailingaddress1 38830 CR 77 nan <class 'str'> True
on record  730000
on record  731000
on record  732000
on record  733000
on record  734000
Bad  72 agentmailingaddress1 2521 S Genoa St nan <class 'str'> True
on record  735000
on record  736000
on record  737000
on record  738000
on record  739000
on record  740000
on record  741000
on record  742000
on record  743000
on record  744000
on record  745000
on record  746000
on record  747000
on record  748000
on record  749000
on record  750000
on record  751000
on record  752000
on record  753000
Bad  73 principaladdress2 Suite330 nan <class 'str'> True
Bad  74 mailingaddress1 PO Box 246 nan <class 'str'> True
on record  754000
on record  755000
on record  756000
on record  757000
on record  758000
on record  759000
on record  760000
on record  761000
on record  762000
on record  763000
on record  764000
on record  765000
on record  766000
on record  767000
on record  768000
on record  769000
on record  770000
on record  771000
on record  772000
on record  773000
on record  774000
on record  775000
on record  776000
on record  777000
Bad  75 mailingaddress1 P.O. Box 307 nan <class 'str'> True
on record  778000
on record  779000
on record  780000
on record  781000
Bad  76 agentprincipaladdress2 Unit 7 nan <class 'str'> True
on record  782000
on record  783000
on record  784000
on record  785000
on record  786000
on record  787000
on record  788000
on record  789000
on record  790000
on record  791000
on record  792000
on record  793000
on record  794000
on record  795000
on record  796000
on record  797000
Bad  77 mailingaddress1 6660 Delmonico Dr Suite D240 nan <class 'str'> True
on record  798000
on record  799000
on record  800000
on record  801000
on record  802000
on record  803000
on record  804000
on record  805000
on record  806000
on record  807000
on record  808000
on record  809000
on record  810000
on record  811000
on record  812000
on record  813000
on record  814000
on record  815000
Bad  78 mailingaddress1 150 PlayCore Drive SE nan <class 'str'> True
on record  816000
on record  817000
on record  818000
on record  819000
on record  820000
on record  821000
on record  822000
on record  823000
on record  824000
on record  825000
on record  826000
on record  827000
on record  828000
on record  829000
on record  830000
on record  831000
on record  832000
on record  833000
on record  834000
on record  835000
on record  836000
on record  837000

In [304]:
xx = x.loc[x["entityid"] == 19871025787].to_dict(orient="index")

In [307]:
for k,v in xx.items():
    print(v)

{'entityid': 19871025787, 'entityname': 'UNIVERSITY OF DENVER', 'principaladdress1': '2199 S University Blvd.', 'principaladdress2': nan, 'principalcity': 'Denver', 'principalstate': 'CO', 'principalzipcode': '80208', 'principalcountry': 'US', 'mailingaddress1': nan, 'mailingaddress2': nan, 'mailingcity': nan, 'mailingstate': nan, 'mailingzipcode': nan, 'mailingcountry': nan, 'entitystatus': 'Good Standing', 'jurisdictonofformation': 'CO', 'entitytype': 'Nonprofit Corporation', 'agentfirstname': 'Linda', 'agentmiddlename': nan, 'agentlastname': 'Kosten', 'agentsuffix': nan, 'agentorganizationname': nan, 'agentprincipaladdress1': '2199 S UNIVERSITY BLVD', 'agentprincipaladdress2': nan, 'agentprincipalcity': 'DENVER', 'agentprincipalstate': 'CO', 'agentprincipalzipcode': '80208', 'agentprincipalcountry': 'US', 'agentmailingaddress1': '2199 S. University Blvd', 'agentmailingaddress2': 'Mary Reed Bldg, Room 103', 'agentmailingcity': 'Denver', 'agentmailingstate': 'CO', 'agentmailingzipcode': '80210', 'agentmailingcountry': 'US', 'entityformdate': '1864-03-05T00:00:00.000'}

In [15]:
eid= 20221762581
display(dfOrig.loc[dfOrig["Entity Id"] == eid])

display(dfBusCIM.loc[dfBusCIM["entityid"] == eid])
display(dfXen.loc[dfXen["entityId"] ==  eid])

,Entity Id,Entity Name,Principal Address 1,Principal Address 2,Principal City,Principal State,Principal Zip,Principal Country,Mailing Address 1,Mailing Address 2,Mailing City,Mailing State,Mailing Zip,Mailing Country,Entity Status,Jurisdiction of Formation,Perpetual Flag,Term Date,Entity Type,Agent First Name,Agent Middle Name,Agent Last Name,Agent Suffix,Agent Organization Name,Agent Principal Address 1,Agent Principal Address 2,Agent Principal City,Agent Principal State,Agent Principal Zip,Agent Principal Country,Agent Mailing Address 1,Agent Mailing Address 2,Agent Mailing City,Agent Mailing State,Agent Mailing Zip,Agent Mailing Country,Entity Form Date
2238648,20221762581,"Jantzen & Jantzen, LLC",12735 Bowen Bluffs Point,NaN,Colorado Springs,CO,80921,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Y,NaN,DLLC,Jordan,D,Jantzen,NaN,NaN,575 Hidden Marsh Rd,NaN,Monument,CO,80132-8835,US,PO Box 694,NaN,Palmer Lake,CO,80133-0694,US,08/03/2022

,entityid,entityname,principaladdress1,principaladdress2,principalcity,principalstate,principalzipcode,principalcountry,mailingaddress1,mailingaddress2,mailingcity,mailingstate,mailingzipcode,mailingcountry,entitystatus,jurisdictonofformation,entitytype,agentfirstname,agentmiddlename,agentlastname,agentsuffix,agentorganizationname,agentprincipaladdress1,agentprincipaladdress2,agentprincipalcity,agentprincipalstate,agentprincipalzipcode,agentprincipalcountry,agentmailingaddress1,agentmailingaddress2,agentmailingcity,agentmailingstate,agentmailingzipcode,agentmailingcountry,entityformdate
2257864,20221762581,"Jantzen & Jantzen, LLC",575 Hidden Marsh Rd,NaN,Monument,CO,80132-8835,US,PO Box 694,NaN,Palmer Lake,CO,80133-0694,US,Good Standing,CO,Limited Liability Company,Jordan,D,Jantzen,NaN,NaN,575 Hidden Marsh Rd,NaN,Monument,CO,80132-8835,US,PO Box 694,NaN,Palmer Lake,CO,80133-0694,US,08/03/2022

,entityId,entityName,principalAddress1,principalAddress2,principalCity,principalState,principalZipCode,principalCountry,mailingAddress1,mailingAddress2,mailingCity,mailingState,mailingZipCode,mailingCountry,entityStatus,jurisdictonOfFormation,entityType,agentFirstName,agentMiddleName,agentLastName,agentSuffix,agentOrganizationName,agentPrincipalAddress1,agentPrincipalAddress2,agentPrincipalCity,agentPrincipalState,agentPrincipalZipCode,agentPrincipalCountry,agentMailingAddress1,agentMailingAddress2,agentMailingCity,agentMailingState,agentMailingZipCode,agentMailingCountry,entityFormDate
2238648,20221762581,"Jantzen & Jantzen, LLC",12735 Bowen Bluffs Point,NaN,Colorado Springs,CO,80921,US,NaN,NaN,NaN,NaN,NaN,NaN,Good Standing,CO,Limited Liability Company,Jordan,D,Jantzen,NaN,NaN,575 Hidden Marsh Rd,NaN,Monument,CO,80132-8835,US,PO Box 694,NaN,Palmer Lake,CO,80133-0694,US,2022-08-03T00:00:00.000

In [91]:
dfXenNoDup = dfXen.copy()
dfXenNoDup.drop_duplicates(inplace=True)
print(dfXen.shape,dfXenNoDup.shape)

(2514441, 35) (2481249, 35)

In [95]:
import warnings

from pandas.core.common import SettingWithCopyWarning

warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)


eids =dfBusCIM["entityid"].unique()
# eids2 = [20221863095,20221869984,20221882168,20221910188,20221922627] 
# eids2.extend(eids1)
nrec=0
for eid in eids:

    a = dfBusCIM.loc[dfBusCIM["entityid"] == eid]
    b = dfXenNoDup.loc[dfXenNoDup["entityId"] == eid]
    a.drop("entityformdate",inplace=True,axis=1)
    b.drop("entityFormDate",inplace=True,axis=1)
    
    cols=[]
    org = []
    new = []
    for col in b:
     #   print(col,a[col.lower()].values[0],b[col].values[0])
     #   if isinstance(a[col.lower()].values[0],str):
        if isinstance(a[col.lower()].values[0],str):
            a[col.lower()] = a[col.lower()].values[0].strip()
        if isinstance(b[col].values[0],str):
            b[col].values[0] = b[col].values[0].strip()
       
        cols.append(col)
        org.append(a[col.lower()].values[0])
        new.append(b[col].values[0])

    
    c = pd.DataFrame({"Column":cols,"Orig Val":org,"New Val":new})
 #   for nn in range(len(org)):
       # if org[nn] != new[nn]:
       #     if isinstance(org[nn],str):
       #        print(f"{cols[nn]}  {type(org[nn])}  :{len(org[nn])}:  :{len(new[nn])}:")
    if not c["Orig Val"].equals(c["New Val"]):
#    display(c)
       print("Bad Boy ",eid)
       print(eid,file=open("compare-badids","a+"))
    nrec+=1
    if (nrec%500 == 0):
        print(f"Past Record {nrec}")

Past Record 500
Past Record 1000
Past Record 1500
Past Record 2000
Bad Boy  19871033282
Bad Boy  19871037801
Past Record 2500
Past Record 3000
Bad Boy  19871056751
Past Record 3500
Bad Boy  19871063401
Past Record 4000
Bad Boy  19871072644
Past Record 4500
Past Record 5000
Past Record 5500
Past Record 6000
Past Record 6500
Past Record 7000
Past Record 7500
Past Record 8000
Bad Boy  19871175925
Past Record 8500
Past Record 9000
Bad Boy  19871193805
Bad Boy  19871200533
Past Record 9500
Past Record 10000
Past Record 10500
Past Record 11000
Past Record 11500
Past Record 12000
Bad Boy  19871245640
Past Record 12500
Past Record 13000
Past Record 13500
Past Record 14000
Past Record 14500
Bad Boy  19871284242
Past Record 15000
Bad Boy  19871287024
Past Record 15500
Past Record 16000
Past Record 16500
Past Record 17000
Bad Boy  19871326127
Past Record 17500
Bad Boy  19871330666
Past Record 18000
Past Record 18500
Bad Boy  19871346653
Bad Boy  19871348094
Past Record 19000
Past Record 19500
Past Record 20000
Past Record 20500
Past Record 21000
Past Record 21500
Past Record 22000
Bad Boy  19871391046
Past Record 22500
Past Record 23000
Past Record 23500
Past Record 24000
Past Record 24500
Past Record 25000
Past Record 25500
Past Record 26000
Past Record 26500
Past Record 27000
Past Record 27500
Past Record 28000
Bad Boy  19871479966
Past Record 28500
Past Record 29000
Past Record 29500
Past Record 30000
Past Record 30500
Bad Boy  19871503248
Past Record 31000
Past Record 31500
Past Record 32000
Bad Boy  19871520861
Past Record 32500
Past Record 33000
Past Record 33500
Past Record 34000
Past Record 34500
Past Record 35000
Bad Boy  19871554684
Past Record 35500
Bad Boy  19871556615
Bad Boy  19871560230
Past Record 36000
Past Record 36500
Bad Boy  19871571944
Past Record 37000
Bad Boy  19871575118
Past Record 37500
Past Record 38000
Past Record 38500
Past Record 39000
Bad Boy  19871596758
Past Record 39500
Bad Boy  19871599319
Past Record 40000
Past Record 40500
Bad Boy  19871609408
Past Record 41000
Bad Boy  19871619226
Past Record 41500
Past Record 42000
Past Record 42500
Past Record 43000
Past Record 43500
Bad Boy  19871644018
Past Record 44000
Past Record 44500
Past Record 45000
Past Record 45500
Bad Boy  19871661123
Past Record 46000
Bad Boy  19871671732
Past Record 46500
Past Record 47000
Past Record 47500
Past Record 48000
Bad Boy  19871689080
Past Record 48500
Past Record 49000
Past Record 49500
Past Record 50000
Past Record 50500
Past Record 51000
Past Record 51500
Past Record 52000
Past Record 52500
Past Record 53000
Past Record 53500
Past Record 54000
Past Record 54500
Past Record 55000
Past Record 55500
Past Record 56000
Bad Boy  19881018271
Past Record 56500
Bad Boy  19881049022
Past Record 57000
Past Record 57500
Past Record 58000
Past Record 58500
Past Record 59000
Past Record 59500
Past Record 60000
Past Record 60500
Past Record 61000
Bad Boy  19891006847
Past Record 61500
Past Record 62000
Past Record 62500
Bad Boy  19891045137
Past Record 63000
Past Record 63500
Bad Boy  19891074526
Bad Boy  19891074135
Past Record 64000
Past Record 64500
Past Record 65000
Past Record 65500
Past Record 66000
Past Record 66500
Past Record 67000
Past Record 67500
Bad Boy  19901007170
Past Record 68000
Past Record 68500
Bad Boy  19901023042
Past Record 69000
Bad Boy  19901044631
Past Record 69500
Bad Boy  19901059283
Past Record 70000
Past Record 70500
Past Record 71000
Past Record 71500
Past Record 72000
Past Record 72500
Past Record 73000
Past Record 73500
Past Record 74000
Past Record 74500
Past Record 75000
Past Record 75500
Past Record 76000
Bad Boy  19911031320
Bad Boy  19911032705
Bad Boy  19911032882
Past Record 76500
Bad Boy  19911036073
Bad Boy  19911038643
Past Record 77000
Bad Boy  19911047840
Past Record 77500
Bad Boy  19911056474
Past Record 78000
Past Record 78500
Past Record 79000
Bad Boy  19911075496
Past Record 79500
Past Record 80000
Past Record 80500
Past Record 81000
Past Record 81500
Past Record 82000
Past Record 82500
Past Record 83000
Past Record 83500
Past Record 84000
Past Record 84500
Bad Boy  19921038072
Past Record 85000
Bad Boy  19921044835
Bad Boy  19921047255
Bad Boy  19921049215
Past Record 85500
Past Record 86000
Past Record 86500
Past Record 87000
Bad Boy  19921074037
Past Record 87500
Past Record 88000
Past Record 88500
Past Record 89000
Past Record 89500
Past Record 90000
Bad Boy  19921107810
Past Record 90500
Bad Boy  19921113113
Past Record 91000
Past Record 91500
Bad Boy  19921123342
Past Record 92000
Past Record 92500
Past Record 93000
Past Record 93500
Past Record 94000
Bad Boy  19931022366
Past Record 94500
Past Record 95000
Past Record 95500
Past Record 96000
Past Record 96500
Bad Boy  19931051856
Past Record 97000
Past Record 97500
Past Record 98000
Past Record 98500
Past Record 99000
Past Record 99500
Bad Boy  19931079698
Past Record 100000
Past Record 100500
Past Record 101000
Past Record 101500
Past Record 102000
Past Record 102500
Bad Boy  19931115648
Past Record 103000
Past Record 103500
Past Record 104000
Bad Boy  19931132862
Past Record 104500
Past Record 105000
Past Record 105500
Past Record 106000
Past Record 106500
Past Record 107000
Past Record 107500
Past Record 108000
Past Record 108500
Past Record 109000
Bad Boy  19941028536
Past Record 109500
Bad Boy  19941032367
Past Record 110000
Bad Boy  19941034704
Past Record 110500
Past Record 111000
Past Record 111500
Bad Boy  19941050072
Past Record 112000
Past Record 112500
Bad Boy  19941057478
Past Record 113000
Past Record 113500
Past Record 114000
Past Record 114500
Bad Boy  19941072839
Bad Boy  19941076423
Past Record 115000
Past Record 115500
Past Record 116000
Past Record 116500
Past Record 117000
Past Record 117500
Past Record 118000
Past Record 118500
Past Record 119000
Past Record 119500
Past Record 120000
Past Record 120500
Past Record 121000
Past Record 121500
Past Record 122000
Past Record 122500
Past Record 123000
Bad Boy  19941144851
Past Record 123500
Bad Boy  19951000140
Past Record 124000
Past Record 124500
Past Record 125000
Past Record 125500
Bad Boy  19951016315
Bad Boy  19951018093
Past Record 126000
Past Record 126500
Past Record 127000
Past Record 127500
Past Record 128000
Past Record 128500
Past Record 129000
Past Record 129500
Past Record 130000
Past Record 130500
Past Record 131000
Past Record 131500
Bad Boy  19951069729
Past Record 132000
Past Record 132500
Bad Boy  19951077997
Past Record 133000
Past Record 133500
Past Record 134000
Past Record 134500
Past Record 135000
Past Record 135500
Past Record 136000
Past Record 136500
Bad Boy  19951107843
Past Record 137000
Past Record 137500
Past Record 138000
Past Record 138500
Past Record 139000
Past Record 139500
Past Record 140000
Past Record 140500
Past Record 141000
Past Record 141500
Past Record 142000
Past Record 142500
Past Record 143000
Bad Boy  19951149529
Past Record 143500
Past Record 144000
Past Record 144500
Past Record 145000
Past Record 145500
Past Record 146000
Past Record 146500
Past Record 147000
Past Record 147500
Past Record 148000
Past Record 148500
Past Record 149000
Past Record 149500
Past Record 150000
Past Record 150500
Past Record 151000
Bad Boy  19961034546
Bad Boy  19961035185
Past Record 151500
Past Record 152000
Past Record 152500
Past Record 153000
Past Record 153500
Past Record 154000
Past Record 154500
Bad Boy  19961056608
Past Record 155000
Past Record 155500
Bad Boy  19961061964
Past Record 156000
Past Record 156500
Past Record 157000
Past Record 157500
Past Record 158000
Past Record 158500
Past Record 159000
Bad Boy  19961083900
Bad Boy  19961084578
Past Record 159500
Past Record 160000
Past Record 160500
Past Record 161000
Past Record 161500
Past Record 162000
Past Record 162500
Past Record 163000
Past Record 163500
Past Record 164000
Past Record 164500
Past Record 165000
Past Record 165500
Past Record 166000
Past Record 166500
Past Record 167000
Past Record 167500
Past Record 168000
Past Record 168500
Bad Boy  19961141995
Past Record 169000
Past Record 169500
Past Record 170000
Past Record 170500
Bad Boy  19961153080
Past Record 171000
Past Record 171500
Past Record 172000
Bad Boy  19961161053
Past Record 172500
Past Record 173000
Past Record 173500
Bad Boy  19961170804
Past Record 174000
Past Record 174500
Past Record 175000
Bad Boy  19971005717
Past Record 175500
Bad Boy  19971010313
Past Record 176000
Past Record 176500
Bad Boy  19971014987
Past Record 177000
Past Record 177500
Past Record 178000
Past Record 178500
Past Record 179000
Past Record 179500
Past Record 180000
Past Record 180500
Bad Boy  19971043477
Past Record 181000
Bad Boy  19971046485
Past Record 181500
Bad Boy  19971046674
Past Record 182000
Past Record 182500
Bad Boy  19971056930
Past Record 183000
Past Record 183500
Past Record 184000
Past Record 184500
Past Record 185000
Past Record 185500
Bad Boy  19971073921
Bad Boy  19971074618
Bad Boy  19971074731
Bad Boy  19971074783
Bad Boy  19971075912
Past Record 186000
Bad Boy  19971079465
Past Record 186500
Past Record 187000
Past Record 187500
Past Record 188000
Past Record 188500
Bad Boy  19971095601
Past Record 189000
Past Record 189500
Past Record 190000
Past Record 190500
Past Record 191000
Past Record 191500
Past Record 192000
Past Record 192500
Bad Boy  19971122711
Past Record 193000
Past Record 193500
Past Record 194000
Bad Boy  19971131869
Bad Boy  19971134894
Past Record 194500
Past Record 195000
Past Record 195500
Past Record 196000
Past Record 196500
Past Record 197000
Past Record 197500
Past Record 198000
Past Record 198500
Past Record 199000
Past Record 199500
Past Record 200000
Past Record 200500
Past Record 201000
Past Record 201500
Past Record 202000
Past Record 202500
Past Record 203000
Past Record 203500
Past Record 204000
Past Record 204500
Past Record 205000
Past Record 205500
Past Record 206000
Past Record 206500
Past Record 207000
Past Record 207500
Past Record 208000
Past Record 208500
Past Record 209000
Past Record 209500
Past Record 210000
Past Record 210500
Past Record 211000
Bad Boy  19981039402
Past Record 211500
Bad Boy  19981043122
Past Record 212000
Bad Boy  19981044933
Past Record 212500
Past Record 213000
Bad Boy  19981053172
Past Record 213500
Past Record 214000
Bad Boy  19981057570
Past Record 214500
Past Record 215000
Bad Boy  19981065536
Past Record 215500
Past Record 216000
Bad Boy  19981073334
Past Record 216500
Bad Boy  19981076636
Bad Boy  19981077933
Past Record 217000
Past Record 217500
Bad Boy  19981081562
Bad Boy  19981081910
Bad Boy  19981082567
Bad Boy  19981085317
Past Record 218000
Past Record 218500
Past Record 219000
Bad Boy  19981094262
Past Record 219500
Bad Boy  19981096681
Past Record 220000
Past Record 220500
Bad Boy  19981105902
Past Record 221000
Past Record 221500
Past Record 222000
Past Record 222500
Past Record 223000
Past Record 223500
Past Record 224000
Past Record 224500
Bad Boy  19981132659
Past Record 225000
Past Record 225500
Past Record 226000
Past Record 226500
Past Record 227000
Past Record 227500
Past Record 228000
Past Record 228500
Past Record 229000
Past Record 229500
Past Record 230000
Past Record 230500
Past Record 231000
Past Record 231500
Past Record 232000
Past Record 232500
Past Record 233000
Past Record 233500
Past Record 234000
Bad Boy  19981199524
Past Record 234500
Past Record 235000
Past Record 235500
Past Record 236000
Past Record 236500
Bad Boy  19981216235
Past Record 237000
Bad Boy  19981220839
Past Record 237500
Bad Boy  19981223924
Past Record 238000
Past Record 238500
Past Record 239000
Past Record 239500
Past Record 240000
Past Record 240500
Past Record 241000
Past Record 241500
Bad Boy  19991013620
Bad Boy  19991016959
Past Record 242000
Past Record 242500
Past Record 243000
Past Record 243500
Past Record 244000
Past Record 244500
Past Record 245000
Bad Boy  19991040403
Past Record 245500
Bad Boy  19991041567
Past Record 246000
Past Record 246500
Past Record 247000
Past Record 247500
Past Record 248000
Bad Boy  19991059180
Past Record 248500
Past Record 249000
Past Record 249500
Past Record 250000
Past Record 250500
Bad Boy  19991073135
Bad Boy  19991073140
Bad Boy  19991073809
Past Record 251000
Past Record 251500
Past Record 252000
Past Record 252500
Bad Boy  19991088516
Past Record 253000
Past Record 253500
Bad Boy  19991094001
Past Record 254000
Past Record 254500
Bad Boy  19991101012
Past Record 255000
Bad Boy  19991104066
Past Record 255500
Past Record 256000
Past Record 256500
Past Record 257000
Past Record 257500
Bad Boy  19991119092
Past Record 258000
Past Record 258500
Past Record 259000
Past Record 259500
Past Record 260000
Past Record 260500
Bad Boy  19991137705
Past Record 261000
Past Record 261500
Past Record 262000
Past Record 262500
Past Record 263000
Past Record 263500
Past Record 264000
Bad Boy  19991162295
Past Record 264500
Past Record 265000
Past Record 265500
Past Record 266000
Past Record 266500
Past Record 267000
Bad Boy  19991182207
Past Record 267500
Past Record 268000
Past Record 268500
Past Record 269000
Past Record 269500
Past Record 270000
Past Record 270500
Past Record 271000
Past Record 271500
Past Record 272000
Bad Boy  19991214877
Past Record 272500
Past Record 273000
Past Record 273500
Past Record 274000
Past Record 274500
Past Record 275000
Past Record 275500
Past Record 276000
Past Record 276500
Past Record 277000
Past Record 277500
Past Record 278000
Past Record 278500
Past Record 279000
Past Record 279500
Past Record 280000
Past Record 280500
Past Record 281000
Past Record 281500
Past Record 282000
Past Record 282500
Bad Boy  20001030370
Past Record 283000
Past Record 283500
Past Record 284000
Past Record 284500
Past Record 285000
Past Record 285500
Past Record 286000
Bad Boy  20001050535
Past Record 286500
Bad Boy  20001055128
Past Record 287000
Past Record 287500
Past Record 288000
Bad Boy  20001063222
Past Record 288500
Past Record 289000
Past Record 289500
Bad Boy  20001070942
Past Record 290000
Past Record 290500
Bad Boy  20001077687
Bad Boy  20001077690
Past Record 291000
Past Record 291500
Past Record 292000
Past Record 292500
Past Record 293000
Bad Boy  20001095838
Past Record 293500
Past Record 294000
Bad Boy  20001099907
Past Record 294500
Bad Boy  20001105189
Past Record 295000
Past Record 295500
Past Record 296000
Past Record 296500
Past Record 297000
Past Record 297500
Past Record 298000
Past Record 298500
Past Record 299000
Past Record 299500
Past Record 300000
Past Record 300500
Bad Boy  20001140031
Past Record 301000
Past Record 301500
Past Record 302000
Past Record 302500
Past Record 303000
Bad Boy  20001155465
Past Record 303500
Past Record 304000
Past Record 304500
Past Record 305000
Past Record 305500
Past Record 306000
Past Record 306500
Past Record 307000
Past Record 307500
Past Record 308000
Past Record 308500
Past Record 309000
Past Record 309500
Past Record 310000
Past Record 310500
Past Record 311000
Past Record 311500
Past Record 312000
Past Record 312500
Past Record 313000
Past Record 313500
Past Record 314000
Past Record 314500
Past Record 315000
Past Record 315500
Past Record 316000
Past Record 316500
Past Record 317000
Past Record 317500
Past Record 318000
Past Record 318500
Past Record 319000
Past Record 319500
Past Record 320000
Past Record 320500
Past Record 321000
Past Record 321500
Past Record 322000
Bad Boy  20011019120
Past Record 322500
Past Record 323000
Past Record 323500
Bad Boy  20011028859
Past Record 324000
Past Record 324500
Past Record 325000
Past Record 325500
Past Record 326000
Past Record 326500
Bad Boy  20011051561
Past Record 327000
Past Record 327500
Bad Boy  20011056467
Past Record 328000
Past Record 328500
Past Record 329000
Past Record 329500
Past Record 330000
Past Record 330500
Bad Boy  20011073954
Past Record 331000
Bad Boy  20011076030
Bad Boy  20011077076
Past Record 331500
Past Record 332000
Past Record 332500
Past Record 333000
Past Record 333500
Past Record 334000
Past Record 334500
Bad Boy  20011097520
Bad Boy  20011098944
Past Record 335000
Bad Boy  20011100080
Past Record 335500
Bad Boy  20011104363
Bad Boy  20011105336
Past Record 336000
Past Record 336500
Bad Boy  20011109708
Past Record 337000
Past Record 337500
Past Record 338000
Past Record 338500
Past Record 339000
Past Record 339500
Past Record 340000
Past Record 340500
Past Record 341000
Past Record 341500
Past Record 342000
Past Record 342500
Past Record 343000
Past Record 343500
Past Record 344000
Past Record 344500
Past Record 345000
Past Record 345500
Past Record 346000
Past Record 346500
Past Record 347000
Past Record 347500
Past Record 348000
Past Record 348500
Past Record 349000
Past Record 349500
Past Record 350000
Past Record 350500
Past Record 351000
Past Record 351500
Past Record 352000
Past Record 352500
Past Record 353000
Past Record 353500
Bad Boy  20011214622
Past Record 354000
Past Record 354500
Past Record 355000
Bad Boy  20141110204
Past Record 355500
Past Record 356000
Past Record 356500
Past Record 357000
Past Record 357500
Past Record 358000
Past Record 358500
Past Record 359000
Bad Boy  20011244933
Past Record 359500
Past Record 360000
Past Record 360500
Past Record 361000
Past Record 361500
Past Record 362000
Past Record 362500
Past Record 363000
Past Record 363500
Past Record 364000
Past Record 364500
Bad Boy  20021028218
Past Record 365000
Past Record 365500
Past Record 366000
Past Record 366500
Past Record 367000
Past Record 367500
Past Record 368000
Past Record 368500
Bad Boy  20021058026
Past Record 369000
Bad Boy  20021063920
Past Record 369500
Bad Boy  20021065540
Past Record 370000
Past Record 370500
Past Record 371000
Past Record 371500
Past Record 372000
Past Record 372500
Past Record 373000
Past Record 373500
Past Record 374000
Past Record 374500
Bad Boy  20021105780
Past Record 375000
Past Record 375500
Past Record 376000
Past Record 376500
Past Record 377000
Past Record 377500
Past Record 378000
Past Record 378500
Past Record 379000
Past Record 379500
Past Record 380000
Bad Boy  20021153986
Past Record 380500
Bad Boy  20021154821
Bad Boy  20021155530
Past Record 381000
Past Record 381500
Past Record 382000
Bad Boy  20021167849
Past Record 382500
Past Record 383000
Past Record 383500
Past Record 384000
Past Record 384500
Past Record 385000
Past Record 385500
Past Record 386000
Past Record 386500
Past Record 387000
Past Record 387500
Past Record 388000
Past Record 388500
Past Record 389000
Past Record 389500
Past Record 390000
Past Record 390500
Past Record 391000
Past Record 391500
Past Record 392000
Past Record 392500
Past Record 393000
Past Record 393500
Past Record 394000
Past Record 394500
Past Record 395000
Past Record 395500
Past Record 396000
Past Record 396500
Bad Boy  20021289782
Past Record 397000
Past Record 397500
Past Record 398000
Past Record 398500
Past Record 399000
Past Record 399500
Past Record 400000
Past Record 400500
Past Record 401000
Past Record 401500
Bad Boy  20021325924
Past Record 402000
Past Record 402500
Past Record 403000
Past Record 403500
Past Record 404000
Past Record 404500
Past Record 405000
Past Record 405500
Past Record 406000
Past Record 406500
Past Record 407000
Past Record 407500
Past Record 408000
Bad Boy  20031012739
Past Record 408500
Bad Boy  20031020350
Past Record 409000
Past Record 409500
Past Record 410000
Past Record 410500
Past Record 411000
Past Record 411500
Past Record 412000
Past Record 412500
Past Record 413000
Past Record 413500
Past Record 414000
Past Record 414500
Past Record 415000
Past Record 415500
Past Record 416000
Past Record 416500
Past Record 417000
Past Record 417500
Bad Boy  20031092036
Past Record 418000
Past Record 418500
Past Record 419000
Past Record 419500
Past Record 420000
Past Record 420500
Past Record 421000
Past Record 421500
Bad Boy  20031123675
Past Record 422000
Bad Boy  20031130636
Past Record 422500
Past Record 423000
Past Record 423500
Bad Boy  20031141464
Bad Boy  20031144360
Past Record 424000
Bad Boy  20031146351
Bad Boy  20031147417
Bad Boy  20031148576
Bad Boy  20031148577
Past Record 424500
Bad Boy  20031152220

IndexError: index 0 is out of bounds for axis 0 with size 0

In [77]:
display(c)

                    Column            Orig Val             New Val
0                 entityId         20221922627         20221922627
1               entityName          ORKD CORP.          ORKD CORP.
2        principalAddress1  324 INVERNESS DR S  324 INVERNESS DR S
3        principalAddress2          SUITE 7301          SUITE 7301
4            principalCity           Englewood           Englewood
5           principalState                  CO                  CO
6         principalZipCode               80112               80112
7         principalCountry                  US                  US
8          mailingAddress1                 NaN                 NaN
9          mailingAddress2                 NaN                 NaN
10             mailingCity                 NaN                 NaN
11            mailingState                 NaN                 NaN
12          mailingZipCode                 NaN                 NaN
13          mailingCountry                 NaN                 NaN
14            entityStatus       Good Standing       Good Standing
15  jurisdictonOfFormation                  CO                  CO
16              entityType         Corporation         Corporation
17          agentFirstName            CATALEYA                 TIA
18         agentMiddleName                   A                 NaN
19           agentLastName             MADEIRA           JIMMERSON
20             agentSuffix                 NaN                 NaN
21   agentOrganizationName                 NaN                 NaN
22  agentPrincipalAddress1  10205 TALIESIN DR.  10205 TALIESIN DR.
23  agentPrincipalAddress2                 NaN                 NaN
24      agentPrincipalCity           ENGLEWOOD           ENGLEWOOD
25     agentPrincipalState                  CO                  CO
26   agentPrincipalZipCode               80112               80112
27   agentPrincipalCountry                  US                  US
28    agentMailingAddress1  324 INVERNESS DR S  324 INVERNESS DR S
29    agentMailingAddress2          SUITE 7301          SUITE 7301
30        agentMailingCity           ENGLEWOOD           ENGLEWOOD
31       agentMailingState                  CO                  CO
32     agentMailingZipCode               80112               80112
33     agentMailingCountry                  US                  US