In [1]:
import pandas as pd

In [17]:
df = pd.read_csv("/home/joe/bic_etl/cdos/business/business/scripts/rules/entitytype.csv")

In [3]:
df.head()

  Entity Type                            Entity Type Description
0          CS                                   Corporation Sole
1          CU                                       Credit Union
2        DC55                            Cooperative Association
3    DC55-PBC  Cooperative Association-Public Benefit Corpora...
4        DC56                                        Cooperative

In [5]:
data = pd.read_csv("https://data.colorado.gov/resource/4ykn-tg5h.csv?$limit=999999999")

In [6]:
data.columns

Index(['entityid', 'entityname', 'principaladdress1', 'principaladdress2',
       'principalcity', 'principalstate', 'principalzipcode',
       'principalcountry', 'mailingaddress1', 'mailingaddress2', 'mailingcity',
       'mailingstate', 'mailingzipcode', 'mailingcountry', 'entitystatus',
       'jurisdictonofformation', 'entitytype', 'agentfirstname',
       'agentmiddlename', 'agentlastname', 'agentsuffix',
       'agentorganizationname', 'agentprincipaladdress1',
       'agentprincipaladdress2', 'agentprincipalcity', 'agentprincipalstate',
       'agentprincipalzipcode', 'agentprincipalcountry',
       'agentmailingaddress1', 'agentmailingaddress2', 'agentmailingcity',
       'agentmailingstate', 'agentmailingzipcode', 'agentmailingcountry',
       'entityformdate'],
      dtype='object')

In [9]:
a = data['entitytype'].value_counts().to_dict()

In [18]:
df["Type Name"] = df["Entity Type"].map(a)

In [19]:
df.head(200)

   Entity Type                            Entity Type Description  Type Name
0           CS                                   Corporation Sole      287.0
1           CU                                       Credit Union       39.0
2         DC55                            Cooperative Association      181.0
3     DC55-PBC  Cooperative Association-Public Benefit Corpora...       27.0
4         DC56                                        Cooperative      719.0
5     DC56-PBC             Cooperative-Public Benefit Corporation       51.0
6         DLCA                    Limited Cooperative Association      291.0
7     DLCA-PBC  Limited Cooperative Association-Public Benefit...       82.0
8         DLLC                          Limited Liability Company  1803180.0
9        DLLLP              Limited Liability Limited Partnership    11693.0
10        DLLP                      Limited Liability Partnership    13104.0
11         DLP                                Limited Partnership    22099.0
12        DLPA                    Limited Partnership Association      516.0
13         DNC                              Nonprofit Corporation   119393.0
14         DPC                                        Corporation   495875.0
15     DPC-PBC             Corporation-Public Benefit Corporation     2696.0
16          DT                                      Ditch Company      300.0
17       FCOOP                                Foreign Cooperative      144.0
18        FLCA            Foreign Limited Cooperative Association        5.0
19        FLLC                  Foreign Limited Liability Company   108540.0
20       FLLLP      Foreign Limited Liability Limited Partnership      442.0
21        FLLP              Foreign Limited Liability Partnership     1004.0
22         FLP                        Foreign Limited Partnership     8348.0
23        FLPA            Foreign Limited Partnership Association        6.0
24         FNC                      Foreign Nonprofit Corporation     7899.0
25          FO                                      Foreign Other     4899.0
26         FPC                                Foreign Corporation   112901.0
27          GP                                General Partnership     3833.0
28          IC                                  Insurance Company      958.0
29         IND                                         Individual        NaN
30          RG                          Foreign Name Registration        NaN
31          RS                                   Name Reservation        NaN
32          SL                                   Savings And Loan       21.0
33          SP                                Sole Proprietorship        2.0
34        TMSM                             Trademark/Service Mark        NaN
35      TRDNAM                                          Tradename        NaN
36         UNA               Unincorporated Nonprofit Association      480.0
37          WC                                      Water Company      222.0

In [14]:
df.dropna(inplace=True)

In [16]:
df.head(200)

   Entity Type                            Entity Type Description  Type Name
0           CS                                   Corporation Sole      287.0
1           CU                                       Credit Union       39.0
2         DC55                            Cooperative Association      181.0
3     DC55-PBC  Cooperative Association-Public Benefit Corpora...       27.0
4         DC56                                        Cooperative      719.0
5     DC56-PBC             Cooperative-Public Benefit Corporation       51.0
6         DLCA                    Limited Cooperative Association      291.0
7     DLCA-PBC  Limited Cooperative Association-Public Benefit...       82.0
8         DLLC                          Limited Liability Company  1803180.0
9        DLLLP              Limited Liability Limited Partnership    11693.0
10        DLLP                      Limited Liability Partnership    13104.0
11         DLP                                Limited Partnership    22099.0
12        DLPA                    Limited Partnership Association      516.0
13         DNC                              Nonprofit Corporation   119393.0
14         DPC                                        Corporation   495875.0
15     DPC-PBC             Corporation-Public Benefit Corporation     2696.0
16          DT                                      Ditch Company      300.0
17       FCOOP                                Foreign Cooperative      144.0
18        FLCA            Foreign Limited Cooperative Association        5.0
19        FLLC                  Foreign Limited Liability Company   108540.0
20       FLLLP      Foreign Limited Liability Limited Partnership      442.0
21        FLLP              Foreign Limited Liability Partnership     1004.0
22         FLP                        Foreign Limited Partnership     8348.0
23        FLPA            Foreign Limited Partnership Association        6.0
24         FNC                      Foreign Nonprofit Corporation     7899.0
25          FO                                      Foreign Other     4899.0
26         FPC                                Foreign Corporation   112901.0
27          GP                                General Partnership     3833.0
28          IC                                  Insurance Company      958.0
32          SL                                   Savings And Loan       21.0
33          SP                                Sole Proprietorship        2.0
36         UNA               Unincorporated Nonprofit Association      480.0
37          WC                                      Water Company      222.0

In [13]:
df.to_csv("entity_counts_Sept_2024.csv",index=False)