In [6]:
import glob,json
import pandas as pd
from croniter import croniter
from datetime import datetime
from cron_descriptor import get_description, ExpressionDescriptor
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)


# Set the CSS style for the DataFrame display
pd.set_option('display.max_colwidth', 100)

## run_etl.json

In [43]:
def find_files_recursive(directory):
    # This function finds all files recursively in a given directory
    return glob.glob(f'{directory}/**/run_etl.json', recursive=True)

def decodeExtract(extract):
    
    prog=""
    lang=""
    if 'language' in extract:
        lang=extract['language']
            
    if 'file' in extract:
        prog=extract['file']
        
    else:
        print("No Prgram",lang,title,file)
    opts={}
    if 'options' in extract:
        lang=extract['language']
        for opt in extract['options']:
            opt=opt.strip()
            indx=opt.find(" ")
            o=opt[:indx]
            opts[o]= opt[indx+1:]

    return lang,prog,opts


def processRun_etls(): 
## Get all run_etl.json files
    directory_path = '/home/joe/bic_etl'
    files = find_files_recursive(directory_path)
    
    
    
    datasets={}
    noEx=0
    for file in files:
        ll=len(file)
        group=file[18:-13]
        fin=open(file)
        infos = json.load(fin)
        fin.close()
        title=""
        extract=""
        for info in infos: 
            if 'title' in info:
                title=info['title']
                datasets[title]={}
                datasets[title]['extract']={}
                datasets[title]['extract']['language']=''
                datasets[title]['extract']['program']=''
                datasets[title]['extract']['options']={}
                datasets[title]['group']=group
                datasets[title]['transform']={}
                datasets[title]['load']={}
                
                
                if 'extract' in info:
                    extract=info['extract']
                    if isinstance(extract,dict):
                       lang,prog,opts=decodeExtract(extract)
                       datasets[title]['extract']['language']=lang
                       datasets[title]['extract']['program']=prog
                       datasets[title]['extract']['options']=opts
                    elif isinstance(extract,list):
                        for infoL in extract: 
                            lang,prog,opts=decodeExtract(infoL)
                            datasets[title]['extract']['language']=lang
                            datasets[title]['extract']['program']=prog
                            datasets[title]['extract']['options']=opts
                    else:
                        print("UNK",type(info))
                if 'transform' in info:
                    
                    transform=info['transform']
                    if 'file' in transform:
                       datasets[title]['transform']['program']=transform['file']
                    else:
                       datasets[title]['transform']['program']=''
                else:
                    datasets[title]['transform']['program']=''

                if 'load' in info:
                    load=info['load']
                    if 'file' in load:
                       datasets[title]['load']['sij']=load['file']
                    else:
                       datasets[title]['load']['sij']=''

                    if 'type' in load:
                       datasets[title]['load']['type']=load['type']
                    else:
                       datasets[title]['load']['type']=''
                    if 'format' in load:
                       datasets[title]['load']['format']=load['format']
                    else:
                       datasets[title]['load']['format']=''
                        
            else:
                print("No Title",file)
    return datasets

datasets = processRun_etls()

No Title /home/joe/bic_etl/general/example/run_etl.json

In [44]:
datasets

{'CIM Catalog Download': {'extract': {'language': 'node',
   'program': 'general/scripts/request_url.js',
   'options': {'-u': 'https://data.colorado.gov/api/views/e7nm-tn2z/rows.csv?accessType=DOWNLOAD',
    '-f': 'catalog/data_source/inventory-$(date +%F).csv'}},
  'group': 'catalog',
  'transform': {'program': ''},
  'load': {}},
 'Housing Inventory: New Listing Count in Colorado': {'extract': {'language': '',
   'program': '',
   'options': {}},
  'group': 'fred',
  'transform': {'program': 'fred/scripts/fred_new_listing_extract_transform.py'},
  'load': {'sij': 'fred_housing_inventory.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Average Weekly & Hourly Earnings and Work Hours Across Major Industry Sectors in Colorado': {'extract': {'language': 'py',
   'program': 'bls/scripts/blsExtract.py',
   'options': {'-p': 'bls',
    '-f': 'sm.data.6.Colorado',
    '-o': 'data_source/sm.data.6.Colorado.tsv',
    '-u': 'https://download.bls.gov/pub/time.series/sm',
    '-r': 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8 application/signed-exchange;v=b3;q=0.7\tAccept-Encoding: gzip, deflate, br, zstd\tAccept-Language: en-US,en;q=0.9\tConnection: keep-alive\tSec-Fetch-Mode: navigate\tUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36'}},
  'group': 'bls',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'sm.sij', 'type': 'datasync', 'format': 'csv'}},
 'Monthly Consumer Price Index Data for Denver-Aurora-Lakewood': {'extract': {'language': 'py',
   'program': 'bls/scripts/blsExtract.py',
   'options': {'-p': 'bls',
    '-f': 'cu.data.0.Current',
    '-o': 'data_source/cu.data.0.Current.tsv',
    '-u': 'https://download.bls.gov/pub/time.series/cu',
    '-r': 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8 application/signed-exchange;v=b3;q=0.7\tAccept-Encoding: gzip, deflate, br, zstd\tAccept-Language: en-US,en;q=0.9\tConnection: keep-alive\tSec-Fetch-Mode: navigate\tUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36'}},
  'group': 'bls',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'cu.monthly.sij', 'type': 'datasync', 'format': 'csv'}},
 'Durable Medical Equipment Suppliers in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'DME/CurrentDMESuppliers-CIM.txt',
    '-o': 'cdos/health/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/health',
  'transform': {'program': 'scripts/dme_suppliers.js'},
  'load': {'sij': 'dme_suppliers.sij', 'type': 'datasync', 'format': 'csv'}},
 'Current Notaries in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'notary/CurrentCommissionedNotaries.txt',
    '-o': 'cdos/government/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/government',
  'transform': {'program': 'scripts/current_notaries.js'},
  'load': {'sij': 'current_notaries.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Uniform Commercial Code (UCC) Collateral Information in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'UCC/ucccoll2.txt',
    '-o': 'cdos/business/ucc/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/ucc',
  'transform': {'program': 'scripts/ucccoll.js'},
  'load': {'sij': 'ucccoll.sij', 'type': 'datasync', 'format': 'csv'}},
 'Uniform Commercial Code (UCC) Debtor Information in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'UCC/uccdbtr.txt',
    '-o': 'cdos/business/ucc/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/ucc',
  'transform': {'program': 'scripts/uccdbtr.js'},
  'load': {'sij': 'uccdbtr.sij', 'type': 'datasync', 'format': 'csv'}},
 'Uniform Commercial Code (UCC) Filing Information in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'UCC/uccstmt.txt',
    '-o': 'cdos/business/ucc/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/ucc',
  'transform': {'program': 'scripts/uccstmt.js'},
  'load': {'sij': 'uccstmt.sij', 'type': 'datasync', 'format': 'csv'}},
 'Secured Party Information in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'UCC/uccsecr.txt',
    '-o': 'cdos/business/ucc/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/ucc',
  'transform': {'program': 'scripts/uccsecr.js'},
  'load': {'sij': 'uccsecr.sij', 'type': 'datasync', 'format': 'csv'}},
 'Business Entities in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'business/corpmstr.txt',
    '-o': 'cdos/business/business/data_source/',
    '-a': '.tsv',
    '-n': 'business_entities.tsv'}},
  'group': 'cdos/business/business',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'business_entities.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Business Entity Transaction History': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'business/corphist-2.txt',
    '-o': 'cdos/business/business/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/business',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'corporate_history.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Trademarks for Businesses in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'business/trademarks.txt',
    '-o': 'cdos/business/business/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/business',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'trademarks.sij', 'type': 'datasync', 'format': 'csv'}},
 'Trade Names for Businesses in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'business/tradenames.txt',
    '-o': 'cdos/business/business/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/business',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'tradenames.sij', 'type': 'datasync', 'format': 'csv'}},
 'Master List in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'UCC/UCCMstrLB1.txt',
    '-o': 'cdos/business/business/data_source/',
    '-n': 'masterlist.tsv'}},
  'group': 'cdos/business/business',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'masterlist.sij', 'type': 'datasync', 'format': 'csv'}},
 'Campaign Reports for Solicitation Notices to Charities in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/sn_cmpgn_rpts.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'sn_cmpgn_rpts.sij', 'type': 'datasync', 'format': 'csv'}},
 'Charitable Organizations’ Offices in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/offices.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'offices.sij', 'type': 'datasync', 'format': 'csv'}},
 'Charitable Purpose of the Charity in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/purpose.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'purpose.sij', 'type': 'datasync', 'format': 'csv'}},
 'Charitable Solicitation Call Center Locations in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/sol_ntcs_locs.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'sol_ntcs_locs.sij', 'type': 'datasync', 'format': 'csv'}},
 'Charities Solicitation Type by Solicitation in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/sol_typ_sol_ntcs.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'sol_typ_sol_ntcs.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Charity Extension Requests': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/char_orgs_ext.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'char_orgs_ext.sij', 'type': 'datasync', 'format': 'csv'}},
 'Communication Methods Used in Solicitation Campaigns in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/sol_typ_entity.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'sol_typ_entity.sij', 'type': 'datasync', 'format': 'csv'}},
 'Federal Tax-Exempt Subsection Codes in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/tax_exempt_cds.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'tax_exempt_cds.sij', 'type': 'datasync', 'format': 'csv'}},
 'Other Names a Registered Entity Uses to Solicit Contributions in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/doing_bus_as.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'doing_bus_as.sij', 'type': 'datasync', 'format': 'csv'}},
 'Other State Solicitation of Charities’ Registrants in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/states.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'states.sij', 'type': 'datasync', 'format': 'csv'}},
 'Paid Solicitors Disclosed on Charity Registration Forms in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/char_orgs_sol.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'char_orgs_sol.sij', 'type': 'datasync', 'format': 'csv'}},
 'Paid Solicitor Solicitation Notices in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/sol_ntcs.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'sol_ntcs.sij', 'type': 'datasync', 'format': 'csv'}},
 'Persons Associated with Charitable Organizations, Paid Solicitors, and Professional Fundraising Consultants in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/persons_entity.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'persons_entity.sij', 'type': 'datasync', 'format': 'csv'}},
 'Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/reg_finan.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'reg_finan.sij', 'type': 'datasync', 'format': 'csv'}},
 'Solicitation Campaign Supervisors Listed on Solicitation Notices in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/persons_sol_ntcs.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'char_solicitations_campaign_supervisors.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'State Lobbyist Officials in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/state_lobbyist_officials.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'state_lobbyist_officials.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'State Lobbyist Directory in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/state_lobbyist_directory.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'state_lobbyist_directory.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'State Lobbyists Funds and Hours in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/state_lobbyist_funds_hours.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'state_lobbyist_funds_hours.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'State Lobbyist Bills in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/state_lobbyist_bills.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'state_lobbyist_bills.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Professional Lobbyist Subcontractors in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/prof_subcontractors.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'prof_subcontractors.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Professional Lobbyist Directory in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/prof_lobbyist_directory.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'prof_lobbyist_directory.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Professional Lobbyist Income in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/prof_income.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'prof_income.sij', 'type': 'datasync', 'format': 'csv'}},
 'Professional Lobbyist Expenditures in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/prof_expenditures.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'prof_expenditures.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Professional Lobbyist Disclosure Report Summary in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/prof_disclosure_report_summary.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'prof_disclosure_report_summary.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Professional Lobbyist Clients in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/prof_clients.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'prof_clients.sij', 'type': 'datasync', 'format': 'csv'}},
 'Professional Lobbyist Bills in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/prof_bills.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'prof_bills.sij', 'type': 'datasync', 'format': 'csv'}},
 'Enrollment Demographics for Post-Secondary Graduates in Colorado': {'extract': {'language': '',
   'program': '',
   'options': {}},
  'group': 'cdhe',
  'transform': {'program': 'enrollment.js'},
  'load': {'sij': 'enrollment.sij', 'type': 'datasync', 'format': 'csv'}},
 'Post-Secondary Financial Aid Demographics in Colorado': {'extract': {'language': '',
   'program': '',
   'options': {}},
  'group': 'cdhe',
  'transform': {'program': 'financial_aid.js'},
  'load': {'sij': 'financial_aid.sij', 'type': 'datasync', 'format': 'csv'}},
 'DPA Tops Data': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'TOPS/',
    '-o': 'dpa/data_source/',
    '-n': 'tops_extract.xlsx',
    '-u': 'bic_cim_svc',
    '-p': 'Denver2020!',
    '-h': 'prod.moveit.state.co.us',
    '-k': 'bic_dpa_priv_key.ppk',
    '-': '-r'}},
  'group': 'dpa',
  'transform': {'program': 'scripts/dpa_transform.py'},
  'load': {'sij': 'dpa_exp_rev.sij', 'type': 'datasync', 'format': 'csv'}},
 'Restaurant Inspections in Tri-County Colorado': {'extract': {'language': 'node',
   'program': 'cdos/general/scripts/sftp_extract.js',
   'options': {'-f': 'TriCounty/TCHD_FDA_Food_Inspections.xlsx',
    '-o': 'tchd/data_source/',
    '-a': '.xlsx'}},
  'group': 'tchd',
  'transform': {'program': 'restaurant_inspections.js'},
  'load': {'sij': 'scripts/datasync/restaurant_inspections.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Restaurant Inspections in Boulder County': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'VendorInterfaces/Boulder_County/In/Resturant_Inspection.csv',
    '-o': 'boulder/data_source/',
    '-h': 'prod.moveit.state.co.us',
    '-k': 'dora_bic_transfer',
    '-u': 'bic_cim_svc',
    '-n': 'restaurant_inspections.csv'}},
  'group': 'boulder',
  'transform': {'program': ''},
  'load': {'sij': 'scripts/datasync/boulder_restaurant_inspections.sij',
   'type': 'datasync',
   'format': 'csv'}},

### Get web/ftp Addresses

In [45]:
def getUrlAddresses(datasets):
    hist={}
    addresses={}
    options={}
    specOpts={}
    specOpts["general/scripts/request_url.js"]={}
    specOpts["general/scripts/request_url.js"]["-u"]="-f"
    
    specOpts["general/scripts/sftp_extract.js"]={}
    specOpts["general/scripts/sftp_extract.js"]["-h"]="-f"
    specOpts["general/scripts/sftp_extract.js"]["none"]="-f"
    
    specOpts["cdos/general/scripts/sftp_extract.js"]={}
    specOpts["cdos/general/scripts/sftp_extract.js"]["none"]="-f"
    
    lookupNotFound = {
    'bea/scripts/bea_msa_api_reader.py':['https://apps.bea.gov/api/data'],
    'denver/scripts/get_data.py':['https://www.denvergov.org/content/dam/denvergov/Portals/covid19/documents/Denver-Approved-Patio-Expansion-List.xlsx'],
    'scripts/extract_liquor_files.py':'https://sbg.colorado.gov/liquor-license-lists',
    'county_sales_extract.py':['https://docs.google.com/spreadsheets/d/1br_cwfHy24d2R2bcXacb2KarOIBKGrbR/export?format=csv'],
    'scripts/county_salestax_extract.py':['https://docs.google.com/spreadsheets/d/1EhlDIrXjJdmg_ob2eMFeN5xtyvTq2jtr/export?format=csv'],
    'scripts/tax_fee_extract.py':['https://docs.google.com/spreadsheets/d/1e8hnG64Vkg9ffgkNpKQ1kzPsXNbGjG2X/export?format=csv'],
    'scripts/state_mar_sales_extract.py':['https://docs.google.com/spreadsheets/d/1wE7Z_1q2zxL7-kP0AqlUvL731U3Aui1l/export?format=csv'],
    'scripts/city_extract.py':['https://docs.google.com/spreadsheets/d/1wo4WKzvlfdw47_3841jD2RUibbDwos3L/export?format=csv','https://docs.google.com/spreadsheets/d/1WI2jvRCzBqYFIPA2vsUmCjHedKCQD911/export?format=csv'],
    'scripts/county_extract.py':['https://docs.google.com/spreadsheets/d/1irLP8K7jREdDgIiamgZ2MiTbkeMX5lrM/export?format=csv'],
    'scripts/extract_scripts/citybyindustry_extract.py':['https://docs.google.com/spreadsheets/d/1ZKc0olDlChHyRiLlxL3ECxKqBYtyaUaB/export?format=csv','https://docs.google.com/spreadsheets/d/1E6VqKiPnUD3LMnrSBy1aEYSc4QsU6Y9v/export?format=csv'],
    'scripts/extract_scripts/industry_extract.py':['https://docs.google.com/spreadsheets/d/{1WANzZQFE57J73daXvo1xu4mITy-1DmuP/export?format=csv','https://docs.google.com/spreadsheets/d/1cmTJ4ZRAjBFfevT0hyCatUXDIzIG393I/export?format=csv'],
    'scripts/extract_scripts/countybyindustry_extract.py':['https://docs.google.com/spreadsheets/d/1CI66-qv0ooK93asc21VyV-tJiYSc2J3c/export?format=csv','https://docs.google.com/spreadsheets/d/1kybUGf02krqwyl8yBPHnTbn0iQT4Cnnz/export?format=csv'],
    'scripts/extract_liquor_files.py':['https://sbg.colorado.gov/liquor-license-lists']
    }
    
    
    noProg={}
    for title,dct in datasets.items():
        if 'group' in dct:
            group=dct['group']
        else:
            group=""
        if 'extract' in dct:
            if 'language' in dct['extract']:
                lang=dct['extract']['language']
                prog=dct['extract']['program']
                if lang not in hist:
                    hist[lang]={}
                if prog not in hist[lang]:
                    hist[lang][prog]=0
                hist[lang][prog]+=1
    
                if prog not in addresses:
                    addresses[prog]={}
                if 'options' in dct['extract']:
                    if prog in specOpts:
                        o=list(specOpts[prog].keys())[0]
                        fOpt=specOpts[prog][o]
                        ff = dct['extract']['options'][fOpt]  
                        if o in dct['extract']['options']:
                            a=dct['extract']['options'][o]
                        else:
                            if prog == "general/scripts/sftp_extract.js":
                              a="ftps.sos.state.co.us"
                            else:
                              a=""
                    else:
                        ff=""
                        o=""
                        a=""
                        if prog in lookupNotFound:
                            a = lookupNotFound[prog]
                        else:
                            if prog not in noProg:
                                noProg[prog]={}
                            noProg[prog]['group']=group
                        
                    if isinstance(a,str):
                        b=[]
                        b.append(a)
                    else:
                        b=a
                    for a in b: 
                        if a not in addresses[prog]:
                            addresses[prog][a]={}
                        if ff not in addresses[prog][a]:
                           addresses[prog][a][ff]={}
                        
                        if title not in addresses[prog][a][ff]:
                           addresses[prog][a][ff][title]={}
                            
                           addresses[prog][a][ff][title]['count']=0
                           addresses[prog][a][ff][title]['group']=group
                        
                        
                    addresses[prog][a][ff][title]['count']+=1
##  Create a DataFrame
    programs=[]
    address=[]
    files=[]
    counts=[]
    titles=[]
    groups=[]
    for p,dct in addresses.items():
        for o,dct2 in dct.items():   
            for f,dct3 in dct2.items():
                for t,dct4 in dct3.items():
                    
                    programs.append(p)
                    address.append(o)
                    files.append(f)
                    counts.append(dct4['count'])
                    groups.append(dct4['group'])
                    
                    titles.append(t)
    df = pd.DataFrame({
        "Title":titles,
        "Group":groups,
        "Program":programs,
        "Address":address,
        "File":files,
        "Count":counts})
    return addresses,df
addresses,df = getUrlAddresses(datasets)

In [46]:
datasets

{'CIM Catalog Download': {'extract': {'language': 'node',
   'program': 'general/scripts/request_url.js',
   'options': {'-u': 'https://data.colorado.gov/api/views/e7nm-tn2z/rows.csv?accessType=DOWNLOAD',
    '-f': 'catalog/data_source/inventory-$(date +%F).csv'}},
  'group': 'catalog',
  'transform': {'program': ''},
  'load': {}},
 'Housing Inventory: New Listing Count in Colorado': {'extract': {'language': '',
   'program': '',
   'options': {}},
  'group': 'fred',
  'transform': {'program': 'fred/scripts/fred_new_listing_extract_transform.py'},
  'load': {'sij': 'fred_housing_inventory.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Average Weekly & Hourly Earnings and Work Hours Across Major Industry Sectors in Colorado': {'extract': {'language': 'py',
   'program': 'bls/scripts/blsExtract.py',
   'options': {'-p': 'bls',
    '-f': 'sm.data.6.Colorado',
    '-o': 'data_source/sm.data.6.Colorado.tsv',
    '-u': 'https://download.bls.gov/pub/time.series/sm',
    '-r': 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8 application/signed-exchange;v=b3;q=0.7\tAccept-Encoding: gzip, deflate, br, zstd\tAccept-Language: en-US,en;q=0.9\tConnection: keep-alive\tSec-Fetch-Mode: navigate\tUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36'}},
  'group': 'bls',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'sm.sij', 'type': 'datasync', 'format': 'csv'}},
 'Monthly Consumer Price Index Data for Denver-Aurora-Lakewood': {'extract': {'language': 'py',
   'program': 'bls/scripts/blsExtract.py',
   'options': {'-p': 'bls',
    '-f': 'cu.data.0.Current',
    '-o': 'data_source/cu.data.0.Current.tsv',
    '-u': 'https://download.bls.gov/pub/time.series/cu',
    '-r': 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8 application/signed-exchange;v=b3;q=0.7\tAccept-Encoding: gzip, deflate, br, zstd\tAccept-Language: en-US,en;q=0.9\tConnection: keep-alive\tSec-Fetch-Mode: navigate\tUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36'}},
  'group': 'bls',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'cu.monthly.sij', 'type': 'datasync', 'format': 'csv'}},
 'Durable Medical Equipment Suppliers in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'DME/CurrentDMESuppliers-CIM.txt',
    '-o': 'cdos/health/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/health',
  'transform': {'program': 'scripts/dme_suppliers.js'},
  'load': {'sij': 'dme_suppliers.sij', 'type': 'datasync', 'format': 'csv'}},
 'Current Notaries in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'notary/CurrentCommissionedNotaries.txt',
    '-o': 'cdos/government/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/government',
  'transform': {'program': 'scripts/current_notaries.js'},
  'load': {'sij': 'current_notaries.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Uniform Commercial Code (UCC) Collateral Information in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'UCC/ucccoll2.txt',
    '-o': 'cdos/business/ucc/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/ucc',
  'transform': {'program': 'scripts/ucccoll.js'},
  'load': {'sij': 'ucccoll.sij', 'type': 'datasync', 'format': 'csv'}},
 'Uniform Commercial Code (UCC) Debtor Information in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'UCC/uccdbtr.txt',
    '-o': 'cdos/business/ucc/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/ucc',
  'transform': {'program': 'scripts/uccdbtr.js'},
  'load': {'sij': 'uccdbtr.sij', 'type': 'datasync', 'format': 'csv'}},
 'Uniform Commercial Code (UCC) Filing Information in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'UCC/uccstmt.txt',
    '-o': 'cdos/business/ucc/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/ucc',
  'transform': {'program': 'scripts/uccstmt.js'},
  'load': {'sij': 'uccstmt.sij', 'type': 'datasync', 'format': 'csv'}},
 'Secured Party Information in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'UCC/uccsecr.txt',
    '-o': 'cdos/business/ucc/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/ucc',
  'transform': {'program': 'scripts/uccsecr.js'},
  'load': {'sij': 'uccsecr.sij', 'type': 'datasync', 'format': 'csv'}},
 'Business Entities in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'business/corpmstr.txt',
    '-o': 'cdos/business/business/data_source/',
    '-a': '.tsv',
    '-n': 'business_entities.tsv'}},
  'group': 'cdos/business/business',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'business_entities.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Business Entity Transaction History': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'business/corphist-2.txt',
    '-o': 'cdos/business/business/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/business',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'corporate_history.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Trademarks for Businesses in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'business/trademarks.txt',
    '-o': 'cdos/business/business/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/business',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'trademarks.sij', 'type': 'datasync', 'format': 'csv'}},
 'Trade Names for Businesses in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'business/tradenames.txt',
    '-o': 'cdos/business/business/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/business',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'tradenames.sij', 'type': 'datasync', 'format': 'csv'}},
 'Master List in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'UCC/UCCMstrLB1.txt',
    '-o': 'cdos/business/business/data_source/',
    '-n': 'masterlist.tsv'}},
  'group': 'cdos/business/business',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'masterlist.sij', 'type': 'datasync', 'format': 'csv'}},
 'Campaign Reports for Solicitation Notices to Charities in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/sn_cmpgn_rpts.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'sn_cmpgn_rpts.sij', 'type': 'datasync', 'format': 'csv'}},
 'Charitable Organizations’ Offices in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/offices.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'offices.sij', 'type': 'datasync', 'format': 'csv'}},
 'Charitable Purpose of the Charity in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/purpose.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'purpose.sij', 'type': 'datasync', 'format': 'csv'}},
 'Charitable Solicitation Call Center Locations in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/sol_ntcs_locs.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'sol_ntcs_locs.sij', 'type': 'datasync', 'format': 'csv'}},
 'Charities Solicitation Type by Solicitation in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/sol_typ_sol_ntcs.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'sol_typ_sol_ntcs.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Charity Extension Requests': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/char_orgs_ext.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'char_orgs_ext.sij', 'type': 'datasync', 'format': 'csv'}},
 'Communication Methods Used in Solicitation Campaigns in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/sol_typ_entity.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'sol_typ_entity.sij', 'type': 'datasync', 'format': 'csv'}},
 'Federal Tax-Exempt Subsection Codes in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/tax_exempt_cds.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'tax_exempt_cds.sij', 'type': 'datasync', 'format': 'csv'}},
 'Other Names a Registered Entity Uses to Solicit Contributions in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/doing_bus_as.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'doing_bus_as.sij', 'type': 'datasync', 'format': 'csv'}},
 'Other State Solicitation of Charities’ Registrants in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/states.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'states.sij', 'type': 'datasync', 'format': 'csv'}},
 'Paid Solicitors Disclosed on Charity Registration Forms in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/char_orgs_sol.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'char_orgs_sol.sij', 'type': 'datasync', 'format': 'csv'}},
 'Paid Solicitor Solicitation Notices in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/sol_ntcs.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'sol_ntcs.sij', 'type': 'datasync', 'format': 'csv'}},
 'Persons Associated with Charitable Organizations, Paid Solicitors, and Professional Fundraising Consultants in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/persons_entity.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'persons_entity.sij', 'type': 'datasync', 'format': 'csv'}},
 'Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/reg_finan.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'reg_finan.sij', 'type': 'datasync', 'format': 'csv'}},
 'Solicitation Campaign Supervisors Listed on Solicitation Notices in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'charity/persons_sol_ntcs.txt',
    '-o': 'cdos/business/nonprofit/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/business/nonprofit',
  'transform': {'program': 'general/scripts/transform.py'},
  'load': {'sij': 'char_solicitations_campaign_supervisors.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'State Lobbyist Officials in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/state_lobbyist_officials.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'state_lobbyist_officials.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'State Lobbyist Directory in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/state_lobbyist_directory.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'state_lobbyist_directory.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'State Lobbyists Funds and Hours in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/state_lobbyist_funds_hours.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'state_lobbyist_funds_hours.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'State Lobbyist Bills in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/state_lobbyist_bills.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'state_lobbyist_bills.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Professional Lobbyist Subcontractors in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/prof_subcontractors.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'prof_subcontractors.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Professional Lobbyist Directory in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/prof_lobbyist_directory.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'prof_lobbyist_directory.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Professional Lobbyist Income in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/prof_income.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'prof_income.sij', 'type': 'datasync', 'format': 'csv'}},
 'Professional Lobbyist Expenditures in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/prof_expenditures.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'prof_expenditures.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Professional Lobbyist Disclosure Report Summary in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/prof_disclosure_report_summary.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'prof_disclosure_report_summary.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Professional Lobbyist Clients in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/prof_clients.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'prof_clients.sij', 'type': 'datasync', 'format': 'csv'}},
 'Professional Lobbyist Bills in Colorado': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'lobby/prof_bills.txt',
    '-o': 'cdos/lobbyist/data_source/',
    '-a': '.tsv'}},
  'group': 'cdos/lobbyist',
  'transform': {'program': ''},
  'load': {'sij': 'prof_bills.sij', 'type': 'datasync', 'format': 'csv'}},
 'Enrollment Demographics for Post-Secondary Graduates in Colorado': {'extract': {'language': '',
   'program': '',
   'options': {}},
  'group': 'cdhe',
  'transform': {'program': 'enrollment.js'},
  'load': {'sij': 'enrollment.sij', 'type': 'datasync', 'format': 'csv'}},
 'Post-Secondary Financial Aid Demographics in Colorado': {'extract': {'language': '',
   'program': '',
   'options': {}},
  'group': 'cdhe',
  'transform': {'program': 'financial_aid.js'},
  'load': {'sij': 'financial_aid.sij', 'type': 'datasync', 'format': 'csv'}},
 'DPA Tops Data': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'TOPS/',
    '-o': 'dpa/data_source/',
    '-n': 'tops_extract.xlsx',
    '-u': 'bic_cim_svc',
    '-p': 'Denver2020!',
    '-h': 'prod.moveit.state.co.us',
    '-k': 'bic_dpa_priv_key.ppk',
    '-': '-r'}},
  'group': 'dpa',
  'transform': {'program': 'scripts/dpa_transform.py'},
  'load': {'sij': 'dpa_exp_rev.sij', 'type': 'datasync', 'format': 'csv'}},
 'Restaurant Inspections in Tri-County Colorado': {'extract': {'language': 'node',
   'program': 'cdos/general/scripts/sftp_extract.js',
   'options': {'-f': 'TriCounty/TCHD_FDA_Food_Inspections.xlsx',
    '-o': 'tchd/data_source/',
    '-a': '.xlsx'}},
  'group': 'tchd',
  'transform': {'program': 'restaurant_inspections.js'},
  'load': {'sij': 'scripts/datasync/restaurant_inspections.sij',
   'type': 'datasync',
   'format': 'csv'}},
 'Restaurant Inspections in Boulder County': {'extract': {'language': 'node',
   'program': 'general/scripts/sftp_extract.js',
   'options': {'-f': 'VendorInterfaces/Boulder_County/In/Resturant_Inspection.csv',
    '-o': 'boulder/data_source/',
    '-h': 'prod.moveit.state.co.us',
    '-k': 'dora_bic_transfer',
    '-u': 'bic_cim_svc',
    '-n': 'restaurant_inspections.csv'}},
  'group': 'boulder',
  'transform': {'program': ''},
  'load': {'sij': 'scripts/datasync/boulder_restaurant_inspections.sij',
   'type': 'datasync',
   'format': 'csv'}},

In [47]:
def mapetload(row):
    title=row['Title']
    eprog=""
    elang=""
    tprog=""
    ltype=""
    lform=""
    sij=""
    if title in datasets:
        dct=datasets[title]
 
        if 'extract' in dct:
            if 'language' in dct['extract']:
                elang=dct['extract']['language']
                eprog= dct['extract']['program']
    
        if 'transform' in dct:
            if 'program' in dct['transform']:
                tprog=dct['transform']['program']

        if 'load' in dct:
            if 'sij' in dct['load']:
                sij=dct['load']['sij']
            if 'format' in dct['load']:
                lform=dct['load']['format']
            if 'type' in dct['load']:
                ltype=dct['load']['type']
                
        row['transform program']=tprog
        row['load type']=ltype
        row['load format']=lform
        row['load sij']=sij
    return row

df = df.apply(mapetload,axis=1)

In [ ]:
df.head(30)

## CRON

In [9]:
def getCronInfo(cron_file_path):
    fin=open(cron_file_path)
    lines=fin.readlines()
    crons={}
    for line in lines:
        if line[0:1] != "#" and line[0:1] != " " and len(line) > 2:
            line=line.strip()
            spl=line.split()
            crn=' '.join(spl[:5])
            rest = ' '.join(spl[5:])
            
            crons[rest]=crn
    return crons

def decodeCron(cron_file):
    hist={}
    cronGroups={}
    crons=getCronInfo(cron_file)
    for inf,crn in crons.items():
    
        desc = get_description(crn)
        print(desc)
        spl=inf.split()
        lang=spl[0]
        prg=spl[1]
        indxP=inf.find("-p")
        if indxP > -1:
           tmp=inf[indxP+2:].lstrip()
           end=tmp.find(" ")
           grp=tmp[:end]
        else:
            grp=""
    
        indxT=inf.find("-t")
        if indxT > -1:
           tmp=inf[indxT+2:].lstrip()
           start = tmp.find('"')
           end=tmp[start+1:].find('"')
           titl=tmp[start+1:end+1]
        else:
            titl="ALL"
        if grp not in cronGroups:
            cronGroups[grp]={}
        cronGroups[grp][titl]=desc
        print(grp,titl)     
        if lang not in hist:
            hist[lang]={}
        if prg not in hist[lang]:
            hist[lang][prg]=0
        hist[lang][prg]+=1
    return cronGroups
cron_file = '/home/joe/bic_etl/general/cron/cron_file'    
cronGroups=decodeCron(cron_file)

At 02:50 AM
 ALL
At 02:58 AM

At 05:00 AM
 ALL
At 04:00 AM, on day 15 of the month
bls/sm ALL
At 03:10 AM
boulder Septic Systems in Boulder County Colorado
At 04:00 AM
catalog ALL
At 06:05 AM, only on Friday
cdos/business/nonprofit ALL
At 05:05 AM
cdos/business/nonprofit Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado
At 05:10 AM
cdos/business/business Business Entities in Colorado
At 08:00 AM
cdos/business/business Business Entity Transaction History
At 04:00 AM, only on Tuesday
cdos/health ALL
At 04:15 AM
cdos/lobbyist ALL
At 04:30 AM, only on Tuesday
cdos/government ALL
At 05:30 AM, on day 4 of the month
cdos/business/business Master List in Colorado
At 04:00 AM
cdos/business/business Trade Names for Businesses in Colorado
At 04:00 AM
cdos/business/business Trademarks for Businesses in Colorado
At 03:00 AM
cdos/business/ucc ALL
At 04:10 AM, on day 4 of the month
cdot/transportation_road_attributes ALL
At 04:30 AM, on day 4 of the month
cdot/transportation_infrastructure ALL
At 04:50 AM, on day 4 of the month
cdot/natural_resources ALL
At 08:45 AM, only on Tuesday
cdot/tops ALL
At 04:00 AM, on day 4 of the month
dola/boundaries ALL
At 05:20 AM, on day 4 of the month
dola/special_districts ALL
At 04:30 AM, on day 1 of the month
dola/demographics ALL
At 04:20 AM, on day 1, 8, 15, and 22 of the month
cdor/revenue_marijuana ALL
At 04:30 AM, on day 10 of the month
cdor/retail_reports ALL
At 04:40 AM, on day 6 of the month
cdor/regulations_liquor ALL
At 04:00 AM, only on Tuesday
ceo/useia Gasoline Prices in Colorado
At 05:00 AM, only on Thursday
ceo/useia Natural Gas Prices in Colorado
At 03:30 AM, on day 7 of the month
fred ALL
At 02:47 PM
 ALL

In [10]:
cronGroups

{'': {'ALL': 'At 02:47 PM', '': 'At 02:58 AM'},
 'bls/sm': {'ALL': 'At 04:00 AM, on day 15 of the month'},
 'boulder': {'Septic Systems in Boulder County Colorado': 'At 03:10 AM'},
 'catalog': {'ALL': 'At 04:00 AM'},
 'cdos/business/nonprofit': {'ALL': 'At 06:05 AM, only on Friday',
  'Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado': 'At 05:05 AM'},
 'cdos/business/business': {'Business Entities in Colorado': 'At 05:10 AM',
  'Business Entity Transaction History': 'At 08:00 AM',
  'Master List in Colorado': 'At 05:30 AM, on day 4 of the month',
  'Trade Names for Businesses in Colorado': 'At 04:00 AM',
  'Trademarks for Businesses in Colorado': 'At 04:00 AM'},
 'cdos/health': {'ALL': 'At 04:00 AM, only on Tuesday'},
 'cdos/lobbyist': {'ALL': 'At 04:15 AM'},
 'cdos/government': {'ALL': 'At 04:30 AM, only on Tuesday'},
 'cdos/business/ucc': {'ALL': 'At 03:00 AM'},
 'cdot/transportation_road_attributes': {'ALL': 'At 04:10 AM, on day 4 of the month'},
 'cdot/transportation_infrastructure': {'ALL': 'At 04:30 AM, on day 4 of the month'},
 'cdot/natural_resources': {'ALL': 'At 04:50 AM, on day 4 of the month'},
 'cdot/tops': {'ALL': 'At 08:45 AM, only on Tuesday'},
 'dola/boundaries': {'ALL': 'At 04:00 AM, on day 4 of the month'},
 'dola/special_districts': {'ALL': 'At 05:20 AM, on day 4 of the month'},
 'dola/demographics': {'ALL': 'At 04:30 AM, on day 1 of the month'},
 'cdor/revenue_marijuana': {'ALL': 'At 04:20 AM, on day 1, 8, 15, and 22 of the month'},
 'cdor/retail_reports': {'ALL': 'At 04:30 AM, on day 10 of the month'},
 'cdor/regulations_liquor': {'ALL': 'At 04:40 AM, on day 6 of the month'},
 'ceo/useia': {'Gasoline Prices in Colorado': 'At 04:00 AM, only on Tuesday',
  'Natural Gas Prices in Colorado': 'At 05:00 AM, only on Thursday'},
 'fred': {'ALL': 'At 03:30 AM, on day 7 of the month'}}

## Combine Cron and Dataset Info

In [79]:
def addCronInfo(row):
    title=row['Title']
    group=row['Group']
    if group in cronGroups:
        dct=cronGroups[group]
        for how,crn in dct.items(): 
            if how == "ALL":
               cron=crn
            elif title in cronGroups[group]:
               cron=cronGroups[group][title]
            else:
                cron="Unknown"

    else:
        cron="No Group Found"
    return cron

df["Cron"] = df.apply(addCronInfo,axis=1)

In [ ]:
tmp=None

for prg,cnt in df['Program'].value_counts().to_dict().items():
    if tmp is not None:
       tmp=pd.concat([tmp,df.loc[df["Program"] == prg]])
    else:
       tmp=df.loc[df["Program"] == prg]
        
    display(prg)
    display(tmp[["Title","Group","Address"]].head(100))

In [19]:
df.columns

Index(['Title', 'Group', 'Program', 'Address', 'File', 'Count'], dtype='object')

In [52]:
tmp.to_csv("tilesInfo.csv",index=False)

In [18]:
df['Address'].value_counts()

Address
ftps.sos.state.co.us                                                                                                                                                                        46
                                                                                                                                                                                            17
prod.moveit.state.co.us                                                                                                                                                                      4
http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/Mileposts.zip                                                                                                              2
sftp.micropact.com                                                                                                                                                                           2
https://data.colorado.gov/api/views/e7nm-tn2z/rows.csv?accessType=DOWNLOAD                                                                                                                   1
http://coloradosos.gov/pubs/UCC/downloadFiles/UCCMstrLB1.txt                                                                                                                                 1
http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/Routes.zip                                                                                                                 1
https://dtdapps.coloradodot.info/arcgis/rest/services/MapView/Transportation_MapView_js/MapServer/17/query?where=objectid+%3D+objectid&outFields=ROUTE%2COBJECTID%2CNAME%2CSHAPE&f=pjson     1
http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/MajorRoads.zip                                                                                                             1
http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/LocalRoads.zip                                                                                                             1
http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/highways.zip                                                                                                               1
http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/lakes.zip                                                                                                                  1
http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/streams.zip                                                                                                                1
http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/airports.zip                                                                                                               1
http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/cities.zip                                                                                                                 1
https://storage.googleapis.com/co-publicdata/dlfire.zip                                                                                                                                      1
https://storage.googleapis.com/co-publicdata/dlhospital.zip                                                                                                                                  1
https://storage.googleapis.com/co-publicdata/dlwatersan.zip                                                                                                                                  1
https://storage.googleapis.com/co-publicdata/dllibrary.zip                                                                                                                                   1
http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/counties.zip                                                                                                               1
http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/railroads.zip                                                                                                              1
https://storage.googleapis.com/co-publicdata/dlmetro.zip                                                                                                                                     1
https://storage.googleapis.com/co-publicdata/dlpark.zip                                                                                                                                      1
https://storage.googleapis.com/co-publicdata/dlall.zip                                                                                                                                       1
https://storage.googleapis.com/co-publicdata/dlcemetery.zip                                                                                                                                  1
https://storage.googleapis.com/co-publicdata/dlsoil.zip                                                                                                                                      1
https://storage.googleapis.com/co-publicdata/dlschool.zip                                                                                                                                    1
https://storage.googleapis.com/co-publicdata/Annexations.zip                                                                                                                                 1
https://storage.googleapis.com/co-publicdata/MuniBounds.zip                                                                                                                                  1
https://storage.googleapis.com/co-publicdata/sya-county.csv                                                                                                                                  1
https://storage.googleapis.com/co-publicdata/race-estimates-county.csv                                                                                                                       1
https://data.colorado.gov/api/views/htyp-tqzh/rows.csv?accessType=DOWNLOAD                                                                                                                   1
https://data.colorado.gov/api/views/kapc-ib6e/rows.csv?accessType=DOWNLOAD                                                                                                                   1
https://data.colorado.gov/api/views/d6t8-xish/rows.csv?accessType=DOWNLOAD                                                                                                                   1
https://storage.googleapis.com/co-publicdata/race-forecast-county.csv                                                                                                                        1
https://www.eia.gov/dnav/ng/xls/NG_PRI_SUM_DCU_SCO_M.xls                                                                                                                                     1
https://www.eia.gov/dnav/pet/xls/PET_PRI_GND_DCUS_SCO_W.xls                                                                                                                                  1
https://data.colorado.gov/api/views/9pwz-gi5v/rows.csv?accessType=DOWNLOAD                                                                                                                   1
https://data.colorado.gov/api/views/pwjb-9dd5/rows.csv?accessType=DOWNLOAD                                                                                                                   1
Name: count, dtype: int64

In [81]:
df.head()

,Title,Group,Program,Address,File,Count,Cron
0,CIM Catalog Download,catalog,general/scripts/request_url.js,https://data.colorado.gov/api/views/e7nm-tn2z/rows.csv?accessType=DOWNLOAD,catalog/data_source/inventory-$(date +%F).csv,1,At 12:00 AM
1,Master List in Colorado,cdos/business/business,general/scripts/request_url.js,http://coloradosos.gov/pubs/UCC/downloadFiles/UCCMstrLB1.txt,cdos/business/business/data_source/masterlist.tsv,1,At 12:00 AM
2,Highway Milepoints in Colorado,cdot/transportation_road_attributes,general/scripts/request_url.js,http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/Mileposts.zip,cdot/transportation_road_attributes/data_source/mileposts.zip,1,At 12:00 AM
3,Highway Mileposts in Colorado,cdot/transportation_road_attributes,general/scripts/request_url.js,http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/Mileposts.zip,cdot/transportation_road_attributes/data_source/mileposts.zip,1,At 12:00 AM
4,Highway Routes in Colorado,cdot/transportation_road_attributes,general/scripts/request_url.js,http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/Routes.zip,cdot/transportation_road_attributes/data_source/routes.zip,1,At 12:00 AM

## All Combined Into ONE Cell

In [2]:
## Get ETL Directinves Out of run_etl.json For All Dataset

def find_files_recursive(directory):
    # This function finds all files recursively in a given directory
    return glob.glob(f'{directory}/**/run_etl.json', recursive=True)

def decodeExtract(extract):
    
    prog=""
    lang=""
    if 'language' in extract:
        lang=extract['language']
            
    if 'file' in extract:
        prog=extract['file']
        
    else:
        print("No Prgram",lang,title,file)
    opts={}
    if 'options' in extract:
        lang=extract['language']
        for opt in extract['options']:
            opt=opt.strip()
            indx=opt.find(" ")
            o=opt[:indx]
            opts[o]= opt[indx+1:]

    return lang,prog,opts


def processRun_etls(directory_path='/home/joe/bic_etl'): 
## Get all run_etl.json files
    files = find_files_recursive(directory_path)
    groups={}
    datasets={}
    noEx=0
    for file in files:
        ll=len(file)
        group=file[18:-13]
        fin=open(file)
        infos = json.load(fin)
        fin.close()
        title=""
        extract=""
        for info in infos: 
            if 'title' in info:
                title=info['title']
                datasets[title]={}
                datasets[title]['extract']={}
                datasets[title]['extract']['language']=''
                datasets[title]['extract']['program']=''
                datasets[title]['extract']['options']={}
                datasets[title]['group']=group
                if group not in groups:
                    groups[group]=[]
                groups[group].append(title)
                
                if 'extract' in info:
                    extract=info['extract']
                    if isinstance(extract,dict):
                       lang,prog,opts=decodeExtract(extract)
                       datasets[title]['extract']['language']=lang
                       datasets[title]['extract']['program']=prog
                       datasets[title]['extract']['options']=opts
                    elif isinstance(extract,list):
                        for infoL in extract: 
                            lang,prog,opts=decodeExtract(infoL)
                            datasets[title]['extract']['language']=lang
                            datasets[title]['extract']['program']=prog
                            datasets[title]['extract']['options']=opts
                    else:
                        print("UNK",type(info))
        
            else:
                print("No Title",file)
    return datasets,groups


def getUrlAddresses(datasets):
    hist={}
    addresses={}
    options={}
    specOpts={}
    specOpts["general/scripts/request_url.js"]={}
    specOpts["general/scripts/request_url.js"]["-u"]="-f"
    
    specOpts["general/scripts/sftp_extract.js"]={}
    specOpts["general/scripts/sftp_extract.js"]["-h"]="-f"
    specOpts["general/scripts/sftp_extract.js"]["none"]="-f"
    
    specOpts["cdos/general/scripts/sftp_extract.js"]={}
    specOpts["cdos/general/scripts/sftp_extract.js"]["none"]="-f"
    
    lookupNotFound = {
    'bea/scripts/bea_msa_api_reader.py':['https://apps.bea.gov/api/data'],
    'denver/scripts/get_data.py':['https://www.denvergov.org/content/dam/denvergov/Portals/covid19/documents/Denver-Approved-Patio-Expansion-List.xlsx'],
    'scripts/extract_liquor_files.py':'https://sbg.colorado.gov/liquor-license-lists',
    'county_sales_extract.py':['https://docs.google.com/spreadsheets/d/1br_cwfHy24d2R2bcXacb2KarOIBKGrbR/export?format=csv'],
    'scripts/county_salestax_extract.py':['https://docs.google.com/spreadsheets/d/1EhlDIrXjJdmg_ob2eMFeN5xtyvTq2jtr/export?format=csv'],
    'scripts/tax_fee_extract.py':['https://docs.google.com/spreadsheets/d/1e8hnG64Vkg9ffgkNpKQ1kzPsXNbGjG2X/export?format=csv'],
    'scripts/state_mar_sales_extract.py':['https://docs.google.com/spreadsheets/d/1wE7Z_1q2zxL7-kP0AqlUvL731U3Aui1l/export?format=csv'],
    'scripts/city_extract.py':['https://docs.google.com/spreadsheets/d/1wo4WKzvlfdw47_3841jD2RUibbDwos3L/export?format=csv','https://docs.google.com/spreadsheets/d/1WI2jvRCzBqYFIPA2vsUmCjHedKCQD911/export?format=csv'],
    'scripts/county_extract.py':['https://docs.google.com/spreadsheets/d/1irLP8K7jREdDgIiamgZ2MiTbkeMX5lrM/export?format=csv'],
    'scripts/extract_scripts/citybyindustry_extract.py':['https://docs.google.com/spreadsheets/d/1ZKc0olDlChHyRiLlxL3ECxKqBYtyaUaB/export?format=csv','https://docs.google.com/spreadsheets/d/1E6VqKiPnUD3LMnrSBy1aEYSc4QsU6Y9v/export?format=csv'],
    'scripts/extract_scripts/industry_extract.py':['https://docs.google.com/spreadsheets/d/{1WANzZQFE57J73daXvo1xu4mITy-1DmuP/export?format=csv','https://docs.google.com/spreadsheets/d/1cmTJ4ZRAjBFfevT0hyCatUXDIzIG393I/export?format=csv'],
    'scripts/extract_scripts/countybyindustry_extract.py':['https://docs.google.com/spreadsheets/d/1CI66-qv0ooK93asc21VyV-tJiYSc2J3c/export?format=csv','https://docs.google.com/spreadsheets/d/1kybUGf02krqwyl8yBPHnTbn0iQT4Cnnz/export?format=csv'],
    'scripts/extract_liquor_files.py':['https://sbg.colorado.gov/liquor-license-lists']
    }
    
    
    noProg={}
    for title,dct in datasets.items():
        if 'group' in dct:
            group=dct['group']
        else:
            group=""
        if 'extract' in dct:
            if 'language' in dct['extract']:
                lang=dct['extract']['language']
                prog=dct['extract']['program']
                if lang not in hist:
                    hist[lang]={}
                if prog not in hist[lang]:
                    hist[lang][prog]=0
                hist[lang][prog]+=1
    
                if prog not in addresses:
                    addresses[prog]={}
                if 'options' in dct['extract']:
                    if prog in specOpts:
                        o=list(specOpts[prog].keys())[0]
                        fOpt=specOpts[prog][o]
                        ff = dct['extract']['options'][fOpt]  
                        if o in dct['extract']['options']:
                            a=dct['extract']['options'][o]
                        else:
                            if prog == "general/scripts/sftp_extract.js":
                              a="ftps.sos.state.co.us"
                            else:
                              a=""
                    else:
                        ff=""
                        o=""
                        a=""
                        if prog in lookupNotFound:
                            a = lookupNotFound[prog]
                        else:
                            if prog not in noProg:
                                noProg[prog]={}
                            noProg[prog]['group']=group
                        
                    if isinstance(a,str):
                        b=[]
                        b.append(a)
                    else:
                        b=a
                    for a in b: 
                        if a not in addresses[prog]:
                            addresses[prog][a]={}
                        if ff not in addresses[prog][a]:
                           addresses[prog][a][ff]={}
                        
                        if title not in addresses[prog][a][ff]:
                           addresses[prog][a][ff][title]={}
                            
                           addresses[prog][a][ff][title]['count']=0
                           addresses[prog][a][ff][title]['group']=group
                        
                        
                    addresses[prog][a][ff][title]['count']+=1
##  Create a DataFrame
    programs=[]
    address=[]
    files=[]
    counts=[]
    titles=[]
    groups=[]
    for p,dct in addresses.items():
        for o,dct2 in dct.items():   
            for f,dct3 in dct2.items():
                for t,dct4 in dct3.items():
                    
                    programs.append(p)
                    address.append(o)
                    files.append(f)
                    counts.append(dct4['count'])
                    groups.append(dct4['group'])
                    
                    titles.append(t)
    df = pd.DataFrame({
        "Title":titles,
        "Group":groups,
        "Program":programs,
        "Address":address,
        "File":files,
        "Count":counts})
    return addresses,df

## Collect CRON Info from cron File

def getCronInfo(cron_file_path):
    fin=open(cron_file_path)
    lines=fin.readlines()
    crons={}
    for line in lines:
        if line[0:1] != "#" and line[0:1] != " " and len(line) > 2:
            line=line.strip()
            spl=line.split()
            crn=' '.join(spl[:5])
            rest = ' '.join(spl[5:])
            
            crons[rest]=crn
    return crons

def decodeCron(cron_file):
    hist={}
    cronGroups={}
    crons=getCronInfo(cron_file)
    for inf,crn in crons.items():
    
        desc = get_description(crn)
        spl=inf.split()
        lang=spl[0]
        prg=spl[1]
        indxP=inf.find("-p")
        if indxP > -1:
           tmp=inf[indxP+2:].lstrip()
           end=tmp.find(" ")
           grp=tmp[:end]
        else:
            grp=""
        indxT=inf.find("-t")
        if indxT > -1:
           tmp=inf[indxT+2:].lstrip()
           start = tmp.find('"')
           end=tmp[start+1:].find('"')
           titl=tmp[start+1:end+1]
        else:
            titl="ALL"
        if grp not in cronGroups:
            cronGroups[grp]={}
        cronGroups[grp][titl]=desc
        print(grp,titl)     
        if lang not in hist:
            hist[lang]={}
        if prg not in hist[lang]:
            hist[lang][prg]=0
        hist[lang][prg]+=1
    return cronGroups

## Combine Dataset ETL Info and CRON Info 
def addCronInfo(row):
    title=row['Title']
    group=row['Group']
#    print(group,title)
    if group in cronGroups:
        dct=cronGroups[group]
        if title in dct:
            cron=cronGroups[group][title]
        elif "ALL" in dct:
            cron=cronGroups[group]["ALL"]
        else:
            cron="Unknown"   
            
        # for how,crn in dct.items(): 
        #     print("  ",how,crn)
        #     if title in cronGroups[group]:
        #        cron=cronGroups[group][title]
        #        break
        #     elif how == "ALL":
        #         cron=crn
        #         break
        #     else:
        #         cron="Unknown"
        #         print("    Unknown ",how,title,crn)

    else:
        cron="No Group Found"
    print(group,cron,title)
    return cron

directory_path="/home/joe/bic_etl"
datasets,groups = processRun_etls(directory_path=directory_path)
addresses,df = getUrlAddresses(datasets) 
cron_file = '/home/joe/bic_etl/general/cron/cron_file'    
cronGroups=decodeCron(cron_file)
df["Cron"] = df.apply(addCronInfo,axis=1)

No Title /home/joe/bic_etl/general/example/run_etl.json
 ALL

 ALL
bls/sm ALL
boulder ALL
catalog ALL
cdos/business/nonprofit ALL
cdos/business/nonprofit Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado
cdos/business/business Business Entities in Colorado
cdos/business/business Business Entity Transaction History
cdos/health ALL
cdos/lobbyist ALL
cdos/government ALL
cdos/business/business Master List in Colorado
cdos/business/business Trade Names for Businesses in Colorado
cdos/business/business Trademarks for Businesses in Colorado
cdos/business/ucc ALL
cdot/transportation_road_attributes ALL
cdot/transportation_infrastructure ALL
cdot/natural_resources ALL
cdot/tops ALL
dola/boundaries ALL
dola/special_districts ALL
dola/demographics ALL
cdor/revenue_marijuana ALL
cdor/retail_reports ALL
cdor/regulations_liquor ALL
ceo/useia Gasoline Prices in Colorado
ceo/useia Natural Gas Prices in Colorado
 ALL
catalog At 04:00 AM CIM Catalog Download
cdot/transportation_road_attributes At 04:10 AM, on day 4 of the month Highway Milepoints in Colorado
cdot/transportation_road_attributes At 04:10 AM, on day 4 of the month Highway Mileposts in Colorado
cdot/transportation_road_attributes At 04:10 AM, on day 4 of the month Highway Routes in Colorado
cdot/transportation_road_attributes At 04:10 AM, on day 4 of the month Highways in Colorado
cdot/transportation_road_attributes At 04:10 AM, on day 4 of the month Local Roads in Colorado
cdot/transportation_road_attributes At 04:10 AM, on day 4 of the month Major Roads in Colorado
cdot/transportation_road_attributes At 04:10 AM, on day 4 of the month Scenic Byways in Colorado
cdot/natural_resources At 04:50 AM, on day 4 of the month Lakes in Colorado
cdot/natural_resources At 04:50 AM, on day 4 of the month Streams in Colorado
cdot/transportation_infrastructure At 04:30 AM, on day 4 of the month Airports in Colorado
cdot/transportation_infrastructure At 04:30 AM, on day 4 of the month Cities in Colorado
cdot/transportation_infrastructure At 04:30 AM, on day 4 of the month Counties in Colorado
cdot/transportation_infrastructure At 04:30 AM, on day 4 of the month Railroads in Colorado
dola/special_districts At 05:20 AM, on day 4 of the month Metro Districts in Colorado
dola/special_districts At 05:20 AM, on day 4 of the month Parks and Rec Districts in Colorado
dola/special_districts At 05:20 AM, on day 4 of the month Fire Districts in Colorado
dola/special_districts At 05:20 AM, on day 4 of the month Hospital Districts in Colorado
dola/special_districts At 05:20 AM, on day 4 of the month Water and Sanitation Districts in Colorado
dola/special_districts At 05:20 AM, on day 4 of the month Library Districts in Colorado
dola/special_districts At 05:20 AM, on day 4 of the month School Districts in Colorado
dola/special_districts At 05:20 AM, on day 4 of the month Soil Districts in Colorado
dola/special_districts At 05:20 AM, on day 4 of the month Cemetery Districts in Colorado
dola/special_districts At 05:20 AM, on day 4 of the month All Special Districts in Colorado
dola/boundaries At 04:00 AM, on day 4 of the month Municipal Annexations in Colorado
dola/boundaries At 04:00 AM, on day 4 of the month Municipal Boundaries in Colorado
dola/demographics At 04:30 AM, on day 1 of the month Population Projections in Colorado
dola/demographics At 04:30 AM, on day 1 of the month Race Estimates in Colorado
dola/demographics At 04:30 AM, on day 1 of the month Race Forecast in Colorado
cdor/regulations_liquor At 04:40 AM, on day 6 of the month Liquor Permits for Special Events in Colorado
cdor/regulations_liquor At 04:40 AM, on day 6 of the month Liquor Compliance Check Statistics in Colorado
cdor/regulations_liquor At 04:40 AM, on day 6 of the month Recently Approved Liquor Licenses in Colorado
cdor/regulations_liquor At 04:40 AM, on day 6 of the month Recently Expired and Surrendered Liquor Licenses in Colorado
cdor/regulations_liquor At 04:40 AM, on day 6 of the month Sales Rooms in Colorado
ceo/useia At 04:00 AM, only on Tuesday Gasoline Prices in Colorado
ceo/useia At 05:00 AM, only on Thursday Natural Gas Prices in Colorado
bls/sm At 04:00 AM, on day 15 of the month Average Weekly & Hourly Earnings and Work Hours Across Major Industry Sectors in Colorado
cdos/health At 04:00 AM, only on Tuesday Durable Medical Equipment Suppliers in Colorado
cdos/government At 04:30 AM, only on Tuesday Current Notaries in Colorado
cdos/business/ucc At 03:00 AM Uniform Commercial Code (UCC) Collateral Information in Colorado
cdos/business/ucc At 03:00 AM Uniform Commercial Code (UCC) Debtor Information in Colorado
cdos/business/ucc At 03:00 AM Uniform Commercial Code (UCC) Filing Information in Colorado
cdos/business/ucc At 03:00 AM Secured Party Information in Colorado
cdos/business/business At 05:10 AM Business Entities in Colorado
cdos/business/business At 08:00 AM Business Entity Transaction History
cdos/business/business At 04:00 AM, only on Tuesday Trademarks for Businesses in Colorado
cdos/business/business At 04:00 AM, only on Tuesday Trade Names for Businesses in Colorado
cdos/business/business At 05:30 AM, on day 4 of the month Master List in Colorado
cdos/business/nonprofit At 06:05 AM, only on Friday Campaign Reports for Solicitation Notices to Charities in Colorado
cdos/business/nonprofit At 06:05 AM, only on Friday Charitable Organizations’ Offices in Colorado
cdos/business/nonprofit At 06:05 AM, only on Friday Charitable Purpose of the Charity in Colorado
cdos/business/nonprofit At 06:05 AM, only on Friday Charitable Solicitation Call Center Locations in Colorado
cdos/business/nonprofit At 06:05 AM, only on Friday Charities Solicitation Type by Solicitation in Colorado
cdos/business/nonprofit At 06:05 AM, only on Friday Charity Extension Requests
cdos/business/nonprofit At 06:05 AM, only on Friday Communication Methods Used in Solicitation Campaigns in Colorado
cdos/business/nonprofit At 06:05 AM, only on Friday Federal Tax-Exempt Subsection Codes in Colorado
cdos/business/nonprofit At 06:05 AM, only on Friday Other Names a Registered Entity Uses to Solicit Contributions in Colorado
cdos/business/nonprofit At 06:05 AM, only on Friday Other State Solicitation of Charities’ Registrants in Colorado
cdos/business/nonprofit At 06:05 AM, only on Friday Paid Solicitors Disclosed on Charity Registration Forms in Colorado
cdos/business/nonprofit At 06:05 AM, only on Friday Paid Solicitor Solicitation Notices in Colorado
cdos/business/nonprofit At 06:05 AM, only on Friday Persons Associated with Charitable Organizations, Paid Solicitors, and Professional Fundraising Consultants in Colorado
cdos/business/nonprofit At 05:05 AM Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado
cdos/business/nonprofit At 06:05 AM, only on Friday Solicitation Campaign Supervisors Listed on Solicitation Notices in Colorado
cdos/lobbyist At 04:15 AM State Lobbyist Officials in Colorado
cdos/lobbyist At 04:15 AM State Lobbyist Directory in Colorado
cdos/lobbyist At 04:15 AM State Lobbyists Funds and Hours in Colorado
cdos/lobbyist At 04:15 AM State Lobbyist Bills in Colorado
cdos/lobbyist At 04:15 AM Professional Lobbyist Subcontractors in Colorado
cdos/lobbyist At 04:15 AM Professional Lobbyist Directory in Colorado
cdos/lobbyist At 04:15 AM Professional Lobbyist Income in Colorado
cdos/lobbyist At 04:15 AM Professional Lobbyist Expenditures in Colorado
cdos/lobbyist At 04:15 AM Professional Lobbyist Disclosure Report Summary in Colorado
cdos/lobbyist At 04:15 AM Professional Lobbyist Clients in Colorado
cdos/lobbyist At 04:15 AM Professional Lobbyist Bills in Colorado
irs No Group Found Purpose and Operational Size of Charities Operating in Colorado
irs No Group Found Fundraising Revenue of Charities Operating in Colorado
irs No Group Found Total Revenue of Charities Operating in Colorado
irs No Group Found IRS Filing Information for Charities Operating in Colorado
irs No Group Found Total Revenue and Types of Art for Charities Operating in Colorado
irs No Group Found Conservation Easements for Charities Operating in Colorado
irs No Group Found Activities of Charities Operating in Colorado
irs No Group Found Expenses of Charities Operating in Colorado
dpa No Group Found DPA Tops Data
boulder At 03:10 AM Restaurant Inspections in Boulder County
boulder At 03:10 AM Septic Systems in Boulder County Colorado
cdot/tops At 08:45 AM, only on Tuesday CDOT Expenses
cdot/tops At 08:45 AM, only on Tuesday CDOT Revenues
cdot/tops At 08:45 AM, only on Tuesday CDOT Payroll Expenditures
dora/regulations No Group Found Licensed Real Estate Professionals in Colorado
dora/regulations No Group Found Professional and Occupational Licenses in Colorado
cdhe No Group Found Enrollment Demographics for Post-Secondary Graduates in Colorado
cdhe No Group Found Post-Secondary Financial Aid Demographics in Colorado
tchd No Group Found Restaurant Inspections in Tri-County Colorado
bea No Group Found GDP by Metropolitan Statistical Area
denver No Group Found Temporary Outdoor Expansions for Restaurants in Denver, Colorado
cdor/revenue_marijuana At 04:20 AM, on day 1, 8, 15, and 22 of the month Marijuana Sales by County in Colorado
cdor/revenue_marijuana At 04:20 AM, on day 1, 8, 15, and 22 of the month Retail Marijuana Sales Tax Revenue by County in Colorado
cdor/revenue_marijuana At 04:20 AM, on day 1, 8, 15, and 22 of the month Marijuana Tax and Fee Revenue in Colorado
cdor/revenue_marijuana At 04:20 AM, on day 1, 8, 15, and 22 of the month Marijuana Sales Revenue in Colorado
cdor/retail_reports At 04:30 AM, on day 10 of the month Retail Sales Tax Return History in Colorado
cdor/retail_reports At 04:30 AM, on day 10 of the month Retail Reports by City in Colorado
cdor/retail_reports At 04:30 AM, on day 10 of the month Retail Reports by City in Colorado
cdor/retail_reports At 04:30 AM, on day 10 of the month Retail Reports by County in Colorado
cdor/retail_reports At 04:30 AM, on day 10 of the month Retail Reports by Industry and City in Colorado
cdor/retail_reports At 04:30 AM, on day 10 of the month Retail Reports by Industry and City in Colorado
cdor/retail_reports At 04:30 AM, on day 10 of the month Retail Reports by Industry and County in Colorado
cdor/retail_reports At 04:30 AM, on day 10 of the month Retail Reports by Industry and County in Colorado
cdor/retail_reports At 04:30 AM, on day 10 of the month Retail Reports by Industry in Colorado
cdor/retail_reports At 04:30 AM, on day 10 of the month Retail Reports by Industry in Colorado
cdor/regulations_liquor At 04:40 AM, on day 6 of the month Liquor Licenses in Colorado
cdor/regulations_liquor At 04:40 AM, on day 6 of the month Manufacturer Temporary Sales Room Permits in Colorado

In [8]:
cronGroups["cdos/business/nonprofit"]["Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"]

'At 05:05 AM'

In [5]:
cronGroups["cdos/business/nonprofit"]

{'ALL': 'At 06:05 AM, only on Friday',
 'Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado': 'At 05:05 AM'}

In [6]:
display(df[["Group","Title"]].head(200))

,Group,Title
0,catalog,CIM Catalog Download
1,cdos/business/business,Master List in Colorado
2,cdot/transportation_road_attributes,Highway Milepoints in Colorado
3,cdot/transportation_road_attributes,Highway Mileposts in Colorado
4,cdot/transportation_road_attributes,Highway Routes in Colorado
5,cdot/transportation_road_attributes,Highways in Colorado
6,cdot/transportation_road_attributes,Local Roads in Colorado
7,cdot/transportation_road_attributes,Major Roads in Colorado
8,cdot/transportation_road_attributes,Scenic Byways in Colorado
9,cdot/natural_resources,Lakes in Colorado
10,cdot/natural_resources,Streams in Colorado
11,cdot/transportation_infrastructure,Airports in Colorado
12,cdot/transportation_infrastructure,Cities in Colorado
13,cdot/transportation_infrastructure,Counties in Colorado
14,cdot/transportation_infrastructure,Railroads in Colorado
15,dola/special_districts,Metro Districts in Colorado
16,dola/special_districts,Parks and Rec Districts in Colorado
17,dola/special_districts,Fire Districts in Colorado
18,dola/special_districts,Hospital Districts in Colorado
19,dola/special_districts,Water and Sanitation Districts in Colorado
20,dola/special_districts,Library Districts in Colorado
21,dola/special_districts,School Districts in Colorado
22,dola/special_districts,Soil Districts in Colorado
23,dola/special_districts,Cemetery Districts in Colorado
24,dola/special_districts,All Special Districts in Colorado
25,dola/boundaries,Municipal Annexations in Colorado
26,dola/boundaries,Municipal Boundaries in Colorado
27,dola/demographics,Population Projections in Colorado
28,dola/demographics,Race Estimates in Colorado
29,dola/demographics,Race Forecast in Colorado
30,cdor/regulations_liquor,Liquor Permits for Special Events in Colorado
31,cdor/regulations_liquor,Liquor Compliance Check Statistics in Colorado
32,cdor/regulations_liquor,Recently Approved Liquor Licenses in Colorado
33,cdor/regulations_liquor,Recently Expired and Surrendered Liquor Licenses in Colorado
34,cdor/regulations_liquor,Sales Rooms in Colorado
35,ceo/useia,Gasoline Prices in Colorado
36,ceo/useia,Natural Gas Prices in Colorado
37,cdos/health,Durable Medical Equipment Suppliers in Colorado
38,cdos/government,Current Notaries in Colorado
39,cdos/business/ucc,Uniform Commercial Code (UCC) Collateral Information in Colorado
40,cdos/business/ucc,Uniform Commercial Code (UCC) Debtor Information in Colorado
41,cdos/business/ucc,Uniform Commercial Code (UCC) Filing Information in Colorado
42,cdos/business/ucc,Secured Party Information in Colorado
43,cdos/business/business,Business Entities in Colorado
44,cdos/business/business,Business Entity Transaction History
45,cdos/business/business,Trademarks for Businesses in Colorado
46,cdos/business/business,Trade Names for Businesses in Colorado
47,cdos/business/nonprofit,Campaign Reports for Solicitation Notices to Charities in Colorado
48,cdos/business/nonprofit,Charitable Organizations’ Offices in Colorado
49,cdos/business/nonprofit,Charitable Purpose of the Charity in Colorado
50,cdos/business/nonprofit,Charitable Solicitation Call Center Locations in Colorado
51,cdos/business/nonprofit,Charities Solicitation Type by Solicitation in Colorado
52,cdos/business/nonprofit,Charity Extension Requests
53,cdos/business/nonprofit,Communication Methods Used in Solicitation Campaigns in Colorado
54,cdos/business/nonprofit,Federal Tax-Exempt Subsection Codes in Colorado
55,cdos/business/nonprofit,Other Names a Registered Entity Uses to Solicit Contributions in Colorado
56,cdos/business/nonprofit,Other State Solicitation of Charities’ Registrants in Colorado
57,cdos/business/nonprofit,Paid Solicitors Disclosed on Charity Registration Forms in Colorado
58,cdos/business/nonprofit,Paid Solicitor Solicitation Notices in Colorado
59,cdos/business/nonprofit,"Persons Associated with Charitable Organizations, Paid Solicitors, and Professional Fundraising ..."
60,cdos/business/nonprofit,"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit..."
61,cdos/business/nonprofit,Solicitation Campaign Supervisors Listed on Solicitation Notices in Colorado
62,cdos/lobbyist,State Lobbyist Officials in Colorado
63,cdos/lobbyist,State Lobbyist Directory in Colorado
64,cdos/lobbyist,State Lobbyists Funds and Hours in Colorado
65,cdos/lobbyist,State Lobbyist Bills in Colorado
66,cdos/lobbyist,Professional Lobbyist Subcontractors in Colorado
67,cdos/lobbyist,Professional Lobbyist Directory in Colorado
68,cdos/lobbyist,Professional Lobbyist Income in Colorado
69,cdos/lobbyist,Professional Lobbyist Expenditures in Colorado
70,cdos/lobbyist,Professional Lobbyist Disclosure Report Summary in Colorado
71,cdos/lobbyist,Professional Lobbyist Clients in Colorado
72,cdos/lobbyist,Professional Lobbyist Bills in Colorado
73,boulder,Restaurant Inspections in Boulder County
74,boulder,Septic Systems in Boulder County Colorado
75,irs,Purpose and Operational Size of Charities Operating in Colorado
76,irs,Fundraising Revenue of Charities Operating in Colorado
77,irs,Total Revenue of Charities Operating in Colorado
78,irs,IRS Filing Information for Charities Operating in Colorado
79,irs,Total Revenue and Types of Art for Charities Operating in Colorado
80,irs,Conservation Easements for Charities Operating in Colorado
81,irs,Activities of Charities Operating in Colorado
82,irs,Expenses of Charities Operating in Colorado
83,dpa,DPA Tops Data
84,cdot/tops,CDOT Expenses
85,cdot/tops,CDOT Revenues
86,cdot/tops,CDOT Payroll Expenditures
87,dora/regulations,Licensed Real Estate Professionals in Colorado
88,dora/regulations,Professional and Occupational Licenses in Colorado
89,cdhe,Enrollment Demographics for Post-Secondary Graduates in Colorado
90,cdhe,Post-Secondary Financial Aid Demographics in Colorado
91,tchd,Restaurant Inspections in Tri-County Colorado
92,bea,GDP by Metropolitan Statistical Area
93,denver,"Temporary Outdoor Expansions for Restaurants in Denver, Colorado"
94,cdor/revenue_marijuana,Marijuana Sales by County in Colorado
95,cdor/revenue_marijuana,Retail Marijuana Sales Tax Revenue by County in Colorado
96,cdor/revenue_marijuana,Marijuana Tax and Fee Revenue in Colorado
97,cdor/revenue_marijuana,Marijuana Sales Revenue in Colorado
98,cdor/retail_reports,Retail Sales Tax Return History in Colorado
99,cdor/retail_reports,Retail Reports by City in Colorado
100,cdor/retail_reports,Retail Reports by City in Colorado
101,cdor/retail_reports,Retail Reports by County in Colorado
102,cdor/retail_reports,Retail Reports by Industry and City in Colorado
103,cdor/retail_reports,Retail Reports by Industry and City in Colorado
104,cdor/retail_reports,Retail Reports by Industry and County in Colorado
105,cdor/retail_reports,Retail Reports by Industry and County in Colorado
106,cdor/retail_reports,Retail Reports by Industry in Colorado
107,cdor/retail_reports,Retail Reports by Industry in Colorado
108,cdor/regulations_liquor,Liquor Licenses in Colorado
109,cdor/regulations_liquor,Manufacturer Temporary Sales Room Permits in Colorado

In [87]:
df.head()

,Title,Group,Program,Address,File,Count,Cron
0,CIM Catalog Download,catalog,general/scripts/request_url.js,https://data.colorado.gov/api/views/e7nm-tn2z/rows.csv?accessType=DOWNLOAD,catalog/data_source/inventory-$(date +%F).csv,1,At 04:00 AM
1,Master List in Colorado,cdos/business/business,general/scripts/request_url.js,http://coloradosos.gov/pubs/UCC/downloadFiles/UCCMstrLB1.txt,cdos/business/business/data_source/masterlist.tsv,1,"At 05:30 AM, on day 4 of the month"
2,Highway Milepoints in Colorado,cdot/transportation_road_attributes,general/scripts/request_url.js,http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/Mileposts.zip,cdot/transportation_road_attributes/data_source/mileposts.zip,1,"At 04:10 AM, on day 4 of the month"
3,Highway Mileposts in Colorado,cdot/transportation_road_attributes,general/scripts/request_url.js,http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/Mileposts.zip,cdot/transportation_road_attributes/data_source/mileposts.zip,1,"At 04:10 AM, on day 4 of the month"
4,Highway Routes in Colorado,cdot/transportation_road_attributes,general/scripts/request_url.js,http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/Routes.zip,cdot/transportation_road_attributes/data_source/routes.zip,1,"At 04:10 AM, on day 4 of the month"

In [114]:
newGroups={}
for group,titles in groups.items():
    spl=group.split("/")
    if len(spl) > 1:
       subGroup = '/'.join(spl[1:])
       group=spl[0]
    else:
       subGroup=""
    if group not in newGroups:
        newGroups[group]={}
    if len(subGroup) > 0:
        newGroups[group][subGroup]=titles
    else:
        newGroups[group]=titles

In [117]:
newGroups['cdot']

{'transportation_road_attributes': ['Highway Milepoints in Colorado',
  'Highway Mileposts in Colorado',
  'Highway Routes in Colorado',
  'Highways in Colorado',
  'Local Roads in Colorado',
  'Major Roads in Colorado',
  'Scenic Byways in Colorado'],
 'tops': ['CDOT Expenses', 'CDOT Revenues', 'CDOT Payroll Expenditures'],
 'natural_resources': ['Lakes in Colorado', 'Streams in Colorado'],
 'transportation_infrastructure': ['Airports in Colorado',
  'Cities in Colorado',
  'Counties in Colorado',
  'Railroads in Colorado']}

In [105]:
cronGroups

{'': {'ALL': 'At 02:47 PM', '': 'At 02:58 AM'},
 'boulder': {'ALL': 'At 03:10 AM'},
 'catalog': {'ALL': 'At 04:00 AM'},
 'cdos/business/nonprofit': {'ALL': 'At 06:05 AM, only on Friday',
  'Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado': 'At 05:05 AM'},
 'cdos/business/business': {'Business Entities in Colorado': 'At 05:10 AM',
  'Business Entity Transaction History': 'At 08:00 AM',
  'Master List in Colorado': 'At 05:30 AM, on day 4 of the month',
  'Trade Names for Businesses in Colorado': 'At 04:00 AM, only on Tuesday',
  'Trademarks for Businesses in Colorado': 'At 04:00 AM, only on Tuesday'},
 'cdos/health': {'ALL': 'At 04:00 AM, only on Tuesday'},
 'cdos/lobbyist': {'ALL': 'At 04:15 AM'},
 'cdos/government': {'ALL': 'At 04:30 AM, only on Tuesday'},
 'cdos/business/ucc': {'ALL': 'At 03:00 AM'},
 'cdot/transportation_road_attributes': {'ALL': 'At 04:10 AM, on day 4 of the month'},
 'cdot/transportation_infrastructure': {'ALL': 'At 04:30 AM, on day 4 of the month'},
 'cdot/natural_resources': {'ALL': 'At 04:50 AM, on day 4 of the month'},
 'cdot/tops': {'ALL': 'At 08:45 AM, only on Tuesday'},
 'dola/boundaries': {'ALL': 'At 04:00 AM, on day 4 of the month'},
 'dola/special_districts': {'ALL': 'At 05:20 AM, on day 4 of the month'},
 'dola/demographics': {'ALL': 'At 04:30 AM, on day 1 of the month'},
 'cdor/revenue_marijuana': {'ALL': 'At 04:20 AM, on day 1, 8, 15, and 22 of the month'},
 'cdor/retail_reports': {'ALL': 'At 04:30 AM, on day 10 of the month'},
 'cdor/regulations_liquor': {'ALL': 'At 04:40 AM, on day 6 of the month'},
 'ceo/useia': {'Gasoline Prices in Colorado': 'At 04:00 AM, only on Tuesday',
  'Natural Gas Prices in Colorado': 'At 05:00 AM, only on Thursday'}}

In [95]:
tmp=df.loc[df["Title"] == "Master List in Colorado"]

In [96]:
tmp.shape

(1, 7)

In [103]:
df["Cron"].value_counts()

Cron
No Group Found                                       16
Unknown                                              14
At 04:15 AM                                          11
At 04:30 AM, on day 10 of the month                  10
At 05:20 AM, on day 4 of the month                   10
At 04:10 AM, on day 4 of the month                    7
At 04:40 AM, on day 6 of the month                    7
At 04:30 AM, on day 4 of the month                    4
At 04:00 AM, only on Tuesday                          4
At 03:00 AM                                           4
At 04:20 AM, on day 1, 8, 15, and 22 of the month     4
At 04:30 AM, on day 1 of the month                    3
At 08:45 AM, only on Tuesday                          3
At 04:00 AM, on day 4 of the month                    2
At 04:50 AM, on day 4 of the month                    2
At 03:10 AM                                           2
At 05:30 AM, on day 4 of the month                    1
At 04:00 AM                                           1
At 05:00 AM, only on Thursday                         1
At 08:00 AM                                           1
At 05:10 AM                                           1
At 04:30 AM, only on Tuesday                          1
At 05:05 AM                                           1
Name: count, dtype: int64

In [102]:
group=list(tmp["Group"].value_counts().to_dict().keys())[0]
prog=list(tmp["Program"].value_counts().to_dict().keys())[0]
cron=list(tmp["Cron"].value_counts().to_dict().keys())[0]
print(group,prog,cron)
add = tmp["Address"].values.tolist()
file = tmp["File"].values.tolist()

cdos/business/business general/scripts/request_url.js At 05:30 AM, on day 4 of the month

In [101]:
add

['http://coloradosos.gov/pubs/UCC/downloadFiles/UCCMstrLB1.txt']

In [20]:
df.loc[df["Address"].str.contains("ftps")]

,Title,Group,Program,Address,File,Count,Cron
37,Durable Medical Equipment Suppliers in Colorado,cdos/health,general/scripts/sftp_extract.js,ftps.sos.state.co.us,DME/CurrentDMESuppliers-CIM.txt,1,"At 04:00 AM, only on Tuesday"
38,Current Notaries in Colorado,cdos/government,general/scripts/sftp_extract.js,ftps.sos.state.co.us,notary/CurrentCommissionedNotaries.txt,1,"At 04:30 AM, only on Tuesday"
39,Uniform Commercial Code (UCC) Collateral Information in Colorado,cdos/business/ucc,general/scripts/sftp_extract.js,ftps.sos.state.co.us,UCC/ucccoll2.txt,1,At 03:00 AM
40,Uniform Commercial Code (UCC) Debtor Information in Colorado,cdos/business/ucc,general/scripts/sftp_extract.js,ftps.sos.state.co.us,UCC/uccdbtr.txt,1,At 03:00 AM
41,Uniform Commercial Code (UCC) Filing Information in Colorado,cdos/business/ucc,general/scripts/sftp_extract.js,ftps.sos.state.co.us,UCC/uccstmt.txt,1,At 03:00 AM
42,Secured Party Information in Colorado,cdos/business/ucc,general/scripts/sftp_extract.js,ftps.sos.state.co.us,UCC/uccsecr.txt,1,At 03:00 AM
43,Business Entities in Colorado,cdos/business/business,general/scripts/sftp_extract.js,ftps.sos.state.co.us,business/corpmstr.txt,1,At 05:10 AM
44,Business Entity Transaction History,cdos/business/business,general/scripts/sftp_extract.js,ftps.sos.state.co.us,business/corphist-2.txt,1,At 08:00 AM
45,Trademarks for Businesses in Colorado,cdos/business/business,general/scripts/sftp_extract.js,ftps.sos.state.co.us,business/trademarks.txt,1,"At 04:00 AM, only on Tuesday"
46,Trade Names for Businesses in Colorado,cdos/business/business,general/scripts/sftp_extract.js,ftps.sos.state.co.us,business/tradenames.txt,1,"At 04:00 AM, only on Tuesday"
47,Campaign Reports for Solicitation Notices to Charities in Colorado,cdos/business/nonprofit,general/scripts/sftp_extract.js,ftps.sos.state.co.us,charity/sn_cmpgn_rpts.txt,1,Unknown
48,Charitable Organizations’ Offices in Colorado,cdos/business/nonprofit,general/scripts/sftp_extract.js,ftps.sos.state.co.us,charity/offices.txt,1,Unknown
49,Charitable Purpose of the Charity in Colorado,cdos/business/nonprofit,general/scripts/sftp_extract.js,ftps.sos.state.co.us,charity/purpose.txt,1,Unknown
50,Charitable Solicitation Call Center Locations in Colorado,cdos/business/nonprofit,general/scripts/sftp_extract.js,ftps.sos.state.co.us,charity/sol_ntcs_locs.txt,1,Unknown
51,Charities Solicitation Type by Solicitation in Colorado,cdos/business/nonprofit,general/scripts/sftp_extract.js,ftps.sos.state.co.us,charity/sol_typ_sol_ntcs.txt,1,Unknown
52,Charity Extension Requests,cdos/business/nonprofit,general/scripts/sftp_extract.js,ftps.sos.state.co.us,charity/char_orgs_ext.txt,1,Unknown
53,Communication Methods Used in Solicitation Campaigns in Colorado,cdos/business/nonprofit,general/scripts/sftp_extract.js,ftps.sos.state.co.us,charity/sol_typ_entity.txt,1,Unknown
54,Federal Tax-Exempt Subsection Codes in Colorado,cdos/business/nonprofit,general/scripts/sftp_extract.js,ftps.sos.state.co.us,charity/tax_exempt_cds.txt,1,Unknown
55,Other Names a Registered Entity Uses to Solicit Contributions in Colorado,cdos/business/nonprofit,general/scripts/sftp_extract.js,ftps.sos.state.co.us,charity/doing_bus_as.txt,1,Unknown
56,Other State Solicitation of Charities’ Registrants in Colorado,cdos/business/nonprofit,general/scripts/sftp_extract.js,ftps.sos.state.co.us,charity/states.txt,1,Unknown
57,Paid Solicitors Disclosed on Charity Registration Forms in Colorado,cdos/business/nonprofit,general/scripts/sftp_extract.js,ftps.sos.state.co.us,charity/char_orgs_sol.txt,1,Unknown
58,Paid Solicitor Solicitation Notices in Colorado,cdos/business/nonprofit,general/scripts/sftp_extract.js,ftps.sos.state.co.us,charity/sol_ntcs.txt,1,Unknown
59,"Persons Associated with Charitable Organizations, Paid Solicitors, and Professional Fundraising ...",cdos/business/nonprofit,general/scripts/sftp_extract.js,ftps.sos.state.co.us,charity/persons_entity.txt,1,Unknown
60,"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit...",cdos/business/nonprofit,general/scripts/sftp_extract.js,ftps.sos.state.co.us,charity/reg_finan.txt,1,At 05:05 AM
61,Solicitation Campaign Supervisors Listed on Solicitation Notices in Colorado,cdos/business/nonprofit,general/scripts/sftp_extract.js,ftps.sos.state.co.us,charity/persons_sol_ntcs.txt,1,Unknown
62,State Lobbyist Officials in Colorado,cdos/lobbyist,general/scripts/sftp_extract.js,ftps.sos.state.co.us,lobby/state_lobbyist_officials.txt,1,At 04:15 AM
63,State Lobbyist Directory in Colorado,cdos/lobbyist,general/scripts/sftp_extract.js,ftps.sos.state.co.us,lobby/state_lobbyist_directory.txt,1,At 04:15 AM
64,State Lobbyists Funds and Hours in Colorado,cdos/lobbyist,general/scripts/sftp_extract.js,ftps.sos.state.co.us,lobby/state_lobbyist_funds_hours.txt,1,At 04:15 AM
65,State Lobbyist Bills in Colorado,cdos/lobbyist,general/scripts/sftp_extract.js,ftps.sos.state.co.us,lobby/state_lobbyist_bills.txt,1,At 04:15 AM
66,Professional Lobbyist Subcontractors in Colorado,cdos/lobbyist,general/scripts/sftp_extract.js,ftps.sos.state.co.us,lobby/prof_subcontractors.txt,1,At 04:15 AM
67,Professional Lobbyist Directory in Colorado,cdos/lobbyist,general/scripts/sftp_extract.js,ftps.sos.state.co.us,lobby/prof_lobbyist_directory.txt,1,At 04:15 AM
68,Professional Lobbyist Income in Colorado,cdos/lobbyist,general/scripts/sftp_extract.js,ftps.sos.state.co.us,lobby/prof_income.txt,1,At 04:15 AM
69,Professional Lobbyist Expenditures in Colorado,cdos/lobbyist,general/scripts/sftp_extract.js,ftps.sos.state.co.us,lobby/prof_expenditures.txt,1,At 04:15 AM
70,Professional Lobbyist Disclosure Report Summary in Colorado,cdos/lobbyist,general/scripts/sftp_extract.js,ftps.sos.state.co.us,lobby/prof_disclosure_report_summary.txt,1,At 04:15 AM
71,Professional Lobbyist Clients in Colorado,cdos/lobbyist,general/scripts/sftp_extract.js,ftps.sos.state.co.us,lobby/prof_clients.txt,1,At 04:15 AM
72,Professional Lobbyist Bills in Colorado,cdos/lobbyist,general/scripts/sftp_extract.js,ftps.sos.state.co.us,lobby/prof_bills.txt,1,At 04:15 AM
73,Restaurant Inspections in Boulder County,boulder,general/scripts/sftp_extract.js,ftps.sos.state.co.us,BoulderCounty/Resturant_Inspection.csv,1,At 03:10 AM
74,Septic Systems in Boulder County Colorado,boulder,general/scripts/sftp_extract.js,ftps.sos.state.co.us,BoulderCounty/Septic_Export_from_Accela.csv,1,At 03:10 AM
75,Purpose and Operational Size of Charities Operating in Colorado,irs,general/scripts/sftp_extract.js,ftps.sos.state.co.us,irs_990/PurposeAndOperations.txt,1,No Group Found
76,Fundraising Revenue of Charities Operating in Colorado,irs,general/scripts/sftp_extract.js,ftps.sos.state.co.us,irs_990/Fundraising.txt,1,No Group Found
77,Total Revenue of Charities Operating in Colorado,irs,general/scripts/sftp_extract.js,ftps.sos.state.co.us,irs_990/TotalRevenue.txt,1,No Group Found
78,IRS Filing Information for Charities Operating in Colorado,irs,general/scripts/sftp_extract.js,ftps.sos.state.co.us,irs_990/FilerInfo.txt,1,No Group Found
79,Total Revenue and Types of Art for Charities Operating in Colorado,irs,general/scripts/sftp_extract.js,ftps.sos.state.co.us,irs_990/ArtCollections.txt,1,No Group Found
80,Conservation Easements for Charities Operating in Colorado,irs,general/scripts/sftp_extract.js,ftps.sos.state.co.us,irs_990/ConservationEasements.txt,1,No Group Found
81,Activities of Charities Operating in Colorado,irs,general/scripts/sftp_extract.js,ftps.sos.state.co.us,irs_990/Activities.txt,1,No Group Found
82,Expenses of Charities Operating in Colorado,irs,general/scripts/sftp_extract.js,ftps.sos.state.co.us,irs_990/ExpensesEZ.txt,1,No Group Found

In [ ]:
for group in df["Group"].value_counts().to_dict().keys():
    print(group)
    tmp = df.loc[df["Group"]==group]
    display(tmp[["Group","Title","Program","Address"]].head(100))