# Reconcile ETL Cron Runs vs Dataset Tracker Metadata

This program's goal is to compare the chronological frequency of all tasks being run on the OIT server against what is listed in the Dataset Tracker, which ultimatley is teh ground truth for ALL metadata for our CIM datasets, of which the dadtaset update schedule is just a small, though very important, part.

## Library Imports

In [1]:

import pandas as pd
import plotly.express as px
import calendar
from datetime import datetime
from datetime import timedelta
from cronsim import CronSim

from datetime import date

today = date.today()
import argparse
import json
#import PySimpleGUI as sg
#import PySimpleGUIWeb as sg
import pathlib
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
import textwrap
import re
import webbrowser
import subprocess
import collections
import pyglet,tkinter
from pyglet import font
import os
import subprocess
import requests
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# import OpenGL
# from OpenGL import GLU
font.add_file('/etc/fonts/fonts/CENTAUR.TTF')
font='Courier 10 bold '
import difflib

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)
pd.options.mode.chained_assignment = None 
pd.options.display.max_colwidth = 100
pd.set_option('display.width', 1500)
pd.set_option('display.max_colwidth', 1000)

## Get CRON info

### Read the cron_file from the local ETL github repo

In [2]:
crons = []
def find_all(a_str, sub):
    start = 0
    while True:
        start = a_str.find(sub, start)
        if start == -1: return
        yield start
        start += len(sub) # use start += 1 to find overlapping matches
with open("/home/joe/bic_etl/general/cron/cron_file","r") as fin:
    for line in fin:
        if line[0:1] != "#"  and len(line) > 5:
           #print(line0)
#           print(line)
           crons.append(line.rstrip())
        line0=line
print(f"{len(crons)} Cron Jobs Found")

crons_all = []
ncrons=0
descriptions = []
for line in crons:
    line = line.strip(" ")
    spl = line.split(" ")
    crn=""
    print(line)
    mm = line.find("node")
    nj = line.find("java")
    npyth = line.find("python")
    nt = line.find("-t")
    np = line.find("-p")
    if (np > 0):
        a = list(find_all(line[np:],'\"'))
        # if len(a) > 0:
        #   p=line[np+a[0]:np+a[1]+1]
        # else:
        ss = line[np:].split()
        p=ss[1]
    elif mm > 0:
        pp = spl[6].split("/")
        p= pp[-1]
        
    elif nj > 0:  # java line
        pp = spl[7].split("/")
        p= pp[-1]
       
    elif npyth > 0:  # java line
        pp = spl[10].split("/")
        p= pp[-1]
       
    else:
            p=""
        
    if (nt > 0):
        ngt = line.find(">>")
        a = list(find_all(line[nt:ngt],'\"'))
        if len(a) > 0:
          t=line[nt+a[0]:nt+a[1]+1]
        else:
          ss = line[nt:].split()
          t=ss[1]
    else:
        t=""
            

    for val in spl[:5]:
        crn+= f"{val} "
    crn = crn.rstrip()
    if spl[5] == "node":
        pg = spl[6]
    else:
        pg=""
    if len(p) > 0:  #  There is a program listed
      
        pgs=pg.split("/")
       
    #    print(line)
        mo = 1
        yr=today.year
        mo=today.month
        
        
        try:
            it = CronSim(crn,datetime.strptime(f"{yr}-{mo}-01","%Y-%m-%d"))
            tmp={}
            tmp["line"]=line
            tmp["desc"] = it.explain()
            print("ME ",yr,mo,it.explain())
            descriptions.append(tmp)
            a = next(it) 
        
            while  a.month == mo:
         #       print(a.month,a.day,a.hour,a.minute,a.hour+a.minute/60)
         #       print("DAY ",calendar.day_name[a.weekday()])
          #      print(f"start:{a}   end:{a+timedelta(days=1)}")
                d = dict(Day=calendar.day_name[a.weekday()],Cron=line,T=t,TM=f"{a.hour}:{a.minute}",Task=p,Details=t,Program=pg,Start=a,End=a+timedelta(days=1),Time=a.hour+a.minute/60)
                crons_all.append(d)
            # print(f"pg: {pg} P:{p} T:{t}")    
                a = next(it)
            ncrons+=1 
        except Exception as err:
            print("Count not Process",crn)
            print(err)
            print(line)
    else:  # Not a node runnning a cim dataset... must be java or python
        print(line)
    #  print("--------")

print(f"{len(crons_all)}  Crons successfully mapped to time ranges")

30 Cron Jobs Found
50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 02:50 every day
58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 02:58 every day
0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 05:00 every day
10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 03:10 every day
0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 04:00 every day
5 6 * * 5 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 06:05 on Friday
5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 05:05 every day
10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 05:10 every day
0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 08:00 every day
0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/health 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 04:00 on Tuesday
15 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 04:15 on Tuesday
30 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/government 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 04:30 on Tuesday
30 5 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Master List in Colorado" 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 05:30 on the fourth day of every month
0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Trade Names for Businesses in Colorado" 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 04:00 on Tuesday
0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Trademarks for Businesses in Colorado" 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 04:00 on Tuesday
0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 03:00 every day
10 4 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdot/transportation_road_attributes -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.8-jar-with-dependencies.jar 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 04:10 on the fourth day of every month
30 4 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdot/transportation_infrastructure 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 04:30 on the fourth day of every month
50 4 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdot/natural_resources 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 04:50 on the fourth day of every month
45 5 * * 3 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdot/tops 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 05:45 on Wednesday
0 4 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dola/boundaries 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 04:00 on the fourth day of every month
20 5 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dola/special_districts 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 05:20 on the fourth day of every month
30 4 1 * *  node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dola/demographics 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 04:30 on the first day of every month
20 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dora/regulations -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 03:20 every day
20 4 1,8,15,22 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/revenue_marijuana 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 04:20 on the first, the eighth, the 15th, and the 22th day of month
30 4 1,8,15,22 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/retail_reports 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 04:30 on the first, the eighth, the 15th, and the 22th day of month
40 4 1,8,15,22 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/regulations_liquor 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 04:40 on the first, the eighth, the 15th, and the 22th day of month
0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Gasoline Prices in Colorado" 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 04:00 on Tuesday
0 5 * * 4 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Natural Gas Prices in Colorado" 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 05:00 on Thursday
47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> $bic_etl_home/general/logs/cron.log
ME  2024 3 At 14:47 every day
397  Crons successfully mapped to time ranges

In [13]:
print(today.today())
display(dir(today))

2024-03-10

['__add__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 'ctime',
 'day',
 'fromisocalendar',
 'fromisoformat',
 'fromordinal',
 'fromtimestamp',
 'isocalendar',
 'isoformat',
 'isoweekday',
 'max',
 'min',
 'month',
 'replace',
 'resolution',
 'strftime',
 'timetuple',
 'today',
 'toordinal',
 'weekday',
 'year']

Sunday

In [17]:
day = datetime.now().strftime('%A')
print(day)

tod={}
for cron in crons_all:
    if cron['Day'] == day:
       print(cron['Day'],cron['Cron'])
       tod[cron['Cron']]=1

Sunday
Sunday 50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> $bic_etl_home/general/logs/cron.log
Sunday 50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> $bic_etl_home/general/logs/cron.log
Sunday 50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> $bic_etl_home/general/logs/cron.log
Sunday 50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> $bic_etl_home/general/logs/cron.log
Sunday 50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> $bic_etl_home/general/logs/cron.log
Sunday 58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> $bic_etl_home/general/logs/cron.log
Sunday 58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> $bic_etl_home/general/logs/cron.log
Sunday 58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> $bic_etl_home/general/logs/cron.log
Sunday 58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> $bic_etl_home/general/logs/cron.log
Sunday 58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> $bic_etl_home/general/logs/cron.log
Sunday 10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> $bic_etl_home/general/logs/cron.log
Sunday 10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> $bic_etl_home/general/logs/cron.log
Sunday 10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> $bic_etl_home/general/logs/cron.log
Sunday 10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> $bic_etl_home/general/logs/cron.log
Sunday 10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> $bic_etl_home/general/logs/cron.log
Sunday 5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> $bic_etl_home/general/logs/cron.log
Sunday 5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> $bic_etl_home/general/logs/cron.log
Sunday 5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> $bic_etl_home/general/logs/cron.log
Sunday 5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> $bic_etl_home/general/logs/cron.log
Sunday 5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> $bic_etl_home/general/logs/cron.log
Sunday 10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> $bic_etl_home/general/logs/cron.log
Sunday 10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> $bic_etl_home/general/logs/cron.log
Sunday 10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> $bic_etl_home/general/logs/cron.log
Sunday 10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> $bic_etl_home/general/logs/cron.log
Sunday 10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> $bic_etl_home/general/logs/cron.log
Sunday 0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> $bic_etl_home/general/logs/cron.log
Sunday 20 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dora/regulations -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> $bic_etl_home/general/logs/cron.log
Sunday 20 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dora/regulations -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> $bic_etl_home/general/logs/cron.log
Sunday 20 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dora/regulations -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> $bic_etl_home/general/logs/cron.log
Sunday 20 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dora/regulations -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> $bic_etl_home/general/logs/cron.log
Sunday 20 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dora/regulations -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> $bic_etl_home/general/logs/cron.log
Sunday 47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> $bic_etl_home/general/logs/cron.log
Sunday 47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> $bic_etl_home/general/logs/cron.log
Sunday 47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> $bic_etl_home/general/logs/cron.log
Sunday 47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> $bic_etl_home/general/logs/cron.log
Sunday 47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> $bic_etl_home/general/logs/cron.log

In [20]:
for key in tod:
 #   print(key)
    if key.find("node") > -1:
   #     print("Found Node")
        st = key.find("node")
        key=key[st:]
        ed = key.find("2>>")
  #      print(key[:ed])
    elif key.find("PATH") > -1:
        st = key.find("PATH")
        key=key[st:]
        ed = key.find("2>>")
  #      print(key[:ed])
    else:
        print(key)

58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> $bic_etl_home/general/logs/cron.log

In [30]:
keys = ["node","PATH","/usr/bin"]
tod2 = tod.copy()
toRun = []
for string in tod:
 #   print(key)
    hit=0
    for key in keys:
        if string.find(key) > -1:
            st = string.find(key)
            string=string[st:]
            ed = string.find("2>>")
            hit=1
            if ed > -1:
                toRun.append(string[:ed])
            else:
                print("ROH ROH ",string)
    if hit == 0:
        print(string)
   

for string in toRun:
    print(string)

node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js
/usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json
PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a
node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder
node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog
node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar
node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado"
node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History"
node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc
node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dora/regulations -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar
node /usr/local/cim/bic_etl/general/scripts/cleanup.js

###  Get Groups and datasets listed in cron file

In [ ]:
cron4Xref = []
for ds in descriptions:
    print(ds["line"])
    st=ds["line"].find(r"-p")
    if st > 0:
       end = ds["line"][st+3:].find(r" ")
       group = ds["line"][st+2:st+3+end]
       print("Group: ",group)
       st = ds["line"].find(r"-t")
       ds["group"] = group
       if st > 0:
            st1 = ds["line"][st+3:].find('"')
            ed1 = ds["line"][st+3+st1+1:].find('"')
            dstitle = ds["line"][st+3+st1:st+3+st1+ed1+2]      
            print("title ",dstitle)
            ds["title"] = dstitle
       cron4Xref.append(ds) 
    print("-------------------------------------------------------\n")

In [ ]:
cron4Xref

<b>cron4Xref</b>  ->  a list which contains info about the different groups/datasets being updated by the CRON job.  The majority of the ETL updates are done by groups of datasets, but a few dataset specific updates are also run.

### XREF Groups to Dataset Titles

The majority of the dataset updates in the cron file are done by group, i.e. where just a group is listed in the cron file, and the bic_etl.js program reads teh run_etl.json files for that group and gets all teh dataset titles that are needed (and all the steps).  So we need to get all the datasets listed for each group from the run_etl.json files for all the groups.

#### Get the Unique Set of Groups

In [5]:
groups={}
for val in cron4Xref:
    group = val["group"].strip()
    print(group)
    if group not in groups:
        groups[group]=0
    groups[group]+=1

boulder
catalog
cdos/business/nonprofit
cdos/business/nonprofit
cdos/business/business
cdos/business/business
cdos/health
cdos/lobbyist
cdos/government
cdos/business/business
cdos/business/business
cdos/business/business
cdos/business/ucc
cdot/transportation_road_attributes
cdot/transportation_infrastructure
cdot/natural_resources
cdot/tops
dola/boundaries
dola/special_districts
dola/demographics
dora/regulations
cdor/revenue_marijuana
cdor/retail_reports
cdor/regulations_liquor
ceo/useia
ceo/useia

#### Get All Datasets for Each Group

In [6]:
def getTitles(string):
    titles=[]
    h = subprocess.check_output(string,shell=True)
    j = str(h).split("\\")
    for s in j:
       k = s.split(":")
       if len(k) > 1:
            title=k[1].strip()
            title=title.rstrip(",")
            titles.append(title)
    return titles
titlesG = {}
titles = {}
for key,count in groups.items():
    print(count,key)
    string = f"grep -i title /home/joe/bic_etl/{key}/run_etl.json"

    titlesG[key] = getTitles(string)
    
    for title in titlesG[key]:
      #  print(title)
        titles[title] = key

1 boulder
1 catalog
2 cdos/business/nonprofit
5 cdos/business/business
1 cdos/health
1 cdos/lobbyist
1 cdos/government
1 cdos/business/ucc
1 cdot/transportation_road_attributes
1 cdot/transportation_infrastructure
1 cdot/natural_resources
1 cdot/tops
1 dola/boundaries
1 dola/special_districts
1 dola/demographics
1 dora/regulations
1 cdor/revenue_marijuana
1 cdor/retail_reports
1 cdor/regulations_liquor
2 ceo/useia

In [7]:
titlesG

{'boulder': ['"Restaurant Inspections in Boulder County"',
  '"Septic Systems in Boulder County Colorado"'],
 'catalog': ['"CIM Catalog Download"'],
 'cdos/business/nonprofit': ['"Federal Tax-Exempt Subsection Codes in Colorado"',
  '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
  '"Charitable Organizations',
  '"Other State Solicitation of Charities',
  '"Charitable Purpose of the Charity in Colorado"',
  '"Paid Solicitor Solicitation Notices in Colorado"',
  '"Campaign Reports for Solicitation Notices to Charities in Colorado"',
  '"Solicitation Campaign Supervisors Listed on Solicitation Notices in Colorado"',
  '"Charity Extension Requests"',
  '"Persons Associated with Charitable Organizations, Paid Solicitors, and Professional Fundraising Consultants in Colorado"',
  '"Other Names a Registered Entity Uses to Solicit Contributions in Colorado"',
  '"Paid Solicitors Disclosed on Charity Registration Forms in Colorado"',
  '"Charitable Solicitation Call Center Locations in Colorado"',
  '"Charities Solicitation Type by Solicitation in Colorado"',
  '"Communication Methods Used in Solicitation Campaigns in Colorado"'],
 'cdos/business/business': ['"Business Entities in Colorado"',
  '"Business Entity Transaction History"',
  '"Trademarks for Businesses in Colorado"',
  '"Trade Names for Businesses in Colorado"',
  '"Master List in Colorado"'],
 'cdos/health': ['"Durable Medical Equipment Suppliers in Colorado"'],
 'cdos/lobbyist': ['"Directory of Lobbyists in Colorado"',
  '"Directory of Lobbyist Clients in Colorado"',
  '"Expenses for Lobbyists in Colorado"',
  '"Characterization of Lobbyist Clients in Colorado"',
  '"Subcontractors for Lobbyists in Colorado"',
  '"Bill Information and Position with Income of Lobbyist in Colorado"'],
 'cdos/government': ['"Current Notaries in Colorado"'],
 'cdos/business/ucc': ['"Uniform Commercial Code (UCC) Collateral Information in Colorado"',
  '"Uniform Commercial Code (UCC) Debtor Information in Colorado"',
  '"Uniform Commercial Code (UCC) Filing Information in Colorado"',
  '"Secured Party Information in Colorado"'],
 'cdot/transportation_road_attributes': ['"Highway Milepoints in Colorado"',
  '"Highway Mileposts in Colorado"',
  '"Highway Routes in Colorado"',
  '"Highways in Colorado"',
  '"Local Roads in Colorado"',
  '"Major Roads in Colorado"',
  '"Scenic Byways in Colorado"'],
 'cdot/transportation_infrastructure': ['"Airports in Colorado"',
  '"Cities in Colorado"',
  '"Counties in Colorado"',
  '"Railroads in Colorado"'],
 'cdot/natural_resources': ['"Lakes in Colorado"', '"Streams in Colorado"'],
 'cdot/tops': ['"CDOT Expenses"',
  '"CDOT Revenues"',
  '"CDOT Payroll Expenditures"'],
 'dola/boundaries': ['"Municipal Annexations in Colorado"',
  '"Municipal Boundaries in Colorado"'],
 'dola/special_districts': ['"Metro Districts in Colorado"',
  '"Parks and Rec Districts in Colorado"',
  '"Fire Districts in Colorado"',
  '"Hospital Districts in Colorado"',
  '"Water and Sanitation Districts in Colorado"',
  '"Library Districts in Colorado"',
  '"School Districts in Colorado"',
  '"Soil Districts in Colorado"',
  '"Cemetery Districts in Colorado"',
  '"All Special Districts in Colorado"'],
 'dola/demographics': ['"Population Projections in Colorado"',
  '"Race Estimates in Colorado"',
  '"Race Forecast in Colorado"'],
 'dora/regulations': ['"Licensed Real Estate Professionals in Colorado"',
  '"Professional and Occupational Licenses in Colorado"'],
 'cdor/revenue_marijuana': ['"Marijuana Sales by County in Colorado"',
  '"Retail Marijuana Sales Tax Revenue by County in Colorado"',
  '"Marijuana Tax and Fee Revenue in Colorado"',
  '"Marijuana Sales Revenue in Colorado"'],
 'cdor/retail_reports': ['"Retail Sales Tax Return History in Colorado"',
  '"Retail Reports by City in Colorado"',
  '"Retail Reports by County in Colorado"',
  '"Retail Reports by Industry and City in Colorado"',
  '"Retail Reports by Industry and County in Colorado"',
  '"Retail Reports by Industry in Colorado"'],
 'cdor/regulations_liquor': ['"Liquor Permits for Special Events in Colorado"',
  '"Liquor Compliance Check Statistics in Colorado"',
  '"Liquor Licenses in Colorado"',
  '"Recently Approved Liquor Licenses in Colorado"',
  '"Recently Expired and Surrendered Liquor Licenses in Colorado"',
  '"Sales Rooms in Colorado"',
  '"Manufacturer Temporary Sales Room Permits in Colorado"'],
 'ceo/useia': ['"Gasoline Prices in Colorado"',
  '"Natural Gas Prices in Colorado"']}

## Get Update Metadata from Dataset Tracker

### Get ALL Datasets in Tracker

Get ALL the datasets listed in the dataset tracker.

In [8]:
def getXrefs():
    '''Reads the Inventory google sheet and gets the datasets title and cross-refs it to the Socrata 4x4 id.  Also
    gets the fields by 4x4 dataset id and by the title'''
    scope = ['https://www.googleapis.com/auth/spreadsheets.readonly',
             "https://www.googleapis.com/auth/drive.file",
                  "https://www.googleapis.com/auth/drive"]

    creds = ServiceAccountCredentials.from_json_keyfile_name('/home/joe/work/client_secret.json',
     scope)
    client = gspread.authorize(creds)

    gc = gspread.service_account("/home/joe/work/client_secret.json")
    # for gg in gc.list_spreadsheet_files():
    #      print("GGGGG ",gg)
    
    tracker = client.open('BIC Dataset Tracker').worksheet(
    'PublishedData')
   

    df = pd.DataFrame(tracker.get_all_records(head=3))

    return df
            
df = getXrefs()

/tmp/ipykernel_769/2438374747.py:24: DeprecationWarning: [Deprecated][in version 6.0.0]: client_factory will be replaced by gspread.http_client types
  df = getXrefs()

In [9]:
df.columns

Index(['Dataset Title', 'Short Description', 'Category', 'Keywords', 'Type', 'License Type', 'Data Provider', 'Data Provided by', 'Source Link', 'State Steward', 'Citation', 'Agency Program Page', 'Agency Data Series Page', 'Business Contact and Phone', 'Technical Contact and Phone', 'Data Source', 'Unit of Analysis', 'Granularity Coverage', 'Geographic Extent and Division', 'Collection Mode', 'Collection Methodology', 'Data Collection Instrument', 'Date of Initial Dataset Creation', 'Field Names, comma delimited', 'Oldest Record in Dataset', 'Newest Record in Dataset', 'Long Description', 'Data Dictionary', 'Additional Metadata', 'Technical Documentation', 'Data Quality Certification', 'Applicable Information Quality Guideline Designation', 'Stewardship Plan', 'Collection Method', 'Horizontal Accuracy', 'Horizontal Coordinate System', 'Update Schedule', 'Update Method', 'Source Update Schedule', 'Update Schedule Last Audit', 'Update Type', 'Total Records at Initial Publish', 'Row Class RDF', 'Subject Column RDF', 'Single Row', 'Row Count (11/20/17)', 'Total Fields at Initial Publish', 'FIle Size at Initial Publish or as of 3-1-2016', 'Expected approximate increase in record count at update', 'Date Published to CIM', 'GoCode FY Published to CIM', 'Socrata Link', 'API 4x4', 'Web Display Coordinate System', 'Coordinate System Disclaimer', 'Related Datasets', 'Quarter of Gov FY Published', 'cimAllData Updates', 'Complexity'], dtype='object')

In [10]:
sorted(df.columns)

['API 4x4',
 'Additional Metadata',
 'Agency Data Series Page',
 'Agency Program Page',
 'Applicable Information Quality Guideline Designation',
 'Business Contact and Phone',
 'Category',
 'Citation',
 'Collection Method',
 'Collection Methodology',
 'Collection Mode',
 'Complexity',
 'Coordinate System Disclaimer',
 'Data Collection Instrument',
 'Data Dictionary',
 'Data Provided by',
 'Data Provider',
 'Data Quality Certification',
 'Data Source',
 'Dataset Title',
 'Date Published to CIM',
 'Date of Initial Dataset Creation',
 'Expected approximate increase in record count at update',
 'FIle Size at Initial Publish or as of 3-1-2016',
 'Field Names, comma delimited',
 'Geographic Extent and Division',
 'GoCode FY Published to CIM',
 'Granularity Coverage',
 'Horizontal Accuracy',
 'Horizontal Coordinate System',
 'Keywords',
 'License Type',
 'Long Description',
 'Newest Record in Dataset',
 'Oldest Record in Dataset',
 'Quarter of Gov FY Published',
 'Related Datasets',
 'Row Class RDF',
 'Row Count (11/20/17)',
 'Short Description',
 'Single Row',
 'Socrata Link',
 'Source Link',
 'Source Update Schedule',
 'State Steward',
 'Stewardship Plan',
 'Subject Column RDF',
 'Technical Contact and Phone',
 'Technical Documentation',
 'Total Fields at Initial Publish',
 'Total Records at Initial Publish',
 'Type',
 'Unit of Analysis',
 'Update Method',
 'Update Schedule',
 'Update Schedule Last Audit',
 'Update Type',
 'Web Display Coordinate System',
 'cimAllData Updates']

### Extract Just the Subset of Metadata we Need

In [11]:
#dfS = df[['Socrata Link','Dataset Title','State Steward','Category','Type','Update Type','Update Schedule', 'Update Method','Source Update Schedule','CIM Updated', 'Days Since CIM Update',
#       'cimAllData Updates', 'Complexity']]

dfS = df[['Socrata Link','Dataset Title','State Steward','Category','Type','Update Type','Update Schedule', 'Update Method','Source Update Schedule',
       'cimAllData Updates', 'Complexity']]

### Quick View of the Unique Values in Each Column

In [12]:
for col in dfS.columns:
    print("Column ",col)
    print(dfS[col].value_counts())
    print("-----------------------------------------")

Column  Socrata Link
Socrata Link
itzi-4q6v    6
8hx8-24k6    1
pxgq-s7pg    1
be63-q8yz    1
2mk-94p9     1
ifza-iedd    1
evkd-zgn4    1
e4ky-6g2n    1
5ccs-vx79    1
u943-ics6    1
5qqr-23dz    1
t8ag-kzkw    1
knbf-ggf2    1
ej2c-jkvh    1
3sm5-jtur    1
j7a3-jgd3    1
d4s4-xqg6    1
e7ye-tasg    1
gyeb-jc69    1
qvrk-xsmj    1
d6t8-xish    1
ier5-5ms2    1
kapc-ib6e    1
4zse-6bnw    1
pdd3-umrz    1
hpem-wb68    1
ab5h-juwk    1
wv7f-qjj7    1
68n7-r6rp    1
7s5z-vewr    1
349y-twqi    1
g53r-j5td    1
q5vp-adf3    1
bu8h-8sux    1
afm6-vyyp    1
3j7e-ezpr    1
sfvq-tb9q    1
mr4v-jz8u    1
2cpa-vbur    1
n55r-9hud    1
73ay-2ues    1
853a-s2qz    1
wwbh-7bpa    1
ew9y-6tv9    1
5wyf-xqw7    1
q2av-rpr5    1
3ka2-m6zm    1
mguq-rjzb    1
3thw-b7wj    1
y6w6-igw6    1
gemu-wyf3    1
q2iw-kpix    1
rpvk-ifh4    1
xz8z-8s8e    1
g62i-kdzu    1
82s5-cpkk    1
8pk9-mh2i    1
ipm7-5rxr    1
tn2f-pf3u    1
chpv-m4xq    1
hysf-mrke    1
b7zn-sry4    1
ceje-t3ek    1
24hn-nv39    1
y2yv-a2wp    1
kr2r-j5ik    1
ua3v-vcuh    1
2z9k-uy4q    1
ujgg-3rdh    1
mxfq-jecf    1
ms6b-y4xc    1
x2jf-bvk8    1
xb4j-dshc    1
eqsm-7ah7    1
9fte-yff6    1
dm2a-biqr    1
7tmk-3ibe    1
uksn-8qya    1
knby-gpaw    1
u6xi-qwn3    1
7sv7-7d5a    1
pt2g-89wc    1
wxzv-xh9i    1
2h6w-z9ry    1
fbn4-ype4    1
56kc-gpid    1
an2q-gwrx    1
ue4w-dnyi    1
3bgg-gcfa    1
4h6z-rhfw    1
xs2v-uzeg    1
skxn-j975    1
7amf-p4uj    1
d6bh-7i9s    1
uhup-hcc4    1
49ck-u67r    1
trm9-dm4m    1
9syq-9vv5    1
jr8i-33tp    1
4vf9-vbyi    1
4ykn-tg5h    1
v4as-sthd    1
hbkb-4hbj    1
xwar-3geb    1
n9gj-cjub    1
a58g-ce2r    1
vewn-5ajx    1
rcw7-6npp    1
d2cu-rhft    1
42wt-sxkv    1
wyy2-wvrc    1
mqid-8hv2    1
yvwz-kj9z    1
72dx-vrxk    1
knn6-7fy9    1
yajv-ea35    1
wpcp-usqg    1
yree-6k9x    1
fph6-vi4y    1
ii3b-uafi    1
5s6g-ze7t    1
pfjr-vhp3    1
e86d-vx82    1
jd4d-pcwx    1
8pmi-n437    1
xipb-k5bu    1
r87x-h98m    1
us3j-cyz6    1
nbfg-y9mh    1
jwbw-xb7i    1
spwe-6ca7    1
ge9s-ra8y    1
ty5m-9xub    1
iku4-4bpx    1
6hee-tnp6    1
cmkv-zd4f    1
casm-dbbj    1
jjnc-cu9z    1
6ddv-3hk2    1
kfm9-mvzv    1
22bw-ijyi    1
9h8i-6khx    1
6ad7-gqy3    1
2kvt-7ybu    1
rkmy-yymq    1
n5ku-eixc    1
fdcw-ei67    1
6ntv-x37b    1
s9wt-dsfz    1
9gri-r239    1
9ghp-7fx6    1
nbem-wipy    1
gi9w-h59d    1
cr6z-hn4e    1
cdva-fnp3    1
ccz9-ggrb    1
j8pu-22qi    1
6kn4-89kh    1
fe4v-h3pk    1
k3gg-hhc8    1
x8tb-f3vh    1
d6bs-3kgu    1
v9m8-x8dh    1
rjvq-j29g    1
cx7q-izrb    1
869n-zj3f    1
tuvj-xz3m    1
mev7-qffb    1
cmr9-ue2w    1
ixu8-bvqa    1
hwir-8ay9    1
37wu-kn3g    1
pwjb-9dd5    1
htyp-tqzh    1
2yhn-3dbj    1
3kjc-z9fd    1
mvn7-a28c    1
chnk-j6e5    1
2p2k-iq7f    1
kch9-6p6i    1
mdbi-p4c8    1
8upq-58vz    1
4am6-w6u4    1
4e3w-qire    1
c8jj-hcxj    1
wz8h-dap6    1
uiuh-m69w    1
rifs-n6ib    1
ap62-sav4    1
jnj7-fw37    1
esrk-9vjd    1
6aqe-63uq    1
9pwz-gi5v    1
4j38-u7sj    1
bk6n-e4g7    1
uzf4-3qtt    1
x5dz-rik8    1
3b56-km3g    1
dx5q-y5je    1
xi27-7j3e    1
hxnu-kp2f    1
gvnt-p2w8    1
v4w4-3yz8    1
rt7b-823p    1
8j3i-rjn4    1
xum2-smvh    1
ewkj-ipn7    1
sn6p-34bq    1
5yyk-mqmn    1
f8ak-7nmp    1
xymp-u28i    1
ytai-hin3    1
wtpp-eaj8    1
v56b-yh3u    1
qx2d-46a5    1
94t6-d4wd    1
q56w-zzzm    1
tbmm-ubn9    1
86h6-mdkh    1
3u6n-menq    1
6fg8-f8c5    1
3djr-p9q9    1
gafi-svtb    1
xwky-bmsn    1
c6qj-6kx2    1
33q3-djk8    1
xpi4-stak    1
t2jr-8j7z    1
7i2s-r6pd    1
2chb-kzb6    1
t3uw-qtqc    1
9cn8-g4er    1
4zf4-r52a    1
n53p-giqe    1
ueer-yycc    1
6gtx-i289    1
ekih-pydt    1
smjm-6h6g    1
ph72-axst    1
jycn-t6wi    1
7m6d-cpmt    1
xxfz-y2eq    1
mqbr-wyyb    1
qten-sdpn    1
vcag-iwy7    1
f3th-4ste    1
nnpy-czzx    1
mxmm-svgz    1
hcfi-bvst    1
unz2-68bn    1
x5bw-ax3d    1
v4jc-jbmt    1
gh3v-k494    1
vqzj-5nyt    1
emmy-a4kg    1
u2t6-bfhr    1
ihbp-hi2s    1
vqx7-fwxd    1
qtga-qgdf    1
d3m2-b6we    1
ty6r-gpdz    1
33fk-kb5q    1
fwb5-rzg5    1
fypu-tup4    1
j3me-5ifv    1
9bzu-nqxb    1
gxnn-wthy    1
q2qp-xhnj    1
hwz6-96jc    1
e6e8-qmi7    1
xi5f-mkzt    1
team-3ugz    1
nxw4-ev8w    1
wffy-3uut    1
2ddb-srxn    1
sdgy-egf7    1
rkuy-jxyz    1
u7sb-g482    1
k26c-fz5q    1
n5sw-qzbs    1
ax6t-kdim    1
u9u9-cq2s    1
abdb-jtwc    1
t3k6-vndx    1
nwd2-s3kd    1
rtw9-6tit    1
w2w7-ggyk    1
t5eg-ziay    1
eeb6-6s76    1
gcmk-9nwy    1
x238-vje7    1
4qh9-evw6    1
nymn-sjs9    1
et6s-ufjm    1
uir2-bpe7    1
hyr8-d3v9    1
f325-6r9c    1
u56p-777a    1
6exr-8xkn    1
8ant-mn9d    1
ffjg-bf34    1
h5yt-egtp    1
67vn-ijga    1
m9tc-zgz8    1
sc9q-ryk8    1
bxgy-dnjp    1
bynd-i2hj    1
7bzf-viss    1
dnyf-3m59    1
u4xw-xiec    1
7yta-8qvv    1
x88m-3a2j    1
w6kb-3vsj    1
qifa-4jur    1
2sn7-naei    1
inae-mki6    1
druy-a38s    1
23sa-se52    1
35y-dxds     1
nd6a-59yu    1
cpwf-cznk    1
sys8-yyuf    1
f3vc-vat3    1
sacq-tw7c    1
xiem-he2v    1
p8m4-v33g    1
443p-eijy    1
5b9u-fuzs    1
sn8z-q44h    1
busm-qa5b    1
cjkq-q9ih    1
cdkn-c7n9    1
ue5s-8u8t    1
4jjg-g3yq    1
s7ct-nf65    1
e7wz-djhw    1
35k5-cv8s    1
e4mf-ggwf    1
sshp-3kyq    1
hxf8-ab6k    1
4yw9-a5y6    1
k4uv-yvnk    1
hb4b-8v4q    1
mv3v-5qet    1
6vnq-az4b    1
j6g4-gayk    1
ya69-n6ta    1
2e5i-5hfy    1
bqa5-gr84    1
37uc-bdj5    1
wcvg-8vki    1
p674-r4hf    1
8vnm-57r6    1
7t53-5gfx    1
cj4m-96y8    1
qjuy-fmh4    1
aevh-apr2    1
tfrg-b5pp    1
jc8p-yc8f    1
fifs-d43p    1
q7ri-3nsu    1
yqfw-dg5f    1
xh4c-32wb    1
gu6r-zvv2    1
fjhv-ruxa    1
cuid-432h    1
v5m6-vhha    1
fr27-d5rz    1
rntb-5cdp    1
x5e5-npqm    1
xg8m-4prc    1
p562-ke9a    1
9b7x-qm8d    1
232d-4jxg    1
sxfp-qxs6    1
66zf-qjdd    1
mpff-jbkx    1
74qa-79bk    1
dsw3-mrn4    1
wnau-xrqi    1
npnz-8mvz    1
wx84-he7r    1
7nuk-vzhq    1
icqv-mi3c    1
34aw-ny67    1
3ftn-9s6k    1
7jm9-f28m    1
3qtu-edua    1
g89g-muvw    1
bd44-na6d    1
khe9-7d2c    1
ucnv-vw74    1
bjhg-77mf    1
iuxm-ddzz    1
g598-t929    1
rwak-e74e    1
jd2b-7gyb    1
vne4-cwmy    1
wwhd-vg25    1
Name: count, dtype: int64
-----------------------------------------
Column  Dataset Title
Dataset Title
Zoning in Lake County 2020                                                                                                                  1
2019 Novel Coronavirus COVID-19 (2019-nCoV) Data Repository by Johns Hopkins CSSE                                                           1
Active Business Licenses Denver                                                                                                             1
Activities of Charities Operating in Colorado                                                                                               1
Airports in Colorado                                                                                                                        1
All Special Districts in Colorado                                                                                                           1
Alternative Energy Laws and Incentives in Colorado 2014                                                                                     1
Alternative Fuels and Electric Vehicle Charging Station Locations in Colorado                                                               1
Annual Arrests in Colorado by Crime Type for 243 Police Agencies, 1974-2021                                                                 1
Aquaculture Facilities in Colorado                                                                                                          1
Arrests and Offenses Tool for Colorado                                                                                                      1
Bicycle and Pedestrian Counts in Colorado                                                                                                   1
Bill Information and Position with Income of Lobbyist in Colorado                                                                           1
Biomass Potential in Colorado 2014                                                                                                          1
Biomass Residue in Colorado                                                                                                                 1
Biomethane Potential in Colorado 2014                                                                                                       1
Board Boundaries for Denver Public Schools                                                                                                  1
Body Art Licenses Denver                                                                                                                    1
Breckenridge COVID-19 Business Modifications                                                                                                1
Building Material Sales in Colorado                                                                                                         1
Subdivisions in La Plata County 2019                                                                                                        1
Subdivisions in Larimer County 2019                                                                                                         1
Subdivisions in Pitkin County 2019                                                                                                          1
Taxes by County and Industry in Colorado                                                                                                    1
Total Revenue and Types of Art for Charities Operating in Colorado                                                                          1
Total Revenue of Charities Operating in Colorado                                                                                            1
Trade Names for Businesses in Colorado                                                                                                      1
Trademarks for Businesses in Colorado                                                                                                       1
State Highway On-System Curb Ramps in Colorado                                                                                              1
Streams in Colorado                                                                                                                         1
Subcontractors for Lobbyists in Colorado                                                                                                    1
Subdivisions in Adams County 2019                                                                                                           1
Subdivisions in Boulder County 2019                                                                                                         1
Subdivisions in Broomfield County 2019                                                                                                      1
Subdivisions in Eagle County 2019                                                                                                           1
Subdivisions in Garfield County 2019                                                                                                        1
Solar Direct Normal Irradiance in Colorado 2014                                                                                             1
Solar Global Horizontal Irradiance in Colorado 2014                                                                                         1
Solar Photovoltaic Resource in Colorado                                                                                                     1
Solar PV Capacity Factor in Colorado 2015                                                                                                   1
Solicitation Campaign Supervisors Listed on Solicitation Notices in Colorado                                                                1
State Agency Electricity Usage in Colorado                                                                                                  1
State Agency Fuel Usage in Colorado                                                                                                         1
State Agency Water and Sewer Usage in Colorado                                                                                              1
Septic System Locations in Mesa County Colorado                                                                                             1
Septic Systems in Boulder County Colorado                                                                                                   1
Short-Term Employment Projections in Colorado                                                                                               1
Sign Locations in Colorado                                                                                                                  1
Sign Panels in Colorado                                                                                                                     1
Sign Posts in Colorado                                                                                                                      1
Snow Depths in Northern Colorado                                                                                                            1
Soil Districts in Colorado                                                                                                                  1
Census County Subdivisions SF3 in Colorado 2000                                                                                             1
Census Datasets on Colorado Information Marketplace                                                                                         1
Census Field Descriptions                                                                                                                   1
Census in Colorado 2014                                                                                                                     1
Census in Colorado 2015                                                                                                                     1
Census in Colorado 2016                                                                                                                     1
Census in Colorado 2017                                                                                                                     1
Census in Colorado 2018                                                                                                                     1
Census Counties in Colorado 2019                                                                                                            1
Census Counties in Colorado 2020                                                                                                            1
Census Counties SF1 in Colorado 2000                                                                                                        1
Census Counties SF3 in Colorado 2000                                                                                                        1
Census County Subdivisions in Colorado 2010                                                                                                 1
Census County Subdivisions in Colorado 2011                                                                                                 1
Census County Subdivisions in Colorado 2012                                                                                                 1
Census County Subdivisions SF1 in Colorado 2000                                                                                             1
Census Counties in Colorado 2010                                                                                                            1
Census Counties in Colorado 2012                                                                                                            1
Census Counties in Colorado 2013                                                                                                            1
Census Counties in Colorado 2014                                                                                                            1
Census Counties in Colorado 2015                                                                                                            1
Census Counties in Colorado 2016                                                                                                            1
Census Counties in Colorado 2017                                                                                                            1
Census Counties in Colorado 2018                                                                                                            1
Census Congressional Districts in Colorado 2016                                                                                             1
Census Congressional Districts in Colorado 2017                                                                                             1
Census Congressional Districts in Colorado 2018                                                                                             1
Census Congressional Districts in Colorado 2019                                                                                             1
Census Congressional Districts in Colorado 2020                                                                                             1
Census Core Based Statistical Area in Colorado 2010                                                                                         1
Census Core Based Statistical Area in Colorado 2011                                                                                         1
Census Core Based Statistical Area in Colorado 2012                                                                                         1
Census Tracts in Colorado 2010                                                                                                              1
Census Tracts in Colorado 2011                                                                                                              1
Census Tracts in Colorado 2012                                                                                                              1
Census Tracts in Colorado 2013                                                                                                              1
Census Tracts in Colorado 2014                                                                                                              1
Census Tracts in Colorado 2015                                                                                                              1
Census Tracts in Colorado 2016                                                                                                              1
Census Tracts in Colorado 2017                                                                                                              1
Census School Districts in Colorado 2011                                                                                                    1
Census School Districts in Colorado 2012                                                                                                    1
Census State in Colorado 2010                                                                                                               1
Census State in Colorado 2011                                                                                                               1
Census State in Colorado 2012                                                                                                               1

### Extract Just the Automated Dataset Updates

The Datasets with Automated in their Update Type are the ones we need to check.  We will check for those incorrectly labled (i.e. datasets IN the cron etl process, but not listed as automatic) in different steps.

In [13]:
dfSauto = dfS.loc[dfS["Update Type"].str.lower().str.contains("auto")]

In [14]:
dfSauto["Update Type"].value_counts()

Update Type
Automated - weekly     41
Automated - monthly    26
Automated - daily      19
Name: count, dtype: int64

In [15]:
dfCron = pd.DataFrame(cron4Xref)

In [16]:
mapCron = {
"At 04:00 on Tuesday": "Automated - weekly",
"At 04:00 every day": "Automated - daily",
"At 04:00 every day": "Automated - daily" ,
"At 03:10 every day": "Automated - daily" , 
"At 06:05 on Friday": "Automated - weekly" ,
"At 05:05 every day": "Automated - daily" ,
"At 05:10 every day": "Automated - daily",
"At 08:00 every day": "Automated - daily" ,
"At 04:15 on Tuesday": "Automated - weely" ,
"At 04:30 on Tuesday": "Automated - weekly" ,  
"At 03:00 every day": "Automated - daily",
"At 05:30 on the fourth day of every month": "Automated - monthly",
"At 04:10 on the fourth day of every month": "Automated - monthly",
"At 04:30 on the fourth day of every month": "Automated - monthly",
"At 04:50 on the fourth day of every month": "Automated - monthly",
"At 05:45 on Wednesday": "Automated - weekly",
"At 04:00 on the fourth day of every month": "Automated - monthly",
"At 05:20 on the fourth day of every month": "Automated - monthly",
"At 04:30 on the first day of every month": "Automated - monthly",
"At 03:20 every day": "Automated - daily",
"At 04:20 on the first, the eighth, the 15th, and the 22th day of month": "Automated - weekly",
"At 04:30 on the first, the eighth, the 15th, and the 22th day of month": "Automated - weekly",
"At 04:40 on the first, the eighth, the 15th, and the 22th day of month": "Automated - weekly",
"At 05:00 on Thursday": "Automated - weekly"   
}


dfCron["Update Type"] = dfCron["desc"].map(mapCron)
print(dfCron.isna().sum())

line            0
desc            0
group           0
title          18
Update Type     0
dtype: int64

In [17]:
dfCron["Update Type"].value_counts()

Update Type
Automated - weekly     11
Automated - daily       7
Automated - monthly     7
Automated - weely       1
Name: count, dtype: int64

In [18]:
dfCron.head()

                                                                                                                                                                                                                                                                                                                                              line                desc                     group                                                                                                                                       title         Update Type
0                                                                                                                                                                                                                             10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> $bic_etl_home/general/logs/cron.log  At 03:10 every day                   boulder                                                                                                                                         NaN   Automated - daily
1                                                                                                                                                                                                                              0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> $bic_etl_home/general/logs/cron.log  At 04:00 every day                   catalog                                                                                                                                         NaN   Automated - daily
2                                                                                                                                                                                                              5 6 * * 5 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit 2>> $bic_etl_home/general/logs/cron.log  At 06:05 on Friday   cdos/business/nonprofit                                                                                                                                         NaN  Automated - weekly
3  5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> $bic_etl_home/general/logs/cron.log  At 05:05 every day   cdos/business/nonprofit  "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"   Automated - daily
4                                                                                                                                                                           10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> $bic_etl_home/general/logs/cron.log  At 05:10 every day    cdos/business/business                                                                                                             "Business Entities in Colorado"   Automated - daily

In [19]:
titlesG

{'boulder': ['"Restaurant Inspections in Boulder County"',
  '"Septic Systems in Boulder County Colorado"'],
 'catalog': ['"CIM Catalog Download"'],
 'cdos/business/nonprofit': ['"Federal Tax-Exempt Subsection Codes in Colorado"',
  '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
  '"Charitable Organizations',
  '"Other State Solicitation of Charities',
  '"Charitable Purpose of the Charity in Colorado"',
  '"Paid Solicitor Solicitation Notices in Colorado"',
  '"Campaign Reports for Solicitation Notices to Charities in Colorado"',
  '"Solicitation Campaign Supervisors Listed on Solicitation Notices in Colorado"',
  '"Charity Extension Requests"',
  '"Persons Associated with Charitable Organizations, Paid Solicitors, and Professional Fundraising Consultants in Colorado"',
  '"Other Names a Registered Entity Uses to Solicit Contributions in Colorado"',
  '"Paid Solicitors Disclosed on Charity Registration Forms in Colorado"',
  '"Charitable Solicitation Call Center Locations in Colorado"',
  '"Charities Solicitation Type by Solicitation in Colorado"',
  '"Communication Methods Used in Solicitation Campaigns in Colorado"'],
 'cdos/business/business': ['"Business Entities in Colorado"',
  '"Business Entity Transaction History"',
  '"Trademarks for Businesses in Colorado"',
  '"Trade Names for Businesses in Colorado"',
  '"Master List in Colorado"'],
 'cdos/health': ['"Durable Medical Equipment Suppliers in Colorado"'],
 'cdos/lobbyist': ['"Directory of Lobbyists in Colorado"',
  '"Directory of Lobbyist Clients in Colorado"',
  '"Expenses for Lobbyists in Colorado"',
  '"Characterization of Lobbyist Clients in Colorado"',
  '"Subcontractors for Lobbyists in Colorado"',
  '"Bill Information and Position with Income of Lobbyist in Colorado"'],
 'cdos/government': ['"Current Notaries in Colorado"'],
 'cdos/business/ucc': ['"Uniform Commercial Code (UCC) Collateral Information in Colorado"',
  '"Uniform Commercial Code (UCC) Debtor Information in Colorado"',
  '"Uniform Commercial Code (UCC) Filing Information in Colorado"',
  '"Secured Party Information in Colorado"'],
 'cdot/transportation_road_attributes': ['"Highway Milepoints in Colorado"',
  '"Highway Mileposts in Colorado"',
  '"Highway Routes in Colorado"',
  '"Highways in Colorado"',
  '"Local Roads in Colorado"',
  '"Major Roads in Colorado"',
  '"Scenic Byways in Colorado"'],
 'cdot/transportation_infrastructure': ['"Airports in Colorado"',
  '"Cities in Colorado"',
  '"Counties in Colorado"',
  '"Railroads in Colorado"'],
 'cdot/natural_resources': ['"Lakes in Colorado"', '"Streams in Colorado"'],
 'cdot/tops': ['"CDOT Expenses"',
  '"CDOT Revenues"',
  '"CDOT Payroll Expenditures"'],
 'dola/boundaries': ['"Municipal Annexations in Colorado"',
  '"Municipal Boundaries in Colorado"'],
 'dola/special_districts': ['"Metro Districts in Colorado"',
  '"Parks and Rec Districts in Colorado"',
  '"Fire Districts in Colorado"',
  '"Hospital Districts in Colorado"',
  '"Water and Sanitation Districts in Colorado"',
  '"Library Districts in Colorado"',
  '"School Districts in Colorado"',
  '"Soil Districts in Colorado"',
  '"Cemetery Districts in Colorado"',
  '"All Special Districts in Colorado"'],
 'dola/demographics': ['"Population Projections in Colorado"',
  '"Race Estimates in Colorado"',
  '"Race Forecast in Colorado"'],
 'dora/regulations': ['"Licensed Real Estate Professionals in Colorado"',
  '"Professional and Occupational Licenses in Colorado"'],
 'cdor/revenue_marijuana': ['"Marijuana Sales by County in Colorado"',
  '"Retail Marijuana Sales Tax Revenue by County in Colorado"',
  '"Marijuana Tax and Fee Revenue in Colorado"',
  '"Marijuana Sales Revenue in Colorado"'],
 'cdor/retail_reports': ['"Retail Sales Tax Return History in Colorado"',
  '"Retail Reports by City in Colorado"',
  '"Retail Reports by County in Colorado"',
  '"Retail Reports by Industry and City in Colorado"',
  '"Retail Reports by Industry and County in Colorado"',
  '"Retail Reports by Industry in Colorado"'],
 'cdor/regulations_liquor': ['"Liquor Permits for Special Events in Colorado"',
  '"Liquor Compliance Check Statistics in Colorado"',
  '"Liquor Licenses in Colorado"',
  '"Recently Approved Liquor Licenses in Colorado"',
  '"Recently Expired and Surrendered Liquor Licenses in Colorado"',
  '"Sales Rooms in Colorado"',
  '"Manufacturer Temporary Sales Room Permits in Colorado"'],
 'ceo/useia': ['"Gasoline Prices in Colorado"',
  '"Natural Gas Prices in Colorado"']}

In [20]:
dfCronAll = pd.DataFrame({},columns=dfCron.columns)
dfCronAll.head()

Empty DataFrame
Columns: [line, desc, group, title, Update Type]
Index: []

In [21]:
titles2Skip = dfCron["title"].value_counts().to_dict()
titles2Skip

{'"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"': 1,
 '"Business Entities in Colorado"': 1,
 '"Business Entity Transaction History"': 1,
 '"Master List in Colorado"': 1,
 '"Trade Names for Businesses in Colorado"': 1,
 '"Trademarks for Businesses in Colorado"': 1,
 '"Gasoline Prices in Colorado"': 1,
 '"Natural Gas Prices in Colorado"': 1}

In [22]:
dfCronAll = pd.DataFrame({},columns=dfCron.columns)

for index,row in dfCron.iterrows():
    title=row['title']
    group = row["group"].strip()
    print(group)
    if group in titlesG:
        if isinstance(title,str):
            tmp=dfCron.iloc[index:index+1,:]
            print(tmp.shape)
            dfCronAll=pd.concat([tmp,dfCronAll])
        else:
            for tit in titlesG[group]:
                tit=tit.strip()
                tit=tit.replace('"','')
                print('   ',tit)
                if tit not in titles2Skip:
                    tmp=dfCron.iloc[index:index+1,:]
                    tmp["title"]=tit
                    dfCronAll=pd.concat([tmp,dfCronAll])
                else:
                    print("Skipping ",tit)

boulder
    Restaurant Inspections in Boulder County
    Septic Systems in Boulder County Colorado
catalog
    CIM Catalog Download
cdos/business/nonprofit
    Federal Tax-Exempt Subsection Codes in Colorado
    Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado
    Charitable Organizations
    Other State Solicitation of Charities
    Charitable Purpose of the Charity in Colorado
    Paid Solicitor Solicitation Notices in Colorado
    Campaign Reports for Solicitation Notices to Charities in Colorado
    Solicitation Campaign Supervisors Listed on Solicitation Notices in Colorado
    Charity Extension Requests
    Persons Associated with Charitable Organizations, Paid Solicitors, and Professional Fundraising Consultants in Colorado
    Other Names a Registered Entity Uses to Solicit Contributions in Colorado
    Paid Solicitors Disclosed on Charity Registration Forms in Colorado
    Charitable Solicitation Call Center Locations in Colorado
    Charities Solicitation Type by Solicitation in Colorado
    Communication Methods Used in Solicitation Campaigns in Colorado
cdos/business/nonprofit
(1, 5)
cdos/business/business
(1, 5)
cdos/business/business
(1, 5)
cdos/health
    Durable Medical Equipment Suppliers in Colorado
cdos/lobbyist
    Directory of Lobbyists in Colorado
    Directory of Lobbyist Clients in Colorado
    Expenses for Lobbyists in Colorado
    Characterization of Lobbyist Clients in Colorado
    Subcontractors for Lobbyists in Colorado
    Bill Information and Position with Income of Lobbyist in Colorado
cdos/government
    Current Notaries in Colorado
cdos/business/business
(1, 5)
cdos/business/business
(1, 5)
cdos/business/business
(1, 5)
cdos/business/ucc
    Uniform Commercial Code (UCC) Collateral Information in Colorado
    Uniform Commercial Code (UCC) Debtor Information in Colorado
    Uniform Commercial Code (UCC) Filing Information in Colorado
    Secured Party Information in Colorado
cdot/transportation_road_attributes
    Highway Milepoints in Colorado
    Highway Mileposts in Colorado
    Highway Routes in Colorado
    Highways in Colorado
    Local Roads in Colorado
    Major Roads in Colorado
    Scenic Byways in Colorado
cdot/transportation_infrastructure
    Airports in Colorado
    Cities in Colorado
    Counties in Colorado
    Railroads in Colorado
cdot/natural_resources
    Lakes in Colorado
    Streams in Colorado
cdot/tops
    CDOT Expenses
    CDOT Revenues
    CDOT Payroll Expenditures
dola/boundaries
    Municipal Annexations in Colorado
    Municipal Boundaries in Colorado
dola/special_districts
    Metro Districts in Colorado
    Parks and Rec Districts in Colorado
    Fire Districts in Colorado
    Hospital Districts in Colorado
    Water and Sanitation Districts in Colorado
    Library Districts in Colorado
    School Districts in Colorado
    Soil Districts in Colorado
    Cemetery Districts in Colorado
    All Special Districts in Colorado
dola/demographics
    Population Projections in Colorado
    Race Estimates in Colorado
    Race Forecast in Colorado
dora/regulations
    Licensed Real Estate Professionals in Colorado
    Professional and Occupational Licenses in Colorado
cdor/revenue_marijuana
    Marijuana Sales by County in Colorado
    Retail Marijuana Sales Tax Revenue by County in Colorado
    Marijuana Tax and Fee Revenue in Colorado
    Marijuana Sales Revenue in Colorado
cdor/retail_reports
    Retail Sales Tax Return History in Colorado
    Retail Reports by City in Colorado
    Retail Reports by County in Colorado
    Retail Reports by Industry and City in Colorado
    Retail Reports by Industry and County in Colorado
    Retail Reports by Industry in Colorado
cdor/regulations_liquor
    Liquor Permits for Special Events in Colorado
    Liquor Compliance Check Statistics in Colorado
    Liquor Licenses in Colorado
    Recently Approved Liquor Licenses in Colorado
    Recently Expired and Surrendered Liquor Licenses in Colorado
    Sales Rooms in Colorado
    Manufacturer Temporary Sales Room Permits in Colorado
ceo/useia
(1, 5)
ceo/useia
(1, 5)

In [23]:
print(dfCronAll.shape)

(88, 5)

In [24]:
print(dfCronAll['title'].value_counts().sort_index())

title
"Business Entities in Colorado"                                                                                                               1
"Business Entity Transaction History"                                                                                                         1
"Gasoline Prices in Colorado"                                                                                                                 1
"Master List in Colorado"                                                                                                                     1
"Natural Gas Prices in Colorado"                                                                                                              1
"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"    1
"Trade Names for Businesses in Colorado"                                                                                                      1
"Trademarks for Businesses in Colorado"                                                                                                       1
Airports in Colorado                                                                                                                          1
All Special Districts in Colorado                                                                                                             1
Bill Information and Position with Income of Lobbyist in Colorado                                                                             1
CDOT Expenses                                                                                                                                 1
CDOT Payroll Expenditures                                                                                                                     1
CDOT Revenues                                                                                                                                 1
CIM Catalog Download                                                                                                                          1
Campaign Reports for Solicitation Notices to Charities in Colorado                                                                            1
Cemetery Districts in Colorado                                                                                                                1
Characterization of Lobbyist Clients in Colorado                                                                                              1
Charitable Organizations                                                                                                                      1
Charitable Purpose of the Charity in Colorado                                                                                                 1
Charitable Solicitation Call Center Locations in Colorado                                                                                     1
Charities Solicitation Type by Solicitation in Colorado                                                                                       1
Charity Extension Requests                                                                                                                    1
Cities in Colorado                                                                                                                            1
Communication Methods Used in Solicitation Campaigns in Colorado                                                                              1
Counties in Colorado                                                                                                                          1
Current Notaries in Colorado                                                                                                                  1
Directory of Lobbyist Clients in Colorado                                                                                                     1
Directory of Lobbyists in Colorado                                                                                                            1
Durable Medical Equipment Suppliers in Colorado                                                                                               1
Expenses for Lobbyists in Colorado                                                                                                            1
Federal Tax-Exempt Subsection Codes in Colorado                                                                                               1
Fire Districts in Colorado                                                                                                                    1
Highway Milepoints in Colorado                                                                                                                1
Highway Mileposts in Colorado                                                                                                                 1
Highway Routes in Colorado                                                                                                                    1
Highways in Colorado                                                                                                                          1
Hospital Districts in Colorado                                                                                                                1
Lakes in Colorado                                                                                                                             1
Library Districts in Colorado                                                                                                                 1
Licensed Real Estate Professionals in Colorado                                                                                                1
Liquor Compliance Check Statistics in Colorado                                                                                                1
Liquor Licenses in Colorado                                                                                                                   1
Liquor Permits for Special Events in Colorado                                                                                                 1
Local Roads in Colorado                                                                                                                       1
Major Roads in Colorado                                                                                                                       1
Manufacturer Temporary Sales Room Permits in Colorado                                                                                         1
Marijuana Sales Revenue in Colorado                                                                                                           1
Marijuana Sales by County in Colorado                                                                                                         1
Marijuana Tax and Fee Revenue in Colorado                                                                                                     1
Metro Districts in Colorado                                                                                                                   1
Municipal Annexations in Colorado                                                                                                             1
Municipal Boundaries in Colorado                                                                                                              1
Other Names a Registered Entity Uses to Solicit Contributions in Colorado                                                                     1
Other State Solicitation of Charities                                                                                                         1
Paid Solicitor Solicitation Notices in Colorado                                                                                               1
Paid Solicitors Disclosed on Charity Registration Forms in Colorado                                                                           1
Parks and Rec Districts in Colorado                                                                                                           1
Persons Associated with Charitable Organizations, Paid Solicitors, and Professional Fundraising Consultants in Colorado                       1
Population Projections in Colorado                                                                                                            1
Professional and Occupational Licenses in Colorado                                                                                            1
Race Estimates in Colorado                                                                                                                    1
Race Forecast in Colorado                                                                                                                     1
Railroads in Colorado                                                                                                                         1
Recently Approved Liquor Licenses in Colorado                                                                                                 1
Recently Expired and Surrendered Liquor Licenses in Colorado                                                                                  1
Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado      1
Restaurant Inspections in Boulder County                                                                                                      1
Retail Marijuana Sales Tax Revenue by County in Colorado                                                                                      1
Retail Reports by City in Colorado                                                                                                            1
Retail Reports by County in Colorado                                                                                                          1
Retail Reports by Industry and City in Colorado                                                                                               1
Retail Reports by Industry and County in Colorado                                                                                             1
Retail Reports by Industry in Colorado                                                                                                        1
Retail Sales Tax Return History in Colorado                                                                                                   1
Sales Rooms in Colorado                                                                                                                       1
Scenic Byways in Colorado                                                                                                                     1
School Districts in Colorado                                                                                                                  1
Secured Party Information in Colorado                                                                                                         1
Septic Systems in Boulder County Colorado                                                                                                     1
Soil Districts in Colorado                                                                                                                    1
Solicitation Campaign Supervisors Listed on Solicitation Notices in Colorado                                                                  1
Streams in Colorado                                                                                                                           1
Subcontractors for Lobbyists in Colorado                                                                                                      1
Uniform Commercial Code (UCC) Collateral Information in Colorado                                                                              1
Uniform Commercial Code (UCC) Debtor Information in Colorado                                                                                  1
Uniform Commercial Code (UCC) Filing Information in Colorado                                                                                  1
Water and Sanitation Districts in Colorado                                                                                                    1
Name: count, dtype: int64

In [25]:
dfCronAll['group'].value_counts().sort_index()

group
 boulder                                 2
 catalog                                 1
 cdor/regulations_liquor                 7
 cdor/retail_reports                     6
 cdor/revenue_marijuana                  4
 cdos/business/business                  5
 cdos/business/nonprofit                16
 cdos/business/ucc                       4
 cdos/government                         1
 cdos/health                             1
 cdos/lobbyist                           6
 cdot/natural_resources                  2
 cdot/tops                               3
 cdot/transportation_infrastructure      4
 cdot/transportation_road_attributes     7
 ceo/useia                               2
 dola/boundaries                         2
 dola/demographics                       3
 dola/special_districts                 10
 dora/regulations                        2
Name: count, dtype: int64

In [26]:
dfCronAll.head()

                                                                                                                                                         line                                                                    desc                     group                                                         title         Update Type
25  0 5 * * 4 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Natural Gas Prices in Colorado" 2>> $bic_etl_home/general/logs/cron.log                                                    At 05:00 on Thursday                 ceo/useia                              "Natural Gas Prices in Colorado"  Automated - weekly
24     0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Gasoline Prices in Colorado" 2>> $bic_etl_home/general/logs/cron.log                                                     At 04:00 on Tuesday                 ceo/useia                                 "Gasoline Prices in Colorado"  Automated - weekly
23               40 4 1,8,15,22 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/regulations_liquor 2>> $bic_etl_home/general/logs/cron.log  At 04:40 on the first, the eighth, the 15th, and the 22th day of month   cdor/regulations_liquor         Manufacturer Temporary Sales Room Permits in Colorado  Automated - weekly
23               40 4 1,8,15,22 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/regulations_liquor 2>> $bic_etl_home/general/logs/cron.log  At 04:40 on the first, the eighth, the 15th, and the 22th day of month   cdor/regulations_liquor                                       Sales Rooms in Colorado  Automated - weekly
23               40 4 1,8,15,22 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/regulations_liquor 2>> $bic_etl_home/general/logs/cron.log  At 04:40 on the first, the eighth, the 15th, and the 22th day of month   cdor/regulations_liquor  Recently Expired and Surrendered Liquor Licenses in Colorado  Automated - weekly

### Get 4x4 for Cron Datasets From SIJ

In [27]:
def init():
    
    groups = []
    desktop = pathlib.Path("/home/joe/bic_etl")
    runEtls = []
    dataSets = []
    info = {}
    files4Datasets={}
    # .rglob() produces a generator too
    desktop.rglob("*")
    files = list(desktop.rglob("*"))
# Which you can wrap in a list() constructor to materialize
    for ff in files:
            if (str(ff).split("/")[-1] == "run_etl.json"):     
                runEtls.append(ff)
                
            
 #   print(f"{len(runEtls)} run_etl.json files found")    
    datasets = []
    dataSetsEtl={}
    dataSets = []
    groups = []
    for file in runEtls:
      f = open(file,"r")
      data = json.load(f)
   #   files[data['title']]=ff
      dataSets.append(data)
      for dat in data:
          if 'title' in dat:
                files4Datasets[dat['title']]=file
                
                
    cron4x4Titles = {}
    cronTitle4x4s = {}
    
    
    for data in dataSets:
        for ds in data:      
     #       title=ds['title']
            if 'load' in ds:
                if 'file' in ds['load']:
                    title=ds['title']
                    file=str(files4Datasets[title])
                    ne = file.rfind("/")
                    loadFile = ds['load']['file']
                    if loadFile.find('/') > -1:
                       spl=loadFile.split("/")
                       loadFile=spl[-1]

                    fileSIJ = f"{file[:ne]}/scripts/datasync/{loadFile}"
                    f = open(fileSIJ,"r")
                    sij = json.load(f)
                    cronTitle4x4s[title] = sij['datasetID'].strip()
                    cron4x4Titles[sij['datasetID'].strip()] = title
                    
    
    return cron4x4Titles,cronTitle4x4s
        

cron4x4Titles,cronTitle4x4s = init()

In [28]:
#  Remove double quotes from title names
dfCronAll["title"] = dfCronAll["title"].str.replace('"','')

In [29]:
def mapTitle(row):
    title=row['title']
    if title in cronTitle4x4s:
        w4x4= cronTitle4x4s[title]
    else:
        w4x4 = ''
    return w4x4
dfCronAll['4x4'] = dfCronAll.apply(mapTitle,axis=1)

In [30]:
dfCronAll['4x4'].value_counts()

4x4
             27
37wu-kn3g     2
8pk9-mh2i     1
9pwz-gi5v     1
d4s4-xqg6     1
htyp-tqzh     1
ier5-5ms2     1
kapc-ib6e     1
d6t8-xish     1
6kn4-89kh     1
fe4v-h3pk     1
k3gg-hhc8     1
e4ky-6g2n     1
x8tb-f3vh     1
2yhn-3dbj     1
p6y8-s74x     1
54t3-n5uh     1
v9m8-x8dh     1
j7a3-jgd3     1
7s5z-vewr     1
3sm5-jtur     1
4zse-6bnw     1
ab5h-juwk     1
wv7f-qjj7     1
q5vp-adf3     1
rkmy-yymq     1
2kvt-7ybu     1
n5ku-eixc     1
pwjb-9dd5     1
6aqe-63uq     1
ap62-sav4     1
8upq-58vz     1
wffy-3uut     1
d3m2-b6we     1
u7sb-g482     1
ej2c-jkvh     1
4am6-w6u4     1
gxnn-wthy     1
gcmk-9nwy     1
g89g-muvw     1
eqsm-7ah7     1
35k5-cv8s     1
bqa5-gr84     1
s7ct-nf65     1
k4uv-yvnk     1
casm-dbbj     1
4ykn-tg5h     1
w6kb-3vsj     1
34aw-ny67     1
wwhd-vg25     1
wwbh-7bpa     1
q2av-rpr5     1
mr4v-jz8u     1
icqv-mi3c     1
hyr8-d3v9     1
fdcw-ei67     1
ew9y-6tv9     1
7jm9-f28m     1
2z9k-uy4q     1
ihbp-hi2s     1
tuvj-xz3m     1
Name: count, dtype: int64

In [32]:
dfSauto.columns

Index(['Socrata Link', 'Dataset Title', 'State Steward', 'Category', 'Type', 'Update Type', 'Update Schedule', 'Update Method', 'Source Update Schedule', 'cimAllData Updates', 'Complexity'], dtype='object')

In [33]:
dfSauto.head()

   Socrata Link                                                      Dataset Title              State Steward           Category               Type          Update Type           Update Schedule                Update Method Source Update Schedule cimAllData Updates Complexity
1     s9wt-dsfz                                    Active Business Licenses Denver  City and county of Denver           Business         Businesses    Automated - daily  Every day after midnight  Automated on Socrata by BIC               Annually                  1
3     x5bw-ax3d                                               Airports in Colorado                       CDOT     Transportation     Infrastructure  Automated - monthly              4th of month  Automated by Staging Server                                        25
4     dm2a-biqr                                  All Special Districts in Colorado                       DOLA  Local Aggregation  Special Districts  Automated - monthly              4th of month  Automated by Staging Server                                        25
11    gxnn-wthy  Bill Information and Position with Income of Lobbyist in Colorado                       CDOS           Lobbyist              Bills   Automated - weekly        Tuesday after 12AM  Automated by Staging Server                                        38
20    4ykn-tg5h                                      Business Entities in Colorado                       CDOS           Business         Businesses    Automated - daily  Every day after midnight  Automated by Staging Server                                         1

In [34]:
dfCronAll.head()

                                                                                                                                                         line                                                                    desc                     group                                                         title         Update Type        4x4
25  0 5 * * 4 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Natural Gas Prices in Colorado" 2>> $bic_etl_home/general/logs/cron.log                                                    At 05:00 on Thursday                 ceo/useia                                Natural Gas Prices in Colorado  Automated - weekly  e4ky-6g2n
24     0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Gasoline Prices in Colorado" 2>> $bic_etl_home/general/logs/cron.log                                                     At 04:00 on Tuesday                 ceo/useia                                   Gasoline Prices in Colorado  Automated - weekly  8pk9-mh2i
23               40 4 1,8,15,22 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/regulations_liquor 2>> $bic_etl_home/general/logs/cron.log  At 04:40 on the first, the eighth, the 15th, and the 22th day of month   cdor/regulations_liquor         Manufacturer Temporary Sales Room Permits in Colorado  Automated - weekly  d4s4-xqg6
23               40 4 1,8,15,22 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/regulations_liquor 2>> $bic_etl_home/general/logs/cron.log  At 04:40 on the first, the eighth, the 15th, and the 22th day of month   cdor/regulations_liquor                                       Sales Rooms in Colorado  Automated - weekly  9pwz-gi5v
23               40 4 1,8,15,22 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/regulations_liquor 2>> $bic_etl_home/general/logs/cron.log  At 04:40 on the first, the eighth, the 15th, and the 22th day of month   cdor/regulations_liquor  Recently Expired and Surrendered Liquor Licenses in Colorado  Automated - weekly  pwjb-9dd5

## Analysis

### Compare Cron to Dataset Tracker

In [35]:
nbad=0
nmiss=0
ngood=0
n2many=0
miss={}
dfSauto['Cron Update'] = ""
dfSauto['Result'] = ""

for index,row in dfSauto.iterrows():
#    print(row["Update Type"],row["Dataset Title"])
    titleI=row["Dataset Title"]
    c4x4=row['Socrata Link']
    update=row["Update Type"]
    tmp = dfCronAll.loc[(dfCronAll["title"].str.lower() == titleI.lower()) | (dfCronAll['4x4'] == c4x4)]
    if tmp.shape[0] == 1:
        upt = tmp["Update Type"].values.tolist()[0]
        dfSauto.loc[index,"Con Update"]=upt

        if upt != update:
           print("BAD")
           print(titleI,upt,update,row['State Steward'])
      #     print(tmp.head())
           dfSauto.loc[index,"Result"]="BAD"
           nbad+=1
        else:
            print("GOOD ")
            print(titleI,upt,update,row['State Steward'])
      #      print(tmp.head())
            dfSauto.loc[index,"Result"]="GOOD"
                  
            ngood+=1
    elif tmp.shape[0] == 0:
        print("MISS",titleI)
        
        miss[titleI]=c4x4
      
   #    print(tmp.head())
        nmiss+=1
    else:
        print("TOO MANY",titleI)
        print(tmp.head())
        n2many+=1
        
        
print("SUMMARY")
print(f"GOOD {ngood}")
print(f"BAD {nbad}")
print(f"MISS {nmiss}")
print(f"Too Many {n2many}")

MISS Active Business Licenses Denver
GOOD
Airports in Colorado Automated - monthly Automated - monthly CDOT
GOOD
All Special Districts in Colorado Automated - monthly Automated - monthly DOLA
BAD
Bill Information and Position with Income of Lobbyist in Colorado Automated - weely Automated - weekly CDOS
GOOD
Business Entities in Colorado Automated - daily Automated - daily CDOS
GOOD
Business Entity Transaction History Automated - daily Automated - daily CDOS
MISS Business Improvement Districts Denver
GOOD
Campaign Reports for Solicitation Notices to Charities in Colorado Automated - weekly Automated - weekly CDOS
GOOD
CDOT Expenses   Automated - weekly Automated - weekly CDOT
GOOD
CDOT Payroll Expenditures   Automated - weekly Automated - weekly CDOT
GOOD
CDOT Revenues   Automated - weekly Automated - weekly CDOT
GOOD
Cemetery Districts in Colorado Automated - monthly Automated - monthly DOLA
BAD
Characterization of Lobbyist Clients in Colorado Automated - weely Automated - weekly CDOS
MISS Charitable Organizations’ Offices in Colorado
GOOD
Charitable Purpose of the Charity in Colorado Automated - weekly Automated - weekly CDOS
GOOD
Charitable Solicitation Call Center Locations in Colorado Automated - weekly Automated - weekly CDOS
GOOD
Charities Solicitation Type by Solicitation in Colorado Automated - weekly Automated - weekly CDOS
GOOD
Charity Extension Requests Automated - weekly Automated - weekly CDOS
GOOD
Cities in Colorado Automated - monthly Automated - monthly CDOT
GOOD
Communication Methods Used in Solicitation Campaigns in Colorado Automated - weekly Automated - weekly CDOS
GOOD
Counties in Colorado Automated - monthly Automated - monthly CDOT
GOOD
Current Notaries in Colorado Automated - weekly Automated - weekly CDOS
MISS Current Surface Water Conditions in Colorado
BAD
Directory of Lobbyist Clients in Colorado Automated - weely Automated - weekly CDOS
BAD
Directory of Lobbyists in Colorado Automated - weely Automated - weekly CDOS
GOOD
Durable Medical Equipment Suppliers in Colorado Automated - weekly Automated - weekly CDOS
BAD
Expenses for Lobbyists in Colorado Automated - weely Automated - weekly CDOS
GOOD
Federal Tax-Exempt Subsection Codes in Colorado Automated - weekly Automated - weekly CDOS
GOOD
Fire Districts in Colorado Automated - monthly Automated - monthly DOLA
MISS Food Stores in Denver
GOOD
Gasoline Prices in Colorado Automated - weekly Automated - weekly CEO
MISS General Improvement Districts Denver
GOOD
Highway Milepoints in Colorado Automated - monthly Automated - monthly CDOT
GOOD
Highway Mileposts in Colorado Automated - monthly Automated - monthly CDOT
GOOD
Highway Routes in Colorado Automated - monthly Automated - monthly CDOT
GOOD
Highways in Colorado Automated - monthly Automated - monthly CDOT
GOOD
Hospital Districts in Colorado Automated - monthly Automated - monthly DOLA
GOOD
Lakes in Colorado Automated - monthly Automated - monthly CDOT
GOOD
Library Districts in Colorado Automated - monthly Automated - monthly DOLA
GOOD
Licensed Real Estate Professionals in Colorado Automated - daily Automated - daily DORA
GOOD
Liquor Compliance Check Statistics in Colorado Automated - weekly Automated - weekly CDOR
GOOD
Liquor Licenses in Colorado Automated - weekly Automated - weekly CDOR
GOOD
Liquor Permits for Special Events in Colorado Automated - weekly Automated - weekly CDOR
GOOD
Local Roads in Colorado Automated - monthly Automated - monthly CDOT
GOOD
Major Roads in Colorado Automated - monthly Automated - monthly CDOT
GOOD
Manufacturer Temporary Sales Room Permits in Colorado Automated - weekly Automated - weekly CDOR
GOOD
Marijuana Sales by County in Colorado Automated - weekly Automated - weekly CDOR
GOOD
Marijuana Tax and Fee Revenue in Colorado
 Automated - weekly Automated - weekly CDOR
GOOD
Master List in Colorado Automated - monthly Automated - monthly CDOS
GOOD
Metro Districts in Colorado Automated - monthly Automated - monthly DOLA
GOOD
Municipal Annexations in Colorado Automated - monthly Automated - monthly DOLA
GOOD
Municipal Boundaries in Colorado Automated - monthly Automated - monthly DOLA
GOOD
Natural Gas Prices in Colorado Automated - weekly Automated - weekly CEO
MISS Neighborhood Business Revitalization Corridors Denver
GOOD
Other Names a Registered Entity Uses to Solicit Contributions in Colorado Automated - weekly Automated - weekly CDOS
MISS Other State Solicitation of Charities’ Registrants in Colorado
GOOD
Paid Solicitor Solicitation Notices in Colorado Automated - weekly Automated - weekly CDOS
GOOD
Paid Solicitors Disclosed on Charity Registration Forms in Colorado Automated - weekly Automated - weekly CDOS
MISS Parks and Rec Districts in Colorado
GOOD
Persons Associated with Charitable Organizations, Paid Solicitors, and Professional Fundraising Consultants in Colorado Automated - weekly Automated - weekly CDOS
MISS Points of Interest in Denver
GOOD
Professional and Occupational Licenses in Colorado Automated - daily Automated - daily DORA
GOOD
Railroads in Colorado Automated - monthly Automated - monthly CDOT
GOOD
Recently Approved Liquor Licenses in Colorado Automated - weekly Automated - weekly CDOR
GOOD
Recently Expired and Surrendered Liquor Licenses in Colorado Automated - weekly Automated - weekly CDOR
TOO MANY Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado
                                                                                                                                                                                                                                                                                                                                              line                desc                     group                                                                                                                                     title         Update Type        4x4
3  5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> $bic_etl_home/general/logs/cron.log  At 05:05 every day   cdos/business/nonprofit  Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado   Automated - daily  37wu-kn3g
2                                                                                                                                                                                                              5 6 * * 5 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit 2>> $bic_etl_home/general/logs/cron.log  At 06:05 on Friday   cdos/business/nonprofit  Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado  Automated - weekly  37wu-kn3g
GOOD
Restaurant Inspections in Boulder County Automated - daily Automated - daily BOCO
GOOD
Retail Marijuana Sales Tax Revenue by County in Colorado Automated - weekly Automated - weekly CDOR
GOOD
Sales Rooms in Colorado Automated - weekly Automated - weekly CDOR
GOOD
Scenic Byways in Colorado Automated - monthly Automated - monthly CDOT
GOOD
School Districts in Colorado Automated - monthly Automated - monthly DOLA
GOOD
Secured Party Information in Colorado Automated - daily Automated - daily CDOS
GOOD
Septic Systems in Boulder County Colorado Automated - daily Automated - daily BOCO
GOOD
Soil Districts in Colorado Automated - monthly Automated - monthly DOLA
GOOD
Solicitation Campaign Supervisors Listed on Solicitation Notices in Colorado Automated - weekly Automated - weekly CDOS
GOOD
Streams in Colorado Automated - monthly Automated - monthly CDOT
BAD
Subcontractors for Lobbyists in Colorado Automated - weely Automated - weekly CDOS
GOOD
Trade Names for Businesses in Colorado Automated - weekly Automated - weekly CDOS
GOOD
Trademarks for Businesses in Colorado Automated - weekly Automated - weekly CDOS
MISS Transparency Online Project (TOPS) - State Government Revenue and Expenditures in Colorado
MISS Tree Canopy Assesment 2013 Denver
MISS Tree Inventory Denver
GOOD
Uniform Commercial Code (UCC) Collateral Information in Colorado Automated - daily Automated - daily CDOS
GOOD
Uniform Commercial Code (UCC) Debtor Information in Colorado Automated - daily Automated - daily CDOS
GOOD
Uniform Commercial Code (UCC) Filing Information in Colorado Automated - daily Automated - daily CDOS
GOOD
Water and Sanitation Districts in Colorado Automated - monthly Automated - monthly DOLA
SUMMARY
GOOD 66
BAD 6
MISS 13
Too Many 1

In [36]:
dfSauto.to_csv("results.csv",index=False)

In [37]:
dfSauto.head()

   Socrata Link                                                      Dataset Title              State Steward           Category               Type          Update Type           Update Schedule                Update Method Source Update Schedule cimAllData Updates Complexity Cron Update Result           Con Update
1     s9wt-dsfz                                    Active Business Licenses Denver  City and county of Denver           Business         Businesses    Automated - daily  Every day after midnight  Automated on Socrata by BIC               Annually                  1                                                NaN
3     x5bw-ax3d                                               Airports in Colorado                       CDOT     Transportation     Infrastructure  Automated - monthly              4th of month  Automated by Staging Server                                        25                          GOOD  Automated - monthly
4     dm2a-biqr                                  All Special Districts in Colorado                       DOLA  Local Aggregation  Special Districts  Automated - monthly              4th of month  Automated by Staging Server                                        25                          GOOD  Automated - monthly
11    gxnn-wthy  Bill Information and Position with Income of Lobbyist in Colorado                       CDOS           Lobbyist              Bills   Automated - weekly        Tuesday after 12AM  Automated by Staging Server                                        38                           BAD    Automated - weely
20    4ykn-tg5h                                      Business Entities in Colorado                       CDOS           Business         Businesses    Automated - daily  Every day after midnight  Automated by Staging Server                                         1                          GOOD    Automated - daily

###  Check Dataset Titles Not Found in Cron

In the analysis above, we start with teh titles found in the Dataset Tracker and looks for those in the cron listings.  These are the ones we did not find in the cron listing.

In [38]:
titlesDT = dfSauto["Dataset Title"].value_counts().to_dict()
titlesCron = {title.lower().strip().replace('"',''):group  for title,group in sorted(titles.items())}

In [39]:
dfSauto.columns

Index(['Socrata Link', 'Dataset Title', 'State Steward', 'Category', 'Type', 'Update Type', 'Update Schedule', 'Update Method', 'Source Update Schedule', 'cimAllData Updates', 'Complexity', 'Cron Update', 'Result', 'Con Update'], dtype='object')

In [40]:
fixed={}
# fixed['']=1
fixed['Highways in Colorado']=1
fixed['CDOT Payroll Expenditures  ']=1
fixed['Sign Locations in Colorado']=1
fixed['Sign Panels in Colorado']=1
fixed['Sign Posts in Colorado']=1
fixed['Total Revenue and Types of Art for Charities Operating in Colorado']=1
fixed['IRS Filing Information for Charities Operating in Colorado']=1
fixed['Activities of Charities Operating in Colorado']=1
fixed['Conservation Easements for Charities Operating in Colorado']=1
fixed['Purpose and Operational Size of Charities Operating in Colorado']=1
fixed['Expenses of Charities Operating in Colorado']=1
fixed['Expenses of Charities Filing IRS Form EZ Operating in Colorado']=1
fixed['Septic System Locations in Mesa County Colorado']=1
fixed['Charitable Organizations’ Offices in Colorado']=1
fixed['Other State Solicitation of Charities’ Registrants in Colorado']=1
fixed['Total Revenue of Charities Operating in Colorado']=1
fixed['Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado']=1
fixed['Fundraising Revenue of Charities Operating in Colorado']=1
fixed['Other Names a Registered Entity Uses to Solicit Contributions in Colorado']=1

In [41]:
nmiss=0
#for title in sorted(titlesDT.keys()):
for index,row in dfSauto.sort_values(by="State Steward").iterrows():
    title=row["Dataset Title"].lower().strip()
    w4x4 = row['Socrata Link']
#    print(f":{title}:")
    if title.strip() not in titlesCron and row["Dataset Title"] not in fixed:
        print(f"Length:{len(title)} Steward:{row['State Steward']}  Cat:{row['Category']}  Type:{row['Type']} Update Method: {row['Update Method']}  Days Updated:{row['cimAllData Updates']}")
        print(f"4x4: {w4x4}")
        print(f"   Title:{row['Dataset Title']}: ")
        nmiss+=1
        tmp={}
        groups=[]
        groups.append(f"{row['State Steward'].lower().strip()}/{row['Category'].lower().strip()}/{row['Type'].lower().strip()}")
        groups.append(f"{row['State Steward'].lower().strip()}/{row['Category'].lower().strip()}")
        groups.append(f"{row['State Steward'].lower().strip()}")
        
        for titleCron in titlesCron.keys():
            R=difflib.SequenceMatcher(lambda x: x == " ", a=title, b=titleCron)  
            tmp[titleCron]=R.ratio()
        tmp = {k: v for k, v in sorted(tmp.items(), key=lambda x: x[1],reverse=True)}
        ncnt=0
        for key,val in tmp.items():
            ncnt+=1
            if ncnt < 5:
                print(f"{len(key):3d} {val:.2f} {key}")
        print("-------------------")
        tmp = dfCronAll.loc[dfCronAll['group'].str.strip().isin(groups)]
        print("Titles in Cron Group: ",tmp.shape[0])
        for index,row in tmp.sort_values(by="title").iterrows():
            c4x4=row['4x4']
            titl=row['title']
            print(c4x4,titl)
        print("\n===============================================================================\n")
            
            
        
print("MISSED ",nmiss)

Length:33 Steward:City and county of Denver  Cat:Natural Resources  Type:Natural Features Update Method: Automated on Socrata by BIC  Days Updated:1
4x4: xi27-7j3e
   Title:Tree Canopy Assesment 2013 Denver:
 47 0.33 durable medical equipment suppliers in colorado
 38 0.31 trade names for businesses in colorado
 13 0.30 cdot expenses
 13 0.30 cdot revenues
-------------------
Titles in Cron Group:  0

===============================================================================

Length:21 Steward:City and county of Denver  Cat:Natural Resources  Type:Natural Features Update Method: Automated on Socrata by BIC  Days Updated:1
4x4: wz8h-dap6
   Title:Tree Inventory Denver:
 19 0.45 streams in colorado
 13 0.41 cdot revenues
 18 0.41 cities in colorado
 20 0.39 counties in colorado
-------------------
Titles in Cron Group:  0

===============================================================================

Length:31 Steward:City and county of Denver  Cat:Business  Type:Businesses Update Method: Automated on Socrata by BIC  Days Updated:1
4x4: s9wt-dsfz
   Title:Active Business Licenses Denver:
 29 0.50 business entities in colorado
 27 0.45 liquor licenses in colorado
 37 0.44 trademarks for businesses in colorado
 38 0.43 trade names for businesses in colorado
-------------------
Titles in Cron Group:  0

===============================================================================

Length:28 Steward:City and county of Denver  Cat:Economic Development  Type:Tourism Update Method: Automated on Socrata by BIC  Days Updated:1
4x4: y6w6-igw6
   Title:Points of Interest in Denver:
 23 0.43 master list in colorado
 30 0.38 highway milepoints in colorado
 46 0.35 licensed real estate professionals in colorado
 30 0.34 cemetery districts in colorado
-------------------
Titles in Cron Group:  0

===============================================================================

Length:53 Steward:City and county of Denver  Cat:Economic Development  Type:Economic Zones Update Method: Automated on Socrata by BIC  Days Updated:1
4x4: ifza-iedd
   Title:Neighborhood Business Revitalization Corridors Denver:
 29 0.51 business entities in colorado
 38 0.48 trade names for businesses in colorado
 35 0.48 business entity transaction history
 37 0.47 trademarks for businesses in colorado
-------------------
Titles in Cron Group:  0

===============================================================================

Length:37 Steward:City and county of Denver  Cat:Economic Development  Type:Economic Zones Update Method: Automated on Socrata by BIC  Days Updated:1
4x4: qtga-qgdf
   Title:Business Improvement Districts Denver:
 30 0.48 cemetery districts in colorado
 27 0.47 metro districts in colorado
 30 0.45 hospital districts in colorado
 35 0.44 business entity transaction history
-------------------
Titles in Cron Group:  0

===============================================================================

Length:21 Steward:City and county of Denver  Cat:Business  Type:Businesses Update Method: Automated by Staging Server  Days Updated:1
4x4: hysf-mrke
   Title:Food Stores in Denver:
 25 0.43 race forecast in colorado
 13 0.41 cdot revenues
 20 0.39 airports in colorado
 27 0.38 liquor licenses in colorado
-------------------
Titles in Cron Group:  0

===============================================================================

Length:36 Steward:City and county of Denver  Cat:Economic Development  Type:Economic Zones Update Method: Automated on Socrata by BIC  Days Updated:1
4x4: g62i-kdzu
   Title:General Improvement Districts Denver:
 30 0.48 cemetery districts in colorado
 27 0.48 metro districts in colorado
 29 0.46 library districts in colorado
 42 0.46 water and sanitation districts in colorado
-------------------
Titles in Cron Group:  0

===============================================================================

Length:90 Steward:DPA  Cat:Government  Type: Update Method: Automated by Staging Server  Days Updated:#N/A
4x4: rifs-n6ib
   Title:Transparency Online Project (TOPS) - State Government Revenue and Expenditures in Colorado:
 42 0.45 water and sanitation districts in colorado
 47 0.45 paid solicitor solicitation notices in colorado
 56 0.45 retail marijuana sales tax revenue by county in colorado
 35 0.43 marijuana sales revenue in colorado
-------------------
Titles in Cron Group:  0

===============================================================================

Length:44 Steward:DWR  Cat:Water  Type:Water Resources Update Method: Automated by Staging Server  Days Updated:#N/A
4x4: 4yw9-a5y6
   Title:Current Surface Water Conditions in Colorado:
 42 0.60 water and sanitation districts in colorado
 26 0.60 race estimates in colorado
 30 0.59 cemetery districts in colorado
 28 0.58 current notaries in colorado
-------------------
Titles in Cron Group:  0

===============================================================================

MISSED  10

In [42]:
dfS['Update Method'].value_counts()

Update Method
None                           233
Automated by Staging Server     79
Manual                          57
                                25
Automated on Socrata by BIC      7
Automated by Staging server      1
Automated by Data Provider       1
Static                           1
Name: count, dtype: int64

In [43]:
dfS['Update Type'].value_counts()

Update Type
Static                 267
Manual - annual         43
Automated - weekly      41
Automated - monthly     26
Automated - daily       19
Manual - monthly         8
Name: count, dtype: int64

In [44]:
dfS.loc[dfS['Update Type'] == "Fixed"]

Empty DataFrame
Columns: [Socrata Link, Dataset Title, State Steward, Category, Type, Update Type, Update Schedule, Update Method, Source Update Schedule, cimAllData Updates, Complexity]
Index: []

### Look at Datasets with Mis-Match in UPdate Schedule

In [45]:
dfSauto.loc[dfSauto["Result"] == "BAD"]

    Socrata Link                                                      Dataset Title State Steward  Category      Type         Update Type     Update Schedule                Update Method Source Update Schedule cimAllData Updates Complexity Cron Update Result         Con Update
11     gxnn-wthy  Bill Information and Position with Income of Lobbyist in Colorado          CDOS  Lobbyist     Bills  Automated - weekly  Tuesday after 12AM  Automated by Staging Server                                        38                           BAD  Automated - weely
133    g89g-muvw                   Characterization of Lobbyist Clients in Colorado          CDOS  Lobbyist    Client  Automated - weekly  Tuesday after 12AM  Automated by Staging Server                                         3                           BAD  Automated - weely
191    35k5-cv8s                          Directory of Lobbyist Clients in Colorado          CDOS  Lobbyist    Client  Automated - weekly  Tuesday after 12AM  Automated by Staging Server                                         3                           BAD  Automated - weely
192    bqa5-gr84                                 Directory of Lobbyists in Colorado          CDOS  Lobbyist  Lobbyist  Automated - weekly  Tuesday after 12AM  Automated by Staging Server                                         3                           BAD  Automated - weely
205    eqsm-7ah7                                 Expenses for Lobbyists in Colorado          CDOS  Lobbyist     Bills  Automated - weekly  Tuesday after 12AM  Automated by Staging Server                                         3                           BAD  Automated - weely
358    gcmk-9nwy                           Subcontractors for Lobbyists in Colorado          CDOS  Lobbyist  Lobbyist  Automated - weekly  Tuesday after 12AM  Automated by Staging Server                                         3                           BAD  Automated - weely

In [46]:
dfCronAll['group'].values

array([' ceo/useia', ' ceo/useia', ' cdor/regulations_liquor',
       ' cdor/regulations_liquor', ' cdor/regulations_liquor',
       ' cdor/regulations_liquor', ' cdor/regulations_liquor',
       ' cdor/regulations_liquor', ' cdor/regulations_liquor',
       ' cdor/retail_reports', ' cdor/retail_reports',
       ' cdor/retail_reports', ' cdor/retail_reports',
       ' cdor/retail_reports', ' cdor/retail_reports',
       ' cdor/revenue_marijuana', ' cdor/revenue_marijuana',
       ' cdor/revenue_marijuana', ' cdor/revenue_marijuana',
       ' dora/regulations', ' dora/regulations', ' dola/demographics',
       ' dola/demographics', ' dola/demographics',
       ' dola/special_districts', ' dola/special_districts',
       ' dola/special_districts', ' dola/special_districts',
       ' dola/special_districts', ' dola/special_districts',
       ' dola/special_districts', ' dola/special_districts',
       ' dola/special_districts', ' dola/special_districts',
       ' dola/boundaries', ' dola/boundaries', ' cdot/tops', ' cdot/tops',
       ' cdot/tops', ' cdot/natural_resources', ' cdot/natural_resources',
       ' cdot/transportation_infrastructure',
       ' cdot/transportation_infrastructure',
       ' cdot/transportation_infrastructure',
       ' cdot/transportation_infrastructure',
       ' cdot/transportation_road_attributes',
       ' cdot/transportation_road_attributes',
       ' cdot/transportation_road_attributes',
       ' cdot/transportation_road_attributes',
       ' cdot/transportation_road_attributes',
       ' cdot/transportation_road_attributes',
       ' cdot/transportation_road_attributes', ' cdos/business/ucc',
       ' cdos/business/ucc', ' cdos/business/ucc', ' cdos/business/ucc',
       ' cdos/business/business', ' cdos/business/business',
       ' cdos/business/business', ' cdos/government', ' cdos/lobbyist',
       ' cdos/lobbyist', ' cdos/lobbyist', ' cdos/lobbyist',
       ' cdos/lobbyist', ' cdos/lobbyist', ' cdos/health',
       ' cdos/business/business', ' cdos/business/business',
       ' cdos/business/nonprofit', ' cdos/business/nonprofit',
       ' cdos/business/nonprofit', ' cdos/business/nonprofit',
       ' cdos/business/nonprofit', ' cdos/business/nonprofit',
       ' cdos/business/nonprofit', ' cdos/business/nonprofit',
       ' cdos/business/nonprofit', ' cdos/business/nonprofit',
       ' cdos/business/nonprofit', ' cdos/business/nonprofit',
       ' cdos/business/nonprofit', ' cdos/business/nonprofit',
       ' cdos/business/nonprofit', ' cdos/business/nonprofit', ' catalog',
       ' boulder', ' boulder'], dtype=object)

In [47]:
a="Restaurant Inspections in Boulder Colorado"
b="Restaurant Inspections in Boulder County"

In [48]:
R=difflib.SequenceMatcher(lambda x: x == " ", a=a, b=b)

In [49]:
R.ratio()

0.8780487804878049

In [50]:
import pathlib
import json

### Title Cross Check b/w Tracker and Cron

In [51]:
dfS.head()

  Socrata Link                                                                      Dataset Title              State Steward           Category               Type          Update Type           Update Schedule                Update Method Source Update Schedule cimAllData Updates Complexity
0    rkuy-jxyz  2019 Novel Coronavirus COVID-19 (2019-nCoV) Data Repository by Johns Hopkins CSSE                       CDOS             Health                                  Static                      None                         None                                      1439
1    s9wt-dsfz                                                    Active Business Licenses Denver  City and county of Denver           Business         Businesses    Automated - daily  Every day after midnight  Automated on Socrata by BIC               Annually                  1
2    vewn-5ajx                                      Activities of Charities Operating in Colorado                       CDOS           Business          Nonprofit               Static                      None                         None                                      1632
3    x5bw-ax3d                                                               Airports in Colorado                       CDOT     Transportation     Infrastructure  Automated - monthly              4th of month  Automated by Staging Server                                        25
4    dm2a-biqr                                                  All Special Districts in Colorado                       DOLA  Local Aggregation  Special Districts  Automated - monthly              4th of month  Automated by Staging Server                                        25

In [52]:
titlesTracker = df['Dataset Title'].str.lower().str.strip().values.tolist()
ngood=0
nbad=0
bad={}

for index,row in dfCronAll.iterrows():
    title = row['title']
    titleClean = title.lower().strip()
    if titleClean not in titlesTracker:
        bad[title]=row['4x4']
        nbad+=1
    else:
        ngood+=1
        
print("Good ",ngood)
print("Bad  ",nbad)

Good  82
Bad   6

In [53]:
a=df[["Socrata Link","Dataset Title"]].values.tolist()
titlesBy4x4 = {vals[0]:vals[1] for vals in a}
for title,w4x4 in bad.items():
    if w4x4 in titlesBy4x4:
        print(title,w4x4,titlesBy4x4[w4x4])
    else:
        print("MISS ",title,w4x4)

MISS  Retail Sales Tax Return History in Colorado 54t3-n5uh
MISS  Marijuana Sales Revenue in Colorado p6y8-s74x
Race Forecast in Colorado ab5h-juwk Race Forecasts in Colorado
MISS  Other State Solicitation of Charities
MISS  Charitable Organizations
MISS  CIM Catalog Download

In [54]:
display(dfCronAll.loc[dfCronAll['title'].isin(bad)])

                                                                                                                                           line                                                                    desc                     group                                        title          Update Type        4x4
22     30 4 1,8,15,22 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/retail_reports 2>> $bic_etl_home/general/logs/cron.log  At 04:30 on the first, the eighth, the 15th, and the 22th day of month       cdor/retail_reports  Retail Sales Tax Return History in Colorado   Automated - weekly  54t3-n5uh
21  20 4 1,8,15,22 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/revenue_marijuana 2>> $bic_etl_home/general/logs/cron.log  At 04:20 on the first, the eighth, the 15th, and the 22th day of month    cdor/revenue_marijuana          Marijuana Sales Revenue in Colorado   Automated - weekly  p6y8-s74x
19              30 4 1 * *  node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dola/demographics 2>> $bic_etl_home/general/logs/cron.log                                At 04:30 on the first day of every month         dola/demographics                    Race Forecast in Colorado  Automated - monthly  ab5h-juwk
2           5 6 * * 5 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit 2>> $bic_etl_home/general/logs/cron.log                                                      At 06:05 on Friday   cdos/business/nonprofit        Other State Solicitation of Charities   Automated - weekly
2           5 6 * * 5 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit 2>> $bic_etl_home/general/logs/cron.log                                                      At 06:05 on Friday   cdos/business/nonprofit                     Charitable Organizations   Automated - weekly
1                           0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> $bic_etl_home/general/logs/cron.log                                                      At 04:00 every day                   catalog                         CIM Catalog Download    Automated - daily

In [127]:
bad

{'Retail Sales Tax Return History in Colorado': '54t3-n5uh',
 'Marijuana Sales Revenue in Colorado': 'p6y8-s74x',
 'Race Forecast in Colorado': 'ab5h-juwk',
 'Registration for Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado': '',
 'Other State Solicitation of Charities': '',
 'Charitable Organizations': '',
 'CIM Catalog Download': ''}

In [131]:
titleT= df.loc[df['Socrata Link'] == '37wu-kn3g','Dataset Title'].values[0]

In [132]:
print(len(titleT))

136

In [133]:
b='Registration for Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado'

In [134]:
print(len(b))

137

In [135]:
print(titleT)
print(b)

Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado
Registration for Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado

### Clean Up Update Schedule

In [106]:
a = dfS.groupby(['Update Type','Update Schedule'],as_index=False).count()

In [109]:
b = a[['Update Type','Update Schedule','Socrata Link']]

In [111]:
b.rename(columns={'Socrata Link':'Count'},inplace=True)
display(b)

           Update Type           Update Schedule  Count
0    Automated - daily  Every day after midnight     19
1  Automated - monthly              4th of month     26
2   Automated - weekly        Tuesday after 12AM     41
3                Fixed                                1
4      Manual - Annual                  Annually      6
5      Manual - annual                    5-year      1
6      Manual - annual                  Annually     35
7     Manual - monthly              4th of month      8
8               Static                   Monthly      1
9               Static                      None    261

In [ ]:
dfS.loc[dfS['Update Type'].isin(["Automated - monthly","Automated - weekly"])]

In [125]:
dfSA = dfS.loc[dfS['Update Type'].isin(["Automated - monthly","Automated - weekly"])]
dfSA['Cron Update'] = ""
for index,row in dfSA.iterrows():
    title = row['Dataset Title']
    desc = dfCronAll.loc[dfCronAll['title'].str.lower().str.strip() == title.lower().strip(),"desc"].values.tolist()
    if len(desc) > 0:
       dfSA.loc[index,'Cron Update'] = desc[0]

In [128]:
dfSA.columns

Index(['Socrata Link', 'Dataset Title', 'State Steward', 'Category', 'Type', 'Update Type', 'Update Schedule', 'Update Method', 'Source Update Schedule', 'cimAllData Updates', 'Complexity', 'Cron Update'], dtype='object')

In [135]:
dfSA = dfSA[['Socrata Link', 'Dataset Title', 'State Steward', 'Category', 'Type', 'Update Type', 'Update Schedule', 'Cron Update','Update Method', 'Source Update Schedule', 'cimAllData Updates'] ]

In [137]:
dfSA.sort_values(by=['Update Type','Dataset Title']).to_csv("results-updatesched.csv",index=False)

In [136]:
display(dfSA.sort_values(by=['Update Type','Dataset Title']).head(100))

    Socrata Link                                                                                                                             Dataset Title State Steward           Category               Type          Update Type     Update Schedule                                                             Cron Update                Update Method Source Update Schedule cimAllData Updates
3      x5bw-ax3d                                                                                                                      Airports in Colorado          CDOT     Transportation     Infrastructure  Automated - monthly        4th of month                               At 04:30 on the fourth day of every month  Automated by Staging Server                                        24
4      dm2a-biqr                                                                                                         All Special Districts in Colorado          DOLA  Local Aggregation  Special Districts  Automated - monthly        4th of month                               At 05:20 on the fourth day of every month  Automated by Staging Server                                        24
29     9h8i-6khx                                                                                                            Cemetery Districts in Colorado          DOLA  Local Aggregation  Special Districts  Automated - monthly        4th of month                               At 05:20 on the fourth day of every month  Automated by Staging Server                                        24
139    7nuk-vzhq                                                                                                                        Cities in Colorado          CDOT     Transportation     Infrastructure  Automated - monthly        4th of month                               At 04:30 on the fourth day of every month  Automated by Staging Server                                        24
169    67vn-ijga                                                                                                                      Counties in Colorado          CDOT     Transportation     Infrastructure  Automated - monthly        4th of month                               At 04:30 on the fourth day of every month  Automated by Staging Server                                        24
207    ua3v-vcuh                                                                                                                Fire Districts in Colorado          DOLA  Local Aggregation  Special Districts  Automated - monthly        4th of month                               At 05:20 on the fourth day of every month  Automated by Staging Server                                        24
226    9syq-9vv5                                                                                                            Highway Milepoints in Colorado          CDOT     Transportation    Road Attributes  Automated - monthly        4th of month                               At 04:10 on the fourth day of every month  Automated by Staging Server                                        24
227    trm9-dm4m                                                                                                             Highway Mileposts in Colorado          CDOT     Transportation    Road Attributes  Automated - monthly        4th of month                               At 04:10 on the fourth day of every month  Automated by Staging Server                                        24
233    xs2v-uzeg                                                                                                                Highway Routes in Colorado          CDOT     Transportation    Road Attributes  Automated - monthly        4th of month                               At 04:10 on the fourth day of every month  Automated by Staging Server                                        24
240    2h6w-z9ry                                                                                                                      Highways in Colorado          CDOT     Transportation    Road Attributes  Automated - monthly        4th of month                               At 04:10 on the fourth day of every month  Automated by Staging Server                                        24
241    wxzv-xh9i                                                                                                            Hospital Districts in Colorado          DOLA  Local Aggregation  Special Districts  Automated - monthly        4th of month                               At 05:20 on the fourth day of every month  Automated by Staging Server                                        24
246    uksn-8qya                                                                                                                         Lakes in Colorado          CDOT  Natural Resources    Water Resources  Automated - monthly        4th of month                               At 04:50 on the fourth day of every month  Automated by Staging Server                                        23
249    3thw-b7wj                                                                                                             Library Districts in Colorado          DOLA  Local Aggregation  Special Districts  Automated - monthly        4th of month                               At 05:20 on the fourth day of every month  Automated by Staging Server                                        24
254    qvrk-xsmj                                                                                                                   Local Roads in Colorado          CDOT     Transportation    Road Attributes  Automated - monthly        4th of month                               At 04:10 on the fourth day of every month  Automated by Staging Server                                        24
256    e7ye-tasg                                                                                                                   Major Roads in Colorado          CDOT     Transportation    Road Attributes  Automated - monthly        4th of month                               At 04:10 on the fourth day of every month  Automated by Staging Server                                        24
260    ej2c-jkvh                                                                                                                   Master List in Colorado          CDOS           Business         Businesses  Automated - monthly        4th of month                                                                          Automated by Staging Server                                        56
261    knbf-ggf2                                                                                                               Metro Districts in Colorado          DOLA  Local Aggregation  Special Districts  Automated - monthly        4th of month                               At 05:20 on the fourth day of every month  Automated by Staging Server                                        24
263    5qqr-23dz                                                                                                         Municipal Annexations in Colorado          DOLA  Local Aggregation         Boundaries  Automated - monthly        4th of month                               At 04:00 on the fourth day of every month  Automated by Staging Server                                        24
264    u943-ics6                                                                                                          Municipal Boundaries in Colorado          DOLA  Local Aggregation         Boundaries  Automated - monthly        4th of month                               At 04:00 on the fourth day of every month  Automated by Staging Server                                        24
281    853a-s2qz                                                                                                      Parks and Rec Districts in Colorado           DOLA  Local Aggregation  Special Districts  Automated - monthly        4th of month                               At 05:20 on the fourth day of every month  Automated by Staging Server                                        24
297    hpem-wb68                                                                                                                     Railroads in Colorado          CDOT     Transportation     Infrastructure  Automated - monthly        4th of month                               At 04:30 on the fourth day of every month  Automated by Staging Server                                        24
331    6aqe-63uq                                                                                                                 Scenic Byways in Colorado          CDOT     Transportation    Road Attributes  Automated - monthly        4th of month                               At 04:10 on the fourth day of every month  Automated by Staging Server                                       525
332    esrk-9vjd                                                                                                              School Districts in Colorado          DOLA  Local Aggregation  Special Districts  Automated - monthly        4th of month                               At 05:20 on the fourth day of every month  Automated by Staging Server                                        24
342    fwb5-rzg5                                                                                                                Soil Districts in Colorado          DOLA  Local Aggregation  Special Districts  Automated - monthly        4th of month                               At 05:20 on the fourth day of every month  Automated by Staging Server                                        24
352    x238-vje7                                                                                                                       Streams in Colorado          CDOT  Natural Resources    Water Resources  Automated - monthly        4th of month                               At 04:50 on the fourth day of every month  Automated by Staging Server                                        23
380    d6bs-3kgu                                                                                                Water and Sanitation Districts in Colorado          DOLA  Local Aggregation  Special Districts  Automated - monthly        4th of month                               At 05:20 on the fourth day of every month  Automated by Staging Server                                        24
11     gxnn-wthy                                                                         Bill Information and Position with Income of Lobbyist in Colorado          CDOS           Lobbyist              Bills   Automated - weekly  Tuesday after 12AM                                                     At 04:15 on Tuesday  Automated by Staging Server                                        37
25     n5ku-eixc                                                                                                                           CDOT Expenses            CDOT     Transportation     Infrastructure   Automated - weekly  Tuesday after 12AM                                                   At 05:45 on Wednesday  Automated by Staging Server                                         1
26     rkmy-yymq                                                                                                               CDOT Payroll Expenditures            CDOT     Transportation     Infrastructure   Automated - weekly  Tuesday after 12AM                                                   At 05:45 on Wednesday  Automated by Staging Server                                        23
27     2kvt-7ybu                                                                                                                           CDOT Revenues            CDOT     Transportation     Infrastructure   Automated - weekly  Tuesday after 12AM                                                   At 05:45 on Wednesday  Automated by Staging Server                                         1
24     fdcw-ei67                                                                        Campaign Reports for Solicitation Notices to Charities in Colorado          CDOS           Business          Nonprofit   Automated - weekly  Tuesday after 12AM                                                      At 06:05 on Friday  Automated by Staging Server                                         6
133    g89g-muvw                                                                                          Characterization of Lobbyist Clients in Colorado          CDOS           Lobbyist             Client   Automated - weekly  Tuesday after 12AM                                                     At 04:15 on Tuesday  Automated by Staging Server                                         2
134    3qtu-edua                                                                                             Charitable Organizations’ Offices in Colorado          CDOS           Business          Nonprofit   Automated - weekly  Tuesday after 12AM                                                                          Automated by Staging Server                                         6
135    7jm9-f28m                                                                                             Charitable Purpose of the Charity in Colorado          CDOS           Business          Nonprofit   Automated - weekly  Tuesday after 12AM                                                      At 06:05 on Friday  Automated by Staging Server                                         6
136    wwhd-vg25                                                                                 Charitable Solicitation Call Center Locations in Colorado          CDOS           Business          Nonprofit   Automated - weekly  Tuesday after 12AM                                                      At 06:05 on Friday  Automated by Staging Server                                        41
137    34aw-ny67                                                                                   Charities Solicitation Type by Solicitation in Colorado          CDOS           Business          Nonprofit   Automated - weekly  Tuesday after 12AM                                                      At 06:05 on Friday  Automated by Staging Server                                         6
138    icqv-mi3c                                                                                                                Charity Extension Requests          CDOS           Business          Nonprofit   Automated - weekly  Tuesday after 12AM                                                      At 06:05 on Friday  Automated by Staging Server                                        55
159    w6kb-3vsj                                                                          Communication Methods Used in Solicitation Campaigns in Colorado          CDOS           Business          Nonprofit   Automated - weekly  Tuesday after 12AM                                                      At 06:05 on Friday  Automated by Staging Server                                       272
180    k4uv-yvnk                                                                                                              Current Notaries in Colorado          CDOS         Government           Notaries   Automated - weekly  Tuesday after 12AM                                                     At 04:30 on Tuesday  Automated by Staging Server                                         2
186    35k5-cv8s                                                                                                 Directory of Lobbyist Clients in Colorado          CDOS           Lobbyist             Client   Automated - weekly  Tuesday after 12AM                                                     At 04:15 on Tuesday  Automated by Staging Server                                         2
187    bqa5-gr84                                                                                                        Directory of Lobbyists in Colorado          CDOS           Lobbyist           Lobbyist   Automated - weekly  Tuesday after 12AM                                                     At 04:15 on Tuesday  Automated by Staging Server                                         2
188    s7ct-nf65                                                                                           Durable Medical Equipment Suppliers in Colorado          CDOS             Health         Healthcare   Automated - weekly  Tuesday after 12AM                                                     At 04:00 on Tuesday  Automated by Staging Server                                         9
200    eqsm-7ah7                                                                                                        Expenses for Lobbyists in Colorado          CDOS           Lobbyist              Bills   Automated - weekly  Tuesday after 12AM                                                     At 04:15 on Tuesday  Automated by Staging Server                                         2
206    2z9k-uy4q                                                                                           Federal Tax-Exempt Subsection Codes in Colorado          CDOS           Business          Nonprofit   Automated - weekly  Tuesday after 12AM                                                      At 06:05 on Friday  Automated by Staging Server                                       923
217    8pk9-mh2i                                                                                                               Gasoline Prices in Colorado           CEO             Energy         Statistics   Automated - weekly  Tuesday after 12AM                                                                          Automated by Staging Server                                         2
251    kapc-ib6e                                                                                            Liquor Compliance Check Statistics in Colorado          CDOR        Regulations  Liquor Regulation   Automated - weekly  Tuesday after 12AM  At 04:40 on the first, the eighth, the 15th, and the 22th day of month  Automated by Staging Server                                       160
252    ier5-5ms2                                                                                                               Liquor Licenses in Colorado          CDOR        Regulations  Liquor Regulation   Automated - weekly  Tuesday after 12AM  At 04:40 on the first, the eighth, the 15th, and the 22th day of month  Automated by Staging Server                                        25
253    d6t8-xish                                                                                             Liquor Permits for Special Events in Colorado          CDOR        Regulations  Liquor Regulation   Automated - weekly  Tuesday after 12AM  At 04:40 on the first, the eighth, the 15th, and the 22th day of month  Automated by Staging Server                                       259
257    d4s4-xqg6                                                                                     Manufacturer Temporary Sales Room Permits in Colorado          CDOR        Regulations  Liquor Regulation   Automated - weekly  Tuesday after 12AM  At 04:40 on the first, the eighth, the 15th, and the 22th day of month  Automated by Staging Server                                        25
258    j7a3-jgd3                                                                                                     Marijuana Sales by County in Colorado          CDOR            Revenue              Sales   Automated - weekly  Tuesday after 12AM  At 04:20 on the first, the eighth, the 15th, and the 22th day of month  Automated by Staging Server                                        14