In [5]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)
import math

In [2]:
dfC = pd.read_csv("https://data.colorado.gov/resource/349y-twqi.csv")
dfN = pd.read_csv("Professional_and_Occupational_License_Types_in_Colorado_20241224.csv")

In [3]:
dfC.shape,dfN.shape

((333, 7), (333, 7))

In [3]:
dfN.columns
import math

In [6]:
histC={}
for indx,row in dfC.iterrows():
    cat = row["licensecategory"].strip()
    pre = row["licenseprefix"]
    if isinstance(pre,str) or not math.isnan(pre):
        pre=pre.strip()
    if cat not in histC:
        histC[cat]={}
    if pre not in histC[cat]:
        histC[cat][pre]=0
    histC[cat][pre]+=1
    


histN={}
for indx,row in dfN.iterrows():
    cat = row["licenseCategory"]
    pre = row["licensePrefix"]
    if isinstance(pre,str) or not math.isnan(pre):
        pre=pre.strip()
    if cat not in histN:
        histN[cat]={}
    if pre not in histN[cat]:
        histN[cat][pre]=0
    histN[cat][pre]+=1

In [7]:
for cat,dct in histC.items():
    for pre,count in dct.items():
        if count > 1:
            print(cat,pre,count)

Pharmacy PHATP 2
Psychology PSYC 2

In [6]:
for cat,dct in histN.items():
    for pre,count in dct.items():
        if count > 1:
            print(cat,pre,count)

Pharmacy PHATP 2
Psychology PSYC 2

In [10]:
for cat,dct in histN.items():
    for pre,cnt in dct.items():
        if cnt > 1:
            print("BAD COUNT IN NEW DATA",cnt,cat,pre)
        if cat not in histC:
            print(f"NEW CAT IN NEW DATA {len(cat)} :{cat}: {pre}")
        elif pre not in histC[cat]:
            print(f"NEW TOPIC IN NEW DATA for CATEGORY {cat}: {pre}")

BAD COUNT IN NEW DATA 2 Pharmacy PHATP
BAD COUNT IN NEW DATA 2 Psychology PSYC

In [9]:
for cat,dct in histC.items():
    for pre,cnt in dct.items():
        if cnt > 1:
            print("BAD COUNT IN CIM DATA",cnt,cat,pre)
        if cat not in histN:
            print(f"CIM CAT NOT IN NEW DATA {len(cat)}  {cat} {pre}")
        elif pre not in histN[cat]:
            print(f"CIM TOPIC IN NEW DATA for CATEGORY {cat}: {pre}")

BAD COUNT IN CIM DATA 2 Pharmacy PHATP
BAD COUNT IN CIM DATA 2 Psychology PSYC

In [11]:
dfN.drop_duplicates()

,licenseCategory,licenseType,licensePrefix,businessOrIndividual,renewalCycle,year,renewalExpirationDate
0,Accountancy,Certified Public Accountant,CPA,Individual,Two Year,Odd,30-Nov
1,Accountancy,Military Spouse - Certified Public Accountant,MSCPA,Individual,Two Year,odd,30-Nov
2,Accountancy,Public Accounting Firm,FRM,Business,Three Year,NaN,31-Aug
3,Accountancy,Temporary CPA Permit (Historic Only),TPA,Individual,Do not renew,NaN,NaN
4,Acupuncture,Acupuncturist,ACU,Individual,Two Year,Odd,31-Dec
...,...,...,...,...,...,...,...
328,Veterinary,Military Spouse Veterinarian Technician,MSVT,Individual,Two Year,Even,31-Oct
329,Veterinary,Temporary - Veterinarian (Historic Only),T-VET,Individual,Do not renew,NaN,NaN
330,Veterinary,Veterinarian,VET,Individual,Two Year,Even,31-Oct
331,Veterinary,Veterinarian Technician,VT,Individual,Two Year,Even,31-Oct
332,Veterinary,Veterinarian Technician Provisional,PVT,Individual,Two Year,Even,31-Oct

In [12]:
dfN.shape

(333, 7)

In [16]:
dfN["renewalCycle"].value_counts()

renewalCycle
Two Year        177
Do not renew     86
Annual           43
Three Year       21
Varies            6
Name: count, dtype: int64

In [15]:
dfData = pd.read_csv("https://data.colorado.gov/resource/7s5z-vewr.csv?$limit=5000000")

In [24]:
dfData.shape

(1488614, 24)

In [25]:
dfData.head()

,lastname,firstname,middlename,suffix,entityname,city,state,mailzipcode,licensetype,subcategory,...,licensestatusdescription,specialty,title,degrees,casenumber,programaction,disciplineeffectivedate,disciplinecompletedate,linktoverifylicense,linktoviewhealthcareprofile
0,Sherman-Luce,Nicole,Dawn,NaN,NaN,Nome,AK,99762,NaN,NaN,...,Expired,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora/licensing/Lookup...,https://www.colorado.gov/dora/licensing/Snapsh...
1,James,Joseph,NaN,NaN,NaN,Golden,CO,80401,APE,NaN,...,Expired,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora/licensing/Lookup...,NaN
2,Williams,Sadie,Louise,NaN,NaN,Fruita,CO,81521,CSW,NaN,...,Active,NaN,NaN,~Bachelors of Arts~Masters of Social Work,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora/licensing/Lookup...,https://www.colorado.gov/dora/licensing/Snapsh...
3,Patnode,Leo,Jon,NaN,NaN,Lafayette,CO,80026,JW,NaN,...,Expired,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora/licensing/Lookup...,NaN
4,Schlagel,Keith,Allen,NaN,NaN,Longmont,CO,80504,PE,NaN,...,Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora/licensing/Lookup...,NaN

In [26]:
dfData.columns

Index(['lastname', 'firstname', 'middlename', 'suffix', 'entityname', 'city',
       'state', 'mailzipcode', 'licensetype', 'subcategory', 'licensenumber',
       'licensefirstissuedate', 'licenselastreneweddate',
       'licenseexpirationdate', 'licensestatusdescription', 'specialty',
       'title', 'degrees', 'casenumber', 'programaction',
       'disciplineeffectivedate', 'disciplinecompletedate',
       'linktoverifylicense', 'linktoviewhealthcareprofile'],
      dtype='object')

In [103]:
dfData["licensetype"].value_counts()

licensetype
RN        226777
APE        77928
COS        73872
DR         65128
PE         59670
PN         49609
CPA        38642
AP         35962
JW         31183
MT         27212
MAN        24062
COZ        22412
NLC        22199
REG        21525
PTL        20343
PHA        18818
ARC        18030
LPC        17513
APN        16541
IV         15623
DEN        15228
CSW        14900
PHATP      13823
VET        13231
ME         12704
EC         11866
DH         11448
RXN        11401
JP         11320
RTL        10625
TL         10559
PHAT        9746
LPCC        9680
IN          9644
PA          9028
C-APN       8848
MP          8796
CHR         8632
OT          8227
BAR         8097
T-NA        7659
LSW         7453
LOCAL       7218
PSY         6821
ST          6765
SLP         6284
RW          6011
EL          5793
SEC         5674
TRNP        5354
CST         5309
PC          4908
C-RXN       4895
ACC         4805
CDR         4790
HST         4679
FRM         4003
PLS         3959
VT          3925
DD          3779
PTA         3648
OPT         3594
PSYC        3309
OSP         3244
PAR         3237
COR         3192
ACA         3141
ACB         3053
OUT         3029
NHA         3013
ACU         2842
MFT         2801
ACD         2733
TGRNP       2542
SWC         2378
RP          2372
CDRH        2318
SA          2301
AT          2276
PMT         2165
PDO         2092
OTA         1840
WHO         1836
LA          1689
TGPNP       1541
MFTC        1452
MI          1430
PSLP        1396
AUD         1306
T-RN        1108
TPNP         855
POD          803
AV           800
PVT          740
AC           700
JEWP         685
TRM          637
LPP          631
MINS         631
OO           623
HAD          592
RME          587
ADDC         586
C-IV         480
FH           455
SWP          426
GEN          421
MODS         407
NTO          379
DRP          373
MAA          368
PTLP         366
SPDO         345
HAT          345
NHATPE       320
MWR          301
HAAP         300
PI1          294
RMT          290
ND           288
TMPMOD       284
ANT          279
T-PN         279
MSRN         273
MEWP         261
TMPGEN       250
RWWP         213
TLTP         200
MPWP         198
JPWP         192
CDS          190
AIT          175
WHI          162
PRO          146
PCS          143
CFY          138
SRN          135
OFC          134
DOC-NA       133
MWM          130
PDT          126
CM           118
ANI          112
ITR          111
HAA          108
TPLP         107
MIV          103
T-DH          92
LTD           87
MWS           79
MFR           74
RPWP          66
T-DEN         61
ECS           61
TCRN          60
MSNA          58
APT           55
MSCOS         53
TDP           52
MFP           45
NOF           45
T-OT          43
MSPN          42
MSCSW         32
MSPTL         30
MSAPN         28
T-APN         28
AD            26
OTP           25
TPA           25
MSCOZ         24
MSRXN         23
DOC-RN        22
MSPA          21
MSSLP         21
MSPHAT        20
MSLSW         20
WP            19
MSLPC         17
MSMT          16
TNHAP         16
MSDH          16
MSMAN         16
MSOT          15
T-OTA         15
WC            15
WI            14
MSDR          14
HSP           13
MSPTA         13
T-RTL         13
MSPHA         13
T-PTA         12
PSP           11
NMTP          11
T-CHR         10
DOC-PN         8
MSST           8
MSDEN          8
MSPSY          8
TPDO           7
MSLOC          7
TCPN           7
MSAT           7
T-PA           7
PSYRX          7
MSLPCC         7
MSRTL          7
MSVET          6
OTAP           6
MSMFT          6
T-DR           5
T-PTL          5
MSBAR          5
MSVT           5
PDV            5
MSOTA          4
DOCRXN         4
MSHST          4
DOCAPN         4
NTTB           4
T-VET          4
MSACA          3
MSPE           3
OPV            3
MSJW           3
MSIN           3
MSCPA          3
MSACU          3
T-OPT          3
MSCHR          3
MSMAA          2
MSMFTC         2
NMF            2
MSJP           2
MSACC          2
SPN            2
MSNHA          2
MSIV           2
T-ANT          2
METPE          2
MSOPT          2
MSSWC          2
MSLPP          2
MPTPE          1
MSEL           1
T-SLP          1
MSITR          1
MSPOD          1
MSHAAP         1
MSNLC          1
MSMWM          1
MSPSYC         1
MSOUT          1
MSAIT          1
MSCOR          1
MSMWR          1
MSHAD          1
DT             1
MSSA           1
MSANT          1
MSND           1
MSWI           1
MSDD           1
MSPLS          1
MSTL           1
MSGEN          1
MSPRO          1
MSRP           1
MSWP           1
MSMINS         1
MSMWS          1
MSOFC          1
MSAD           1
MSAPT          1
MSAUD          1
MSMI           1
T-POD          1
MSRME          1
MSRMT          1
MSSWP          1
MSAV           1
MSANI          1
MSMFP          1
MSMIV          1
MSRW           1
MSPDT          1
MSACD          1
MSADDC         1
MSLA           1
MSME           1
MSMODS         1
MSMP           1
PHACS          1
MSPAR          1
MSAC           1
MSPSP          1
MSARC          1
Name: count, dtype: int64

In [105]:
da=dfData["licensetype"].value_counts().to_dict()

In [ ]:
da

In [29]:
dfN.columns

Index(['licenseCategory', 'licenseType', 'licensePrefix',
       'businessOrIndividual', 'renewalCycle', 'year',
       'renewalExpirationDate'],
      dtype='object')

In [36]:
tp=dfN['licensePrefix'].value_counts().to_dict()

In [37]:
da.keys()

dict_keys(['NP', 'C-NP', 'CRNA', 'CNM', 'CNS', 'C-CRNA', 'C-CNM', 'C-CNS'])

In [38]:
tp.keys()

dict_keys(['PHATP', 'PSYC', 'MSOUT', 'T-OPT', 'OPV', 'OPT', 'MSOPT', 'T-OTA', 'T-OT', 'OTAP', 'OTA', 'OUT', 'OT', 'MSOTA', 'MSOT', 'TNHAP', 'AIT', 'NHA', 'NHATPE', 'MSNHA', 'OTP', 'TPLP', 'TPDO', 'SPDO', 'OSP', 'PDO', 'PHAT', 'PHACS', 'IN', 'PHA', 'TRM', 'NOF', 'MSPHAT', 'MSIN', 'MSPHA', 'MFR', 'LTD', 'HSP', 'CMPD', 'APDS', 'DOCAPN CNS', 'OO', 'MSAPN NP', 'MSMAA', 'MSPN', 'MSIV', 'MSRXN CNS', 'MSAPN CNS', 'MSRXN CRNA', 'MSAPN CRNA', 'MSRXN CNM', 'MSAIT', 'MSNA', 'MAA', 'PN', 'IV', 'DOC-RN', 'DOCRXN NP', 'DOCAPN NP', 'DOC-PN', 'DOCRXN CNS', 'MSAPN CNM', 'TRNP', 'TPNP', 'TGRNP', 'TGPNP', 'TCRN', 'TCPN', 'T-RN', 'T-PN', 'T-NA', 'MSRXN NP', 'SRN', 'SPN', 'RN', 'MI', 'DD', 'RXN NP', 'APN NP', 'MSRN', 'MSMI', 'MSDD', 'T-APN', 'PE', 'MSPLS', 'MSSWC', 'MSARC', 'ARC', 'MSACD', 'MSACA', 'MSACC', 'MSADDC', 'WHI', 'MSRME', 'VT', 'VET', 'T-VET', 'MSVT', 'MSPVT', 'MSVET', 'MSAV', 'AV', 'ACD', 'EL', 'CHR', 'ANI', 'AC', 'REG', 'MAN', 'MSMAN', 'MSHST', 'MSCOZ', 'PLS', 'MSBAR', 'HST', 'COZ', 'COS', 'BAR', 'MSAUD', 'CFY', 'AUD', 'MSAT', 'AT', 'MSCOS', 'MSRMT', 'MSAP', 'MSMP', 'MSJP', 'MPWP', 'MPTE', 'MP', 'JPWP', 'JP', 'NLC', 'T-PTL', 'PTLP', 'PTA', 'PTL', 'MSPTA', 'MSPTL', 'MSAPT', 'APT', 'WHO', 'T-PTA', 'MSNLC', 'NTTB', 'ST', 'SA', 'MSST', 'MSSA', 'T-SLP', 'SLP', 'PSLP', 'MSRTL', 'SWP', 'MSSWP', 'MSLSW', 'MSCSW', 'WC', 'LSW', 'CSW', 'SWC', 'T-RTL', 'RTL', 'MSSLP', 'DT', 'DH', 'GEN', 'CDS', 'AD', 'MSPAR', 'MSCOR', 'MSPRO', 'MSOFC', 'DOCRXN CRNA', 'PRO', 'PAR', 'OFC', 'COR', 'CST', 'T-CHR', 'MSEL', 'MSCHR', 'MSANI', 'SEC', 'EC', 'APE', 'TMPMOD', 'TMPGEN', 'T-DEN', 'T-DH', 'PCS', 'MODS', 'MINS', 'DEN', 'MSMINS', 'MSLOC', 'MSITR', 'MSDEN', 'MSDH', 'MSGEN', 'MSAD', 'LOCAL', 'ITR', 'ECS', 'MSMODS', 'WI', 'MSPE', 'RPWP', 'RP', 'PC', 'AP', 'MSWP', 'MSWI', 'MSRP', 'MSAC', 'ACC', 'ACB', 'ADDC', 'MSACU', 'ACU', 'TPA', 'FRM', 'MSCPA', 'CPA', 'ACA', 'RME', 'RMT', 'PSP', 'MSPSYC', 'PSYRX', 'MSPSP', 'MSPSY', 'PSY', 'LPP', 'WP', 'MSLPCC', 'MSLPC', 'LPCC', 'LPC', 'T-POD', 'PDV', 'PDT', 'POD', 'MSPDT', 'MSPOD', 'MSLPP', 'CMW', 'ND', 'MSND', 'NMTP', 'NMIT', 'NMF', 'NMDE', 'NMCF', 'MSMWS', 'JW', 'MSMIV', 'MSMWR', 'MWS', 'MWM', 'MIV', 'MWR', 'T-PA', 'T-DR', 'T-ANT', 'MSMWM', 'PVT', 'DOCAPN CRNA', 'DOCAPN CNM', 'DOCRXN CNM', 'DOC-NA', 'C-RXN C-NP', 'C-APN C-NP', 'C-IV', 'C-RXN C-CNS', 'CMWRX', 'C-RXN C-CRNA', 'C-APN C-CRNA', 'C-RXN C-CNM', 'C-APN C-CNM', 'RXN CNS', 'APN CNS', 'RXN CRNA', 'APN CRNA', 'RXN CNM', 'APN CNM', 'C-APN C-CNS', 'MSLA', 'LA', 'MSHAD', 'MSHAAP', 'HAT', 'HAD', 'HAA', 'HAAP', 'FH', 'DRP', 'RWWP', 'RW', 'MSRW', 'MSME', 'MSJW', 'MSAPE', 'MEWP', 'METPE', 'ME', 'JEWP', 'CM', 'TL', 'TLTP', 'PA', 'DR', 'MSTL', 'MSPA', 'MSDR', 'MSANT', 'TDP', 'MFT', 'CDR', 'ANT', 'PMT', 'MSMT', 'MT', 'MFP', 'MSMFP', 'MSMFTC', 'MSMFT', 'MFTC', 'CDRH'])

In [107]:
set(tp.keys())-set(da.keys())

{'APDS',
 'APN CNM',
 'APN CNS',
 'APN CRNA',
 'APN NP',
 'C-APN C-CNM',
 'C-APN C-CNS',
 'C-APN C-CRNA',
 'C-APN C-NP',
 'C-RXN C-CNM',
 'C-RXN C-CNS',
 'C-RXN C-CRNA',
 'C-RXN C-NP',
 'CMPD',
 'CMW',
 'CMWRX',
 'DOCAPN CNM',
 'DOCAPN CNS',
 'DOCAPN CRNA',
 'DOCAPN NP',
 'DOCRXN CNM',
 'DOCRXN CNS',
 'DOCRXN CRNA',
 'DOCRXN NP',
 'MPTE',
 'MSAP',
 'MSAPE',
 'MSAPN CNM',
 'MSAPN CNS',
 'MSAPN CRNA',
 'MSAPN NP',
 'MSPVT',
 'MSRXN CNM',
 'MSRXN CNS',
 'MSRXN CRNA',
 'MSRXN NP',
 'NMCF',
 'NMDE',
 'NMIT',
 'RXN CNM',
 'RXN CNS',
 'RXN CRNA',
 'RXN NP'}

In [109]:
b=set(da.keys())-set(tp.keys())

In [114]:
dfData.loc[dfData["licensetype"].isin(b),'licensetype'].value_counts()

licensetype
APN       16541
RXN       11401
C-APN      8848
C-RXN      4895
NTO         379
PI1         294
MSAPN        28
MSRXN        23
DOCRXN        4
DOCAPN        4
MPTPE         1
Name: count, dtype: int64

Data         Type File
'C-CNM'      'C-RXN C-CNM'
'C-CNS'      'C-RXN C-CNS' 
'C-CRNA'     'C-RXN C-CRNA' 
'C-NP'       'C-RXN C-NP'
'CNM'
'CNS'
'CRNA'
'NP'

In [102]:
dfData.loc[dfData['license'] == "C-CNM"]

Empty DataFrame
Columns: [lastname, firstname, middlename, suffix, entityname, city, state, mailzipcode, licensetype, subcategory, licensenumber, licensefirstissuedate, licenselastreneweddate, licenseexpirationdate, licensestatusdescription, specialty, title, degrees, casenumber, programaction, disciplineeffectivedate, disciplinecompletedate, linktoverifylicense, linktoviewhealthcareprofile]
Index: []

In [42]:
print(sorted(tp.keys()))

['AC', 'ACA', 'ACB', 'ACC', 'ACD', 'ACU', 'AD', 'ADDC', 'AIT', 'ANI', 'ANT', 'AP', 'APDS', 'APE', 'APN CNM', 'APN CNS', 'APN CRNA', 'APN NP', 'APT', 'ARC', 'AT', 'AUD', 'AV', 'BAR', 'C-APN C-CNM', 'C-APN C-CNS', 'C-APN C-CRNA', 'C-APN C-NP', 'C-IV', 'C-RXN C-CNM', 'C-RXN C-CNS', 'C-RXN C-CRNA', 'C-RXN C-NP', 'CDR', 'CDRH', 'CDS', 'CFY', 'CHR', 'CM', 'CMPD', 'CMW', 'CMWRX', 'COR', 'COS', 'COZ', 'CPA', 'CST', 'CSW', 'DD', 'DEN', 'DH', 'DOC-NA', 'DOC-PN', 'DOC-RN', 'DOCAPN CNM', 'DOCAPN CNS', 'DOCAPN CRNA', 'DOCAPN NP', 'DOCRXN CNM', 'DOCRXN CNS', 'DOCRXN CRNA', 'DOCRXN NP', 'DR', 'DRP', 'DT', 'EC', 'ECS', 'EL', 'FH', 'FRM', 'GEN', 'HAA', 'HAAP', 'HAD', 'HAT', 'HSP', 'HST', 'IN', 'ITR', 'IV', 'JEWP', 'JP', 'JPWP', 'JW', 'LA', 'LOCAL', 'LPC', 'LPCC', 'LPP', 'LSW', 'LTD', 'MAA', 'MAN', 'ME', 'METPE', 'MEWP', 'MFP', 'MFR', 'MFT', 'MFTC', 'MI', 'MINS', 'MIV', 'MODS', 'MP', 'MPTE', 'MPWP', 'MSAC', 'MSACA', 'MSACC', 'MSACD', 'MSACU', 'MSAD', 'MSADDC', 'MSAIT', 'MSANI', 'MSANT', 'MSAP', 'MSAPE', 'MSAPN CNM', 'MSAPN CNS', 'MSAPN CRNA', 'MSAPN NP', 'MSAPT', 'MSARC', 'MSAT', 'MSAUD', 'MSAV', 'MSBAR', 'MSCHR', 'MSCOR', 'MSCOS', 'MSCOZ', 'MSCPA', 'MSCSW', 'MSDD', 'MSDEN', 'MSDH', 'MSDR', 'MSEL', 'MSGEN', 'MSHAAP', 'MSHAD', 'MSHST', 'MSIN', 'MSITR', 'MSIV', 'MSJP', 'MSJW', 'MSLA', 'MSLOC', 'MSLPC', 'MSLPCC', 'MSLPP', 'MSLSW', 'MSMAA', 'MSMAN', 'MSME', 'MSMFP', 'MSMFT', 'MSMFTC', 'MSMI', 'MSMINS', 'MSMIV', 'MSMODS', 'MSMP', 'MSMT', 'MSMWM', 'MSMWR', 'MSMWS', 'MSNA', 'MSND', 'MSNHA', 'MSNLC', 'MSOFC', 'MSOPT', 'MSOT', 'MSOTA', 'MSOUT', 'MSPA', 'MSPAR', 'MSPDT', 'MSPE', 'MSPHA', 'MSPHAT', 'MSPLS', 'MSPN', 'MSPOD', 'MSPRO', 'MSPSP', 'MSPSY', 'MSPSYC', 'MSPTA', 'MSPTL', 'MSPVT', 'MSRME', 'MSRMT', 'MSRN', 'MSRP', 'MSRTL', 'MSRW', 'MSRXN CNM', 'MSRXN CNS', 'MSRXN CRNA', 'MSRXN NP', 'MSSA', 'MSSLP', 'MSST', 'MSSWC', 'MSSWP', 'MSTL', 'MSVET', 'MSVT', 'MSWI', 'MSWP', 'MT', 'MWM', 'MWR', 'MWS', 'ND', 'NHA', 'NHATPE', 'NLC', 'NMCF', 'NMDE', 'NMF', 'NMIT', 'NMTP', 'NOF', 'NTTB', 'OFC', 'OO', 'OPT', 'OPV', 'OSP', 'OT', 'OTA', 'OTAP', 'OTP', 'OUT', 'PA', 'PAR', 'PC', 'PCS', 'PDO', 'PDT', 'PDV', 'PE', 'PHA', 'PHACS', 'PHAT', 'PHATP', 'PLS', 'PMT', 'PN', 'POD', 'PRO', 'PSLP', 'PSP', 'PSY', 'PSYC', 'PSYRX', 'PTA', 'PTL', 'PTLP', 'PVT', 'REG', 'RME', 'RMT', 'RN', 'RP', 'RPWP', 'RTL', 'RW', 'RWWP', 'RXN CNM', 'RXN CNS', 'RXN CRNA', 'RXN NP', 'SA', 'SEC', 'SLP', 'SPDO', 'SPN', 'SRN', 'ST', 'SWC', 'SWP', 'T-ANT', 'T-APN', 'T-CHR', 'T-DEN', 'T-DH', 'T-DR', 'T-NA', 'T-OPT', 'T-OT', 'T-OTA', 'T-PA', 'T-PN', 'T-POD', 'T-PTA', 'T-PTL', 'T-RN', 'T-RTL', 'T-SLP', 'T-VET', 'TCPN', 'TCRN', 'TDP', 'TGPNP', 'TGRNP', 'TL', 'TLTP', 'TMPGEN', 'TMPMOD', 'TNHAP', 'TPA', 'TPDO', 'TPLP', 'TPNP', 'TRM', 'TRNP', 'VET', 'VT', 'WC', 'WHI', 'WHO', 'WI', 'WP']

In [54]:
a= 'C-RXN C-CNM'
for a in b: 
    a = f"C-RXN {a}"
    print(a)
    
    display(dfN.loc[dfN["licensePrefix"] == a])

C-RXN NP

Empty DataFrame
Columns: [licenseCategory, licenseType, licensePrefix, businessOrIndividual, renewalCycle, year, renewalExpirationDate]
Index: []

C-RXN CNS

Empty DataFrame
Columns: [licenseCategory, licenseType, licensePrefix, businessOrIndividual, renewalCycle, year, renewalExpirationDate]
Index: []

C-RXN CRNA

Empty DataFrame
Columns: [licenseCategory, licenseType, licensePrefix, businessOrIndividual, renewalCycle, year, renewalExpirationDate]
Index: []

C-RXN C-NP

,licenseCategory,licenseType,licensePrefix,businessOrIndividual,renewalCycle,year,renewalExpirationDate
160,Nursing,Compact Nurse Practitioner - C-RXN,C-RXN C-NP,Individual,Two Year,Odd and Even,30-Sep

C-RXN C-CNS

,licenseCategory,licenseType,licensePrefix,businessOrIndividual,renewalCycle,year,renewalExpirationDate
157,Nursing,Compact Clinical Nurse Specialist - C-RXN,C-RXN C-CNS,Individual,Two Year,Odd and Even,30-Sep

C-RXN C-CNM

,licenseCategory,licenseType,licensePrefix,businessOrIndividual,renewalCycle,year,renewalExpirationDate
153,Nursing,Compact Certified Nurse Midwife - C-RXN,C-RXN C-CNM,Individual,Two Year,Odd and Even,30-Sep

C-RXN C-CRNA

,licenseCategory,licenseType,licensePrefix,businessOrIndividual,renewalCycle,year,renewalExpirationDate
155,Nursing,Compact Certified Registered Nurse Anesthetist...,C-RXN C-CRNA,Individual,Two Year,Odd and Even,30-Sep

C-RXN CNM

Empty DataFrame
Columns: [licenseCategory, licenseType, licensePrefix, businessOrIndividual, renewalCycle, year, renewalExpirationDate]
Index: []

In [89]:
dfData.columns

Index(['lastname', 'firstname', 'middlename', 'suffix', 'entityname', 'city',
       'state', 'mailzipcode', 'licensetype', 'subcategory', 'licensenumber',
       'licensefirstissuedate', 'licenselastreneweddate',
       'licenseexpirationdate', 'licensestatusdescription', 'specialty',
       'title', 'degrees', 'casenumber', 'programaction',
       'disciplineeffectivedate', 'disciplinecompletedate',
       'linktoverifylicense', 'linktoviewhealthcareprofile'],
      dtype='object')

In [91]:
display(dfData["subcategory"].value_counts())

subcategory
NP        23041
C-NP      12083
CRNA       1987
CNM        1494
CNS        1479
C-CRNA     1185
C-CNM       328
C-CNS       147
Name: count, dtype: int64

In [92]:
display(dfData["licensetype"].value_counts())

licensetype
RN        226777
APE        77928
COS        73872
DR         65128
PE         59670
PN         49609
CPA        38642
AP         35962
JW         31183
MT         27212
MAN        24062
COZ        22412
NLC        22199
REG        21525
PTL        20343
PHA        18818
ARC        18030
LPC        17513
APN        16541
IV         15623
DEN        15228
CSW        14900
PHATP      13823
VET        13231
ME         12704
EC         11866
DH         11448
RXN        11401
JP         11320
RTL        10625
TL         10559
PHAT        9746
LPCC        9680
IN          9644
PA          9028
C-APN       8848
MP          8796
CHR         8632
OT          8227
BAR         8097
T-NA        7659
LSW         7453
LOCAL       7218
PSY         6821
ST          6765
SLP         6284
RW          6011
EL          5793
SEC         5674
TRNP        5354
CST         5309
PC          4908
C-RXN       4895
ACC         4805
CDR         4790
HST         4679
FRM         4003
PLS         3959
VT          3925
DD          3779
PTA         3648
OPT         3594
PSYC        3309
OSP         3244
PAR         3237
COR         3192
ACA         3141
ACB         3053
OUT         3029
NHA         3013
ACU         2842
MFT         2801
ACD         2733
TGRNP       2542
SWC         2378
RP          2372
CDRH        2318
SA          2301
AT          2276
PMT         2165
PDO         2092
OTA         1840
WHO         1836
LA          1689
TGPNP       1541
MFTC        1452
MI          1430
PSLP        1396
AUD         1306
T-RN        1108
TPNP         855
POD          803
AV           800
PVT          740
AC           700
JEWP         685
TRM          637
LPP          631
MINS         631
OO           623
HAD          592
RME          587
ADDC         586
C-IV         480
FH           455
SWP          426
GEN          421
MODS         407
NTO          379
DRP          373
MAA          368
PTLP         366
SPDO         345
HAT          345
NHATPE       320
MWR          301
HAAP         300
PI1          294
RMT          290
ND           288
TMPMOD       284
ANT          279
T-PN         279
MSRN         273
MEWP         261
TMPGEN       250
RWWP         213
TLTP         200
MPWP         198
JPWP         192
CDS          190
AIT          175
WHI          162
PRO          146
PCS          143
CFY          138
SRN          135
OFC          134
DOC-NA       133
MWM          130
PDT          126
CM           118
ANI          112
ITR          111
HAA          108
TPLP         107
MIV          103
T-DH          92
LTD           87
MWS           79
MFR           74
RPWP          66
T-DEN         61
ECS           61
TCRN          60
MSNA          58
APT           55
MSCOS         53
TDP           52
MFP           45
NOF           45
T-OT          43
MSPN          42
MSCSW         32
MSPTL         30
MSAPN         28
T-APN         28
AD            26
OTP           25
TPA           25
MSCOZ         24
MSRXN         23
DOC-RN        22
MSPA          21
MSSLP         21
MSPHAT        20
MSLSW         20
WP            19
MSLPC         17
MSMT          16
TNHAP         16
MSDH          16
MSMAN         16
MSOT          15
T-OTA         15
WC            15
WI            14
MSDR          14
HSP           13
MSPTA         13
T-RTL         13
MSPHA         13
T-PTA         12
PSP           11
NMTP          11
T-CHR         10
DOC-PN         8
MSST           8
MSDEN          8
MSPSY          8
TPDO           7
MSLOC          7
TCPN           7
MSAT           7
T-PA           7
PSYRX          7
MSLPCC         7
MSRTL          7
MSVET          6
OTAP           6
MSMFT          6
T-DR           5
T-PTL          5
MSBAR          5
MSVT           5
PDV            5
MSOTA          4
DOCRXN         4
MSHST          4
DOCAPN         4
NTTB           4
T-VET          4
MSACA          3
MSPE           3
OPV            3
MSJW           3
MSIN           3
MSCPA          3
MSACU          3
T-OPT          3
MSCHR          3
MSMAA          2
MSMFTC         2
NMF            2
MSJP           2
MSACC          2
SPN            2
MSNHA          2
MSIV           2
T-ANT          2
METPE          2
MSOPT          2
MSSWC          2
MSLPP          2
MPTPE          1
MSEL           1
T-SLP          1
MSITR          1
MSPOD          1
MSHAAP         1
MSNLC          1
MSMWM          1
MSPSYC         1
MSOUT          1
MSAIT          1
MSCOR          1
MSMWR          1
MSHAD          1
DT             1
MSSA           1
MSANT          1
MSND           1
MSWI           1
MSDD           1
MSPLS          1
MSTL           1
MSGEN          1
MSPRO          1
MSRP           1
MSWP           1
MSMINS         1
MSMWS          1
MSOFC          1
MSAD           1
MSAPT          1
MSAUD          1
MSMI           1
T-POD          1
MSRME          1
MSRMT          1
MSSWP          1
MSAV           1
MSANI          1
MSMFP          1
MSMIV          1
MSRW           1
MSPDT          1
MSACD          1
MSADDC         1
MSLA           1
MSME           1
MSMODS         1
MSMP           1
PHACS          1
MSPAR          1
MSAC           1
MSPSP          1
MSARC          1
Name: count, dtype: int64

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [94]:
display(dfData.head())

,lastname,firstname,middlename,suffix,entityname,city,state,mailzipcode,licensetype,subcategory,licensenumber,licensefirstissuedate,licenselastreneweddate,licenseexpirationdate,licensestatusdescription,specialty,title,degrees,casenumber,programaction,disciplineeffectivedate,disciplinecompletedate,linktoverifylicense,linktoviewhealthcareprofile
0,Sherman-Luce,Nicole,Dawn,NaN,NaN,Nome,AK,99762,NaN,NaN,799805,2020-09-01T00:00:00.000,2020-09-01T00:00:00.000,2021-01-31T00:00:00.000,Expired,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora/licensing/Lookup...,https://www.colorado.gov/dora/licensing/Snapsh...
1,James,Joseph,NaN,NaN,NaN,Golden,CO,80401,APE,NaN,9933406,NaN,2013-10-25T00:00:00.000,NaN,Expired,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora/licensing/Lookup...,NaN
2,Williams,Sadie,Louise,NaN,NaN,Fruita,CO,81521,CSW,NaN,1521,2010-03-10T00:00:00.000,2023-09-01T00:00:00.000,2025-08-31T00:00:00.000,Active,NaN,NaN,~Bachelors of Arts~Masters of Social Work,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora/licensing/Lookup...,https://www.colorado.gov/dora/licensing/Snapsh...
3,Patnode,Leo,Jon,NaN,NaN,Lafayette,CO,80026,JW,NaN,111217,2008-07-19T00:00:00.000,2017-10-01T00:00:00.000,2020-09-30T00:00:00.000,Expired,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora/licensing/Lookup...,NaN
4,Schlagel,Keith,Allen,NaN,NaN,Longmont,CO,80504,PE,NaN,29540,1994-02-04T00:00:00.000,2023-11-01T00:00:00.000,2025-10-31T00:00:00.000,Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora/licensing/Lookup...,NaN

In [63]:
dfNN = dfN.dropna(subset=["licensePrefix"])

In [96]:
display(dfNN.head(100))

,licenseCategory,licenseType,licensePrefix,businessOrIndividual,renewalCycle,year,renewalExpirationDate
0,Accountancy,Certified Public Accountant,CPA,Individual,Two Year,Odd,30-Nov
1,Accountancy,Military Spouse - Certified Public Accountant,MSCPA,Individual,Two Year,odd,30-Nov
2,Accountancy,Public Accounting Firm,FRM,Business,Three Year,NaN,31-Aug
3,Accountancy,Temporary CPA Permit (Historic Only),TPA,Individual,Do not renew,NaN,NaN
4,Acupuncture,Acupuncturist,ACU,Individual,Two Year,Odd,31-Dec
5,Acupuncture,Military Spouse - Acupuncturist,MSACU,Individual,Two Year,Odd,31-Dec
6,Addiction Counselors,Addiction Counselor Candidate,ADDC,Individual,Three Year,NaN,NaN
7,Addiction Counselors,Certified Addiction Counselor II,ACB,Individual,Two Year,Odd,31-Aug
8,Addiction Counselors,Certified Addiction Specialist,ACC,Individual,Two Year,Odd,31-Aug
9,Addiction Counselors,Certified Addiction Technician,ACA,Individual,Two Year,Odd,31-Aug
10,Addiction Counselors,Licensed Addiction Counselor,ACD,Individual,Two Year,Odd,31-Aug
11,Addiction Counselors,Military Spouse - Addiction Counselor Candidate,MSADDC,Individual,Three Year,NaN,NaN
12,Addiction Counselors,Military Spouse - Certified Addiction Specialist,MSACC,Individual,Two Year,Odd,31-Aug
13,Addiction Counselors,Military Spouse - Certified Addiction Technician,MSACA,Individual,Two Year,Odd,31-Aug
14,Addiction Counselors,Military Spouse - Licensed Addiction Counselor,MSACD,Individual,Two Year,Odd,31-Aug
15,"Architects, Engineers and Land Surveyors",Architect,ARC,Individual,Two Year,Odd,31-Oct
16,"Architects, Engineers and Land Surveyors",Military Spouse - Architect,MSARC,Individual,Two Year,Odd,31-Oct
17,"Architects, Engineers and Land Surveyors",Military Spouse - Professional Engineer,MSPE,Individual,Two Year,Odd,31-Oct
18,"Architects, Engineers and Land Surveyors",Military Spouse - Professional Land Surveyor,MSPLS,Individual,Two Year,Odd,31-Oct
19,"Architects, Engineers and Land Surveyors",Professional Engineer,PE,Individual,Two Year,Odd,31-Oct
20,"Architects, Engineers and Land Surveyors",Professional Land Surveyor,PLS,Individual,Two Year,Odd,31-Oct
21,Athletic Trainers,Athletic Trainers,AT,Individual,Two Year,Odd,30-Nov
22,Athletic Trainers,Military Spouse - Athletic Trainers,MSAT,Individual,Two Year,Odd,30-Nov
23,Audiology,Audiologist,AUD,Individual,Two Year,Even,31-Mar
24,Audiology,Clinical Fellow in Audiology (Historic Only),CFY,Individual,Do not renew,NaN,NaN
25,Audiology,Military Spouse - Audiologist,MSAUD,Individual,Two Year,Even,31-Mar
26,Barber/Cosmetology,Barber,BAR,Individual,Two Year,Even,31-Mar
27,Barber/Cosmetology,Cosmetologist,COS,Individual,Two Year,Odd and Even,30-Apr
28,Barber/Cosmetology,Esthetician,COZ,Individual,Two Year,Even,31-Mar
29,Barber/Cosmetology,Hair Stylist,HST,Individual,Two Year,Even,31-Mar
30,Barber/Cosmetology,Military Spouse - Barber,MSBAR,Individual,Two Year,Even,31-Mar
31,Barber/Cosmetology,Military Spouse - Cosmetologist,MSCOS,Individual,Two Year,Odd and Even,30-Apr
32,Barber/Cosmetology,Military Spouse - Esthetician,MSCOZ,Individual,Two Year,Even,31-Mar
33,Barber/Cosmetology,Military Spouse - Hair Stylist,MSHST,Individual,Two Year,Even,31-Mar
34,Barber/Cosmetology,Military Spouse - Nail Technician,MSMAN,Individual,Two Year,Even,31-Mar
35,Barber/Cosmetology,Nail Technician,MAN,Individual,Two Year,Even,31-Mar
36,Barber/Cosmetology,Shop Registration,REG,Business,Two Year,Odd,30-Nov
37,Chiropractic,Acupuncture Chiorpractic (CHR Authority),AC,Individual,Do not renew,NaN,NaN
38,Chiropractic,Animal Chiropractic (CHR Authority),ANI,Individual,Do not renew,NaN,NaN
39,Chiropractic,Chiropractor,CHR,Individual,Two Year,Odd,31-Oct
40,Chiropractic,Electrotherapy - Chiropractic (CHR Authority),EL,Individual,Do not renew,NaN,NaN
41,Chiropractic,Military Spouse - Acupuncture - Chiropractic,MSAC,Individual,Do not renew,NaN,NaN
42,Chiropractic,Military Spouse - Animal Chiropractic,MSANI,Individual,Do not renew,NaN,NaN
43,Chiropractic,Military Spouse - Chiropractic,MSCHR,Individual,Two Year,Odd,31-Oct
44,Chiropractic,Military Spouse - Electrotherapy - Chiropractic,MSEL,Individual,Do not renew,NaN,NaN
45,Chiropractic,Temporary - Chiropractor (Historic Only),T-CHR,Individual,Do not renew,NaN,NaN
46,Combative Sports,Boxing Contestant (Historic Only),CST,Individual,Do not renew,NaN,NaN
47,Combative Sports,Boxing Corner,COR,Individual,Annual,NaN,30-Jun
48,Combative Sports,Boxing Official,OFC,Individual,Annual,NaN,30-Jun
49,Combative Sports,Boxing Participant,PAR,Individual,Annual,NaN,30-Jun
50,Combative Sports,Boxing Promoter,PRO,Individual,Annual,NaN,30-Jun
51,Combative Sports,Boxing Second (Historic Only),SEC,Individual,Do not renew,NaN,NaN
52,Combative Sports,Military Spouse - Boxing Official,MSOFC,Individual,Annual,NaN,30-Jun
53,Combative Sports,Military Spouse - Boxing Promoter,MSPRO,Individual,Annual,NaN,30-Jun
54,Combative Sports,Military Spouse - Corner,MSCOR,Individual,Annual,NaN,30-Jun
55,Combative Sports,Military Spouse - Participant,MSPAR,Individual,Annual,NaN,30-Jun
56,Dental,Academic Dentist,AD,Individual,Two Year,Even,28-Feb
57,Dental,Conscious / Deep Sedation (Historic Only),CDS,Individual,Do not renew,NaN,NaN
58,Dental,Deep Sedation/General Anesthesia (DEN Authority),GEN,Individual,Varies,NaN,NaN
59,Dental,Dental Hygienist,DH,Individual,Two Year,Even,28-Feb
60,Dental,Dental Therapist,DT,Individual,Two Year,Even,28-Feb
61,Dental,Dentist,DEN,Individual,Two Year,Even,28-Feb
62,Dental,Enteral Conscious Sedation (Historic Only),ECS,Individual,Do not renew,NaN,NaN
63,Dental,Interim Therapeutic Restorations Permit,ITR,Individual,Do not renew,NaN,NaN
64,Dental,Local Anesthesia (DH Authority),LOCAL,Individual,Do not renew,NaN,NaN
65,Dental,Military Spouse - Academic Dentist,MSAD,Individual,Two Year,Even,28-Feb
66,Dental,Military Spouse - Deep Sedation/General Anesth...,MSGEN,Individual,Varies,NaN,NaN
67,Dental,Military Spouse - Dental Hygienist,MSDH,Individual,Two Year,Even,28-Feb
68,Dental,Military Spouse - Dentist,MSDEN,Individual,Two Year,Even,28-Feb
69,Dental,Military Spouse - Interim Therapeutic Restorat...,MSITR,Individual,Do not renew,NaN,NaN
70,Dental,Military Spouse - Local Anesthesia,MSLOC,Individual,Do not renew,NaN,NaN
71,Dental,Military Spouse - Minimal Sedation,MSMINS,Individual,Varies,NaN,NaN
72,Dental,Military Spouse - Moderate Sedation,MSMODS,Individual,Varies,NaN,NaN
73,Dental,Minimal Sedation (DEN Authority),MINS,Individual,Varies,NaN,NaN
74,Dental,Moderate Sedation (DEN Authority),MODS,Individual,Varies,NaN,NaN
75,Dental,Parenteral/Enteral Conscious Sedation (Histori...,PCS,Individual,Do not renew,NaN,NaN
76,Dental,Temporary - Dental Hygienist (Historic Only),T-DH,Individual,Do not renew,NaN,NaN
77,Dental,Temporary - Dentist (Historic Only),T-DEN,Individual,Do not renew,NaN,NaN
78,Dental,Temporary Deep Sedation/General Anesthesia Permit,TMPGEN,Individual,Do not renew,NaN,NaN
79,Dental,Temporary Moderate Sedation Privleges,TMPMOD,Individual,Do not renew,NaN,NaN
80,Electrical,Electrical Apprentice,APE,Individual,Do not renew,NaN,NaN
81,Electrical,Electrical Contractor,EC,Business,Three Year,NaN,30-Sep
82,Electrical,Journeyman Electrician,JW,Individual,Three Year,NaN,30-Sep
83,Electrical,Journeyman Electrician Work Permit,JEWP,Individual,Do not renew,NaN,NaN
84,Electrical,Master Electrician,ME,Individual,Three Year,NaN,30-Sep
85,Electrical,Master Electrician Temporary Permit for Emerge...,METPE,Individual,Do not renew,NaN,NaN
86,Electrical,Master Electrician Work Permit,MEWP,Individual,Do not renew,NaN,NaN
87,Electrical,Military Spouse - Electrical Apprentice,MSAPE,Individual,Do not renew,NaN,NaN
88,Electrical,Military Spouse - Journeyman Electrician,MSJW,Individual,Three Year,NaN,30-Sep
89,Electrical,Military Spouse - Master Electrician,MSME,Individual,Three Year,NaN,30-Sep
90,Electrical,Military Spouse - Residential Wireman,MSRW,Individual,Three Year,NaN,30-Sep
91,Electrical,Residential Wireman,RW,Individual,Three Year,NaN,30-Sep
92,Electrical,Residential Wireman Work Permit,RWWP,Individual,Do not renew,NaN,NaN
93,Funeral Home and Crematory,Crematory,CM,Business,Annual,NaN,30-Nov
94,Funeral Home and Crematory,Funeral Home,FH,Business,Annual,NaN,30-Nov
95,Hearing Aid Providers,Hearing Aid Apprentice,HAAP,Individual,Two Year,Even,31-Mar
96,Hearing Aid Providers,Hearing Aid Associate,HAA,Individual,Do not renew,NaN,NaN
97,Hearing Aid Providers,Hearing Aid Provider,HAD,Individual,Two Year,Even,31-Mar
98,Hearing Aid Providers,Hearing Aid Provider - Trainee,HAT,Individual,Do not renew,NaN,NaN
99,Hearing Aid Providers,Military Spouse - Hearing Aid Apprentice,MSHAAP,Individual,Two Year,Even,31-Mar

In [73]:
mils=dfNN.loc[dfNN["licenseType"].str.contains("^Military",case=False),"licensePrefix"].to_list()

In [74]:
len(mils)

108

In [76]:
len(dfNN.loc[dfNN["licenseType"].str.contains("^Military",case=False)])

108

In [85]:
dfMil=dfData.loc[dfData["licensetype"].str.upper().isin(mils)]

In [86]:
dfMil.head()

,lastname,firstname,middlename,suffix,entityname,city,state,mailzipcode,licensetype,subcategory,licensenumber,licensefirstissuedate,licenselastreneweddate,licenseexpirationdate,licensestatusdescription,specialty,title,degrees,casenumber,programaction,disciplineeffectivedate,disciplinecompletedate,linktoverifylicense,linktoviewhealthcareprofile
2821,Grizzell,Deirdre,NaN,NaN,NaN,Colorado Springs,CO,80916,MSRN,NaN,33,2021-05-14T00:00:00.000,2021-05-14T00:00:00.000,2024-05-14T00:00:00.000,Expired,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora/licensing/Lookup...,https://www.colorado.gov/dora/licensing/Snapsh...
4157,Rivas,Carmella,Maximina,NaN,NaN,Colorado Springs,CO,80916,MSPHA,NaN,8,2024-05-16T00:00:00.000,2024-05-16T00:00:00.000,2027-05-16T00:00:00.000,Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora/licensing/Lookup...,https://www.colorado.gov/dora/licensing/Snapsh...
6978,Garcia,Monserrat,NaN,NaN,NaN,Colorado Springs,CO,80903,MSRN,NaN,36,2021-06-15T00:00:00.000,2021-06-15T00:00:00.000,2024-06-15T00:00:00.000,Expired,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora/licensing/Lookup...,https://www.colorado.gov/dora/licensing/Snapsh...
9640,Heddy,Lauren,Elizabeth,NaN,NaN,Arlington,VA,22201,MSRN,NaN,179,2023-05-08T00:00:00.000,2023-05-08T00:00:00.000,2026-05-08T00:00:00.000,Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora/licensing/Lookup...,https://www.colorado.gov/dora/licensing/Snapsh...
10718,Rodriguez Alvarez,Christina,Michelle,NaN,NaN,Olathe,CO,81425,MSPHAT,NaN,7,2023-01-11T00:00:00.000,2023-01-11T00:00:00.000,2026-01-11T00:00:00.000,Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora/licensing/Lookup...,https://www.colorado.gov/dora/licensing/Snapsh...

In [87]:
dfMil.shape

(884, 24)