In [2]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)
import sys
sys.path.insert(0, '/mnt/c/users/cojoe/Python-Stuff')
import JCLib
import re

## Functions

In [2]:
import numpy as np
def analyzeDF(df): 
    print(df.shape)
    def analyzeD(row,stats,allColsNan):
        ncols=0
        nNaN=0
        for col in list(row.index):
             stats[col]["# rows"]+=1
             ncols+=1
             if pd.isna(row[col]):
                stats[col]["NaN"]+=1
                nNaN+=1
             elif isinstance(row[col],int):
                stats[col]["int"]+=1
             elif isinstance(row[col],str):
                stats[col]['str-all']+=1
                if row[col].isnumeric():
                   stats[col]['str-num']+=1
                else:
                   stats[col]['str-str']+=1
        if ncols == nNaN:
            allColsNan+=1
                
            
    stats = {}

    for col in df.columns:
        stats[col] = {}
        stats[col]["# rows"] = 0
        stats[col]["int"]=0
        stats[col]["str-all"] = 0
        stats[col]["str-num"] = 0
        stats[col]["str-str"] = 0
        stats[col]["NaN"] = 0
        

    allColsNan=0
        
    x = df.apply(analyzeD,axis=1,args=(stats,allColsNan))
    statsDf = pd.DataFrame(stats)
    display(statsDf.T.head())
    print(f"# Rows All Data Missing: ",allColsNan)

## Federal Tax Codes

In [ ]:
dfTax = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_source/tax_exempt_cds.tsv",sep="\t",encoding="latin")

In [ ]:
dfTax.shape

In [ ]:
dfTax.head()

In [ ]:
dfTax.isna().sum()

In [ ]:
dfTax.tail()

## Purpose
7jm9-f28m

### Original file

In [3]:
dfOrig = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_source/purpose.tsv",sep="\t",encoding="latin")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
analyzeDF(dfOrig)

(203282, 6)

              # rows     int  str-all  str-num  str-str  NaN
Entity Id     203282  203282        0        0        0    0
Document Id   203282   72210   131072   131065        7    0
Ce Fein       203282       0   203282        0   203282    0
Org Name      203282       0   203282        2   203280    0
Ce File Date  203282       0   203281        0   203281    1

# Rows All Data Missing:  0

In [ ]:

dfOrig.apply(analyzeDF,axis=1)

In [7]:
dfOrig.shape

(203282, 6)

In [8]:
dfOrig.head()

,Entity Id,Document Id,Ce Fein,Org Name,Ce File Date,Cr Purpose
0,20023004097,20043001780,84-0725883,NAMAQUA CENTER,02/06/2004,PROVIDE TREATMENT SERVICES TO SEVERLY EMOTIONA...
1,20023004011,20053001748,84-0402706,"GIRL SCOUTS, COLUMBINE COUNCIL, INC.",02/10/2005,"GIRL SCOUTS, COLUMBINE COUNCIL IS A NON-PROFIT..."
2,20023008029,20043001850,13-1624102,"NATIONAL AUDUBON SOCIETY, INC.",02/23/2004,OUR MISSION IS TO CONSERVE AND RESTORE NATURAL...
3,20023007827,20043001773,84-0897434,KERN FOUNDATION,02/10/2004,THE PURPOSE OF THE FOUNDATION IS TO PROVIDE FU...
4,20023003781,20043001823,23-7113221,UNITED WAY OF SOUTHWEST COLORADO,02/18/2004,HELPS BUILD HEALTHY COMMUNITIES BY RAISING MON...

In [ ]:
dfOrig["Ce Acct Id"].str.isnumeric()

In [ ]:
vals = dfOrig["Ce Acct Id"].astype(int).values.tolist()

In [ ]:
dfOrig["Ce Acct Id"].value_counts()

In [ ]:
nrec=0
for val in vals:
    nrec+=1
    try:
        val = int(val)
        if isinstance(val,int) == False:
            print(nrec,val,type(val))
    except:
        print("ROH ROH ",nrec,val,type(val))
#    if nrec > 100:break

In [ ]:
dfOrig.isna().sum()

### Local Converted File

In [60]:
purpNew = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_transformed/purpose.csv")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (1,2) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [61]:
purpNew.head()

,entityId,documentId,fein,name,statementOfPurpose,filingDate
0,20023004097,20043001780,840725883,NAMAQUA CENTER,PROVIDE TREATMENT SERVICES TO SEVERLY EMOTIONA...,02/06/2020
1,20023004011,20053001748,840402706,"GIRL SCOUTS, COLUMBINE COUNCIL, INC.","GIRL SCOUTS, COLUMBINE COUNCIL IS A NON-PROFIT...",02/10/2020
2,20023008029,20043001850,131624102,"NATIONAL AUDUBON SOCIETY, INC.",OUR MISSION IS TO CONSERVE AND RESTORE NATURAL...,02/23/2020
3,20023007827,20043001773,840897434,KERN FOUNDATION,THE PURPOSE OF THE FOUNDATION IS TO PROVIDE FU...,02/10/2020
4,20023003781,20043001823,237113221,UNITED WAY OF SOUTHWEST COLORADO,HELPS BUILD HEALTHY COMMUNITIES BY RAISING MON...,02/18/2020

In [12]:
dfNew.shape

(203282, 6)

In [13]:
dfNew.isna().sum()

entityId              0
documentId            0
fein                  0
name                  0
statementOfPurpose    0
filingDate            1
dtype: int64

In [14]:
dfNew.head()

,entityId,documentId,fein,name,statementOfPurpose,filingDate
0,20023004097,20043001780,840725883,NAMAQUA CENTER,PROVIDE TREATMENT SERVICES TO SEVERLY EMOTIONA...,02/06/2020
1,20023004011,20053001748,840402706,"GIRL SCOUTS, COLUMBINE COUNCIL, INC.","GIRL SCOUTS, COLUMBINE COUNCIL IS A NON-PROFIT...",02/10/2020
2,20023008029,20043001850,131624102,"NATIONAL AUDUBON SOCIETY, INC.",OUR MISSION IS TO CONSERVE AND RESTORE NATURAL...,02/23/2020
3,20023007827,20043001773,840897434,KERN FOUNDATION,THE PURPOSE OF THE FOUNDATION IS TO PROVIDE FU...,02/10/2020
4,20023003781,20043001823,237113221,UNITED WAY OF SOUTHWEST COLORADO,HELPS BUILD HEALTHY COMMUNITIES BY RAISING MON...,02/18/2020

### CIM Data

In [90]:
dfCIM = pd.read_csv("https://data.colorado.gov/api/views/7jm9-f28m/rows.csv?accessType=DOWNLOAD")

In [91]:
dfCim.shape

(203560, 6)

In [13]:
dfCim.head()

,entityId,documentId,fein,name,statementOfPurpose,filingDate
0,20023004097,20043001780,840725883,NAMAQUA CENTER,PROVIDE TREATMENT SERVICES TO SEVERLY EMOTIONA...,02/06/2020 12:00:00 AM
1,20023004011,20053001748,840402706,"GIRL SCOUTS, COLUMBINE COUNCIL, INC.","GIRL SCOUTS, COLUMBINE COUNCIL IS A NON-PROFIT...",02/10/2020 12:00:00 AM
2,20023008029,20043001850,131624102,"NATIONAL AUDUBON SOCIETY, INC.",OUR MISSION IS TO CONSERVE AND RESTORE NATURAL...,02/23/2020 12:00:00 AM
3,20023007827,20043001773,840897434,KERN FOUNDATION,THE PURPOSE OF THE FOUNDATION IS TO PROVIDE FU...,02/10/2020 12:00:00 AM
4,20023003781,20043001823,237113221,UNITED WAY OF SOUTHWEST COLORADO,HELPS BUILD HEALTHY COMMUNITIES BY RAISING MON...,02/18/2020 12:00:00 AM

In [ ]:
dfCim.isna().sum()

In [ ]:
dfNew.columns

In [ ]:
a = dfNew['entityId'].value_counts().to_dict()

In [ ]:
b = dfOrig['Entity Id'].value_counts().to_dict()

In [ ]:
ngood=0
nbad=0

for k,v in b.items():
    if v == a[k]:
        ngood+=1
    else:
        print("Miss")
        print("A ",k,v)
        print("B ",k,b[k])
        nbad+=1
        
print("Good ",ngood)
print(" bad ",nbad)

### Compares

In [86]:
purpOrig = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_source/purpose.tsv",sep="\t",encoding="latin")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [93]:
purpCIM = pd.read_csv("https://data.colorado.gov/api/views/7jm9-f28m/rows.csv?accessType=DOWNLOAD")

In [88]:
purpConv = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_transformed/purpose.csv")

In [94]:
print(f"Orig: {purpOrig.shape}")
print(f"Conv: {purpConv.shape}")
print(f" CIM: {purpCIM.shape}")
print(f"Conv - Orig: {purpConv.shape[0] - purpOrig.shape[0]}")
print(f"Conv -  CIM: {purpConv.shape[0] - purpCIM.shape[0]}")

Orig: (203560, 6)
Conv: (203560, 6)
 CIM: (203560, 6)
Conv - Orig: 0
Conv -  CIM: 0

## Other State Solicitation of Charities’ Registrants in Colorado
5wyf-xqw7

### Orginal File

In [15]:
statesOrig = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_source/states.tsv",sep="\t",encoding="latin")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (0,1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [16]:
statesOrig.dtypes

Entity Id      object
Document Id    object
Ce Fein        object
Org Name       object
Cs State       object
Cs Auth Flg    object
Entity Type    object
dtype: object

In [17]:
statesOrig.head()

,Entity Id,Document Id,Ce Fein,Org Name,Cs State,Cs Auth Flg,Entity Type
0,20023004698,20033009607,39-0983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,MN,Y,CO
1,20023004698,20033009607,39-0983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,MO,Y,CO
2,20023004698,20033009607,39-0983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,MS,Y,CO
3,20023004698,20033009607,39-0983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,NC,Y,CO
4,20023004698,20033009607,39-0983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,NH,Y,CO

In [18]:
statesOrig.shape

(2452848, 7)

In [ ]:
statesOrig["Entity Id"].astype(int)

In [ ]:
nrec=0
for val in statesOrig["Entity Id"].values.tolist():
    nrec+=1
    try: 
        val = int(val)
    except:
        print(nrec,val,type(val))

In [ ]:
nrec=0
for val in statesOrig["Ce Acct Id"].values.tolist():
    nrec+=1
    try: 
        val = int(val)
    except:
        print(nrec,val,type(val))

In [3]:
stateCIM = pd.read_csv("https://data.colorado.gov/api/views/5wyf-xqw7/rows.csv?accessType=DOWNLOAD")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (0,1,2) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
stateCIM.dtypes

In [ ]:
stateCIM.shape

In [ ]:
print(stateCIM.duplicated().sum())
print(statesOrig.duplicated().sum())

In [ ]:
statesOrig.loc[statesOrig.duplicated(keep=False)]

In [ ]:
stateCIM.head(100)

In [ ]:
statesOrig.shape

In [ ]:
statesOrig.duplicated().sum()

In [ ]:
stateCIM.head()

In [ ]:
stateCIM.shape

In [ ]:
nrec=0
for val in stateCIM["entityId"].values.tolist():
    nrec+=1
    try: 
        val = int(val)
    except:
        print(nrec,val,type(val))

In [ ]:
stateCIM.loc[(~stateCIM["entityId"].isna()) & (stateCIM["entityId"].str.contains("TEMP"))]

In [ ]:
stateCIM.isna().sum()

### Locally Converted File

In [70]:
statesConv = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_transformed/state.csv")

In [71]:
statesConv.shape

(2457707, 8)

In [72]:
statesConv.head()

,entityId,documentId,fein,name,stateAbbreviation,authorizedSoliciting,registrantTypeAbbr,registrantType
0,20023004698,20033009607,390983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,MN,NaN,CO,Charitable Organization
1,20023004698,20033009607,390983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,MO,NaN,CO,Charitable Organization
2,20023004698,20033009607,390983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,MS,NaN,CO,Charitable Organization
3,20023004698,20033009607,390983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,NC,NaN,CO,Charitable Organization
4,20023004698,20033009607,390983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,NH,NaN,CO,Charitable Organization

In [26]:
statesConv.duplicated().sum()

903

In [23]:
statesConv.shape

(2452848, 8)

### CIM

In [5]:
statesCim = pd.read_csv("https://data.colorado.gov/api/views/5wyf-xqw7/rows.csv?accessType=DOWNLOAD")

In [6]:
statesCim.shape

(2452848, 8)

In [7]:
statesCim.head()

,entityId,documentId,fein,name,stateAbbreviation,authorizedSoliciting,registrantTypeAbbr,registrantType
0,20023004698,20033009607,390983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,MN,NaN,CO,Charitable Organization
1,20023004698,20033009607,390983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,MO,NaN,CO,Charitable Organization
2,20023004698,20033009607,390983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,MS,NaN,CO,Charitable Organization
3,20023004698,20033009607,390983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,NC,NaN,CO,Charitable Organization
4,20023004698,20033009607,390983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,NH,NaN,CO,Charitable Organization

In [31]:
statesCim.duplicated().sum()

903

### Compares

In [65]:
statesOrig = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_source/states.tsv",sep="\t",encoding="latin")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (0,1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [69]:
statesConv = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_transformed/state.csv")

In [95]:
statesCim = pd.read_csv("https://data.colorado.gov/api/views/5wyf-xqw7/rows.csv?accessType=DOWNLOAD")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (0,1,2) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [97]:
print(f"Orig: {statesOrig.shape}")
print(f"Conv: {statesConv.shape}")
print(f" CIM: {statesCim.shape}")
print(f"Conv - Orig: {statesConv.shape[0] - statesOrig.shape[0]}")
print(f"Conv -  CIM: {statesConv.shape[0] - statesCim.shape[0]}")

Orig: (2457707, 7)
Conv: (2457707, 8)
 CIM: (2457707, 8)
Conv - Orig: 0
Conv -  CIM: 0

## Communication Methods Used in Solicitation Campaigns in Colorado
w6kb-3vsj

### Original

In [35]:
solTypEntOrig = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_source/sol_typ_entity.tsv",sep="\t",encoding="latin")

In [36]:
solTypEntOrig.dtypes

Entity Id           int64
Document Id        object
Ce Fein           float64
Org Name           object
Sol Type Dscrp     object
dtype: object

In [37]:
analyzeDF(solTypEntOrig)

(2448, 5)

                # rows   int  str-all  str-num  str-str   NaN
Entity Id         2448  2448        0        0        0     0
Document Id       2448     0     2448     2446        2     0
Ce Fein           2448     0        0        0        0  2448
Org Name          2448     0     2448        0     2448     0
Sol Type Dscrp    2448     0     2448        0     2448     0

# Rows All Data Missing:  0

In [6]:
solTypEntOrig.head()

,Entity Id,Ce Acct Id,Ce Fein,Org Name,Sol Type Dscrp
0,20023003236,20023003236,NaN,ARIA COMMUNICATIONS CORPORATION,TELEPHONE
1,20023003632,20023003632,NaN,"CIVIC DEVELOPMENT GROUP, LLC",TELEPHONE
2,20023003238,20023003238,NaN,"TROOPER PUBLICATIONS WEST, INC.",ADVERTISEMENTS/COUPON BOOKS
3,20023003283,20023003283,NaN,COMMUNITY OUTREACH,DIRECT MAIL
4,20023003560,20023003560,NaN,"COMMUNITY SAFETY, LLC",TELEPHONE

In [ ]:
solTypEntOrig.isna().sum()

In [ ]:
solTypEntOrig.columns

### Local Converted

In [74]:
solTypEntConv = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_transformed/sol_typ_entity.csv")

In [75]:
solTypEntConv.head()

,entityId,documentId,orgName,solTypeDscrp
0,20023003236,20023003236,ARIA COMMUNICATIONS CORPORATION,TELEPHONE
1,20023003632,20023003632,"CIVIC DEVELOPMENT GROUP, LLC",TELEPHONE
2,20023003238,20023003238,"TROOPER PUBLICATIONS WEST, INC.",ADVERTISEMENTS/COUPON BOOKS
3,20023003283,20023003283,COMMUNITY OUTREACH,DIRECT MAIL
4,20023003560,20023003560,"COMMUNITY SAFETY, LLC",TELEPHONE

In [40]:
solTypEntConv.isna().sum()

entityId        0
documentId      0
orgName         0
solTypeDscrp    0
dtype: int64

In [41]:
solTypEntConv.shape

(2448, 4)

In [42]:
analyzeDF(solTypEntConv)

(2448, 4)

              # rows   int  str-all  str-num  str-str  NaN
entityId        2448  2448        0        0        0    0
documentId      2448     0     2448     2446        2    0
orgName         2448     0     2448        0     2448    0
solTypeDscrp    2448     0     2448        0     2448    0

# Rows All Data Missing:  0

### CIM

In [8]:
solTypEntCIM = pd.read_csv("https://data.colorado.gov/api/views/w6kb-3vsj/rows.csv?accessType=DOWNLOAD")

In [9]:
solTypEntCIM.shape

(2448, 4)

In [10]:
solTypEntCIM.head()

,entityId,documentId,name,communicationType
0,20023003236,20023003236,ARIA COMMUNICATIONS CORPORATION,TELEPHONE
1,20023003632,20023003632,"CIVIC DEVELOPMENT GROUP, LLC",TELEPHONE
2,20023003238,20023003238,"TROOPER PUBLICATIONS WEST, INC.",ADVERTISEMENTS/COUPON BOOKS
3,20023003283,20023003283,COMMUNITY OUTREACH,DIRECT MAIL
4,20023003560,20023003560,"COMMUNITY SAFETY, LLC",TELEPHONE

In [50]:
solTypEntCIM.isna().sum()

entityId             0
documentId           0
name                 0
communicationType    0
dtype: int64

### Compares

In [38]:
solTypEntOrig = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_source/sol_typ_entity.tsv",sep="\t",encoding="latin")

In [39]:
solTypEntConv = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_transformed/sol_typ_entity.csv")

In [98]:
solTypEntCIM = pd.read_csv("https://data.colorado.gov/api/views/w6kb-3vsj/rows.csv?accessType=DOWNLOAD")

In [100]:
print(f"Orig: {solTypEntOrig.shape}")
print(f"Conv: {solTypEntConv.shape}")
print(f" CIM: {solTypEntCIM.shape}")
print(f"Conv - Orig: {solTypEntConv.shape[0] - solTypEntOrig.shape[0]}")
print(f"Conv -  CIM: {solTypEntConv.shape[0] - solTypEntCIM.shape[0]}")

Orig: (2448, 5)
Conv: (2448, 4)
 CIM: (2448, 4)
Conv - Orig: 0
Conv -  CIM: 0

## Other Names a Registered Entity Uses to Solicit Contributions
q2av-rpr5

### Original

In [21]:
doingBusAsOrig = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_source/doing_bus_as.txt",sep="\t",encoding="latin")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [22]:
doingBusAsOrig.shape

(144315, 5)

In [53]:
doingBusAsOrig.head()

,Entity Id,Document Id,Ce Fein,Org Name,Cd Dba
0,20023004698,20033009607,39-0983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,MILITARY ORDER OF THE PURPLE HEART
1,20023004698,20033009607,39-0983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,PURPLE HEART VETERANS
2,20023004698,20033009607,39-0983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,PURPLE HEART
3,20023004698,20033009607,39-0983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,PURPLE HEART SERVICE FOUNDATION
4,20033005903,20033009688,56-0942853,POPULATION SERVICES INTERNATIONAL,PSI

### Local Converted

In [78]:
doingBusAsConv = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_transformed/doing_bus_as.csv")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [79]:
doingBusAsConv.head()

,entityId,documentId,fein,name,otherName
0,20023004698,20033009607,390983584.0,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,MILITARY ORDER OF THE PURPLE HEART
1,20023004698,20033009607,390983584.0,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,PURPLE HEART VETERANS
2,20023004698,20033009607,390983584.0,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,PURPLE HEART
3,20023004698,20033009607,390983584.0,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,PURPLE HEART SERVICE FOUNDATION
4,20033005903,20033009688,560942853.0,POPULATION SERVICES INTERNATIONAL,PSI

In [56]:
doingBusAsConv.shape

(144156, 5)

In [11]:
doingBusAsConv.dtypes

entityId       int64
acctId        object
fein         float64
name          object
otherName     object
dtype: object

In [12]:
doingBusAsConv.isna().sum()

entityId        0
acctId          0
fein         1684
name            0
otherName     301
dtype: int64

In [13]:
doingBusAsConv["acctId"].value_counts()

20163031191    876
20173009492    876
20183016536    874
20193025686    744
20203023452    744
              ...
20223026690      1
20053001587      1
20193012265      1
20133040679      1
20133018998      1
Name: acctId, Length: 69111, dtype: int64

### CIM

In [23]:
doingBusAsCIM = pd.read_csv("https://data.colorado.gov/api/views/q2av-rpr5/rows.csv?accessType=DOWNLOAD")

In [24]:
doingBusAsOrig.shape

(144315, 5)

In [25]:
doingBusAsCIM.shape

(144156, 5)

In [16]:
doingBusAsCIM.head()

,entityId,documentId,fein,name,otherName
0,20023004698,20033009607,390983584.0,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,MILITARY ORDER OF THE PURPLE HEART
1,20023004698,20033009607,390983584.0,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,PURPLE HEART VETERANS
2,20023004698,20033009607,390983584.0,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,PURPLE HEART
3,20023004698,20033009607,390983584.0,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,PURPLE HEART SERVICE FOUNDATION
4,20033005903,20033009688,560942853.0,POPULATION SERVICES INTERNATIONAL,PSI

### Compares

In [47]:
doingBusAsOrig = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_source/doing_bus_as.tsv",sep="\t",encoding="latin")

In [48]:
doingBusAsConv = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_transformed/doing_bus_as.csv")

In [101]:
doingBusAsCIM = pd.read_csv("https://data.colorado.gov/api/views/q2av-rpr5/rows.csv?accessType=DOWNLOAD")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [103]:
print(f"Orig: {doingBusAsOrig.shape}")
print(f"Conv: {doingBusAsConv.shape}")
print(f" CIM: {doingBusAsCIM.shape}")
print(f"Conv - Orig: {doingBusAsConv.shape[0] - doingBusAsOrig.shape[0]}")
print(f"Conv -  CIM: {doingBusAsConv.shape[0] - doingBusAsCIM.shape[0]}")

Orig: (144315, 5)
Conv: (144315, 5)
 CIM: (144315, 5)
Conv - Orig: 0
Conv -  CIM: 0

## Paid Solicitors Disclosed on Charity Registration Forms in Colorado
wwbh-7bpa

### Original File

In [68]:
charOrgsSolOrig = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_source/char_orgs_sol.tsv",sep="\t",encoding="latin")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [69]:
charOrgsSolOrig.shape

(46115, 24)

In [70]:
charOrgsSolOrig.head()

,Entity Id,Document Id,Ce Fein,Org Name,Ol Org Name,Ol Title,Ol Fname,Ol Mname,Ol Lname,Person Type,...,Ce Name,Ol Maddr,Ol Mcity,Ol Mstate,Ol Mzip,Ol Waddr,Ol Wcity,Ol Wstate,Ol Wzip,Ol Wphone
0,20023003049,20023003049,84-0405244,"BOY SCOUTS OF AMERICA, ROCKY MOUNTAIN COUNCIL",BIRKHOLM DIRECT,NaN,NaN,NaN,NaN,PFC,...,"BOY SCOUTS OF AMERICA, ROCKY MOUNTAIN COUNCIL",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20023003285,20023003285,84-1477546,METRO DENVER BLACK CHURCH INITIATIVE,JANINE VANDERBURG ASSOCIATES,MRS.,NaN,NaN,NaN,PFC,...,METRO DENVER BLACK CHURCH INITIATIVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20023003306,20023003306,84-0536045,"DENVER MONTESSORI SOCIETY, INC.",THE ROBERT B SHARP COMPANY OF CO,NaN,NaN,NaN,NaN,PFC,...,"DENVER MONTESSORI SOCIETY, INC.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20023003198,20023003198,74-2319180,FOOTHILLS GATEWAY REHABILITATION CENTER CHARIT...,NaN,DIRECTOR,JAMIE,NaN,MOYER,PFC,...,FOOTHILLS GATEWAY REHABILITATION CENTER CHARIT...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20023002969,20023002969,84-0511458,COLORADO SYMPHONY ASSOCIATION,PHOENIX RESOURCE GROUP,NaN,NaN,NaN,NaN,PFC,...,COLORADO SYMPHONY ASSOCIATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Converted File

In [82]:
charOrgsSolConv = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_transformed/char_orgs_sol.csv")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (1,19) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [83]:
charOrgsSolConv.shape

(46186, 27)

In [84]:
charOrgsSolConv.head()

,entityId,documentId,fein,name,nameofPS-PFC-CCV,title,firstName,middleName,lastName,registrantTypeAbbr,registrantType,address,city,state,zipCode,zipCode4,mailingAddress,mailingCity,mailingState,mailingZipCode,mailingZipCode4,performedAddress,performedCity,performedState,performedZipCode,performedZipCode4,phone
0,20023004698,20033009607,390983584,MILITARY ORDER OF THE PURPLE HEART SERVICE FOU...,AMERICAN TRADE AND CONVENTION PUBLI,NaN,NaN,NaN,NaN,PFC,NaN,"312 EAST WISCONSIN AVE, SUITE 601",Milwaukee,WI,53202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20023003251,20033009617,846038762,DENVER RESCUE MISSION,RUSS REID,PROFESSIONAL FUNDRAISING ORG.,NaN,NaN,NaN,PFC,NaN,TWO NORTH LAKE AVENUE,Pasadena,CA,91101186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20043000340,20043000340,132535763,ACCION INTERNATIONAL,LAUTMAN & COMPANY,NaN,NaN,NaN,NaN,PFC,NaN,"1730 RHODE ISLAND AVE, NW, #700",Washington,DC,20036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20023003940,20033009624,362222693,PIONEER CLUBS,MDS COMMUNICATIONS,NaN,NaN,NaN,NaN,PFC,NaN,24 W JUANITA AVE,Mesa,AZ,85210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20021314382,20033009561,237325778,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.","WARFIELD & WALSH, INC.",NaN,NaN,NaN,NaN,PFC,NaN,701 PRINCE STREET,Alexandria,VA,22314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
charOrgsSolConv["zipCode4"].value_counts()

3018.0    134
3807.0     51
1868.0     40
5102.0     30
4924.0     22
         ...
1528.0      1
1181.0      1
4347.0      1
1499.0      1
40.0        1
Name: zipCode4, Length: 244, dtype: int64

In [75]:
charOrgsSolConv.dtypes

entityId                int64
documentId             object
fein                    int64
name                   object
nameofPS-PFC-CCV       object
title                  object
firstName              object
middleName             object
lastName               object
registrantTypeAbbr     object
registrantType        float64
address                object
city                   object
state                  object
zipCode                object
zipCode4              float64
mailingAddress         object
mailingCity            object
mailingState          float64
mailingZipCode         object
mailingZipCode4       float64
performedAddress       object
performedCity          object
performedState         object
performedZipCode       object
performedZipCode4     float64
phone                 float64
dtype: object

### CIM

In [81]:
charOrgsSolCIM = pd.read_csv("https://data.colorado.gov/api/views/wwbh-7bpa/rows.csv?accessType=DOWNLOAD")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (1,19) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [82]:
charOrgsSolCIM.shape

(46115, 27)

In [83]:
charOrgsSolCIM.head()

,entityId,documentId,fein,name,nameofPS-PFC-CCV,title,firstName,middleName,lastName,registrantTypeAbbr,...,mailingCity,mailingState,mailingZipCode,mailingZipCode4,performedAddress,performedCity,performedState,performedZipCode,performedZipCode4,phone
0,20023003049,20023003049,840405244,"BOY SCOUTS OF AMERICA, ROCKY MOUNTAIN COUNCIL",BIRKHOLM DIRECT,NaN,NaN,NaN,NaN,PFC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20023003285,20023003285,841477546,METRO DENVER BLACK CHURCH INITIATIVE,JANINE VANDERBURG ASSOCIATES,MRS.,NaN,NaN,NaN,PFC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20023003306,20023003306,840536045,"DENVER MONTESSORI SOCIETY, INC.",THE ROBERT B SHARP COMPANY OF CO,NaN,NaN,NaN,NaN,PFC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20023003198,20023003198,742319180,FOOTHILLS GATEWAY REHABILITATION CENTER CHARIT...,NaN,DIRECTOR,Jamie,NaN,Moyer,PFC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20023002969,20023002969,840511458,COLORADO SYMPHONY ASSOCIATION,PHOENIX RESOURCE GROUP,NaN,NaN,NaN,NaN,PFC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Compares

In [52]:
charOrgsSolOrig = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_source/char_orgs_sol.tsv",sep="\t",encoding="latin")

In [53]:
charOrgsSolConv = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_transformed/char_orgs_sol.csv")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (19) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [104]:
charOrgsSolCIM = pd.read_csv("https://data.colorado.gov/api/views/wwbh-7bpa/rows.csv?accessType=DOWNLOAD")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (1,19) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [106]:
print(f"Orig: {charOrgsSolOrig.shape}")
print(f"Conv: {charOrgsSolConv.shape}")
print(f" CIM: {charOrgsSolCIM.shape}")
print(f"Conv - Orig: {charOrgsSolConv.shape[0] - charOrgsSolOrig.shape[0]}")
print(f"Conv -  CIM: {charOrgsSolConv.shape[0] - charOrgsSolCIM.shape[0]}")

Orig: (46186, 24)
Conv: (46186, 27)
 CIM: (46186, 27)
Conv - Orig: 0
Conv -  CIM: 0

## Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado (reg_finan)

### Original File

In [34]:
regFinanOrig = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_source/reg_finan.tsv",sep="\t",encoding="latin")

/tmp/ipykernel_1765/2450480401.py:1: DtypeWarning: Columns (4,5,12,20,28,57,58,59,60,72,73,74,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  regFinanOrig = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_source/reg_finan.tsv",sep="\t",encoding="latin")

In [36]:
for col in sorted(regFinanOrig.columns):
    print(col)

Ce A1sign
Ce A1sign Date
Ce A2sign
Ce A2sign Date
Ce Actual Flg
Ce Cnty
Ce Cons Flg
Ce Country
Ce Date Paid
Ce Fax
Ce Fein
Ce File Date
Ce Maddr
Ce Maddr2
Ce Mail Zip
Ce Mcity
Ce Mcountry
Ce Mprovince
Ce Mstate
Ce Org Fy Ends
Ce Org Fy Start
Ce Org Txdduc Flg
Ce Org Txmpt Code
Ce Org Txmpt Date
Ce Org Txmpt Flg
Ce Paddr
Ce Paddr2
Ce Parent Id
Ce Pbc Flg
Ce Pcity
Ce Phone
Ce Province
Ce Ps Coi Affirm
Ce Ps Coi Flg
Ce Pstate
Ce Pzip
Ce Renew Due
Ce Url
Current Status
Date Formed
Document Id
Entity Id
Entity Type
Expiration Date
Filing Type
Legal Form
Ntee Dscrp
Ntee Dscrp2
Ntee Dscrp3
Of Begin Taxyr
Of Endng Taxyr
Of Exoorg Flg
Of Fr Prcnt1
Of Fr Prcnt2
Of Oorg Flg
Of Oorg Name
Of Pbc Location
Of Pbc Method
Of Pbc Promo
Of Pbc Rpt Sent
Of Pf Fees
Of Py Cntrbs
Of Py Frcosts
Of Py Mcosts
Of Txddct Flg
Of Txstmt Flg
Org Name
Os Eoy Ass
Os Eoy Liab
Os Exp Admn
Os Exp Comment
Os Exp Fundr
Os Exp Othr
Os Exp Payaff
Os Exp Pserv
Os Net Ass
Os Perm Ass
Os Rev Cntrb
Os Rev Evnts
Os Rev Grnts
Os Rev Inv
Os Rev Othr
Os Rev Pserv
Os Rev Sales
Os Temp Ass
Os Tot Exp
Os Tot Rev
Os Unrstr Ass
Place Formed
Program Services Ratio
Status Date

In [16]:
regFinanOrig.shape

(212045, 94)

In [17]:
regFinanOrig.columns

Index(['Entity Id', 'Entity Type', 'Org Name', 'Ce Fein', 'Document Id',
       'Ce Parent Id', 'Filing Type', 'Ce Actual Flg', 'Ce Paddr', 'Ce Paddr2',
       'Ce Pcity', 'Ce Pstate', 'Ce Province', 'Ce Pzip', 'Ce Cnty',
       'Ce Country', 'Ce Maddr', 'Ce Maddr2', 'Ce Mcity', 'Ce Mstate',
       'Ce Mprovince', 'Ce Mail Zip', 'Ce Mcountry', 'Ce Phone', 'Ce Fax',
       'Ce Url', 'Ce A1sign', 'Ce A1sign Date', 'Ce A2sign', 'Ce A2sign Date',
       'Ce File Date', 'Ce Date Paid', 'Ce Renew Due', 'Ce Org Fy Start',
       'Ce Org Fy Ends', 'Ntee Dscrp', 'Ntee Dscrp2', 'Ntee Dscrp3',
       'Ce Org Txmpt Flg', 'Ce Org Txmpt Code', 'Ce Org Txmpt Date',
       'Ce Org Txdduc Flg', 'Ce Ext Flg', 'Ce Cons Flg', 'Ce Pbc Flg',
       'Of Begin Taxyr', 'Of Endng Taxyr', 'Of Pf Fees', 'Of Py Cntrbs',
       'Of Py Frcosts', 'Of Py Mcosts', 'Of Fr Prcnt1', 'Of Fr Prcnt2',
       'Of Oorg Name', 'Of Oorg Flg', 'Of Exoorg Flg', 'Of Txddct Flg',
       'Of Txstmt Flg', 'Of Pbc Method', 'Of Pbc Promo', 'Of Pbc Shr Flg',
       'Of Pbc Shr Num', 'Of Pbc Rpt Sent', 'Of Pbc Location', 'Os Rev Cntrb',
       'Os Rev Grnts', 'Os Rev Pserv', 'Os Rev Inv', 'Os Rev Evnts',
       'Os Rev Sales', 'Os Rev Othr', 'Os Tot Rev', 'Os Exp Pserv',
       'Os Exp Admn', 'Os Exp Fundr', 'Os Exp Payaff', 'Os Exp Othr',
       'Os Exp Comment', 'Os Tot Exp', 'Os Eoy Ass', 'Os Eoy Liab',
       'Os Net Ass', 'Os Unrstr Ass', 'Os Temp Ass', 'Os Perm Ass',
       'Ce Ps Coi Flg', 'Ce Ps Coi Affirm', 'Legal Form', 'Place Formed',
       'Date Formed', 'Current Status', 'Status Date', 'Expiration Date',
       'Program Services Ratio'],
      dtype='object')

In [46]:
regFinanOrig.loc[regFinanOrig["Document Id"] == 20173039865,['Entity Id','Org Name', 'Of Begin Taxyr','Of Endng Taxyr']]

,Entity Id,Org Name,Of Begin Taxyr,Of Endng Taxyr
174110,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20160101.0,20161231.0
174111,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20170101.0,20170930.0

In [52]:
regFinanOrig.loc[regFinanOrig["Entity Id"] ==20153043885 ,['Entity Id','Org Name', 'Document Id','Of Begin Taxyr','Of Endng Taxyr']]

,Entity Id,Org Name,Document Id,Of Begin Taxyr,Of Endng Taxyr
174108,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20153043885,20140101.0,20141231.0
174109,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20163038851,20150101.0,20151231.0
174110,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20173039865,20160101.0,20161231.0
174111,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20173039865,20170101.0,20170930.0
174112,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20183029893,20170101.0,20170930.0
174113,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20193028030,20171001.0,20180930.0
174114,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20203024224,20181001.0,20190930.0
174115,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20213024127,20191001.0,20200930.0
174116,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20223025333,20201001.0,20210930.0
174117,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20233007986,NaN,NaN

In [9]:
regFinanOrig['Ce Org Fy Start'].value_counts()

01-01    118125
07-01     44157
10-01     11490
09-01      5235
06-01      5101
04-01      4982
08-01      4303
05-01      2967
02-01      2589
03-01      1980
11-01      1970
12-01      1241
Name: Ce Org Fy Start, dtype: int64

In [11]:
regFinanOrig['Ce Org Fy Ends'].value_counts()

12-31    125384
06-31     44562
09-31     11040
08-31      4505
05-31      4259
03-31      4244
07-31      3612
04-31      2126
01-31      1586
10-31      1433
02-31       768
11-31       622
Name: Ce Org Fy Ends, dtype: int64

In [87]:
regFinanOrig.head()

,Entity Id,Entity Type,Org Name,Ce Fein,Document Id,Ce Parent Id,Filing Type,Ce Actual Flg,Ce Paddr,Ce Paddr2,...,Os Perm Ass,Ce Ps Coi Flg,Ce Ps Coi Affirm,Legal Form,Place Formed,Date Formed,Current Status,Status Date,Expiration Date,Program Services Ratio
0,20023003049,CO,"ROCKY MOUNTAIN COUNCIL, INC BOY SCOUTS OF AMERICA",84-0405244,20163024997,20153023046,RENEWAL,Y,411 SOUTH PUEBLO BLVD,NaN,...,0,NaN,NaN,CORPORATION,CO,19180827.0,NOTICE 3,20210816,08/15/21,0.78551
1,20023003049,CO,"ROCKY MOUNTAIN COUNCIL, INC BOY SCOUTS OF AMERICA",84-0405244,20173019313,20163024997,RENEWAL,Y,411 SOUTH PUEBLO BLVD,NaN,...,0,NaN,NaN,CORPORATION,CO,19180827.0,NOTICE 3,20210816,08/15/21,0.81116
2,20023003049,CO,"ROCKY MOUNTAIN COUNCIL, INC BOY SCOUTS OF AMERICA",84-0405244,20183030583,20173019313,RENEWAL,Y,411 SOUTH PUEBLO BLVD,NaN,...,0,NaN,NaN,CORPORATION,CO,19180827.0,NOTICE 3,20210816,08/15/21,0.81213
3,20023003049,CO,"ROCKY MOUNTAIN COUNCIL, INC BOY SCOUTS OF AMERICA",84-0405244,20193023161,20183030583,RENEWAL,Y,411 SOUTH PUEBLO BLVD,NaN,...,"303,611",NaN,NaN,CORPORATION,CO,19180827.0,NOTICE 3,20210816,08/15/21,0.79193
4,20023003049,CO,"ROCKY MOUNTAIN COUNCIL, INC BOY SCOUTS OF AMERICA",84-0405244,20203025236,20193023161,RENEWAL,Y,411 SOUTH PUEBLO BLVD,NaN,...,"303,611",NaN,NaN,CORPORATION,CO,19180827.0,NOTICE 3,20210816,08/15/21,0.79193

In [106]:
print(regFinanOrig["Date Formed"].value_counts())
print(regFinanOrig["Date Formed"].isna().sum())

19930701.0    264
19461101.0    215
20000101.0    182
19930413.0    170
19840101.0    162
             ...
20060116.0      1
20220119.0      1
18880223.0      1
19890505.0      1
19921130.0      1
Name: Date Formed, Length: 12453, dtype: int64
4713

In [71]:
regFinanOrig["Document Id"].value_counts()

20163000859    3
20163005436    2
20203027750    2
20163000388    2
20213008202    2
              ..
20153021445    1
20223027030    1
20173013311    1
20123045000    1
20173029376    1
Name: Document Id, Length: 211868, dtype: int64

In [22]:
missingAnal(regFinanOrig,2)

Total Rows:  212609
Column                           missing   %-miss   Type
-------------------------------------------------------------

                    Column # missing   % missing     Type
0                Ce A1sign       438    0.206012   object
1           Ce A1sign Date       438    0.206012  float64
2                Ce A2sign    209363   98.473254   object
3           Ce A2sign Date    209358   98.470902  float64
4            Ce Actual Flg      4223    1.986275   object
5                  Ce Cnty     11731    5.517640   object
6              Ce Cons Flg         0    0.000000   object
7               Ce Country      4914    2.311285   object
8             Ce Date Paid      4108    1.932185  float64
9               Ce Ext Flg         0    0.000000   object
10                  Ce Fax     89530   42.110165   object
11                 Ce Fein      2798    1.316031   object
12            Ce File Date         8    0.003763  float64
13                Ce Maddr    118208   55.598775   object
14               Ce Maddr2    199518   93.842688   object
15             Ce Mail Zip    118164   55.578080   object
16                Ce Mcity    118170   55.580902   object
17             Ce Mcountry    121910   57.340000   object
18            Ce Mprovince    212552   99.973190   object
19               Ce Mstate    116748   54.912069   object
20          Ce Org Fy Ends      8061    3.791467   object
21         Ce Org Fy Start      8062    3.791937   object
22       Ce Org Txdduc Flg         0    0.000000   object
23       Ce Org Txmpt Code     10148    4.773081   object
24       Ce Org Txmpt Date     11890    5.592426   object
25        Ce Org Txmpt Flg         0    0.000000   object
26                Ce Paddr      4914    2.311285   object
27               Ce Paddr2    195025   91.729419   object
28            Ce Parent Id     25963   12.211619   object
29              Ce Pbc Flg         0    0.000000   object
30                Ce Pcity      4914    2.311285   object
31                Ce Phone      5027    2.364434   object
32             Ce Province    212465   99.932270   object
33        Ce Ps Coi Affirm    211996   99.711677   object
34           Ce Ps Coi Flg    211891   99.662291   object
35               Ce Pstate      4992    2.347972   object
36                 Ce Pzip      4918    2.313166   object
37            Ce Renew Due      1564    0.735623  float64
38                  Ce Url     41649   19.589481   object
39          Current Status         0    0.000000   object
40             Date Formed      4913    2.310815  float64
41             Document Id         0    0.000000   object
42               Entity Id         0    0.000000    int64
43             Entity Type         0    0.000000   object
44         Expiration Date         0    0.000000   object
45             Filing Type       257    0.120879   object
46              Legal Form      7344    3.454228   object
47              Ntee Dscrp      8117    3.817806   object
48             Ntee Dscrp2    108579   51.069804   object
49             Ntee Dscrp3    145076   68.236058   object
50          Of Begin Taxyr      6871    3.231754  float64
51          Of Endng Taxyr      6871    3.231754  float64
52           Of Exoorg Flg      6863    3.227991   object
53            Of Fr Prcnt1    187509   88.194291  float64
54            Of Fr Prcnt2    187509   88.194291  float64
55             Of Oorg Flg      6863    3.227991   object
56            Of Oorg Name    172496   81.132972   object
57         Of Pbc Location    212269   99.840082   object
58           Of Pbc Method    212202   99.808569   object
59            Of Pbc Promo    212250   99.831145   object
60         Of Pbc Rpt Sent    212594   99.992945   object
61          Of Pbc Shr Flg    212609  100.000000  float64
62          Of Pbc Shr Num    212609  100.000000  float64
63              Of Pf Fees      8097    3.808399   object
64            Of Py Cntrbs      8087    3.803696   object
65           Of Py Frcosts      8116    3.817336   object
66            Of Py Mcosts      8115    3.816866   object
67           Of Txddct Flg      6863    3.227991   object
68           Of Txstmt Flg      6863    3.227991   object
69                Org Name         0    0.000000   object
70              Os Eoy Ass      7292    3.429770   object
71             Os Eoy Liab      7290    3.428829   object
72             Os Exp Admn      7312    3.439177   object
73          Os Exp Comment    208820   98.217855   object
74            Os Exp Fundr      7307    3.436825   object
75             Os Exp Othr     10692    5.028950   object
76           Os Exp Payaff      8515    4.005004   object
77            Os Exp Pserv      7308    3.437296   object
78              Os Net Ass      7284    3.426007   object
79             Os Perm Ass      7309    3.437766   object
80            Os Rev Cntrb      7286    3.426948   object
81            Os Rev Evnts      7365    3.464105   object
82            Os Rev Grnts      7312    3.439177   object
83              Os Rev Inv      7346    3.455169   object
84             Os Rev Othr      7320    3.442940   object
85            Os Rev Pserv      7311    3.438707   object
86            Os Rev Sales      7316    3.441058   object
87             Os Temp Ass      7310    3.438236   object
88              Os Tot Exp      7284    3.426007   object
89              Os Tot Rev      7284    3.426007   object
90           Os Unrstr Ass      7317    3.441529   object
91            Place Formed      4922    2.315048   object
92  Program Services Ratio     12407    5.835595  float64
93             Status Date         0    0.000000    int64

### Converted File

In [2]:
regFinanConv = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_transformed/reg_finan.csv")

/tmp/ipykernel_2114/3460680475.py:1: DtypeWarning: Columns (3,5,6,12,21,25,30,31,60,61,62,63,77) have mixed types. Specify dtype option on import or set low_memory=False.
  regFinanConv = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_transformed/reg_finan.csv")

In [13]:
regFinanConv.shape

(212609, 97)

In [100]:
regFinanConv["statusDate"].sort_values().unique()

array(['01/02/2004', '01/02/2017', '01/02/2018', ..., '12/31/2013',
       '12/31/2015', '12/31/2020'], dtype=object)

In [97]:
regFinanConv["expirationDate"].sort_values().unique()

array(['01/02/20', '01/03/20', '01/03/23', ..., '12/29/23', '12/31/10',
       '12/31/12'], dtype=object)

In [73]:
regFinanConv.head()

,entityId,registrantTypeAbbr,name,fein,filingType,documentId,amendmentEntityId,externalFilingFromNccs,externalFilingType,actualFinancialsProvided,...,permanentlyRestrictedAssets,conflictOfInterest,conflictOfInterestAffirmation,legalBusinessFormation,placeFormed,dateFormed,currentStatus,statusDate,expirationDate,programServiceRatio
0,20021314382,CO,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.",2.37326e+08,INITIAL REGISTRATION - ESTIMATES,20021314382,NaN,NaN,NaN,0.0,...,0.0,NaN,NaN,CORPORATION,NY,19730518.0,GOOD,20230201,02/15/24,0.79776
1,20021314382,CO,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.",2.37326e+08,RENEWAL,20033009561,20021314382,NaN,NaN,0.0,...,0.0,NaN,NaN,CORPORATION,NY,19730518.0,GOOD,20230201,02/15/24,0.78544
2,20021314382,CO,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.",2.37326e+08,RENEWAL,20043009759,20033009561,NaN,NaN,0.0,...,0.0,NaN,NaN,CORPORATION,NY,19730518.0,GOOD,20230201,02/15/24,0.78309
3,20021314382,CO,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.",2.37326e+08,RENEWAL,20053009471,20043009759,NaN,NaN,0.0,...,0.0,NaN,NaN,CORPORATION,NY,19730518.0,GOOD,20230201,02/15/24,0.73437
4,20021314382,CO,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.",2.37326e+08,RENEWAL,20063009958,20053009471,NaN,NaN,0.0,...,0.0,NaN,NaN,CORPORATION,NY,19730518.0,GOOD,20230201,02/15/24,0.75429

In [53]:
col = "documentId"
#regFinanConv["documentId"].tail()
regFinanConv.loc[(~regFinanConv[col].isna()) & (regFinanConv[col].str.contains("\D"))]

#regFinanConv.loc[(~regFinanConv[col].isna())].shape[0]
#regFinanConv.loc[(regFinanConv[col].str.contains("\d"))].shape[0]
#regFinanConv.loc[regFinanConv[col].str.contains("\d")]
#regFinanConv.loc[~regFinanConv[col].isna()]
#len(regFinanConv[col].unique().tolist())

15

In [54]:
x = regFinanConv[col].value_counts().to_dict()

In [66]:
totl=0
stats = {}
for ky,val in x.items():
    totl+=val
    if type(ky) in stats:
        stats[type(ky)]+=1
    else:
        stats[type(ky)]=1
        
#   print(ky,totl)
    
print(totl)

213177

In [67]:
stats

{int: 147536, str: 65465}

In [68]:
regFinanConv[col].dtypes

dtype('O')

In [70]:
import numpy as np

In [76]:
regFinanConv.loc[~regFinanConv["documentId"].str.isnumeric().isna()].shape
regFinanConv.loc[~regFinanConv["documentId"].str.isnumeric().isna()].shape

(65536, 94)

In [7]:
col = "documentId"
tmp = regFinanConv.loc[regFinanConv.apply(pd.to_numeric, errors="ignore").applymap(lambda x: isinstance(x, int), na_action='ignore'),col]

ValueError: Cannot index with multidimensional key

In [12]:
regFinanConv.loc[regFinanConv.apply(pd.to_numeric, errors="ignore").applymap(lambda x: isinstance(x, str), na_action='ignore')[col],col]

0         20133014356
1         20143023994
2         20153023046
3         20163024997
4         20173019313
             ...
122875    20223012650
122876    20233012322
122877    20093010088
122878    20093013628
122879    20103031080
Name: documentId, Length: 65536, dtype: object

In [17]:
regFinanConv.loc[regFinanConv[col].apply(lambda x: isinstance(x,str)),col]

0         20133014356
1         20143023994
2         20153023046
3         20163024997
4         20173019313
             ...
122875    20223012650
122876    20233012322
122877    20093010088
122878    20093013628
122879    20103031080
Name: documentId, Length: 65536, dtype: object

In [81]:
a = regFinanConv["documentId"].apply(type).value_counts().to_dict()

In [85]:
for k in a:
    print(k)

<class 'int'>
<class 'str'>

In [89]:
a

{int: 147641, str: 65536}

In [94]:

if int in a:
    print("hit",a[int])

hit 147641

In [80]:
for col in regFinanConv.columns:
    print(col,regFinanConv[col].apply(type).value_counts().to_dict())

entityId {<class 'int'>: 213177}
registrantTypeAbbr {<class 'str'>: 213177}
name {<class 'str'>: 213177}
fein {<class 'float'>: 196802, <class 'int'>: 8192, <class 'str'>: 8183}
filingType {<class 'str'>: 212913, <class 'float'>: 264}
documentId {<class 'int'>: 147641, <class 'str'>: 65536}
amendmentEntityId {<class 'float'>: 152152, <class 'str'>: 61025}
actualFinancialsProvided {<class 'float'>: 213177}
principalAddress {<class 'str'>: 208028, <class 'float'>: 5149}
principalAddress2 {<class 'float'>: 195538, <class 'str'>: 17639}
principalCity {<class 'str'>: 208028, <class 'float'>: 5149}
principalState {<class 'str'>: 207949, <class 'float'>: 5228}
principalProvince {<class 'float'>: 213031, <class 'str'>: 146}
residentialCounty {<class 'str'>: 201205, <class 'float'>: 11972}
principalCountry {<class 'str'>: 208028, <class 'float'>: 5149}
principalZipcode {<class 'str'>: 208024, <class 'float'>: 5153}
principalZipcode4 {<class 'float'>: 213177}
mailingAddress {<class 'float'>: 118569, <class 'str'>: 94608}
mailingAddress2 {<class 'float'>: 200028, <class 'str'>: 13149}
mailingCity {<class 'float'>: 118531, <class 'str'>: 94646}
mailingState {<class 'float'>: 117109, <class 'str'>: 96068}
mailingProvince {<class 'float'>: 213120, <class 'str'>: 57}
mailingZipcode {<class 'float'>: 118525, <class 'str'>: 94652}
mailingZipcode4 {<class 'float'>: 213177}
mailingCountry {<class 'float'>: 122296, <class 'str'>: 90881}
phone {<class 'float'>: 205114, <class 'str'>: 8063}
fax {<class 'float'>: 213177}
website {<class 'str'>: 169086, <class 'float'>: 44091}
authorizedOfficerName {<class 'str'>: 212739, <class 'float'>: 438}
authorizedOfficerSignedDate {<class 'str'>: 212739, <class 'float'>: 438}
cfoName {<class 'float'>: 209931, <class 'str'>: 3246}
cfoSignedDate {<class 'float'>: 209926, <class 'str'>: 3251}
registrationApprovedDate {<class 'str'>: 213169, <class 'float'>: 8}
paymentProcessedDate {<class 'str'>: 208837, <class 'float'>: 4340}
nextRenewalRegistrationDate {<class 'str'>: 211602, <class 'float'>: 1575}
fiscalYearStartDate {<class 'str'>: 204868, <class 'float'>: 8309}
fiscalYearEndDate {<class 'str'>: 204869, <class 'float'>: 8308}
NTEECode1 {<class 'str'>: 204813, <class 'float'>: 8364}
NTEECode2 {<class 'float'>: 109006, <class 'str'>: 104171}
NTEECode3 {<class 'float'>: 145563, <class 'str'>: 67614}
taxExemptStatus {<class 'int'>: 213177}
taxExemptCode {<class 'str'>: 202779, <class 'float'>: 10398}
IRSDeterminationDate {<class 'float'>: 173265, <class 'str'>: 39912}
donationsTaxDeductible {<class 'int'>: 213177}
extensionFiled {<class 'int'>: 213177}
consolidatedRegistrationStatement {<class 'int'>: 213177}
publicBenefitCorporation {<class 'float'>: 213177}
reportingPeriodBegin {<class 'str'>: 206067, <class 'float'>: 7110}
reportingPeriodEnd {<class 'str'>: 206067, <class 'float'>: 7110}
outsideProfessionalFundraiserFees {<class 'float'>: 213177}
totalContributionsRaisedPreviousYear {<class 'float'>: 213177}
totalFundraisingExpensesPreviousYear {<class 'float'>: 213177}
totalManagementGeneralExpensesPreviousYear {<class 'float'>: 213177}
expensesDividedByContributions {<class 'float'>: 213177}
totalExpensesPlusManagementGeneralDividedByContributions {<class 'float'>: 213177}
relatedOrganizationName {<class 'float'>: 173004, <class 'str'>: 40173}
relatedToOtherOrganization {<class 'float'>: 213177}
relatedOrganizationTaxExempt {<class 'float'>: 213177}
solicitedNonTaxDeductibleGifts {<class 'float'>: 213177}
statedGiftNotTaxDeductible {<class 'float'>: 213177}
pbcRecordingMethod {<class 'float'>: 212770, <class 'str'>: 407}
pbcPromotedBenifit {<class 'float'>: 212818, <class 'str'>: 359}
pbcBenefitReportSent {<class 'float'>: 213162, <class 'str'>: 15}
pbcAnnualBenefitReport {<class 'float'>: 212837, <class 'str'>: 340}
revenueFromContibutions {<class 'float'>: 213177}
revenueFromGovernment {<class 'float'>: 213177}
programServiceRevenue {<class 'float'>: 213177}
revenueFromInvestments {<class 'float'>: 213177}
revenueFromSpecialEvents {<class 'float'>: 213177}
revenueFromSales {<class 'float'>: 213177}
revenueFromOther {<class 'float'>: 213177}
revenueTotal {<class 'float'>: 213177}
expensesFromProgramServices {<class 'float'>: 213177}
expensesFromAdministrativeOther {<class 'float'>: 213177}
expensesFundraising {<class 'float'>: 213177}
expensesAffiliates {<class 'float'>: 213177}
expensesOther {<class 'float'>: 213177}
expensesOtherComment {<class 'float'>: 209388, <class 'str'>: 3789}
expensesTotal {<class 'float'>: 213177}
endOfYearAssests {<class 'float'>: 213177}
endOfYearTotalLiabilities {<class 'float'>: 213177}
endOfYearAssestsMinusLiabilities {<class 'float'>: 213177}
unrestrictedAssests {<class 'float'>: 213177}
temporarilyRestrictedAssets {<class 'float'>: 213177}
permanentlyRestrictedAssets {<class 'float'>: 213177}
conflictOfInterest {<class 'float'>: 213177}
conflictOfInterestAffirmation {<class 'float'>: 213177}
legalBusinessFormation {<class 'str'>: 205596, <class 'float'>: 7581}
placeFormed {<class 'str'>: 208021, <class 'float'>: 5156}
dateFormed {<class 'float'>: 213177}
currentStatus {<class 'str'>: 213177}
statusDate {<class 'int'>: 213177}
expirationDate {<class 'str'>: 213177}
programServiceRatio {<class 'float'>: 213177}

In [8]:
def missingAnal(df,sort_by=1):
#  sort_by    1 = sort by % missing file, descending order
#             2 = sort by COlumn Nem
    nrows = df.shape[0]
    stats = pd.DataFrame(columns=["Column","# missing","% missing","Type"])
    print("Total Rows: ",nrows)
    print(f"{'Column':30.30s}   missing   %-miss   Type")
    print(f"-------------------------------------------------------------")
    for col in sorted(df.columns):
        nc = df[col].isna().sum()
        pp = df[col].isna().sum()/nrows*100
#        print(f"{col:30.30s}  {nc:8d}   %{pp:4.1f}   {df[col].dtype}")
        stats = stats.append(pd.DataFrame({"Column":[col],"# missing":nc,"% missing":pp,"Type":[df[col].dtype]}),ignore_index=True)
    sb = "% missing"
    asc=False
    if sort_by == 2:
        sb = "Column"
        asc=True
    stats.sort_values(by=sb,inplace=True,ascending=asc)
    display(stats)
        
missingAnal(regFinanConv)

Total Rows:  213177
Column                           missing   %-miss   Type
-------------------------------------------------------------

,Column,# missing,% missing,Type
50,pbcBenefitReportSent,213162,99.992964,object
41,mailingProvince,213120,99.973262,object
60,principalProvince,213031,99.931512,object
49,pbcAnnualBenefitReport,212837,99.840508,object
51,pbcPromotedBenifit,212818,99.831595,object
52,pbcRecordingMethod,212770,99.809079,object
11,conflictOfInterestAffirmation,212559,99.710100,float64
10,conflictOfInterest,212454,99.660845,float64
44,mailingZipcode4,210839,98.903259,float64
63,principalZipcode4,210813,98.891062,float64
8,cfoName,209931,98.477322,object
9,cfoSignedDate,209926,98.474976,object
27,expensesOtherComment,209388,98.222604,object
38,mailingAddress2,200028,93.831886,object
57,principalAddress2,195538,91.725655,object
89,totalExpensesPlusManagementGeneralDividedByCon...,188062,88.218710,float64
22,expensesDividedByContributions,188062,88.218710,float64
0,IRSDeterminationDate,173265,81.277530,object
69,relatedOrganizationName,173004,81.155096,object
3,NTEECode3,145563,68.282695,object
40,mailingCountry,122296,57.368290,object
37,mailingAddress,118569,55.619978,object
39,mailingCity,118531,55.602152,object
43,mailingZipcode,118525,55.599338,object
42,mailingState,117109,54.935101,object
2,NTEECode2,109006,51.134034,object
31,fax,87602,41.093551,float64
93,website,44091,20.682813,object
5,amendmentEntityId,26021,12.206289,object
64,programServiceRatio,12655,5.936382,float64
74,residentialCounty,11972,5.615990,object
26,expensesOther,10940,5.131886,float64
85,taxExemptCode,10398,4.877637,object
21,expensesAffiliates,8763,4.110669,float64
1,NTEECode1,8364,3.923500,object
90,totalFundraisingExpensesPreviousYear,8363,3.923031,float64
91,totalManagementGeneralExpensesPreviousYear,8362,3.922562,float64
47,outsideProfessionalFundraiserFees,8344,3.914118,float64
88,totalContributionsRaisedPreviousYear,8334,3.909427,float64
35,fiscalYearStartDate,8309,3.897700,object
34,fiscalYearEndDate,8308,3.897231,object
80,revenueFromSpecialEvents,7605,3.567458,float64
77,revenueFromInvestments,7586,3.558545,float64
36,legalBusinessFormation,7581,3.556200,object
78,revenueFromOther,7560,3.546349,float64
92,unrestrictedAssests,7557,3.544942,float64
79,revenueFromSales,7556,3.544472,float64
23,expensesFromAdministrativeOther,7552,3.542596,float64
76,revenueFromGovernment,7552,3.542596,float64
65,programServiceRevenue,7551,3.542127,float64
87,temporarilyRestrictedAssets,7550,3.541658,float64
53,permanentlyRestrictedAssets,7549,3.541189,float64
24,expensesFromProgramServices,7548,3.540720,float64
25,expensesFundraising,7547,3.540251,float64
17,endOfYearAssests,7532,3.533214,float64
19,endOfYearTotalLiabilities,7530,3.532276,float64
75,revenueFromContibutions,7526,3.530400,float64
81,revenueTotal,7524,3.529461,float64
28,expensesTotal,7524,3.529461,float64
18,endOfYearAssestsMinusLiabilities,7524,3.529461,float64
73,reportingPeriodEnd,7110,3.335257,object
72,reportingPeriodBegin,7110,3.335257,object
70,relatedOrganizationTaxExempt,7102,3.331504,float64
83,statedGiftNotTaxDeductible,7102,3.331504,float64
82,solicitedNonTaxDeductibleGifts,7102,3.331504,float64
71,relatedToOtherOrganization,7102,3.331504,float64
54,phone,5261,2.467902,object
61,principalState,5228,2.452422,object
55,placeFormed,5156,2.418647,object
62,principalZipcode,5153,2.417240,object
59,principalCountry,5149,2.415364,object
56,principalAddress,5149,2.415364,object
58,principalCity,5149,2.415364,object
14,dateFormed,5147,2.414426,float64
4,actualFinancialsProvided,4463,2.093565,float64
48,paymentProcessedDate,4340,2.035867,object
32,fein,2808,1.317215,object
46,nextRenewalRegistrationDate,1575,0.738823,object
66,publicBenefitCorporation,550,0.258002,float64
6,authorizedOfficerName,438,0.205463,object
7,authorizedOfficerSignedDate,438,0.205463,object
33,filingType,264,0.123841,object
68,registrationApprovedDate,8,0.003753,object
29,expirationDate,0,0.000000,object
30,extensionFiled,0,0.000000,int64
20,entityId,0,0.000000,int64
67,registrantTypeAbbr,0,0.000000,object
86,taxExemptStatus,0,0.000000,int64
45,name,0,0.000000,object
84,statusDate,0,0.000000,int64
16,donationsTaxDeductible,0,0.000000,int64
15,documentId,0,0.000000,object
12,consolidatedRegistrationStatement,0,0.000000,int64
13,currentStatus,0,0.000000,object

In [97]:
regFinanConv.head()

,entityId,registrantTypeAbbr,name,fein,filingType,documentId,amendmentEntityId,externalFilingFromNccs,externalFilingType,actualFinancialsProvided,...,permanentlyRestrictedAssets,conflictOfInterest,conflictOfInterestAffirmation,legalBusinessFormation,placeFormed,dateFormed,currentStatus,statusDate,expirationDate,programServiceRatio
0,20023003049,CO,"ROCKY MOUNTAIN COUNCIL, INC BOY SCOUTS OF AMERICA",8.40405e+08,RENEWAL,2.016302e+10,20153023046,NaN,NaN,1.0,...,0.0,NaN,NaN,CORPORATION,CO,19180827.0,NOTICE 3,20210816,08/15/21,0.78551
1,20023003049,CO,"ROCKY MOUNTAIN COUNCIL, INC BOY SCOUTS OF AMERICA",8.40405e+08,RENEWAL,2.017302e+10,20163024997,NaN,NaN,1.0,...,0.0,NaN,NaN,CORPORATION,CO,19180827.0,NOTICE 3,20210816,08/15/21,0.81116
2,20023003049,CO,"ROCKY MOUNTAIN COUNCIL, INC BOY SCOUTS OF AMERICA",8.40405e+08,RENEWAL,2.018303e+10,20173019313,NaN,NaN,1.0,...,0.0,NaN,NaN,CORPORATION,CO,19180827.0,NOTICE 3,20210816,08/15/21,0.81213
3,20023003049,CO,"ROCKY MOUNTAIN COUNCIL, INC BOY SCOUTS OF AMERICA",8.40405e+08,RENEWAL,2.019302e+10,20183030583,NaN,NaN,1.0,...,303611.0,NaN,NaN,CORPORATION,CO,19180827.0,NOTICE 3,20210816,08/15/21,0.79193
4,20023003049,CO,"ROCKY MOUNTAIN COUNCIL, INC BOY SCOUTS OF AMERICA",8.40405e+08,RENEWAL,2.020303e+10,20193023161,NaN,NaN,1.0,...,303611.0,NaN,NaN,CORPORATION,CO,19180827.0,NOTICE 3,20210816,08/15/21,0.79193

In [22]:
regFinanConv["fiscalYearEndDate"].head(20)

0     06-31
1     06-31
2     06-31
3     06-31
4     06-31
5     06-31
6     06-31
7     06-31
8     06-31
9     06-31
10    06-31
11    06-31
12    06-31
13    06-31
14    06-31
15    06-31
16    06-31
17    06-31
18    06-31
19    06-31
Name: fiscalYearEndDate, dtype: object

In [38]:
regFinanConv["documentId"].dtype

dtype('float64')

In [45]:
#regFinanConv.loc[regFinanConv["documentId"] == 20173039865.,["reportingPeriodBegin","reportingPeriodEnd" ]]
regFinanConv.loc[regFinanConv["entityId"] == 20153043885,["documentId","name","reportingPeriodBegin","reportingPeriodEnd" ]]

,documentId,name,reportingPeriodBegin,reportingPeriodEnd
174108,NaN,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,01/01/2014,12/31/2014
174109,NaN,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,01/01/2015,12/31/2015
174110,NaN,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,01/01/2016,12/31/2016
174111,NaN,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,01/01/2017,09/30/2017
174112,NaN,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,01/01/2017,09/30/2017
174113,NaN,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,10/01/2017,09/30/2018
174114,NaN,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,10/01/2018,09/30/2019
174115,NaN,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,10/01/2019,09/30/2020
174116,NaN,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,10/01/2020,09/30/2021
174117,NaN,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,NaN,NaN

### CIM

In [2]:
regFinanCIM = pd.read_csv("https://data.colorado.gov/api/views/37wu-kn3g/rows.csv?accessType=DOWNLOAD")

/tmp/ipykernel_517/2968904024.py:1: DtypeWarning: Columns (3,5,6,21,22,27,28,68,76,77,78,79,80,81,82,89) have mixed types. Specify dtype option on import or set low_memory=False.
  regFinanCIM = pd.read_csv("https://data.colorado.gov/api/views/37wu-kn3g/rows.csv?accessType=DOWNLOAD")

In [6]:
#regFinanCIM = pd.read_csv("https://data.colorado.gov/api/views/37wu-kn3g/rows.csv?accessType=DOWNLOAD")
regFinanCIM = pd.read_csv("Registration_of_Charities__Paid_Solicitors__Professional_Fundraising_Consultants__and_for-profit_Public_Benefit_Corporations_in_Colorado.csv")

/tmp/ipykernel_1765/3311466022.py:2: DtypeWarning: Columns (3,5,6,21,22,27,28,68,76,77,78,79,80,81,82,89) have mixed types. Specify dtype option on import or set low_memory=False.
  regFinanCIM = pd.read_csv("Registration_of_Charities__Paid_Solicitors__Professional_Fundraising_Consultants__and_for-profit_Public_Benefit_Corporations_in_Colorado.csv")

In [6]:
for col in sorted(regFinanCIM.columns):
    print(col)

IRSDeterminationDate
NTEECode1
NTEECode2
NTEECode3
actualFinancialsProvided
amendmentEntityId
authorizedOfficerName
authorizedOfficerSignedDate
cfoName
cfoSignedDate
conflictOfInterest
conflictOfInterestAffirmation
consolidatedRegistrationStatement
currentStatus
dateFormed
documentId
donationsTaxDeductible
endOfYearAssests
endOfYearAssestsMinusLiabilities
endOfYearTotalLiabilities
entityId
expensesAffiliates
expensesDividedByContributions
expensesFromAdministrativeOther
expensesFromProgramServices
expensesFundraising
expensesOther
expensesOtherComment
expensesTotal
expirationDate
extensionFiled
fax
fein
filingType
fiscalYearEndDate
fiscalYearStartDate
legalBusinessFormation
mailingAddress
mailingAddress2
mailingCity
mailingCountry
mailingProvince
mailingState
mailingZipcode
mailingZipcode4
name
nextRenewalRegistrationDate
outsideProfessionalFundraiserFees
paymentProcessedDate
pbcAnnualBenefitReport
pbcBenefitReportSent
pbcPromotedBenefit
pbcRecordingMethod
permanentlyRestrictedAssets
phone
placeFormed
principalAddress
principalCity
principalCountry
principalProvince
principalSddress2
principalState
principalZipcode
principalZipcode4
programServiceRatio
programServiceRevenue
publicBenefitCorporation
registrantTypeAbbr
registrationApprovedDate
relatedOrganizationName
relatedOrganizationTaxExempt
relatedToOtherOrganization
reportingPeriodBegin
reportingPeriodEnd
residentialCounty
revenueFromContibutions
revenueFromGovernment
revenueFromInvestments
revenueFromOther
revenueFromSales
revenueFromSpecialEvents
revenueTotal
solicitedNonTaxDeductibleGifts
statedGiftNotTaxDeductible
statusDate
taxExemptCode
taxExemptStatus
temporarilyRestrictedAssets
totalContributionsRaisedPreviousYear
totalExpensesPlusManagementGeneralDividedByContributions
totalFundraisingExpensesPreviousYear
totalManagementGeneralExpensesPreviousYear
unrestrictedAssests
website

In [7]:
col="consolidatedRegistrationStatement"
regFinanCIM[col].value_counts()

consolidatedRegistrationStatement
False    208350
True       5122
Name: count, dtype: int64

In [12]:
regFinanCIM["actualFinancialsProvided"].dtypes

dtype('O')

In [32]:
regFinanCIM["actualFinancialsProvided"].value_counts()

actualFinancialsProvided
True     176956
False     31912
Name: count, dtype: int64

In [15]:
regFinanCIM["actualFinancialsProvided"].str.contains("\d").sum()

AttributeError: Can only use .str accessor with string values!

In [30]:
regFinanCIM.head()
a,b,c,d = dfStringAnal(regFinanCIM)

entityId
registrantTypeAbbr
{<class 'str'>: 213343}
name
{<class 'str'>: 213343}
fein
{<class 'float'>: 196968, <class 'int'>: 8192, <class 'str'>: 8183}
filingType
{<class 'str'>: 213082, <class 'float'>: 261}
documentId
{<class 'int'>: 147807, <class 'str'>: 65536}
amendmentEntityId
{<class 'float'>: 152322, <class 'str'>: 61021}
actualFinancialsProvided
{<class 'bool'>: 208868, <class 'float'>: 4475}
actualFinancialsProvided error Can only use .str accessor with string values!
principalAddress
{<class 'str'>: 208179, <class 'float'>: 5164}
principalCity
{<class 'str'>: 208179, <class 'float'>: 5164}
principalState
{<class 'str'>: 208100, <class 'float'>: 5243}
principalZipcode
{<class 'str'>: 208175, <class 'float'>: 5168}
principalZipcode4
residentialCounty
{<class 'str'>: 201359, <class 'float'>: 11984}
mailingAddress
{<class 'float'>: 118657, <class 'str'>: 94686}
mailingAddress2
{<class 'float'>: 200174, <class 'str'>: 13169}
mailingCity
{<class 'float'>: 118619, <class 'str'>: 94724}
mailingState
{<class 'float'>: 117197, <class 'str'>: 96146}
mailingZipcode
{<class 'float'>: 118613, <class 'str'>: 94730}
mailingZipcode4
mailingCountry
{<class 'float'>: 122395, <class 'str'>: 90948}
mailingProvince
{<class 'float'>: 213286, <class 'str'>: 57}
phone
{<class 'float'>: 205280, <class 'str'>: 8063}
fax
website
{<class 'str'>: 169209, <class 'float'>: 44134}
authorizedOfficerName
{<class 'str'>: 212905, <class 'float'>: 438}
authorizedOfficerSignedDate
{<class 'str'>: 212905, <class 'float'>: 438}
cfoName
{<class 'float'>: 210097, <class 'str'>: 3246}
cfoSignedDate
{<class 'float'>: 210092, <class 'str'>: 3251}
registrationApprovedDate
{<class 'str'>: 213335, <class 'float'>: 8}
paymentProcessedDate
{<class 'str'>: 208991, <class 'float'>: 4352}
nextRenewalRegistrationDate
{<class 'str'>: 211767, <class 'float'>: 1576}
fiscalYearStartDate
{<class 'str'>: 205021, <class 'float'>: 8322}
fiscalYearEndDate
{<class 'str'>: 205022, <class 'float'>: 8321}
NTEECode1
{<class 'str'>: 204966, <class 'float'>: 8377}
NTEECode2
{<class 'float'>: 109094, <class 'str'>: 104249}
NTEECode3
{<class 'float'>: 145688, <class 'str'>: 67655}
taxExemptStatus
taxExemptCode
{<class 'str'>: 202274, <class 'float'>: 11069}
IRSDeterminationDate
{<class 'float'>: 173390, <class 'str'>: 39953}
donationsTaxDeductible
extensionFiled
consolidatedRegistrationStatement
reportingPeriodBegin
{<class 'str'>: 206221, <class 'float'>: 7122}
reportingPeriodEnd
{<class 'str'>: 206221, <class 'float'>: 7122}
outsideProfessionalFundraiserFees
totalContributionsRaisedPreviousYear
totalFundraisingExpensesPreviousYear
totalManagementGeneralExpensesPreviousYear
expensesDividedByContributions
totalExpensesPlusManagementGeneralDividedByContributions
relatedOrganizationName
{<class 'float'>: 173135, <class 'str'>: 40208}
relatedToOtherOrganization
{<class 'bool'>: 206229, <class 'float'>: 7114}
relatedToOtherOrganization error Can only use .str accessor with string values!
relatedOrganizationTaxExempt
{<class 'bool'>: 206229, <class 'float'>: 7114}
relatedOrganizationTaxExempt error Can only use .str accessor with string values!
solicitedNonTaxDeductibleGifts
{<class 'bool'>: 206229, <class 'float'>: 7114}
solicitedNonTaxDeductibleGifts error Can only use .str accessor with string values!
statedGiftNotTaxDeductible
{<class 'bool'>: 206229, <class 'float'>: 7114}
statedGiftNotTaxDeductible error Can only use .str accessor with string values!
revenueFromContibutions
revenueFromGovernment
programServiceRevenue
revenueFromInvestments
revenueFromSpecialEvents
revenueFromSales
revenueTotal
expensesFromProgramServices
expensesFromAdministrativeOther
expensesFundraising
expensesAffiliates
expensesOther
expensesOtherComment
{<class 'float'>: 209554, <class 'str'>: 3789}
expensesTotal
endOfYearAssests
endOfYearTotalLiabilities
endOfYearAssestsMinusLiabilities
unrestrictedAssests
temporarilyRestrictedAssets
permanentlyRestrictedAssets
publicBenefitCorporation
{<class 'bool'>: 212793, <class 'float'>: 550}
publicBenefitCorporation error Can only use .str accessor with string values!
pbcRecordingMethod
{<class 'float'>: 212934, <class 'str'>: 409}
pbcPromotedBenefit
{<class 'float'>: 212982, <class 'str'>: 361}
pbcBenefitReportSent
{<class 'float'>: 213328, <class 'str'>: 15}
pbcAnnualBenefitReport
{<class 'float'>: 213001, <class 'str'>: 342}
conflictOfInterest
{<class 'float'>: 212620, <class 'bool'>: 723}
conflictOfInterest error Can only use .str accessor with string values!
conflictOfInterestAffirmation
{<class 'float'>: 212725, <class 'bool'>: 618}
conflictOfInterestAffirmation error Can only use .str accessor with string values!
legalBusinessFormation
{<class 'str'>: 205747, <class 'float'>: 7596}
currentStatus
{<class 'str'>: 213343}
statusDate
{<class 'str'>: 213343}
revenueFromOther
principalSddress2
{<class 'float'>: 195687, <class 'str'>: 17656}
principalCountry
{<class 'str'>: 208179, <class 'float'>: 5164}
principalProvince
{<class 'float'>: 213197, <class 'str'>: 146}
placeFormed
{<class 'str'>: 208172, <class 'float'>: 5171}
dateFormed
expirationDate
{<class 'str'>: 213343}
programServiceRatio

In [ ]:
a

In [29]:
def dfStringAnal(df):
    stats = {}
    nstats = {}
    ndates={}
    nums = ["int64","float64"]
    columnsNoDate=[]
    try: 
        for col in df: 
            print(col)
            if df[col].dtypes == "object":
                try : 
                    stats[col] = {}
                    
                    stats[col]["digits"] = -1
                    stats[col]["non-digits"] = -1
                    stats[col]["numeric"] = -1
                    stats[col]["word"] = -1
        #            stats[col]["non-word"] = df["B1_PER_ID1"].str.contains("\S").sum()
                    stats[col]["non-word"] = -1
                    stats[col]["white-spc"] = -1
                    stats[col]["_"] = -1                     
                    stats[col]["-"] = -1
                    stats[col]["#"] = -1
                    stats[col]["missing"] = -1

                    columnsNoDate.append(col)
                    typs = df[col].apply(type).value_counts().to_dict()
                    print(typs)
                    
                    if str in typs:
                       stats[col]["string"] = typs[str]
                    else:
                       stats[col]["string"] = 0

                    if int in typs:
                       stats[col]["integer"] = typs[int]
                    else:
                       stats[col]["integer"] = 0

                    if float in typs:
                       stats[col]["float"] = typs[float]
                    else:
                       stats[col]["float"] = 0
                    
                    if bool in typs:
                       stats[col]["boolean"] = typs[bool]
                    else:
                       stats[col]["boolean"] = 0
                    
                    stats[col]["missing"] = df[col].isna().sum() 

                    stats[col]["digits"] = df[col].str.contains("\d").sum()
                    stats[col]["non-digits"] = df[col].str.contains("\D").sum()
                    stats[col]["numeric"] = df[col].str.replace(".","",1).str.isdecimal().sum()


                    stats[col]["word"] = df[col].str.contains("\w").sum()
        #            stats[col]["non-word"] = df["B1_PER_ID1"].str.contains("\S").sum()
                    stats[col]["non-word"] = df[col].str.contains("[^a-zA-Z0-9_ \-]").sum() 
                    stats[col]["white-spc"] = df[col].str.contains("\s").sum()   

                    stats[col]["_"] = df[col].str.contains("_").sum()                        
                    stats[col]["-"] = df[col].str.contains("-").sum()   
                    stats[col]["#"] = df[col].str.contains("#").sum() 
                except Exception as errs:
                    print(f"{col} error {errs}")
                    
            elif df[col].dtypes in nums:
                columnsNoDate.append(col)            
                amin,amax,amen,astd = df[col].agg(["min","max","mean","std"])
                nstats[col]={}
                nstats[col]["Min"] = amin
                nstats[col]["Max"] = amax
                nstats[col]["Mean"] = amen
                nstats[col]["Std"] = astd
                nstats[col]["Missing"] =df[col].isna().sum()
            else:
                ndates[col]={}
                ndates[col]["Start"] = df[col].min()
                ndates[col]["End"] = df[col].max()
                ndates[col]["# Unique Dates"] = df[col].nunique()
    except Exception as err:
        print("dfStringAnal Error")
        print(err)

            
            
            
    nrecs=0
    return stats,nstats,ndates,columnsNoDate

In [33]:
regFinanCIM["extensionFiled"].isna().sum()

213343

In [ ]:
sorted(regFinanCIM.columns)

In [102]:
regFinanCIM["statusDate"].value_counts()

Series([], Name: statusDate, dtype: int64)

In [114]:
regFinanCIM["dateFormed"].sort_values().unique()

array([   60503.,    71203.,  2000401., ..., 20230525., 20251120.,
             nan])

In [27]:
regFinanCIM[["fiscalYearStartDate","fiscalYearEndDate"]].head(20)

   fiscalYearStartDate fiscalYearEndDate
0                01-01             12-31
1                10-01             09-31
2                01-01             12-31
3                01-01             12-31
4                08-01             07-31
5                01-01             12-31
6                07-01             06-31
7                07-01             06-31
8                  NaN               NaN
9                01-01             12-31
10               10-01             09-31
11               07-01             06-31
12               01-01             12-31
13               01-01             12-31
14               07-01             06-31
15                 NaN               NaN
16               01-01             12-31
17               07-01             06-31
18               01-01             12-31
19               07-01             06-31

In [29]:
regFinanCIM[["reportingPeriodBegin","reportingPeriodEnd"]].head(20)

      reportingPeriodBegin      reportingPeriodEnd
0   01/01/2021 12:00:00 AM  12/31/2021 12:00:00 AM
1   10/01/2020 12:00:00 AM  09/30/2021 12:00:00 AM
2   01/01/2011 12:00:00 AM  12/31/2011 12:00:00 AM
3   01/01/2005 12:00:00 AM  12/31/2005 12:00:00 AM
4   08/01/2008 12:00:00 AM  07/31/2009 12:00:00 AM
5   01/01/2021 12:00:00 AM  12/31/2021 12:00:00 AM
6   07/01/2018 12:00:00 AM  06/30/2019 12:00:00 AM
7   07/01/2016 12:00:00 AM  06/30/2017 12:00:00 AM
8                      NaN                     NaN
9   01/01/2018 12:00:00 AM  12/31/2018 12:00:00 AM
10  10/01/2006 12:00:00 AM  09/30/2007 12:00:00 AM
11  07/01/2008 12:00:00 AM  06/30/2009 12:00:00 AM
12  01/01/2012 12:00:00 AM  12/31/2012 12:00:00 AM
13  01/01/2017 12:00:00 AM  12/31/2017 12:00:00 AM
14  07/01/2011 12:00:00 AM  06/30/2012 12:00:00 AM
15                     NaN                     NaN
16  01/01/2010 12:00:00 AM  12/31/2010 12:00:00 AM
17  07/01/2013 12:00:00 AM  06/30/2014 12:00:00 AM
18  01/01/2017 12:00:00 AM  12/31/2017 12:00:00 AM
19  07/01/2015 12:00:00 AM  06/30/2016 12:00:00 AM

In [75]:
regFinanCIM.loc[regFinanCIM["entityId"] == 20153043885,["name","documentId","reportingPeriodBegin","reportingPeriodEnd"]]

,name,documentId,reportingPeriodBegin,reportingPeriodEnd
37572,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,NaN,01/01/2017 12:00:00 AM,09/30/2017 12:00:00 AM
40185,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,NaN,10/01/2018 12:00:00 AM,09/30/2019 12:00:00 AM
59533,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,NaN,10/01/2017 12:00:00 AM,09/30/2018 12:00:00 AM
95524,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,NaN,01/01/2017 12:00:00 AM,09/30/2017 12:00:00 AM
150310,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,NaN,01/01/2014 12:00:00 AM,12/31/2014 12:00:00 AM
166914,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,NaN,01/01/2015 12:00:00 AM,12/31/2015 12:00:00 AM
169954,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,NaN,NaN,NaN
187041,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,NaN,10/01/2019 12:00:00 AM,09/30/2020 12:00:00 AM
202020,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,NaN,10/01/2020 12:00:00 AM,09/30/2021 12:00:00 AM
202092,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,NaN,01/01/2016 12:00:00 AM,12/31/2016 12:00:00 AM

In [32]:
regFinanCIM["documentId"].dtypes

dtype('float64')

In [76]:
regFinanOrig.loc[regFinanOrig["Entity Id"] ==20153043885 ,['Entity Id','Org Name', 'Document Id','Of Begin Taxyr','Of Endng Taxyr']]

,Entity Id,Org Name,Document Id,Of Begin Taxyr,Of Endng Taxyr
174108,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20153043885,20140101.0,20141231.0
174109,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20163038851,20150101.0,20151231.0
174110,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20173039865,20160101.0,20161231.0
174111,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20173039865,20170101.0,20170930.0
174112,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20183029893,20170101.0,20170930.0
174113,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20193028030,20171001.0,20180930.0
174114,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20203024224,20181001.0,20190930.0
174115,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20213024127,20191001.0,20200930.0
174116,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20223025333,20201001.0,20210930.0
174117,20153043885,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20233007986,NaN,NaN

In [79]:
regFinanCIM.loc[regFinanCIM["documentId"] == "20173039865",["name","documentId","reportingPeriodBegin","reportingPeriodEnd"]]

Empty DataFrame
Columns: [name, documentId, reportingPeriodBegin, reportingPeriodEnd]
Index: []

In [82]:
regFinanConv.loc[regFinanConv["documentId"] == 20173039865,["name","documentId","fiscalYearStartDate","fiscalYearEndDate","reportingPeriodBegin","reportingPeriodEnd"]]

,name,documentId,fiscalYearStartDate,fiscalYearEndDate,reportingPeriodBegin,reportingPeriodEnd
174110,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20173039865,01-01,12-31,01/01/2016,12/31/2016
174111,THE TRANSLATIONAL GENOMICS RESEARCH INSTITUTE ...,20173039865,10-01,09-31,01/01/2017,09/30/2017

In [91]:
regFinanCIM.loc[(~regFinanCIM["fiscalYearStartDate"].isna()) & (regFinanCIM["fiscalYearEndDate"].isna()),["name","documentId","fiscalYearStartDate","fiscalYearEndDate","reportingPeriodBegin","reportingPeriodEnd"]]

,name,documentId,fiscalYearStartDate,fiscalYearEndDate,reportingPeriodBegin,reportingPeriodEnd
17414,PARAGON FOUNDATION,NaN,01-01,NaN,01/01/2001 12:00:00 AM,12/31/2001 12:00:00 AM

In [88]:
a = regFinanCIM.loc[(~regFinanCIM["reportingPeriodBegin"].isna())]

In [89]:
a.shape

(205326, 99)

In [90]:
a.loc[regFinanCIM["reportingPeriodEnd"].isna()]

Empty DataFrame
Columns: [entityId, registrantTypeAbbr, name, fein, filingType, documentId, amendmentEntityId, externalFilingFromNccs, externalFilingType, actualFinancialsProvided, principalAddress, principalCity, principalState, principalZipcode, principalZipcode4, residentialCounty, mailingAddress, mailingCity, mailingState, mailingZipcode, mailingZipcode4, phone, fax, website, authorizedOfficerName, authorizedOfficerSignedDate, cfoName, cfoSignedDate, registrationApprovedDate, paymentProcessedDate, nextRenewalRegistrationDate, fiscalYearStartDate, fiscalYearEndDate, NTEECode1, NTEECode2, NTEECode3, taxExemptStatus, taxExemptCode, IRSDeterminationDate, donationsTaxDeductible, extensionFiled, consolidatedRegistrationStatement, reportingPeriodBegin, reportingPeriodEnd, newCharity, outsideProfessionalFundraiserFees, totalContributionsRaisedPreviousYear, totalFundraisingExpensesPreviousYear, totalManagementGeneralExpensesPreviousYear, expensesDividedByContributions, totalExpensesPlusManagementGeneralDividedByContributions, relatedOrganizationName, relatedToOtherOrganization, relatedOrganizationTaxExempt, solicitedNonTaxDeductibleGifts, statedGiftNotTaxDeductible, revenueFromContibutions, revenueFromGovernment, programServiceRevenue, revenueFromInvestments, revenueFromSpecialEvents, revenueFromSales, revenueOther, revenueTotal, expensesFromProgramServices, expensesFromAdministrativeOther, expensesFundraising, expensesAffiliates, expensesOther, expensesOtherComment, expensesTotal, endOfYearAssests, endOfYearTotalLiabilities, endOfYearAssestsMinusLiabilities, unrestrictedAssests, temporarilyRestrictedAssets, permanentlyRestrictedAssets, publicBenefitCorporation, pbcRecordingMethod, pbcPromotedBenefit, pbcIssuesStockShares, pbcStockSharesAvailable, pbcBenefitReportSent, pbcAnnualBenefitReport, conflictOfInterest, conflictOfInterestAffirmation, legalBusinessFormation, currentStatus, statusDate, principalAddress2, principalProvince, principalCountry, mailingAddress2, mailingProvince, mailingCountry, placeFormed, dateFormed, expirationDate, programServiceRatio]
Index: []

[0 rows x 99 columns]

### Compares

In [6]:
colsCIM = list(regFinanCIM.columns)
colsConv = list(regFinanConv.columns)

for col in colsCIM:
    if col not in colsConv:
        print(f"in CIM, not in CONV: {col}")
        
for col in colsConv:
    if col not in colsCIM:
        print(f"in Conv, not in CIM: {col}")

in CIM, not in CONV: externalFilingFromNccs
in CIM, not in CONV: externalFilingType
in CIM, not in CONV: newCharity
in CIM, not in CONV: revenueOther
in CIM, not in CONV: pbcPromotedBenefit
in CIM, not in CONV: pbcIssuesStockShares
in CIM, not in CONV: pbcStockSharesAvailable
in Conv, not in CIM: pbcPromotedBenifit
in Conv, not in CIM: revenueFromOther

In [8]:
for col in sorted(colsCIM):
    print(col)

IRSDeterminationDate
NTEECode1
NTEECode2
NTEECode3
actualFinancialsProvided
amendmentEntityId
authorizedOfficerName
authorizedOfficerSignedDate
cfoName
cfoSignedDate
conflictOfInterest
conflictOfInterestAffirmation
consolidatedRegistrationStatement
currentStatus
dateFormed
documentId
donationsTaxDeductible
endOfYearAssests
endOfYearAssestsMinusLiabilities
endOfYearTotalLiabilities
entityId
expensesAffiliates
expensesDividedByContributions
expensesFromAdministrativeOther
expensesFromProgramServices
expensesFundraising
expensesOther
expensesOtherComment
expensesTotal
expirationDate
extensionFiled
externalFilingFromNccs
externalFilingType
fax
fein
filingType
fiscalYearEndDate
fiscalYearStartDate
legalBusinessFormation
mailingAddress
mailingAddress2
mailingCity
mailingCountry
mailingProvince
mailingState
mailingZipcode
mailingZipcode4
name
newCharity
nextRenewalRegistrationDate
outsideProfessionalFundraiserFees
paymentProcessedDate
pbcAnnualBenefitReport
pbcBenefitReportSent
pbcIssuesStockShares
pbcPromotedBenefit
pbcRecordingMethod
pbcStockSharesAvailable
permanentlyRestrictedAssets
phone
placeFormed
principalAddress
principalAddress2
principalCity
principalCountry
principalProvince
principalState
principalZipcode
principalZipcode4
programServiceRatio
programServiceRevenue
publicBenefitCorporation
registrantTypeAbbr
registrationApprovedDate
relatedOrganizationName
relatedOrganizationTaxExempt
relatedToOtherOrganization
reportingPeriodBegin
reportingPeriodEnd
residentialCounty
revenueFromContibutions
revenueFromGovernment
revenueFromInvestments
revenueFromSales
revenueFromSpecialEvents
revenueOther
revenueTotal
solicitedNonTaxDeductibleGifts
statedGiftNotTaxDeductible
statusDate
taxExemptCode
taxExemptStatus
temporarilyRestrictedAssets
totalContributionsRaisedPreviousYear
totalExpensesPlusManagementGeneralDividedByContributions
totalFundraisingExpensesPreviousYear
totalManagementGeneralExpensesPreviousYear
unrestrictedAssests
website

In [4]:
# Original
regFinanOrig = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_source/reg_finan.tsv",sep="\t",encoding="latin")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (4,5,12,20,28,58,59,62,63,75,76,77,85,86) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [38]:
# Converted Data
regFinanConv = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_transformed/reg_finan.csv")

/tmp/ipykernel_1765/2884876631.py:2: DtypeWarning: Columns (3,5,6,12,21,25,30,31,60,61,62,63,77) have mixed types. Specify dtype option on import or set low_memory=False.
  regFinanConv = pd.read_csv("~/bic_etl/cdos/business/nonprofit/data_transformed/reg_finan.csv")

In [41]:
regFinanConv.head()

,entityId,registrantTypeAbbr,name,fein,filingType,documentId,amendmentEntityId,actualFinancialsProvided,principalAddress,principalAddress2,principalCity,principalState,principalProvince,residentialCounty,principalCountry,principalZipcode,principalZipcode4,mailingAddress,mailingAddress2,mailingCity,mailingState,mailingProvince,mailingZipcode,mailingZipcode4,mailingCountry,phone,fax,website,authorizedOfficerName,authorizedOfficerSignedDate,cfoName,cfoSignedDate,registrationApprovedDate,paymentProcessedDate,nextRenewalRegistrationDate,fiscalYearStartDate,fiscalYearEndDate,NTEECode1,NTEECode2,NTEECode3,taxExemptStatus,taxExemptCode,IRSDeterminationDate,donationsTaxDeductible,extensionFiled,consolidatedRegistrationStatement,publicBenefitCorporation,reportingPeriodBegin,reportingPeriodEnd,outsideProfessionalFundraiserFees,totalContributionsRaisedPreviousYear,totalFundraisingExpensesPreviousYear,totalManagementGeneralExpensesPreviousYear,expensesDividedByContributions,totalExpensesPlusManagementGeneralDividedByContributions,relatedOrganizationName,relatedToOtherOrganization,relatedOrganizationTaxExempt,solicitedNonTaxDeductibleGifts,statedGiftNotTaxDeductible,pbcRecordingMethod,pbcPromotedBenifit,pbcBenefitReportSent,pbcAnnualBenefitReport,revenueFromContibutions,revenueFromGovernment,programServiceRevenue,revenueFromInvestments,revenueFromSpecialEvents,revenueFromSales,revenueFromOther,revenueTotal,expensesFromProgramServices,expensesFromAdministrativeOther,expensesFundraising,expensesAffiliates,expensesOther,expensesOtherComment,expensesTotal,endOfYearAssests,endOfYearTotalLiabilities,endOfYearAssestsMinusLiabilities,unrestrictedAssests,temporarilyRestrictedAssets,permanentlyRestrictedAssets,conflictOfInterest,conflictOfInterestAffirmation,legalBusinessFormation,placeFormed,dateFormed,currentStatus,statusDate,expirationDate,programServiceRatio
0,20023003050,CO,HANNAH KAHN DANCE COMPANY,841187813.0,RENEWAL,20123014652,20113015377,1.0,75 S. CHEROKEE ST.,NaN,Denver,CO,NaN,DENVER,UNITED STATES,80223,NaN,119 S. FRANKLIN ST.,NaN,DENVER,CO,NaN,80209,NaN,UNITED STATES,3037894181.0,NaN,hannahkahndance.org,Hannah Kahn,05/02/2012,NaN,NaN,05/02/2012,05/02/2012,05/15/2013,01-01,12-31,"ARTS,CULTURE & HUMANITIES",NaN,NaN,1,501(C)(3),NaN,1,NaN,0,0.0,01/01/2011,12/31/2011,0.0,43774.00,0.0,1825.00,1.0,1.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,22432.0,21342.0,21393.0,0.0,0.0,0.0,0.0,65167.0,61520.0,1825.0,0.0,0.0,0.0,NaN,63345.0,34210.0,0.0,34210.0,0.0,0.0,0.0,NaN,NaN,CORPORATION,CO,19920408.0,GOOD,08/08/2022,08/15/23,0.97119
1,20023003050,CO,HANNAH KAHN DANCE COMPANY,841187813.0,RENEWAL,20133012204,20123014652,1.0,75 S. CHEROKEE ST.,NaN,Denver,CO,NaN,DENVER,UNITED STATES,80223,NaN,119 S. FRANKLIN ST.,NaN,DENVER,CO,NaN,80209,NaN,UNITED STATES,3037894181.0,NaN,hannahkahndance.org,Hannah Kahn,04/22/2013,NaN,NaN,04/27/2013,04/22/2013,05/15/2014,01-01,12-31,"ARTS,CULTURE & HUMANITIES",NaN,NaN,1,501(C)(3),NaN,1,NaN,0,0.0,01/01/2012,12/31/2012,0.0,45638.60,20.0,1998.50,1.0,1.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,24385.0,21254.0,23670.0,0.0,0.0,0.0,0.0,69308.0,66008.0,1999.0,20.0,0.0,0.0,NaN,68026.0,35492.0,0.0,35492.0,0.0,0.0,0.0,NaN,NaN,CORPORATION,CO,19920408.0,GOOD,08/08/2022,08/15/23,0.97033
2,20023003050,CO,HANNAH KAHN DANCE COMPANY,841187813.0,RENEWAL,20143011950,20133012204,1.0,75 S. CHEROKEE ST.,NaN,Denver,CO,NaN,DENVER,UNITED STATES,80223,NaN,119 S. FRANKLIN ST.,NaN,DENVER,CO,NaN,80209,NaN,UNITED STATES,3037894181.0,NaN,hannahkahndance.org,Hannah Kahn,04/14/2014,NaN,NaN,04/22/2014,04/14/2014,05/15/2015,01-01,12-31,"ARTS,CULTURE & HUMANITIES",NaN,NaN,1,501(C)(3),NaN,1,NaN,0,0.0,01/01/2013,12/31/2013,0.0,52743.70,0.0,1100.00,1.0,1.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,27025.0,25719.0,26684.0,0.0,0.0,0.0,0.0,79427.0,75301.0,1100.0,0.0,0.0,0.0,NaN,76401.0,38518.0,0.0,38518.0,0.0,0.0,0.0,NaN,NaN,CORPORATION,CO,19920408.0,GOOD,08/08/2022,08/15/23,0.98560
3,20023003050,CO,HANNAH KAHN DANCE COMPANY,841187813.0,RENEWAL,20153012786,20143011950,1.0,75 S. CHEROKEE ST.,NaN,Denver,CO,NaN,DENVER,UNITED STATES,80223,NaN,119 S. FRANKLIN ST.,NaN,DENVER,CO,NaN,80209,NaN,UNITED STATES,3037894181.0,NaN,hannahkahndance.org,Hannah Kahn,04/20/2015,NaN,NaN,04/29/2015,04/20/2015,05/15/2016,01-01,12-31,"ARTS,CULTURE & HUMANITIES",NaN,NaN,1,501(C)(3),NaN,1,NaN,0,0.0,01/01/2014,12/31/2014,0.0,47212.68,0.0,2375.22,1.0,1.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,23989.0,23224.0,28278.0,0.0,0.0,0.0,0.0,75491.0,72465.0,2375.0,0.0,0.0,0.0,NaN,74840.0,39169.0,0.0,39169.0,0.0,0.0,0.0,NaN,NaN,CORPORATION,CO,19920408.0,GOOD,08/08/2022,08/15/23,0.96826
4,20023003050,CO,HANNAH KAHN DANCE COMPANY,841187813.0,RENEWAL,20163013433,20153012786,1.0,75 S. CHEROKEE ST.,NaN,Denver,CO,NaN,DENVER,UNITED STATES,80223,NaN,119 S. FRANKLIN ST.,NaN,DENVER,CO,NaN,80209,NaN,UNITED STATES,3037894181.0,NaN,hannahkahndance.org,Hannah Kahn,04/25/2016,NaN,NaN,04/27/2016,04/25/2016,05/15/2017,01-01,12-31,"ARTS,CULTURE & HUMANITIES",NaN,NaN,1,501(C)(3),NaN,1,NaN,0,0.0,01/01/2015,12/31/2015,0.0,47272.25,0.0,793.61,1.0,1.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,47272.0,0.0,22297.0,0.0,0.0,0.0,750.0,70319.0,68367.0,794.0,0.0,0.0,0.0,NaN,69161.0,40328.0,0.0,40328.0,0.0,0.0,0.0,NaN,NaN,CORPORATION,CO,19920408.0,GOOD,08/08/2022,08/15/23,0.98853

In [49]:
a,b,c,d = dfStringAnal(regFinanConv)

In [ ]:
a

#### Check Code

In [48]:
def dfStringAnal(df):
    stats = {}
    nstats = {}
    ndates={}
    nums = ["int64","float64"]
    columnsNoDate=[]
    try: 
        for col in df: 
        #    print(col)
            if df[col].dtypes == "object":
                try : 
                    stats[col] = {}
                    
                    stats[col]["digits"] = -1
                    stats[col]["non-digits"] = -1
                    stats[col]["numeric"] = -1
                    stats[col]["word"] = -1
        #            stats[col]["non-word"] = df["B1_PER_ID1"].str.contains("\S").sum()
                    stats[col]["non-word"] = -1
                    stats[col]["white-spc"] = -1
                    stats[col]["_"] = -1                     
                    stats[col]["-"] = -1
                    stats[col]["#"] = -1
                    stats[col]["missing"] = -1

                    columnsNoDate.append(col)
                    typs = df[col].apply(type).value_counts().to_dict()
               #     print(typs)
                    
                    if str in typs:
                       stats[col]["string"] = typs[str]
                    else:
                       stats[col]["string"] = 0

                    if int in typs:
                       stats[col]["integer"] = typs[int]
                    else:
                       stats[col]["integer"] = 0

                    if float in typs:
                       stats[col]["float"] = typs[float]
                    else:
                       stats[col]["float"] = 0
                    
                    if bool in typs:
                       stats[col]["boolean"] = typs[bool]
                    else:
                       stats[col]["boolean"] = 0
                    
                    stats[col]["missing"] = df[col].isna().sum() 
                    stats[col]["% miss"] = df[col].isna().sum()/df.shape[0]*100 
                    stats[col]["% miss"] = f"{stats[col]['% miss']:4.1f}"

                    stats[col]["digits"] = df[col].str.contains("\d").sum()
                    stats[col]["non-digits"] = df[col].str.contains("\D").sum()
                    stats[col]["numeric"] = df[col].str.replace(".","",1).str.isdecimal().sum()


                    stats[col]["word"] = df[col].str.contains("\w").sum()
        #            stats[col]["non-word"] = df["B1_PER_ID1"].str.contains("\S").sum()
                    stats[col]["non-word"] = df[col].str.contains("[^a-zA-Z0-9_ \-]").sum() 
                    stats[col]["white-spc"] = df[col].str.contains("\s").sum()   

                    stats[col]["_"] = df[col].str.contains("_").sum()                        
                    stats[col]["-"] = df[col].str.contains("-").sum()   
                    stats[col]["#"] = df[col].str.contains("#").sum() 
                except Exception as errs:
                    print(f"{col} Object error {errs}")
#                    windowP["-PINFO-"].update(f"{col} Object error {errs}\n",append=True)
                    
            elif df[col].dtypes in nums:
                try: 
                    columnsNoDate.append(col)            
                    # amin,amax,amen,astd = df[col].agg(["min","max","mean","std"])
                    nstats[col]={}
                    # nstats[col]["Min"] = amin
                    # nstats[col]["Max"] = amax
                    # nstats[col]["Mean"] = amen
                    # nstats[col]["Std"] = astd
                    nstats[col]["Missing"] =df[col].isna().sum()
                    nstats[col]["% miss"] = df[col].isna().sum()/df.shape[0]*100 
                    nstats[col]["% miss"] = f"{nstats[col]['% miss']:4.1f}"
                except Exception as errs:
                    print(f"{col} Number error {errs}")
#                    windowP["-PINFO-"].update(f"{col} Number error {errs}\n",append=True)
                    
                    
            else:
                ndates[col]={}
                ndates[col]["Start"] = df[col].min()
                ndates[col]["End"] = df[col].max()
                ndates[col]["# Unique Dates"] = df[col].nunique()
    except Exception as err:
        print("dfStringAnal Error")
        print(err)

            
            
            
    nrecs=0
    return stats,nstats,ndates,columnsNoDate

In [39]:
! ls ~/bic_etl/cdos/business/nonprofit/scripts/reg_finan.js

/home/joe/bic_etl/cdos/business/nonprofit/scripts/reg_finan.js

In [29]:
fin = open("/home/joe/bic_etl/cdos/business/nonprofit/scripts/reg_finan.js","r")
lines = fin.readlines()
fout = open("output.txt","w")
org = []
xrefsO2T = {}
xrefsT2O = {}

for line in lines:
    if re.findall("row",line.lower()) and re.findall("=",line.lower()) and not re.findall("^//",line.lstrip()):
        st1=line.find("[")
        ed1=line.find("]")
        st2=line.rfind("[")
        ed2=line.rfind("]")
        org.append(line[st2+2:ed2-1])
#        print(line)
#        print(line[st1+1:ed1],line[st2+1:ed2])
        fout.write(f"{line[st1+1:ed1]}  {line[st2+1:ed2]}\n")
        og = line[st2+1:ed2].replace("'","")
        og = og.replace("].toLowerCase()","")
       
        
        tr = line[st1+1:ed1].replace(".toLowerCase()","")
        tr = tr.replace('"','')
       
        
 
        # tr = line[st1+1:ed1]
        # og = line[st2+1:ed2]
        
        xrefsT2O[tr]  = og
        xrefsO2T[og]  = tr
        
    
#        print("--")
        
        count=0
        vars = []
#         for match in re.finditer(r'\[', line):
#             count += 1
# #            print("match", count, match.group(), "start index", match.start(), "End index", match.end())
#             st = match.start()
#             tt = re.search(r'\]',line[st:])
#             vars.append(line[st+1:st+tt.end()])
#             print(st+1,tt.end(),line[st+1:st+tt.end()+1])
#         print(vars)
#print(org)
fout.close()

xrefsO2T

{'  let tRow                                                         = {;': '  let tRow                                                         = {;',
 'entity_id_input': 'entityId',
 'Entity Type': 'registrantTypeAbbr',
 'Org Name': 'name',
 'Ce Fein': 'fein',
 'Filing Type': 'filingType',
 'Document Id': 'documentId',
 'Ce Parent Id': 'amendmentEntityId',
 'Ce Actual Flg': 'actualFinancialsProvided',
 'Ce Paddr': 'principalAddress',
 '"Ce Paddr2"': 'principalAddress2',
 'Ce Pcity': 'principalCity',
 'Ce Pstate': 'principalState',
 'Ce Province': 'principalProvince',
 'Ce Cnty': 'residentialCounty',
 'Ce Country': 'principalCountry',
 'Ce Pzip': 'principalZipcode4',
 'Ce Maddr': 'mailingAddress',
 'Ce Maddr2': 'mailingAddress2',
 'Ce Mcity': 'mailingCity',
 'Ce Mstate': 'mailingState',
 'Ce Mprovince': 'mailingProvince',
 'Ce Mail Zip': 'mailingZipcode4',
 'Ce Mcountry': 'mailingCountry',
 'Ce Phone': 'phone',
 'Ce Fax': 'fax',
 'Ce Url': 'website',
 'Ce A1sign': 'authorizedOfficerName',
 'Ce A1sign Date': 'authorizedOfficerSignedDate',
 'Ce A2sign': 'cfoName',
 'Ce A2sign Date': 'cfoSignedDate',
 'Ce File Date': 'registrationApprovedDate',
 'Ce Date Paid': 'paymentProcessedDate',
 'Ce Renew Due': 'nextRenewalRegistrationDate',
 'Ce Org Fy Start': 'fiscalYearStartDate',
 'Ce Org Fy Ends': 'fiscalYearEndDate',
 'Ntee Dscrp': 'NTEECode1',
 'Ntee Dscrp2': 'NTEECode2',
 'Ntee Dscrp3': 'NTEECode3',
 'Ce Org Txmpt Flg': 'taxExemptStatus',
 'Ce Org Txmpt Code': 'taxExemptCode',
 'Ce Org Txmpt Date': 'IRSDeterminationDate',
 'Ce Org Txdduc Flg': 'donationsTaxDeductible',
 'Ce Ext Flg': 'extensionFiled',
 'Ce Cons Flg': 'consolidatedRegistrationStatement',
 'Ce Pbc Flg': 'publicBenefitCorporation',
 'Of Begin Taxyr': 'reportingPeriodBegin',
 'Of Endng Taxyr': 'reportingPeriodEnd',
 'Of Pf Fees': 'outsideProfessionalFundraiserFees',
 'Of Py Cntrbs': 'totalContributionsRaisedPreviousYear',
 'Of Py Frcosts': 'totalFundraisingExpensesPreviousYear',
 'Of Py Mcosts': 'totalManagementGeneralExpensesPreviousYear',
 'Of Fr Prcnt1': 'expensesDividedByContributions',
 'Of Fr Prcnt2': 'totalExpensesPlusManagementGeneralDividedByContributions',
 'Of Oorg Name': 'relatedOrganizationName',
 'Of Oorg Flg': 'relatedToOtherOrganization',
 'Of Exoorg Flg': 'relatedOrganizationTaxExempt',
 'Of Txddct Flg': 'solicitedNonTaxDeductibleGifts',
 'Of Txstmt Flg': 'statedGiftNotTaxDeductible',
 'Of Pbc Method': 'pbcRecordingMethod',
 'Of Pbc Promo': 'pbcPromotedBenifit',
 'Of Pbc Rpt Sent': 'pbcBenefitReportSent',
 'Of Pbc Location': 'pbcAnnualBenefitReport',
 'Os Rev Cntrb': 'revenueFromContibutions',
 'Os Rev Grnts': 'revenueFromGovernment',
 'Os Rev Pserv': 'programServiceRevenue',
 'Os Rev Inv': 'revenueFromInvestments',
 'Os Rev Evnts': 'revenueFromSpecialEvents',
 'Os Rev Sales': 'revenueFromSales',
 'Os Rev Othr': 'revenueFromOther',
 'Os Tot Rev': 'revenueTotal',
 'Os Exp Pserv': 'expensesFromProgramServices',
 'Os Exp Admn': 'expensesFromAdministrativeOther',
 'Os Exp Fundr': 'expensesFundraising',
 'Os Exp Payaff': 'expensesAffiliates',
 'Os Exp Othr': 'expensesOther',
 'Os Exp Comment': 'expensesOtherComment',
 'Os Tot Exp': 'expensesTotal',
 'Os Eoy Ass': 'endOfYearAssests',
 'Os Eoy Liab': 'endOfYearTotalLiabilities',
 'Os Net Ass': 'endOfYearAssestsMinusLiabilities',
 'Os Unrstr Ass': 'unrestrictedAssests',
 'Os Temp Ass': 'temporarilyRestrictedAssets',
 'Os Perm Ass': 'permanentlyRestrictedAssets',
 'Ce Ps Coi Flg': 'conflictOfInterest',
 'Ce Ps Coi Affirm': 'conflictOfInterestAffirmation',
 'Legal Form': 'legalBusinessFormation',
 'Place Formed': 'placeFormed',
 'Date Formed': 'dateFormed',
 'Current Status': 'currentStatus',
 'Status Date': 'statusDate',
 'Expiration Date': 'expirationDate',
 'Program Services Ratio': 'programServiceRatio'}

In [23]:
xrefsO2T

{'  let tRow                                                         = {};': '  let tRow                                                         = {};',
 'entity_id_input': '"entityId"',
 "'Entity Type'": '"registrantTypeAbbr"',
 "'Org Name'": '"name"',
 "'Ce Fein'": '"fein"',
 "'Filing Type'": '"filingType"',
 "'Document Id'": '"documentId"',
 "'Ce Parent Id'": '"amendmentEntityId"',
 "'Ce Actual Flg'].toLowerCase()": '"actualFinancialsProvided"',
 "'Ce Paddr'": '"principalAddress"',
 '"Ce Paddr2"': '"principalAddress2"',
 "'Ce Pcity'": '"principalCity"',
 "'Ce Pstate'": '"principalState"',
 "'Ce Province'": '"principalProvince"',
 "'Ce Cnty'": '"residentialCounty"',
 "'Ce Country'": '"principalCountry"',
 "'Ce Pzip'": '"principalZipcode4"',
 "'Ce Maddr'": '"mailingAddress"',
 "'Ce Maddr2'": '"mailingAddress2"',
 "'Ce Mcity'": '"mailingCity"',
 "'Ce Mstate'": '"mailingState"',
 "'Ce Mprovince'": '"mailingProvince"',
 "'Ce Mail Zip'": '"mailingZipcode4"',
 "'Ce Mcountry'": '"mailingCountry"',
 "'Ce Phone'": '"phone"',
 "'Ce Fax'": '"fax"',
 "'Ce Url'": '"website"',
 "'Ce A1sign'": '"authorizedOfficerName"',
 "'Ce A1sign Date'": '"authorizedOfficerSignedDate"',
 "'Ce A2sign'": '"cfoName"',
 "'Ce A2sign Date'": '"cfoSignedDate"',
 "'Ce File Date'": '"registrationApprovedDate"',
 "'Ce Date Paid'": '"paymentProcessedDate"',
 "'Ce Renew Due'": '"nextRenewalRegistrationDate"',
 "'Ce Org Fy Start'": '"fiscalYearStartDate"',
 "'Ce Org Fy Ends'": '"fiscalYearEndDate"',
 "'Ntee Dscrp'": '"NTEECode1"',
 "'Ntee Dscrp2'": '"NTEECode2"',
 "'Ntee Dscrp3'": '"NTEECode3"',
 "'Ce Org Txmpt Flg'].toLowerCase()": '"taxExemptStatus"',
 "'Ce Org Txmpt Code'": '"taxExemptCode"',
 "'Ce Org Txmpt Date'": '"IRSDeterminationDate"',
 "'Ce Org Txdduc Flg'].toLowerCase()": '"donationsTaxDeductible"',
 "'Ce Ext Flg'].toLowerCase()": '"extensionFiled"',
 "'Ce Cons Flg'].toLowerCase()": '"consolidatedRegistrationStatement"',
 "'Ce Pbc Flg'].toLowerCase()": '"publicBenefitCorporation"',
 "'Of Begin Taxyr'": '"reportingPeriodBegin"',
 "'Of Endng Taxyr'": '"reportingPeriodEnd"',
 "'Of Pf Fees'": '"outsideProfessionalFundraiserFees"',
 "'Of Py Cntrbs'": '"totalContributionsRaisedPreviousYear"',
 "'Of Py Frcosts'": '"totalFundraisingExpensesPreviousYear"',
 "'Of Py Mcosts'": '"totalManagementGeneralExpensesPreviousYear"',
 "'Of Fr Prcnt1'": '"expensesDividedByContributions"',
 "'Of Fr Prcnt2'": '"totalExpensesPlusManagementGeneralDividedByContributions"',
 "'Of Oorg Name'": '"relatedOrganizationName"',
 "'Of Oorg Flg'].toLowerCase()": '"relatedToOtherOrganization"',
 "'Of Exoorg Flg'].toLowerCase()": '"relatedOrganizationTaxExempt"',
 "'Of Txddct Flg'].toLowerCase()": '"solicitedNonTaxDeductibleGifts"',
 "'Of Txstmt Flg'].toLowerCase()": '"statedGiftNotTaxDeductible"',
 "'Of Pbc Method'": '"pbcRecordingMethod"',
 "'Of Pbc Promo'": '"pbcPromotedBenifit"',
 "'Of Pbc Rpt Sent'": '"pbcBenefitReportSent"',
 "'Of Pbc Location'": '"pbcAnnualBenefitReport"',
 "'Os Rev Cntrb'": '"revenueFromContibutions"',
 "'Os Rev Grnts'": '"revenueFromGovernment"',
 "'Os Rev Pserv'": '"programServiceRevenue"',
 "'Os Rev Inv'": '"revenueFromInvestments"',
 "'Os Rev Evnts'": '"revenueFromSpecialEvents"',
 "'Os Rev Sales'": '"revenueFromSales"',
 "'Os Rev Othr'": '"revenueFromOther"',
 "'Os Tot Rev'": '"revenueTotal"',
 "'Os Exp Pserv'": '"expensesFromProgramServices"',
 "'Os Exp Admn'": '"expensesFromAdministrativeOther"',
 "'Os Exp Fundr'": '"expensesFundraising"',
 "'Os Exp Payaff'": '"expensesAffiliates"',
 "'Os Exp Othr'": '"expensesOther"',
 "'Os Exp Comment'": '"expensesOtherComment"',
 "'Os Tot Exp'": '"expensesTotal"',
 "'Os Eoy Ass'": '"endOfYearAssests"',
 "'Os Eoy Liab'": '"endOfYearTotalLiabilities"',
 "'Os Net Ass'": '"endOfYearAssestsMinusLiabilities"',
 "'Os Unrstr Ass'": '"unrestrictedAssests"',
 "'Os Temp Ass'": '"temporarilyRestrictedAssets"',
 "'Os Perm Ass'": '"permanentlyRestrictedAssets"',
 "'Ce Ps Coi Flg'].toLowerCase()": '"conflictOfInterest"',
 "'Ce Ps Coi Affirm'].toLowerCase()": '"conflictOfInterestAffirmation"',
 "'Legal Form'": '"legalBusinessFormation"',
 "'Place Formed'": '"placeFormed"',
 "'Date Formed'": '"dateFormed"',
 "'Current Status'": '"currentStatus"',
 "'Status Date'": '"statusDate"',
 "'Expiration Date'": '"expirationDate"',
 "'Program Services Ratio'": '"programServiceRatio"'}

In [40]:
! ls -l ~/bic_etl/cdos/business/nonprofit/scripts/reg_finan.js

-rw-r--r-- 1 joe joe 18564 Jun 26 08:05 /home/joe/bic_etl/cdos/business/nonprofit/scripts/reg_finan.js

In [4]:
orgCleaned = []
for col in sorted(org):
    orgCleaned.append(col.replace("'].toLowerCase(",""))

In [5]:
print("In Original Data NOT in Code")
for col in regFinanOrig.columns:
    if col not in orgCleaned:
        print(col)

In Original Data NOT in Code

NameError: name 'regFinanOrig' is not defined

In [108]:
cols = list(regFinanOrig.columns)
print("In Code, but NOT in Original Data")
for col in orgCleaned:
    if (col not in cols):
        print(col)

In Code, but NOT in Original Data
 let tRow                                                         = {}
Of Est Flg
ntity_id_inpu