In [76]:
import pandas as pd
import numpy as np

import warnings

from pandas.core.common import SettingWithCopyWarning

warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)

In [2]:
dfBusCIM = pd.read_csv("Business_Entities_in_Colorado.csv")

In [3]:
dfXen = pd.read_csv("~/bic_etl/cdos/business/business/data_transformed/business_entities.csv")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (23,29,32) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [80]:
def printComps(eid,how):
#    eid = 20011097520
    a = dfBusCIM.loc[dfBusCIM["entityid"] == eid]
    b = dfXen.loc[dfXen["entityId"] == eid]
    a.drop("entityformdate",inplace=True,axis=1)
    b.drop("entityFormDate",inplace=True,axis=1)

#     a = dfA.copy()
#     b = dfB.copy()
   
    cols=[]
    org = []
    new = []
    for col in b:  
        if isinstance(a[col.lower()].values[0],str):
            a[col.lower()] = a[col.lower()].values[0].strip()
        if isinstance(b[col].values[0],str):
            b[col].values[0] = b[col].values[0].strip()
            
        if how == 0: 
            cols.append(col)
            org.append(a[col.lower()].values[0])
            new.append(b[col].values[0])
        else:
            if col.lower() == "entityid":
                cols.append(col)
                org.append(a[col.lower()].values[0])
                new.append(b[col].values[0])
            
            if type(a[col.lower()].values[0]) != type(b[col].values[0]):
          #       print(type(a[col.lower()].values[0]),type(b[col].values[0]),a[col.lower()].values[0],b[col].values[0])
                 cols.append(col)
                 org.append(a[col.lower()].values[0])
                 new.append(b[col].values[0])
            elif  a[col.lower()].values[0] !=  b[col].values[0]:
                 if isinstance(a[col.lower()].values[0],str) and isinstance(b[col].values[0],str):
                     cols.append(col)
                     org.append(a[col.lower()].values[0])
                     new.append(b[col].values[0])
                 elif not np.isnan(a[col.lower()].values[0]) or  not np.isnan(b[col].values[0]):
                     cols.append(col)
                     org.append(a[col.lower()].values[0])
                     new.append(b[col].values[0])


    c = pd.DataFrame({"Column":cols,"Orig Val":org,"New Val":new})
    print(c["Orig Val"].equals(c["New Val"]))
    display(c)
    
eid = 20011097520
#printComps(dfBusCIM.loc[dfBusCIM["entityid"] == eid].drop("entityformdate",axis=1),dfXen.loc[dfXen["entityId"] == eid].drop("entityFormDate",axis=1),0)
printComps(20011097520,1)

False

                   Column          Orig Val                New Val
0                entityId       20011097520            20011097520
1       principalAddress2       Fifth Floor              5th Floor
2  agentPrincipalAddress2       Fifth Floor              5th Floor
3    agentMailingAddress1  4350 S Monaco St  4350 S. Monaco Street
4    agentMailingAddress2           Floor 5              5th Floor
5        agentMailingCity            Denver                 DENVER

In [9]:
c["Orig Val"].eq(c["New Val"])

0      True
1      True
2      True
3     False
4     False
5      True
6      True
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14     True
15     True
16     True
17    False
18    False
19    False
20    False
21     True
22     True
23    False
24     True
25     True
26     True
27     True
28    False
29    False
30    False
31    False
32    False
33    False
dtype: bool

In [70]:
eids = pd.read_csv("compare-badids",header=None)

In [81]:
for eid in eids[0]:
  printComps(eid,1)

False

                   Column                     Orig Val                New Val
0                entityId                  19871033282            19871033282
1       principalAddress1             1525 Howe Street           1525 Howe St
2         mailingAddress1             1525 Howe Street           1525 Howe St
3  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd

False

                Column     Orig Val       New Val
0             entityId  19871037801  1.987104e+10
1  agentMailingZipCode        80601  8.060100e+04

False

,Column,Orig Val,New Val
0,entityId,19871056751,19871056751
1,principalAddress1,1550 CRYSTAL DR. STE. 1300,1550 Crystal Dr Ste 1300
2,principalAddress2,LEGAL DEPT.,Legal Dept
3,mailingAddress1,NaN,1900 W Littleton Blvd
4,mailingCity,NaN,Littleton
5,mailingState,NaN,CO
6,mailingZipCode,NaN,80120
7,mailingCountry,NaN,US
8,agentPrincipalAddress1,1900 W. Littleton Boulevard,1900 W Littleton Blvd
9,agentMailingAddress1,"1550 CRYSTAL DRIVE, SUITE 1300",NaN
10,agentMailingAddress2,LEGAL DEPT,NaN
11,agentMailingCity,Arlington,NaN
12,agentMailingState,CO,NaN
13,agentMailingZipCode,22202,NaN
14,agentMailingCountry,US,NaN

False

                   Column                     Orig Val                New Val
0                entityId                  19871063401            19871063401
1       principalAddress1               635 SCIENCE DR         635 Science Dr
2  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd

False

                 Column                Orig Val       New Val
0              entityId             19871072644  1.987107e+10
1  agentMailingAddress1  600 Corporate Park Dr.           NaN
2      agentMailingCity                 Clayton           NaN
3     agentMailingState                      CO           NaN
4   agentMailingZipCode                   63105           NaN
5   agentMailingCountry                      US           NaN

False

                 Column             Orig Val             New Val
0              entityId          19871175925         19871175925
1  agentMailingAddress1  7022 Gardenstone Dr  2204 E. Boulder St

False

                    Column                  Orig Val               New Val
0                 entityId               19871193805           19871193805
1        principalAddress1      1730 E FOUNTAIN BLVD  1730 E Fountain Blvd
2          mailingAddress1  955 S UNION BLVD STE 235                   NaN
3              mailingCity          Colorado Springs                   NaN
4             mailingState                        CO                   NaN
5           mailingZipCode                     80910                   NaN
6           mailingCountry                        US                   NaN
7   agentPrincipalAddress1      1730 E FOUNTAIN BLVD  1730 E Fountain Blvd
8       agentPrincipalCity          COLORADO SPRINGS      Colorado Springs
9     agentMailingAddress1              PO BOX 75722  1730 E Fountain Blvd
10        agentMailingCity          COLORADO SPRINGS      Colorado Springs
11     agentMailingZipCode                     80970                 80910

False

                   Column           Orig Val           New Val
0                entityId        19871200533       19871200533
1  agentPrincipalAddress1  16671 W. 74th Ave  16671 W 74th Ave
2    agentMailingAddress1   16671 W 74th Ave               NaN
3        agentMailingCity             Arvada               NaN
4       agentMailingState                 CO               NaN
5     agentMailingZipCode              80007               NaN
6     agentMailingCountry                 US               NaN

False

               Column                Orig Val                  New Val
0            entityId             19871245640              19871245640
1   principalAddress1  1000 Chesterbrook Blvd  1801 California Street,
2   principalAddress2               Suite 250               23rd Floor
3       principalCity                  Berwyn                   Denver
4      principalState                      PA                       CO
5    principalZipCode                   19312                    80202
6     mailingAddress1  1801 California Street                      NaN
7     mailingAddress2              23rd Floor                      NaN
8         mailingCity                  Denver                      NaN
9        mailingState                      CO                      NaN
10     mailingZipCode                   80202                      NaN
11     mailingCountry                      US                      NaN

False

                   Column         Orig Val               New Val
0                entityId      19871284242           19871284242
1       principalAddress1  16509 CTY RD 22  16509 County Road 22
2  agentPrincipalAddress1  16509 CTY RD 22  16509 County Road 22
3      agentPrincipalCity         STERLING              Sterling

False

                    Column            Orig Val             New Val
0                 entityId         19871287024         19871287024
1          mailingAddress1  0981 County Rd 245                 NaN
2              mailingCity          New Castle                 NaN
3             mailingState                  CO                 NaN
4           mailingZipCode               81647                 NaN
5           mailingCountry                  US                 NaN
6   agentPrincipalAddress1   981 County Rd 245  0981 County Rd 245
7       agentPrincipalCity          NEW CASTLE          New Castle
8     agentMailingAddress1   981 County Rd 245                 NaN
9         agentMailingCity          New Castle                 NaN
10       agentMailingState                  CO                 NaN
11     agentMailingZipCode               81647                 NaN
12     agentMailingCountry                  US                 NaN

False

            Column       Orig Val                               New Val
0         entityId    19871326127                           19871326127
1       entityName   IRVINE, INC.  IRVINE, INC., Dissolved May 11, 2023
2  mailingAddress1            NaN                     22518 county Road
3      mailingCity            NaN                                 Eaton
4     mailingState            NaN                                    CO
5   mailingZipCode            NaN                                 80615
6   mailingCountry            NaN                                    US
7     entityStatus  Good Standing                 Voluntarily Dissolved

False

           Column     Orig Val      New Val
0        entityId  19871330666  19871330666
1  agentFirstName       Robert         Gena
2   agentLastName    DeHerrera      Colbert

False

                    Column              Orig Val               New Val
0                 entityId           19871346653           19871346653
1        principalAddress1  1730 E FOUNTAIN BLVD  1730 E Fountain Blvd
2          mailingAddress1          PO BOX 75722                   NaN
3              mailingCity      Colorado Springs                   NaN
4             mailingState                    CO                   NaN
5           mailingZipCode                 80970                   NaN
6           mailingCountry                    US                   NaN
7   agentPrincipalAddress1  1730 E FOUNTAIN BLVD  1730 E Fountain Blvd
8       agentPrincipalCity      COLORADO SPRINGS      Colorado Springs
9     agentMailingAddress1          PO BOX 75722                   NaN
10        agentMailingCity      COLORADO SPRINGS                   NaN
11       agentMailingState                    CO                   NaN
12     agentMailingZipCode                 80970                   NaN
13     agentMailingCountry                    US                   NaN

False

,Column,Orig Val,New Val
0,entityId,19871348094,19871348094
1,principalAddress1,9322 N 94TH WAY,9322 N 94th Way Ste 102
2,principalAddress2,#102,NaN
3,agentLastName,CHANZIT,"CHANZIT,atty"
4,agentPrincipalAddress1,6000 E. Evans Ave. #3-304,6000 E Evans Ave Ste 3-304
5,agentMailingAddress1,12120 N 98th Way,NaN
6,agentMailingCity,Scottsdale,NaN
7,agentMailingState,CO,NaN
8,agentMailingZipCode,85260,NaN
9,agentMailingCountry,US,NaN

False

,Column,Orig Val,New Val
0,entityId,19871391046,19871391046
1,agentOrganizationName,C T Corporation System,Corporation Service Company
2,agentPrincipalAddress1,7700 E Arapahoe Rd Ste 220,1900 W. Littleton Boulevard
3,agentPrincipalCity,Centennial,Littleton
4,agentPrincipalZipCode,80112-1268,80120

False

,Column,Orig Val,New Val
0,entityId,19871479966,19871479966
1,principalAddress1,131 Fairway Lane,131 Fairway Ln
2,agentOrganizationName,Country Club Estates Condominium Association,COUNTRY CLUB ESTATES CONDOMINIUM ASSOCIATION
3,agentPrincipalAddress1,131 FAIRWAY LANE,131 Fairway Ln
4,agentPrincipalCity,FORT MORGAN,Fort Morgan
5,agentMailingAddress1,NaN,131 Fairway Ln
6,agentMailingCity,NaN,Fort Morgan
7,agentMailingState,NaN,CO
8,agentMailingZipCode,NaN,80701
9,agentMailingCountry,NaN,US

False

                   Column                  Orig Val                   New Val
0                entityId               19871503248               19871503248
1       principalAddress1  650 S CHERRY ST STE 1400  650 S Cherry St Ste 1400
2  agentPrincipalAddress1  650 S CHERRY ST STE 1400  650 S Cherry St Ste 1400
3      agentPrincipalCity                    DENVER                    Denver
4    agentMailingAddress1           650 S CHERRY ST  650 S Cherry St Ste 1400
5    agentMailingAddress2                  STE 1400                       NaN
6        agentMailingCity                    DENVER                    Denver

False

                   Column                  Orig Val                   New Val
0                entityId               19871520861               19871520861
1       principalAddress1  650 S CHERRY ST STE 1400  650 S Cherry St Ste 1400
2  agentPrincipalAddress1  650 S CHERRY ST STE 1400  650 S Cherry St Ste 1400
3      agentPrincipalCity                    DENVER                    Denver
4    agentMailingAddress1           650 S CHERRY ST                       NaN
5    agentMailingAddress2                  STE 1400                       NaN
6        agentMailingCity                    DENVER                       NaN
7       agentMailingState                        CO                       NaN
8     agentMailingZipCode                     80246                       NaN
9     agentMailingCountry                        US                       NaN

False

                Column     Orig Val       New Val
0             entityId  19871554684  1.987155e+10
1  agentMailingZipCode        81321  8.132100e+04

False

                 Column       Orig Val        New Val
0              entityId    19871556615    19871556615
1     principalAddress2   P O BOX 6808            NaN
2      principalZipCode          80866          80863
3          entityStatus   Noncompliant  Good Standing
4  agentMailingAddress1    PO BOX 6808    PO Box 6808
5      agentMailingCity  WOODLAND PARK  Woodland Park

False

                   Column                     Orig Val                New Val
0                entityId                  19871560230            19871560230
1         mailingAddress1                   PO BOX 988             PO Box 988
2  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd

False

                   Column             Orig Val           New Val
0                entityId          19871571944       19871571944
1       principalAddress1  850 Broadview Place  850 Broadview Pl
2         mailingAddress1          PO Box 3099       PO Box 6242
3  agentPrincipalAddress1  850 Broadview Place  850 Broadview Pl
4      agentPrincipalCity     COLORADO SPRINGS  Colorado Springs

False

                Column     Orig Val       New Val
0             entityId  19871575118  1.987158e+10
1  agentMailingZipCode        81201  8.120100e+04

False

                   Column          Orig Val             New Val
0                entityId       19871596758         19871596758
1           principalCity          Sunshine             Boulder
2         mailingAddress1  732 County Rd 83  732 County Road 83
3  agentPrincipalAddress1  732 County Rd 83  732 County Road 83
4    agentMailingAddress1  732 COUNTY RD 83  732 County Road 83
5        agentMailingCity           BOULDER             Boulder

False

              Column            Orig Val               New Val
0           entityId         19871599319           19871599319
1  principalAddress1  126 E. 56th Street  126 E 56th St Fl 10R
2  principalAddress2           Floor 10R                   NaN

False

                   Column                     Orig Val                New Val
0                entityId                  19871609408            19871609408
1  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd
2    agentMailingAddress1  1900 W. Littleton Boulevard                    NaN
3        agentMailingCity                    Littleton                    NaN
4       agentMailingState                           CO                    NaN
5     agentMailingZipCode                        80120                    NaN
6     agentMailingCountry                           US                    NaN

False

                  Column     Orig Val      New Val
0               entityId  19871619226  19871619226
1       principalZipCode   80211-2614        80211
2  agentPrincipalZipCode   80211-2614        80211

False

                 Column     Orig Val      New Val
0              entityId  19871644018  19871644018
1  agentMailingAddress1    PO Box 74   PO Box 301

False

                 Column                     Orig Val                   New Val
0              entityId                  19871661123               19871661123
1  agentMailingAddress1  1000 Depot Hill Road unit I  1000 Depot Hill Rd Ste I

False

                   Column              Orig Val               New Val
0                entityId           19871671732           19871671732
1       principalAddress1  18141 COUNTY ROAD 48  18141 County Road 48
2  agentPrincipalAddress1  18141 COUNTY ROAD 48  18141 County Road 48
3      agentPrincipalCity              STERLING              Sterling

False

                Column     Orig Val       New Val
0             entityId  19871689080  1.987169e+10
1  agentMailingZipCode        81632  8.163200e+04

False

,Column,Orig Val,New Val
0,entityId,19881018271,19881018271
1,entityName,"CARAMEL APPLE AUDIO, INC.","CARAMEL APPLE AUDIO, INC., Dissolved May 10, 2023"
2,mailingAddress1,12533 W. Hawaii Ave,12533 W HAWAII AVE
3,entityStatus,Good Standing,Voluntarily Dissolved

False

                   Column                     Orig Val                 New Val
0                entityId                  19881049022             19881049022
1       principalAddress1                     Box 1397  1816 E Wyatt Earp Blvd
2       principalAddress2         1816 East Wyatt Earp                     NaN
3         mailingAddress1                P.O. Box 1397             PO Box 1397
4  agentPrincipalAddress1  1900 W. Littleton Boulevard   1900 W Littleton Blvd

False

                Column     Orig Val       New Val
0             entityId  19891006847  1.989101e+10
1  agentMailingZipCode        81224  8.122400e+04

False

,Column,Orig Val,New Val
0,entityId,19891045137,19891045137
1,principalAddress1,6300 W. Mansfield Ave.,6300 W Mansfield Ave Unit 67
2,principalAddress2,#67,NaN
3,principalZipCode,80235-3032,80235
4,agentPrincipalAddress1,6500 W. Mansfield Ave.,6500 W Mansfield Ave Unit 9
5,agentPrincipalAddress2,Unit 9,NaN

False

                   Column                   Orig Val                   New Val
0                entityId                19891074526               19891074526
1       principalAddress1      650 S Cherry St #1400  650 S Cherry St Ste 1400
2  agentPrincipalAddress1  650 S CHERRY ST  STE 1400  650 S Cherry St Ste 1400
3      agentPrincipalCity                     DENVER                    Denver
4    agentMailingAddress1            650 S CHERRY ST  650 S Cherry St Ste 1400
5    agentMailingAddress2                   STE 1400                       NaN
6        agentMailingCity                     DENVER                    Denver

False

           Column     Orig Val      New Val
0        entityId  19891074135  19891074135
1  agentFirstName      Lawanda        David
2   agentLastName      Stewart     Gonzalez

False

                   Column       Orig Val        New Val
0                entityId    19901007170    19901007170
1       principalAddress1  320 N 16TH ST  320 N 16th St
2            entityStatus   Noncompliant  Good Standing
3  agentPrincipalAddress1  320 N 16TH ST  320 N 16th St
4      agentPrincipalCity     CANON CITY     Canon City

False

                   Column                     Orig Val                 New Val
0                entityId                  19901023042             19901023042
1       principalAddress1          200 E. RANDOLPH ST.  200 E Randolph St Fl 8
2  agentPrincipalAddress1  1900 W. Littleton Boulevard   1900 W Littleton Blvd

False

                 Column          Orig Val       New Val
0              entityId       19901044631  1.990104e+10
1  agentMailingAddress1  11311 Quivas Way           NaN
2      agentMailingCity       Westminster           NaN
3     agentMailingState                CO           NaN
4   agentMailingZipCode             80234           NaN
5   agentMailingCountry                US           NaN

False

                   Column         Orig Val          New Val
0                entityId      19901059283      19901059283
1       principalAddress1  1413 AIRPORT RD  1413 Airport Rd
2         mailingAddress1       PO BOX 867       PO Box 867
3  agentPrincipalAddress1  1413 AIRPORT RD  1413 Airport Rd
4      agentPrincipalCity            RIFLE            Rifle
5    agentMailingAddress1       PO BOX 867       PO Box 867
6        agentMailingCity            RIFLE            Rifle

False

                   Column                Orig Val                New Val
0                entityId             19911031320            19911031320
1       principalAddress2             Fifth Floor              5th Floor
2  agentPrincipalAddress1  4350 S. Monaco Street.  4350 S. Monaco Street
3  agentPrincipalAddress2             Fifth Floor              5th Floor
4      agentPrincipalCity                  DENVER                 Denver
5    agentMailingAddress1        4350 S Monaco St  4350 S. Monaco Street
6    agentMailingAddress2                 Floor 5              5th Floor

False

,Column,Orig Val,New Val
0,entityId,19911032705,19911032705
1,principalAddress1,1700 LINCOLN STREET SUITE 3901,1700 N Lincoln St Ste 3901
2,mailingAddress1,PO BOX 6670,PO Box 6670
3,agentPrincipalAddress1,449 Oakland,449 Oakland St
4,agentMailingAddress1,P.O. Box 101987,PO Box 101987

False

                 Column         Orig Val        New Val
0              entityId      19911032882    19911032882
1       mailingAddress1   P.O. Box 24979   PO Box 24979
2  agentMailingAddress1  P.O. Box 101987  PO Box 101987

False

                   Column     Orig Val            New Val
0                entityId  19911036073        19911036073
1  agentPrincipalAddress1   642 BREEZE  642 Breeze Street

False

                    Column              Orig Val       New Val
0                 entityId           19911038643   19911038643
1             entityStatus         Good Standing  Noncompliant
2           agentFirstName                 Chris           NaN
3          agentMiddleName                  Alan           NaN
4            agentLastName               Crigler           NaN
5   agentPrincipalAddress1  1825 Lawrence Street           NaN
6   agentPrincipalAddress2                   311           NaN
7       agentPrincipalCity                Denver           NaN
8      agentPrincipalState                    CO           NaN
9    agentPrincipalZipCode                 80204           NaN
10   agentPrincipalCountry                    US           NaN

False

                 Column      Orig Val                 New Val
0              entityId  1.991105e+10             19911047840
1  agentMailingAddress1           NaN  201 E. 4th Street #130
2      agentMailingCity           NaN                Loveland
3     agentMailingState           NaN                      CO
4   agentMailingZipCode           NaN                   80537
5   agentMailingCountry           NaN                      US

False

,Column,Orig Val,New Val
0,entityId,19911056474,19911056474
1,entityName,"TOPO MACHINERY, INC., Delinquent September 1, ...","TOPO MACHINERY, INC."
2,principalAddress1,9 TANGLEWOOD DRIVE,70 Montbello Road
3,principalCity,Durango,Gunnison
4,principalZipCode,81301,81230
5,mailingAddress1,PO 2487,NaN
6,mailingCity,Durango,NaN
7,mailingState,CO,NaN
8,mailingZipCode,81302,NaN
9,mailingCountry,US,NaN
10,entityStatus,Delinquent,Good Standing
11,agentPrincipalAddress1,9 TANGLEWOOD DRIVE,70 Montbello Road
12,agentPrincipalCity,DURANGO,Gunnison
13,agentPrincipalZipCode,81301,81230

False

                    Column                   Orig Val              New Val
0                 entityId                19911075496          19911075496
1        principalAddress1           631 Birch St. #A  631 Birch St Unit A
2          mailingAddress1           631 Birch St. #A  631 Birch St Unit A
3           agentFirstName                      Brett               Dennis
4            agentLastName                      Bolin              Denboer
5   agentPrincipalAddress1   631 Birch Street Suite A       1544 W 28th St
6   agentPrincipalAddress2                    Windsor                  NaN
7       agentPrincipalCity                    Windsor             Loveland
8    agentPrincipalZipCode                      80550                80538
9     agentMailingAddress1  631 Birch Street, Suite A                  NaN
10        agentMailingCity                    Windsor                  NaN
11       agentMailingState                         CO                  NaN
12     agentMailingZipCode                      80550                  NaN
13     agentMailingCountry                         US                  NaN

False

                   Column        Orig Val      New Val
0                entityId     19921038072  19921038072
1       principalAddress1  451 Fourth Ave  451 4th Ave
2  agentPrincipalAddress1  451 Fourth Ave  451 4th Ave
3      agentPrincipalCity           Lyons        LYONS

False

                   Column        Orig Val       New Val
0                entityId     19921044835   19921044835
1         mailingAddress1    P.O. Box 341    PO Box 341
2  agentPrincipalAddress1     P O BOX 341  899 FIRST ST
3    agentMailingAddress1  701 1st Street    PO Box 341

False

                Column     Orig Val       New Val
0             entityId  19921047255  1.992105e+10
1  agentMailingZipCode        80014  8.001400e+04

False

                   Column           Orig Val          New Val
0                entityId        19921049215      19921049215
1       principalAddress1    7013 E 70TH AVE  7013 E 70th Ave
2         mailingAddress1  7013 E. 70th Ave.              NaN
3             mailingCity      Commerce City              NaN
4            mailingState                 CO              NaN
5          mailingZipCode              80022              NaN
6          mailingCountry                 US              NaN
7  agentPrincipalAddress1    7013 E 70TH AVE  7013 E 70th Ave
8      agentPrincipalCity      COMMERCE CITY    Commerce City

False

            Column     Orig Val      New Val
0         entityId  19921074037  19921074037
1   agentFirstName       Jeanne         Lynn
2  agentMiddleName            M            A
3    agentLastName      Beaudry    Caligiuri

False

                Column     Orig Val       New Val
0             entityId  19921107810  1.992111e+10
1  agentMailingZipCode        81611  8.161100e+04

False

              Column                      Orig Val           New Val
0           entityId                   19921113113       19921113113
1  principalAddress1  2015 Clubhouse Dr., Ste. 101  2201 95th Avenue
2    mailingAddress1                           NaN  2201 95th Avenue
3        mailingCity                           NaN           Greeley
4       mailingState                           NaN                CO
5     mailingZipCode                           NaN             80634
6     mailingCountry                           NaN                US

False

                   Column       Orig Val        New Val
0                entityId    19921123342    19921123342
1       principalAddress1  5045 PARIS ST  5045 Paris St
2            entityStatus   Noncompliant  Good Standing
3  agentPrincipalAddress1  5045 PARIS ST  5045 Paris St
4      agentPrincipalCity         DENVER         Denver

False

                   Column                     Orig Val                New Val
0                entityId                  19931022366            19931022366
1       principalAddress1             1612 E. Abriendo    1612 E Abriendo Ave
2  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd

False

                    Column                 Orig Val                New Val
0                 entityId              19931051856            19931051856
1        principalAddress1      1801 BROADWAY, #200  1801 Broadway Ste 200
2          mailingAddress1                      NaN  1801 Broadway Ste 200
3              mailingCity                      NaN                 Denver
4             mailingState                      NaN                     CO
5           mailingZipCode                      NaN                  80202
6           mailingCountry                      NaN                     US
7   agentPrincipalAddress1                SUITE 200  1801 Broadway Ste 200
8   agentPrincipalAddress2            1801 BROADWAY                    NaN
9       agentPrincipalCity                   DENVER                 Denver
10    agentMailingAddress1  1801 BROADWAY SUITE 200  1801 Broadway Ste 200
11        agentMailingCity                   DENVER                 Denver

False

                Column     Orig Val       New Val
0             entityId  19931079698  1.993108e+10
1  agentMailingZipCode        81620  8.162000e+04

False

                Column     Orig Val       New Val
0             entityId  19931115648  1.993112e+10
1  agentMailingZipCode        80222  8.022200e+04

False

              Column                   Orig Val           New Val
0           entityId                19931132862       19931132862
1  principalAddress1  2015 Clubhouse Dr Ste 101  2201 95th Avenue
2    mailingAddress1                        NaN  2201 95th Avenue
3        mailingCity                        NaN           Greeley
4       mailingState                        NaN                CO
5     mailingZipCode                        NaN             80634
6     mailingCountry                        NaN                US

False

                   Column                     Orig Val                New Val
0                entityId                  19941028536            19941028536
1       principalAddress1       1680 CAPITAL ONE DRIVE    1680 Capital One Dr
2           principalCity                       Mclean                Mc Lean
3  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd

False

              Column                Orig Val           New Val
0           entityId             19941032367       19941032367
1  principalAddress1  1824 South Barona Road  1824 S Barona Rd
2    mailingAddress1  1824 South Barona Road  1824 S Barona Rd

False

                Column     Orig Val       New Val
0             entityId  19941034704  1.994103e+10
1  agentMailingZipCode        80540  8.054000e+04

False

                   Column             Orig Val            New Val
0                entityId          19941050072        19941050072
1         mailingAddress1        P.O. BOX 3086        PO Box 3086
2  agentPrincipalAddress1  207 GlenEaton Drive  207 Glen Eaton Dr
3      agentPrincipalCity       PAGOSA SPRINGS     Pagosa Springs

False

            Column      Orig Val      New Val
0         entityId   19941057478  19941057478
1  mailingAddress1  P.O Box 1087  PO Box 1087

False

                   Column        Orig Val         New Val
0                entityId     19941072839     19941072839
1       principalAddress1  303 NAVAJO AVE  303 Navajo Ave
2  agentPrincipalAddress1  303 NAVAJO AVE  303 Navajo Ave
3      agentPrincipalCity         FLAGLER         Flagler
4    agentMailingAddress1       PO Box 74      PO Box 174

False

,Column,Orig Val,New Val
0,entityId,19941076423,19941076423
1,principalAddress1,23024 US Highway 6,49 2nd St
2,principalAddress2,Suite 202,NaN
3,principalCity,Keystone,Montezuma
4,mailingAddress1,23024 US Highway 6,NaN
5,mailingAddress2,Suite 202,NaN
6,mailingCity,Keystone,NaN
7,mailingState,CO,NaN
8,mailingZipCode,80435,NaN
9,mailingCountry,US,NaN
10,entityStatus,Delinquent,Good Standing
11,agentOrganizationName,Vacasa Association Management Solutions - Moun...,Zuma's Finest Property Services
12,agentPrincipalAddress1,0500 ALPINE RD,49 2nd St
13,agentPrincipalCity,Dillon,Montezuma
14,agentMailingAddress1,105 Red Cloud Peak Drive,NaN
15,agentMailingAddress2,Suite 202,NaN
16,agentMailingCity,Dillon,NaN
17,agentMailingState,CO,NaN
18,agentMailingZipCode,80435,NaN
19,agentMailingCountry,US,NaN

False

                Column     Orig Val       New Val
0             entityId  19941144851  1.994114e+10
1  agentMailingZipCode        80721  8.072100e+04

False

                Column     Orig Val       New Val
0             entityId  19951000140  1.995100e+10
1  agentMailingZipCode        81427  8.142700e+04

False

,Column,Orig Val,New Val
0,entityId,19951016315,19951016315
1,entityName,"OHM SYSTEMS, INC.","OHM SYSTEMS, INC., Colorado Authority Relinqui..."
2,principalAddress1,701 Fifth Avenue,1601 Chestnut St.
3,principalAddress2,Suite 4900,NaN
4,principalCity,Seattle,Philadelphia
5,principalZipCode,98104,19192
6,entityStatus,Good Standing,Withdrawn
7,agentOrganizationName,C T Corporation System,NaN
8,agentPrincipalAddress1,7700 E Arapahoe Rd Ste 220,NaN
9,agentPrincipalCity,Centennial,NaN
10,agentPrincipalState,CO,NaN
11,agentPrincipalZipCode,80112-1268,NaN
12,agentPrincipalCountry,US,NaN

False

                Column     Orig Val       New Val
0             entityId  19951018093  1.995102e+10
1  agentMailingZipCode        81435  8.143500e+04

False

                 Column     Orig Val      New Val
0              entityId  19951069729  19951069729
1       mailingAddress1  PO BOX 2209  PO Box 2209
2  agentMailingAddress1  PO BOX 2209  PO Box 2209
3      agentMailingCity       BASALT       Basalt

False

                 Column      Orig Val                 New Val
0              entityId  1.995108e+10             19951077997
1  agentMailingAddress1           NaN  201 E. 4th Street #130
2      agentMailingCity           NaN                Loveland
3     agentMailingState           NaN                      CO
4   agentMailingZipCode           NaN                   80537
5   agentMailingCountry           NaN                      US

False

                   Column               Orig Val                    New Val
0                entityId            19951107843                19951107843
1       principalAddress1    1250 Bergen Parkway  1250 Bergen Pkwy Ste B100
2       principalAddress2            Suite B-100                        NaN
3         mailingAddress1                    NaN      24123 Running Deer Rd
4             mailingCity                    NaN                    Conifer
5            mailingState                    NaN                         CO
6          mailingZipCode                    NaN                      80433
7          mailingCountry                    NaN                         US
8  agentPrincipalAddress1  24123 RUNNING DEER RD      24123 Running Deer Rd
9      agentPrincipalCity                 FOXTON                    Conifer

False

,Column,Orig Val,New Val
0,entityId,19951149529,19951149529
1,entityName,"JANCO PARTNERS, INC., Delinquent September 1, ...","JANCO PARTNERS, INC., Dissolved May 10, 2023"
2,principalAddress1,5231 S. Quebec St.,4875 S MONACO ST
3,principalAddress2,Ste. 200,APT 703
4,principalCity,Greenwood Village,Denver
5,principalZipCode,80111,80237
6,mailingAddress1,5231 S. Quebec,4875 S MONACO ST
7,mailingAddress2,200,APT 703
8,mailingCity,Greenwood Village,Denver
9,mailingZipCode,80111,80237
10,entityStatus,Delinquent,Voluntarily Dissolved

False

                   Column                     Orig Val                New Val
0                entityId                  19961034546            19961034546
1       principalAddress1               11 MADISON AVE      11 MADISON AVENUE
2       principalAddress2                CORP TAX DEPT                    NaN
3  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd

False

              Column             Orig Val         New Val
0           entityId          19961035185     19961035185
1  principalAddress1  8615 N. 29th Street  8615 N 29th St
2    mailingAddress1         PO BOX 12097    PO Box 12097

False

,Column,Orig Val,New Val
0,entityId,19961056608,19961056608
1,principalAddress1,25967 CONIFER ROAD,25967 Conifer Rd
2,agentPrincipalAddress1,"1801 California Street, Suite 2600",1801 California St Ste 2600

False

       Column             Orig Val                            New Val
0    entityId          19961061964                        19961061964
1  entityName           UCPM, Inc.                          UCPM, LLC
2  entityType  Foreign Corporation  Foreign Limited Liability Company

False

           Column     Orig Val        New Val
0        entityId  19961083900    19961083900
1  mailingCountry          NaN             US
2    entityStatus   Delinquent  Good Standing

False

,Column,Orig Val,New Val
0,entityId,19961084578,19961084578
1,principalAddress1,1701 S BROADWAY,1701 S Broadway
2,agentOrganizationName,Dependable Cleaners,"Dependable Cleaners and Shirt Laundry, Inc."
3,agentPrincipalAddress1,1701 S BROADWAY,1701 S Broadway
4,agentPrincipalCity,DENVER,Denver

False

            Column             Orig Val       New Val
0         entityId          19961141995  1.996114e+10
1  mailingAddress1  6110 E Colfax 4-323           NaN
2      mailingCity               Denver           NaN
3     mailingState                   CO           NaN
4   mailingZipCode                80220           NaN
5   mailingCountry                   US           NaN

False

                Column     Orig Val       New Val
0             entityId  19961153080  1.996115e+10
1  agentMailingZipCode        81615  8.161500e+04

False

            Column              Orig Val       New Val
0         entityId           19961161053  1.996116e+10
1  mailingAddress1  126 East 56th Street           NaN
2  mailingAddress2                   10R           NaN
3      mailingCity              New York           NaN
4     mailingState                    NY           NaN
5   mailingZipCode                 10022           NaN
6   mailingCountry                    US           NaN

False

                Column     Orig Val       New Val
0             entityId  19961170804  1.996117e+10
1  agentMailingZipCode        80301  8.030100e+04

False

,Column,Orig Val,New Val
0,entityId,19971005717,19971005717
1,agentOrganizationName,C T Corporation System,Corporation Service Company
2,agentPrincipalAddress1,7700 E Arapahoe Rd Ste 220,1900 W. Littleton Boulevard
3,agentPrincipalCity,Centennial,Littleton
4,agentPrincipalZipCode,80112-1268,80120

False

                Column     Orig Val       New Val
0             entityId  19971010313  1.997101e+10
1  agentMailingZipCode        80228  8.022800e+04

False

                Column     Orig Val       New Val
0             entityId  19971014987  1.997101e+10
1  agentMailingZipCode        81435  8.143500e+04

False

,Column,Orig Val,New Val
0,entityId,19971043477,19971043477
1,principalAddress1,2151 Whitfield Industrial Way,6015 31st St E Ste 201
2,principalCity,Sarasota,Bradenton
3,principalZipCode,34243,34203
4,mailingAddress1,2151 Whitfield Industrial Way,NaN
5,mailingCity,Sarasota,NaN
6,mailingState,FL,NaN
7,mailingZipCode,34243,NaN
8,mailingCountry,US,NaN
9,agentPrincipalZipCode,80112-1268,80112
10,agentMailingAddress1,2151 Whitfield Industrial Way,NaN
11,agentMailingCity,Sarasota,NaN
12,agentMailingState,CO,NaN
13,agentMailingZipCode,34243,NaN
14,agentMailingCountry,US,NaN

False

                   Column                     Orig Val                New Val
0                entityId                  19971046485            19971046485
1       principalAddress1                   PO Box 897   11013 N Woodstock St
2         mailingAddress1                          NaN             PO Box 897
3         mailingAddress2                          NaN   11013 N Woodstock St
4             mailingCity                          NaN                Huntley
5            mailingState                          NaN                     IL
6          mailingZipCode                          NaN                  60142
7          mailingCountry                          NaN                     US
8  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd

False

                Column     Orig Val       New Val
0             entityId  19971046674  1.997105e+10
1  agentMailingZipCode        81501  8.150100e+04

False

,Column,Orig Val,New Val
0,entityId,19971056930,19971056930
1,principalAddress1,429 LENOX AVE,Ondrish & Associates
2,principalAddress2,NaN,"1660 Lincoln St, Ste 2200"
3,principalCity,Miami Beach,Denver
4,principalState,FL,CO
5,principalZipCode,33139,80264
6,mailingAddress1,Ondrish & Associates,NaN
7,mailingAddress2,"1660 Lincoln Street, Suite 2200",NaN
8,mailingCity,Denver,NaN
9,mailingState,CO,NaN
10,mailingZipCode,80264,NaN
11,mailingCountry,US,NaN
12,agentPrincipalAddress1,429 LENOX AVE,Ondrish & Associates
13,agentPrincipalAddress2,NaN,"1660 Lincoln St, Ste 2200"
14,agentPrincipalCity,Miami Beach,Denver
15,agentPrincipalZipCode,33139,80264
16,agentMailingAddress1,Ondrish & Associates,NaN
17,agentMailingAddress2,"1660 Lincoln Street, Suite 2200",NaN
18,agentMailingCity,Denver,NaN
19,agentMailingState,CO,NaN
20,agentMailingZipCode,80264,NaN
21,agentMailingCountry,US,NaN

False

              Column                 Orig Val                       New Val
0           entityId              19971073921                   19971073921
1  principalAddress1  2500 Cumberland Parkway  6980 N. Port Washington Road
2      principalCity                  Atlanta                     Milwaukee
3     principalState                       GA                            WI
4   principalZipCode                    30339                         53217

False

                   Column           Orig Val             New Val
0                entityId        19971074618         19971074618
1       principalAddress1  5341 S DUNKIRK WY  5341 S Dunkirk Way
2  agentPrincipalAddress1  5341 S DUNKIRK WY  5341 S Dunkirk Way

False

                Column     Orig Val       New Val
0             entityId  19971074731  1.997107e+10
1  agentMailingZipCode        80446  8.044600e+04

False

                   Column                   Orig Val                  New Val
0                entityId                19971074783              19971074783
1       principalAddress1  210 S.E. INDEPENDENCE AVE  210 SE Independence Ave
2  agentPrincipalAddress1  210 S.E. INDEPENDENCE AVE  210 SE Independence Ave
3      agentPrincipalCity                  CEDAREDGE                Cedaredge

False

                Column     Orig Val       New Val
0             entityId  19971075912  1.997108e+10
1  agentMailingZipCode        81201  8.120100e+04

False

                   Column              Orig Val          New Val
0                entityId           19971079465      19971079465
1       principalAddress1  5438 N. Xenia Street  5438 N Xenia St
2        principalZipCode            80238-3870            80238
3  agentPrincipalAddress1  5438 N. Xenia Street  5438 N Xenia St

False

                Column     Orig Val       New Val
0             entityId  19971095601  1.997110e+10
1  agentMailingZipCode        80446  8.044600e+04

False

                Column     Orig Val       New Val
0             entityId  19971122711  1.997112e+10
1  agentMailingZipCode        80132  8.013200e+04

False

                Column     Orig Val       New Val
0             entityId  19971131869  1.997113e+10
1  agentMailingZipCode        80163  8.016300e+04

False

                Column     Orig Val       New Val
0             entityId  19971134894  1.997113e+10
1  agentMailingZipCode        81226  8.122600e+04

False

                Column     Orig Val       New Val
0             entityId  19981039402  1.998104e+10
1  agentMailingZipCode        81147  8.114700e+04

False

,Column,Orig Val,New Val
0,entityId,19981043122,19981043122
1,principalAddress1,18521 E. Queen Creekl Rd,18521 E Queen Creek Rd Ste 105-626
2,principalAddress2,Suite 105-626,NaN

False

                   Column                     Orig Val                New Val
0                entityId                  19981044933            19981044933
1       principalAddress1             1400 16th Street   1400 16th St Ste 320
2       principalAddress2                    Suite 320                    NaN
3  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd

False

                   Column                     Orig Val                 New Val
0                entityId                  19981053172             19981053172
1       principalAddress1          200 E. RANDOLPH ST.  200 E Randolph St Fl 8
2  agentPrincipalAddress1  1900 W. Littleton Boulevard   1900 W Littleton Blvd

False

                   Column                   Orig Val                New Val
0                entityId                19981057570            19981057570
1  agentPrincipalAddress1  4033 BOARDWALK DR STE 200  1701 MEADOWAIRE DRIVE
2  agentPrincipalAddress2                  SUITE 200                    NaN
3    agentMailingAddress1      4033 BOARDWALK DR 200                    NaN
4        agentMailingCity               FORT COLLINS                    NaN
5       agentMailingState                         CO                    NaN
6     agentMailingZipCode                      80525                    NaN
7     agentMailingCountry                         US                    NaN

False

                   Column                     Orig Val                 New Val
0                entityId                  19981065536             19981065536
1       principalAddress1               5190 Neil Road  777 S. Figueroa Street
2       principalAddress2                    Suite 560              16th Floor
3           principalCity                         Reno             Los Angeles
4          principalState                           NV                      CA
5        principalZipCode                        89502                   90017
6  agentPrincipalAddress1  1900 W. Littleton Boulevard   1900 W Littleton Blvd

False

                   Column         Orig Val        New Val
0                entityId      19981073334    19981073334
1       principalAddress1    861 SHEKEL LN  861 Shekel Ln
2  agentPrincipalAddress1    861 SHEKEL LN  861 Shekel Ln
3      agentPrincipalCity     BRECKENRIDGE   Breckenridge
4    agentMailingAddress1  861 Shekel Lane            NaN
5    agentMailingAddress2     Breckenridge            NaN
6        agentMailingCity     Breckenridge            NaN
7       agentMailingState               CO            NaN
8     agentMailingZipCode            80424            NaN
9     agentMailingCountry               US            NaN

False

                 Column              Orig Val       New Val
0              entityId           19981076636  1.998108e+10
1  agentMailingAddress1  1942 Broadway Street           NaN
2      agentMailingCity               Boulder           NaN
3     agentMailingState                    CO           NaN
4   agentMailingZipCode                 80302           NaN
5   agentMailingCountry                    US           NaN

False

                   Column              Orig Val               New Val
0                entityId           19981077933           19981077933
1  agentPrincipalAddress1  783 S. Youngfield Ct  783 S Youngfield Ct.

False

                   Column         Orig Val        New Val
0                entityId      19981081562    19981081562
1       principalAddress1       901 N MAIN  901 N Main St
2         agentMiddleName               K.            NaN
3  agentPrincipalAddress1   901 N Main St.  901 N Main St
4      agentPrincipalCity         GUNNISON       Gunnison
5    agentMailingAddress1  901 N. Main St.            NaN
6        agentMailingCity         GUNNISON            NaN
7       agentMailingState               CO            NaN
8     agentMailingZipCode            81230            NaN
9     agentMailingCountry               US            NaN

False

,Column,Orig Val,New Val
0,entityId,19981081910,19981081910
1,entityName,Rocky Mountain Racing Works Inc. dba KTM of Aspen,Rocky Mountain Racing Works Inc. dba KTM of As...
2,entityStatus,Good Standing,Voluntarily Dissolved

False

,Column,Orig Val,New Val
0,entityId,19981082567,19981082567
1,principalAddress1,4845 Pearl East Circle,4845 Pearl East Cir Ste 101
2,principalAddress2,Suite 101,NaN
3,agentPrincipalAddress1,4845 Pearl East Circle,4845 Pearl East Cir Ste 101
4,agentPrincipalAddress2,Suite 101,NaN
5,agentPrincipalCity,BOULDER,Boulder
6,agentMailingAddress1,NaN,4845 Pearl East Cir Ste 101
7,agentMailingCity,NaN,Boulder
8,agentMailingState,NaN,CO
9,agentMailingZipCode,NaN,80301
10,agentMailingCountry,NaN,US

False

                   Column                Orig Val                New Val
0                entityId             19981085317            19981085317
1       principalAddress1  1057 Dancing Horse Dr.  1057 Dancing Horse Dr
2  agentPrincipalAddress1  1057 Dancing Horse Dr.  1057 Dancing Horse Dr
3    agentMailingAddress1                    1057                    NaN
4    agentMailingAddress2       Dancing Horse Dr.                    NaN
5        agentMailingCity        Colorado Springs                    NaN
6       agentMailingState                      CO                    NaN
7     agentMailingZipCode                   80919                    NaN
8     agentMailingCountry                      US                    NaN

False

                Column     Orig Val       New Val
0             entityId  19981094262  1.998109e+10
1  agentMailingZipCode        81147  8.114700e+04

False

                  Column         Orig Val        New Val
0               entityId      19981096681    19981096681
1       principalZipCode       64108-2670          64108
2        mailingAddress1  P.O. BOX 419052  PO Box 419052
3         mailingZipCode       64141-6052          64141
4  agentPrincipalZipCode       80112-1268          80112

False

                Column     Orig Val       New Val
0             entityId  19981105902  1.998111e+10
1  agentMailingZipCode        80103  8.010300e+04

False

            Column      Orig Val       New Val
0         entityId  1.998113e+10   19981132659
1  mailingAddress1           NaN  P O BOX 1012
2      mailingCity           NaN    Wellington
3     mailingState           NaN            CO
4   mailingZipCode           NaN         80549
5   mailingCountry           NaN            US

False

                   Column            Orig Val            New Val
0                entityId         19981199524        19981199524
1       principalAddress1    225 SOUTH PAGOSA  225 S Pagosa Blvd
2  agentPrincipalAddress1  225 S. Pagosa Blvd  225 S Pagosa Blvd
3    agentMailingAddress1  225 S. Pagosa Blvd  225 S Pagosa Blvd

False

                Column     Orig Val       New Val
0             entityId  19981216235  1.998122e+10
1  agentMailingZipCode        81641  8.164100e+04

False

                    Column     Orig Val           New Val
0                 entityId  19981220839       19981220839
1        principalAddress1   PO Box 125     2619 Clyde St
2            principalCity       Beulah          Matlacha
3           principalState           CO                FL
4         principalZipCode        81023             33993
5          mailingAddress1          NaN        PO Box 125
6              mailingCity          NaN            Beulah
7             mailingState          NaN                CO
8           mailingZipCode          NaN             81023
9           mailingCountry          NaN                US
10  agentPrincipalAddress1   PO Box 125  9529 HWY 78 WEST
11      agentPrincipalCity       Beulah            BEULAH
12    agentMailingAddress1   PO Box 118        PO Box 125
13        agentMailingCity     Matlacha            Beulah
14     agentMailingZipCode        33993             81023

False

                   Column              Orig Val               New Val
0                entityId           19981223924           19981223924
1       principalAddress1      950 Ogden Street  950 N Ogden St Apt 4
2       principalAddress2                Unit 4                   NaN
3        principalZipCode            80218-2828                 80218
4  agentPrincipalAddress1  950 Ogden St., Apt 4  950 N Ogden St Apt 4

False

                 Column        Orig Val                 New Val
0              entityId     19991013620             19991013620
1     principalAddress1  1597 Cole Blvd  1597 Cole Blvd Ste 100
2     principalAddress2       Suite 100                     NaN
3          entityStatus    Noncompliant           Good Standing
4  agentMailingAddress1             NaN  1597 Cole Blvd Ste 100
5      agentMailingCity             NaN                Lakewood
6     agentMailingState             NaN                      CO
7   agentMailingZipCode             NaN                   80401
8   agentMailingCountry             NaN                      US

False

                  Column             Orig Val       New Val
0               entityId          19991016959  1.999102e+10
1        mailingAddress1  400 Bear Trax Drive           NaN
2            mailingCity          Canyon City           NaN
3           mailingState                   CO           NaN
4         mailingZipCode                81212           NaN
5         mailingCountry                   US           NaN
6   agentMailingAddress1  400 Bear Trax Drive           NaN
7       agentMailingCity           Canon City           NaN
8      agentMailingState                   CO           NaN
9    agentMailingZipCode                81212           NaN
10   agentMailingCountry                   US           NaN

False

,Column,Orig Val,New Val
0,entityId,19991040403,19991040403
1,entityName,"Joseph O'Leary DDS, PLLC","Joseph O'Leary DDS, PLLC, Dissolved May 10, 2023"
2,entityStatus,Good Standing,Voluntarily Dissolved

False

                   Column           Orig Val                    New Val
0                entityId        19991041567                19991041567
1       principalAddress1  4450 Arapahoe Ave  4450 Arapahoe Ave Ste 100
2       principalAddress2          Suite 100                        NaN
3  agentPrincipalAddress1  4450 Arapahoe Ave  4450 Arapahoe Ave Ste 100
4  agentPrincipalAddress2            Ste 100                        NaN

False

                   Column                     Orig Val                New Val
0                entityId                  19991059180            19991059180
1  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd

False

            Column             Orig Val       New Val
0         entityId          19991073135  1.999107e+10
1  mailingAddress1  6110 E Colfax 4-323           NaN
2      mailingCity               Denver           NaN
3     mailingState                   CO           NaN
4   mailingZipCode                80220           NaN
5   mailingCountry                   US           NaN

False

            Column             Orig Val       New Val
0         entityId          19991073140  1.999107e+10
1  mailingAddress1  6110 E Colfax 4-323           NaN
2      mailingCity               Denver           NaN
3     mailingState                   CO           NaN
4   mailingZipCode                80220           NaN
5   mailingCountry                   US           NaN

False

                    Column                Orig Val                    New Val
0                 entityId             19991073809                19991073809
1        principalAddress1              PO BOX 110  301 S Howes St Fl 1 # 110
2         principalZipCode                   80522                      80521
3          mailingAddress1                     NaN                 PO Box 110
4              mailingCity                     NaN               Fort Collins
5             mailingState                     NaN                         CO
6           mailingZipCode                     NaN                      80522
7           mailingCountry                     NaN                         US
8           agentFirstName                   VICKI                       Sara
9          agentMiddleName                      V.                        NaN
10           agentLastName                  LUCERO                    Szakaly
11  agentPrincipalAddress1  200 WEST OAK, STE 4100           4101 Laporte Ave
12      agentPrincipalCity            FORT COLLINS               Fort Collins
13    agentMailingAddress1  200 W Oak St, Ste 4100                 PO Box 110
14     agentMailingZipCode                   80521                      80522

False

                   Column                     Orig Val                New Val
0                entityId                  19991088516            19991088516
1  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd

False

                   Column              Orig Val              New Val
0                entityId           19991094001          19991094001
1       principalAddress1  3365 N. Academy Blvd  3365 N Academy Blvd
2  agentPrincipalAddress1  3365 N. Academy Blvd  3365 N Academy Blvd
3    agentMailingAddress1   3365 N Academy Blvd                  NaN
4        agentMailingCity      Colorado Springs                  NaN
5       agentMailingState                    CO                  NaN
6     agentMailingZipCode                 80917                  NaN
7     agentMailingCountry                    US                  NaN

False

,Column,Orig Val,New Val
0,entityId,19991101012,19991101012
1,principalAddress1,650 S CHERRY ST,650 S Cherry St Ste 1400
2,principalAddress2,STE 1400,NaN
3,principalZipCode,80246-1815,80246
4,mailingAddress1,650 S CHERRY ST,NaN
5,mailingAddress2,STE 1400,NaN
6,mailingCity,Denver,NaN
7,mailingState,CO,NaN
8,mailingZipCode,80246-1815,NaN
9,mailingCountry,US,NaN
10,agentMiddleName,F.,NaN
11,agentPrincipalAddress1,650 SO CHERRY ST STE 1400,650 S Cherry St Ste 1400
12,agentPrincipalCity,DENVER,Denver
13,agentMailingAddress1,650 S CHERRY ST,650 S Cherry St Ste 1400
14,agentMailingAddress2,STE 1400,NaN
15,agentMailingCity,DENVER,Denver

False

                Column     Orig Val       New Val
0             entityId  19991104066  1.999110e+10
1  agentMailingZipCode        80237  8.023700e+04

False

                   Column                     Orig Val                 New Val
0                entityId                  19991119092             19991119092
1       principalAddress1               5190 Neil Road  777 S. Figueroa Street
2       principalAddress2                    Suite 560              16th Floor
3           principalCity                         Reno             Los Angeles
4          principalState                           NV                      CA
5        principalZipCode                        89502                   90017
6  agentPrincipalAddress1  1900 W. Littleton Boulevard   1900 W Littleton Blvd

False

            Column             Orig Val       New Val
0         entityId          19991137705  1.999114e+10
1  mailingAddress1  6110 E Colfax 4-323           NaN
2      mailingCity               Denver           NaN
3     mailingState                   CO           NaN
4   mailingZipCode                80220           NaN
5   mailingCountry                   US           NaN

False

                Column     Orig Val       New Val
0             entityId  19991162295  1.999116e+10
1  agentMailingZipCode        81130  8.113000e+04

False

                Column     Orig Val       New Val
0             entityId  19991182207  1.999118e+10
1  agentMailingZipCode        81435  8.143500e+04

False

                    Column                Orig Val                     New Val
0                 entityId             19991214877                 19991214877
1           agentFirstName                  Arturo                         NaN
2            agentLastName                 Vasquez                         NaN
3    agentOrganizationName                     NaN      Registered Agents Inc.
4   agentPrincipalAddress1  3587 Stone Canyon Road  1942 Broadway St. STE 314C
5       agentPrincipalCity                   Lyons                     Boulder
6    agentPrincipalZipCode                   80540                       80302
7     agentMailingAddress1           P.O. Box 2526                         NaN
8         agentMailingCity                Longmont                         NaN
9        agentMailingState                      CO                         NaN
10     agentMailingZipCode                   80502                         NaN
11     agentMailingCountry                      US                         NaN

False

,Column,Orig Val,New Val
0,entityId,20001030370,20001030370
1,principalAddress1,BOK Financial c/o Hudson Mead,1600 Broadway
2,principalAddress2,"1600 Broadway, 3rd Floor",4th Floor c/o Russ Gamble
3,entityStatus,Delinquent,Good Standing
4,agentPrincipalAddress1,BOK Financial c/o Hudson Mead,1600 Broadway
5,agentPrincipalAddress2,1600 Broadway 3rd Floor,4th Floor c/o Russ Gamble

False

                Column     Orig Val       New Val
0             entityId  20001050535  2.000105e+10
1  agentMailingZipCode        81133  8.113300e+04

False

       Column           Orig Val       New Val
0    entityId        20001055128   20001055128
1  entityName  CallisonRTKL Inc.  Arcadis Inc.

False

                   Column                     Orig Val                New Val
0                entityId                  20001063222            20001063222
1  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd
2    agentMailingAddress1     101 West Prospect Avenue                    NaN
3        agentMailingCity                    Cleveland                    NaN
4       agentMailingState                           CO                    NaN
5     agentMailingZipCode                        44115                    NaN
6     agentMailingCountry                           US                    NaN

False

                   Column            Orig Val            New Val
0                entityId         20001070942        20001070942
1       principalAddress1  112 E Douglas Ave.  112 E Douglas Ave
2         mailingAddress1  112 E Douglas Ave.  112 E Douglas Ave
3  agentPrincipalAddress1  112 E Douglas Ave.  112 E Douglas Ave
4    agentMailingAddress1  112 E. Douglas Ave  112 E Douglas Ave
5    agentMailingAddress2          (optional)           Optional

False

                   Column                 Orig Val              New Val
0                entityId              20001077687          20001077687
1       principalAddress1        5000 5026 WARD RD         5000 WARD RD
2   agentOrganizationName       Messner Reeves LLP  MESSNER REEVES, LLP
3  agentPrincipalAddress1  1550 Wewatta St Ste 710  1550 WEWATTA STREET
4      agentPrincipalCity                   Denver               DENVER
5    agentMailingAddress1                      NaN  1550 WEWATTA STREET
6        agentMailingCity                      NaN               DENVER
7       agentMailingState                      NaN                   CO
8     agentMailingZipCode                      NaN                80202
9     agentMailingCountry                      NaN                   US

False

                    Column           Orig Val              New Val
0                 entityId        20001077690          20001077690
1        principalAddress1  5000-5026 WARD RD         5000 WARD RD
2           agentFirstName               Mary                  NaN
3          agentMiddleName                  E                  NaN
4            agentLastName             Pierce                  NaN
5    agentOrganizationName                NaN  MESSNER REEVES, LLP
6   agentPrincipalAddress1     5000 Ward Road  1550 WEWATTA STREET
7       agentPrincipalCity        Wheat Ridge               DENVER
8    agentPrincipalZipCode              80033                80202
9     agentMailingAddress1     5000 Ward Road  1550 WEWATTA STREET
10        agentMailingCity        Wheat Ridge               DENVER
11     agentMailingZipCode              80033                80202

False

,Column,Orig Val,New Val
0,entityId,20001095838,20001095838
1,principalAddress1,2150 West Garden of the Gods Road,2150 Garden of the Gods Rd
2,mailingAddress1,NaN,PO Box 76120
3,mailingCity,NaN,Colorado Springs
4,mailingState,NaN,CO
5,mailingZipCode,NaN,80970
6,mailingCountry,NaN,US
7,agentPrincipalAddress1,2150 West Garden of the Gods Road,2150 Garden of the Gods Rd
8,agentMailingAddress1,NaN,PO Box 76120
9,agentMailingCity,NaN,Colorado Springs
10,agentMailingState,NaN,CO
11,agentMailingZipCode,NaN,80970
12,agentMailingCountry,NaN,US

False

                   Column          Orig Val           New Val
0                entityId       20001099907       20001099907
1       principalAddress1  5906 MCINTYRE ST  11010 W 29th Ave
2           principalCity            Golden          Lakewood
3        principalZipCode        80403-7445        80215-7120
4         mailingAddress1  11010 W 29th Ave               NaN
5             mailingCity          Lakewood               NaN
6            mailingState                CO               NaN
7          mailingZipCode        80215-7120               NaN
8          mailingCountry                US               NaN
9  agentPrincipalAddress1  11010 W 29TH AVE  11010 W 29th Ave

False

                   Column                Orig Val             New Val
0                entityId             20001105189         20001105189
1       principalAddress1  3150 North 12th Street      3150 N 12th St
2         mailingAddress1            Po Box 10700        PO Box 10700
3          mailingZipCode              81502-5517               81502
4   agentOrganizationName       PCP INVESTORS LLC  PCP INVESTORS, LLC
5  agentPrincipalAddress1  3150 North 12th Street      3150 N 12th St
6    agentMailingAddress1            Po Box 10700        PO Box 10700
7     agentMailingZipCode              81502-5517               81502

False

,Column,Orig Val,New Val
0,entityId,20001140031,20001140031
1,entityName,"TRINITY BENEFITS GROUP, INC., Delinquent May 1...","TRINITY BENEFITS GROUP, INC."
2,principalAddress1,212 W. 13TH STREET,5755 Oberlin Drive
3,principalAddress2,NaN,301
4,principalCity,Pueblo,San Diego
5,principalState,CO,CA
6,principalZipCode,81003,92121
7,mailingAddress1,NaN,5426 zeil Place
8,mailingCity,NaN,San Diego
9,mailingState,NaN,CA
10,mailingZipCode,NaN,92105
11,mailingCountry,NaN,US
12,entityStatus,Delinquent,Good Standing
13,agentFirstName,MAURICE,NaN
14,agentMiddleName,S.,NaN
15,agentLastName,GORING,NaN
16,agentOrganizationName,NaN,Firstkontak Consulting Inc
17,agentPrincipalAddress1,212 W. 13TH STREET,240 W 4TH AVENUE
18,agentPrincipalCity,PUEBLO,DENVER
19,agentPrincipalZipCode,81003,80223

False

                Column     Orig Val       New Val
0             entityId  20001155465  2.000116e+10
1  agentMailingZipCode        80424  8.042400e+04

False

            Column             Orig Val       New Val
0         entityId          20011019120  2.001102e+10
1  mailingAddress1  6110 E Colfax 4-323           NaN
2      mailingCity               Denver           NaN
3     mailingState                   CO           NaN
4   mailingZipCode                80220           NaN
5   mailingCountry                   US           NaN

False

                Column     Orig Val       New Val
0             entityId  20011028859  2.001103e+10
1  agentMailingZipCode        80477  8.047700e+04

False

,Column,Orig Val,New Val
0,entityId,20011051561,20011051561
1,principalAddress1,350 FELLOWSHIP RD STE 100,350 Fellowship Rd Ste 100
2,principalCity,Mt Laurel,Mount Laurel
3,agentPrincipalAddress1,1900 W. Littleton Boulevard,1900 W Littleton Blvd

False

                   Column                     Orig Val                 New Val
0                entityId                  20011056467             20011056467
1       principalAddress1          200 E. RANDOLPH ST.  200 E Randolph St Fl 8
2  agentPrincipalAddress1  1900 W. Littleton Boulevard   1900 W Littleton Blvd

False

                   Column                     Orig Val                New Val
0                entityId                  20011073954            20011073954
1  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd

False

                 Column           Orig Val               New Val
0              entityId        20011076030           20011076030
1     principalAddress1     340 SILVERLODE  340 SILVERLODE DRIVE
2  agentMailingAddress1  340 SILVERLODE DR                   NaN
3      agentMailingCity              Aspen                   NaN
4     agentMailingState                 CO                   NaN
5   agentMailingZipCode              81611                   NaN
6   agentMailingCountry                 US                   NaN

False

                   Column            Orig Val            New Val
0                entityId         20011077076        20011077076
1        principalZipCode          80229-7515              80229
2  agentPrincipalAddress1  5699 Dexter Street     5699 Dexter St
3    agentMailingAddress1                 NaN  7040 Elizabeth St
4        agentMailingCity                 NaN             Denver
5       agentMailingState                 NaN                 CO
6     agentMailingZipCode                 NaN              80229
7     agentMailingCountry                 NaN                 US

False

                   Column          Orig Val                New Val
0                entityId       20011097520            20011097520
1       principalAddress2       Fifth Floor              5th Floor
2  agentPrincipalAddress2       Fifth Floor              5th Floor
3    agentMailingAddress1  4350 S Monaco St  4350 S. Monaco Street
4    agentMailingAddress2           Floor 5              5th Floor
5        agentMailingCity            Denver                 DENVER

False

                   Column             Orig Val               New Val
0                entityId          20011098944           20011098944
1       principalAddress1        2702 E EMPIRE      2702 E Empire St
2         mailingAddress1           PO BOX 322            PO Box 322
3  agentPrincipalAddress1     7399 Hwy 160-491  7399 Highway 160-491
4    agentMailingAddress1  7399 US HWY 160-491  7399 Highway 160-491
5        agentMailingCity           CO  Cortez                Cortez

False

                   Column                 Orig Val                     New Val
0                entityId              20011100080                 20011100080
1       principalAddress1  3001 Brighton Boulevard  3001 Brighton Blvd Ste 236
2       principalAddress2                Suite 236                         NaN
3  agentPrincipalAddress1  3001 Brighton Boulevard  3001 Brighton Blvd Ste 236
4  agentPrincipalAddress2                Suite 236                         NaN
5    agentMailingAddress1                      NaN  3001 Brighton Blvd Ste 236
6        agentMailingCity                      NaN                      Denver
7       agentMailingState                      NaN                          CO
8     agentMailingZipCode                      NaN                       80216
9     agentMailingCountry                      NaN                          US

False

                   Column            Orig Val                New Val
0                entityId         20011104363            20011104363
1       principalAddress1    8729 E. 23rd Ave        8729 E 23rd Ave
2  agentPrincipalAddress1  1099 - 18th Street  1099 18th St Ste 2600
3  agentPrincipalAddress2          Suite 2600                    NaN
4    agentMailingAddress2    Denver, Colorado        Denver Colorado

False

                   Column             Orig Val            New Val
0                entityId          20011105336        20011105336
1       principalAddress1  785 Columbine Drive  785 Windy Rose Dr
2         mailingAddress1       P. O. Box 3517        PO Box 3517
3  agentPrincipalAddress1  785 Columbine Drive  785 Windy Rose Dr
4      agentPrincipalCity           ESTES PARK         Estes Park
5    agentMailingAddress1          PO BOX 3517        PO Box 3517
6        agentMailingCity           ESTES PARK         Estes Park

False

                   Column              Orig Val          New Val
0                entityId           20011109708      20011109708
1       principalAddress1  61430 Longview TRAIL  61017 Kansas Rd
2  agentPrincipalAddress1    61430 Longview Trl  61017 Kansas Rd
3    agentMailingAddress1      13744  6100 Road              NaN
4        agentMailingCity              Montrose              NaN
5       agentMailingState                    CO              NaN
6     agentMailingZipCode                 81403              NaN
7     agentMailingCountry                    US              NaN

False

            Column                            Orig Val       New Val
0         entityId                         20011214622  2.001121e+10
1  mailingAddress1  1801 California Street, 23rd Floor           NaN
2      mailingCity                              Denver           NaN
3     mailingState                                  CO           NaN
4   mailingZipCode                               80202           NaN
5   mailingCountry                                  US           NaN

False

              Column               Orig Val                New Val
0           entityId            20141110204            20141110204
1  principalAddress1  8765 Jackson Creek Rd      7034 W Roxbury Pl
2      principalCity                Sedalia              Littleton
3   principalZipCode                  80135                  80128
4    mailingAddress1                    NaN  8765 Jackson Creek Rd
5        mailingCity                    NaN                Sedalia
6       mailingState                    NaN                     CO
7     mailingZipCode                    NaN                  80135
8     mailingCountry                    NaN                     US

False

                 Column         Orig Val       New Val
0              entityId      20011244933  2.001124e+10
1  agentMailingAddress1     429 Bond st.           NaN
2      agentMailingCity  Manitou Springs           NaN
3     agentMailingState               CO           NaN
4   agentMailingZipCode            80829           NaN
5   agentMailingCountry               US           NaN

False

              Column                Orig Val                  New Val
0           entityId             20021028218              20021028218
1  principalAddress1  33050 Vista Ridge Driv  33050 Vista Ridge Drive

False

                   Column           Orig Val                New Val
0                entityId        20021058026            20021058026
1       principalAddress1  1235 Pearl Street          1235 Pearl St
2  agentPrincipalAddress1  921 Walnut Street  921 Walnut St Ste 200
3  agentPrincipalAddress2          Suite 200                    NaN

False

                   Column                     Orig Val                New Val
0                entityId                  20021063920            20021063920
1       principalAddress1               11 MADISON AVE      11 MADISON AVENUE
2       principalAddress2                CORP TAX DEPT                    NaN
3  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd
4    agentMailingAddress1                CORP TAX DEPT                    NaN
5    agentMailingAddress2               11 MADISON AVE                    NaN
6        agentMailingCity                     New York                    NaN
7       agentMailingState                           CO                    NaN
8     agentMailingZipCode                        10010                    NaN
9     agentMailingCountry                           US                    NaN

False

                 Column                    Orig Val                   New Val
0              entityId                 20021065540               20021065540
1     principalAddress1  One Procter & Gamble Plaza  1 Procter and Gamble Plz
2     principalAddress2           ATTN TAX DIVISION         Attn Tax Division
3       mailingAddress1                P.O. Box 599                PO Box 599
4  agentMailingAddress1  1 Procter and Gamble Plaza                       NaN
5  agentMailingAddress2                    Tax C-10                       NaN
6      agentMailingCity                  Cincinnati                       NaN
7     agentMailingState                          CO                       NaN
8   agentMailingZipCode                       45202                       NaN
9   agentMailingCountry                          US                       NaN

False

                 Column                  Orig Val       New Val
0              entityId               20021105780  2.002111e+10
1  agentMailingAddress1  4385 Carriage House View           NaN
2      agentMailingCity          Colorado Springs           NaN
3     agentMailingState                        CO           NaN
4   agentMailingZipCode                     80906           NaN
5   agentMailingCountry                        US           NaN

False

                 Column                            Orig Val       New Val
0              entityId                         20021153986  2.002115e+10
1  agentMailingAddress1                         PO BOX 2128           NaN
2  agentMailingAddress2  P.O. DRAWER 2128, MAIL DROP 061-04           NaN
3      agentMailingCity                              Dalton           NaN
4     agentMailingState                                  CO           NaN
5   agentMailingZipCode                               30722           NaN
6   agentMailingCountry                                  US           NaN

False

,Column,Orig Val,New Val
0,entityId,20021154821,20021154821
1,principalAddress1,C/o Three Mile Creek B B & B Ltd,519 Easy St
2,principalAddress2,678 County Road 127,C/O Three Mile Creek B B & B Ltd
3,agentPrincipalAddress1,678 County Road 127,519 Easy St
4,agentPrincipalAddress2,NaN,C/O Three Mile Creek B B & B Ltd
5,agentMailingAddress1,678 County Rd 127,NaN
6,agentMailingCity,Glenwood Springs,NaN
7,agentMailingState,CO,NaN
8,agentMailingZipCode,80601,NaN
9,agentMailingCountry,US,NaN

False

                  Column               Orig Val             New Val
0               entityId            20021155530         20021155530
1      principalAddress1  320 GRANITE RUN DRIVE  320 Granite Run Dr
2        mailingAddress1     320 GRANITE RUN DR  320 Granite Run Dr
3         mailingZipCode                  17604               17601
4  agentPrincipalZipCode             80112-1268               80112

False

                   Column                   Orig Val                 New Val
0                entityId                20021167849             20021167849
1       principalAddress1  599 Topeka Way, Suite 301  599 Topeka Way Ste 301
2  agentPrincipalAddress1  599 Topeka Way, Suite 301  599 Topeka Way Ste 301

False

              Column                   Orig Val        New Val
0           entityId                20021289782    20021289782
1  principalAddress1  104 Esplanade Ave Apt 130  2756 41st Ave
2      principalCity                   Pacifica  San Francisco
3   principalZipCode                      94044          94116
4    mailingAddress1                        NaN  2756 41st Ave
5        mailingCity                        NaN  San Francisco
6       mailingState                        NaN             CA
7     mailingZipCode                        NaN          94116
8     mailingCountry                        NaN             US

False

                   Column                     Orig Val                New Val
0                entityId                  20021325924            20021325924
1         mailingAddress1                P. O. BOX 988             PO Box 988
2  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd

False

                    Column             Orig Val             New Val
0                 entityId          20031012739         20031012739
1        principalAddress1  7658 Youngfield St.  7658 Youngfield St
2          mailingAddress1   7658 Youngfield St                 NaN
3              mailingCity               Arvada                 NaN
4             mailingState                   CO                 NaN
5           mailingZipCode                80005                 NaN
6           mailingCountry                   US                 NaN
7   agentPrincipalAddress1   7658 YOUNGFIELD ST  7658 Youngfield St
8       agentPrincipalCity               ARVADA              Arvada
9     agentMailingAddress1   7658 YOUNGFIELD ST                 NaN
10        agentMailingCity               Arvada                 NaN
11       agentMailingState                   CO                 NaN
12     agentMailingZipCode                80005                 NaN
13     agentMailingCountry                   US                 NaN

False

                    Column             Orig Val                     New Val
0                 entityId          20031020350                 20031020350
1           agentFirstName                  Jon                         NaN
2            agentLastName               Labrum                         NaN
3    agentOrganizationName                  NaN      C T Corporation System
4   agentPrincipalAddress1  2536 Rimrock Avenue  7700 E ARAPAHOE RD STE 220
5   agentPrincipalAddress2        Suite 400-387                         NaN
6       agentPrincipalCity       Grand Junction                  CENTENNIAL
7    agentPrincipalZipCode                81505                  80112-1268
8     agentMailingAddress1  2536 Rimrock Avenue                         NaN
9     agentMailingAddress2        Suite 400-387                         NaN
10        agentMailingCity       Grand Junction                         NaN
11       agentMailingState                   CO                         NaN
12     agentMailingZipCode                81505                         NaN
13     agentMailingCountry                   US                         NaN

False

,Column,Orig Val,New Val
0,entityId,20031092036,20031092036
1,principalAddress1,7200 Wisconsin Avenue,7200 Wisconsin Ave Ste 720
2,principalAddress2,Suite 720,NaN
3,agentPrincipalAddress1,1900 W. Littleton Boulevard,1900 W Littleton Blvd

False

                   Column                 Orig Val                   New Val
0                entityId              20031123675               20031123675
1       principalAddress1  650 South Cherry Street  650 S Cherry St Ste 1400
2       principalAddress2               Suite 1400                       NaN
3        principalZipCode               80246-1815                     80246
4  agentPrincipalAddress1  650 South Cherry Street  650 S Cherry St Ste 1400
5  agentPrincipalAddress2               Suite 1400                       NaN
6   agentPrincipalZipCode               80246-1815                     80246
7    agentMailingAddress1          650 S CHERRY ST  650 S Cherry St Ste 1400
8    agentMailingAddress2                 STE 1400                       NaN
9        agentMailingCity                   DENVER                    Denver

False

                   Column           Orig Val             New Val
0                entityId        20031130636         20031130636
1  agentPrincipalAddress1  6835 S WEBSTER ST  6835 S. Webster St
2  agentPrincipalAddress2             UNIT G              Unit G
3      agentPrincipalCity          LITTLETON           Littleton

False

                   Column               Orig Val                    New Val
0                entityId            20031141464                20031141464
1  agentPrincipalAddress1  102 N. Cascade Avenue  102 N Cascade Ave Ste 550
2  agentPrincipalAddress2              SUITE 550                        NaN

False

                   Column      Orig Val      New Val
0                entityId   20031144360  20031144360
1       principalAddress1  2745 Rim Dr.  2745 Rim Dr
2         mailingAddress1  2745 Rim Dr.  2745 Rim Dr
3  agentPrincipalAddress1  2745 Rim Dr.  2745 Rim Dr
4    agentMailingAddress1  2745 Rim Dr.  2745 Rim Dr

False

                   Column                Orig Val             New Val
0                entityId             20031146351         20031146351
1       principalAddress1      1134 W ENCLAVE CIR  1134 W Enclave Cir
2  agentPrincipalAddress1      1134 W ENCLAVE CIR  1134 W Enclave Cir
3      agentPrincipalCity              LOUISVILLE          Louisville
4    agentMailingAddress1  1134 W. Enclave Circle                 NaN
5        agentMailingCity              Louisville                 NaN
6       agentMailingState                      CO                 NaN
7     agentMailingZipCode                   80027                 NaN
8     agentMailingCountry                      US                 NaN

False

                   Column          Orig Val         New Val
0                entityId       20031147417     20031147417
1         mailingAddress1  4197 Serenade Rd  7041 Cobalt Ct
2          mailingZipCode             80104           80108
3  agentPrincipalAddress1  4197 Serenade Rd  7041 Cobalt Ct
4   agentPrincipalZipCode             80104           80108

False

                    Column        Orig Val           New Val
0                 entityId     20031148576       20031148576
1        principalAddress1  806 8th Street  806 8th St Ste A
2        principalAddress2          Unit A               NaN
3          mailingAddress1  806 8th Street               NaN
4          mailingAddress2          UNIT A               NaN
5              mailingCity         Greeley               NaN
6             mailingState              CO               NaN
7           mailingZipCode           80631               NaN
8           mailingCountry              US               NaN
9   agentPrincipalAddress1  806 8th Street  806 8th St Ste A
10  agentPrincipalAddress2          Unit A               NaN
11      agentPrincipalCity         GREELEY           Greeley

False

                   Column        Orig Val           New Val
0                entityId     20031148577       20031148577
1       principalAddress1  806 8th Street  806 8th St Ste A
2       principalAddress2          Unit A               NaN
3  agentPrincipalAddress1  806 8th Street  806 8th St Ste A
4  agentPrincipalAddress2          Unit A               NaN
5      agentPrincipalCity         GREELEY           Greeley

False

            Column     Orig Val      New Val
0         entityId  20031152220  20031152220
1  mailingAddress1  PO BOX  213   PO Box 213

False

,Column,Orig Val,New Val
0,entityId,20031155654,20031155654
1,entityName,ALAMEDA GREEN MOUNTAIN GIRLS SOFTBALL ASSOCIATION,ALAMEDA GREEN MOUNTAIN GIRLS SOFTBALL ASSOCIAT...
2,mailingAddress1,NaN,16671 W 74th Ave
3,mailingCity,NaN,Arvada
4,mailingState,NaN,CO
5,mailingZipCode,NaN,80007
6,mailingCountry,NaN,US
7,entityStatus,Good Standing,Voluntarily Dissolved

False

                   Column        Orig Val                 New Val
0                entityId     20031156459             20031156459
1       principalAddress1  19663 Hwy I-76  19663 I 76 Frontage Rd
2  agentPrincipalAddress1  19663 HWY I-76  19663 I 76 Frontage Rd
3      agentPrincipalCity          HUDSON                  Hudson

False

                   Column                     Orig Val                New Val
0                entityId                  20031158298            20031158298
1       principalAddress1         145 Enterprise Drive      145 Enterprise Dr
2  agentPrincipalAddress1  1900 W. Littleton Boulevard  1900 W Littleton Blvd

False

                    Column              Orig Val              New Val
0                 entityId           20031162894          20031162894
1        principalAddress1  104 Broadway, STE500  720 S Colorado Blvd
2        principalAddress2                   NaN             Ste 505S
3            principalCity                Denver             Glendale
4         principalZipCode                 80203                80246
5   agentPrincipalAddress1  104 Broadway, STE500  720 S Colorado Blvd
6   agentPrincipalAddress2                   NaN             Ste 505S
7       agentPrincipalCity                Denver             Glendale
8    agentPrincipalZipCode                 80203                80246
9     agentMailingAddress1                   NaN  720 S Colorado Blvd
10    agentMailingAddress2                   NaN             Ste 505S
11        agentMailingCity                   NaN             Glendale
12       agentMailingState                   NaN                   CO
13     agentMailingZipCode                   NaN                80246
14     agentMailingCountry                   NaN                   US

False

              Column                  Orig Val         New Val
0           entityId               20031169511     20031169511
1  principalAddress1  160 GREENTREE DR STE 101  1209 Orange St
2      principalCity                     Dover      Wilmington
3   principalZipCode                     19904           19801

False

                  Column         Orig Val      New Val
0               entityId      20031176168  20031176168
1       principalZipCode       80210-3101        80210
2  agentPrincipalZipCode       80210-3101        80210
3   agentMailingAddress1  1701 S Broadway          NaN
4       agentMailingCity           Denver          NaN
5      agentMailingState               CO          NaN
6    agentMailingZipCode       80210-3101          NaN
7    agentMailingCountry               US          NaN

False

,Column,Orig Val,New Val
0,entityId,20031205573,20031205573
1,entityName,ROCKY MOUNTAIN BEAN DEALERS ASSOCIATION,The Rocky Mountain Bean Dealers Association

False

,Column,Orig Val,New Val
0,entityId,20031207682,20031207682
1,entityName,"LOUISVILLE STORE & LOCK, INC., Delinquent May ...","LOUISVILLE STORE & LOCK, INC."
2,entityStatus,Delinquent,Good Standing

False

,Column,Orig Val,New Val
0,entityId,20031209201,20031209201
1,agentOrganizationName,Corporation Service Company,"REGISTERED AGENT SOLUTIONS, INC."
2,agentPrincipalAddress1,1900 W Littleton Blvd,36 SOUTH 18TH AVENUE
3,agentPrincipalAddress2,NaN,SUITE D
4,agentPrincipalCity,Littleton,BRIGHTON
5,agentPrincipalZipCode,80120,80601

False

                 Column        Orig Val                 New Val
0              entityId     20031211857             20031211857
1       mailingAddress1             NaN  19578 East 52nd Avenue
2           mailingCity             NaN                  Denver
3          mailingState             NaN                      CO
4        mailingZipCode             NaN                   80249
5        mailingCountry             NaN                      US
6    agentPrincipalCity          Denver                  DENVER
7  agentMailingAddress1  19578 E 52 Ave  19578 East 52nd Avenue
8      agentMailingCity          Denver                  DENVER

False

                   Column               Orig Val              New Val
0                entityId            20031213521          20031213521
1       principalAddress1  5361 S. Richfield Ct.  5361 S Richfield Ct
2  agentPrincipalAddress1  5361 S. Richfield Ct.  5361 S Richfield Ct

False

                   Column            Orig Val          New Val
0                entityId         20041117964      20041117964
1       principalAddress1  2505 Carson Avenue  2505 Carson Ave
2  agentPrincipalAddress1  2505 Carson Avenue  2505 Carson Ave
3    agentMailingAddress1          PO BOX 780              NaN
4    agentMailingAddress2        P.O. Box 780              NaN
5        agentMailingCity            La Junta              NaN
6       agentMailingState                  CO              NaN
7     agentMailingZipCode               81050              NaN
8     agentMailingCountry                  US              NaN

False

                   Column          Orig Val      New Val
0                entityId       20041138287  20041138287
1       principalAddress1   800 11th Street  800 11th St
2         mailingAddress1       800 11TH ST          NaN
3             mailingCity            Golden          NaN
4            mailingState                CO          NaN
5          mailingZipCode             80401          NaN
6          mailingCountry                US          NaN
7  agentPrincipalAddress1  3111 28th Street  800 11th St
8      agentPrincipalCity           Boulder       Golden
9   agentPrincipalZipCode             80301        80401

False

                 Column              Orig Val       New Val
0              entityId           20041149120  2.004115e+10
1  agentMailingAddress1  4854 Fountain Street           NaN
2      agentMailingCity               Boulder           NaN
3     agentMailingState                    CO           NaN
4   agentMailingZipCode                 80304           NaN
5   agentMailingCountry                    US           NaN

False

                 Column              Orig Val       New Val
0              entityId           20041150444  2.004115e+10
1  agentMailingAddress1  4854 Fountain Street           NaN
2      agentMailingCity               Boulder           NaN
3     agentMailingState                    CO           NaN
4   agentMailingZipCode                 80304           NaN
5   agentMailingCountry                    US           NaN

False

,Column,Orig Val,New Val
0,entityId,20041162579,20041162579
1,principalAddress1,200 Fillmore,200 Fillmore St Ste 400
2,principalAddress2,Suite 400,NaN
3,agentPrincipalAddress1,7700 E ARAPAHOE RD STE 220,7700 E Arapahoe Rd Ste 220
4,agentPrincipalCity,CENTENNIAL,Centennial
5,agentPrincipalZipCode,80112-1268,80112

False

                   Column             Orig Val              New Val
0                entityId          20041167890          20041167890
1       principalAddress1  18172 E ADRIATIC PL       28310 E 6th Pl
2           principalCity               Aurora              Catoosa
3          principalState                   CO                   OK
4        principalZipCode                80013                74015
5  agentPrincipalAddress1  18172 E ADRIATIC PL  18172 E Adriatic Pl
6      agentPrincipalCity               AURORA               Aurora

False

              Column              Orig Val             New Val
0           entityId           20041172053         20041172053
1  principalAddress1  601 Riverside Avenue  347 Riverside Ave,
2   principalZipCode                 32204               32202

False

                   Column            Orig Val          New Val
0                entityId         20041190334      20041190334
1       principalAddress1  1933 S.E. 14th St.  1933 14th St SE
2  agentPrincipalAddress1     1933 SE 14TH ST  1933 14th St SE
3    agentMailingAddress1    1933 S E 14th St              NaN
4        agentMailingCity            Loveland              NaN
5       agentMailingState                  CO              NaN
6     agentMailingZipCode               80537              NaN
7     agentMailingCountry                  US              NaN

False

                   Column           Orig Val                     New Val
0                entityId        20041196256                 20041196256
1       principalAddress1  7166 W Custer Ave  7166 W Custer Ave Unit 434
2       principalAddress2           Apt C434                         NaN
3         mailingAddress1  7166 W Custer Ave  7166 W Custer Ave Unit 434
4         mailingAddress2           Apt C434                         NaN
5  agentPrincipalAddress1  7166 W Custer Ave  7166 W Custer Ave Unit 434
6  agentPrincipalAddress2           Apt C434                         NaN
7    agentMailingAddress1  7166 W Custer Ave  7166 W Custer Ave Unit 434
8    agentMailingAddress2           Apt C434                         NaN

False

,Column,Orig Val,New Val
0,entityId,20041200006,20041200006
1,entityName,MONMOUTH REAL ESTATE INVESTMENT CORPORATION,"MONMOUTH REAL ESTATE INVESTMENT CORPORATION, C..."
2,principalAddress1,101 Crawfords Corner Road,Two Newton Place
3,principalAddress2,Suite 1405,255 Washington Street
4,principalCity,Holmdel,Newton
5,principalState,NJ,MA
6,principalZipCode,07733,02458
7,entityStatus,Good Standing,Withdrawn
8,agentOrganizationName,Corporation Service Company,NaN
9,agentPrincipalAddress1,1900 W. Littleton Boulevard,NaN
10,agentPrincipalCity,Littleton,NaN
11,agentPrincipalState,CO,NaN
12,agentPrincipalZipCode,80120,NaN
13,agentPrincipalCountry,US,NaN

False

            Column     Orig Val              New Val
0         entityId  20041216701          20041216701
1  mailingAddress1          NaN  2800 s syracuse way
2  mailingAddress2          NaN               15-101
3      mailingCity          NaN               Denver
4     mailingState          NaN                   CO
5   mailingZipCode          NaN                80231
6   mailingCountry          NaN                   US
7     entityStatus   Delinquent        Good Standing

False

              Column                   Orig Val          New Val
0           entityId                20041393088      20041393088
1  principalAddress1  720 SW Washington Ste 800  1705 SE 3rd Ave
2   principalZipCode                      97205            97214

False

                   Column             Orig Val           New Val
0                entityId          20041436469       20041436469
1       principalAddress1  850 Broadview Place  850 Broadview Pl
2         mailingAddress1        P.O. Box 3099       PO Box 6245
3  agentPrincipalAddress1  850 Broadview Place  850 Broadview Pl
4    agentMailingAddress1          PO Box 3099       PO Box 6245

False

           Column     Orig Val      New Val
0        entityId  20051038386  20051038386
1  agentFirstName      Matthew      Chelsea
2   agentLastName     Gallaher      Magness

False

                   Column               Orig Val             New Val
0                entityId            20051085099         20051085099
1       principalAddress1  21559 E Ottawa Circle  21559 E Ottawa Cir
2  agentPrincipalAddress1  21559 E Ottawa Circle  21559 E Ottawa Cir

False

,Column,Orig Val,New Val
0,entityId,20051103905,20051103905
1,principalAddress1,5801 W. 11th Street,5801 W 11th St Ste 201
2,principalAddress2,Suite 201,NaN
3,agentPrincipalAddress1,"5801 W. 11th Street, Suite 201",5801 W 11th St Ste 201

False

,Column,Orig Val,New Val
0,entityId,20051105279,20051105279
1,principalAddress1,2815 St. Andrews Loop,2815 Saint Andrews Loop Ste B
2,principalAddress2,Suite B,NaN
3,agentPrincipalAddress1,1900 W. Littleton Boulevard,1900 W Littleton Blvd

False

,Column,Orig Val,New Val
0,entityId,20051110590,20051110590
1,principalAddress1,780 Johnson Ferry Rd NE Suite 500,780 Johnson Ferry Rd Ste 500
2,agentPrincipalZipCode,80112-1268,80112

False

                  Column     Orig Val      New Val
0               entityId  20051117887  20051117887
1       principalZipCode        43041        43040
2  agentPrincipalZipCode   80112-1268        80112

False

,Column,Orig Val,New Val
0,entityId,20051134967,20051134967
1,principalAddress1,"5655 S. YOSEMITE ST, STE 301",5655 S Yosemite St Ste 301
2,agentPrincipalAddress1,"5655 S YOSEMITE ST, STE 301",5655 S Yosemite St Ste 301
3,agentPrincipalCity,GREENWOOD VILLAGE,Greenwood Village

False

                   Column            Orig Val         New Val
0                entityId         20051136758     20051136758
1          agentFirstName             Leonard            Todd
2         agentMiddleName              Adrian               R
3           agentLastName            Verhoven           Spain
4  agentPrincipalAddress1  1085 Eaglestone Dr  66 Native Lane
5      agentPrincipalCity         Castle Rock      Grand Lake
6   agentPrincipalZipCode               80104           80447
7    agentMailingAddress1  1085 Eaglestone Dr     PO Box 1895
8        agentMailingCity         Castle Rock      Grand Lake
9     agentMailingZipCode               80104           80447

False

                 Column             Orig Val       New Val
0              entityId          20051177835  2.005118e+10
1  agentMailingAddress1  3285 FARMTRAIL ROAD           NaN
2      agentMailingCity                 YORK           NaN
3     agentMailingState                   CO           NaN
4   agentMailingZipCode                17406           NaN
5   agentMailingCountry                   US           NaN

False

              Column                     Orig Val       New Val
0           entityId                  20051180430   20051180430
1  principalAddress1  1211 Avenue of the Americas  195 Broadway
2   principalZipCode                        10036         10007

False

                    Column                   Orig Val             New Val
0                 entityId                20051182351         20051182351
1        principalAddress1       7099 S. Fillmore Ct.  7099 S Fillmore Ct
2          mailingAddress1       7099 S. Fillmore Ct.                 NaN
3              mailingCity                 Centennial                 NaN
4             mailingState                         CO                 NaN
5           mailingZipCode                      80122                 NaN
6           mailingCountry                         US                 NaN
7   agentPrincipalAddress1       7099 S. Fillmore Ct.  7099 S Fillmore Ct
8     agentMailingAddress1  7099 South Fillmore Court                 NaN
9         agentMailingCity                 Centennial                 NaN
10       agentMailingState                         CO                 NaN
11     agentMailingZipCode                      80122                 NaN
12     agentMailingCountry                         US                 NaN

False

                   Column               Orig Val             New Val
0                entityId            20051189376         20051189376
1       principalAddress1  10328 Severance Drive  10328 Severance Dr
2         mailingAddress1           P.O Box 4391         PO Box 4391
3  agentPrincipalAddress1  10328 Severance Drive  10328 Severance Dr
4    agentMailingAddress1  10328 Severance Drive         PO Box 4391

False

                 Column        Orig Val       New Val
0              entityId     20051202968  2.005120e+10
1  agentMailingAddress1  1820 Folsom St           NaN
2      agentMailingCity         Boulder           NaN
3     agentMailingState              CO           NaN
4   agentMailingZipCode           80302           NaN
5   agentMailingCountry              US           NaN

False

                   Column              Orig Val                New Val
0                entityId           20051203713            20051203713
1  agentPrincipalAddress1  22718 E PRENTICE AVE  22718 E PRENTICE  AVE

False

                   Column       Orig Val      New Val
0                entityId    20051205628  20051205628
1       principalAddress1  815 23rd Lane  815 23rd Ln
2  agentPrincipalAddress1  815 23rd Lane  815 23rd Ln
3    agentMailingAddress1  815 23rd Lane          NaN
4        agentMailingCity         Pueblo          NaN
5       agentMailingState             CO          NaN
6     agentMailingZipCode          81006          NaN
7     agentMailingCountry             US          NaN

False

                    Column              Orig Val                  New Val
0                 entityId           20051211479              20051211479
1        principalAddress1        4 Haystack Row  2180 S Ivanhoe St Ste 8
2            principalCity  Cherry Hills Village                   Denver
3         principalZipCode                 80113                    80222
4   agentPrincipalAddress1        4 Haystack Row  2180 S Ivanhoe St Ste 8
5       agentPrincipalCity  Cherry Hills Village                   Denver
6    agentPrincipalZipCode                 80113                    80222
7     agentMailingAddress1        4 Haystack Row                      NaN
8         agentMailingCity  Cherry Hills Village                      NaN
9        agentMailingState                    CO                      NaN
10     agentMailingZipCode                 80113                      NaN
11     agentMailingCountry                    US                      NaN

False

,Column,Orig Val,New Val
0,entityId,20051238088,20051238088
1,principalAddress1,13300 North MacArthur Boulevard,6608 N. Western Ave.
2,principalAddress2,NaN,#635
3,principalZipCode,73142-3021,73116
4,mailingAddress1,13300 North MacArthur Boulevard,NaN
5,mailingCity,Oklahoma City,NaN
6,mailingState,OK,NaN
7,mailingZipCode,73142-3021,NaN
8,mailingCountry,US,NaN
9,agentMailingAddress1,NaN,6608 N WESTERN AVE # 635
10,agentMailingCity,NaN,Oklahoma City
11,agentMailingState,NaN,CO
12,agentMailingZipCode,NaN,73116
13,agentMailingCountry,NaN,US

False

         Column     Orig Val        New Val
0      entityId  20181695299    20181695299
1  entityStatus   Delinquent  Good Standing

False

                   Column         Orig Val         New Val
0                entityId      20051306280     20051306280
1       principalAddress1  496 S. Broadway  496 S Broadway
2  agentPrincipalAddress1  496 S. Broadway  496 S Broadway
3    agentMailingAddress1              NaN  496 S Broadway
4        agentMailingCity              NaN          Denver
5       agentMailingState              NaN              CO
6     agentMailingZipCode              NaN           80209
7     agentMailingCountry              NaN              US

In [73]:
eids

               0
0    19871033282
1    19871037801
2    19871056751
3    19871063401
4    19871072644
..           ...
232  20051205628
233  20051211479
234  20051238088
235  20181695299
236  20051306280

[237 rows x 1 columns]