In [35]:

import pandas as pd

import calendar
from datetime import datetime
from datetime import timedelta
from cronsim import CronSim

from datetime import date

today = date.today()
import argparse
import json
import PySimpleGUI as sg

today = date.today()
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)  # Set to None for no limit
# Or set a specific width

In [13]:
crons = []
def find_all(a_str, sub):
    start = 0
    while True:
        start = a_str.find(sub, start)
        if start == -1: return
        yield start
        start += len(sub) # use start += 1 to find overlapping matches
         
with open("/home/joe/bic_etl/general/cron/cron_file","r") as fin:
    for line in fin:
        if line[0:1] != "#"  and len(line) > 5:
           #print(line0)
#           print(line)
           crons.append(line.rstrip())
        line0=line
print(f"{len(crons)} Cron Jobs Found")

crons_all = []
ncrons=0
descriptions = []
for line in crons:
    line = line.strip(" ")
    spl = line.split(" ")
    crn=""
#    print(line)
    mm = line.find("node")
    nj = line.find("java")
    npyth = line.find("python")
    nt = line.find("-t")
    np = line.find("-p")
    if (np > 0):
        a = list(find_all(line[np:],'\"'))
        # if len(a) > 0:
        #   p=line[np+a[0]:np+a[1]+1]
        # else:
        ss = line[np:].split()
        p=ss[1]
    elif mm > 0:
        pp = spl[6].split("/")
        p= pp[-1]
        display("NODE ",p)
        
        
    elif nj > 0:  # java line
        pp = spl[7].split("/")
        p= pp[-1]
        display("JAVA ",p)
       
    elif npyth > 0:  # java line
        pp = spl[10].split("/")
        p= pp[-1]
        display("PYTHON ",p)
       
    else:
            p=""
            display("Find Program")
            display(line)
        
    if (nt > 0):
        ngt = line.find(">>")
        a = list(find_all(line[nt:ngt],'\"'))
        if len(a) > 0:
          t=line[nt+a[0]:nt+a[1]+1]
        else:
          ss = line[nt:].split()
          t=ss[1]
    else:
        t=""
            

    for val in spl[:5]:
        crn+= f"{val} "
    crn = crn.rstrip()
    if spl[5] == "node":
        pg = spl[6]
    else:
        pg=""
    print("PROGRAM",p)
    if len(p) > 0:  #  There is a program listed
      
        pgs=pg.split("/")
       
    #    print(line)
        mo = 1
        yr=today.year
        mo=today.month
        dy=today.day
        
#        date = datetime.strptime(f"{yr}-{mo}-01","%Y-%m-%d")
        date = datetime.strptime(f"{yr}-{mo}-{dy}","%Y-%m-%d")
        print("DATE  ",date)
        
        try:
            it = CronSim(crn,date)
            tmp={}
            tmp["line"]=line
            tmp["desc"] = it.explain()
         #   print("ME ",yr,mo,it.explain())
            descriptions.append(tmp)
            a = next(it) 
            cdate = datetime.strptime(f"{a.year}-{a.month}-{a.day}","%Y-%m-%d")
            ndays = (cdate-date).days
            print("Days ",ndays,a)
            while  ndays < 32:
         #       print(a.month,a.day,a.hour,a.minute,a.hour+a.minute/60)
         #       print("DAY ",calendar.day_name[a.weekday()])
          #      print(f"start:{a}   end:{a+timedelta(days=1)}")
                d = dict(Day=calendar.day_name[a.weekday()],Cron=line,T=t,TM=f"{a.hour}:{a.minute}",Task=p,Details=t,Program=pg,Start=a,End=a+timedelta(days=1),Time=a.hour+a.minute/60)
           #     crons_all.append(d)
                cdate = datetime.strptime(f"{a.year}-{a.month}-{a.day}","%Y-%m-%d")
                print(f"DD {crn}  {a.year}-{a.month}-{a.day}-{a.hour}-{a.minute}")
                ndays = (cdate-date).days
                if ndays <= 31:
                     crons_all.append(d)
               # print(date,cdate,ndays)
            # print(f"pg: {pg} P:{p} T:{t}")    
                a = next(it)
            ncrons+=1 
        except Exception as err:
            print("Count not Process",crn)
            print(err)
            print(line)
    else:  # Not a node runnning a cim dataset... must be java or python
        print(line)
    #  print("--------")

print(f"{len(crons_all)}  Crons successfully mapped to time ranges")

'NODE '

'pull_and_setup.js'

'JAVA '

'DataSync-1.8.2.jar'

'PYTHON '

'metadata_updater.py'

'NODE '

'cleanup.js'

display(crons_all)

In [14]:
hist={}
for dct in crons_all:
    cron = dct['Cron']
    if cron not in hist:
       hist[cron]=[]
    hist[cron].append(dct)

In [ ]:
hist

In [15]:
mapping = {32: "Daily",30:"Daily",4:"Weekly",5:"Weekly",1:"Monthly"}
mapped={}
counts={}                                                          
for cron,vals in hist.items():
    count=len(vals)
    if count > 30:
        print(count,cron)
    try:
        mapped[cron]=mapping[count]
        if count not in counts:
            counts[count]=0
        counts[count]+=1
    except:
        print("Bad ",count)
        for v in vals:
            print(v['Start'])

In [16]:
for cron in crons_all:
    cron['Schedule'] = mapped[cron['Cron']]

In [17]:
crons_all

[{'Day': 'Monday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 9, 2, 50),
  'End': datetime.datetime(2024, 12, 10, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Tuesday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 10, 2, 50),
  'End': datetime.datetime(2024, 12, 11, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Wednesday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 11, 2, 50),
  'End': datetime.datetime(2024, 12, 12, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Thursday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 12, 2, 50),
  'End': datetime.datetime(2024, 12, 13, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Friday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 13, 2, 50),
  'End': datetime.datetime(2024, 12, 14, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Saturday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 14, 2, 50),
  'End': datetime.datetime(2024, 12, 15, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Sunday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 15, 2, 50),
  'End': datetime.datetime(2024, 12, 16, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Monday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 16, 2, 50),
  'End': datetime.datetime(2024, 12, 17, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Tuesday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 17, 2, 50),
  'End': datetime.datetime(2024, 12, 18, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Wednesday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 18, 2, 50),
  'End': datetime.datetime(2024, 12, 19, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Thursday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 19, 2, 50),
  'End': datetime.datetime(2024, 12, 20, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Friday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 20, 2, 50),
  'End': datetime.datetime(2024, 12, 21, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Saturday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 21, 2, 50),
  'End': datetime.datetime(2024, 12, 22, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Sunday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 22, 2, 50),
  'End': datetime.datetime(2024, 12, 23, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Monday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 23, 2, 50),
  'End': datetime.datetime(2024, 12, 24, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Tuesday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 24, 2, 50),
  'End': datetime.datetime(2024, 12, 25, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Wednesday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 25, 2, 50),
  'End': datetime.datetime(2024, 12, 26, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Thursday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 26, 2, 50),
  'End': datetime.datetime(2024, 12, 27, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Friday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 27, 2, 50),
  'End': datetime.datetime(2024, 12, 28, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Saturday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 28, 2, 50),
  'End': datetime.datetime(2024, 12, 29, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Sunday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 29, 2, 50),
  'End': datetime.datetime(2024, 12, 30, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Monday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 30, 2, 50),
  'End': datetime.datetime(2024, 12, 31, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Tuesday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2024, 12, 31, 2, 50),
  'End': datetime.datetime(2025, 1, 1, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Wednesday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2025, 1, 1, 2, 50),
  'End': datetime.datetime(2025, 1, 2, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Thursday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2025, 1, 2, 2, 50),
  'End': datetime.datetime(2025, 1, 3, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Friday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2025, 1, 3, 2, 50),
  'End': datetime.datetime(2025, 1, 4, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Saturday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2025, 1, 4, 2, 50),
  'End': datetime.datetime(2025, 1, 5, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Sunday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2025, 1, 5, 2, 50),
  'End': datetime.datetime(2025, 1, 6, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Monday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2025, 1, 6, 2, 50),
  'End': datetime.datetime(2025, 1, 7, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Tuesday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2025, 1, 7, 2, 50),
  'End': datetime.datetime(2025, 1, 8, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Wednesday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2025, 1, 8, 2, 50),
  'End': datetime.datetime(2025, 1, 9, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Thursday',
  'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': '',
  'TM': '2:50',
  'Task': 'pull_and_setup.js',
  'Details': '',
  'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
  'Start': datetime.datetime(2025, 1, 9, 2, 50),
  'End': datetime.datetime(2025, 1, 10, 2, 50),
  'Time': 2.8333333333333335,
  'Schedule': 'Daily'},
 {'Day': 'Monday',
  'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': 'LoadPreferences',
  'TM': '2:58',
  'Task': 'DataSync-1.8.2.jar',
  'Details': 'LoadPreferences',
  'Program': '',
  'Start': datetime.datetime(2024, 12, 9, 2, 58),
  'End': datetime.datetime(2024, 12, 10, 2, 58),
  'Time': 2.966666666666667,
  'Schedule': 'Daily'},
 {'Day': 'Tuesday',
  'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': 'LoadPreferences',
  'TM': '2:58',
  'Task': 'DataSync-1.8.2.jar',
  'Details': 'LoadPreferences',
  'Program': '',
  'Start': datetime.datetime(2024, 12, 10, 2, 58),
  'End': datetime.datetime(2024, 12, 11, 2, 58),
  'Time': 2.966666666666667,
  'Schedule': 'Daily'},
 {'Day': 'Wednesday',
  'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': 'LoadPreferences',
  'TM': '2:58',
  'Task': 'DataSync-1.8.2.jar',
  'Details': 'LoadPreferences',
  'Program': '',
  'Start': datetime.datetime(2024, 12, 11, 2, 58),
  'End': datetime.datetime(2024, 12, 12, 2, 58),
  'Time': 2.966666666666667,
  'Schedule': 'Daily'},
 {'Day': 'Thursday',
  'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': 'LoadPreferences',
  'TM': '2:58',
  'Task': 'DataSync-1.8.2.jar',
  'Details': 'LoadPreferences',
  'Program': '',
  'Start': datetime.datetime(2024, 12, 12, 2, 58),
  'End': datetime.datetime(2024, 12, 13, 2, 58),
  'Time': 2.966666666666667,
  'Schedule': 'Daily'},
 {'Day': 'Friday',
  'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': 'LoadPreferences',
  'TM': '2:58',
  'Task': 'DataSync-1.8.2.jar',
  'Details': 'LoadPreferences',
  'Program': '',
  'Start': datetime.datetime(2024, 12, 13, 2, 58),
  'End': datetime.datetime(2024, 12, 14, 2, 58),
  'Time': 2.966666666666667,
  'Schedule': 'Daily'},
 {'Day': 'Saturday',
  'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': 'LoadPreferences',
  'TM': '2:58',
  'Task': 'DataSync-1.8.2.jar',
  'Details': 'LoadPreferences',
  'Program': '',
  'Start': datetime.datetime(2024, 12, 14, 2, 58),
  'End': datetime.datetime(2024, 12, 15, 2, 58),
  'Time': 2.966666666666667,
  'Schedule': 'Daily'},
 {'Day': 'Sunday',
  'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': 'LoadPreferences',
  'TM': '2:58',
  'Task': 'DataSync-1.8.2.jar',
  'Details': 'LoadPreferences',
  'Program': '',
  'Start': datetime.datetime(2024, 12, 15, 2, 58),
  'End': datetime.datetime(2024, 12, 16, 2, 58),
  'Time': 2.966666666666667,
  'Schedule': 'Daily'},
 {'Day': 'Monday',
  'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': 'LoadPreferences',
  'TM': '2:58',
  'Task': 'DataSync-1.8.2.jar',
  'Details': 'LoadPreferences',
  'Program': '',
  'Start': datetime.datetime(2024, 12, 16, 2, 58),
  'End': datetime.datetime(2024, 12, 17, 2, 58),
  'Time': 2.966666666666667,
  'Schedule': 'Daily'},
 {'Day': 'Tuesday',
  'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': 'LoadPreferences',
  'TM': '2:58',
  'Task': 'DataSync-1.8.2.jar',
  'Details': 'LoadPreferences',
  'Program': '',
  'Start': datetime.datetime(2024, 12, 17, 2, 58),
  'End': datetime.datetime(2024, 12, 18, 2, 58),
  'Time': 2.966666666666667,
  'Schedule': 'Daily'},
 {'Day': 'Wednesday',
  'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  'T': 'LoadPreferences',
  'TM': '2:58',
  'Task': 'DataSync-1.8.2.jar',
  'Details': 'LoadPreferences',
  'Program': '',
  'Start': datetime.datetime(2024, 12, 18, 2, 58),
  'End': datetime.datetime(2024, 12, 19, 2, 58),
  'Time': 2.966666666666667,
  'Schedule': 'Daily'},
 {'Day': 'Thursday',

In [18]:
info=[]
done = {}
for cron in crons_all:
    c = cron['Cron']
    if c not in done:
        done[c]={}
    day = cron['Day']
    if day not in done[c]: 
        info.append([cron['Day'],cron['TM'],cron['Schedule'],cron['Task'],cron['T'],cron['Cron'],cron['Time']])
        done[c][day]=1

In [19]:
day = datetime.now().strftime('%A')
display(day)

def getDay(day):

    tod={}
    for cron in crons_all:
        display(cron)
        if cron['Day'] == day:
           tod[cron['Cron']]=1
          
    keys = ["node","PATH","/usr/bin"]
    tod2 = tod.copy()
    toRun = []
    for string in tod:
        hit=0
        for key in keys:
            if string.find(key) > -1:
                st = string.find(key)
                string=string[st:]
                ed = string.find("2>>")
                hit=1
                if ed > -1:
                    toRun.append(string[:ed])
                else:
                    print("ROH ROH ",string)
        if hit == 0:
            print(string)
       
    
    return toRun

toRun = getDay(day)

'Monday'

{'Day': 'Monday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 9, 2, 50),
 'End': datetime.datetime(2024, 12, 10, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 10, 2, 50),
 'End': datetime.datetime(2024, 12, 11, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 11, 2, 50),
 'End': datetime.datetime(2024, 12, 12, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 12, 2, 50),
 'End': datetime.datetime(2024, 12, 13, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 13, 2, 50),
 'End': datetime.datetime(2024, 12, 14, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 14, 2, 50),
 'End': datetime.datetime(2024, 12, 15, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 15, 2, 50),
 'End': datetime.datetime(2024, 12, 16, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 16, 2, 50),
 'End': datetime.datetime(2024, 12, 17, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 17, 2, 50),
 'End': datetime.datetime(2024, 12, 18, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 18, 2, 50),
 'End': datetime.datetime(2024, 12, 19, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 19, 2, 50),
 'End': datetime.datetime(2024, 12, 20, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 20, 2, 50),
 'End': datetime.datetime(2024, 12, 21, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 21, 2, 50),
 'End': datetime.datetime(2024, 12, 22, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 22, 2, 50),
 'End': datetime.datetime(2024, 12, 23, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 23, 2, 50),
 'End': datetime.datetime(2024, 12, 24, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 24, 2, 50),
 'End': datetime.datetime(2024, 12, 25, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 25, 2, 50),
 'End': datetime.datetime(2024, 12, 26, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 26, 2, 50),
 'End': datetime.datetime(2024, 12, 27, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 27, 2, 50),
 'End': datetime.datetime(2024, 12, 28, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 28, 2, 50),
 'End': datetime.datetime(2024, 12, 29, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 29, 2, 50),
 'End': datetime.datetime(2024, 12, 30, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 30, 2, 50),
 'End': datetime.datetime(2024, 12, 31, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2024, 12, 31, 2, 50),
 'End': datetime.datetime(2025, 1, 1, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2025, 1, 1, 2, 50),
 'End': datetime.datetime(2025, 1, 2, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2025, 1, 2, 2, 50),
 'End': datetime.datetime(2025, 1, 3, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2025, 1, 3, 2, 50),
 'End': datetime.datetime(2025, 1, 4, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2025, 1, 4, 2, 50),
 'End': datetime.datetime(2025, 1, 5, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2025, 1, 5, 2, 50),
 'End': datetime.datetime(2025, 1, 6, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2025, 1, 6, 2, 50),
 'End': datetime.datetime(2025, 1, 7, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2025, 1, 7, 2, 50),
 'End': datetime.datetime(2025, 1, 8, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2025, 1, 8, 2, 50),
 'End': datetime.datetime(2025, 1, 9, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '2:50',
 'Task': 'pull_and_setup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/pull_and_setup.js',
 'Start': datetime.datetime(2025, 1, 9, 2, 50),
 'End': datetime.datetime(2025, 1, 10, 2, 50),
 'Time': 2.8333333333333335,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 9, 2, 58),
 'End': datetime.datetime(2024, 12, 10, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 10, 2, 58),
 'End': datetime.datetime(2024, 12, 11, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 11, 2, 58),
 'End': datetime.datetime(2024, 12, 12, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 12, 2, 58),
 'End': datetime.datetime(2024, 12, 13, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 13, 2, 58),
 'End': datetime.datetime(2024, 12, 14, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 14, 2, 58),
 'End': datetime.datetime(2024, 12, 15, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 15, 2, 58),
 'End': datetime.datetime(2024, 12, 16, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 16, 2, 58),
 'End': datetime.datetime(2024, 12, 17, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 17, 2, 58),
 'End': datetime.datetime(2024, 12, 18, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 18, 2, 58),
 'End': datetime.datetime(2024, 12, 19, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 19, 2, 58),
 'End': datetime.datetime(2024, 12, 20, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 20, 2, 58),
 'End': datetime.datetime(2024, 12, 21, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 21, 2, 58),
 'End': datetime.datetime(2024, 12, 22, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 22, 2, 58),
 'End': datetime.datetime(2024, 12, 23, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 23, 2, 58),
 'End': datetime.datetime(2024, 12, 24, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 24, 2, 58),
 'End': datetime.datetime(2024, 12, 25, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 25, 2, 58),
 'End': datetime.datetime(2024, 12, 26, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 26, 2, 58),
 'End': datetime.datetime(2024, 12, 27, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 27, 2, 58),
 'End': datetime.datetime(2024, 12, 28, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 28, 2, 58),
 'End': datetime.datetime(2024, 12, 29, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 29, 2, 58),
 'End': datetime.datetime(2024, 12, 30, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 30, 2, 58),
 'End': datetime.datetime(2024, 12, 31, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 31, 2, 58),
 'End': datetime.datetime(2025, 1, 1, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 1, 2, 58),
 'End': datetime.datetime(2025, 1, 2, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 2, 2, 58),
 'End': datetime.datetime(2025, 1, 3, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 3, 2, 58),
 'End': datetime.datetime(2025, 1, 4, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 4, 2, 58),
 'End': datetime.datetime(2025, 1, 5, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 5, 2, 58),
 'End': datetime.datetime(2025, 1, 6, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 6, 2, 58),
 'End': datetime.datetime(2025, 1, 7, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 7, 2, 58),
 'End': datetime.datetime(2025, 1, 8, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 8, 2, 58),
 'End': datetime.datetime(2025, 1, 9, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': 'LoadPreferences',
 'TM': '2:58',
 'Task': 'DataSync-1.8.2.jar',
 'Details': 'LoadPreferences',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 9, 2, 58),
 'End': datetime.datetime(2025, 1, 10, 2, 58),
 'Time': 2.966666666666667,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 9, 5, 0),
 'End': datetime.datetime(2024, 12, 10, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 10, 5, 0),
 'End': datetime.datetime(2024, 12, 11, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 11, 5, 0),
 'End': datetime.datetime(2024, 12, 12, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 12, 5, 0),
 'End': datetime.datetime(2024, 12, 13, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 13, 5, 0),
 'End': datetime.datetime(2024, 12, 14, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 14, 5, 0),
 'End': datetime.datetime(2024, 12, 15, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 15, 5, 0),
 'End': datetime.datetime(2024, 12, 16, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 16, 5, 0),
 'End': datetime.datetime(2024, 12, 17, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 17, 5, 0),
 'End': datetime.datetime(2024, 12, 18, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 18, 5, 0),
 'End': datetime.datetime(2024, 12, 19, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 19, 5, 0),
 'End': datetime.datetime(2024, 12, 20, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 20, 5, 0),
 'End': datetime.datetime(2024, 12, 21, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 21, 5, 0),
 'End': datetime.datetime(2024, 12, 22, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 22, 5, 0),
 'End': datetime.datetime(2024, 12, 23, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 23, 5, 0),
 'End': datetime.datetime(2024, 12, 24, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 24, 5, 0),
 'End': datetime.datetime(2024, 12, 25, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 25, 5, 0),
 'End': datetime.datetime(2024, 12, 26, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 26, 5, 0),
 'End': datetime.datetime(2024, 12, 27, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 27, 5, 0),
 'End': datetime.datetime(2024, 12, 28, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 28, 5, 0),
 'End': datetime.datetime(2024, 12, 29, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 29, 5, 0),
 'End': datetime.datetime(2024, 12, 30, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 30, 5, 0),
 'End': datetime.datetime(2024, 12, 31, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2024, 12, 31, 5, 0),
 'End': datetime.datetime(2025, 1, 1, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 1, 5, 0),
 'End': datetime.datetime(2025, 1, 2, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 2, 5, 0),
 'End': datetime.datetime(2025, 1, 3, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 3, 5, 0),
 'End': datetime.datetime(2025, 1, 4, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 4, 5, 0),
 'End': datetime.datetime(2025, 1, 5, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 5, 5, 0),
 'End': datetime.datetime(2025, 1, 6, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 6, 5, 0),
 'End': datetime.datetime(2025, 1, 7, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 7, 5, 0),
 'End': datetime.datetime(2025, 1, 8, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 8, 5, 0),
 'End': datetime.datetime(2025, 1, 9, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:0',
 'Task': 'metadata_updater.py',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 9, 5, 0),
 'End': datetime.datetime(2025, 1, 10, 5, 0),
 'Time': 5.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 9, 3, 10),
 'End': datetime.datetime(2024, 12, 10, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 10, 3, 10),
 'End': datetime.datetime(2024, 12, 11, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 11, 3, 10),
 'End': datetime.datetime(2024, 12, 12, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 12, 3, 10),
 'End': datetime.datetime(2024, 12, 13, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 13, 3, 10),
 'End': datetime.datetime(2024, 12, 14, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 14, 3, 10),
 'End': datetime.datetime(2024, 12, 15, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 15, 3, 10),
 'End': datetime.datetime(2024, 12, 16, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 16, 3, 10),
 'End': datetime.datetime(2024, 12, 17, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 17, 3, 10),
 'End': datetime.datetime(2024, 12, 18, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 18, 3, 10),
 'End': datetime.datetime(2024, 12, 19, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 19, 3, 10),
 'End': datetime.datetime(2024, 12, 20, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 20, 3, 10),
 'End': datetime.datetime(2024, 12, 21, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 21, 3, 10),
 'End': datetime.datetime(2024, 12, 22, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 22, 3, 10),
 'End': datetime.datetime(2024, 12, 23, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 23, 3, 10),
 'End': datetime.datetime(2024, 12, 24, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 24, 3, 10),
 'End': datetime.datetime(2024, 12, 25, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 25, 3, 10),
 'End': datetime.datetime(2024, 12, 26, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 26, 3, 10),
 'End': datetime.datetime(2024, 12, 27, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 27, 3, 10),
 'End': datetime.datetime(2024, 12, 28, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 28, 3, 10),
 'End': datetime.datetime(2024, 12, 29, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 29, 3, 10),
 'End': datetime.datetime(2024, 12, 30, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 30, 3, 10),
 'End': datetime.datetime(2024, 12, 31, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 31, 3, 10),
 'End': datetime.datetime(2025, 1, 1, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 1, 3, 10),
 'End': datetime.datetime(2025, 1, 2, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 2, 3, 10),
 'End': datetime.datetime(2025, 1, 3, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 3, 3, 10),
 'End': datetime.datetime(2025, 1, 4, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 4, 3, 10),
 'End': datetime.datetime(2025, 1, 5, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 5, 3, 10),
 'End': datetime.datetime(2025, 1, 6, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 6, 3, 10),
 'End': datetime.datetime(2025, 1, 7, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 7, 3, 10),
 'End': datetime.datetime(2025, 1, 8, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 8, 3, 10),
 'End': datetime.datetime(2025, 1, 9, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:10',
 'Task': 'boulder',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 9, 3, 10),
 'End': datetime.datetime(2025, 1, 10, 3, 10),
 'Time': 3.1666666666666665,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 9, 4, 0),
 'End': datetime.datetime(2024, 12, 10, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 10, 4, 0),
 'End': datetime.datetime(2024, 12, 11, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 11, 4, 0),
 'End': datetime.datetime(2024, 12, 12, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 12, 4, 0),
 'End': datetime.datetime(2024, 12, 13, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 13, 4, 0),
 'End': datetime.datetime(2024, 12, 14, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 14, 4, 0),
 'End': datetime.datetime(2024, 12, 15, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 15, 4, 0),
 'End': datetime.datetime(2024, 12, 16, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 16, 4, 0),
 'End': datetime.datetime(2024, 12, 17, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 17, 4, 0),
 'End': datetime.datetime(2024, 12, 18, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 18, 4, 0),
 'End': datetime.datetime(2024, 12, 19, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 19, 4, 0),
 'End': datetime.datetime(2024, 12, 20, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 20, 4, 0),
 'End': datetime.datetime(2024, 12, 21, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 21, 4, 0),
 'End': datetime.datetime(2024, 12, 22, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 22, 4, 0),
 'End': datetime.datetime(2024, 12, 23, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 23, 4, 0),
 'End': datetime.datetime(2024, 12, 24, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 24, 4, 0),
 'End': datetime.datetime(2024, 12, 25, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 25, 4, 0),
 'End': datetime.datetime(2024, 12, 26, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 26, 4, 0),
 'End': datetime.datetime(2024, 12, 27, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 27, 4, 0),
 'End': datetime.datetime(2024, 12, 28, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 28, 4, 0),
 'End': datetime.datetime(2024, 12, 29, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 29, 4, 0),
 'End': datetime.datetime(2024, 12, 30, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 30, 4, 0),
 'End': datetime.datetime(2024, 12, 31, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 31, 4, 0),
 'End': datetime.datetime(2025, 1, 1, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 1, 4, 0),
 'End': datetime.datetime(2025, 1, 2, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 2, 4, 0),
 'End': datetime.datetime(2025, 1, 3, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 3, 4, 0),
 'End': datetime.datetime(2025, 1, 4, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 4, 4, 0),
 'End': datetime.datetime(2025, 1, 5, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 5, 4, 0),
 'End': datetime.datetime(2025, 1, 6, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 6, 4, 0),
 'End': datetime.datetime(2025, 1, 7, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 7, 4, 0),
 'End': datetime.datetime(2025, 1, 8, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 8, 4, 0),
 'End': datetime.datetime(2025, 1, 9, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'catalog',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 9, 4, 0),
 'End': datetime.datetime(2025, 1, 10, 4, 0),
 'Time': 4.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '5 6 * * 5 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '6:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 13, 6, 5),
 'End': datetime.datetime(2024, 12, 14, 6, 5),
 'Time': 6.083333333333333,
 'Schedule': 'Weekly'}

{'Day': 'Friday',
 'Cron': '5 6 * * 5 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '6:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 20, 6, 5),
 'End': datetime.datetime(2024, 12, 21, 6, 5),
 'Time': 6.083333333333333,
 'Schedule': 'Weekly'}

{'Day': 'Friday',
 'Cron': '5 6 * * 5 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '6:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 27, 6, 5),
 'End': datetime.datetime(2024, 12, 28, 6, 5),
 'Time': 6.083333333333333,
 'Schedule': 'Weekly'}

{'Day': 'Friday',
 'Cron': '5 6 * * 5 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '6:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 3, 6, 5),
 'End': datetime.datetime(2025, 1, 4, 6, 5),
 'Time': 6.083333333333333,
 'Schedule': 'Weekly'}

{'Day': 'Monday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 9, 5, 5),
 'End': datetime.datetime(2024, 12, 10, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 10, 5, 5),
 'End': datetime.datetime(2024, 12, 11, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 11, 5, 5),
 'End': datetime.datetime(2024, 12, 12, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 12, 5, 5),
 'End': datetime.datetime(2024, 12, 13, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 13, 5, 5),
 'End': datetime.datetime(2024, 12, 14, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 14, 5, 5),
 'End': datetime.datetime(2024, 12, 15, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 15, 5, 5),
 'End': datetime.datetime(2024, 12, 16, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 16, 5, 5),
 'End': datetime.datetime(2024, 12, 17, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 17, 5, 5),
 'End': datetime.datetime(2024, 12, 18, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 18, 5, 5),
 'End': datetime.datetime(2024, 12, 19, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 19, 5, 5),
 'End': datetime.datetime(2024, 12, 20, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 20, 5, 5),
 'End': datetime.datetime(2024, 12, 21, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 21, 5, 5),
 'End': datetime.datetime(2024, 12, 22, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 22, 5, 5),
 'End': datetime.datetime(2024, 12, 23, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 23, 5, 5),
 'End': datetime.datetime(2024, 12, 24, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 24, 5, 5),
 'End': datetime.datetime(2024, 12, 25, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 25, 5, 5),
 'End': datetime.datetime(2024, 12, 26, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 26, 5, 5),
 'End': datetime.datetime(2024, 12, 27, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 27, 5, 5),
 'End': datetime.datetime(2024, 12, 28, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 28, 5, 5),
 'End': datetime.datetime(2024, 12, 29, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 29, 5, 5),
 'End': datetime.datetime(2024, 12, 30, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 30, 5, 5),
 'End': datetime.datetime(2024, 12, 31, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 31, 5, 5),
 'End': datetime.datetime(2025, 1, 1, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 1, 5, 5),
 'End': datetime.datetime(2025, 1, 2, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 2, 5, 5),
 'End': datetime.datetime(2025, 1, 3, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 3, 5, 5),
 'End': datetime.datetime(2025, 1, 4, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 4, 5, 5),
 'End': datetime.datetime(2025, 1, 5, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 5, 5, 5),
 'End': datetime.datetime(2025, 1, 6, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 6, 5, 5),
 'End': datetime.datetime(2025, 1, 7, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 7, 5, 5),
 'End': datetime.datetime(2025, 1, 8, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 8, 5, 5),
 'End': datetime.datetime(2025, 1, 9, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'TM': '5:5',
 'Task': 'cdos/business/nonprofit',
 'Details': '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 9, 5, 5),
 'End': datetime.datetime(2025, 1, 10, 5, 5),
 'Time': 5.083333333333333,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 9, 5, 10),
 'End': datetime.datetime(2024, 12, 10, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 10, 5, 10),
 'End': datetime.datetime(2024, 12, 11, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 11, 5, 10),
 'End': datetime.datetime(2024, 12, 12, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 12, 5, 10),
 'End': datetime.datetime(2024, 12, 13, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 13, 5, 10),
 'End': datetime.datetime(2024, 12, 14, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 14, 5, 10),
 'End': datetime.datetime(2024, 12, 15, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 15, 5, 10),
 'End': datetime.datetime(2024, 12, 16, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 16, 5, 10),
 'End': datetime.datetime(2024, 12, 17, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 17, 5, 10),
 'End': datetime.datetime(2024, 12, 18, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 18, 5, 10),
 'End': datetime.datetime(2024, 12, 19, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 19, 5, 10),
 'End': datetime.datetime(2024, 12, 20, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 20, 5, 10),
 'End': datetime.datetime(2024, 12, 21, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 21, 5, 10),
 'End': datetime.datetime(2024, 12, 22, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 22, 5, 10),
 'End': datetime.datetime(2024, 12, 23, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 23, 5, 10),
 'End': datetime.datetime(2024, 12, 24, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 24, 5, 10),
 'End': datetime.datetime(2024, 12, 25, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 25, 5, 10),
 'End': datetime.datetime(2024, 12, 26, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 26, 5, 10),
 'End': datetime.datetime(2024, 12, 27, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 27, 5, 10),
 'End': datetime.datetime(2024, 12, 28, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 28, 5, 10),
 'End': datetime.datetime(2024, 12, 29, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 29, 5, 10),
 'End': datetime.datetime(2024, 12, 30, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 30, 5, 10),
 'End': datetime.datetime(2024, 12, 31, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 31, 5, 10),
 'End': datetime.datetime(2025, 1, 1, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 1, 5, 10),
 'End': datetime.datetime(2025, 1, 2, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 2, 5, 10),
 'End': datetime.datetime(2025, 1, 3, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 3, 5, 10),
 'End': datetime.datetime(2025, 1, 4, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 4, 5, 10),
 'End': datetime.datetime(2025, 1, 5, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 5, 5, 10),
 'End': datetime.datetime(2025, 1, 6, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 6, 5, 10),
 'End': datetime.datetime(2025, 1, 7, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 7, 5, 10),
 'End': datetime.datetime(2025, 1, 8, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 8, 5, 10),
 'End': datetime.datetime(2025, 1, 9, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entities in Colorado"',
 'TM': '5:10',
 'Task': 'cdos/business/business',
 'Details': '"Business Entities in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 9, 5, 10),
 'End': datetime.datetime(2025, 1, 10, 5, 10),
 'Time': 5.166666666666667,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 9, 8, 0),
 'End': datetime.datetime(2024, 12, 10, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 10, 8, 0),
 'End': datetime.datetime(2024, 12, 11, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 11, 8, 0),
 'End': datetime.datetime(2024, 12, 12, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 12, 8, 0),
 'End': datetime.datetime(2024, 12, 13, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 13, 8, 0),
 'End': datetime.datetime(2024, 12, 14, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 14, 8, 0),
 'End': datetime.datetime(2024, 12, 15, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 15, 8, 0),
 'End': datetime.datetime(2024, 12, 16, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 16, 8, 0),
 'End': datetime.datetime(2024, 12, 17, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 17, 8, 0),
 'End': datetime.datetime(2024, 12, 18, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 18, 8, 0),
 'End': datetime.datetime(2024, 12, 19, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 19, 8, 0),
 'End': datetime.datetime(2024, 12, 20, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 20, 8, 0),
 'End': datetime.datetime(2024, 12, 21, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 21, 8, 0),
 'End': datetime.datetime(2024, 12, 22, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 22, 8, 0),
 'End': datetime.datetime(2024, 12, 23, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 23, 8, 0),
 'End': datetime.datetime(2024, 12, 24, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 24, 8, 0),
 'End': datetime.datetime(2024, 12, 25, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 25, 8, 0),
 'End': datetime.datetime(2024, 12, 26, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 26, 8, 0),
 'End': datetime.datetime(2024, 12, 27, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 27, 8, 0),
 'End': datetime.datetime(2024, 12, 28, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 28, 8, 0),
 'End': datetime.datetime(2024, 12, 29, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 29, 8, 0),
 'End': datetime.datetime(2024, 12, 30, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 30, 8, 0),
 'End': datetime.datetime(2024, 12, 31, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 31, 8, 0),
 'End': datetime.datetime(2025, 1, 1, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 1, 8, 0),
 'End': datetime.datetime(2025, 1, 2, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 2, 8, 0),
 'End': datetime.datetime(2025, 1, 3, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 3, 8, 0),
 'End': datetime.datetime(2025, 1, 4, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 4, 8, 0),
 'End': datetime.datetime(2025, 1, 5, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 5, 8, 0),
 'End': datetime.datetime(2025, 1, 6, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 6, 8, 0),
 'End': datetime.datetime(2025, 1, 7, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 7, 8, 0),
 'End': datetime.datetime(2025, 1, 8, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 8, 8, 0),
 'End': datetime.datetime(2025, 1, 9, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Business Entity Transaction History"',
 'TM': '8:0',
 'Task': 'cdos/business/business',
 'Details': '"Business Entity Transaction History"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 9, 8, 0),
 'End': datetime.datetime(2025, 1, 10, 8, 0),
 'Time': 8.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/health 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'cdos/health',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 10, 4, 0),
 'End': datetime.datetime(2024, 12, 11, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/health 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'cdos/health',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 17, 4, 0),
 'End': datetime.datetime(2024, 12, 18, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/health 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'cdos/health',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 24, 4, 0),
 'End': datetime.datetime(2024, 12, 25, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/health 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'cdos/health',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 31, 4, 0),
 'End': datetime.datetime(2025, 1, 1, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/health 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'cdos/health',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 7, 4, 0),
 'End': datetime.datetime(2025, 1, 8, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Monday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 9, 4, 15),
 'End': datetime.datetime(2024, 12, 10, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 10, 4, 15),
 'End': datetime.datetime(2024, 12, 11, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 11, 4, 15),
 'End': datetime.datetime(2024, 12, 12, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 12, 4, 15),
 'End': datetime.datetime(2024, 12, 13, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 13, 4, 15),
 'End': datetime.datetime(2024, 12, 14, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 14, 4, 15),
 'End': datetime.datetime(2024, 12, 15, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 15, 4, 15),
 'End': datetime.datetime(2024, 12, 16, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 16, 4, 15),
 'End': datetime.datetime(2024, 12, 17, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 17, 4, 15),
 'End': datetime.datetime(2024, 12, 18, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 18, 4, 15),
 'End': datetime.datetime(2024, 12, 19, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 19, 4, 15),
 'End': datetime.datetime(2024, 12, 20, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 20, 4, 15),
 'End': datetime.datetime(2024, 12, 21, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 21, 4, 15),
 'End': datetime.datetime(2024, 12, 22, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 22, 4, 15),
 'End': datetime.datetime(2024, 12, 23, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 23, 4, 15),
 'End': datetime.datetime(2024, 12, 24, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 24, 4, 15),
 'End': datetime.datetime(2024, 12, 25, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 25, 4, 15),
 'End': datetime.datetime(2024, 12, 26, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 26, 4, 15),
 'End': datetime.datetime(2024, 12, 27, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 27, 4, 15),
 'End': datetime.datetime(2024, 12, 28, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 28, 4, 15),
 'End': datetime.datetime(2024, 12, 29, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 29, 4, 15),
 'End': datetime.datetime(2024, 12, 30, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 30, 4, 15),
 'End': datetime.datetime(2024, 12, 31, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 31, 4, 15),
 'End': datetime.datetime(2025, 1, 1, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 1, 4, 15),
 'End': datetime.datetime(2025, 1, 2, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 2, 4, 15),
 'End': datetime.datetime(2025, 1, 3, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 3, 4, 15),
 'End': datetime.datetime(2025, 1, 4, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 4, 4, 15),
 'End': datetime.datetime(2025, 1, 5, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 5, 4, 15),
 'End': datetime.datetime(2025, 1, 6, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 6, 4, 15),
 'End': datetime.datetime(2025, 1, 7, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 7, 4, 15),
 'End': datetime.datetime(2025, 1, 8, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 8, 4, 15),
 'End': datetime.datetime(2025, 1, 9, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:15',
 'Task': 'cdos/lobbyist',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 9, 4, 15),
 'End': datetime.datetime(2025, 1, 10, 4, 15),
 'Time': 4.25,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '30 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/government 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:30',
 'Task': 'cdos/government',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 10, 4, 30),
 'End': datetime.datetime(2024, 12, 11, 4, 30),
 'Time': 4.5,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '30 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/government 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:30',
 'Task': 'cdos/government',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 17, 4, 30),
 'End': datetime.datetime(2024, 12, 18, 4, 30),
 'Time': 4.5,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '30 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/government 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:30',
 'Task': 'cdos/government',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 24, 4, 30),
 'End': datetime.datetime(2024, 12, 25, 4, 30),
 'Time': 4.5,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '30 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/government 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:30',
 'Task': 'cdos/government',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 31, 4, 30),
 'End': datetime.datetime(2025, 1, 1, 4, 30),
 'Time': 4.5,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '30 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/government 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:30',
 'Task': 'cdos/government',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 7, 4, 30),
 'End': datetime.datetime(2025, 1, 8, 4, 30),
 'Time': 4.5,
 'Schedule': 'Weekly'}

{'Day': 'Saturday',
 'Cron': '30 5 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Master List in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Master List in Colorado"',
 'TM': '5:30',
 'Task': 'cdos/business/business',
 'Details': '"Master List in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 4, 5, 30),
 'End': datetime.datetime(2025, 1, 5, 5, 30),
 'Time': 5.5,
 'Schedule': 'Monthly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Trade Names for Businesses in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Trade Names for Businesses in Colorado"',
 'TM': '4:0',
 'Task': 'cdos/business/business',
 'Details': '"Trade Names for Businesses in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 10, 4, 0),
 'End': datetime.datetime(2024, 12, 11, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Trade Names for Businesses in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Trade Names for Businesses in Colorado"',
 'TM': '4:0',
 'Task': 'cdos/business/business',
 'Details': '"Trade Names for Businesses in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 17, 4, 0),
 'End': datetime.datetime(2024, 12, 18, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Trade Names for Businesses in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Trade Names for Businesses in Colorado"',
 'TM': '4:0',
 'Task': 'cdos/business/business',
 'Details': '"Trade Names for Businesses in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 24, 4, 0),
 'End': datetime.datetime(2024, 12, 25, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Trade Names for Businesses in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Trade Names for Businesses in Colorado"',
 'TM': '4:0',
 'Task': 'cdos/business/business',
 'Details': '"Trade Names for Businesses in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 31, 4, 0),
 'End': datetime.datetime(2025, 1, 1, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Trade Names for Businesses in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Trade Names for Businesses in Colorado"',
 'TM': '4:0',
 'Task': 'cdos/business/business',
 'Details': '"Trade Names for Businesses in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 7, 4, 0),
 'End': datetime.datetime(2025, 1, 8, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Trademarks for Businesses in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Trademarks for Businesses in Colorado"',
 'TM': '4:0',
 'Task': 'cdos/business/business',
 'Details': '"Trademarks for Businesses in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 10, 4, 0),
 'End': datetime.datetime(2024, 12, 11, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Trademarks for Businesses in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Trademarks for Businesses in Colorado"',
 'TM': '4:0',
 'Task': 'cdos/business/business',
 'Details': '"Trademarks for Businesses in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 17, 4, 0),
 'End': datetime.datetime(2024, 12, 18, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Trademarks for Businesses in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Trademarks for Businesses in Colorado"',
 'TM': '4:0',
 'Task': 'cdos/business/business',
 'Details': '"Trademarks for Businesses in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 24, 4, 0),
 'End': datetime.datetime(2024, 12, 25, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Trademarks for Businesses in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Trademarks for Businesses in Colorado"',
 'TM': '4:0',
 'Task': 'cdos/business/business',
 'Details': '"Trademarks for Businesses in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 31, 4, 0),
 'End': datetime.datetime(2025, 1, 1, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Trademarks for Businesses in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Trademarks for Businesses in Colorado"',
 'TM': '4:0',
 'Task': 'cdos/business/business',
 'Details': '"Trademarks for Businesses in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 7, 4, 0),
 'End': datetime.datetime(2025, 1, 8, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Monday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 9, 3, 0),
 'End': datetime.datetime(2024, 12, 10, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 10, 3, 0),
 'End': datetime.datetime(2024, 12, 11, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 11, 3, 0),
 'End': datetime.datetime(2024, 12, 12, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 12, 3, 0),
 'End': datetime.datetime(2024, 12, 13, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 13, 3, 0),
 'End': datetime.datetime(2024, 12, 14, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 14, 3, 0),
 'End': datetime.datetime(2024, 12, 15, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 15, 3, 0),
 'End': datetime.datetime(2024, 12, 16, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 16, 3, 0),
 'End': datetime.datetime(2024, 12, 17, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 17, 3, 0),
 'End': datetime.datetime(2024, 12, 18, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 18, 3, 0),
 'End': datetime.datetime(2024, 12, 19, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 19, 3, 0),
 'End': datetime.datetime(2024, 12, 20, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 20, 3, 0),
 'End': datetime.datetime(2024, 12, 21, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 21, 3, 0),
 'End': datetime.datetime(2024, 12, 22, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 22, 3, 0),
 'End': datetime.datetime(2024, 12, 23, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 23, 3, 0),
 'End': datetime.datetime(2024, 12, 24, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 24, 3, 0),
 'End': datetime.datetime(2024, 12, 25, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 25, 3, 0),
 'End': datetime.datetime(2024, 12, 26, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 26, 3, 0),
 'End': datetime.datetime(2024, 12, 27, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 27, 3, 0),
 'End': datetime.datetime(2024, 12, 28, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 28, 3, 0),
 'End': datetime.datetime(2024, 12, 29, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 29, 3, 0),
 'End': datetime.datetime(2024, 12, 30, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 30, 3, 0),
 'End': datetime.datetime(2024, 12, 31, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 31, 3, 0),
 'End': datetime.datetime(2025, 1, 1, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 1, 3, 0),
 'End': datetime.datetime(2025, 1, 2, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 2, 3, 0),
 'End': datetime.datetime(2025, 1, 3, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 3, 3, 0),
 'End': datetime.datetime(2025, 1, 4, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 4, 3, 0),
 'End': datetime.datetime(2025, 1, 5, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 5, 3, 0),
 'End': datetime.datetime(2025, 1, 6, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 6, 3, 0),
 'End': datetime.datetime(2025, 1, 7, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 7, 3, 0),
 'End': datetime.datetime(2025, 1, 8, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 8, 3, 0),
 'End': datetime.datetime(2025, 1, 9, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '0 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '3:0',
 'Task': 'cdos/business/ucc',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 9, 3, 0),
 'End': datetime.datetime(2025, 1, 10, 3, 0),
 'Time': 3.0,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '10 4 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdot/transportation_road_attributes -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.8-jar-with-dependencies.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:10',
 'Task': 'cdot/transportation_road_attributes',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 4, 4, 10),
 'End': datetime.datetime(2025, 1, 5, 4, 10),
 'Time': 4.166666666666667,
 'Schedule': 'Monthly'}

{'Day': 'Saturday',
 'Cron': '30 4 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdot/transportation_infrastructure 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:30',
 'Task': 'cdot/transportation_infrastructure',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 4, 4, 30),
 'End': datetime.datetime(2025, 1, 5, 4, 30),
 'Time': 4.5,
 'Schedule': 'Monthly'}

{'Day': 'Saturday',
 'Cron': '50 4 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdot/natural_resources 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:50',
 'Task': 'cdot/natural_resources',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 4, 4, 50),
 'End': datetime.datetime(2025, 1, 5, 4, 50),
 'Time': 4.833333333333333,
 'Schedule': 'Monthly'}

{'Day': 'Tuesday',
 'Cron': '45 8 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdot/tops 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '8:45',
 'Task': 'cdot/tops',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 10, 8, 45),
 'End': datetime.datetime(2024, 12, 11, 8, 45),
 'Time': 8.75,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '45 8 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdot/tops 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '8:45',
 'Task': 'cdot/tops',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 17, 8, 45),
 'End': datetime.datetime(2024, 12, 18, 8, 45),
 'Time': 8.75,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '45 8 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdot/tops 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '8:45',
 'Task': 'cdot/tops',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 24, 8, 45),
 'End': datetime.datetime(2024, 12, 25, 8, 45),
 'Time': 8.75,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '45 8 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdot/tops 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '8:45',
 'Task': 'cdot/tops',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 31, 8, 45),
 'End': datetime.datetime(2025, 1, 1, 8, 45),
 'Time': 8.75,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '45 8 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdot/tops 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '8:45',
 'Task': 'cdot/tops',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 7, 8, 45),
 'End': datetime.datetime(2025, 1, 8, 8, 45),
 'Time': 8.75,
 'Schedule': 'Weekly'}

{'Day': 'Saturday',
 'Cron': '0 4 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dola/boundaries 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:0',
 'Task': 'dola/boundaries',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 4, 4, 0),
 'End': datetime.datetime(2025, 1, 5, 4, 0),
 'Time': 4.0,
 'Schedule': 'Monthly'}

{'Day': 'Saturday',
 'Cron': '20 5 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dola/special_districts 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '5:20',
 'Task': 'dola/special_districts',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 4, 5, 20),
 'End': datetime.datetime(2025, 1, 5, 5, 20),
 'Time': 5.333333333333333,
 'Schedule': 'Monthly'}

{'Day': 'Wednesday',
 'Cron': '30 4 1 * *  node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dola/demographics 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:30',
 'Task': 'dola/demographics',
 'Details': '',
 'Program': '',
 'Start': datetime.datetime(2025, 1, 1, 4, 30),
 'End': datetime.datetime(2025, 1, 2, 4, 30),
 'Time': 4.5,
 'Schedule': 'Monthly'}

{'Day': 'Sunday',
 'Cron': '20 4 1,8,15,22 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/revenue_marijuana 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:20',
 'Task': 'cdor/revenue_marijuana',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 15, 4, 20),
 'End': datetime.datetime(2024, 12, 16, 4, 20),
 'Time': 4.333333333333333,
 'Schedule': 'Weekly'}

{'Day': 'Sunday',
 'Cron': '20 4 1,8,15,22 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/revenue_marijuana 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:20',
 'Task': 'cdor/revenue_marijuana',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 22, 4, 20),
 'End': datetime.datetime(2024, 12, 23, 4, 20),
 'Time': 4.333333333333333,
 'Schedule': 'Weekly'}

{'Day': 'Wednesday',
 'Cron': '20 4 1,8,15,22 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/revenue_marijuana 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:20',
 'Task': 'cdor/revenue_marijuana',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 1, 4, 20),
 'End': datetime.datetime(2025, 1, 2, 4, 20),
 'Time': 4.333333333333333,
 'Schedule': 'Weekly'}

{'Day': 'Wednesday',
 'Cron': '20 4 1,8,15,22 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/revenue_marijuana 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:20',
 'Task': 'cdor/revenue_marijuana',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 8, 4, 20),
 'End': datetime.datetime(2025, 1, 9, 4, 20),
 'Time': 4.333333333333333,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '30 4 10 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/retail_reports 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '4:30',
 'Task': 'cdor/retail_reports',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 10, 4, 30),
 'End': datetime.datetime(2024, 12, 11, 4, 30),
 'Time': 4.5,
 'Schedule': 'Monthly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Gasoline Prices in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Gasoline Prices in Colorado"',
 'TM': '4:0',
 'Task': 'ceo/useia',
 'Details': '"Gasoline Prices in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 10, 4, 0),
 'End': datetime.datetime(2024, 12, 11, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Gasoline Prices in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Gasoline Prices in Colorado"',
 'TM': '4:0',
 'Task': 'ceo/useia',
 'Details': '"Gasoline Prices in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 17, 4, 0),
 'End': datetime.datetime(2024, 12, 18, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Gasoline Prices in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Gasoline Prices in Colorado"',
 'TM': '4:0',
 'Task': 'ceo/useia',
 'Details': '"Gasoline Prices in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 24, 4, 0),
 'End': datetime.datetime(2024, 12, 25, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Gasoline Prices in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Gasoline Prices in Colorado"',
 'TM': '4:0',
 'Task': 'ceo/useia',
 'Details': '"Gasoline Prices in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 31, 4, 0),
 'End': datetime.datetime(2025, 1, 1, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Tuesday',
 'Cron': '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Gasoline Prices in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Gasoline Prices in Colorado"',
 'TM': '4:0',
 'Task': 'ceo/useia',
 'Details': '"Gasoline Prices in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 7, 4, 0),
 'End': datetime.datetime(2025, 1, 8, 4, 0),
 'Time': 4.0,
 'Schedule': 'Weekly'}

{'Day': 'Thursday',
 'Cron': '0 5 * * 4 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Natural Gas Prices in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Natural Gas Prices in Colorado"',
 'TM': '5:0',
 'Task': 'ceo/useia',
 'Details': '"Natural Gas Prices in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 12, 5, 0),
 'End': datetime.datetime(2024, 12, 13, 5, 0),
 'Time': 5.0,
 'Schedule': 'Weekly'}

{'Day': 'Thursday',
 'Cron': '0 5 * * 4 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Natural Gas Prices in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Natural Gas Prices in Colorado"',
 'TM': '5:0',
 'Task': 'ceo/useia',
 'Details': '"Natural Gas Prices in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 19, 5, 0),
 'End': datetime.datetime(2024, 12, 20, 5, 0),
 'Time': 5.0,
 'Schedule': 'Weekly'}

{'Day': 'Thursday',
 'Cron': '0 5 * * 4 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Natural Gas Prices in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Natural Gas Prices in Colorado"',
 'TM': '5:0',
 'Task': 'ceo/useia',
 'Details': '"Natural Gas Prices in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2024, 12, 26, 5, 0),
 'End': datetime.datetime(2024, 12, 27, 5, 0),
 'Time': 5.0,
 'Schedule': 'Weekly'}

{'Day': 'Thursday',
 'Cron': '0 5 * * 4 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Natural Gas Prices in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Natural Gas Prices in Colorado"',
 'TM': '5:0',
 'Task': 'ceo/useia',
 'Details': '"Natural Gas Prices in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 2, 5, 0),
 'End': datetime.datetime(2025, 1, 3, 5, 0),
 'Time': 5.0,
 'Schedule': 'Weekly'}

{'Day': 'Thursday',
 'Cron': '0 5 * * 4 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p ceo/useia -t "Natural Gas Prices in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '"Natural Gas Prices in Colorado"',
 'TM': '5:0',
 'Task': 'ceo/useia',
 'Details': '"Natural Gas Prices in Colorado"',
 'Program': '/usr/local/cim/bic_etl/general/scripts/bic_etl.js',
 'Start': datetime.datetime(2025, 1, 9, 5, 0),
 'End': datetime.datetime(2025, 1, 10, 5, 0),
 'Time': 5.0,
 'Schedule': 'Weekly'}

{'Day': 'Monday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 9, 14, 47),
 'End': datetime.datetime(2024, 12, 10, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 10, 14, 47),
 'End': datetime.datetime(2024, 12, 11, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 11, 14, 47),
 'End': datetime.datetime(2024, 12, 12, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 12, 14, 47),
 'End': datetime.datetime(2024, 12, 13, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 13, 14, 47),
 'End': datetime.datetime(2024, 12, 14, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 14, 14, 47),
 'End': datetime.datetime(2024, 12, 15, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 15, 14, 47),
 'End': datetime.datetime(2024, 12, 16, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 16, 14, 47),
 'End': datetime.datetime(2024, 12, 17, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 17, 14, 47),
 'End': datetime.datetime(2024, 12, 18, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 18, 14, 47),
 'End': datetime.datetime(2024, 12, 19, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 19, 14, 47),
 'End': datetime.datetime(2024, 12, 20, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 20, 14, 47),
 'End': datetime.datetime(2024, 12, 21, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 21, 14, 47),
 'End': datetime.datetime(2024, 12, 22, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 22, 14, 47),
 'End': datetime.datetime(2024, 12, 23, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 23, 14, 47),
 'End': datetime.datetime(2024, 12, 24, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 24, 14, 47),
 'End': datetime.datetime(2024, 12, 25, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 25, 14, 47),
 'End': datetime.datetime(2024, 12, 26, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 26, 14, 47),
 'End': datetime.datetime(2024, 12, 27, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 27, 14, 47),
 'End': datetime.datetime(2024, 12, 28, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 28, 14, 47),
 'End': datetime.datetime(2024, 12, 29, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 29, 14, 47),
 'End': datetime.datetime(2024, 12, 30, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 30, 14, 47),
 'End': datetime.datetime(2024, 12, 31, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2024, 12, 31, 14, 47),
 'End': datetime.datetime(2025, 1, 1, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2025, 1, 1, 14, 47),
 'End': datetime.datetime(2025, 1, 2, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2025, 1, 2, 14, 47),
 'End': datetime.datetime(2025, 1, 3, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Friday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2025, 1, 3, 14, 47),
 'End': datetime.datetime(2025, 1, 4, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Saturday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2025, 1, 4, 14, 47),
 'End': datetime.datetime(2025, 1, 5, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Sunday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2025, 1, 5, 14, 47),
 'End': datetime.datetime(2025, 1, 6, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Monday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2025, 1, 6, 14, 47),
 'End': datetime.datetime(2025, 1, 7, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Tuesday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2025, 1, 7, 14, 47),
 'End': datetime.datetime(2025, 1, 8, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Wednesday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2025, 1, 8, 14, 47),
 'End': datetime.datetime(2025, 1, 9, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

{'Day': 'Thursday',
 'Cron': '47 14 * * * node /usr/local/cim/bic_etl/general/scripts/cleanup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
 'T': '',
 'TM': '14:47',
 'Task': 'cleanup.js',
 'Details': '',
 'Program': '/usr/local/cim/bic_etl/general/scripts/cleanup.js',
 'Start': datetime.datetime(2025, 1, 9, 14, 47),
 'End': datetime.datetime(2025, 1, 10, 14, 47),
 'Time': 14.783333333333333,
 'Schedule': 'Daily'}

In [27]:
toRun

['node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js ',
 '/usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json ',
 'PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a ',
 'node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder ',
 'node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog ',
 'node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar ',
 'node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" ',
 'node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" ',
 'node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist ',
 'node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/ucc ',
 'node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dora/regulations -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar ',
 'node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/revenue_marijuana ',
 'node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/regulations_liquor ',
 'node /usr/local/cim/bic_etl/general/scripts/cleanup.js ']

In [10]:
def showInfo(day):
    display("Show Day ",day)
    data = []
    for vals in info:
        if vals[0] == day:
            data.append(vals)
    data = sorted(data, key=lambda x: x[-1]) 
 #   data = data[:][:-1]
    display(data)
    header=["Day","Time","Schedule","Group","Dataset","Cron"]
    layout = [
              [sg.Text(f"Detailed Info for {day}",font='Courier 30 bold ')],
              [sg.Button('Quit',font='Courier 15 bold')],
              [sg.Table(values=data,
               background_color='green',auto_size_columns=True,enable_events=True,
               justification='center',alternating_row_color='brown',size=(100,30),
               key='-TABLE-', headings = header,vertical_scroll_only = False)]
        ]

    sg.theme('Dark Green 5')
    window2 = sg.Window('ETL', layout,finalize=True,resizable=True,background_color="#FFD700")

In [ ]:
days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]
layout = [
              [sg.Text("BIC Cron Finder",font='Courier 30 bold ')],
              [sg.Combo(days,enable_events=True,key="-DAYOFWEEK-",font='Courier 20 bold ')],
              [sg.Output(font='Courier 15 bold ',background_color="lightblue",key="-OUTPUT-",size=[120,20])],
              [sg.Button('Exit',font='Courier 15 bold')]
        ]

sg.theme('Dark Green 5')
window2 = sg.Window('ETL', layout,finalize=True,resizable=True,background_color="#FFD700")


try: 
    while True:

     #   event, values = window2.read()
        wid, event, values = sg.read_all_windows()
        print("\n\n-----------------------------------\n")
        print('event: ',event)
        print("VALS ",values)
        print(wid.Title)
        print(wid)

        if event == sg.WIN_CLOSED or event == "Exit":
            window2.close()
            break
        elif event == sg.WIN_CLOSED or event == "Quit":
            wid.close()
        elif event == "-DAYOFWEEK-":
            day = values['-DAYOFWEEK-']
            toRun = getDay(day)

            # string=""
            # for crn in toRun:
            #     string+= crn + "\n"

            wid["-OUTPUT-"].update("") 
            # wid["-OUTPUT-"].update(string) 
            for nn,crn in enumerate(toRun):
                if nn%2 == 0:
                    color="red"
                else:
                    color="green"
                wid['-OUTPUT-'].print(f"{crn}\n",text_color=color)
                
            showInfo(day)
            
              
            
            
except Exception as err:
    display(err)

In [20]:
info

[['Monday',
  '2:50',
  'Daily',
  'pull_and_setup.js',
  '',
  '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  2.8333333333333335],
 ['Tuesday',
  '2:50',
  'Daily',
  'pull_and_setup.js',
  '',
  '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  2.8333333333333335],
 ['Wednesday',
  '2:50',
  'Daily',
  'pull_and_setup.js',
  '',
  '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  2.8333333333333335],
 ['Thursday',
  '2:50',
  'Daily',
  'pull_and_setup.js',
  '',
  '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  2.8333333333333335],
 ['Friday',
  '2:50',
  'Daily',
  'pull_and_setup.js',
  '',
  '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  2.8333333333333335],
 ['Saturday',
  '2:50',
  'Daily',
  'pull_and_setup.js',
  '',
  '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  2.8333333333333335],
 ['Sunday',
  '2:50',
  'Daily',
  'pull_and_setup.js',
  '',
  '50 2 * * * node /usr/local/cim/bic_etl/general/scripts/pull_and_setup.js 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  2.8333333333333335],
 ['Monday',
  '2:58',
  'Daily',
  'DataSync-1.8.2.jar',
  'LoadPreferences',
  '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  2.966666666666667],
 ['Tuesday',
  '2:58',
  'Daily',
  'DataSync-1.8.2.jar',
  'LoadPreferences',
  '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  2.966666666666667],
 ['Wednesday',
  '2:58',
  'Daily',
  'DataSync-1.8.2.jar',
  'LoadPreferences',
  '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  2.966666666666667],
 ['Thursday',
  '2:58',
  'Daily',
  'DataSync-1.8.2.jar',
  'LoadPreferences',
  '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  2.966666666666667],
 ['Friday',
  '2:58',
  'Daily',
  'DataSync-1.8.2.jar',
  'LoadPreferences',
  '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  2.966666666666667],
 ['Saturday',
  '2:58',
  'Daily',
  'DataSync-1.8.2.jar',
  'LoadPreferences',
  '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  2.966666666666667],
 ['Sunday',
  '2:58',
  'Daily',
  'DataSync-1.8.2.jar',
  'LoadPreferences',
  '58 2 * * * /usr/bin/java -jar /usr/local/cim/bic_etl/general/datasync/DataSync-1.8.2.jar -t LoadPreferences -c /usr/local/cim/bic_etl/general/datasync/config.json 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  2.966666666666667],
 ['Monday',
  '5:0',
  'Daily',
  'metadata_updater.py',
  '',
  '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.0],
 ['Tuesday',
  '5:0',
  'Daily',
  'metadata_updater.py',
  '',
  '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.0],
 ['Wednesday',
  '5:0',
  'Daily',
  'metadata_updater.py',
  '',
  '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.0],
 ['Thursday',
  '5:0',
  'Daily',
  'metadata_updater.py',
  '',
  '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.0],
 ['Friday',
  '5:0',
  'Daily',
  'metadata_updater.py',
  '',
  '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.0],
 ['Saturday',
  '5:0',
  'Daily',
  'metadata_updater.py',
  '',
  '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.0],
 ['Sunday',
  '5:0',
  'Daily',
  'metadata_updater.py',
  '',
  '0 5 * * * PATH=$PATH:/home/giddensm/.local/bin PIPENV_PIPFILE=/usr/local/cim/bic_etl/general/metadata_updater/scripts/Pipfile pipenv run python /usr/local/cim/bic_etl/general/metadata_updater/scripts/metadata_updater.py -a 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.0],
 ['Monday',
  '3:10',
  'Daily',
  'boulder',
  '',
  '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  3.1666666666666665],
 ['Tuesday',
  '3:10',
  'Daily',
  'boulder',
  '',
  '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  3.1666666666666665],
 ['Wednesday',
  '3:10',
  'Daily',
  'boulder',
  '',
  '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  3.1666666666666665],
 ['Thursday',
  '3:10',
  'Daily',
  'boulder',
  '',
  '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  3.1666666666666665],
 ['Friday',
  '3:10',
  'Daily',
  'boulder',
  '',
  '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  3.1666666666666665],
 ['Saturday',
  '3:10',
  'Daily',
  'boulder',
  '',
  '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  3.1666666666666665],
 ['Sunday',
  '3:10',
  'Daily',
  'boulder',
  '',
  '10 3 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p boulder 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  3.1666666666666665],
 ['Monday',
  '4:0',
  'Daily',
  'catalog',
  '',
  '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.0],
 ['Tuesday',
  '4:0',
  'Daily',
  'catalog',
  '',
  '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.0],
 ['Wednesday',
  '4:0',
  'Daily',
  'catalog',
  '',
  '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.0],
 ['Thursday',
  '4:0',
  'Daily',
  'catalog',
  '',
  '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.0],
 ['Friday',
  '4:0',
  'Daily',
  'catalog',
  '',
  '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.0],
 ['Saturday',
  '4:0',
  'Daily',
  'catalog',
  '',
  '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.0],
 ['Sunday',
  '4:0',
  'Daily',
  'catalog',
  '',
  '0 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p catalog 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.0],
 ['Friday',
  '6:5',
  'Weekly',
  'cdos/business/nonprofit',
  '',
  '5 6 * * 5 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  6.083333333333333],
 ['Monday',
  '5:5',
  'Daily',
  'cdos/business/nonprofit',
  '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
  '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.083333333333333],
 ['Tuesday',
  '5:5',
  'Daily',
  'cdos/business/nonprofit',
  '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
  '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.083333333333333],
 ['Wednesday',
  '5:5',
  'Daily',
  'cdos/business/nonprofit',
  '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
  '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.083333333333333],
 ['Thursday',
  '5:5',
  'Daily',
  'cdos/business/nonprofit',
  '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
  '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.083333333333333],
 ['Friday',
  '5:5',
  'Daily',
  'cdos/business/nonprofit',
  '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
  '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.083333333333333],
 ['Saturday',
  '5:5',
  'Daily',
  'cdos/business/nonprofit',
  '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
  '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.083333333333333],
 ['Sunday',
  '5:5',
  'Daily',
  'cdos/business/nonprofit',
  '"Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado"',
  '5 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/nonprofit -t "Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado" -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.1.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.083333333333333],
 ['Monday',
  '5:10',
  'Daily',
  'cdos/business/business',
  '"Business Entities in Colorado"',
  '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.166666666666667],
 ['Tuesday',
  '5:10',
  'Daily',
  'cdos/business/business',
  '"Business Entities in Colorado"',
  '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.166666666666667],
 ['Wednesday',
  '5:10',
  'Daily',
  'cdos/business/business',
  '"Business Entities in Colorado"',
  '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.166666666666667],
 ['Thursday',
  '5:10',
  'Daily',
  'cdos/business/business',
  '"Business Entities in Colorado"',
  '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.166666666666667],
 ['Friday',
  '5:10',
  'Daily',
  'cdos/business/business',
  '"Business Entities in Colorado"',
  '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.166666666666667],
 ['Saturday',
  '5:10',
  'Daily',
  'cdos/business/business',
  '"Business Entities in Colorado"',
  '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.166666666666667],
 ['Sunday',
  '5:10',
  'Daily',
  'cdos/business/business',
  '"Business Entities in Colorado"',
  '10 5 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entities in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.166666666666667],
 ['Monday',
  '8:0',
  'Daily',
  'cdos/business/business',
  '"Business Entity Transaction History"',
  '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  8.0],
 ['Tuesday',
  '8:0',
  'Daily',
  'cdos/business/business',
  '"Business Entity Transaction History"',
  '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  8.0],
 ['Wednesday',
  '8:0',
  'Daily',
  'cdos/business/business',
  '"Business Entity Transaction History"',
  '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  8.0],
 ['Thursday',
  '8:0',
  'Daily',
  'cdos/business/business',
  '"Business Entity Transaction History"',
  '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  8.0],
 ['Friday',
  '8:0',
  'Daily',
  'cdos/business/business',
  '"Business Entity Transaction History"',
  '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  8.0],
 ['Saturday',
  '8:0',
  'Daily',
  'cdos/business/business',
  '"Business Entity Transaction History"',
  '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  8.0],
 ['Sunday',
  '8:0',
  'Daily',
  'cdos/business/business',
  '"Business Entity Transaction History"',
  '0 8 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Business Entity Transaction History" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  8.0],
 ['Tuesday',
  '4:0',
  'Weekly',
  'cdos/health',
  '',
  '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/health 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.0],
 ['Monday',
  '4:15',
  'Daily',
  'cdos/lobbyist',
  '',
  '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.25],
 ['Tuesday',
  '4:15',
  'Daily',
  'cdos/lobbyist',
  '',
  '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.25],
 ['Wednesday',
  '4:15',
  'Daily',
  'cdos/lobbyist',
  '',
  '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.25],
 ['Thursday',
  '4:15',
  'Daily',
  'cdos/lobbyist',
  '',
  '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.25],
 ['Friday',
  '4:15',
  'Daily',
  'cdos/lobbyist',
  '',
  '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.25],
 ['Saturday',
  '4:15',
  'Daily',
  'cdos/lobbyist',
  '',
  '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.25],
 ['Sunday',
  '4:15',
  'Daily',
  'cdos/lobbyist',
  '',
  '15 4 * * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/lobbyist 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.25],
 ['Tuesday',
  '4:30',
  'Weekly',
  'cdos/government',
  '',
  '30 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/government 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.5],
 ['Saturday',
  '5:30',
  'Monthly',
  'cdos/business/business',
  '"Master List in Colorado"',
  '30 5 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Master List in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  5.5],
 ['Tuesday',
  '4:0',
  'Weekly',
  'cdos/business/business',
  '"Trade Names for Businesses in Colorado"',
  '0 4 * * 2 node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t "Trade Names for Businesses in Colorado" 2>> /usr/local/cim/bic_etl/general/logs/cron.log',
  4.0],
 ['Tuesday',
  '4:0',
  'Weekly',
  'cdos/business/business',
  '"Trademarks for Businesses in Colorado"',

In [29]:
df=pd.DataFrame(info,columns=["Day","Time","Schedule","Program","Unknow","Cron","Cron Orig"])

In [30]:
df.head()

,Day,Time,Schedule,Program,Unknow,Cron,Cron Orig
0,Monday,2:50,Daily,pull_and_setup.js,,50 2 * * * node /usr/local/cim/bic_etl/general...,2.833333
1,Tuesday,2:50,Daily,pull_and_setup.js,,50 2 * * * node /usr/local/cim/bic_etl/general...,2.833333
2,Wednesday,2:50,Daily,pull_and_setup.js,,50 2 * * * node /usr/local/cim/bic_etl/general...,2.833333
3,Thursday,2:50,Daily,pull_and_setup.js,,50 2 * * * node /usr/local/cim/bic_etl/general...,2.833333
4,Friday,2:50,Daily,pull_and_setup.js,,50 2 * * * node /usr/local/cim/bic_etl/general...,2.833333

In [36]:
df.loc[df["Schedule"] == "Monthly",["Schedule","Program","Unknow","Cron"]]

,Schedule,Program,Unknow,Cron
66,Monthly,cdos/business/business,"""Master List in Colorado""","30 5 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdos/business/business -t ""Master List in Colorado"" 2>> /usr/local/cim/bic_etl/general/logs/cron.log"
76,Monthly,cdot/transportation_road_attributes,,10 4 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdot/transportation_road_attributes -d /usr/local/cim/bic_etl/general/datasync/DataSync-1.9.8-jar-with-dependencies.jar 2>> /usr/local/cim/bic_etl/general/logs/cron.log
77,Monthly,cdot/transportation_infrastructure,,30 4 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdot/transportation_infrastructure 2>> /usr/local/cim/bic_etl/general/logs/cron.log
78,Monthly,cdot/natural_resources,,50 4 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdot/natural_resources 2>> /usr/local/cim/bic_etl/general/logs/cron.log
80,Monthly,dola/boundaries,,0 4 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dola/boundaries 2>> /usr/local/cim/bic_etl/general/logs/cron.log
81,Monthly,dola/special_districts,,20 5 4 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dola/special_districts 2>> /usr/local/cim/bic_etl/general/logs/cron.log
82,Monthly,dola/demographics,,30 4 1 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p dola/demographics 2>> /usr/local/cim/bic_etl/general/logs/cron.log
85,Monthly,cdor/retail_reports,,30 4 10 * * node /usr/local/cim/bic_etl/general/scripts/bic_etl.js -p cdor/retail_reports 2>> /usr/local/cim/bic_etl/general/logs/cron.log

In [37]:
3/7

0.42857142857142855