In [ ]:
from io import BytesIO
from urllib.request import urlopen
from zipfile import ZipFile

zipurl = 'http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/LocalRoads.zip'

with urlopen(zipurl) as zipresp:
    with ZipFile(BytesIO(zipresp.read())) as zfile:
        zfile.extractall('data')

In [ ]:
import requests
url = 'http://dtdapps.coloradodot.info/staticdata/Downloads/StateGeoData/LocalRoads.zip'

r = requests.get(url)
with open("output.zip", "wb") as fd:
    fd.write(r.content)

In [ ]:
from zipfile import ZipFile
    
with ZipFile('output.zip') as myzip:
    myzip.extractall()

In [1]:
from osgeo import ogr
import csv,sys

In [ ]:
! dir SHP/STATEWIDE

In [4]:


shpfile=r'SHP/STATEWIDE/Local_Roads.shp' #sys.argv[1]
csvfile=r'test.csv' #sys.argv[2]

#Open files
csvfile=open(csvfile,'w')
ds=ogr.Open(shpfile)
lyr=ds.GetLayer()

#Get field names
dfn=lyr.GetLayerDefn()
#print(dfn)
nfields=dfn.GetFieldCount()
fields=[]
for i in range(nfields):
    fields.append(dfn.GetFieldDefn(i).GetName())
fields.append('kmlgeometry')
print(fields)
#csvwriter = csv.DictWriter(csvfile, fields)
csvwriter = csv.DictWriter(csvfile,fieldnames=fields)

try:csvwriter.writeheader() #python 2.7+
except:csvfile.write(','.join(fields)+'\n')

# Write attributes and kml out to csv
for feat in lyr:
    attributes=feat.items()
    geom=feat.GetGeometryRef()
    attributes['kmlgeometry']=geom.ExportToKML()
    csvwriter.writerow(attributes)

#clean up
del csvwriter,lyr,ds
csvfile.close()

['GISID', 'FIPS', 'ROUTE', 'SEGMID', 'SEG_LENGTH', 'FIPSCOUNTY', 'ROUTENAME', 'FROM_DESCR', 'SEGMDIR', 'TO_DESCR', 'FUNCCLASSI', 'ADMINCLASS', 'HPMSID', 'SURF_TYPE', 'SURFNAME', 'SURFWD', 'PSI', 'IRI', 'THRULNQTY', 'THRULNWD', 'OPERATION', 'URBAN', 'POPULATION', 'NHSDESIG', 'SPECIALSYS', 'GOVLEVEL', 'AADT', 'AADTYR', 'AADTDERIV', 'COUNTSTATI', 'BUILTYR', 'JURSPLIT', 'FORESTROUT', 'LRSROUTE', 'RUNLENGTH_', 'RUNLENGTH1', 'FundID', 'Shape_STLe', 'kmlgeometry']

In [3]:
shpfile=r'SHP/STATEWIDE/Local_Roads.shp' #sys.argv[1]
csvfile=r'test.csv' #sys.argv[2]

#Open files
#csvfile=open(csvfile,'w')
dataset=ogr.Open(shpfile)




### Let's get the driver from this file
driver = dataset.GetDriver()
print('Dataset driver is: {n}\n'.format(n=driver.name))

### How many layers are contained in this Shapefile?
layer_count = dataset.GetLayerCount()
print('The shapefile has {n} layer(s)\n'.format(n=layer_count))

### What is the name of the 1 layer?
layer = dataset.GetLayerByIndex(0)
print('The layer is named: {n}\n'.format(n=layer.GetName()))

### What is the layer's geometry? is it a point? a polyline? a polygon?
# First read in the geometry - but this is the enumerated type's value
geometry = layer.GetGeomType()

# So we need to translate it to the name of the enum
geometry_name = ogr.GeometryTypeToName(geometry)
print("The layer's geometry is: {geom}\n".format(geom=geometry_name))

### What is the layer's projection?
# Get the spatial reference
spatial_ref = layer.GetSpatialRef()

# Export this spatial reference to something we can read... like the Proj4
proj4 = spatial_ref.ExportToProj4()
print('Layer projection is: {proj4}\n'.format(proj4=proj4))

### How many features are in the layer?
feature_count = layer.GetFeatureCount()
print('Layer has {n} features\n'.format(n=feature_count))

### How many fields are in the shapefile, and what are their names?
# First we need to capture the layer definition
defn = layer.GetLayerDefn()

# How many fields
field_count = defn.GetFieldCount()
print('Layer has {n} fields'.format(n=field_count))

# What are their names?
print('Their names are: ')
for i in range(field_count):
    field_defn = defn.GetFieldDefn(i)
    print('\t{name} - {datatype}'.format(name=field_defn.GetName(),
                                         datatype=field_defn.GetTypeName()))

Dataset driver is: ESRI Shapefile

The shapefile has 1 layer(s)

The layer is named: Local_Roads

The layer's geometry is: 3D Measured Line String

Layer projection is: +proj=utm +zone=13 +datum=NAD83 +units=m +no_defs

Layer has 176643 features

Layer has 38 fields
Their names are:
	GISID - String
	FIPS - String
	ROUTE - String
	SEGMID - Integer64
	SEG_LENGTH - Real
	FIPSCOUNTY - String
	ROUTENAME - String
	FROM_DESCR - String
	SEGMDIR - String
	TO_DESCR - String
	FUNCCLASSI - String
	ADMINCLASS - String
	HPMSID - String
	SURF_TYPE - String
	SURFNAME - String
	SURFWD - Integer
	PSI - Real
	IRI - Integer
	THRULNQTY - Integer
	THRULNWD - Integer
	OPERATION - String
	URBAN - String
	POPULATION - String
	NHSDESIG - String
	SPECIALSYS - String
	GOVLEVEL - String
	AADT - Integer64
	AADTYR - String
	AADTDERIV - String
	COUNTSTATI - String
	BUILTYR - String
	JURSPLIT - String
	FORESTROUT - String
	LRSROUTE - String
	RUNLENGTH_ - Real
	RUNLENGTH1 - Real
	FundID - String
	Shape_STLe - Real

In [ ]:
srcdb = ogr.Open("test.csv")

In [ ]:
srcdb

In [ ]:
def getShapeInfo(file):
    shp = ogr.Open(file)    
    print(f"Name       : {shp.GetName()}")
    print(f"Layer Count: {shp.GetLayerCount()}")
    print(f"Description: {shp.GetDescription()}")
    print(f"Metadata   : {shp.GetMetadata()}")
    print(f"Drive      : {shp.GetDriver()}")   
    print(f"MetadataDom: {shp.GetMetadataDomainList()}")
    print(f"Ref Count  : {shp.GetRefCount()}")
#    print(shp.Release())
    layer = shp.GetLayer()
    print(f"Layer Name : {layer.GetName()}")
    print(f"   Feature Count      : {layer.GetFeatureCount()}")
    print(f"   Feature Description: {layer.GetDescription()}")
    print(f"   Layer Defnt        : {layer.GetLayerDefn()}")
    print(f"   Geometry Columnm   : {layer.GetGeometryColumn()}")
    print(f"   Style Table        : {layer.GetStyleTable()}")
    print(f"   Spatial Reference  : {layer.GetSpatialRef()}")
    
    
        
    
    
getShapeInfo("test.csv")

In [38]:
driver = ogr.GetDriverByName("ESRI Shapefile")
#driver = ogr.GetDriverByName("CSV")

dataSource = driver.Open("SHP/STATEWIDE/Local_Roads.shp", 0)
print(dataSource)
layer = dataSource.GetLayer()
print(layer.GetGeomType())
nfeat=0
layerDefinition = layer.GetLayerDefn()

names = []
dictShp = []
for i in range(layerDefinition.GetFieldCount()):
    a = layerDefinition.GetFieldDefn(i)
#    print (i,a.GetName(),a.GetNameRef(),a.GetType(),a.GetSubType(),a.GetFieldTypeName(a.GetType()),a.GetTypeName(),a.GetNameRef(),a.GetDomainName())
    names.append(a.GetName())

for feature in layer:
    tmp={}
    geom = feature.GetGeometryRef()
#     # print(geom)
#     # print (geom.Centroid().ExportToWkt())
#     print(geom.GetGeometryType())
#    print(geom)
    print(f"Dim: {geom.GetDimension()} WkbSize: {geom.WkbSize()} # Points: {geom.GetPointCount()} ")

#geom.GetSpatialReference()
#    print(dir(geom))
# #    print(dir(geom))
    print(f"Feat count: {feature.GetFieldCount()}  Geom Field Count: {feature.GetGeomFieldCount()}")
#    print(dir(feature))
    nfield=0
#    print(dir(geom))
#    print(geom.ExportToWkt())
    for field in feature:
#        print(names[nfield],field)
        tmp[names[nfield]] = field

        nfield+=1
#         print(f"Indx:  {field.index()}")
#         print(field.__class__)
#         print(dir(field))
# #     print(f"Style String: {feature.GetStyleString()}")
    #tmp["geom"] = geom.ExportToWkt()
#    tmp["geom"] = geom.GetPoint_2D()
    tmp["geom"] = []
    
    for p in geom.GetPoints():
        g=[]
        for pp in p:
            g.append(pp)
        tmp["geom"].append(g)

    dictShp.append(tmp)
    print("----------------")
    nfeat+=1
    if nfeat > 5: break

<osgeo.ogr.DataSource; proxy of <Swig Object of type 'OGRDataSourceShadow *' at 0x7f4a02c756c0> >
3002
Dim: 1 WkbSize: 585 # Points: 18
Feat count: 38  Geom Field Count: 1
----------------
Dim: 1 WkbSize: 265 # Points: 8
Feat count: 38  Geom Field Count: 1
----------------
Dim: 1 WkbSize: 73 # Points: 2
Feat count: 38  Geom Field Count: 1
----------------
Dim: 1 WkbSize: 169 # Points: 5
Feat count: 38  Geom Field Count: 1
----------------
Dim: 1 WkbSize: 169 # Points: 5
Feat count: 38  Geom Field Count: 1
----------------
Dim: 1 WkbSize: 73 # Points: 2
Feat count: 38  Geom Field Count: 1
----------------

In [39]:
dictShp

[{'GISID': '77290ELM      DR  100',
  'FIPS': 'Thornton',
  'ROUTE': 'ELM      DR',
  'SEGMID': 100,
  'SEG_LENGTH': 0.14,
  'FIPSCOUNTY': 'Adams',
  'ROUTENAME': 'ELM DR',
  'FROM_DESCR': None,
  'SEGMDIR': 'NW',
  'TO_DESCR': '108TH AV',
  'FUNCCLASSI': '7  Local',
  'ADMINCLASS': '2  Local Service',
  'HPMSID': None,
  'SURF_TYPE': 'Paved',
  'SURFNAME': '1    Asphalt',
  'SURFWD': 40,
  'PSI': 4.0,
  'IRI': 0,
  'THRULNQTY': 2,
  'THRULNWD': 12,
  'OPERATION': '2',
  'URBAN': '23527',
  'POPULATION': '4',
  'NHSDESIG': '0',
  'SPECIALSYS': '0',
  'GOVLEVEL': '4',
  'AADT': 0,
  'AADTYR': None,
  'AADTDERIV': None,
  'COUNTSTATI': None,
  'BUILTYR': None,
  'JURSPLIT': '0',
  'FORESTROUT': None,
  'LRSROUTE': '001-0-2013-0998',
  'RUNLENGTH_': 0.19,
  'RUNLENGTH1': 0.33,
  'FundID': 'LOCAL',
  'Shape_STLe': 184.059420481,
  'geom': [[506123.7756249998, 4415662.64875, 0.0],
   [506121.4123750003, 4415671.548374999, 0.0],
   [506115.60675000027, 4415686.99175, 0.0],
   [506103.16062499955, 4415718.314375, 0.0],
   [506097.8716249997, 4415730.784, 0.0],
   [506092.5486249998, 4415741.655375, 0.0],
   [506086.4565000003, 4415751.107875001, 0.0],
   [506080.89162500016, 4415759.517000001, 0.0],
   [506076.42787500005, 4415765.076375, 0.0],
   [506071.9597500004, 4415769.7469999995, 0.0],
   [506066.90725000016, 4415774.395749999, 0.0],
   [506061.3493750002, 4415779.4533750005, 0.0],
   [506055.23199999984, 4415784.336625, 0.0],
   [506049.01012500003, 4415788.661875, 0.0],
   [506042.32974999957, 4415792.786374999, 0.0],
   [506035.6972500002, 4415796.325874999, 0.0],
   [506028.85924999975, 4415799.435875, 0.0],
   [506018.2695000004, 4415803.68275, 0.0]]},
 {'GISID': '77290131ST    CT  200',
  'FIPS': 'Thornton',
  'ROUTE': '131ST    CT',
  'SEGMID': 200,
  'SEG_LENGTH': 0.059,
  'FIPSCOUNTY': 'Adams',
  'ROUTENAME': '131ST CT',
  'FROM_DESCR': 'CUL DE SAC',
  'SEGMDIR': 'E',
  'TO_DESCR': '131ST DR',
  'FUNCCLASSI': '7  Local',
  'ADMINCLASS': '2  Local Service',
  'HPMSID': None,
  'SURF_TYPE': 'Paved',
  'SURFNAME': '1    Asphalt',
  'SURFWD': 32,
  'PSI': 4.0,
  'IRI': 0,
  'THRULNQTY': 2,
  'THRULNWD': 10,
  'OPERATION': '2',
  'URBAN': '23527',
  'POPULATION': '4',
  'NHSDESIG': '0',
  'SPECIALSYS': '0',
  'GOVLEVEL': '4',
  'AADT': 0,
  'AADTYR': None,
  'AADTDERIV': None,
  'COUNTSTATI': None,
  'BUILTYR': '2012',
  'JURSPLIT': '0',
  'FORESTROUT': None,
  'LRSROUTE': '001-0-2013-0339',
  'RUNLENGTH_': 0.0,
  'RUNLENGTH1': 0.059,
  'FundID': 'LOCAL',
  'Shape_STLe': 96.0667685225,
  'geom': [[505158.73112499993, 4420490.351500001, 0.0],
   [505184.36649999954, 4420490.006999999, 0.0],
   [505191.8849999998, 4420490.224749999, 0.0],
   [505199.35424999986, 4420491.081, 0.0],
   [505206.7253750004, 4420492.565874999, 0.0],
   [505213.9456249997, 4420494.670875, 0.0],
   [505220.95912500005, 4420497.3807500005, 0.0],
   [505251.02962500043, 4420510.556500001, 0.0]]},
 {'GISID': '77290126TH    CT  100',
  'FIPS': 'Thornton',
  'ROUTE': '126TH    CT',
  'SEGMID': 100,
  'SEG_LENGTH': 0.04,
  'FIPSCOUNTY': 'Adams',
  'ROUTENAME': '126TH CT',
  'FROM_DESCR': 'CDS',
  'SEGMDIR': 'SE',
  'TO_DESCR': 'FOREST ST',
  'FUNCCLASSI': '7  Local',
  'ADMINCLASS': '2  Local Service',
  'HPMSID': None,
  'SURF_TYPE': 'Paved',
  'SURFNAME': '1    Asphalt',
  'SURFWD': 32,
  'PSI': 2.5,
  'IRI': 0,
  'THRULNQTY': 2,
  'THRULNWD': 11,
  'OPERATION': '2',
  'URBAN': '23527',
  'POPULATION': '4',
  'NHSDESIG': '0',
  'SPECIALSYS': '0',
  'GOVLEVEL': '4',
  'AADT': 0,
  'AADTYR': None,
  'AADTDERIV': None,
  'COUNTSTATI': None,
  'BUILTYR': None,
  'JURSPLIT': '0',
  'FORESTROUT': None,
  'LRSROUTE': '001-0-2013-0238',
  'RUNLENGTH_': 0.0,
  'RUNLENGTH1': 0.04,
  'FundID': 'LOCAL',
  'Shape_STLe': 57.727926275,
  'geom': [[506141.3591250004, 4419447.9846250005, 0.0],
   [506182.70012500044, 4419407.692749999, 0.0]]},
 {'GISID': '77290CHERRY   WY  400',
  'FIPS': 'Thornton',
  'ROUTE': 'CHERRY   WY',
  'SEGMID': 400,
  'SEG_LENGTH': 0.1,
  'FIPSCOUNTY': 'Adams',
  'ROUTENAME': 'CHERRY WY',
  'FROM_DESCR': 'CDS',
  'SEGMDIR': 'N',
  'TO_DESCR': '134TH AV',
  'FUNCCLASSI': '7  Local',
  'ADMINCLASS': '2  Local Service',
  'HPMSID': None,
  'SURF_TYPE': 'Paved',
  'SURFNAME': '1    Asphalt',
  'SURFWD': 32,
  'PSI': 4.0,
  'IRI': 0,
  'THRULNQTY': 2,
  'THRULNWD': 10,
  'OPERATION': '2',
  'URBAN': '23527',
  'POPULATION': '4',
  'NHSDESIG': '0',
  'SPECIALSYS': '0',
  'GOVLEVEL': '4',
  'AADT': 0,
  'AADTYR': None,
  'AADTDERIV': None,
  'COUNTSTATI': None,
  'BUILTYR': None,
  'JURSPLIT': '0',
  'FORESTROUT': None,
  'LRSROUTE': '001-0-2013-0814',
  'RUNLENGTH_': 0.0,
  'RUNLENGTH1': 0.1,
  'FundID': 'LOCAL',
  'Shape_STLe': 147.702420296,
  'geom': [[505729.5242499998, 4420993.504000001, 0.0],
   [505746.6660000002, 4421044.823625, 0.0],
   [505748.921875, 4421053.495999999, 0.0],
   [505750.96750000026, 4421074.378374999, 0.0],
   [505756.0870000003, 4421137.8245, 0.0]]},
 {'GISID': '7729093RD     AV   50',
  'FIPS': 'Thornton',
  'ROUTE': '93RD     AV',
  'SEGMID': 50,
  'SEG_LENGTH': 0.13,
  'FIPSCOUNTY': 'Adams',
  'ROUTENAME': '93RD AV',
  'FROM_DESCR': 'GARFIELD ST',
  'SEGMDIR': 'E',
  'TO_DESCR': 'COLORADO BD',
  'FUNCCLASSI': '7  Local',
  'ADMINCLASS': '2  Local Service',
  'HPMSID': None,
  'SURF_TYPE': 'Paved',
  'SURFNAME': '1    Asphalt',
  'SURFWD': 32,
  'PSI': 4.0,
  'IRI': 0,
  'THRULNQTY': 2,
  'THRULNWD': 10,
  'OPERATION': '2',
  'URBAN': '23527',
  'POPULATION': '4',
  'NHSDESIG': '0',
  'SPECIALSYS': '0',
  'GOVLEVEL': '4',
  'AADT': 0,
  'AADTYR': None,
  'AADTDERIV': None,
  'COUNTSTATI': None,
  'BUILTYR': '2002',
  'JURSPLIT': '0',
  'FORESTROUT': None,
  'LRSROUTE': '001-0-2013-0594',
  'RUNLENGTH_': 0.0,
  'RUNLENGTH1': 0.13,
  'FundID': 'LOCAL',
  'Shape_STLe': 211.30156704,
  'geom': [[504886.33325000014, 4412794.052874999, 0.0],
   [504963.4263749998, 4412794.550875001, 0.0],
   [505039.5525000002, 4412795.051000001, 0.0],
   [505095.64487500023, 4412795.551124999, 0.0],
   [505097.62925000023, 4412795.569625, 0.0]]},
 {'GISID': '7729098TH     AV  120',
  'FIPS': 'Thornton',
  'ROUTE': '98TH     AV',
  'SEGMID': 120,
  'SEG_LENGTH': 0.028,
  'FIPSCOUNTY': 'Adams',
  'ROUTENAME': '98TH AV',
  'FROM_DESCR': '98TH AV',
  'SEGMDIR': 'N',
  'TO_DESCR': 'CDS',
  'FUNCCLASSI': '7  Local',
  'ADMINCLASS': '2  Local Service',
  'HPMSID': None,
  'SURF_TYPE': 'Paved',
  'SURFNAME': '1    Asphalt',
  'SURFWD': 36,
  'PSI': 1.0,
  'IRI': 0,
  'THRULNQTY': 2,
  'THRULNWD': 10,
  'OPERATION': '2',
  'URBAN': '23527',
  'POPULATION': '4',
  'NHSDESIG': '0',
  'SPECIALSYS': '0',
  'GOVLEVEL': '4',
  'AADT': 0,
  'AADTYR': None,
  'AADTDERIV': None,
  'COUNTSTATI': None,
  'BUILTYR': None,
  'JURSPLIT': '0',
  'FORESTROUT': None,
  'LRSROUTE': '001-0-2013-0652',
  'RUNLENGTH_': 0.0,
  'RUNLENGTH1': 0.028,
  'FundID': 'LOCAL',
  'Shape_STLe': 39.6901320113,
  'geom': [[502589.93987500016, 4413940.41925, 0.0],
   [502589.42174999975, 4413980.106000001, 0.0]]}]

In [41]:
import pandas as pd
df = pd.DataFrame(dictShp)

In [42]:
df.head()

,GISID,FIPS,ROUTE,SEGMID,SEG_LENGTH,FIPSCOUNTY,ROUTENAME,FROM_DESCR,SEGMDIR,TO_DESCR,...,COUNTSTATI,BUILTYR,JURSPLIT,FORESTROUT,LRSROUTE,RUNLENGTH_,RUNLENGTH1,FundID,Shape_STLe,geom
0,77290ELM DR 100,Thornton,ELM DR,100,0.140,Adams,ELM DR,None,NW,108TH AV,...,None,None,0,None,001-0-2013-0998,0.19,0.330,LOCAL,184.059420,"[[506123.7756249998, 4415662.64875, 0.0], [506..."
1,77290131ST CT 200,Thornton,131ST CT,200,0.059,Adams,131ST CT,CUL DE SAC,E,131ST DR,...,None,2012,0,None,001-0-2013-0339,0.00,0.059,LOCAL,96.066769,"[[505158.73112499993, 4420490.351500001, 0.0],..."
2,77290126TH CT 100,Thornton,126TH CT,100,0.040,Adams,126TH CT,CDS,SE,FOREST ST,...,None,None,0,None,001-0-2013-0238,0.00,0.040,LOCAL,57.727926,"[[506141.3591250004, 4419447.9846250005, 0.0],..."
3,77290CHERRY WY 400,Thornton,CHERRY WY,400,0.100,Adams,CHERRY WY,CDS,N,134TH AV,...,None,None,0,None,001-0-2013-0814,0.00,0.100,LOCAL,147.702420,"[[505729.5242499998, 4420993.504000001, 0.0], ..."
4,7729093RD AV 50,Thornton,93RD AV,50,0.130,Adams,93RD AV,GARFIELD ST,E,COLORADO BD,...,None,2002,0,None,001-0-2013-0594,0.00,0.130,LOCAL,211.301567,"[[504886.33325000014, 4412794.052874999, 0.0],..."

In [43]:
layerDefinition = layer.GetLayerDefn()


for i in range(layerDefinition.GetFieldCount()):
    a = layerDefinition.GetFieldDefn(i)
    print (i,a.GetName(),a.GetNameRef(),a.GetType(),a.GetSubType(),a.GetFieldTypeName(a.GetType()),a.GetTypeName(),a.GetNameRef(),a.GetDomainName())
#    print (dir(layerDefinition.GetFieldDefn(i)))

0 GISID GISID 4 0 String String GISID
1 FIPS FIPS 4 0 String String FIPS
2 ROUTE ROUTE 4 0 String String ROUTE
3 SEGMID SEGMID 12 0 Integer64 Integer64 SEGMID
4 SEG_LENGTH SEG_LENGTH 2 0 Real Real SEG_LENGTH
5 FIPSCOUNTY FIPSCOUNTY 4 0 String String FIPSCOUNTY
6 ROUTENAME ROUTENAME 4 0 String String ROUTENAME
7 FROM_DESCR FROM_DESCR 4 0 String String FROM_DESCR
8 SEGMDIR SEGMDIR 4 0 String String SEGMDIR
9 TO_DESCR TO_DESCR 4 0 String String TO_DESCR
10 FUNCCLASSI FUNCCLASSI 4 0 String String FUNCCLASSI
11 ADMINCLASS ADMINCLASS 4 0 String String ADMINCLASS
12 HPMSID HPMSID 4 0 String String HPMSID
13 SURF_TYPE SURF_TYPE 4 0 String String SURF_TYPE
14 SURFNAME SURFNAME 4 0 String String SURFNAME
15 SURFWD SURFWD 0 0 Integer Integer SURFWD
16 PSI PSI 2 0 Real Real PSI
17 IRI IRI 0 0 Integer Integer IRI
18 THRULNQTY THRULNQTY 0 0 Integer Integer THRULNQTY
19 THRULNWD THRULNWD 0 0 Integer Integer THRULNWD
20 OPERATION OPERATION 4 0 String String OPERATION
21 URBAN URBAN 4 0 String String URBAN
22 POPULATION POPULATION 4 0 String String POPULATION
23 NHSDESIG NHSDESIG 4 0 String String NHSDESIG
24 SPECIALSYS SPECIALSYS 4 0 String String SPECIALSYS
25 GOVLEVEL GOVLEVEL 4 0 String String GOVLEVEL
26 AADT AADT 12 0 Integer64 Integer64 AADT
27 AADTYR AADTYR 4 0 String String AADTYR
28 AADTDERIV AADTDERIV 4 0 String String AADTDERIV
29 COUNTSTATI COUNTSTATI 4 0 String String COUNTSTATI
30 BUILTYR BUILTYR 4 0 String String BUILTYR
31 JURSPLIT JURSPLIT 4 0 String String JURSPLIT
32 FORESTROUT FORESTROUT 4 0 String String FORESTROUT
33 LRSROUTE LRSROUTE 4 0 String String LRSROUTE
34 RUNLENGTH_ RUNLENGTH_ 2 0 Real Real RUNLENGTH_
35 RUNLENGTH1 RUNLENGTH1 2 0 Real Real RUNLENGTH1
36 FundID FundID 4 0 String String FundID
37 Shape_STLe Shape_STLe 2 0 Real Real Shape_STLe

##

## GeoPandas

### Shape

In [2]:
import geopandas as gpd

In [3]:
gfg = gpd.read_file("/home/joe/bic_etl/cdot/natural_resources/data_transformed/lakes/SHP/STATEWIDE/LAKES.shp")

ERROR 1: libpoppler.so.140: cannot open shared object file: No such file or directory
ERROR 1: libpoppler.so.140: cannot open shared object file: No such file or directory

In [4]:
gfg.shape

(7669, 5)

In [5]:
gfg.head()

,NAME,CO_FIPS,SHAPE_area,SHAPE_len,geometry
0,None,75,43943.882906,1421.863910,"POLYGON ((649398.625 4536736, 649423.187 45367..."
1,None,123,113139.428500,2612.763812,"POLYGON ((564387.812 4536298, 564367.313 45363..."
2,None,123,19650.690250,665.928074,"POLYGON ((540634.25 4536306.5, 540624 4536321...."
3,None,75,33915.643687,718.493858,"POLYGON ((667222.563 4535920.5, 667221.563 453..."
4,None,123,16946.800750,673.976201,"POLYGON ((601993.25 4535612, 601996.25 4535574..."

In [6]:
gfg.columns

Index(['NAME', 'CO_FIPS', 'SHAPE_area', 'SHAPE_len', 'geometry'], dtype='object')

In [ ]:
dir(gf)

In [18]:
gf.to_csv("new.csv")

In [43]:
import sys
sys.setrecursionlimit(4000)

### CSV

In [66]:
gfo = gpd.read_file("SHP/STATEWIDE/Local_Roads.csv")

In [67]:
gfo.shape

(176643, 40)

In [68]:
display(gfo.head())

,WKT,GISID,FIPS,ROUTE,SEGMID,SEG_LENGTH,FIPSCOUNTY,ROUTENAME,FROM_DESCR,SEGMDIR,...,COUNTSTATI,BUILTYR,JURSPLIT,FORESTROUT,LRSROUTE,RUNLENGTH_,RUNLENGTH1,FundID,Shape_STLe,geometry
0,LINESTRING ZM (506123.775625 4415662.64875 0 0...,77290ELM DR 100,Thornton,ELM DR,100,0.140,Adams,ELM DR,,NW,...,,,0,,001-0-2013-0998,0.19,0.330,LOCAL,184.059420,"LINESTRING Z (506123.776 4415662.649 0.000, 50..."
1,LINESTRING ZM (505158.731125 4420490.3515 0 -2...,77290131ST CT 200,Thornton,131ST CT,200,0.059,Adams,131ST CT,CUL DE SAC,E,...,,2012,0,,001-0-2013-0339,0.00,0.059,LOCAL,96.066769,"LINESTRING Z (505158.731 4420490.351 0.000, 50..."
2,LINESTRING ZM (506141.359125 4419447.984625 0 ...,77290126TH CT 100,Thornton,126TH CT,100,0.040,Adams,126TH CT,CDS,SE,...,,,0,,001-0-2013-0238,0.00,0.040,LOCAL,57.727926,"LINESTRING Z (506141.359 4419447.985 0.000, 50..."
3,LINESTRING ZM (505729.52425 4420993.504 0 -2.7...,77290CHERRY WY 400,Thornton,CHERRY WY,400,0.100,Adams,CHERRY WY,CDS,N,...,,,0,,001-0-2013-0814,0.00,0.100,LOCAL,147.702420,"LINESTRING Z (505729.524 4420993.504 0.000, 50..."
4,LINESTRING ZM (504886.33325 4412794.052875 0 -...,7729093RD AV 50,Thornton,93RD AV,50,0.130,Adams,93RD AV,GARFIELD ST,E,...,,2002,0,,001-0-2013-0594,0.00,0.130,LOCAL,211.301567,"LINESTRING Z (504886.333 4412794.053 0.000, 50..."

In [69]:
gfo.plot()

ValueError: 'box_aspect' and 'fig_aspect' must be positive

ValueError: 'box_aspect' and 'fig_aspect' must be positive

In [30]:
gfo.head()

,WKT,GISID,FIPS,ROUTE,SEGMID,SEG_LENGTH,FIPSCOUNTY,ROUTENAME,FROM_DESCR,SEGMDIR,...,COUNTSTATI,BUILTYR,JURSPLIT,FORESTROUT,LRSROUTE,RUNLENGTH_,RUNLENGTH1,FundID,Shape_STLe,geometry
0,LINESTRING ZM (506123.775625 4415662.64875 0 0...,77290ELM DR 100,Thornton,ELM DR,100,0.140,Adams,ELM DR,,NW,...,,,0,,001-0-2013-0998,0.190,0.330,LOCAL,184.05942048100,"LINESTRING Z (506123.776 4415662.649 0.000, 50..."
1,LINESTRING ZM (505158.731125 4420490.3515 0 -2...,77290131ST CT 200,Thornton,131ST CT,200,0.059,Adams,131ST CT,CUL DE SAC,E,...,,2012,0,,001-0-2013-0339,0.000,0.059,LOCAL,96.06676852250,"LINESTRING Z (505158.731 4420490.351 0.000, 50..."
2,LINESTRING ZM (506141.359125 4419447.984625 0 ...,77290126TH CT 100,Thornton,126TH CT,100,0.040,Adams,126TH CT,CDS,SE,...,,,0,,001-0-2013-0238,0.000,0.040,LOCAL,57.72792627500,"LINESTRING Z (506141.359 4419447.985 0.000, 50..."
3,LINESTRING ZM (505729.52425 4420993.504 0 -2.7...,77290CHERRY WY 400,Thornton,CHERRY WY,400,0.100,Adams,CHERRY WY,CDS,N,...,,,0,,001-0-2013-0814,0.000,0.100,LOCAL,147.70242029600,"LINESTRING Z (505729.524 4420993.504 0.000, 50..."
4,LINESTRING ZM (504886.33325 4412794.052875 0 -...,7729093RD AV 50,Thornton,93RD AV,50,0.130,Adams,93RD AV,GARFIELD ST,E,...,,2002,0,,001-0-2013-0594,0.000,0.130,LOCAL,211.30156704000,"LINESTRING Z (504886.333 4412794.053 0.000, 50..."

In [32]:
print(gfo["WKT"].head())
print(gfo["geometry"].head())

0    LINESTRING ZM (506123.775625 4415662.64875 0 0...
1    LINESTRING ZM (505158.731125 4420490.3515 0 -2...
2    LINESTRING ZM (506141.359125 4419447.984625 0 ...
3    LINESTRING ZM (505729.52425 4420993.504 0 -2.7...
4    LINESTRING ZM (504886.33325 4412794.052875 0 -...
Name: WKT, dtype: object
0    LINESTRING Z (506123.776 4415662.649 0.000, 50...
1    LINESTRING Z (505158.731 4420490.351 0.000, 50...
2    LINESTRING Z (506141.359 4419447.985 0.000, 50...
3    LINESTRING Z (505729.524 4420993.504 0.000, 50...
4    LINESTRING Z (504886.333 4412794.053 0.000, 50...
Name: geometry, dtype: geometry

In [6]:
dir(gfg['geometry'].dtype.name)
print(gfg['geometry'].dtype.name)

geometry

## Compare

In [70]:
def compareDF(df1,df2):
    nums = ["int","int64","float","float64"]
    strs = ["object","str","string"]
    cols1 = set(df1.columns)
    cols2 = set(df2.columns)
    cols = list(cols1 & cols2)
    dc1 = list(cols1 - cols2)
    dc2 = list(cols2 - cols1)
    print(cols)
    print(dc1)
    print(dc2)
    
    nrows1 = df1.shape[0]
    nrows2 = df2.shape[0]
    print(nrows1,nrows2)
    stats={}
    for col in cols:
     #   print(col)
        stats[col] = {}
        stats[col]['good'] = 0
        stats[col]['bad'] = 0
   #     print("one ",df1[col].dtype,df2[col].dtype)
        if df1[col].dtype.name in nums and df2[col].dtype.name not in nums:
            df2[col] =  df2[col].astype(df1[col].dtype)
        elif df1[col].dtype.name not in nums and df2[col].dtype.name in nums:
            df1[col] =  df1[col].astype(df2[col].dtype)
  #      print("two ",df1[col].dtype,df2[col].dtype)
                                        

        if df1[col].dtype.name != 'geometry':
   #         print(df1[col].dtype.name,df2[col].dtype.name)
            a = df1[col].values.tolist()
            b = df2[col].values.tolist()
            for nn in range(nrows1):
                if a[nn] == None:
                    a[nn] = ""
                if b[nn] == None:
                    b[nn] = ""   
                
      #          print(nn,col,"a:",a[nn],"b:",b[nn],type(a[nn]),type(b[nn]))
                
                if a[nn] == b[nn]:
                    stats[col]['good']+=1
                else:
                    stats[col]['bad']+=1
      #          if nn > 10: break
        
    return stats    
    
#stats=compareDF(gfg,gfo)

['RUNLENGTH1', 'URBAN', 'HPMSID', 'AADTYR', 'RUNLENGTH_', 'OPERATION', 'FUNCCLASSI', 'FundID', 'SURFWD', 'FIPS', 'GISID', 'SEGMDIR', 'SEG_LENGTH', 'ROUTE', 'FROM_DESCR', 'IRI', 'GOVLEVEL', 'FIPSCOUNTY', 'Shape_STLe', 'NHSDESIG', 'BUILTYR', 'geometry', 'ADMINCLASS', 'JURSPLIT', 'AADT', 'LRSROUTE', 'SURF_TYPE', 'TO_DESCR', 'PSI', 'THRULNQTY', 'ROUTENAME', 'SURFNAME', 'THRULNWD', 'POPULATION', 'COUNTSTATI', 'SEGMID', 'SPECIALSYS', 'FORESTROUT', 'AADTDERIV']
[]
['WKT']
176643 176643

In [71]:
gfo = gpd.read_file("SHP/STATEWIDE/Loal_Roads.csv")

In [83]:
gfo["geometry"].head()

0    LINESTRING Z (-104.92837 39.89101 0.00000, -10...
1    LINESTRING Z (-104.93962 39.93451 0.00000, -10...
2    LINESTRING Z (-104.92813 39.92511 0.00000, -10...
3    LINESTRING Z (-104.93294 39.93904 0.00000, -10...
4    LINESTRING Z (-104.94287 39.86517 0.00000, -10...
Name: geometry, dtype: geometry

In [82]:
gfn = gpd.read_file("SHP/STATEWIDE/Local_Roads.csv")
print(gfn["geometry"].head())
print(gfn["WKT"].head())

0    LINESTRING Z (506123.776 4415662.649 0.000, 50...
1    LINESTRING Z (505158.731 4420490.351 0.000, 50...
2    LINESTRING Z (506141.359 4419447.985 0.000, 50...
3    LINESTRING Z (505729.524 4420993.504 0.000, 50...
4    LINESTRING Z (504886.333 4412794.053 0.000, 50...
Name: geometry, dtype: geometry
0    LINESTRING ZM (506123.775625 4415662.64875 0 0...
1    LINESTRING ZM (505158.731125 4420490.3515 0 -2...
2    LINESTRING ZM (506141.359125 4419447.984625 0 ...
3    LINESTRING ZM (505729.52425 4420993.504 0 -2.7...
4    LINESTRING ZM (504886.33325 4412794.052875 0 -...
Name: WKT, dtype: object

In [73]:
stats = compareDF(gfo,gfn)

['WKT', 'RUNLENGTH1', 'URBAN', 'HPMSID', 'AADTYR', 'RUNLENGTH_', 'OPERATION', 'FUNCCLASSI', 'FundID', 'SURFWD', 'FIPS', 'GISID', 'SEGMDIR', 'ROUTE', 'SEG_LENGTH', 'FROM_DESCR', 'IRI', 'GOVLEVEL', 'FIPSCOUNTY', 'BUILTYR', 'NHSDESIG', 'Shape_STLe', 'geometry', 'ADMINCLASS', 'JURSPLIT', 'AADT', 'LRSROUTE', 'SURF_TYPE', 'TO_DESCR', 'PSI', 'THRULNQTY', 'ROUTENAME', 'SURFNAME', 'THRULNWD', 'POPULATION', 'COUNTSTATI', 'SEGMID', 'SPECIALSYS', 'FORESTROUT', 'AADTDERIV']
[]
[]
176643 176643

In [74]:
for col in stats.keys():
    print(col,stats[col]['good'],stats[col]['bad'])

WKT 0 176643
RUNLENGTH1 176643 0
URBAN 176643 0
HPMSID 176643 0
AADTYR 176643 0
RUNLENGTH_ 176643 0
OPERATION 176643 0
FUNCCLASSI 176643 0
FundID 176643 0
SURFWD 176643 0
FIPS 176643 0
GISID 176643 0
SEGMDIR 176643 0
ROUTE 176643 0
SEG_LENGTH 176643 0
FROM_DESCR 176643 0
IRI 176643 0
GOVLEVEL 176643 0
FIPSCOUNTY 176643 0
BUILTYR 176643 0
NHSDESIG 176643 0
Shape_STLe 176643 0
geometry 0 0
ADMINCLASS 176643 0
JURSPLIT 176643 0
AADT 176643 0
LRSROUTE 176643 0
SURF_TYPE 176643 0
TO_DESCR 176643 0
PSI 176643 0
THRULNQTY 176643 0
ROUTENAME 176643 0
SURFNAME 176643 0
THRULNWD 176643 0
POPULATION 176643 0
COUNTSTATI 176643 0
SEGMID 176643 0
SPECIALSYS 176643 0
FORESTROUT 176643 0
AADTDERIV 176643 0

In [75]:
gfo["geometry"].head()

0    LINESTRING Z (-104.92837 39.89101 0.00000, -10...
1    LINESTRING Z (-104.93962 39.93451 0.00000, -10...
2    LINESTRING Z (-104.92813 39.92511 0.00000, -10...
3    LINESTRING Z (-104.93294 39.93904 0.00000, -10...
4    LINESTRING Z (-104.94287 39.86517 0.00000, -10...
Name: geometry, dtype: geometry

In [76]:
gfn["geometry"].head()

0    LINESTRING Z (506123.776 4415662.649 0.000, 50...
1    LINESTRING Z (505158.731 4420490.351 0.000, 50...
2    LINESTRING Z (506141.359 4419447.985 0.000, 50...
3    LINESTRING Z (505729.524 4420993.504 0.000, 50...
4    LINESTRING Z (504886.333 4412794.053 0.000, 50...
Name: geometry, dtype: geometry

In [ ]:
gfg["geometry"].to_list()

In [15]:
gfo.columns

Index(['WKT', 'GISID', 'FIPS', 'ROUTE', 'SEGMID', 'SEG_LENGTH', 'FIPSCOUNTY',
       'ROUTENAME', 'FROM_DESCR', 'SEGMDIR', 'TO_DESCR', 'FUNCCLASSI',
       'ADMINCLASS', 'HPMSID', 'SURF_TYPE', 'SURFNAME', 'SURFWD', 'PSI', 'IRI',
       'THRULNQTY', 'THRULNWD', 'OPERATION', 'URBAN', 'POPULATION', 'NHSDESIG',
       'SPECIALSYS', 'GOVLEVEL', 'AADT', 'AADTYR', 'AADTDERIV', 'COUNTSTATI',
       'BUILTYR', 'JURSPLIT', 'FORESTROUT', 'LRSROUTE', 'RUNLENGTH_',
       'RUNLENGTH1', 'FundID', 'Shape_STLe', 'geometry'],
      dtype='object')

In [ ]:
gf.to_file("new.shp")

In [ ]:
gfn = gpd.read_file("new.shp")

In [ ]:
gf.difference(gfn)

In [ ]:
gfn.head()

In [ ]:
gf.shape

In [ ]:
gfn.shape

In [ ]:
gfn.plot()

In [ ]:
gf.area

In [ ]:
dir(gf)

In [ ]:
gf.LINESTRING()

In [ ]:
gf.difference(gfn)

In [ ]:
gf.columns

In [ ]:
gf.geometry

In [ ]:
gfn.geometry

In [ ]:
for col in gf.columns:
    a = gf[col].values
    b = gfn[col].values
    fail=False
    nbad=0
    ngood=0
    for nn in range(len(a)):
        if a[nn] == b[nn]:
            ngood+=1
        else:
            nbad=1
            fail = True
            print(col,nn)
    if (fail):
        print(col)
    else:
        print(f"Col: {col}  Good: {ngood}  Bad: {nbad}")

## GDAL

In [ ]:
from osgeo import ogr, osr, gdal
gdal.UseExceptions()
#gdal.DontUseExceptions()

In [ ]:
gdal.UseExceptions()
#gdal.DontUseExceptions()

In [ ]:
from osgeo import ogr, osr, gdal
gdal.UseExceptions()
#gdal.DontUseExceptions()

# def gdal_error_handler(err_class, err_num, err_msg):
#     errtype = {
#             gdal.CE_None:'None',
#             gdal.CE_Debug:'Debug',
#             gdal.CE_Warning:'Warning',
#             gdal.CE_Failure:'Failure',
#             gdal.CE_Fatal:'Fatal'
#     }
#     err_msg = err_msg.replace('\n',' ')
#     err_class = errtype.get(err_class, 'None')
#     print ('Error Number: %s' % (err_num))
#     print ('Error Type: %s' % (err_class))
#     print ('Error Message: %s' % (err_msg))

# if __name__=='__main__':

#     # install error handler
#     gdal.PushErrorHandler(gdal_error_handler)

#     # Raise a dummy error
#     gdal.Error(1, 2, 'test error')

#     #uninstall error handler
#     gdal.PopErrorHandler()

In [ ]:
# indriver=ogr.GetDriverByName('ESRI Shapefile')
# srcdb = indriver.Open('SHP/STATEWIDE/Local_Roads.shp',0)
srcdb = ogr.Open("SHP/STATEWIDE/Local_Roads.shp")

In [ ]:
layer = srcdb.GetLayer()

In [ ]:
nfeat=0
for feature in layer:
    nfeat+=1

In [ ]:
print(feature.GetFieldCount())
print(feature.GetFieldType())

In [ ]:
dir(feature)

In [ ]:
for field in feature:
    print(field)
#    print(field.__class__,isinstance(field,str))
    if (isinstance(field,str)):
        print(field.title())
    else:
        print(field)
        print(dir(field))
    # print(field.isnumeric())
 #   break

In [ ]:
dir(field)

In [ ]:
dir(field)

In [ ]:
dir(field)

In [ ]:
dir(feature.GetFeatureFieldCount())

In [ ]:
def getShapeInfo(file):
    shp = ogr.Open(file)    
    print(f"Name       : {shp.GetName()}")
    print(f"Layer Count: {shp.GetLayerCount()}")
    print(f"Description: {shp.GetDescription()}")
    print(f"Metadata   : {shp.GetMetadata()}")
    print(f"Drive      : {shp.GetDriver()}")   
    print(f"MetadataDom: {shp.GetMetadataDomainList()}")
    print(f"Ref Count  : {shp.GetRefCount()}")
#    print(shp.Release())
    layer = shp.GetLayer()
    print(f"Layer Name : {layer.GetName()}")
    print(f"   Feature Count      : {layer.GetFeatureCount()}")
    print(f"   Feature Description: {layer.GetDescription()}")
    print(f"   Layer Defnt        : {layer.GetLayerDefn()}")
    print(f"   Geometry Columnm   : {layer.GetGeometryColumn()}")
    print(f"   Style Table        : {layer.GetStyleTable()}")
    print(f"   Spatial Reference  : {layer.GetSpatialRef()}")
    
    for feature in layer.GetFeature():
        
    
    
getShapeInfo("SHP/STATEWIDE/Local_Roads.shp")

In [ ]:
dir(srcdb)

In [ ]:
layer = srcdb.GetLayer()
featureCount = layer.GetFeatureCount()
print ("Number of features in : %d" % (featureCount))
print(layer.GetName())

In [ ]:
dir(layer)

In [ ]:
layer.GetName()

In [ ]:

for feature in layer:
    print (feature)
layer.ResetReading()

In [ ]:
layer.GetName()

In [ ]:
dir(layer)

In [ ]:
'GetDescription',
 'GetDriver',
 'GetLayer',
 'GetLayerByIndex',
 'GetLayerByName',
 'GetLayerCount',
 'GetMetadata',
 'GetMetadataDomainList',
 'GetMetadataItem',
 'GetMetadata_Dict',
 'GetMetadata_List',
 'GetName',
 'GetRefCount',
 'GetStyleTable',
 'GetSummaryRefCount',

In [ ]:
print(srcdb.GetDescription())
print(srcdb.GetDriver())
print(srcdb.GetLayer())
#print(srcdb.GetLayerByName())
print(srcdb.GetLayerCount())
print(srcdb.GetMetadata())
#print(srcdb.GetMetadataItem())
print(srcdb.GetMetadata_Dict())
print(srcdb.GetMetadata_List())
print(srcdb.GetName())
print(srcdb.GetRefCount())
print(srcdb.GetStyleTable())
print(srcdb.GetSummaryRefCount())

In [ ]:
for attribute, value in srcdb.__dict__.items():
     print(attribute,value)

In [ ]:
for attribute in dir(srcdb):
    print(attribute, getattr(srcdb, attribute))

In [ ]:
print(layer.GetDescription())
print(layer.GetExtent())
print(layer.GetFIDColumn())
#print(layer.GetFeature())
print(layer.GetFeatureCount())
print(layer.GetFeaturesRead())
print(layer.GetGeomType())
print(layer.GetGeometryColumn())
print(layer.GetLayerDefn())
print(layer.GetMetadata())
print(layer.GetMetadataDomainList())
#print(layer.GetMetadataItem())
print(layer.GetMetadata_Dict())
print(layer.GetMetadata_List())
print(layer.GetName())
print(layer.GetNextFeature())
print(layer.GetRefCount())
print(layer.GetSpatialFilter())
print(layer.GetSpatialRef())

In [ ]:
dataSource = ogr.Open("SHP/STATEWIDE/Local_Roads.shp")
daLayer = dataSource.GetLayer(0)
layerDefinition = daLayer.GetLayerDefn()


print ("Name  -  Type  Width  Precision")
for i in range(layerDefinition.GetFieldCount()):
    fieldName =  layerDefinition.GetFieldDefn(i).GetName()
    fieldTypeCode = layerDefinition.GetFieldDefn(i).GetType()
    fieldType = layerDefinition.GetFieldDefn(i).GetFieldTypeName(fieldTypeCode)
    fieldWidth = layerDefinition.GetFieldDefn(i).GetWidth()
    GetPrecision = layerDefinition.GetFieldDefn(i).GetPrecision()

    print (fieldName + " - " + fieldType+ " " + str(fieldWidth) + " " + str(GetPrecision))

In [4]:
import geopandas as gpd

# Define file paths
input_file = "scenic_byways.json"  # Path to the GeoJSON input file
output_file = "scenic_byways.csv"  # Path to the output CSV file

# Load the GeoJSON file into a GeoDataFrame
gdf = gpd.read_file(input_file)

# Reproject the GeoDataFrame to CRS:84 (WGS84)
gdf = gdf.to_crs("EPSG:4326")

# Convert geometries to Well-Known Text (WKT) format
gdf["geometry"] = gdf["geometry"].apply(lambda geom: geom.wkt if geom else None)

# Flatten geometry collections if they exist
if gdf.geometry.iloc[0].startswith("GEOMETRYCOLLECTION"):
    # Explode collections into individual geometries
    gdf = gdf.explode(index_parts=False)

# Save the transformed GeoDataFrame to a CSV file
gdf.to_csv(output_file, index=False)

/tmp/ipykernel_7381/778040610.py:14: UserWarning: Geometry column does not contain geometry.
  gdf["geometry"] = gdf["geometry"].apply(lambda geom: geom.wkt if geom else None)

In [2]:
pip install geopandas

Collecting geopandas
  Using cached geopandas-1.0.1-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: numpy>=1.22 in /home/joe/anaconda3/envs/fire/lib/python3.11/site-packages (from geopandas) (1.26.4)
Collecting pyogrio>=0.7.2 (from geopandas)
  Downloading pyogrio-0.11.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Requirement already satisfied: packaging in /home/joe/anaconda3/envs/fire/lib/python3.11/site-packages (from geopandas) (23.2)
Requirement already satisfied: pandas>=1.4.0 in /home/joe/anaconda3/envs/fire/lib/python3.11/site-packages (from geopandas) (2.2.3)
Requirement already satisfied: pyproj>=3.3.0 in /home/joe/anaconda3/envs/fire/lib/python3.11/site-packages (from geopandas) (3.6.1)
Collecting shapely>=2.0.0 (from geopandas)
  Downloading shapely-2.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/joe/anaconda3/envs/fire/lib/python3.11/site-packages (from pandas>=1.4.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/joe/anaconda3/envs/fire/lib/python3.11/site-packages (from pandas>=1.4.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/joe/anaconda3/envs/fire/lib/python3.11/site-packages (from pandas>=1.4.0->geopandas) (2025.2)
Requirement already satisfied: certifi in /home/joe/anaconda3/envs/fire/lib/python3.11/site-packages (from pyogrio>=0.7.2->geopandas) (2025.1.31)
Requirement already satisfied: six>=1.5 in /home/joe/anaconda3/envs/fire/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->geopandas) (1.17.0)
Using cached geopandas-1.0.1-py3-none-any.whl (323 kB)
Downloading pyogrio-0.11.0-cp311-cp311-manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 23.7 MB/s eta 0:00:0000:0100:01
Downloading shapely-2.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 28.2 MB/s eta 0:00:00
Installing collected packages: shapely, pyogrio, geopandas
Successfully installed geopandas-1.0.1 pyogrio-0.11.0 shapely-2.1.0
Note: you may need to restart the kernel to use updated packages.