In [4]:
import pandas as pd
import csv

## Original Data

In [3]:
df = pd.read_csv("/home/joe/bic_etl/bls/data_source/sm.data.6.Colorado.tsv",sep=r"\t")
df.columns = df.columns.str.strip()
df1 = df.loc[df["series_id"].str.slice(18,20) == "01"]

/tmp/ipykernel_1977/40916781.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv("/home/joe/bic_etl/bls/data_source/sm.data.6.Colorado.tsv",sep=r"\t")

In [ ]:
mt = srs[2:3]
    st = srs[3:5]
    ar = srs[5:10]
    ss = srs[10:12]
    ic = srs[12:18]
    fc = srs[10:18]
    dt = srs[18:]

In [22]:
dfUU = df1.loc[df1["series_id"].str[2:3] == "U"] 
dfSS = df1.loc[df1["series_id"].str[2:3] == "S"] 

#df1['series_id'].str[10:12].value_counts()

In [23]:
print(dfUU.shape)
print(dfSS.shape)

(140526, 5)
(17548, 5)

In [27]:
dfUU['series_id'].str[10:12].unique()

array(['00', '05', '06', '07', '08', '10', '15', '20', '30', '31', '32',
       '40', '41', '42', '43', '50', '55', '60', '65', '70', '80', '90'],
      dtype=object)

In [11]:
df1.loc[df1['series_id'].str[5:10] == '19740']

                             series_id  year period  value footnote_codes
17108   SMS08197400000000001            1990    M01  845.6           None
17109   SMS08197400000000001            1990    M02  847.1           None
17110   SMS08197400000000001            1990    M03  848.5           None
17111   SMS08197400000000001            1990    M04  850.6           None
17112   SMS08197400000000001            1990    M05  856.1           None
...                                ...   ...    ...    ...            ...
132795  SMU08197409093161101            2025    M04   74.7           None
132796  SMU08197409093161101            2025    M05   75.6           None
132797  SMU08197409093161101            2025    M06   75.1           None
132798  SMU08197409093161101            2025    M07   70.6           None
132799  SMU08197409093161101            2025    M08   71.7              P

[30804 rows x 5 columns]

## Transformed Data

In [5]:
dfT = pd.read_csv("/home/joe/bic_etl/bls/data_transformed/sm.data.6.Colorado.employ.tsv",sep=r"\t")

/tmp/ipykernel_1977/2383442145.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  dfT = pd.read_csv("/home/joe/bic_etl/bls/data_transformed/sm.data.6.Colorado.employ.tsv",sep=r"\t")

In [6]:
dfT.head()

,year,month,area,superSector,industry,series,unadjusted,seasonallyAdjusted
0,1939,1,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,217.2,NaN
1,1939,2,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,216.8,NaN
2,1939,3,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,220.1,NaN
3,1939,4,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,224.9,NaN
4,1939,5,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,232.2,NaN

In [12]:
dfT.groupby(['area','superSector'])['year'].agg(['min','max','count'])

                                                 min   max  count
area      superSector
Boulder   Durable Goods                         1990  2025    428
          Education and Health Services         1990  2025    428
          Financial Activities                  1990  2025    428
          Goods Producing                       1990  2025    428
          Government                            1990  2025   2568
...                                              ...   ...    ...
Statewide Total Nonfarm                         1939  2025   1040
          Total Private                         1990  2025    428
          Trade, Transportation, and Utilities  1990  2025    428
          Transportation and Utilities          1990  2025   2996
          Wholesale Trade                       1990  2025   1284

[154 rows x 3 columns]

In [18]:
print(dfT["area"].value_counts())
print(dfT["superSector"].value_counts())
print(dfT["industry"].value_counts())

area
Statewide                 35212
Denver-Aurora-Lakewood    28080
Colorado Springs          14312
Boulder                   11640
Fort Collins              10700
Greeley                   10272
Grand Junction             9844
Pueblo                     9844
Name: count, dtype: int64
superSector
Government                              21400
Professional and Business Services      12528
Leisure and Hospitality                 11088
Education and Health Services            8604
Transportation and Utilities             8132
Financial Activities                     8132
Information                              6680
Retail Trade                             6420
Wholesale Trade                          5136
Other Services                           5136
Total Nonfarm                            4120
Total Private                            3424
Service-Providing                        3424
Goods Producing                          3424
Durable Goods                            3424
Private Service Providing                3424
Manufacturing                            3424
Mining, Logging, and Construction        3424
Trade, Transportation, and Utilities     3424
Construction                             2996
Non-Durable Goods                        1712
Mining and Logging                        428
Name: count, dtype: int64
industry
Total Nonfarm                                      4120
Total Private                                      3424
Goods Producing                                    3424
Service-Providing                                  3424
Private Service Providing                          3424
                                                   ...
Other Amusement and Recreation Industries           428
State Government Excluding Education                428
Local Government excluding Educational Services     428
Offices of Physicians                               284
Business Support Services                           272
Name: count, Length: 83, dtype: int64

In [28]:
dfUU['series_id'].str[10:12].value_counts().sort_index()

series_id
00     4458
05     3704
06     3704
07     3704
08     3704
10      463
15     3704
20     3241
30     3704
31     3704
32     1852
40     3704
41     5556
42     6945
43     8797
50     7226
55     8797
60    13552
65     9307
70    11994
80     5556
90    23150
Name: count, dtype: int64

In [29]:
dfUU.isna().sum()

series_id              0
year                   0
period                 0
value                  0
footnote_codes    140221
dtype: int64

In [75]:
ut = dfUU.loc[(dfUU['series_id'].str[10:12] == "00") & (dfUU['period'].str.strip() != "M13")]

In [34]:
tr = dfT.loc[dfT["superSector"] == "Total Nonfarm"]

In [35]:
tr.shape

(4120, 8)

In [36]:
tr.head()

,year,month,area,superSector,industry,series,unadjusted,seasonallyAdjusted
0,1939,1,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,217.2,NaN
1,1939,2,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,216.8,NaN
2,1939,3,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,220.1,NaN
3,1939,4,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,224.9,NaN
4,1939,5,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,232.2,NaN

In [76]:
ut["series_id"].str[3:].value_counts()

series_id
08000000000000001              1040
08145000000000001               512
08178200000000001               428
08197400000000001               428
08226600000000001               428
08243000000000001               428
08245400000000001               428
08393800000000001               428
Name: count, dtype: int64

In [77]:
ut.head()

                            series_id  year period  value footnote_codes
21373  SMU08000000000000001            1939    M01  217.2           None
21374  SMU08000000000000001            1939    M02  216.8           None
21375  SMU08000000000000001            1939    M03  220.1           None
21376  SMU08000000000000001            1939    M04  224.9           None
21377  SMU08000000000000001            1939    M05  232.2           None

In [40]:
tr["series"].value_counts()

series
8000000000000001    1040
8145000000000001     512
8178200000000001     428
8197400000000001     428
8226600000000001     428
8243000000000001     428
8245400000000001     428
8393800000000001     428
Name: count, dtype: int64

In [59]:
t=tr.loc[tr["series"] == 8393800000000001]

In [45]:
ut.head()

                            series_id  year period  value footnote_codes
21373  SMU08000000000000001            1939    M01  217.2           None
21374  SMU08000000000000001            1939    M02  216.8           None
21375  SMU08000000000000001            1939    M03  220.1           None
21376  SMU08000000000000001            1939    M04  224.9           None
21377  SMU08000000000000001            1939    M05  232.2           None

In [70]:
u=ut.loc[(ut["series_id"].str.strip().isin(["SMU08393800000000001"])) & (ut['period'].str.strip() != 'M13')]

In [74]:
u["series_id"].value_counts().sort_index().to_dict()

{'SMU08393800000000001          ': 428}

In [73]:
ut['period'].value_counts().sort_index().to_dict()

{'M01': 346,
 'M02': 346,
 'M03': 346,
 'M04': 346,
 'M05': 346,
 'M06': 346,
 'M07': 346,
 'M08': 346,
 'M09': 338,
 'M10': 338,
 'M11': 338,
 'M12': 338,
 'M13': 338}

In [57]:
u.head()

                             series_id  year period  value footnote_codes
168314  SMU08393800000000001            1990    M01   41.2           None
168315  SMU08393800000000001            1990    M02   41.7           None
168316  SMU08393800000000001            1990    M03   42.3           None
168317  SMU08393800000000001            1990    M04   43.0           None
168318  SMU08393800000000001            1990    M05   43.5           None

In [58]:
u['year'].value_counts()

year
1990    13
1991    13
1992    13
1993    13
1994    13
1995    13
1996    13
1997    13
1998    13
1999    13
2000    13
2001    13
2002    13
2003    13
2004    13
2005    13
2006    13
2007    13
2008    13
2009    13
2010    13
2011    13
2012    13
2013    13
2014    13
2015    13
2016    13
2017    13
2018    13
2019    13
2020    13
2021    13
2022    13
2023    13
2024    13
2025     8
Name: count, dtype: int64

In [62]:
t['year'].value_counts()

year
1990    12
1991    12
1992    12
1993    12
1994    12
1995    12
1996    12
1997    12
1998    12
1999    12
2000    12
2001    12
2002    12
2003    12
2004    12
2005    12
2006    12
2007    12
2008    12
2009    12
2010    12
2011    12
2012    12
2013    12
2014    12
2015    12
2016    12
2017    12
2018    12
2019    12
2020    12
2021    12
2022    12
2023    12
2024    12
2025     8
Name: count, dtype: int64

In [78]:
dfT.isna().sum()

year                       0
month                      0
area                       0
superSector                0
industry                   0
series                     0
unadjusted                 0
seasonallyAdjusted    112356
dtype: int64

In [79]:
df1.head()

                        series_id  year period   value footnote_codes
0  SMS08000000000000001            1990    M01  1502.2           None
1  SMS08000000000000001            1990    M02  1506.5           None
2  SMS08000000000000001            1990    M03  1510.6           None
3  SMS08000000000000001            1990    M04  1514.3           None
4  SMS08000000000000001            1990    M05  1523.7           None

In [80]:
dfT.head()

,year,month,area,superSector,industry,series,unadjusted,seasonallyAdjusted
0,1939,1,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,217.2,NaN
1,1939,2,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,216.8,NaN
2,1939,3,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,220.1,NaN
3,1939,4,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,224.9,NaN
4,1939,5,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,232.2,NaN

In [87]:
df1.loc[(df1["series_id"].str[2:3] == "S") & (df1['period'].str.strip() != "M13")].count()

series_id         17548
year              17548
period            17548
value             17548
footnote_codes       41
dtype: int64

In [83]:
dfT.head()

,year,month,area,superSector,industry,series,unadjusted,seasonallyAdjusted
0,1939,1,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,217.2,NaN
1,1939,2,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,216.8,NaN
2,1939,3,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,220.1,NaN
3,1939,4,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,224.9,NaN
4,1939,5,Statewide,Total Nonfarm,Total Nonfarm,8000000000000001,232.2,NaN

In [85]:
dfT["seasonallyAdjusted"].count()

np.int64(17548)