In [1]:
import pandas as pd
import csv

In [2]:
df = pd.read_csv("sm.data.6.Colorado",delimiter="\s+")

In [3]:
df.shape

(175923, 5)

In [4]:
df.head()

              series_id  year period   value footnote_codes
0  SMS08000000000000001  1990    M01  1502.2            NaN
1  SMS08000000000000001  1990    M02  1506.5            NaN
2  SMS08000000000000001  1990    M03  1510.6            NaN
3  SMS08000000000000001  1990    M04  1514.3            NaN
4  SMS08000000000000001  1990    M05  1523.7            NaN

In [9]:
dfS = df.loc[df["series_id"].str.slice(2,3) == "S"]
dfU = df.loc[df["series_id"].str.slice(2,3) == "U"]

In [10]:
dfS.shape

(20973, 5)

In [11]:
dfU.shape

(154950, 5)

In [ ]:
print(dfS["series_id"].value_counts())
print(dfU["series_id"].value_counts())

In [22]:
dfS["series_id"].str.slice(18,20).value_counts()

series_id
01    17220
26     3753
Name: count, dtype: int64

In [21]:
dfU["series_id"].str.slice(18,20).value_counts()

series_id
01    137781
02      4194
03      4194
11      4194
07      1529
08      1529
30      1529
Name: count, dtype: int64

In [23]:
dfU.loc[dfU["series_id"].str.slice(19,20) == "30"]

Empty DataFrame
Columns: [series_id, year, period, value, footnote_codes]
Index: []

In [27]:
hist=dfU["series_id"].str.slice(0,19).value_counts().to_dict()

In [ ]:
hist.keys()

In [29]:
dfU.loc[dfU["series_id"].str.slice(0,19) == 'SMU0814500909216110']

                  series_id  year period  value footnote_codes
81424  SMU08145009092161101  1990    M01   10.2            NaN
81425  SMU08145009092161101  1990    M02   11.0            NaN
81426  SMU08145009092161101  1990    M03   11.2            NaN
81427  SMU08145009092161101  1990    M04   10.0            NaN
81428  SMU08145009092161101  1990    M05   10.0            NaN
...                     ...   ...    ...    ...            ...
81873  SMU08145009092161101  2024    M08   19.8            NaN
81874  SMU08145009092161101  2024    M09   22.8            NaN
81875  SMU08145009092161101  2024    M10   22.8            NaN
81876  SMU08145009092161101  2024    M11   23.1            NaN
81877  SMU08145009092161101  2024    M12   22.9              P

[454 rows x 5 columns]

## Colorado Data

In [2]:
fin=open("sm.data.6.Colorado")

linesCol = fin.readlines()

In [27]:
import numpy as np
vars=["01",'02', '03', '11', '07', '08', '30']

count=0
allRecs={}
histColVar={}
histColSer={}
invtCol={}
for line in linesCol[1:]:
    vals = [val.strip() for val in line.split("\t")]
    sbase = vals[0][:18]
    var = vals[0][18:]
    year=int(vals[1])
    month=int(vals[2].lower().strip("m"))
    value=vals[3]
    srs=vals[0]
    if month < 13:
        count+=1
        if srs not in invtCol:
            invtCol[srs]={}
        if year not in invtCol[srs]:
            invtCol[srs][year]={}
        if month not in invtCol[srs][year]:
            invtCol[srs][year][month]=0
        invtCol[srs][year][month]+=1
    
    
        
        if srs not in histColSer:
            histColSer[srs]={}
            histColSer[srs]['count']=0
            histColSer[srs]['startYr']=np.Infinity
            histColSer[srs]['endYr']=-1
            
        histColSer[srs]['count']+=1
        if year < histColSer[srs]['startYr']:
            histColSer[srs]['startYr']=year
        if year > histColSer[srs]['endYr']:
            histColSer[srs]['endYr']=year
        if var in vars:
            if year not in allRecs:
                allRecs[year]={}
            if month not in allRecs[year]:
                allRecs[year][month]={}
            if sbase not in allRecs[year][month]:
                allRecs[year][month][sbase]={}
            allRecs[year][month][sbase][var]=float(value)
        if var not in histColVar:
            histColVar[var]=0
        histColVar[var]+=1
#    print(sbase,var,len(vals[0]),vals[0],year,month,value)

In [4]:
vars=['01']

count=0
allRecs01={}
histColVar01={}
hist01={}
for line in linesCol[1:]:
    vals = [val.strip() for val in line.split("\t")]
    sbase = vals[0][3:19]
    var = vals[0][18:]
    year=int(vals[1])
    month=int(vals[2].lower().strip("m"))
    value=vals[3]
    srs=vals[0]
    us=vals[0][2:3]
    if month < 13:
        count+=1

        if var in vars:
            if srs not in hist01:
                hist01[srs]=0
            hist01[srs]+=1
            if year not in allRecs01:
                allRecs01[year]={}
            if month not in allRecs01[year]:
                allRecs01[year][month]={}
            if sbase not in allRecs01[year][month]:
                allRecs01[year][month][sbase]={}
            allRecs01[year][month][sbase][us]=float(value)
        if us not in histColVar01:
            histColVar01[us]=0
        histColVar01[us]+=1

In [5]:
vars=['26']

count=0
allRecs26={}

for line in linesCol[1:]:
    vals = [val.strip() for val in line.split("\t")]
    sbase = vals[0][3:19]
    var = vals[0][18:]
    year=int(vals[1])
    month=int(vals[2].lower().strip("m"))
    value=vals[3]
    srs=vals[0]
    us=vals[0][2:3]
    if month < 13:
        count+=1

        if var in vars:
            if year not in allRecs26:
                allRecs26[year]={}
            if month not in allRecs26[year]:
                allRecs26[year][month]={}
            
            allRecs26[year][month][sbase]=float(value)

In [6]:
len(histColSer)

424

In [7]:
allRecs[1990][1]['SMU0814500909316110'].keys()

KeyError: 1990

In [8]:
allRecs[1990][1].keys()

KeyError: 1990

## Definitions

In [9]:
fdef = open("sm.series")
lines=fdef.readlines()

In [10]:
len(lines)

23856

In [11]:
histDefs={}
histDates={}
nlines=0
for line in lines[1:]:
    nlines+=1
    spl=line.split("\t")
    spl=[val.strip() for val in spl]
    srs = spl[0]
    var=spl[5]
    tp=spl[6]
    if tp not in histDefs:
        histDefs[tp]={}

    if srs not in histDefs[tp]:
        histDefs[tp][srs]={}
    
    if var not in histDefs[tp][srs]:
        histDefs[tp][srs][var]={}
    histDefs[tp][srs][var]["startYr"]=spl[9]
    histDefs[tp][srs][var]["startMo"]=spl[10].strip("M")
    histDefs[tp][srs][var]["endYr"]=spl[11]
    histDefs[tp][srs][var]["endMo"]=spl[12].strip("M")

    if srs not in histDates:
        histDates[srs]={}
        histDates[srs]["startYr"]=spl[9]   
        histDates[srs]["startMo"]=spl[10].strip("M")
        histDates[srs]["endYr"]=spl[11]
        histDates[srs]["endMo"]=spl[12].strip("M")

In [12]:
summary={}
totl=0
for tp,dct in histDefs.items():
    if tp not in summary:
        summary[tp]={}
    for srs,dct2 in dct.items():
        for var,dct3 in dct2.items():
            s=int(dct3["startYr"])
            e=int(dct3["endYr"])
            ncnt = (e-s+1)*12
            totl+=ncnt
#            print(srs,var,s,e,ncnt)
            if var not in summary[tp]:
                summary[tp][var]=0
            summary[tp][var]+=ncnt

## Analysis

In [ ]:
totl=0
for srs,dct in histColSer.items():
    cnt=dct['count']
    syrC=dct['startYr']
    eyrC=dct['endYr']
    
    totl+=cnt
    if srs in histDates:
        syr=int(histDates[srs]['startYr'])
        eyr=int(histDates[srs]['endYr'])
        icnt=(eyr-syr+1)*12    
        if cnt-icnt != 0:
            print(srs,cnt,icnt,cnt-icnt,syrC,eyrC,syr,eyr)
            for year,inv in sorted(invtCol[srs].items()):
                print(f"{int(year):4d} ",end="")
                for mo in range(1,13):
                    if mo in inv:
                        cc=int(inv[mo])
                    else:
                        cc=0
                    print(f"{cc:3d}",end="")
                print()
                        

print(totl)

In [ ]:
histDates.keys()

## Transform Analysis

In [13]:
dataTypes = pd.read_csv("sm.data_type",delimiter="\t")

In [14]:
dataTypes = dataTypes.set_index('data_type_code')['data_type_text'].to_dict()

In [15]:
allRecs[1990][1]['SMS0800000000000000']

KeyError: 1990

In [28]:
histData={}
histV={}
invtVar={}
invtVarSer={}
for year,dct in allRecs.items():
    for month,dct2 in dct.items():
        for srs,dct3 in dct2.items():
            tp=srs[2:3]
            for var,val in dct3.items():
                ss=f"{srs}{var}"
                if ss not in histData:
                    histData[ss]=0
                histData[ss]+=1

                if tp not in histV:
                    histV[tp]={}
                if var not in histV[tp]:
                    histV[tp][var]=0
                histV[tp][var]+=1

                if var not in invtVar:
                    invtVar[var]={}

                if year not in invtVar[var]:
                    invtVar[var][year]={}
                if month not in invtVar[var][year]:
                    invtVar[var][year][month]=0
                
                invtVar[var][year][month]+=1

                if var not in invtVarSer:
                    invtVarSer[var]={}
                if srs not in invtVarSer[var]:
                    invtVarSer[var][srs]=0
                invtVarSer[var][srs]+=1

In [ ]:
invtVarSer

In [30]:
totl=0
for var,cnt in histColVar.items():
    totl+=cnt

for var,cnt in histColVar.items():
    pp=round(cnt/totl,2)*100
    desc = dataTypes[int(var)]
    print(f"{var:2s}  {pp:4.1f}  {cnt:6d}  {desc}")

01  88.0  144684  All Employees, In Thousands
26   2.0    3753  All Employees, 3-month average change, In Thousands, seasonally adjusted
02   2.0    3888  Average Weekly Hours of All Employees
03   2.0    3888  Average Hourly Earnings of All Employees, In Dollars
11   2.0    3888  Average Weekly Earnings of All Employees, In Dollars
07   1.0    1416  Average Weekly Hours of Production Employees
08   1.0    1416  Average Hourly Earnings of Production Employees, In Dollars
30   1.0    1416  Average Weekly Earnings of Production Employees, In Dollars

In [22]:
tot=0
for tp,dct in histV.items():
    for var,cnt in dct.items():
        tot+=cnt

print("Typ   Var   %     Count  Description")
for tp,dct in histV.items():
    for var,cnt in dct.items():
        pp=round(cnt/tot,2)*100
        desc = dataTypes[int(var)]
        print(f"  {tp:1s}    {var:2s}  {pp:4.1f}  {cnt:6d}  {desc}")

Typ   Var   %     Count  Description
  S    01  10.0   17220  All Employees, In Thousands
  S    26   2.0    3753  All Employees, 3-month average change, In Thousands, seasonally adjusted
  U    01  78.0  127464  All Employees, In Thousands
  U    07   1.0    1416  Average Weekly Hours of Production Employees
  U    08   1.0    1416  Average Hourly Earnings of Production Employees, In Dollars
  U    30   1.0    1416  Average Weekly Earnings of Production Employees, In Dollars
  U    02   2.0    3888  Average Weekly Hours of All Employees
  U    03   2.0    3888  Average Hourly Earnings of All Employees, In Dollars
  U    11   2.0    3888  Average Weekly Earnings of All Employees, In Dollars

In [ ]:
#skip=["01","26"]
skip=["26"]

for var,dct in invtVar.items():
    if var not in skip:
        for year,dct2 in dct.items():
            print(f"{var:.2s}  {year:4d}",end="")
            for month in range(1,13):
                if month in dct2:
                    cnt=dct2[month]
                else:
                    cnt=0
                print(f" {cnt:4d}",end="")
            print()

In [60]:
def decodeSeries(srs):
    mt = srs[2:3]
    st = srs[3:5]
    ar = srs[5:10]
    ss = srs[10:12]
    ic = srs[12:18]
    fc = srs[10:18]
    dt = srs[18:]
    return mt,st,ar,ss,ic,fc,dt

def colsToDict(df,key,val,fmt={}):
    return df.set_index(key)[val].to_dict()

    
defSS = pd.read_csv("sm.supersector",delimiter="\t")
defSS = colsToDict(defSS,"supersector_code","supersector_name")

defFS = pd.read_csv("sm.industry",delimiter="\t",dtype={"industry_code":"str","industry_name":"str"})
defFS = colsToDict(defFS,"industry_code","industry_name")

defAR = pd.read_csv("sm.area",delimiter="\t")
defAR = colsToDict(defAR,"area_code","area_name")

defDT = pd.read_csv("sm.data_type",delimiter="\t")
defDT = colsToDict(defDT,"data_type_code","data_type_text")

hist={}
areas={}
histInd={}
for var,dct in invtVarSer.items():
    for srs,cnt in sorted(dct.items()):
        if var != "01":
            if var not in hist:
               hist[var]={}
            mt,st,ar,ss,ic,fc,dt = decodeSeries(srs)
   #         print(f"{var:2s} {defDT[int(var)]:75s} {defAR[int(ar)]:30s}  {srs:20s} {ss:2s}  {defSS[int(ss)]:20s} {ic:6s} {defFS[fc]:8s} {cnt:5d}")
            area= defAR[int(ar)]
            areas[area]=1
            inds = defFS[fc]
            if inds not in hist[var]:
                hist[var][inds]={}
            hist[var][inds][area]=cnt

            if var not in histInd:
                histInd[var]={}
            if ss not in histInd[var]:
                histInd[var][ss]={}
            if fc not in histInd[var][ss]:
                histInd[var][ss][fc]=0
            histInd[var][ss][fc]+=1

In [63]:
summary={}
for var,dct in histInd.items():
    for ss,dct2 in dct.items():
        if ss not in summary:
            summary[ss]={}
        for ind in dct2.keys():
            if ind not in summary[ss]:
                summary[ss][ind]=0
            summary[ss][ind]+=cnt

for ss,dct in summary.items():
    cnt=len(dct.keys())
    print(f"{cnt:2d}  {defSS[int(ss)]}")

 1  Construction
 1  Manufacturing
 1  Durable Goods
 1  Non-Durable Goods
 1  Total Private
 1  Goods Producing
 1  Private Service Providing
 1  Trade, Transportation, and Utilities
 1  Financial Activities
 1  Professional and Business Services
 1  Education and Health Services
 1  Leisure and Hospitality
 1  Other Services

In [59]:
totl=0
for ind,dct in histInd["01"].items():
    cnt=len(dct.keys())
    print(f"{cnt:2d} {defSS[int(ind)]}")
    totl+=cnt
print(totl)

 1 Total Nonfarm
 1 Total Private
 1 Goods Producing
 1 Service-Providing
 1 Private Service Providing
 1 Mining and Logging
 1 Mining, Logging, and Construction
 4 Construction
 1 Manufacturing
 4 Durable Goods
 2 Non-Durable Goods
 1 Trade, Transportation, and Utilities
 3 Wholesale Trade
 3 Retail Trade
 7 Transportation and Utilities
 4 Information
 6 Financial Activities
11 Professional and Business Services
 8 Education and Health Services
10 Leisure and Hospitality
 4 Other Services
 8 Government
83

In [68]:

allRecs[2020][12]

{'SMS080000000000000': {'01': 2647.9},
 'SMS080000005000000': {'01': 2217.3},
 'SMS080000006000000': {'01': 341.2},
 'SMS080000007000000': {'01': 2306.7},
 'SMS080000008000000': {'01': 1876.1},
 'SMS080000010000000': {'01': 19.4},
 'SMS080000015000000': {'01': 194.3},
 'SMS080000020000000': {'01': 174.9},
 'SMS080000030000000': {'01': 146.9},
 'SMS080000031000000': {'01': 91.2},
 'SMS080000032000000': {'01': 55.7},
 'SMS080000040000000': {'01': 482.8},
 'SMS080000041000000': {'01': 107.6},
 'SMS080000042000000': {'01': 271.4},
 'SMS080000043000000': {'01': 103.8},
 'SMS080000050000000': {'01': 74.4},
 'SMS080000055000000': {'01': 174.9},
 'SMS080000055520000': {'01': 120.2},
 'SMS080000055530000': {'01': 54.7},
 'SMS080000060000000': {'01': 436.2},
 'SMS080000060540000': {'01': 243.0},
 'SMS080000060550000': {'01': 42.1},
 'SMS080000060560000': {'01': 151.1},
 'SMS080000065000000': {'01': 344.9},
 'SMS080000065610000': {'01': 41.4},
 'SMS080000065620000': {'01': 303.5},
 'SMS080000070000000': {'01': 248.3},
 'SMS080000070710000': {'01': 42.5},
 'SMS080000070720000': {'01': 205.8},
 'SMS080000080000000': {'01': 114.6},
 'SMS080000090000000': {'01': 430.6},
 'SMS080000090910000': {'01': 54.5},
 'SMS080000090920000': {'01': 121.4},
 'SMS080000090930000': {'01': 254.7},
 'SMS081450000000000': {'01': 187.9},
 'SMS081782000000000': {'01': 292.8},
 'SMS081974000000000': {'01': 1460.7},
 'SMS082266000000000': {'01': 164.9},
 'SMS082430000000000': {'01': 61.7},
 'SMS082454000000000': {'01': 102.5},
 'SMS083938000000000': {'01': 60.5},
 'SMU080000000000000': {'01': 2665.5},
 'SMU080000005000000': {'01': 2231.8, '02': 33.5, '03': 31.2, '11': 1045.2},
 'SMU080000006000000': {'01': 340.6, '02': 39.4, '03': 33.66, '11': 1326.2},
 'SMU080000007000000': {'01': 2324.9},
 'SMU080000008000000': {'01': 1891.2, '02': 32.4, '03': 30.66, '11': 993.38},
 'SMU080000010000000': {'01': 19.7},
 'SMU080000015000000': {'01': 193.5},
 'SMU080000020000000': {'01': 173.8,
  '02': 38.8,
  '03': 33.18,
  '07': 40.2,
  '08': 29.33,
  '11': 1287.38,
  '30': 1179.07},
 'SMU080000020236000': {'01': 34.8},
 'SMU080000020237000': {'01': 24.2},
 'SMU080000020238000': {'01': 114.8},
 'SMU080000030000000': {'01': 147.1,
  '02': 39.5,
  '03': 31.9,
  '07': 40.9,
  '08': 25.96,
  '11': 1260.05,
  '30': 1061.76},
 'SMU080000031000000': {'01': 91.3, '07': 40.7, '08': 29.95, '30': 1218.97},
 'SMU080000031332000': {'01': 14.5},
 'SMU080000031334000': {'01': 22.9},
 'SMU080000031336000': {'01': 11.5},
 'SMU080000032000000': {'01': 55.8, '07': 41.2, '08': 19.12, '30': 787.74},
 'SMU080000032312100': {'01': 8.1},
 'SMU080000040000000': {'01': 498.5, '02': 32.0, '03': 26.46, '11': 846.72},
 'SMU080000041000000': {'01': 108.0},
 'SMU080000041423000': {'01': 66.4},
 'SMU080000041424000': {'01': 36.5},
 'SMU080000042000000': {'01': 280.0},
 'SMU080000042445000': {'01': 57.0},
 'SMU080000042455000': {'01': 59.7},
 'SMU080000043000000': {'01': 110.5},
 'SMU080000043220000': {'01': 8.3},
 'SMU080000043400089': {'01': 102.2},
 'SMU080000043481000': {'01': 15.3},
 'SMU080000043484000': {'01': 20.3},
 'SMU080000043492000': {'01': 25.7},
 'SMU080000043493000': {'01': 21.6},
 'SMU080000050000000': {'01': 74.4},
 'SMU080000050513000': {'01': 23.2},
 'SMU080000050513200': {'01': 17.6},
 'SMU080000050517000': {'01': 25.7},
 'SMU080000055000000': {'01': 176.3, '02': 36.4, '03': 36.83, '11': 1340.61},
 'SMU080000055520000': {'01': 120.3},
 'SMU080000055522000': {'01': 48.6},
 'SMU080000055524000': {'01': 48.9},
 'SMU080000055530000': {'01': 56.0},
 'SMU080000055531000': {'01': 44.9},
 'SMU080000060000000': {'01': 434.3, '02': 36.3, '03': 36.87, '11': 1338.38},
 'SMU080000060540000': {'01': 243.7},
 'SMU080000060541100': {'01': 20.2},
 'SMU080000060541300': {'01': 51.2},
 'SMU080000060541500': {'01': 69.2},
 'SMU080000060541600': {'01': 36.7},
 'SMU080000060550000': {'01': 42.2},
 'SMU080000060560000': {'01': 148.4},
 'SMU080000060561300': {'01': 43.2},
 'SMU080000060561400': {'01': 19.1},
 'SMU080000060561700': {'01': 42.9},
 'SMU080000065000000': {'01': 346.0, '02': 32.1, '03': 29.8, '11': 956.58},
 'SMU080000065610000': {'01': 41.2},
 'SMU080000065620000': {'01': 304.8},
 'SMU080000065621000': {'01': 144.0},
 'SMU080000065621100': {'01': 39.1},
 'SMU080000065622000': {'01': 59.7},
 'SMU080000065623000': {'01': 42.5},
 'SMU080000065624000': {'01': 58.6},
 'SMU080000070000000': {'01': 248.2, '02': 24.2, '03': 19.63, '11': 475.05},
 'SMU080000070710000': {'01': 44.1},
 'SMU080000070713000': {'01': 36.7},
 'SMU080000070713900': {'01': 34.3},
 'SMU080000070720000': {'01': 204.1},
 'SMU080000070721000': {'01': 32.3},
 'SMU080000070722000': {'01': 171.8},
 'SMU080000070722500': {'01': 162.3},
 'SMU080000070722511': {'01': 64.8},
 'SMU080000070722590': {'01': 97.5},
 'SMU080000080000000': {'01': 113.5, '02': 32.2, '03': 27.87, '11': 897.41},
 'SMU080000080811000': {'01': 25.8},
 'SMU080000080812000': {'01': 26.7},
 'SMU080000080813000': {'01': 61.0},
 'SMU080000090000000': {'01': 433.7},
 'SMU080000090910000': {'01': 54.1},
 'SMU080000090920000': {'01': 125.7},
 'SMU080000090921611': {'01': 72.8},
 'SMU080000090922000': {'01': 52.9},
 'SMU080000090930000': {'01': 253.9},
 'SMU080000090931611': {'01': 131.5},
 'SMU080000090932000': {'01': 122.4},
 'SMU081450000000000': {'01': 188.7},
 'SMU081450005000000': {'01': 153.5, '02': 33.0, '03': 35.15, '11': 1159.95},
 'SMU081450006000000': {'01': 26.1},
 'SMU081450007000000': {'01': 162.6},
 'SMU081450008000000': {'01': 127.4},
 'SMU081450015000000': {'01': 5.6},
 'SMU081450030000000': {'01': 20.5},
 'SMU081450031334000': {'01': 9.0},
 'SMU081450040000000': {'01': 26.2},
 'SMU081450041000000': {'01': 6.5},
 'SMU081450042000000': {'01': 17.4},
 'SMU081450042445000': {'01': 4.6},
 'SMU081450043000000': {'01': 2.3},
 'SMU081450050000000': {'01': 8.7},
 'SMU081450050513000': {'01': 5.4},
 'SMU081450055000000': {'01': 7.4},
 'SMU081450060000000': {'01': 38.5},
 'SMU081450060540000': {'01': 30.4},
 'SMU081450065000000': {'01': 25.4},
 'SMU081450070000000': {'01': 13.6},
 'SMU081450080000000': {'01': 7.6},
 'SMU081450090000000': {'01': 35.2},
 'SMU081450090910000': {'01': 2.0},
 'SMU081450090920000': {'01': 17.9},
 'SMU081450090921611': {'01': 17.0},
 'SMU081450090930000': {'01': 15.3},
 'SMU081450090931611': {'01': 8.6},
 'SMU081782000000000': {'01': 293.9},
 'SMU081782005000000': {'01': 240.3, '02': 32.7, '03': 29.05, '11': 949.94},
 'SMU081782006000000': {'01': 30.6},
 'SMU081782007000000': {'01': 263.3},
 'SMU081782008000000': {'01': 209.7},
 'SMU081782015000000': {'01': 19.1},
 'SMU081782020238000': {'01': 12.0},
 'SMU081782030000000': {'01': 11.5},
 'SMU081782040000000': {'01': 47.0},
 'SMU081782041000000': {'01': 6.2},
 'SMU081782042000000': {'01': 33.4},
 'SMU081782042445000': {'01': 5.8},
 'SMU081782042455000': {'01': 8.1},
 'SMU081782043000000': {'01': 7.4},
 'SMU081782050000000': {'01': 5.2},
 'SMU081782050517000': {'01': 1.3},
 'SMU081782055000000': {'01': 19.5},
 'SMU081782055520000': {'01': 14.2},
 'SMU081782060000000': {'01': 48.5},
 'SMU081782060540000': {'01': 28.9},
 'SMU081782060561300': {'01': 4.2},
 'SMU081782065000000': {'01': 42.4},
 'SMU081782065610000': {'01': 4.5},
 'SMU081782065620000': {'01': 37.9},
 'SMU081782070000000': {'01': 29.0},
 'SMU081782070720000': {'01': 25.1},
 'SMU081782070722000': {'01': 21.1},
 'SMU081782080000000': {'01': 18.1},
 'SMU081782090000000': {'01': 53.6},
 'SMU081782090910000': {'01': 12.5},
 'SMU081782090920000': {'01': 12.7},
 'SMU081782090921611': {'01': 4.6},
 'SMU081782090930000': {'01': 28.4},
 'SMU081782090931611': {'01': 18.4},
 'SMU081974000000000': {'01': 1467.4},
 'SMU081974005000000': {'01': 1270.1, '02': 34.8, '03': 33.36, '11': 1160.93},
 'SMU081974006000000': {'01': 175.7},
 'SMU081974007000000': {'01': 1291.7},
 'SMU081974008000000': {'01': 1094.4},
 'SMU081974015000000': {'01': 106.6},
 'SMU081974020236000': {'01': 18.0},
 'SMU081974020238000': {'01': 66.2},
 'SMU081974030000000': {'01': 69.1, '07': 41.6, '08': 29.48, '30': 1226.37},
 'SMU081974031000000': {'01': 41.9},
 'SMU081974031334000': {'01': 6.3},
 'SMU081974031336000': {'01': 9.0},
 'SMU081974032000000': {'01': 27.2},
 'SMU081974040000000': {'01': 292.4},
 'SMU081974041000000': {'01': 72.6},
 'SMU081974041423000': {'01': 46.6},
 'SMU081974041424000': {'01': 22.8},
 'SMU081974042000000': {'01': 142.7},
 'SMU081974042445000': {'01': 28.9},
 'SMU081974042455000': {'01': 31.0},
 'SMU081974043000000': {'01': 77.1},
 'SMU081974043220000': {'01': 3.9},
 'SMU081974043400089': {'01': 73.2},
 'SMU081974043481000': {'01': 14.6},
 'SMU081974043492000': {'01': 18.0},
 'SMU081974043493000': {'01': 16.3},
 'SMU081974050000000': {'01': 51.3},
 'SMU081974050513000': {'01': 12.7},
 'SMU081974050513200': {'01': 10.7},
 'SMU081974050517000': {'01': 18.7},
 'SMU081974055000000': {'01': 113.6},
 'SMU081974055520000': {'01': 82.1},
 'SMU081974055522000': {'01': 31.7},
 'SMU081974055524000': {'01': 32.7},
 'SMU081974055530000': {'01': 31.5},
 'SMU081974055531000': {'01': 25.2},
 'SMU081974060000000': {'01': 276.2},
 'SMU081974060540000': {'01': 151.4},
 'SMU081974060541300': {'01': 31.7},
 'SMU081974060541500': {'01': 42.4},
 'SMU081974060541600': {'01': 24.6},
 'SMU081974060550000': {'01': 33.9},
 'SMU081974060560000': {'01': 90.9},
 'SMU081974060561300': {'01': 28.4},
 'SMU081974060561700': {'01': 25.3},
 'SMU081974065000000': {'01': 190.4},
 'SMU081974065610000': {'01': 26.8},
 'SMU081974065620000': {'01': 163.6},
 'SMU081974065621000': {'01': 78.6},
 'SMU081974065622000': {'01': 32.0},
 'SMU081974070000000': {'01': 114.3},
 'SMU081974070710000': {'01': 16.8},
 'SMU081974070720000': {'01': 97.5},
 'SMU081974070721000': {'01': 10.1},
 'SMU081974070722000': {'01': 87.4},
 'SMU081974070722500': {'01': 82.5},
 'SMU081974070722511': {'01': 31.4},
 'SMU081974070722590': {'01': 51.1},
 'SMU081974080000000': {'01': 56.2},
 'SMU081974080811000': {'01': 13.5},
 'SMU081974090000000': {'01': 197.3},
 'SMU081974090910000': {'01': 28.9},
 'SMU081974090920000': {'01': 47.0},
 'SMU081974090921611': {'01': 25.8},
 'SMU081974090930000': {'01': 121.4},
 'SMU081974090931611': {'01': 64.5},
 'SMU082266000000000': {'01': 165.1},
 'SMU082266005000000': {'01': 124.5, '02': 32.3, '03': 29.19, '11': 942.84},
 'SMU082266006000000': {'01': 25.7},
 'SMU082266007000000': {'01': 139.4},
 'SMU082266008000000': {'01': 98.8},
 'SMU082266015000000': {'01': 11.7},
 'SMU082266030000000': {'01': 14.0},
 'SMU082266040000000': {'01': 29.7},
 'SMU082266041000000': {'01': 5.3},
 'SMU082266042000000': {'01': 19.7},
 'SMU082266043000000': {'01': 4.7},
 'SMU082266050000000': {'01': 2.8},
 'SMU082266055000000': {'01': 7.0},
 'SMU082266060000000': {'01': 19.9},
 'SMU082266060560000': {'01': 7.7},
 'SMU082266065000000': {'01': 18.5},
 'SMU082266070000000': {'01': 14.2},
 'SMU082266070720000': {'01': 12.6},
 'SMU082266080000000': {'01': 6.7},
 'SMU082266090000000': {'01': 40.6},
 'SMU082266090910000': {'01': 2.5},
 'SMU082266090920000': {'01': 24.0},
 'SMU082266090921611': {'01': 15.2},
 'SMU082266090930000': {'01': 14.1},
 'SMU082266090931611': {'01': 6.9},
 'SMU082430000000000': {'01': 61.9},
 'SMU082430005000000': {'01': 51.6, '02': 32.7, '03': 24.75, '11': 809.33},
 'SMU082430006000000': {'01': 8.8},
 'SMU082430007000000': {'01': 53.1},
 'SMU082430008000000': {'01': 42.8},
 'SMU082430015000000': {'01': 5.7},
 'SMU082430030000000': {'01': 3.1},
 'SMU082430040000000': {'01': 13.5},
 'SMU082430041000000': {'01': 2.2},
 'SMU082430042000000': {'01': 8.6},
 'SMU082430043000000': {'01': 2.7},
 'SMU082430050000000': {'01': 0.5},
 'SMU082430055000000': {'01': 3.2},
 'SMU082430060000000': {'01': 4.8},
 'SMU082430065000000': {'01': 11.9},
 'SMU082430070000000': {'01': 6.6},
 'SMU082430080000000': {'01': 2.3},
 'SMU082430090000000': {'01': 10.3},
 'SMU082430090910000': {'01': 1.8},
 'SMU082430090920000': {'01': 2.6},
 'SMU082430090921611': {'01': 1.6},
 'SMU082430090930000': {'01': 5.9},
 'SMU082430090931611': {'01': 3.4},
 'SMU082454000000000': {'01': 102.4},
 'SMU082454005000000': {'01': 85.7, '02': 35.5, '03': 30.84, '11': 1094.82},
 'SMU082454006000000': {'01': 29.1},
 'SMU082454007000000': {'01': 73.3},
 'SMU082454008000000': {'01': 56.6},
 'SMU082454015000000': {'01': 15.3},
 'SMU082454030000000': {'01': 13.8},
 'SMU082454032000000': {'01': 7.0},
 'SMU082454040000000': {'01': 19.4},
 'SMU082454041000000': {'01': 4.2},
 'SMU082454042000000': {'01': 11.0},
 'SMU082454043000000': {'01': 4.2},
 'SMU082454050000000': {'01': 0.5},
 'SMU082454055000000': {'01': 4.4},
 'SMU082454060000000': {'01': 10.7},
 'SMU082454065000000': {'01': 10.7},
 'SMU082454070000000': {'01': 7.6},
 'SMU082454080000000': {'01': 3.3},
 'SMU082454090000000': {'01': 16.7},
 'SMU082454090910000': {'01': 0.6},
 'SMU082454090920000': {'01': 4.0},
 'SMU082454090921611': {'01': 3.0},
 'SMU082454090930000': {'01': 12.1},
 'SMU082454090931611': {'01': 6.9},
 'SMU083938000000000': {'01': 60.8},
 'SMU083938005000000': {'01': 48.7, '02': 32.9, '03': 24.75, '11': 814.28},
 'SMU083938006000000': {'01': 7.9},
 'SMU083938007000000': {'01': 52.9},
 'SMU083938008000000': {'01': 40.8},
 'SMU083938015000000': {'01': 3.6},
 'SMU083938030000000': {'01': 4.3},
 'SMU083938040000000': {'01': 12.3},
 'SMU083938041000000': {'01': 1.5},
 'SMU083938042000000': {'01': 8.2},
 'SMU083938043000000': {'01': 2.6},
 'SMU083938050000000': {'01': 0.4},
 'SMU083938055000000': {'01': 1.8},
 'SMU083938060000000': {'01': 6.4},
 'SMU083938065000000': {'01': 12.9},
 'SMU083938070000000': {'01': 4.9},
 'SMU083938080000000': {'01': 2.1},
 'SMU083938090000000': {'01': 12.1},
 'SMU083938090910000': {'01': 1.1},
 'SMU083938090920000': {'01': 4.7},
 'SMU083938090921611': {'01': 1.8},
 'SMU083938090930000': {'01': 6.3},
 'SMU083938090931611': {'01': 3.5}}

In [57]:
print(defSS[65])
cnt=0
for ind in histInd["01"]["65"].keys():
    cnt+=1
    print(f"   {cnt}) {defFS[ind]}")

Education and Health Services
   1) Private Education and Health Services
   2) Private Educational Services
   3) Health Care and Social Assistance
   4) Ambulatory Health Care Services
   5) Offices of Physicians
   6) Hospitals
   7) Nursing and Residential Care Facilities
   8) Social Assistance

In [18]:
def decodeSeries(srs):
    mt = srs[2:3]
    st = srs[3:5]
    ar = srs[5:10]
    ss = srs[10:12]
    ic = srs[12:18]
    fc = srs[10:18]
    dt = srs[18:]
    return mt,st,ar,ss,ic,fc,dt

def colsToDict(df,key,val,fmt={}):
    return df.set_index(key)[val].to_dict()

    
defSS = pd.read_csv("sm.supersector",delimiter="\t")
defSS = colsToDict(defSS,"supersector_code","supersector_name")

defFS = pd.read_csv("sm.industry",delimiter="\t",dtype={"industry_code":"str","industry_name":"str"})
defFS = colsToDict(defFS,"industry_code","industry_name")

defAR = pd.read_csv("sm.area",delimiter="\t")
defAR = colsToDict(defAR,"area_code","area_name")

defDT = pd.read_csv("sm.data_type",delimiter="\t")
defDT = colsToDict(defDT,"data_type_code","data_type_text")

hist={}
areas={}
for var,dct in invtVarSer.items():
    for srs,cnt in sorted(dct.items()):
        if var != "01":
            if var not in hist:
               hist[var]={}
            mt,st,ar,ss,ic,fc,dt = decodeSeries(srs)
            print(f"{var:2s} {defDT[int(var)]:75s} {defAR[int(ar)]:30s}  {srs:20s} {ss:2s}  {defSS[int(ss)]:20s} {ic:6s} {defFS[fc]:8s} {cnt:5d}")
            area= defAR[int(ar)]
            areas[area]=1
            inds = defFS[fc]
            if inds not in hist[var]:
                hist[var][inds]={}
            hist[var][inds][area]=cnt

02 Average Weekly Hours of All Employees                                       Statewide                       SMU080000005000000   05  Total Private        000000 Total Private   216
02 Average Weekly Hours of All Employees                                       Statewide                       SMU080000006000000   06  Goods Producing      000000 Goods Producing   216
02 Average Weekly Hours of All Employees                                       Statewide                       SMU080000008000000   08  Private Service Providing 000000 Private Service Providing   216
02 Average Weekly Hours of All Employees                                       Statewide                       SMU080000020000000   20  Construction         000000 Construction   216
02 Average Weekly Hours of All Employees                                       Statewide                       SMU080000030000000   30  Manufacturing        000000 Manufacturing   216
02 Average Weekly Hours of All Employees                                       Statewide                       SMU080000040000000   40  Trade, Transportation, and Utilities 000000 Trade, Transportation, and Utilities   216
02 Average Weekly Hours of All Employees                                       Statewide                       SMU080000055000000   55  Financial Activities 000000 Financial Activities   216
02 Average Weekly Hours of All Employees                                       Statewide                       SMU080000060000000   60  Professional and Business Services 000000 Professional and Business Services   216
02 Average Weekly Hours of All Employees                                       Statewide                       SMU080000065000000   65  Education and Health Services 000000 Private Education and Health Services   216
02 Average Weekly Hours of All Employees                                       Statewide                       SMU080000070000000   70  Leisure and Hospitality 000000 Leisure and Hospitality   216
02 Average Weekly Hours of All Employees                                       Statewide                       SMU080000080000000   80  Other Services       000000 Other Services   216
02 Average Weekly Hours of All Employees                                       Boulder, CO                     SMU081450005000000   05  Total Private        000000 Total Private   216
02 Average Weekly Hours of All Employees                                       Colorado Springs, CO            SMU081782005000000   05  Total Private        000000 Total Private   216
02 Average Weekly Hours of All Employees                                       Denver-Aurora-Lakewood, CO      SMU081974005000000   05  Total Private        000000 Total Private   216
02 Average Weekly Hours of All Employees                                       Fort Collins, CO                SMU082266005000000   05  Total Private        000000 Total Private   216
02 Average Weekly Hours of All Employees                                       Grand Junction, CO              SMU082430005000000   05  Total Private        000000 Total Private   216
02 Average Weekly Hours of All Employees                                       Greeley, CO                     SMU082454005000000   05  Total Private        000000 Total Private   216
02 Average Weekly Hours of All Employees                                       Pueblo, CO                      SMU083938005000000   05  Total Private        000000 Total Private   216
03 Average Hourly Earnings of All Employees, In Dollars                        Statewide                       SMU080000005000000   05  Total Private        000000 Total Private   216
03 Average Hourly Earnings of All Employees, In Dollars                        Statewide                       SMU080000006000000   06  Goods Producing      000000 Goods Producing   216
03 Average Hourly Earnings of All Employees, In Dollars                        Statewide                       SMU080000008000000   08  Private Service Providing 000000 Private Service Providing   216
03 Average Hourly Earnings of All Employees, In Dollars                        Statewide                       SMU080000020000000   20  Construction         000000 Construction   216
03 Average Hourly Earnings of All Employees, In Dollars                        Statewide                       SMU080000030000000   30  Manufacturing        000000 Manufacturing   216
03 Average Hourly Earnings of All Employees, In Dollars                        Statewide                       SMU080000040000000   40  Trade, Transportation, and Utilities 000000 Trade, Transportation, and Utilities   216
03 Average Hourly Earnings of All Employees, In Dollars                        Statewide                       SMU080000055000000   55  Financial Activities 000000 Financial Activities   216
03 Average Hourly Earnings of All Employees, In Dollars                        Statewide                       SMU080000060000000   60  Professional and Business Services 000000 Professional and Business Services   216
03 Average Hourly Earnings of All Employees, In Dollars                        Statewide                       SMU080000065000000   65  Education and Health Services 000000 Private Education and Health Services   216
03 Average Hourly Earnings of All Employees, In Dollars                        Statewide                       SMU080000070000000   70  Leisure and Hospitality 000000 Leisure and Hospitality   216
03 Average Hourly Earnings of All Employees, In Dollars                        Statewide                       SMU080000080000000   80  Other Services       000000 Other Services   216
03 Average Hourly Earnings of All Employees, In Dollars                        Boulder, CO                     SMU081450005000000   05  Total Private        000000 Total Private   216
03 Average Hourly Earnings of All Employees, In Dollars                        Colorado Springs, CO            SMU081782005000000   05  Total Private        000000 Total Private   216
03 Average Hourly Earnings of All Employees, In Dollars                        Denver-Aurora-Lakewood, CO      SMU081974005000000   05  Total Private        000000 Total Private   216
03 Average Hourly Earnings of All Employees, In Dollars                        Fort Collins, CO                SMU082266005000000   05  Total Private        000000 Total Private   216
03 Average Hourly Earnings of All Employees, In Dollars                        Grand Junction, CO              SMU082430005000000   05  Total Private        000000 Total Private   216
03 Average Hourly Earnings of All Employees, In Dollars                        Greeley, CO                     SMU082454005000000   05  Total Private        000000 Total Private   216
03 Average Hourly Earnings of All Employees, In Dollars                        Pueblo, CO                      SMU083938005000000   05  Total Private        000000 Total Private   216
11 Average Weekly Earnings of All Employees, In Dollars                        Statewide                       SMU080000005000000   05  Total Private        000000 Total Private   216
11 Average Weekly Earnings of All Employees, In Dollars                        Statewide                       SMU080000006000000   06  Goods Producing      000000 Goods Producing   216
11 Average Weekly Earnings of All Employees, In Dollars                        Statewide                       SMU080000008000000   08  Private Service Providing 000000 Private Service Providing   216
11 Average Weekly Earnings of All Employees, In Dollars                        Statewide                       SMU080000020000000   20  Construction         000000 Construction   216
11 Average Weekly Earnings of All Employees, In Dollars                        Statewide                       SMU080000030000000   30  Manufacturing        000000 Manufacturing   216
11 Average Weekly Earnings of All Employees, In Dollars                        Statewide                       SMU080000040000000   40  Trade, Transportation, and Utilities 000000 Trade, Transportation, and Utilities   216
11 Average Weekly Earnings of All Employees, In Dollars                        Statewide                       SMU080000055000000   55  Financial Activities 000000 Financial Activities   216
11 Average Weekly Earnings of All Employees, In Dollars                        Statewide                       SMU080000060000000   60  Professional and Business Services 000000 Professional and Business Services   216
11 Average Weekly Earnings of All Employees, In Dollars                        Statewide                       SMU080000065000000   65  Education and Health Services 000000 Private Education and Health Services   216
11 Average Weekly Earnings of All Employees, In Dollars                        Statewide                       SMU080000070000000   70  Leisure and Hospitality 000000 Leisure and Hospitality   216
11 Average Weekly Earnings of All Employees, In Dollars                        Statewide                       SMU080000080000000   80  Other Services       000000 Other Services   216
11 Average Weekly Earnings of All Employees, In Dollars                        Boulder, CO                     SMU081450005000000   05  Total Private        000000 Total Private   216
11 Average Weekly Earnings of All Employees, In Dollars                        Colorado Springs, CO            SMU081782005000000   05  Total Private        000000 Total Private   216
11 Average Weekly Earnings of All Employees, In Dollars                        Denver-Aurora-Lakewood, CO      SMU081974005000000   05  Total Private        000000 Total Private   216
11 Average Weekly Earnings of All Employees, In Dollars                        Fort Collins, CO                SMU082266005000000   05  Total Private        000000 Total Private   216
11 Average Weekly Earnings of All Employees, In Dollars                        Grand Junction, CO              SMU082430005000000   05  Total Private        000000 Total Private   216
11 Average Weekly Earnings of All Employees, In Dollars                        Greeley, CO                     SMU082454005000000   05  Total Private        000000 Total Private   216
11 Average Weekly Earnings of All Employees, In Dollars                        Pueblo, CO                      SMU083938005000000   05  Total Private        000000 Total Private   216
07 Average Weekly Hours of Production Employees                                Statewide                       SMU080000020000000   20  Construction         000000 Construction   288
07 Average Weekly Hours of Production Employees                                Statewide                       SMU080000030000000   30  Manufacturing        000000 Manufacturing   288
07 Average Weekly Hours of Production Employees                                Statewide                       SMU080000031000000   31  Durable Goods        000000 Durable Goods   288
07 Average Weekly Hours of Production Employees                                Statewide                       SMU080000032000000   32  Non-Durable Goods    000000 Non-Durable Goods   288
07 Average Weekly Hours of Production Employees                                Denver-Aurora-Lakewood, CO      SMU081974030000000   30  Manufacturing        000000 Manufacturing   264
08 Average Hourly Earnings of Production Employees, In Dollars                 Statewide                       SMU080000020000000   20  Construction         000000 Construction   288
08 Average Hourly Earnings of Production Employees, In Dollars                 Statewide                       SMU080000030000000   30  Manufacturing        000000 Manufacturing   288
08 Average Hourly Earnings of Production Employees, In Dollars                 Statewide                       SMU080000031000000   31  Durable Goods        000000 Durable Goods   288
08 Average Hourly Earnings of Production Employees, In Dollars                 Statewide                       SMU080000032000000   32  Non-Durable Goods    000000 Non-Durable Goods   288
08 Average Hourly Earnings of Production Employees, In Dollars                 Denver-Aurora-Lakewood, CO      SMU081974030000000   30  Manufacturing        000000 Manufacturing   264
30 Average Weekly Earnings of Production Employees, In Dollars                 Statewide                       SMU080000020000000   20  Construction         000000 Construction   288
30 Average Weekly Earnings of Production Employees, In Dollars                 Statewide                       SMU080000030000000   30  Manufacturing        000000 Manufacturing   288
30 Average Weekly Earnings of Production Employees, In Dollars                 Statewide                       SMU080000031000000   31  Durable Goods        000000 Durable Goods   288
30 Average Weekly Earnings of Production Employees, In Dollars                 Statewide                       SMU080000032000000   32  Non-Durable Goods    000000 Non-Durable Goods   288
30 Average Weekly Earnings of Production Employees, In Dollars                 Denver-Aurora-Lakewood, CO      SMU081974030000000   30  Manufacturing        000000 Manufacturing   264

In [19]:
areasMap={'Statewide': ' SW',
 'Boulder, CO': ' BL',
 'Colorado Springs, CO':' CS',
 'Denver-Aurora-Lakewood, CO': 'DAL',
 'Fort Collins, CO': ' FC',
 'Grand Junction, CO': ' GJ',
 'Greeley, CO': ' GR',
 'Pueblo, CO': ' PU'}

In [31]:
print("VV   Industry                              ",end="")
for ar in areas.keys():
    print(f"  {ar:3s}",end="")
print()
for var,dct in sorted(hist.items()):
    totl=0
    for ind,dct2 in sorted(dct.items()):
        print(f"{var:2s} {ind:40s}",end="")      
        for ar in areas:                 
            if ar in dct2:
                cnt=str(dct2[ar])
                totl+=int(cnt)
            else:
                cnt=""
            print(f" {cnt:4s}",end="")
        print(f"   {defDT[int(var)]}")
    print(f"
#        print()
    print()

VV   Industry                                Statewide  Boulder, CO  Colorado Springs, CO  Denver-Aurora-Lakewood, CO  Fort Collins, CO  Grand Junction, CO  Greeley, CO  Pueblo, CO
02 Construction                             216                                       Average Weekly Hours of All Employees
02 Financial Activities                     216                                       Average Weekly Hours of All Employees
02 Goods Producing                          216                                       Average Weekly Hours of All Employees
02 Leisure and Hospitality                  216                                       Average Weekly Hours of All Employees
02 Manufacturing                            216                                       Average Weekly Hours of All Employees
02 Other Services                           216                                       Average Weekly Hours of All Employees
02 Private Education and Health Services    216                                       Average Weekly Hours of All Employees
02 Private Service Providing                216                                       Average Weekly Hours of All Employees
02 Professional and Business Services       216                                       Average Weekly Hours of All Employees
02 Total Private                            216  216  216  216  216  216  216  216    Average Weekly Hours of All Employees
02 Trade, Transportation, and Utilities     216                                       Average Weekly Hours of All Employees

03 Construction                             216                                       Average Hourly Earnings of All Employees, In Dollars
03 Financial Activities                     216                                       Average Hourly Earnings of All Employees, In Dollars
03 Goods Producing                          216                                       Average Hourly Earnings of All Employees, In Dollars
03 Leisure and Hospitality                  216                                       Average Hourly Earnings of All Employees, In Dollars
03 Manufacturing                            216                                       Average Hourly Earnings of All Employees, In Dollars
03 Other Services                           216                                       Average Hourly Earnings of All Employees, In Dollars
03 Private Education and Health Services    216                                       Average Hourly Earnings of All Employees, In Dollars
03 Private Service Providing                216                                       Average Hourly Earnings of All Employees, In Dollars
03 Professional and Business Services       216                                       Average Hourly Earnings of All Employees, In Dollars
03 Total Private                            216  216  216  216  216  216  216  216    Average Hourly Earnings of All Employees, In Dollars
03 Trade, Transportation, and Utilities     216                                       Average Hourly Earnings of All Employees, In Dollars

07 Construction                             288                                       Average Weekly Hours of Production Employees
07 Durable Goods                            288                                       Average Weekly Hours of Production Employees
07 Manufacturing                            288            264                        Average Weekly Hours of Production Employees
07 Non-Durable Goods                        288                                       Average Weekly Hours of Production Employees

08 Construction                             288                                       Average Hourly Earnings of Production Employees, In Dollars
08 Durable Goods                            288                                       Average Hourly Earnings of Production Employees, In Dollars
08 Manufacturing                            288            264                        Average Hourly Earnings of Production Employees, In Dollars
08 Non-Durable Goods                        288                                       Average Hourly Earnings of Production Employees, In Dollars

11 Construction                             216                                       Average Weekly Earnings of All Employees, In Dollars
11 Financial Activities                     216                                       Average Weekly Earnings of All Employees, In Dollars
11 Goods Producing                          216                                       Average Weekly Earnings of All Employees, In Dollars
11 Leisure and Hospitality                  216                                       Average Weekly Earnings of All Employees, In Dollars
11 Manufacturing                            216                                       Average Weekly Earnings of All Employees, In Dollars
11 Other Services                           216                                       Average Weekly Earnings of All Employees, In Dollars
11 Private Education and Health Services    216                                       Average Weekly Earnings of All Employees, In Dollars
11 Private Service Providing                216                                       Average Weekly Earnings of All Employees, In Dollars
11 Professional and Business Services       216                                       Average Weekly Earnings of All Employees, In Dollars
11 Total Private                            216  216  216  216  216  216  216  216    Average Weekly Earnings of All Employees, In Dollars
11 Trade, Transportation, and Utilities     216                                       Average Weekly Earnings of All Employees, In Dollars

26 Total Nonfarm                            417  417  417  417  417  417  417  417    All Employees, 3-month average change, In Thousands, seasonally adjusted
26 Total Private                            417                                       All Employees, 3-month average change, In Thousands, seasonally adjusted

30 Construction                             288                                       Average Weekly Earnings of Production Employees, In Dollars
30 Durable Goods                            288                                       Average Weekly Earnings of Production Employees, In Dollars
30 Manufacturing                            288            264                        Average Weekly Earnings of Production Employees, In Dollars
30 Non-Durable Goods                        288                                       Average Weekly Earnings of Production Employees, In Dollars

          1 
01234567890123456789
SMU01266207072200001

Characters   Definition
 0 -  1       Dataset Code 
 2 -  2       Measurment Type   U = Unadjusted  S = Seasonal Average removed
 3 -  4       State Code  
 5 -  9       Area Code
10 - 11       Super Sector Code
12 - 17       Industry Code (NAICS?)
18 - 19       Data Type Code

In [16]:
srs

'SMU0839380050000001'

In [24]:
mt = srs[2:3]
st = srs[3:5]
ar = srs[5:10]
ss = srs[10:12]
ic = srs[12:18]
fc = srs[10:18]
dt = srs[18:]
print(mt,st,ar,ss,ic,dt)

U 08 39380 05 000000 1

In [133]:

def colsToDict(df,key,val,fmt={}):
    return df.set_index(key)[val].to_dict()
    
defSS = pd.read_csv("sm.supersector",delimiter="\t")
defSS = colsToDict(defSS,"supersector_code","supersector_name")

defFS = pd.read_csv("sm.industry",delimiter="\t",dtype={"industry_code":"str","industry_name":"str"})
defFS = colsToDict(defFS,"industry_code","industry_name")

defAR = pd.read_csv("sm.area",delimiter="\t")
defAR = colsToDict(defAR,"area_code","area_name")

defDT = pd.read_csv("sm.data_type",delimiter="\t")
defDT = colsToDict(defDT,"data_type_code","data_type_text")

In [134]:
defDT

{1: 'All Employees, In Thousands',
 2: 'Average Weekly Hours of All Employees',
 3: 'Average Hourly Earnings of All Employees, In Dollars',
 6: 'Production or Nonsupervisory Employees, In Thousands',
 7: 'Average Weekly Hours of Production Employees',
 8: 'Average Hourly Earnings of Production Employees, In Dollars',
 11: 'Average Weekly Earnings of All Employees, In Dollars',
 21: 'Diffusion Indexes, 1-month span, seasonally adjusted, total nonfarm',
 22: 'Diffusion Indexes, 3-month span, seasonally adjusted, total nonfarm',
 23: 'Diffusion Indexes, 6-month span, seasonally adjusted, total nonfarm',
 24: 'Diffusion Indexes, 12-month span, seasonally adjusted, total nonfarm',
 26: 'All Employees, 3-month average change, In Thousands, seasonally adjusted',
 30: 'Average Weekly Earnings of Production Employees, In Dollars'}

In [31]:

print(defSS)

{0: 'Total Nonfarm', 5: 'Total Private', 6: 'Goods Producing', 7: 'Service-Providing', 8: 'Private Service Providing', 10: 'Mining and Logging', 15: 'Mining, Logging, and Construction', 20: 'Construction', 30: 'Manufacturing', 31: 'Durable Goods', 32: 'Non-Durable Goods', 40: 'Trade, Transportation, and Utilities', 41: 'Wholesale Trade', 42: 'Retail Trade', 43: 'Transportation and Utilities', 50: 'Information', 55: 'Financial Activities', 60: 'Professional and Business Services', 65: 'Education and Health Services', 70: 'Leisure and Hospitality', 80: 'Other Services', 90: 'Government'}

In [11]:
histColVar.keys()

dict_keys(['01', '26', '02', '03', '11', '07', '08', '30'])

In [8]:
allRecs[1990].keys()

dict_keys([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

## Transform Final

In [104]:
def decodeSeriesNoDt(srs):
    mt = srs[2:3]
    st = srs[3:5]
    ar = srs[5:10]
    ss = srs[10:12]
    ic = srs[12:18]
    fc = srs[10:18]
    return mt,st,ar,ss,ic,fc

some={}
vars=['02', '03', '11', '07', '08', '30']
dlm="\t"
fout=open("test.csv","w")
fout.write("year\tmonth\tarea\tindustry\tseries\t2\t3\t11\t7\t8\t30\n")
for year,dct in allRecs.items():
    for month,dct2 in dct.items():
        for srs,dct3 in dct2.items():
            if srs not in some:
                some[srs]=0
            some[srs]+=1
           
            mt,st,ar,ss,ic,fc = decodeSeriesNoDt(srs)
            susc = defSS[int(ss)]
            inc = defFS[fc]
            area=defAR[int(ar)].rstrip(", CO")
            string=f"{year}\t{month}\t{area}\t{inc}\t{srs:18s}\t"
            for var in vars:
                if var in dct3:
                   val=dct3[var]
                else:
                   val=""
                string+=f"{val}\t"
            string=string.rstrip("\t")
            fout.write(f"{string}\n")
fout.close()

In [136]:
for var in ['02', '03', '11', '07', '08', '30']:
    print(var,defDT[int(var)])

02 Average Weekly Hours of All Employees
03 Average Hourly Earnings of All Employees, In Dollars
11 Average Weekly Earnings of All Employees, In Dollars
07 Average Weekly Hours of Production Employees
08 Average Hourly Earnings of Production Employees, In Dollars
30 Average Weekly Earnings of Production Employees, In Dollars

In [106]:
df = pd.read_csv("test.csv",delimiter="\t")

In [107]:
df.head()

,year,month,area,industry,series,2,3,11,7,8,30
0,2007,1,Statewide,Total Private,SMU080000005000000,34.2,22.66,774.97,NaN,NaN,NaN
1,2007,1,Statewide,Goods Producing,SMU080000006000000,37.7,24.99,942.12,NaN,NaN,NaN
2,2007,1,Statewide,Private Service Providing,SMU080000008000000,33.5,22.13,741.36,NaN,NaN,NaN
3,2007,1,Statewide,Construction,SMU080000020000000,37.0,22.77,842.49,36.7,20.58,755.29
4,2007,1,Statewide,Manufacturing,SMU080000030000000,37.7,26.59,1002.44,38.3,17.05,653.02

In [ ]:
def decodeSeriesNoDt(srs):
    mt = srs[2:3]
    st = srs[3:5]
    ar = srs[5:10]
    ss = srs[10:12]
    ic = srs[12:18]
    fc = srs[10:18]
    return mt,st,ar,ss,ic,fc


fin=open("sm.data.6.Colorado")
lines=fin.readlines()
nhit=0
summary={}
hist={}
for nn,line in enumerate(lines[1:]):
    var=line[18:20]
 
    if var != "01" and var != "26":
        nhit+=1
        if nhit > 0:
            
            srs=line[:20]
            base=line[:18]
            mt,st,ar,ss,ic,fc=decodeSeriesNoDt(base)
        
            spl=line.split("\t")
            year=int(spl[1])
            mo=int(spl[2].strip("M"))
            susc = defSS[int(ss)]
            inc = defFS[fc]
            area=defAR[int(ar)].rstrip(", CO")
            if susc != inc:
                print(year,mo,area,susc,":",inc)
            
            if mo != 13:
                val=float(spl[3])
         #       print(year,mo,var,srs,val)
                
                aval=df.loc[(df["year"] == year) & (df["month"] == mo) & (df["series"] == base),f"{str(int(var))}"].values[0]
                if val != aval:
                    print("BAD ",year,mo,var,val,avar)
                else:
                    if var not in summary:
                        summary[var]=0
                    summary[var]+=1

In [113]:
hist

{'Total Private': 5592,
 'Goods Producing': 699,
 'Private Service Providing': 699,
 'Construction': 1632,
 'Manufacturing': 2487,
 'Durable Goods': 933,
 'Non-Durable Goods': 933,
 'Trade, Transportation, and Utilities': 699,
 'Financial Activities': 699,
 'Professional and Business Services': 699,
 'Private Education and Health Services': 699,
 'Leisure and Hospitality': 699,
 'Other Services': 699}

In [103]:
df.head()

,year,month,area,industry,series,2,3,11,07,8,30
0,2007,1,Statewide,Total Private,SMU080000005000000,34.2,22.66,774.97,NaN,NaN,NaN
1,2007,1,Statewide,Goods Producing,SMU080000006000000,37.7,24.99,942.12,NaN,NaN,NaN
2,2007,1,Statewide,Private Service Providing,SMU080000008000000,33.5,22.13,741.36,NaN,NaN,NaN
3,2007,1,Statewide,Construction,SMU080000020000000,37.0,22.77,842.49,36.7,20.58,755.29
4,2007,1,Statewide,Manufacturing,SMU080000030000000,37.7,26.59,1002.44,38.3,17.05,653.02

In [75]:
df["series"].str.len()

0       18
1       18
2       18
3       18
4       18
        ..
4867    18
4868    18
4869    18
4870    18
4871    18
Name: series, Length: 4872, dtype: int64

In [ ]:
def decodeSeries(srs):
    mt = srs[2:3]
    st = srs[3:5]
    ar = srs[5:10]
    ss = srs[10:12]
    ic = srs[12:18]
    fc = srs[10:18]
    dt = srs[18:]
    return mt,st,ar,ss,ic,fc,dt


for srs in hist01.keys():
    mt,st,ar,ss,ic,fc,dt=decodeSeries(srs)
    ssd=defSS[int(ss)]
    fcd=defFS[fc]
    print(f"{ssd:50s} {fcd}")

In [124]:
defSS.keys()

dict_keys([0, 5, 6, 7, 8, 10, 15, 20, 30, 31, 32, 40, 41, 42, 43, 50, 55, 60, 65, 70, 80, 90])

In [119]:
def decodeSeriesNoDt(srs):
    mt = srs[2:3]
    st = srs[3:5]
    ar = srs[5:10]
    ss = srs[10:12]
    ic = srs[12:18]
    fc = srs[10:18]
    return mt,st,ar,ss,ic,fc


vars=['01']
us=['U','S']
fout=open("test01.csv","w")
fout.write("year,month,series,U,S\n")
for year,dct in allRecs01.items():
    for month,dct2 in dct.items():
        for srs,dct3 in dct2.items():
            string=f"{year},{month},{srs:20s},"
            mt,st,ar,ss,ic,fc=decodeSeriesNoDt(srs[:18])
            print(srs)
            print(ic,fc)
            spl=line.split("\t")
            year=int(spl[1])
            mo=int(spl[2].strip("M"))
            susc = defSS[int(ss)]
            inc = defFS[fc]
            area=defAR[int(ar)].rstrip(", CO")
        
           
            if inc not in hist:
                hist[inc]=0
            hist[inc]+=1
            for tp in us:
                if tp in dct3:
                   val=dct3[tp]
                else:
                   val=""
                string+=f"{val},"
            string=string.rstrip(",")
            fout.write(f"{string}\n")
fout.close()

0800000000000000
0000 000000

KeyError: '000000'

In [116]:
fc

'000000'

In [ ]:
defFS

In [4]:
df01=pd.read_csv("/home/joe/bic_etl/bls/sm/data_transformed/sm.data.6.Colorado.wages.tsv",delimiter="\t")

In [5]:
df01.head()

,year,month,area,superSector,industry,series,2,3,11,7,8,30
0,2007,1,Statewide,Total Private,Total Private,SMU080000005000000,34.2,22.66,774.97,NaN,NaN,NaN
1,2007,1,Statewide,Goods Producing,Goods Producing,SMU080000006000000,37.7,24.99,942.12,NaN,NaN,NaN
2,2007,1,Statewide,Private Service Providing,Private Service Providing,SMU080000008000000,33.5,22.13,741.36,NaN,NaN,NaN
3,2007,1,Statewide,Construction,Construction,SMU080000020000000,37.0,22.77,842.49,36.7,20.58,755.29
4,2007,1,Statewide,Manufacturing,Manufacturing,SMU080000030000000,37.7,26.59,1002.44,38.3,17.05,653.02

In [26]:
vars=['26']

fout=open("test26.csv","w")
fout.write("year,month,series,Value\n")
for year,dct in allRecs26.items():
    for month,dct2 in dct.items():
        for srs,val in dct2.items():
            string=f"{year},{month},{srs:20s},"
            string+=f"{val}"
            fout.write(f"{string}\n")
fout.close()

In [22]:
allRecs01[1957]

{1: {'0800000000000000': {'U': 455.4}},
 2: {'0800000000000000': {'U': 453.2}},
 3: {'0800000000000000': {'U': 456.2}},
 4: {'0800000000000000': {'U': 462.9}},
 5: {'0800000000000000': {'U': 470.7}},
 6: {'0800000000000000': {'U': 482.0}},
 7: {'0800000000000000': {'U': 490.5}},
 8: {'0800000000000000': {'U': 494.5}},
 9: {'0800000000000000': {'U': 491.8}},
 10: {'0800000000000000': {'U': 488.6}},
 11: {'0800000000000000': {'U': 481.8}},
 12: {'0800000000000000': {'U': 478.5}}}

In [33]:
df.count()

year      10176
month     10176
series    10176
2          3888
3          3888
11         3888
07         1416
8          1416
30         1416
dtype: int64

## Extract

In [6]:
import requests

# URL of the file to download (example)
url = "https://download.bls.gov/pub/time.series/sm/sm.data.6.Colorado"

# Set headers to mimic a real browser
headers = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "Accept-Encoding": "gzip, deflate, br, zstd",
    "Accept-Language": "en-US,en;q=0.9",
    "Connection": "keep-alive",
    "Sec-Fetch-Mode": "navigate",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36"
}

# Make the request
response = requests.get(url, headers=headers)

# Check response
if response.status_code == 200:
    print("Download successful!")
    # Save the file
    with open("sm.data.6.Colorado.tsv", "wb") as file:
        file.write(response.content)
else:
    print(f"Failed to download. HTTP Status Code: {response.status_code}")

Download successful!