In [4]:
import pygrib
import numpy as np
import sqlite3
import pandas as pd
import math
import time,datetime,os
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap


def log(what,time=None):
    fout = open("requests","a+")
    
    if what == "start":
        today=datetime.date.today()
        fout.write(f"{process_id} Start  {today}  {start}  {end}  {variables}\n")
        fout.close()
        return today
    elif what == "end":
        todayE=datetime.date.today()
        fout.write(f"{process_id} Complete  {todayE} {todayE-time} {start}  {end}  {variables}\n")
        fout.close()
        return None
    elif what == "fail":
        todayE=datetime.date.today()
        fout.write(f"{process_id} FAIL  {todayE} {todayE-time} {start}  {end}  {variables}\n")
        fout.close()
        return None

date,year-month,variable,point,value

## Get ERA5 API Data

In [3]:
import cdsapi
#variables=["10m_u_component_of_wind","10m_v_component_of_wind","surface_pressure"]
time=log("start")

variables=["2m_temperature","2m_dewpoint_temperature","10m_u_component_of_wind","10m_v_component_of_wind","total_precipitation"]

start=1994
end=1997
# years=[str(year) for year in range(start,end)]
# print(years)

dataset = "reanalysis-era5-land"
for nvar in range(len(variables)): 
    variable= variables[nvar]
    for start in range(start,end,4):
#        end=start+3
        ofile=f"{variable}_{start}_{end}"
        years=[str(year) for year in range(start,end+1)]
        print(ofile,years)
        request = {
            "variable": [
                 f"{variable}"
            ],
            "year": years,
            "month": [
                "01" , "02", "03",
                "04", "05", "06",
                "07", "08", "09",
                "10", "11", "12"
               ],
            "day": [
                "01", "02", "03",
                "04", "05", "06",
                "07", "08", "09",
                "10", "11", "12",
                "13", "14", "15",
                "16", "17", "18",
                "19", "20", "21",
                "22", "23", "24",
                "25", "26", "27",
                "28", "29", "30",
                "31"
            ],
            "time": [
                "00:00", "03:00", "06:00",
                "09:00", "12:00", "15:00",
                "18:00", "21:00"
            ],
            "data_format": "grib",
            "download_format": "unarchived",
            "target":ofile,
            "area": [41.1, -109, 37, -102]
        }
        
        client = cdsapi.Client()
        client.retrieve(dataset, request).download()
        print(f"File {ofile} Downloaded")
log("end",time)

2m_temperature_1994_1997 ['1994', '1995', '1996', '1997']

2025-04-06 09:09:05,667 WARNING [2025-04-03T00:00:00] System is in degraded status due to issues on the underlying infrastructure. Please follow status [here](https://status.ecmwf.int/) or in our [forum](https://forum.ecmwf.int/t/data-stores-in-degraded-status/12472)
2025-04-06 09:09:05,668 INFO [2024-09-26T00:00:00] Watch our [Forum](https://forum.ecmwf.int/) for Announcements, news and other discussed topics.
2025-04-06 09:09:05,668 WARNING [2024-06-16T00:00:00] CDS API syntax is changed and some keys or parameter names may have also changed. To avoid requests failing, please use the "Show API request code" tool on the dataset Download Form to check you are using the correct syntax for your API request.
2025-04-06 09:09:06,087 INFO Request ID is f3752475-7c17-4cd7-aaa5-396ae1fb0762
2025-04-06 09:09:06,281 INFO status has been updated to accepted
2025-04-06 09:31:37,171 INFO status has been updated to successful

a3803ff2d768b8304a3fe67b67705397.grib:   0%|          | 0.00/67.7M [00:00<?, ?B/s]

File 2m_temperature_1994_1997 Downloaded
2m_dewpoint_temperature_1994_1997 ['1994', '1995', '1996', '1997']

2025-04-06 09:31:52,202 WARNING [2025-04-03T00:00:00] System is in degraded status due to issues on the underlying infrastructure. Please follow status [here](https://status.ecmwf.int/) or in our [forum](https://forum.ecmwf.int/t/data-stores-in-degraded-status/12472)
2025-04-06 09:31:52,203 INFO [2024-09-26T00:00:00] Watch our [Forum](https://forum.ecmwf.int/) for Announcements, news and other discussed topics.
2025-04-06 09:31:52,203 WARNING [2024-06-16T00:00:00] CDS API syntax is changed and some keys or parameter names may have also changed. To avoid requests failing, please use the "Show API request code" tool on the dataset Download Form to check you are using the correct syntax for your API request.
2025-04-06 09:31:52,659 INFO Request ID is 11b1e8d9-8b46-4e8e-a19a-ea25b125b703
2025-04-06 09:31:52,852 INFO status has been updated to accepted
2025-04-06 10:04:27,446 INFO status has been updated to successful

9bc630989276ead3e388bdc90468e609.grib:   0%|          | 0.00/67.7M [00:00<?, ?B/s]

File 2m_dewpoint_temperature_1994_1997 Downloaded
10m_u_component_of_wind_1994_1997 ['1994', '1995', '1996', '1997']

2025-04-06 10:04:38,082 WARNING [2025-04-03T00:00:00] System is in degraded status due to issues on the underlying infrastructure. Please follow status [here](https://status.ecmwf.int/) or in our [forum](https://forum.ecmwf.int/t/data-stores-in-degraded-status/12472)
2025-04-06 10:04:38,084 INFO [2024-09-26T00:00:00] Watch our [Forum](https://forum.ecmwf.int/) for Announcements, news and other discussed topics.
2025-04-06 10:04:38,084 WARNING [2024-06-16T00:00:00] CDS API syntax is changed and some keys or parameter names may have also changed. To avoid requests failing, please use the "Show API request code" tool on the dataset Download Form to check you are using the correct syntax for your API request.
2025-04-06 10:04:38,514 INFO Request ID is 1bb09cf0-6879-4ed7-a61c-e6517deca293
2025-04-06 10:04:38,707 INFO status has been updated to accepted
2025-04-06 10:25:09,362 INFO status has been updated to running
2025-04-06 10:51:16,972 INFO status has been updated to successful

30af2fab6ab416b4f6517722ad9c024.grib:   0%|          | 0.00/67.7M [00:00<?, ?B/s]

File 10m_u_component_of_wind_1994_1997 Downloaded
10m_v_component_of_wind_1994_1997 ['1994', '1995', '1996', '1997']

2025-04-06 10:51:47,664 WARNING [2025-04-03T00:00:00] System is in degraded status due to issues on the underlying infrastructure. Please follow status [here](https://status.ecmwf.int/) or in our [forum](https://forum.ecmwf.int/t/data-stores-in-degraded-status/12472)
2025-04-06 10:51:47,665 INFO [2024-09-26T00:00:00] Watch our [Forum](https://forum.ecmwf.int/) for Announcements, news and other discussed topics.
2025-04-06 10:51:47,665 WARNING [2024-06-16T00:00:00] CDS API syntax is changed and some keys or parameter names may have also changed. To avoid requests failing, please use the "Show API request code" tool on the dataset Download Form to check you are using the correct syntax for your API request.
2025-04-06 10:51:48,073 INFO Request ID is d36e006c-9edb-4d47-9321-1944c1c07225
2025-04-06 10:51:48,265 INFO status has been updated to accepted
2025-04-06 11:32:24,436 INFO status has been updated to running
2025-04-06 11:58:31,898 INFO status has been updated to successful

fc0684cb2fee47ef8543e2e56c649e4.grib:   0%|          | 0.00/67.7M [00:00<?, ?B/s]

File 10m_v_component_of_wind_1994_1997 Downloaded
total_precipitation_1994_1997 ['1994', '1995', '1996', '1997']

2025-04-06 11:59:07,899 WARNING [2025-04-03T00:00:00] System is in degraded status due to issues on the underlying infrastructure. Please follow status [here](https://status.ecmwf.int/) or in our [forum](https://forum.ecmwf.int/t/data-stores-in-degraded-status/12472)
2025-04-06 11:59:07,900 INFO [2024-09-26T00:00:00] Watch our [Forum](https://forum.ecmwf.int/) for Announcements, news and other discussed topics.
2025-04-06 11:59:07,901 WARNING [2024-06-16T00:00:00] CDS API syntax is changed and some keys or parameter names may have also changed. To avoid requests failing, please use the "Show API request code" tool on the dataset Download Form to check you are using the correct syntax for your API request.
2025-04-06 11:59:08,313 INFO Request ID is 51fe1511-0380-4615-9d78-e403b0c00e8d
2025-04-06 11:59:08,502 INFO status has been updated to accepted
2025-04-06 13:38:02,133 INFO status has been updated to running
2025-04-06 14:10:26,492 INFO status has been updated to successful

c2fa27dde82cec93802fc5319603cea0.grib:   0%|          | 0.00/101M [00:00<?, ?B/s]

File total_precipitation_1994_1997 Downloaded

      "2m_temperature",
        "10m_u_component_of_wind",
        "10m_v_component_of_wind",
        "surface_pressure"

### Check Data

In [3]:
fin=open("list2")
files=fin.readlines()

In [4]:
files

['d40ba14c5df912c0e5026c128e8414e6.grib\n',
 'fd2e22fa3a9b9a4f3cc9e8a1a82cf505.grib\n',
 'e391b03b9ea92638ce2dfa68f78c0ff.grib\n',
 'e593c5aaa3145c3d76cc8fc44a160073.grib\n']

In [16]:
#grbs = pygrib.open("3da25100a42c035414eef7dde0b27070.grib")
#91894e9252f4bfe9946363c271068844.grib

grbs = pygrib.open("8d084dcb4fe77f60911be04bde726709.grib")

In [23]:
grb=grbs[1]
print(len(grb.latlons()[0][0]))

71

In [30]:
grbs[1].numberOfDataPoints

2982

In [ ]:
grbs[1].keys()

In [ ]:
dir(grbs[1])

In [10]:
lats = grb.latlons()[0]
lons = grb.latlons()[1]
latlons=[]
xlats=[]
xlons=[]
for nrow,lon in enumerate(lons):
    for ncol,lln in enumerate(lon):
        llt = round(lats[nrow][ncol],1)
        lln = round(lln,1)
        latlons.append((lln,llt))
        xlats.append(llt)
        xlons.append(lln)
        
with open("lats.txt", "w") as file:
    # Write each item in the list on a new line
    for item in xlats:
        file.write(f"{item}\n")


with open("lons.txt", "w") as file:
    # Write each item in the list on a new line
    for item in xlons:
        file.write(f"{item}\n")


with open("latlons.txt", "w") as file:
    # Write each item in the list on a new line
    for item in latlons:
        file.write(f"{item[0]},{item[1]}\n")

In [ ]:
xlats

In [ ]:
fig = plt.figure(figsize=(8, 6), edgecolor='b')
mrg=.5
latmin=min(xlats)-mrg
latmax=max(xlats)+mrg
lonmin=min(xlons)-mrg
lonmax=max(xlons)+mrg
my_map = Basemap(projection='cyl',
               llcrnrlat=latmin, urcrnrlat=latmax,resolution="l",
            llcrnrlon=lonmin, urcrnrlon=lonmax)
 
#my_map.drawcoastlines()
my_map.drawstates()
my_map.scatter(xlons, xlats, latlon=True,c="red",s=1)

In [31]:
fin=open("list2")
files=fin.readlines()
print(files)
invt={}
fout=open("files_summary3.txt","w")
for file in files:
    file=file.strip()
    print(file)
    grbs = pygrib.open(file)
    years={}
    months={}
    vars={}
    if grbs[1].numberOfDataPoints != 42*71:
        for grb in grbs:
           yr=grb["year"]
           mo=grb["month"]
           dy=grb["day"]
           var=grb['paramId']
           name=grb['shortName']
           if var not in vars:
               vars[var]=0
           vars[var]+=1
           if yr not in years:
               years[yr]=0
           if mo not in months:
               months[mo]=0
           months[mo]+=1
           years[yr]+=1
           if var not in invt:
               invt[var]={}
           if yr not in invt[var]:
               invt[var][yr]={}
           if mo not in invt[var][yr]:
               invt[var][yr][mo]=0
    
           invt[var][yr][mo]+=1
        print("Variable: ",var,name)
        for yr in sorted(years.keys()):
            print(f"   {yr}  {years[yr]:7d}")
        for mo in months:
            print(f"     {mo}  {months[mo]:5d}")
        fout.write(f"{file} {vars.keys()}  {sorted(years.keys())}\n")
        grbs.close()
fout.close()
print("DONE")

['9035aad105e492216740525c32c4eeee.grib\n', '91894e9252f4bfe9946363c271068844.grib\n', '3da25100a42c035414eef7dde0b27070.grib\n', '8d084dcb4fe77f60911be04bde726709.grib\n', 'd5cb3e579bcac88283a8f806a5591be3.grib\n', 'e593c5aaa3145c3d76cc8fc44a160073.grib\n', 'e391b03b9ea92638ce2dfa68f78c0ff.grib\n', 'd40ba14c5df912c0e5026c128e8414e6.grib\n', 'fd2e22fa3a9b9a4f3cc9e8a1a82cf505.grib']
9035aad105e492216740525c32c4eeee.grib
Variable:  172228 tprate
   2017      360
   2018      360
   2019      360
   2020      360
   2021      360
   2022      360
   2023      360
   2024      360
   2025       60
     1    270
     2    270
     3    240
     4    240
     5    240
     6    240
     7    240
     8    240
     9    240
     10    240
     11    240
     12    240
91894e9252f4bfe9946363c271068844.grib
Variable:  172228 tprate
   2019      216
   2020      216
   2021      216
   2022      216
   2023      216
   2024      216
   2025       36
     1    126
     2    126
     3    108
     4    108
     5    108
     6    108
     7    108
     8    108
     9    108
     10    108
     11    108
     12    108
3da25100a42c035414eef7dde0b27070.grib
Variable:  172228 tprate
   2017      216
   2018      216
     1     36
     2     36
     3     36
     4     36
     5     36
     6     36
     7     36
     8     36
     9     36
     10     36
     11     36
     12     36
8d084dcb4fe77f60911be04bde726709.grib
d5cb3e579bcac88283a8f806a5591be3.grib
e593c5aaa3145c3d76cc8fc44a160073.grib
e391b03b9ea92638ce2dfa68f78c0ff.grib
d40ba14c5df912c0e5026c128e8414e6.grib
fd2e22fa3a9b9a4f3cc9e8a1a82cf505.grib
DONE

In [ ]:
lats=grb.latlons()[0]
lons=grb.latlons()[1]

In [ ]:
lats[0]

In [ ]:
print(len(lats))
print(len(lats[0]))

In [ ]:
for var in invt.keys():
#    for year in range(1990,2025):
    #    year=str(year)
     for year in sorted(invt[var].keys()):
        print(f"{var:3d} {year:4d}",end="")
        for month in range(1,13):
            if month in invt[var][year]:
                cnt=invt[var][year][month]
            else:
                cnt=0
            print(f"{cnt:5d}",end="")
        print("")

## RH and VPD to Sqlite

In [ ]:
import numpy as np

def rh_from_t_td(t, td, units="C"):
    """Compute relative humidity (%) from air temperature and dew point.

    Parameters
    ----------
    t : float or array-like
        Air temperature.
    td : float or array-like
        Dew point temperature (same units as t).
    units : str
        "C" for Celsius (default) or "K" for Kelvin.
    """
    t = np.asarray(t, dtype=float)
    td = np.asarray(td, dtype=float)

    if units.upper() == "K":
        t = t - 273.15
        td = td - 273.15
    elif units.upper() != "C":
        raise ValueError("units must be 'C' or 'K'")

    # Magnus formula (valid for typical atmospheric conditions)
    rh = 100.0 * np.exp((17.625 * td) / (243.04 + td)) / np.exp((17.625 * t) / (243.04 + t))
    return np.clip(rh, 0.0, 100.0)

# Example
print(rh_from_t_td(30.0, 20.0, units="C"))

In [4]:

def tTd2RH(t,td):
#  t,td should be in C
    rh=  100 * (math.exp((17.625 * td) / (243.04 + td))) / (math.exp((17.625 * t) / (243.04 + t)))
    return rh

def vpd(T,RH):
#    T should in in C
 #   tt=T-273.15
    tt=T
    es =0.6108*math.exp((17.27*tt)/(tt+237.3))
    if RH>1:
       val=100
    else:
        val=1
    ea=RH/val*es
    return es-ea

def decodeGrib(grb,data):
    dataTmp=grb.data()
    nlons=29
    date=f'{grb["dataDate"]}{str(grb["validityTime"]).zfill(4)}'
    yrmo=f'{grb["year"]}{grb["month"]}'
#    print(date)
    if date not in data:
        data[date]={}
    tmp = np.empty((17,29))
    latslons= []
    data[date][grb['paramId']]=dataTmp[0]
    # for nrow,dat in enumerate(dataTmp[0]):
    #     # print(nrow,len(dat),data[0][nrow])
    #    ll=[]
    #    for ncol,val in enumerate(dat):
    #        val=dataTmp[0][nrow][ncol]
    #        pt=nlons*nrow+ncol
    #        var=grb['paramId']
    #        if pt not in data[date]:
    #           data[date][pt]={}
          
              
               
      # #     print(nrow,ncol,pt,dataTmp[2][nrow][ncol],dataTmp[1][nrow][ncol])
      #  latslons.append(ll)
    return data


def combineData(data):
    allData={}
    print("COMBINED DATA LEN ",len(data))
    for date in sorted(data.keys()):
     #   print(date)
        tDat=data[date][167]
        tDDat=data[date][168]
        yrmo=date[:6]
        for nrow in range(0,nlats):
            for ncol in range(0,nlons):
              T=tDat[nrow][ncol]-273.15
              Td=tDDat[nrow][ncol]-273.15
              RH=tTd2RH(T,Td)
              vp=  vpd(T,RH)
              pt=nlons*nrow+ncol
              # if pt > 493:
              #     print(pt,nrow,ncol)
                  
              if pt not in allData:
                  allData[pt]={}
              if yrmo not in allData[pt]:
                  allData[pt][yrmo] = {}
              if date not in allData[pt][yrmo]:
                  allData[pt][yrmo][date]={}
              allData[pt][yrmo][date]["T"]=round(T,2)
              allData[pt][yrmo][date]["Td"]=round(Td,2)
              allData[pt][yrmo][date]["RH"]=round(RH,2)
              allData[pt][yrmo][date]["vpd"]=round(vp,4)
    return allData


def computeMeans(allData):
    dates=[]
    temps=[]
    dews=[]
    rhs=[]
    vpds=[]
    pts=[]
    yrmos=[]
    lens=[]
    print("COMPUTE MEANS ALL DATA LEN ",len(allData))
    for pt,dct in allData.items():
        for yrmo,dct1 in dct.items():
            datesTmp=[]
            tempsTmp=[]
            dewsTmp=[]
            rhsTmp=[]
            vpdsTmp=[]
            for date,dct2 in dct1.items():
                datesTmp.append(date)
                tempsTmp.append(dct2["T"])
                dewsTmp.append(dct2["Td"])
                rhsTmp.append(dct2["RH"])
                vpdsTmp.append(dct2["vpd"])
            if len(tempsTmp) > 160:  # need at-least about 2/3 of a month of data to use  means
                tMean=sum(tempsTmp)/len(tempsTmp)
                tdMean=sum(dewsTmp)/len(dewsTmp)
                rhMean=sum(rhsTmp)/len(rhsTmp)
                vpdMean=sum(vpdsTmp)/len(vpdsTmp)
                pts.append(pt)
                yrmos.append(yrmo)
                temps.append(tMean)
                dews.append(tdMean)
                rhs.append(rhMean)
                vpds.append(vpdMean)
                lens.append(len(vpdsTmp))
    print("MEANS LENS ",len(yrmos),len(pts),len(temps),len(dews),len(rhs),len(vpds),len(lens))
    dfOut = pd.DataFrame({
        "Point":pts,
        "Yrmo":yrmos,
        "Length":lens,
        "T":temps,
        "Td":dews,
        "RH":rhs,
        "VPD":vpds
    })
    return dfOut

In [5]:
files=[("645bf4eebfd03a5c9c98f12ca3d81f2f.grib","dc46136c51d42d8ce9857eda74517109.grib"),
("f1f45b78e458240d3eb7b1dcbcb9af2e.grib","e50619361b5e37d6340705730bfbb8c.grib"),
("c1994c9c539633bdf39f0202f6bca6de.grib","106ac6ff21c39917e420069e1f4f2d20.grib"),
("b1b09ea38933614bf7de5e339e2c0356.grib","272ab29b90e861545de51b42554e7fab.grib"),
("56c835fe0bbcd022ddf629e988a2c2de.grib","e0138cf2564488e3ffbeaaa3052db60c.grib"),
("22c623af94b440e336e1123839c4301c.grib","cb344d75de30495348cac2f73b0ab36d.grib"),
("86510760a47e5d2cbd24a093642defa3.grib","f566da3b5cd162ab111fcbdda2c4dbdb.grib"),
("dbc724e917592936eec2a414aa47971f.grib","e5342cf365c0061b874a5a65ce921baf.grib"),
("5664f9d21864634001995f43900dbee4.grib","64ac0e495fe5695c74d33e5b8bd0a76d.grib")]

connr = sqlite3.connect('Data/DB/era5DataMeans.db')
nlons=71
nlats=42
a=time.time()    

for ff in files[2:]:
    data={}
    c=time.time()
    for file in ff:
        print(file)
        grbs = pygrib.open(file)
        for grb in grbs:
            data=decodeGrib(grb,data)
        grbs.close() 
    print("Combining")
    combinedData = combineData(data)
    print("Compute Means")
    df=computeMeans(combinedData)
    print("Write output")
    df.to_sql('MEANS_TTdRHVPD', connr,if_exists="append")
    print(df["Yrmo"].value_counts)
    del combinedData
    del df
    d=time.time()
    print("This round took ",d-c)

b=time.time()
print("Took ",b-a," Seconds to run")
print("Done")

c1994c9c539633bdf39f0202f6bca6de.grib
106ac6ff21c39917e420069e1f4f2d20.grib
Combining
COMBINED DATA LEN  11688

KeyboardInterrupt:

In [6]:
connr = sqlite3.connect('Data/DB/era5DataMeans.db')
tmp = pd.read_sql("select * from MEANS_TTdRHVPD",connr)

dates = tmp["Yrmo"].values.tolist()
invt={}
for yrmo in dates:
    yr=int(yrmo[:4])
    mo=int(yrmo[4:6])
    if yr not in invt:
        invt[yr]={}
    if mo not in invt[yr]:
       invt[yr][mo]=0

    invt[yr][mo]+=1
 

for year in sorted(invt.keys()):
    print(f"{int(year):4d}",end="")
    for month in range(1,13):
        if month in invt[year]:
            cnt=invt[year][month]
        else:
            cnt=0
        print(f"{cnt:5d}",end="")
    print("")

1990 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1991 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1992 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1993 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1994 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1995 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1996 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1997 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1998 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1999 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2000 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2001 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2002 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2003 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2004 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2005 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2006 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2007 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2008 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2009 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2010 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2011 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2012 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2013 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2014 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2015 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2016 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2017 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2018 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2019 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2020 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2021 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2022 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2023 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2024 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982

In [11]:
tmp["Date"]=tmp['Yrmo']+"01"

In [16]:
tmp["Date"]=pd.to_datetime(tmp["Date"])

In [17]:
tmp.loc[tmp["Point"] == 4].to_csv("data_P4.csv",index=False)

In [11]:
a.shape

(5964, 8)

In [12]:
a.head()

     index  Point    Yrmo  Length          T         Td         RH       VPD
48      48      0  199312     247 -10.668583 -13.857328  78.062551  0.064776
97      97      1  199312     247 -10.947530 -13.981174  78.965951  0.060581
146    146      2  199312     247 -10.824696 -13.730729  79.795182  0.058843
195    195      3  199312     247 -10.735587 -13.549231  80.371417  0.057732
244    244      4  199312     247 -10.748543 -13.494534  80.779150  0.056906

In [13]:
a.tail()

         index  Point    Yrmo  Length     T    Td     RH     VPD
291991  145873   2977  199312       1  6.99 -8.29  32.77  0.6732
292040  145922   2978  199312       1  6.62 -7.88  34.71  0.6372
292089  145971   2979  199312       1  6.43 -7.77  35.47  0.6219
292138  146020   2980  199312       1  6.28 -7.69  36.05  0.6097
292187  146069   2981  199312       1  6.09 -7.61  36.77  0.5950

In [31]:

# nlons=29
# nlats=17
nlons=71
nlats=42
allData={}
a= time.time()

def combineData(data):
    for date in sorted(data.keys()):
     #   print(date)
        tDat=data[date][167]
        tDDat=data[date][168]
        yrmo=date[:6]
        for nrow in range(0,nlats):
            for ncol in range(0,nlons):
              T=tDat[nrow][ncol]-273.15
              Td=tDDat[nrow][ncol]-273.15
              RH=tTd2RH(T,Td)
              vp=  vpd(T,RH)
              pt=nlons*nrow+ncol
              # if pt > 493:
              #     print(pt,nrow,ncol)
                  
              if pt not in allData:
                  allData[pt]={}
              if yrmo not in allData[pt]:
                  allData[pt][yrmo] = {}
              if date not in allData[pt][yrmo]:
                  allData[pt][yrmo][date]={}
              allData[pt][yrmo][date]["T"]=round(T,2)
              allData[pt][yrmo][date]["Td"]=round(Td,2)
              allData[pt][yrmo][date]["RH"]=round(RH,2)
              allData[pt][yrmo][date]["vpd"]=round(vp,4)
    return allData

print("Done")

Done

In [ ]:
TImer:  312.7191710472107

In [ ]:
len(tDat[0])

In [30]:
def computeMeans(allData):
    dates=[]
    temps=[]
    dews=[]
    rhs=[]
    vpds=[]
    pts=[]
    yrmos=[]
    lens=[]
    
    for pt,dct in allData.items():
        for yrmo,dct1 in dct.items():
            datesTmp=[]
            tempsTmp=[]
            dewsTmp=[]
            rhsTmp=[]
            vpdsTmp=[]
            for date,dct2 in dct1.items():
                datesTmp.append(date)
                tempsTmp.append(dct2["T"])
                dewsTmp.append(dct2["Td"])
                rhsTmp.append(dct2["RH"])
                vpdsTmp.append(dct2["vpd"])
            tMean=sum(tempsTmp)/len(tempsTmp)
            tdMean=sum(dewsTmp)/len(dewsTmp)
            rhMean=sum(rhsTmp)/len(rhsTmp)
            vpdMean=sum(vpdsTmp)/len(vpdsTmp)
            pts.append(pt)
            yrmos.append(yrmo)
            temps.append(tMean)
            dews.append(tdMean)
            rhs.append(rhMean)
            vpds.append(vpdMean)
            lens.append(len(vpdsTmp))
    dfOut = pd.DataFrame({
        "Point":pts,
        "Yrmo":yrmos,
        "Length":lens,
        "T":temps,
        "Td":dews,
        "RH":rhs,
        "VPD":vpds
    })
    return dfOut

In [26]:
dfOut = pd.DataFrame({
    "Point":pts,
    "Yrmo":yrmos,
    "Length":lens,
    "T":temps,
    "Td":dews,
    "RH":rhs,
    "VPD":vpds
})

In [29]:
48*42*71+42*71

146118

In [27]:
dfOut.shape

(146118, 7)

In [18]:
dfOut

       Point    Yrmo  Length          T         Td         RH       VPD
0          0  198912       1  -7.320000 -10.800000  76.160000  0.084100
1          0  199001     248  -8.463992 -12.366048  74.223548  0.092007
2          0  199002     224  -9.227723 -12.758839  76.263616  0.079737
3          0  199003     248  -3.466290  -7.204153  76.585927  0.127759
4          0  199004     240   4.388708  -3.163000  60.712417  0.380563
...      ...     ...     ...        ...        ...        ...       ...
87852   1792  199308     248  24.516452  15.000565  58.735161  1.462267
87853   1792  199309     240  20.487583   7.905667  49.496417  1.444099
87854   1792  199310     248  13.213266   2.023185  50.593226  0.910102
87855   1792  199311     240   4.843208  -5.739042  49.893167  0.509139
87856   1792  199312     247   3.322470  -7.402794  49.499879  0.468555

[87857 rows x 7 columns]

In [19]:
dfOut["Point"].value_counts()

Point
1792    49
1753    49
1754    49
1755    49
1756    49
        ..
4       49
5       49
6       49
7       49
8       49
Name: count, Length: 1793, dtype: int64

In [ ]:
connr = sqlite3.connect('Data/DB/era5Data.db')

In [ ]:
connr = sqlite3.connect('Data/DB/era5Data.db')
dfOut.to_sql('TTdRHVPD', connr,if_exists="append")

In [ ]:
dfOut["Date"].max()

In [ ]:
for grb in grbs[10:]:
   print(grb["dataTime"],grb["year"],grb["month"],grb["day"],grb["hour"],grb['validityTime'])
   t=dataTmp[1][nrow][ncol])
print("DONE")

In [ ]:
len(grbs)

In [ ]:
dir(grb)

In [ ]:
grb["validityTime"]

In [ ]:
connection = sqlite3.connect("Data/DB/era5_daily.db")
df= pd.read_sql("select * from data",connection)

In [ ]:
df.head()

In [ ]:
def tTd2RH(t,td):
    rh=  100 * (math.exp((17.625 * td) / (243.04 + td))) / (math.exp((17.625 * t) / (243.04 + t)))
    return rh

def vpd(T,RH):
    tt=T-273.15
    es =0.6108*math.exp((17.27*tt)/(tt+237.3))
    if RH>1:
       val=100
    else:
        val=1
    ea=RH/val*es
    return es-ea


hist={}
ncount=0
for date in datesAll[1:]:
    ncount+=1
    tmp= df.loc[df["date"] == date]
    print(f"{ncount} of {len(datesAll)-1} : {date}") 
    pts=tmp["point"].value_counts().to_dict().keys()
    for pt in pts:
        t = float(tmp.loc[(tmp["point"] == pt) & (tmp["variable"] == 167),"value"].values.tolist()[0])
        td = float(tmp.loc[(tmp["point"] == pt) & (tmp["variable"] == 168),"value"].values.tolist()[0])
        yrmo = float(tmp.loc[(tmp["point"] == pt) & (tmp["variable"] == 168),"yrmo"].values.tolist()[0])
        rh=tTd2RH(t-273.15,td-273.15)
        vp=vpd(t,rh)
        
        if yrmo not in hist:
            hist[yrmo]={}
        if pt not in hist[yrmo]:
            hist[yrmo][pt]={}
            hist[yrmo][pt]["t"]=[]
            hist[yrmo][pt]["td"]=[]
            hist[yrmo][pt]["rh"]=[]
            hist[yrmo][pt]["vpd"]=[]
            
        hist[yrmo][pt]["t"].append(t)
        hist[yrmo][pt]["td"].append(td)
        hist[yrmo][pt]["rh"].append(rh)
        hist[yrmo][pt]["vpd"].append(vp)
        
                
       
    #    print(yrmo,pt,t,td,rh)
   
print("DONE")

In [ ]:
for date,dct2 in data['19901'].items():
    
    td=dct2[1][168]
    t=dct2[1][167]
    print(date,t,td)

def tTd2RH(t,td):
    rh=  100 * (exp((17.625 * td) / (243.04 + td))) / (exp((17.625 * t) / (243.04 + t)))
    return rh

In [ ]:
def tTd2RH(t,td):
    rh=  100 * (exp((17.625 * td) / (243.04 + td))) / (exp((17.625 * t) / (243.04 + t)))
    return rh

tTd2RH(

In [ ]:
variables=["2m_temperature","2m_dewpoint_temperature","10m_u_component_of_wind","10m_v_component_of_wind","surface_pressure"]