In [1]:
import pandas as pd
import csv

In [2]:
dfO = pd.read_csv("data/CIM/current_notaries_orig_sort.csv")

In [3]:
dfT = pd.read_csv("data/CIM/Current_Notaries_in_Colorado_20251006_sort.csv")

In [5]:
print(dfO.shape)
print(dfT.shape)

(75855, 10)
(75855, 10)

In [6]:
dfO.head()

,lastName,firstName,middleName,suffix,notaryId,commissionStart,commissionExpire,zipcode,remoteNotary,enotary
0,7388,ALEXANDRA,REYNOLDS,NaN,20234043754,11/17/2023,11/17/2027,80012,No,No
1,A HOLBROOKS,EMILY,ARELYS,NaN,20254021770,06/10/2025,06/10/2029,81008,No,No
2,A ROBINSON,ERIC,ALAN,NaN,20254000119,01/03/2025,01/03/2029,80537,No,No
3,AAD,JEANNE,FAYE,NaN,20224036261,09/15/2022,09/15/2026,80134,No,No
4,AAKER,PAUL,NaN,NaN,20224016323,04/22/2022,04/22/2026,802371629,No,No

In [7]:
dfT.head()

,lastName,firstName,middleName,suffix,zipcode,commissionStart,commissionExpire,notaryId,enotary,remoteNotary
0,7388,ALEXANDRA,REYNOLDS,NaN,80012,11/17/2023,11/17/2027,20234043754,No,No
1,A HOLBROOKS,EMILY,ARELYS,NaN,81008,06/10/2025,06/10/2029,20254021770,No,No
2,A ROBINSON,ERIC,ALAN,NaN,80537,01/03/2025,01/03/2029,20254000119,No,No
3,AAD,JEANNE,FAYE,NaN,80134,09/15/2022,09/15/2026,20224036261,No,No
4,AAKER,PAUL,NaN,NaN,802371629,04/22/2022,04/22/2026,20224016323,No,No

In [15]:
dfT.loc[dfO['lastName'] != dfT['lastName']]

,lastName,firstName,middleName,suffix,zipcode,commissionStart,commissionExpire,notaryId,enotary,remoteNotary
75851,NaN,SUMMER,RAE,NaN,80246,10/26/2023,10/26/2027,20194038537,No,No
75852,NaN,ZACHARY,NaN,NaN,80915,11/08/2024,11/08/2028,20244041314,No,No
75853,NaN,ECHO,NaN,NaN,80203,04/11/2025,04/11/2029,20254014017,No,No
75854,NaN,MEGAN,NaN,NaN,81201,10/06/2024,10/06/2028,20204034703,No,No

In [21]:
hld={}
for col in dfO.columns: 
    hld[col]={}
    print(col)
    hld[col]["O"]=dfO.loc[dfO[col] != dfT[col],col]
    hld[col]["T"]=dfT.loc[dfO[col] != dfT[col],col]

lastName
firstName
middleName
suffix
notaryId
commissionStart
commissionExpire
zipcode
remoteNotary
enotary

In [14]:
dfT.isna().sum()

lastName                4
firstName               1
middleName          35935
suffix              75030
zipcode                 4
commissionStart         0
commissionExpire        0
notaryId                0
enotary                17
remoteNotary            0
dtype: int64

In [22]:
hld["lastName"]

{'O': 75851    NaN
 75852    NaN
 75853    NaN
 75854    NaN
 Name: lastName, dtype: object,
 'T': 75851    NaN
 75852    NaN
 75853    NaN
 75854    NaN
 Name: lastName, dtype: object}

In [23]:
hld.keys()

dict_keys(['lastName', 'firstName', 'middleName', 'suffix', 'notaryId', 'commissionStart', 'commissionExpire', 'zipcode', 'remoteNotary', 'enotary'])

In [26]:
for col,dct in hld.items():
    print(f"Column: {col}")
    print("    NANs",dfO[col].isna().sum(),dfT[col].isna().sum())
    print("Original:",len(dct["O"]))
  #  print(dct["O"])
    print("Target:",len(dct["T"]))
  #  print(dct["T"])
    print("-----")

Column: lastName
    NANs 4 4
Original: 4
Target: 4
-----
Column: firstName
    NANs 1 1
Original: 5
Target: 5
-----
Column: middleName
    NANs 35935 35935
Original: 35936
Target: 35936
-----
Column: suffix
    NANs 75030 75030
Original: 75030
Target: 75030
-----
Column: notaryId
    NANs 0 0
Original: 534
Target: 534
-----
Column: commissionStart
    NANs 0 0
Original: 506
Target: 506
-----
Column: commissionExpire
    NANs 0 0
Original: 506
Target: 506
-----
Column: zipcode
    NANs 4 4
Original: 489
Target: 489
-----
Column: remoteNotary
    NANs 0 0
Original: 72775
Target: 72775
-----
Column: enotary
    NANs 17 17
Original: 73419
Target: 73419
-----

In [28]:
dfO.head()

,lastName,firstName,middleName,suffix,notaryId,commissionStart,commissionExpire,zipcode,remoteNotary,enotary
0,7388,ALEXANDRA,REYNOLDS,NaN,20234043754,11/17/2023,11/17/2027,80012,No,No
1,A HOLBROOKS,EMILY,ARELYS,NaN,20254021770,06/10/2025,06/10/2029,81008,No,No
2,A ROBINSON,ERIC,ALAN,NaN,20254000119,01/03/2025,01/03/2029,80537,No,No
3,AAD,JEANNE,FAYE,NaN,20224036261,09/15/2022,09/15/2026,80134,No,No
4,AAKER,PAUL,NaN,NaN,20224016323,04/22/2022,04/22/2026,802371629,No,No

In [29]:
dfOS = dfO.sort_values(by=["notaryId"])
dfTS = dfT.sort_values(by=["notaryId"])

In [33]:
cols=dfTS.columns

In [34]:
dfOSN = dfOS[cols].copy()

In [35]:
dfOSN.dtypes

lastName            object
firstName           object
middleName          object
suffix              object
zipcode             object
commissionStart     object
commissionExpire    object
notaryId             int64
enotary             object
remoteNotary        object
dtype: object

In [43]:
dfTS.reset_index(drop=True,inplace=True)
dfOSN.reset_index(drop=True,inplace=True)

In [44]:
hld={}
for col in dfOS.columns: 
    hld[col]={}
    print(col)
    hld[col]["O"]=dfOSN.loc[dfOSN[col] != dfTS[col],col]
    hld[col]["T"]=dfTS.loc[dfOSN[col] != dfTS[col],col]

lastName
firstName
middleName
suffix
notaryId
commissionStart
commissionExpire
zipcode
remoteNotary
enotary

In [38]:
colsOS = dfOSN.columns

In [40]:
for nn,col in enumerate(colsOS):
    print(nn,col,colsOS[nn],dfTS[col].dtype,dfOSN[col].dtype)

0 lastName lastName object object
1 firstName firstName object object
2 middleName middleName object object
3 suffix suffix object object
4 zipcode zipcode object object
5 commissionStart commissionStart object object
6 commissionExpire commissionExpire object object
7 notaryId notaryId int64 int64
8 enotary enotary object object
9 remoteNotary remoteNotary object object

In [45]:
for col,dct in hld.items():
    print(f"Column: {col}")
    print("    NANs",dfO[col].isna().sum(),dfT[col].isna().sum())
    print("Original:",len(dct["O"]))
  #  print(dct["O"])
    print("Target:",len(dct["T"]))
  #  print(dct["T"])
    print("-----")

Column: lastName
    NANs 4 4
Original: 4
Target: 4
-----
Column: firstName
    NANs 1 1
Original: 1
Target: 1
-----
Column: middleName
    NANs 35935 35935
Original: 35935
Target: 35935
-----
Column: suffix
    NANs 75030 75030
Original: 75030
Target: 75030
-----
Column: notaryId
    NANs 0 0
Original: 0
Target: 0
-----
Column: commissionStart
    NANs 0 0
Original: 0
Target: 0
-----
Column: commissionExpire
    NANs 0 0
Original: 0
Target: 0
-----
Column: zipcode
    NANs 4 4
Original: 4
Target: 4
-----
Column: remoteNotary
    NANs 0 0
Original: 72745
Target: 72745
-----
Column: enotary
    NANs 17 17
Original: 73396
Target: 73396
-----

In [46]:
dfTS["enotary"].head()

0    No
1    No
2    No
3    No
4    No
Name: enotary, dtype: object

In [47]:
dfOSN["enotary"].head()

0    No
1    No
2    No
3    No
4    No
Name: enotary, dtype: object

In [48]:
dfOSN["enotary"].value_counts()

enotary
No     73379
Yes     2459
Name: count, dtype: int64

In [49]:
dfTS["enotary"].value_counts()

enotary
No     73379
Yes     2459
Name: count, dtype: int64

In [50]:
dfTS["enotary"].str.len()

0        2.0
1        2.0
2        2.0
3        2.0
4        2.0
        ...
75850    2.0
75851    2.0
75852    2.0
75853    2.0
75854    2.0
Name: enotary, Length: 75855, dtype: float64

In [51]:

dfOSN["enotary"].str.len()

0        3.0
1        3.0
2        3.0
3        3.0
4        3.0
        ...
75850    3.0
75851    3.0
75852    3.0
75853    3.0
75854    3.0
Name: enotary, Length: 75855, dtype: float64

In [53]:
for col in dfOSN.columns:
    if dfOSN[col].dtype == 'object':
        dfOSN[col] = dfOSN[col].str.strip()

for col in dfTS.columns:
    if dfTS[col].dtype == 'object':
        dfTS[col] = dfTS[col].str.strip()

In [54]:
hld={}
for col in dfOS.columns: 
    hld[col]={}
    print(col)
    hld[col]["O"]=dfOSN.loc[dfOSN[col] != dfTS[col],col]
    hld[col]["T"]=dfTS.loc[dfOSN[col] != dfTS[col],col]

for col,dct in hld.items():
    print(f"Column: {col}")
    print("    NANs",dfO[col].isna().sum(),dfT[col].isna().sum())
    print("Original:",len(dct["O"]))
  #  print(dct["O"])
    print("Target:",len(dct["T"]))
  #  print(dct["T"])
    print("-----")

lastName
firstName
middleName
suffix
notaryId
commissionStart
commissionExpire
zipcode
remoteNotary
enotary
Column: lastName
    NANs 4 4
Original: 4
Target: 4
-----
Column: firstName
    NANs 1 1
Original: 1
Target: 1
-----
Column: middleName
    NANs 35935 35935
Original: 35935
Target: 35935
-----
Column: suffix
    NANs 75030 75030
Original: 75030
Target: 75030
-----
Column: notaryId
    NANs 0 0
Original: 0
Target: 0
-----
Column: commissionStart
    NANs 0 0
Original: 0
Target: 0
-----
Column: commissionExpire
    NANs 0 0
Original: 0
Target: 0
-----
Column: zipcode
    NANs 4 4
Original: 4
Target: 4
-----
Column: remoteNotary
    NANs 0 0
Original: 0
Target: 0
-----
Column: enotary
    NANs 17 17
Original: 17
Target: 17
-----