In [1]:
import pandas as pd
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd
import os.path,sys
# import streamlit as st
# from st_aggrid import AgGrid, GridUpdateMode
# from st_aggrid.grid_options_builder import GridOptionsBuilder
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/google/auth/crypt/_cryptography_rsa.py:22: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  import cryptography.exceptions

## Read Xentity's CIM Inventory

In [2]:
df1 = pd.read_csv("Asset_Inventory.csv")
print(df1.shape)

(2556, 111)

In [3]:
dfCIM = df1.loc[df1["Owner"] == "Colorado Information Marketplace"]
idsCim = dfCIM["UID"].values.tolist()

In [4]:
print(dfCIM.shape,len(idsCim))

(534, 111) 534

In [5]:
print(dfCIM["Type"].value_counts())
print(dfCIM["Audience"].value_counts())

dataset     347
map         162
href         15
filter        7
datalens      3
Name: Type, dtype: int64
public     466
private     68
Name: Audience, dtype: int64

### Extract on Map datasets that are Public

In [6]:
#  Extract only CIM datasets that are maps and public
dfCIMMap = dfCIM.loc[(dfCIM["Type"] == "map") & (dfCIM["Audience"] == "public")]
idsCimMaptmp = dfCIMMap["UID"].values.tolist()
idsCimMap = []

for id in idsCimMaptmp:
    spl = id.split(":")
    idsCimMap.append(spl[0])

In [7]:
print(len(idsCimMap))
print(dfCIMMap.shape)

157
(157, 111)

In [8]:
# for id in sorted(idsCimMap):
#     print(id)

### Split for Census and Non Census data

In [8]:
dfCIMMapCen = dfCIMMap.loc[dfCIMMap["Name"].str.lower().str.contains("census")]
dfCIMMapNoCen = dfCIMMap.loc[~dfCIMMap["Name"].str.lower().str.contains("census")]

In [10]:
print(dfCIMMap.shape)
print(dfCIMMapCen.shape)
print(dfCIMMapNoCen.shape)

(157, 111)
(92, 111)
(65, 111)

## Tyler Inventory

In [11]:
dfYvn = pd.read_csv("Mondara_Maps.csv")

In [12]:
print(dfYvn.shape)
print(dfCIMMap.shape)

(160, 7)
(157, 111)

In [13]:
idsYvn = dfYvn["uid"].values.tolist()

## Compare Xentity Inventory to Tylers (Yvonne's)

dfCIMMap  -> contains all records that are CIM only, are Maps and Public
dfYvn     -> contains Tyler (Yvonnes) inventory records

idsYvn    -> Tyler ids
idsCimMap -> ids for dfCIMMap

dfCIMMapNoCen ->  all dfCIMMap records that are NOT Census related
dfCIMMapCen   ->  all dfCIMMap records related to the Census

In [14]:
#  datasets in our inventory not in Tylers
for index,row in dfCIMMap.iterrows():
    id=row["UID"]
    spl = id.split(":")
    idn = spl[0]
    if idn not in idsYvn:
        print(idn,row["Name"])

25ry-d5r8 Highway Traffic Counts in Colorado 2017 Map
uman-zjh4 Census in Colorado 2017 Map
azt3-ee77 Census in Colorado 2018 Map
dqd2-3hbj Points of Interest in Denver - Map
mmq3-xrh7 Tree Canopy Assesment Denver - Map
v328-h7vn Map of Recently Approved Liquor Licenses in Colorado
92n9-xx4r Map of Liquor Licenses in Colorado
5jme-s3qi Census Places in Colorado 2018 Map
8q7d-v9sc Census Congressional Districts in Colorado 2018 Map
8bxs-9ctd Census Congressional Districts in Colorado 2019 Map
i6vs-j5v9 Census Tracts in Colorado 2019 Map
pkue-zrfg Business Improvement Districts in Denver Map
r8uq-quqp Census Tracts in Colorado 2018 Map
fwyp-a5y7 EV Charging and Alternative Fuels Stations in Colorado Map
ibr3-r5n3 Census Places in Colorado 2017 Map
fcvc-7tkz Census Places in Colorado 2019 Map
w9zf-5neg Highway Traffic Counts in Colorado 2016 Map
es4r-wt2k Census Block Groups in Colorado 2018 Map
g7tq-rkfe Map of Sales Rooms in Colorado
ewqz-5hmi Scenic Byways in Colorado Map
rm7t-rch9 Census Counties in Colorado 2019 Map
au4m-9k5p Census Zip Codes in Colorado 2018 Map
3nde-6qne Census Counties in Colorado 2019 Map
kje4-ci7c Census Zip Codes in Colorado 2019 Map
kzrg-3rgm Census Counties in Colorado 2017 - Map
x4sv-war6 Map of Recently Expired and Surrendered Liquor Licenses in Colorado
ws2k-4zj6 General Improvement Districts in Denver
yt78-xpzf Neighborhood Business Revitalization Corridors in Denver
a26p-3wtg Vacant Commercial / Industial Parcels
hzmx-2dfk Tree Inventory of Denver - Map
ssuw-z5kg Census Block Groups in Colorado 2017 Map
dms8-ujea Census Tracts in Colorado 2017 Map
c3rd-t2me Census in Colorado 2019 Map
gbbd-diue Census Congressional Districts in Colorado 2018 Map
envj-hfws Parcels in Denver Map
fkrf-c7qd Food Stores in Denver Map

In [15]:
#  Datasets in Tyler list NOT IN our inventory
nmiss=0
owners = {}
for index,row in dfYvn.iterrows():
    id=row["uid"]
    if id not in idsCimMap:
         nmiss+=1
         tmp = df1.loc[df1["UID"] == id,"Owner"].values.tolist()
         for own in tmp:
             if own not in owners:
                owners[own]=0
             owners[own]+= 1
         print(id,row["name"])
         # print(tmp)
         # print("-------------------------")

38bt-frhw ADA Curb Ramp Inventory
eqi3-a27g ADA Curb Ramp Inventory
au67-c4ig All Haz Reg Test Split
p3i7-jjzd CDOT Curb Ramp Inventory: ADA Compliance Factors
szhr-pc3j CDPHE MAP PACKAGE HFACILITIES 2013
w4kj-bsss CO County Boundry
dbeg-r7bz Census Zipcodes 2010
squa-cqq6 Cities
cz3y-bbuv Colo Counties
nvz8-4p3b Colorado Counties (1)
434q-2p8p Colorado Counties Colors
dxhx-4q4y Colorado Counties
p753-497k Colorado Counties
ygbf-cga5 Colorado Counties
jvug-2qau Comminity Anchor Institutions in Colorado 2016
ysa7-n95j Community Anchor Institutions 2017
b6x9-m3zy DOLA Housing Project
6g4b-w8bd Denver Statistical Neighborhoods
nsba-2nqt Garfield County Boundary
seg6-525n Garfield County Incorporated Cities & Towns
ai9y-w2g5 Garfield County Major Rivers & Bodies of Water
7548-bu6k Garfield County Parcels
7bpv-6pjt Garfield County Points Of Interest
wair-rh7k Garfield County Public Buildings
b8i8-bzje Garfield County Roads
qkcy-pt7c Garfield County Structures
rrtm-iex5 Hydrology Basins Phases
eadv-im9p Muni Bounds - GISImporter TEST
736u-4p72 NWregion Dissolve
8d3p-cg3d NWregion Purple
pr98-stac North West Region
5fr4-z8t9 Noxious Weeds
eh8z-dvax Police Agencies Geocoded
su5p-zu9y Police Districts in Colorado
39nj-8s56 US Counties
yk4s-me3x Watershed Coalition Boundaries
7w8w-7j4p Weedtest
vxve-j39m Weedtest2
sm5v-sev2 Workforce Centers

In [16]:
owners

{'Steve Ruge - CDOT': 3,
 'Dan Martinez': 9,
 'camillid': 4,
 'April Broome': 1,
 'Jack Reed': 2,
 'Tudor Stanescu': 1,
 'OIT - GIS': 4,
 'mrmspyker': 1,
 'Garfield County GIS': 8,
 'Adrian': 1,
 'Colorado Information Marketplace': 2,
 'Jessica Potter': 2,
 'Brandon.Serna': 1}

## Result # 1

 Of the 161 datasets, 37 or now owned by CIM.  None of the 37 are related to the Census, so they would be from the 65 Non Census datasets I would send.  Therefore, I will send our list instead of Yvonnes and note it to them.

In [17]:
dfCIMMapNoCen.columns

Index(['UID', 'Name', 'Description', 'Owner', 'Owner UID', 'Publication Stage',
       'Audience', 'Approval Status', 'Provenance', 'Type',
       ...
       'Data Quality: Stewardship Plan', 'Data Updates: Update Schedule',
       'Data Updates: Total Columns at Recent Update',
       'Dataset Summary: Progress',
       'Additional Dataset Documentation: Data Dictionary',
       'Department Metrics: Publishing Department',
       'Data Description: Oldest Record in Dataset',
       'Dataset Summary: Sub Agency',
       'Data Description: Date of Initial Dataset Creation',
       'Data Description: Collection Mode'],
      dtype='object', length=111)

In [18]:
dfCIMMapNoCen[['UID', 'Name', 'Owner','Audience','Type']].to_csv("Map_Datasets_NoCensus.csv",index=False)

## Census Datasets

In [19]:
dfCIMMapCen.shape

(92, 111)

In [21]:
def getFields(w4x4=""):
    '''Reads the Inventory google sheet and getsthe fields by 4x4 dataset id and by the title'''
    bic_etl_home = os.getenv('bic_etl_home')
    print("------------")
    print("Get Fields starting",bic_etl_home)
    print("------------")

## Add the bic_etl/general/script directory to path 
    sys.path.insert(0, os.path.join(bic_etl_home, 'general', 'scripts'))

    SERVICE_ACCOUNT_FILE = os.path.join("/home","joe", 'work',"client_secret.json")
    print(SERVICE_ACCOUNT_FILE)
    scope = ['https://www.googleapis.com/auth/spreadsheets.readonly',
             "https://www.googleapis.com/auth/drive"]

    creds = ServiceAccountCredentials.from_json_keyfile_name(SERVICE_ACCOUNT_FILE,
     scope)
    client = gspread.authorize(creds)

    fields_sheet = client.open('BIC Data Inventory and Metadata').worksheet(
        'MetadataRepository')
    
    print("field sheet",fields_sheet)

    dfFields = pd.DataFrame(fields_sheet.get_all_records(head=3))
    
    fields = {}
    for index,row in dfFields.iterrows():
        s4x4 = row["Socrata Link"].strip()
        a4x4 = row["API 4x4"].strip()
        fields[s4x4] = a4x4
  
    return fields

fields = getFields()

------------
Get Fields starting /home/joe/bic_etl
------------
/home/joe/work/client_secret.json
field sheet <Worksheet 'MetadataRepository' id:323813469>

In [37]:
errs = {}
no = []
yes = []
data = {}
nrows = dfCIMMapCen.shape[0]
count=0
for index,row in dfCIMMapCen.iterrows():
   count+=1
   id = row["UID"]
   name = row["Name"]
   if id in fields:
        api = fields[id]
        print("API ",api)
   else:
        api = id
        print("NO API",api)
   string = f"https://data.colorado.gov/api/views/{api}/rows.csv?accessType=DOWNLOAD"
   print(name)
   print(f"{count} of {nrows}: {string}")
   try:
     df = pd.read_csv(string)
     yes.append(id)
     print("hit",len(yes))
     data[id] = {}
     data[id]['name'] = name
     data[id]['shape'] = df.shape
    
    
     data[id]['data'] = df.head()
     print("-------------------\n")
        
   except Exception as err:
      no.append(id)
      errs[id] = err
      print(err)
      print("------------------------------------\n")

API  kt3p-393c
Census Places in Colorado 2012
1 of 92: https://data.colorado.gov/api/views/kt3p-393c/rows.csv?accessType=DOWNLOAD
hit 1
-------------------

API  rt3s-2378
Census Tracts in Colorado 2010
2 of 92: https://data.colorado.gov/api/views/rt3s-2378/rows.csv?accessType=DOWNLOAD
hit 2
-------------------

API  eghh-ua8y
Census Counties in Colorado 2016
3 of 92: https://data.colorado.gov/api/views/eghh-ua8y/rows.csv?accessType=DOWNLOAD
hit 3
-------------------

NO API uman-zjh4
Census in Colorado 2017 Map
4 of 92: https://data.colorado.gov/api/views/uman-zjh4/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

NO API azt3-ee77
Census in Colorado 2018 Map
5 of 92: https://data.colorado.gov/api/views/azt3-ee77/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

API  n5xr-summ
Census Places in Colorado 2014
6 of 92: https://data.colorado.gov/api/views/n5xr-summ/rows.csv?accessType=DOWNLOAD
hit 4
-------------------

API  s35f-5c94
Census Congressional Districts in Colorado 2014
7 of 92: https://data.colorado.gov/api/views/s35f-5c94/rows.csv?accessType=DOWNLOAD
hit 5
-------------------

API  a85s-zxvh
Census Core Based Statistical Area in Colorado 2011
8 of 92: https://data.colorado.gov/api/views/a85s-zxvh/rows.csv?accessType=DOWNLOAD
hit 6
-------------------

API  eu3v-3d3m
Census Zip Codes SF1 in Colorado 2000
9 of 92: https://data.colorado.gov/api/views/eu3v-3d3m/rows.csv?accessType=DOWNLOAD
hit 7
-------------------

API  kd4i-r65w
Census Core Based Statistical Area in Colorado 2012
10 of 92: https://data.colorado.gov/api/views/kd4i-r65w/rows.csv?accessType=DOWNLOAD
hit 8
-------------------

API  etbc-tkgn
Census County Subdivisions in Colorado 2012
11 of 92: https://data.colorado.gov/api/views/etbc-tkgn/rows.csv?accessType=DOWNLOAD
hit 9
-------------------

API  ivcq-5wnv
Census County Subdivisions SF3 in Colorado 2000
12 of 92: https://data.colorado.gov/api/views/ivcq-5wnv/rows.csv?accessType=DOWNLOAD
hit 10
-------------------

API  muph-8jnm
Census Block Groups in Colorado 2013
13 of 92: https://data.colorado.gov/api/views/muph-8jnm/rows.csv?accessType=DOWNLOAD
hit 11
-------------------

API  4mk5-vv45
Census ACS Counties in Colorado 2011
14 of 92: https://data.colorado.gov/api/views/4mk5-vv45/rows.csv?accessType=DOWNLOAD
hit 12
-------------------

API  fcyp-mtss
Census Zip Codes in Colorado 2012
15 of 92: https://data.colorado.gov/api/views/fcyp-mtss/rows.csv?accessType=DOWNLOAD
hit 13
-------------------

API  m3j7-raj9
Census Counties in Colorado 2013
16 of 92: https://data.colorado.gov/api/views/m3j7-raj9/rows.csv?accessType=DOWNLOAD
hit 14
-------------------

API  7e99-m9fd
Census in Colorado 2015
17 of 92: https://data.colorado.gov/api/views/7e99-m9fd/rows.csv?accessType=DOWNLOAD
hit 15
-------------------

API  jkfh-gi5i
Census Counties in Colorado 2010
18 of 92: https://data.colorado.gov/api/views/jkfh-gi5i/rows.csv?accessType=DOWNLOAD
hit 16
-------------------

API  85u5-cuz2
Census County Subdivisions SF1 in Colorado 2000
19 of 92: https://data.colorado.gov/api/views/85u5-cuz2/rows.csv?accessType=DOWNLOAD
hit 17
-------------------

API  pgs5-k2ve
Census Block Groups in Colorado 2012
20 of 92: https://data.colorado.gov/api/views/pgs5-k2ve/rows.csv?accessType=DOWNLOAD
hit 18
-------------------

API  dwez-qzwp
Census Tracts in Colorado 2014
21 of 92: https://data.colorado.gov/api/views/dwez-qzwp/rows.csv?accessType=DOWNLOAD
hit 19
-------------------

NO API 5jme-s3qi
Census Places in Colorado 2018 Map
22 of 92: https://data.colorado.gov/api/views/5jme-s3qi/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

API  8hh9-tn7j
Census State of Colorado 2013
23 of 92: https://data.colorado.gov/api/views/8hh9-tn7j/rows.csv?accessType=DOWNLOAD
hit 20
-------------------

API  k73m-yqwy
Census Places SF1 in Colorado 2000
24 of 92: https://data.colorado.gov/api/views/k73m-yqwy/rows.csv?accessType=DOWNLOAD
hit 21
-------------------

API  49x6-nvb5
Census Blocks in Colorado 2010
25 of 92: https://data.colorado.gov/api/views/49x6-nvb5/rows.csv?accessType=DOWNLOAD
hit 22
-------------------

API  uzap-vkkz
Census Core Based Statistical Area in Colorado 2010
26 of 92: https://data.colorado.gov/api/views/uzap-vkkz/rows.csv?accessType=DOWNLOAD
hit 23
-------------------

API  vefd-xfvu
Census Block Groups SF3 in Colorado 2000
27 of 92: https://data.colorado.gov/api/views/vefd-xfvu/rows.csv?accessType=DOWNLOAD
hit 24
-------------------

NO API 8q7d-v9sc
Census Congressional Districts in Colorado 2018 Map
28 of 92: https://data.colorado.gov/api/views/8q7d-v9sc/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

NO API 8bxs-9ctd
Census Congressional Districts in Colorado 2019 Map
29 of 92: https://data.colorado.gov/api/views/8bxs-9ctd/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

API  gx4f-gkav
Census Places in Colorado 2010
30 of 92: https://data.colorado.gov/api/views/gx4f-gkav/rows.csv?accessType=DOWNLOAD
hit 25
-------------------

API  3yjp-6a33
Census Zip Codes in Colorado 2013
31 of 92: https://data.colorado.gov/api/views/3yjp-6a33/rows.csv?accessType=DOWNLOAD
hit 26
-------------------

API  jfqj-df4i
Census State SF1 in Colorado 2000
32 of 92: https://data.colorado.gov/api/views/jfqj-df4i/rows.csv?accessType=DOWNLOAD
hit 27
-------------------

API  jppe-46v2
Census Tracts in Colorado 2011
33 of 92: https://data.colorado.gov/api/views/jppe-46v2/rows.csv?accessType=DOWNLOAD
hit 28
-------------------

API  ws3z-urxq
Census Tracts in Colorado 2015
34 of 92: https://data.colorado.gov/api/views/ws3z-urxq/rows.csv?accessType=DOWNLOAD
hit 29
-------------------

NO API i6vs-j5v9
Census Tracts in Colorado 2019 Map
35 of 92: https://data.colorado.gov/api/views/i6vs-j5v9/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

API  mwv9-ygsf
Census Places in Colorado 2016
36 of 92: https://data.colorado.gov/api/views/mwv9-ygsf/rows.csv?accessType=DOWNLOAD
hit 30
-------------------

API  q9ua-9k3d
Census School Districts in Colorado 2010
37 of 92: https://data.colorado.gov/api/views/q9ua-9k3d/rows.csv?accessType=DOWNLOAD
hit 31
-------------------

API  rxks-zb9z
Census Combined Statistical Area in Colorado 2011
38 of 92: https://data.colorado.gov/api/views/rxks-zb9z/rows.csv?accessType=DOWNLOAD
hit 32
-------------------

NO API r8uq-quqp
Census Tracts in Colorado 2018 Map
39 of 92: https://data.colorado.gov/api/views/r8uq-quqp/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

API  a5gi-9pma
Census Combined Statistical Area in Colorado 2012
40 of 92: https://data.colorado.gov/api/views/a5gi-9pma/rows.csv?accessType=DOWNLOAD
hit 33
-------------------

API  jiwb-nqtz
Census Places SF3 in Colorado 2000
41 of 92: https://data.colorado.gov/api/views/jiwb-nqtz/rows.csv?accessType=DOWNLOAD
hit 34
-------------------

API  8d8p-eabg
Census State SF3 in Colorado 2000
42 of 92: https://data.colorado.gov/api/views/8d8p-eabg/rows.csv?accessType=DOWNLOAD
hit 35
-------------------

NO API ibr3-r5n3
Census Places in Colorado 2017 Map
43 of 92: https://data.colorado.gov/api/views/ibr3-r5n3/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

API  umwy-67rm
Census Tracts in Colorado 2016
44 of 92: https://data.colorado.gov/api/views/umwy-67rm/rows.csv?accessType=DOWNLOAD
hit 36
-------------------

NO API fcvc-7tkz
Census Places in Colorado 2019 Map
45 of 92: https://data.colorado.gov/api/views/fcvc-7tkz/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

API  gtau-pbhu
Census Places in Colorado 2015
46 of 92: https://data.colorado.gov/api/views/gtau-pbhu/rows.csv?accessType=DOWNLOAD
hit 37
-------------------

API  vx8e-g83x
Census State in Colorado 2012
47 of 92: https://data.colorado.gov/api/views/vx8e-g83x/rows.csv?accessType=DOWNLOAD
hit 38
-------------------

NO API es4r-wt2k
Census Block Groups in Colorado 2018 Map
48 of 92: https://data.colorado.gov/api/views/es4r-wt2k/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

API  bxxi-pypt
Census Tracts in Colorado 2013
49 of 92: https://data.colorado.gov/api/views/bxxi-pypt/rows.csv?accessType=DOWNLOAD
hit 39
-------------------

API  4t5f-mp2t
Census Zip Codes in Colorado 2014
50 of 92: https://data.colorado.gov/api/views/4t5f-mp2t/rows.csv?accessType=DOWNLOAD
HTTP Error 404: Not Found
------------------------------------

API  wshk-29g7
Census Counties in Colorado 2014
51 of 92: https://data.colorado.gov/api/views/wshk-29g7/rows.csv?accessType=DOWNLOAD
hit 40
-------------------

API  f4n4-vnyx
Census Counties in Colorado 2012
52 of 92: https://data.colorado.gov/api/views/f4n4-vnyx/rows.csv?accessType=DOWNLOAD
hit 41
-------------------

API  55mv-2ynf
Census Zip Codes in Colorado 2016
53 of 92: https://data.colorado.gov/api/views/55mv-2ynf/rows.csv?accessType=DOWNLOAD
HTTP Error 404: Not Found
------------------------------------

API  t48m-528x
Census Counties in Colorado 2015
54 of 92: https://data.colorado.gov/api/views/t48m-528x/rows.csv?accessType=DOWNLOAD
hit 42
-------------------

API  2czt-qzar
Census School Districts in Colorado 2012
55 of 92: https://data.colorado.gov/api/views/2czt-qzar/rows.csv?accessType=DOWNLOAD
hit 43
-------------------

API  5733-dk6i
Census Combined Statistical Area in Colorado 2010
56 of 92: https://data.colorado.gov/api/views/5733-dk6i/rows.csv?accessType=DOWNLOAD
hit 44
-------------------

API  k2sh-64zx
Census School Districts in Colorado 2011
57 of 92: https://data.colorado.gov/api/views/k2sh-64zx/rows.csv?accessType=DOWNLOAD
hit 45
-------------------

API  tukx-q8v8
Census Congressional Districts in Colorado 2015
58 of 92: https://data.colorado.gov/api/views/tukx-q8v8/rows.csv?accessType=DOWNLOAD
hit 46
-------------------

NO API rm7t-rch9
Census Counties in Colorado 2019 Map
59 of 92: https://data.colorado.gov/api/views/rm7t-rch9/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

NO API au4m-9k5p
Census Zip Codes in Colorado 2018 Map
60 of 92: https://data.colorado.gov/api/views/au4m-9k5p/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

API  2rrq-heiy
Census State in Colorado 2011
61 of 92: https://data.colorado.gov/api/views/2rrq-heiy/rows.csv?accessType=DOWNLOAD
hit 47
-------------------

NO API 3nde-6qne
Census Counties in Colorado 2019 Map
62 of 92: https://data.colorado.gov/api/views/3nde-6qne/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

NO API kje4-ci7c
Census Zip Codes in Colorado 2019 Map
63 of 92: https://data.colorado.gov/api/views/kje4-ci7c/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

API  7qc8-fj3p
Census County Subdivisions in Colorado 2011
64 of 92: https://data.colorado.gov/api/views/7qc8-fj3p/rows.csv?accessType=DOWNLOAD
hit 48
-------------------

API  xf9x-4vrx
Census Counties SF3 in Colorado 2000
65 of 92: https://data.colorado.gov/api/views/xf9x-4vrx/rows.csv?accessType=DOWNLOAD
hit 49
-------------------

API  385d-6w27
Census Tracts in Colorado 2012
66 of 92: https://data.colorado.gov/api/views/385d-6w27/rows.csv?accessType=DOWNLOAD
hit 50
-------------------

API  bv6m-vkmf
Census State in Colorado 2010
67 of 92: https://data.colorado.gov/api/views/bv6m-vkmf/rows.csv?accessType=DOWNLOAD
hit 51
-------------------

NO API kzrg-3rgm
Census Counties in Colorado 2017 - Map
68 of 92: https://data.colorado.gov/api/views/kzrg-3rgm/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

API  ibr4-saca
Census Tracts SF1 in Colorado 2000
69 of 92: https://data.colorado.gov/api/views/ibr4-saca/rows.csv?accessType=DOWNLOAD
hit 52
-------------------

API  m6cj-y4yw
Census Block Groups SF1 in Colorado 2000
70 of 92: https://data.colorado.gov/api/views/m6cj-y4yw/rows.csv?accessType=DOWNLOAD
hit 53
-------------------

API  jz4n-qus2
Census Congressional Districts in Colorado 2016
71 of 92: https://data.colorado.gov/api/views/jz4n-qus2/rows.csv?accessType=DOWNLOAD
hit 54
-------------------

API  imy5-eits
Census County Subdivisions in Colorado 2010
72 of 92: https://data.colorado.gov/api/views/imy5-eits/rows.csv?accessType=DOWNLOAD
hit 55
-------------------

API  rz4c-na6y
Census Block Groups in Colorado 2015
73 of 92: https://data.colorado.gov/api/views/rz4c-na6y/rows.csv?accessType=DOWNLOAD
hit 56
-------------------

API  93kh-r488
Census Block Groups in Colorado 2010
74 of 92: https://data.colorado.gov/api/views/93kh-r488/rows.csv?accessType=DOWNLOAD
hit 57
-------------------

API  rue4-ebee
Census Places in Colorado 2011
75 of 92: https://data.colorado.gov/api/views/rue4-ebee/rows.csv?accessType=DOWNLOAD
hit 58
-------------------

API  grnx-2zwm
Census in Colorado 2016
76 of 92: https://data.colorado.gov/api/views/grnx-2zwm/rows.csv?accessType=DOWNLOAD
hit 59
-------------------

API  kyzd-u4zr
Census Blocks in Colorado 2000
77 of 92: https://data.colorado.gov/api/views/kyzd-u4zr/rows.csv?accessType=DOWNLOAD
hit 60
-------------------

API  vdki-aa5n
Census Places in Colorado 2013
78 of 92: https://data.colorado.gov/api/views/vdki-aa5n/rows.csv?accessType=DOWNLOAD
hit 61
-------------------

API  sbcg-h3as
Census Counties SF1 in Colorado 2000
79 of 92: https://data.colorado.gov/api/views/sbcg-h3as/rows.csv?accessType=DOWNLOAD
hit 62
-------------------

API  ic5a-quwv
Census Block Groups in Colorado 2011
80 of 92: https://data.colorado.gov/api/views/ic5a-quwv/rows.csv?accessType=DOWNLOAD
hit 63
-------------------

NO API ssuw-z5kg
Census Block Groups in Colorado 2017 Map
81 of 92: https://data.colorado.gov/api/views/ssuw-z5kg/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

API  kchu-pwtk
Census Congressional Districts in Colorado 2013
82 of 92: https://data.colorado.gov/api/views/kchu-pwtk/rows.csv?accessType=DOWNLOAD
hit 64
-------------------

API  594w-hhep
Census Block Groups in Colorado 2016
83 of 92: https://data.colorado.gov/api/views/594w-hhep/rows.csv?accessType=DOWNLOAD
hit 65
-------------------

API  adbb-iu37
Census Block Groups in Colorado 2014
84 of 92: https://data.colorado.gov/api/views/adbb-iu37/rows.csv?accessType=DOWNLOAD
hit 66
-------------------

API  vy7p-ixjg
Census Zip Codes SF3 in Colorado 2000
85 of 92: https://data.colorado.gov/api/views/vy7p-ixjg/rows.csv?accessType=DOWNLOAD
hit 67
-------------------

API  ehbb-wpcw
Census Tracts SF3 in Colorado 2000
86 of 92: https://data.colorado.gov/api/views/ehbb-wpcw/rows.csv?accessType=DOWNLOAD
hit 68
-------------------

API  wwwp-4j5y
Census in Colorado 2014
87 of 92: https://data.colorado.gov/api/views/wwwp-4j5y/rows.csv?accessType=DOWNLOAD
hit 69
-------------------

API  v6qp-6csn
Census Zip Codes in Colorado 2015
88 of 92: https://data.colorado.gov/api/views/v6qp-6csn/rows.csv?accessType=DOWNLOAD
hit 70
-------------------

NO API dms8-ujea
Census Tracts in Colorado 2017 Map
89 of 92: https://data.colorado.gov/api/views/dms8-ujea/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

NO API c3rd-t2me
Census in Colorado 2019 Map
90 of 92: https://data.colorado.gov/api/views/c3rd-t2me/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

NO API gbbd-diue
Census Congressional Districts in Colorado 2018 Map
91 of 92: https://data.colorado.gov/api/views/gbbd-diue/rows.csv?accessType=DOWNLOAD
No columns to parse from file
------------------------------------

API  7jyi-58ux
Census Zip Codes in Colorado 2010
92 of 92: https://data.colorado.gov/api/views/7jyi-58ux/rows.csv?accessType=DOWNLOAD
hit 71
-------------------

In [27]:
no

['uman-zjh4',
 'azt3-ee77',
 '5jme-s3qi',
 '8q7d-v9sc',
 '8bxs-9ctd',
 'i6vs-j5v9',
 'r8uq-quqp',
 'ibr3-r5n3',
 'fcvc-7tkz',
 'es4r-wt2k',
 'vne4-cwmy',
 'rwak-e74e',
 'rm7t-rch9',
 'au4m-9k5p',
 '3nde-6qne',
 'kje4-ci7c',
 'kzrg-3rgm',
 'ssuw-z5kg',
 'dms8-ujea',
 'c3rd-t2me',
 'gbbd-diue']

In [28]:
fields

{'rifs-n6ib': 'rifs-n6ib',
 'c8jj-hcxj': 'nigi-mnyx',
 '82s5-cpkk': '82s5-cpkk',
 'n55r-9hud': 'n55r-9hud',
 'ms6b-y4xc': 'ms6b-y4xc',
 'e6e8-qmi7': 'px7t-j3xt',
 'hxf8-ab6k': 'yt5k-hawq',
 'p8m4-v33g': 'vgwh-ygn3',
 'g53r-j5td': '6pd5-jdur',
 'jnj7-fw37': 'jnj7-fw37',
 'gyeb-jc69': '9gxp-sqz6',
 'u2t6-bfhr': 'iw7e-tqkz',
 'cjkq-q9ih': 'iaz7-gn2p',
 '4e3w-qire': 'da3r-y7xz',
 'busm-qa5b': 'vu7j-izta',
 '2cpa-vbur': 'udxx-a7kq',
 'bu8h-8sux': 'suda-myfn',
 'pt2g-89wc': '7rd3-4hgz',
 'bynd-i2hj': 'cy35-ndjp',
 'k3gg-hhc8': 'k3gg-hhc8',
 'x8tb-f3vh': 'x8tb-f3vh',
 '2yhn-3dbj': '2yhn-3dbj',
 '6kn4-89kh': '6kn4-89kh',
 '869n-zj3f': '869n-zj3f',
 'sqs8-2un5': 'sqs8-2un5',
 '3sm5-jtur': '3sm5-jtur',
 'ehk3-i5tr': 'ehk3-i5tr',
 'v9m8-x8dh': 'v9m8-x8dh',
 'j7a3-jgd3': 'j7a3-jgd3',
 'kapc-ib6e': 'ii5c-5549',
 'htyp-tqzh': 'htyp-tqzh',
 'ier5-5ms2': 'ier5-5ms2',
 'pwjb-9dd5': 'pwjb-9dd5',
 '9pwz-gi5v': 'ic4i-9zku',
 'd4s4-xqg6': '394i-tr5f',
 'msap-49q7': 'msap-49q7',
 'wz8h-dap6': 'wz8h-dap6',
 'g62i-kdzu': 'g62i-kdzu',
 'ifza-iedd': 'ifza-iedd',
 'y6w6-igw6': 'y6w6-igw6',
 'hysf-mrke': 'hysf-mrke',
 'n9gj-cjub': 'n9gj-cjub',
 'qtga-qgdf': 'qtga-qgdf',
 's9wt-dsfz': 's9wt-dsfz',
 'xi27-7j3e': 'xi27-7j3e',
 '6ntv-x37b': '6ntv-x37b',
 'd6t8-xish': 'tkre-uiwn',
 'hbkb-4hbj': 'pij9-wuvb',
 'pdd3-umrz': '35ps-yuib',
 'rjvq-j29g': 'kq2r-s8hw',
 'fe4v-h3pk': 'smy5-uetg',
 'ax6t-kdim': 'qzw4-fgg6',
 'h5yt-egtp': 'tzjn-r68r',
 'kch9-6p6i': 'd2hz-7rd9',
 'nd6a-59yu': 'jkz5-7nit',
 'wx84-he7r': 'trzr-qjr4',
 '4zse-6bnw': 'qzbt-feti',
 'e7wz-djhw': 'e7wz-djhw',
 '34aw-ny67': '34aw-ny67',
 'k4uv-yvnk': 'ubw3-w6rt',
 'tuvj-xz3m': 'tuvj-xz3m',
 's7ct-nf65': '3ck3-ek9d',
 '35k5-cv8s': 'dm35-83um',
 'bqa5-gr84': '4xaw-3ja7',
 'eqsm-7ah7': 'wkgc-9sne',
 'g89g-muvw': 'kr2z-56yf',
 'gcmk-9nwy': '37vx-jsnr',
 'gxnn-wthy': 'a2bk-zr8i',
 'casm-dbbj': 'hu3b-43c7',
 '2z9k-uy4q': 'pg4y-bhfp',
 '5wyf-xqw7': 'aatx-m2pf',
 'ew9y-6tv9': 'nj9v-fjwa',
 'w6kb-3vsj': 'duaz-bid8',
 'wwhd-vg25': '5kgu-ujzf',
 'fdcw-ei67': 'ymw6-c5vm',
 '37wu-kn3g': 'p3jp-z4tq',
 '7jm9-f28m': 'yvrn-kew4',
 'hyr8-d3v9': 'aaag-hy62',
 'mr4v-jz8u': 'vjpn-wxi8',
 '3qtu-edua': '26xp-8dwd',
 'q2av-rpr5': '9rpm-ca44',
 'wwbh-7bpa': 'i3cf-f6qs',
 'icqv-mi3c': 'j6pz-h6b7',
 'd3m2-b6we': '32mi-brje',
 'ej2c-jkvh': 'h28s-f3n9',
 'u7sb-g482': 'bhcc-9bdx',
 'x5bw-ax3d': 'wj25-kxs8',
 'q2qp-xhnj': 'rk4k-4n2k',
 'n5ku-eixc': 'n5ku-eixc',
 'rkmy-yymq': 'rkmy-yymq',
 '2kvt-7ybu': '2kvt-7ybu',
 '7nuk-vzhq': 'g749-y462',
 'dnyf-3m59': 'ibqw-39av',
 'ihbp-hi2s': 'kp53-5p45',
 '7bzf-viss': 'py3d-8rcb',
 '67vn-ijga': 'ahgn-r8s5',
 'gemu-wyf3': 'whvu-66s7',
 '9syq-9vv5': 'xv9c-7iqh',
 'trm9-dm4m': '2ivx-wb7h',
 '49ck-u67r': 'bw7c-66ew',
 'uhup-hcc4': 'k5jg-kjbh',
 'd6bh-7i9s': '4rpn-vqpu',
 '7amf-p4uj': 'q2m8-2gk3',
 'skxn-j975': 'skxn-j975',
 'xs2v-uzeg': 'i7qk-ahka',
 '6aqe-63uq': '6aqe-63uq',
 '4h6z-rhfw': '4hz3-qup8',
 '3bgg-gcfa': 'sms6-dzsz',
 'ue4w-dnyi': 'ue4w-dnyi',
 '4vf9-vbyi': '4vf9-vbyi',
 '56kc-gpid': '56kc-gpid',
 'fbn4-ype4': 'fbn4-ype4',
 '2h6w-z9ry': 'phvc-rwei',
 '7sv7-7d5a': 'ddci-aui8',
 'uksn-8qya': 'fv4u-jgb3',
 'qvrk-xsmj': 'nxhx-5jh3',
 'e7ye-tasg': 'ah2h-6fx9',
 '8hx8-24k6': 'meem-5sxj',
 't8ag-kzkw': '3p4c-fm5u',
 'sfvq-tb9q': 'fsyh-pm89',
 'mguq-rjzb': '9mid-gqwm',
 'hpem-wb68': '2tib-gtif',
 'j8pu-22qi': 'ywaw-cfpm',
 'cdva-fnp3': 'df48-rqfu',
 'gi9w-h59d': 'dgjp-iua8',
 'nbem-wipy': 'ezkd-u92f',
 '9ghp-7fx6': '36jf-z7v4',
 'uiuh-m69w': 'vigw-75nf',
 'dx5q-y5je': 'iqyg-cdrz',
 '3b56-km3g': '3b56-km3g',
 'x5dz-rik8': 'x5dz-rik8',
 'uzf4-3qtt': 'uzf4-3qtt',
 'bk6n-e4g7': 'bk6n-e4g7',
 '4j38-u7sj': '4j38-u7sj',
 'emmy-a4kg': 'neii-3ga4',
 'vqzj-5nyt': '2jqz-wx74',
 'gh3v-k494': '8i9r-ecqh',
 '4qh9-evw6': 'sb9m-ecvv',
 'x238-vje7': 'sqxp-g37g',
 'inae-mki6': 'inae-mki6',
 'hwz6-96jc': '',
 'j6g4-gayk': 'j6g4-gayk',
 '6vnq-az4b': '6vnq-az4b',
 '2e5i-5hfy': 'ci9y-twe5',
 'ya69-n6ta': 'fc73-cgrc',
 'nymn-sjs9': 'nxsb-d2uu',
 'et6s-ufjm': '4y5q-y4pt',
 'uir2-bpe7': 'nbrq-f8ym',
 'itzi-4q6v': 'xxgw-kkry',
 'q2iw-kpix': 'q2iw-kpix',
 '7s5z-vewr': 'idu3-cuww',
 '3kjc-z9fd': '3kjc-z9fd',
 'mqid-8hv2': 'auv6-u3qc',
 'ffjg-bf34': 'ffjg-bf34',
 'iuxm-ddzz': 'iuxm-ddzz',
 'bjhg-77mf': 'bjhg-77mf',
 'ucnv-vw74': 'ucnv-vw74',
 '86h6-mdkh': '86h6-mdkh',
 'tbmm-ubn9': 'tbmm-ubn9',
 'q56w-zzzm': 'q56w-zzzm',
 'ph72-axst': 'ph72-axst',
 'smjm-6h6g': 'smjm-6h6g',
 'ekih-pydt': 'ekih-pydt',
 'ge9s-ra8y': 'ge9s-ra8y',
 'spwe-6ca7': 'spwe-6ca7',
 'jwbw-xb7i': 'jwbw-xb7i',
 'qjuy-fmh4': 'qjuy-fmh4',
 'cj4m-96y8': 'cj4m-96y8',
 '7t53-5gfx': '7t53-5gfx',
 'xum2-smvh': 'xum2-smvh',
 '8j3i-rjn4': '8j3i-rjn4',
 'rt7b-823p': 'rt7b-823p',
 't2jr-8j7z': 't2jr-8j7z',
 'xpi4-stak': 'xpi4-stak',
 '33q3-djk8': '33q3-djk8',
 'g598-t929': 'g598-t929',
 '3u6n-menq': '3u6n-menq',
 'jycn-t6wi': 'jycn-t6wi',
 '7i2s-r6pd': '7i2s-r6pd',
 'aevh-apr2': 'aevh-apr2',
 'ewkj-ipn7': 'ewkj-ipn7',
 'ty5m-9xub': 'ty5m-9xub',
 'qten-sdpn': 'qten-sdpn',
 'vcag-iwy7': 'vcag-iwy7',
 'mqbr-wyyb': 'wwwp-4j5y',
 '7m6d-cpmt': 'grnx-2zwm',
 'ab5h-juwk': 'tz69-nqfv',
 'wv7f-qjj7': 'tek5-fkv6',
 'rwak-e74e': '55mv-2ynf',
 'v4as-sthd': '3wx6-h3cs',
 'ty6r-gpdz': 'kchu-pwtk',
 'gafi-svtb': 's35f-5c94',
 '3djr-p9q9': 'tukx-q8v8',
 '6fg8-f8c5': 'jz4n-qus2',
 '2chb-kzb6': 'mwv9-ygsf',
 'iku4-4bpx': '594w-hhep',
 'sn6p-34bq': 'eghh-ua8y',
 'tfrg-b5pp': 'umwy-67rm',
 '37uc-bdj5': 'fcyp-mtss',
 '3ftn-9s6k': '3yjp-6a33',
 'jd2b-7gyb': 'v6qp-6csn',
 'chpv-m4xq': 've36-qdic',
 'tn2f-pf3u': 'ue2w-bebj',
 '232d-4jxg': 'bxxi-pypt',
 '4zf4-r52a': 'vdki-aa5n',
 '9gri-r239': 'muph-8jnm',
 'v5m6-vhha': '8hh9-tn7j',
 'xymp-u28i': 'm3j7-raj9',
 '5yyk-mqmn': 't48m-528x',
 '6hee-tnp6': 'rz4c-na6y',
 'jc8p-yc8f': 'ws3z-urxq',
 't3uw-qtqc': 'gtau-pbhu',
 'xxfz-y2eq': '7e99-m9fd',
 '2p2k-iq7f': 's28a-3huk',
 'chnk-j6e5': 'r5py-vgrn',
 'cmr9-ue2w': 'yifv-9mje',
 'hwir-8ay9': 'ufkp-k5vs',
 'ixu8-bvqa': 'g6ci-vc3b',
 'mvn7-a28c': 'qwt4-f2pv',
 '9cn8-g4er': 'n5xr-summ',
 'f8ak-7nmp': 'wshk-29g7',
 'fifs-d43p': 'dwez-qzwp',
 'vne4-cwmy': '4t5f-mp2t',
 'cmkv-zd4f': 'adbb-iu37',
 '3thw-b7wj': '7myi-3bh6',
 '853a-s2qz': '5ku5-3ak6',
 '9h8i-6khx': 'q8mv-cahs',
 'd6bs-3kgu': 'rkr9-nd87',
 'dm2a-biqr': '7rar-v5z8',
 'esrk-9vjd': 'mm2p-ag5w',
 'fwb5-rzg5': '2h36-cxjh',
 'knbf-ggf2': '6mdp-xw2u',
 'ua3v-vcuh': '9s32-6t85',
 'wxzv-xh9i': 'nq9j-ybu4',
 '2ddb-srxn': 'a5gi-9pma',
 'fr27-d5rz': 'vx8e-g83x',
 'n53p-giqe': 'kt3p-393c',
 'p562-ke9a': 'k2sh-64zx',
 'qx2d-46a5': 'a85s-zxvh',
 'rntb-5cdp': '2rrq-heiy',
 'sdgy-egf7': 'rxks-zb9z',
 'ueer-yycc': 'rue4-ebee',
 'v56b-yh3u': 'kd4i-r65w',
 'xg8m-4prc': '2czt-qzar',
 '22bw-ijyi': '4mk5-vv45',
 '6gtx-i289': '7qc8-fj3p',
 'jjnc-cu9z': 'pgs5-k2ve',
 'mxmm-svgz': 'etbc-tkgn',
 'xh4c-32wb': 'jppe-46v2',
 'xwky-bmsn': 'f4n4-vnyx',
 'yqfw-dg5f': '385d-6w27',
 '6ddv-3hk2': 'ic5a-quwv',
 'r87x-h98m': 'kyzd-u4zr',
 '7yta-8qvv': 'jiwb-nqtz',
 '8vnm-57r6': 'ibr4-saca',
 'bd44-na6d': 'vy7p-ixjg',
 'c6qj-6kx2': 'k73m-yqwy',
 'cuid-432h': 'jfqj-df4i',
 'f3th-4ste': 'ivcq-5wnv',
 'fjhv-ruxa': '8d8p-eabg',
 'gvnt-p2w8': 'xf9x-4vrx',
 'khe9-7d2c': 'eu3v-3d3m',
 'nbfg-y9mh': 'm6cj-y4yw',
 'nnpy-czzx': '85u5-cuz2',
 'p674-r4hf': 'ehbb-wpcw',
 'us3j-cyz6': 'vefd-xfvu',
 'v4w4-3yz8': 'sbcg-h3as',
 'xipb-k5bu': '49x6-nvb5',
 '33fk-kb5q': '5733-dk6i',
 '94t6-d4wd': 'uzap-vkkz',
 '9b7x-qm8d': 'q9ua-9k3d',
 'gu6r-zvv2': 'rt3s-2378',
 'hcfi-bvst': 'gx4f-gkav',
 'hxnu-kp2f': 'imy5-eits',
 'kfm9-mvzv': '93kh-r488',
 'wcvg-8vki': '7jyi-58ux',
 'wtpp-eaj8': 'jkfh-gi5i',
 'x5e5-npqm': 'bv6m-vkmf',
 '5qqr-23dz': '9ucd-vbp8',
 'u943-ics6': 'vhut-u4rz',
 'q5vp-adf3': 'tv8u-hswn',
 '349y-twqi': 'ymww-exmk',
 'e4mf-ggwf': 'e4mf-ggwf',
 'a58g-ce2r': 'a58g-ce2r',
 '68n7-r6rp': '4wg3-tqyq',
 'ipm7-5rxr': 'ph23-52ee',
 'k26c-fz5q': 'hymk-uc38',
 'knby-gpaw': 'jeme-vzwk',
 'n5sw-qzbs': '92i4-sq8f',
 'u4xw-xiec': 'swg4-buem',
 'vewn-5ajx': '8i97-peax',
 'x2jf-bvk8': 'yha9-4ccf',
 'xb4j-dshc': 'mbbw-b2d6',
 'rkuy-jxyz': 'rkuy-jxyz',
 'm9tc-zgz8': 'm9tc-zgz8',
 '4am6-w6u4': 'xa32-xrhn',
 '4ykn-tg5h': '4eit-nuxn',
 'pxgq-s7pg': 'pxgq-s7pg',
 'vqx7-fwxd': 'vqx7-fwxd',
 'f325-6r9c': 'sdj2-eu7g',
 'rtw9-6tit': 'gjan-8bvh',
 '8upq-58vz': 'x6nk-8epw',
 'wffy-3uut': '8d38-bpb6',
 'unz2-68bn': 'kw3i-nbzq',
 'rpvk-ifh4': 'm2xu-8h22',
 'nxw4-ev8w': '3j8c-74kv',
 'jd4d-pcwx': 'qsdh-79ii',
 'e86d-vx82': 'g9ic-qkrx',
 'pfjr-vhp3': 'tad2-pzgf',
 'yree-6k9x': 'xtzv-jp5p',
 'fph6-vi4y': 'd7g2-77vf',
 'ii3b-uafi': 'qp93-8k7d',
 '5s6g-ze7t': 'b3y4-fgw8',
 'wpcp-usqg': 'a9xs-cha8',
 'yajv-ea35': 'smwj-ct9m',
 '9bzu-nqxb': 'cke2-rfdy',
 'fypu-tup4': 'u5s6-q8vu',
 '443p-eijy': 'ah76-cwyd',
 'team-3ugz': 'c7ve-fkni',
 'xiem-he2v': '',
 '6ad7-gqy3': 'yw89-ab4q',
 'ap62-sav4': '72ay-gvmj',
 '73ay-2ues': '73ay-2ues',
 '8ant-mn9d': '8ant-mn9d',
 'cx7q-izrb': 'p8vj-f8bc',
 '4yw9-a5y6': '4yw9-a5y6',
 'xwar-3geb': 'xwar-3geb',
 'ue5s-8u8t': 'he3j-mqae',
 '4jjg-g3yq': 'xv5c-h458',
 'cdkn-c7n9': 'tvek-dibi',
 'e4ky-6g2n': 'uxyf-4dfg',
 '8pk9-mh2i': 'xyh2-p9cg',
 'hb4b-8v4q': 'ffh6-n4ga',
 'mv3v-5qet': 'mwga-t3nx',
 'evkd-zgn4': 'j6yj-kaid',
 'sc9q-ryk8': '',
 '5ccs-vx79': '',
 'knn6-7fy9': '32h9-64b2',
 'mev7-qffb': 'mev7-qffb',
 'qifa-4jur': 'qifa-4jur',
 'sacq-tw7c': 'sacq-tw7c',
 '7tmk-3ibe': '7tmk-3ibe',
 '9fte-yff6': '9fte-yff6',
 '3ka2-m6zm': '3ka2-m6zm',
 'ceje-t3ek': 'ceje-t3ek',
 'afm6-vyyp': 'afm6-vyyp',
 '24hn-nv39': '24hn-nv39',
 'y2yv-a2wp': 'y2yv-a2wp',
 'b7zn-sry4': 'b7zn-sry4',
 'kr2r-j5ik': 'kr2r-j5ik',
 '3j7e-ezpr': '3j7e-ezpr',
 'u9u9-cq2s': 'u9u9-cq2s',
 'abdb-jtwc': 'abdb-jtwc',
 'mdbi-p4c8': 'mdbi-p4c8',
 't3k6-vndx': 't3k6-vndx',
 'rcw7-6npp': 'rcw7-6npp',
 'nwd2-s3kd': 'nwd2-s3kd',
 'd2cu-rhft': 'd2cu-rhft',
 '42wt-sxkv': '42wt-sxkv',
 '6exr-8xkn': '6exr-8xkn',
 'wyy2-wvrc': 'wyy2-wvrc',
 'w2w7-ggyk': 'w2w7-ggyk',
 '8pmi-n437': '8pmi-n437',
 't5eg-ziay': 't5eg-ziay',
 'yvwz-kj9z': 'yvwz-kj9z',
 'eeb6-6s76': 'eeb6-6s76',
 '72dx-vrxk': '72dx-vrxk',
 'ccz9-ggrb': 'ccz9-ggrb',
 'an2q-gwrx': 'an2q-gwrx',
 'jr8i-33tp': 'jr8i-33tp',
 'cr6z-hn4e': 'cr6z-hn4e',
 '2sn7-naei': '2sn7-naei',
 'sshp-3kyq': 'sshp-3kyq',
 'q7ri-3nsu': 'q7ri-3nsu',
 'f3vc-vat3': 'f3vc-vat3',
 'mpff-jbkx': 'mpff-jbkx',
 'wnau-xrqi': 'wnau-xrqi',
 '66zf-qjdd': '66zf-qjdd',
 '23sa-se52': '23sa-se52',
 '74qa-79bk': '74qa-79bk',
 'dsw3-mrn4': 'dsw3-mrn4',
 'sys8-yyuf': 'sys8-yyuf',
 'npnz-8mvz': 'npnz-8mvz',
 'sxfp-qxs6': 'sxfp-qxs6',
 'v4jc-jbmt': 'v4jc-jbmt',
 'be63-q8yz': 'be63-q8yz',
 'u56p-777a': 'u56p-777a',
 'j3me-5ifv': 'j3me-5ifv',
 'bxgy-dnjp': 'bxgy-dnjp',
 'xz8z-8s8e': 'xz8z-8s8e',
 'x88m-3a2j': 'x88m-3a2j',
 'u6xi-qwn3': 'u6xi-qwn3',
 'mxfq-jecf': 'mxfq-jecf',
 'ujgg-3rdh': 'ujgg-3rdh',
 'ytai-hin3': 'ytai-hin3',
 'sn8z-q44h': 'sn8z-q44h',
 'druy-a38s': 'druy-a38s',
 '2mk-94p9': '2mk-94p9',
 '35y-dxds': '35y-dxds',
 'xi5f-mkzt': 'xi5f-mkzt'}

In [33]:
for col in sorted(dfCIMMapCen.columns):
    print(col)

API Endpoint
Additional Dataset Documentation: Additional Metadata
Additional Dataset Documentation: Data Dictionary
Additional Dataset Documentation: FGDC Compliance (Geospatial Only)
Additional Dataset Documentation: Technical Documentation
Approval Status
Attribution
Attribution Link
Audience
Category
Column Count
Contact Email
Contributing Agency Information: Agency Data Series Page
Contributing Agency Information: Agency Program Page
Contributing Agency Information: Business Contact and Phone
Contributing Agency Information: Citation
Contributing Agency Information: Data Source
Contributing Agency Information: Technical Contact and Phone
Creation Date (UTC)
Data Description: Collection Method
Data Description: Collection Mode
Data Description: Data Collection Instrument
Data Description: Date of Initial Dataset Creation
Data Description: Field Names, comma delimited
Data Description: Long Description
Data Description: Newest Record in Dataset
Data Description: Oldest Record in Dataset
Data Description: Related Datasets
Data Description: Single Row
Data Quality: Applicable Information Quality Guideline Designation
Data Quality: Data Governance Plan
Data Quality: Data Quality Certification
Data Quality: Expected Update Frequency
Data Quality: Privacy and Confidentiality
Data Quality: Stewardship Plan
Data Updates: Date of Inital Publish
Data Updates: File Size at Recent Update
Data Updates: Source Update Schedule
Data Updates: Total Columns at Recent Update
Data Updates: Total Records at Initial Publish
Data Updates: Total Records at Recent Update
Data Updates: Update Method
Data Updates: Update Schedule
Data Updates: Update Type
Data.colorado.gov Dataset Descriptions: Agency
Data.colorado.gov Dataset Descriptions: Data Governance Plan
Data.colorado.gov Dataset Descriptions: Data Quality Certified
Data.colorado.gov Dataset Descriptions: Date Created
Data.colorado.gov Dataset Descriptions: Frequency of Update
Data.colorado.gov Dataset Descriptions: Last Updated
Data.colorado.gov Dataset Descriptions: Purpose
Data.colorado.gov Dataset Descriptions: Secondary Content Provider
Data.colorado.gov Dataset Descriptions: Status
Data.colorado.gov Dataset Descriptions: Stewardship Plan
Data.colorado.gov Dataset Descriptions: Sub agency
Data.colorado.gov Dataset Descriptions: Time Period
Dataset Coverage: Geographic Coverage
Dataset Coverage: Granularity
Dataset Coverage: Unit of Analysis
Dataset Summary: Agency
Dataset Summary: Category
Dataset Summary: Currentness Reference
Dataset Summary: Date Released
Dataset Summary: Date Updated
Dataset Summary: Frequency
Dataset Summary: High Value Dataset
Dataset Summary: Local Government Entity
Dataset Summary: Progress
Dataset Summary: Purpose
Dataset Summary: Source
Dataset Summary: Sub Agency
Dataset Summary: Suggested by Public
Dataset Summary: Time Period
Dataset Summary: Type
Department Metrics: Publishing Department
Derived View
Description
Domain
Downloads
Flood 2013: Content type
Geo Data Information: Bounding Coordinates
Geo Data Information: Horizontal Coordinate System
Geo Data Information: Positional Accuracy
Geospatial: Collection Method
Geospatial: Coordinate System Disclaimer
Geospatial: Horizontal Accuracy
Geospatial: Horizontal Coordinate System
Geospatial: Positional Accuracy
Geospatial: Web Display Coordinate System
Last Data Updated Date (UTC)
Last Metadata Updated Date (UTC)
License
Name
Owner
Owner UID
Parent UID
Provenance
Publication Stage
Published Version Name
Published Version UID
Required Field Set: Agency
Required Field Set: Frequency of Update
Required Field Set: Primary Content Provider
Required Field Set: Secondary Content Editor
Row Count
Row Label
Tags
Type
UID
Visits
url

In [35]:

print(dfCIMMapCen.loc[dfCIMMapCen["UID"].isin(no),["Name","Audience"]])

                                                   Name Audience
370                         Census in Colorado 2017 Map   public
371                         Census in Colorado 2018 Map   public
789                  Census Places in Colorado 2018 Map   public
983   Census Congressional Districts in Colorado 201...   public
986   Census Congressional Districts in Colorado 201...   public
1027                 Census Tracts in Colorado 2019 Map   public
1075                 Census Tracts in Colorado 2018 Map   public
1248                 Census Places in Colorado 2017 Map   public
1250                 Census Places in Colorado 2019 Map   public
1289           Census Block Groups in Colorado 2018 Map   public
1413                  Census Zip Codes in Colorado 2014   public
1425                  Census Zip Codes in Colorado 2016   public
1462               Census Counties in Colorado 2019 Map   public
1479              Census Zip Codes in Colorado 2018 Map   public
1658               Census Counties in Colorado 2019 Map   public
1672              Census Zip Codes in Colorado 2019 Map   public
1924             Census Counties in Colorado 2017 - Map   public
2388           Census Block Groups in Colorado 2017 Map   public
2429                 Census Tracts in Colorado 2017 Map   public
2438                        Census in Colorado 2019 Map   public
2459  Census Congressional Districts in Colorado 201...   public

In [ ]:
data

In [90]:
for id,dct in data.items():
    print(id,dct["shape"],dct["name"])
    display(dct["data"].head(3))

n53p-giqe (455, 157) Census Places in Colorado 2012

,the_geom,pop,geonum,geoname,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,r400t599,rntl400,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,"MULTIPOLYGON (((-103.848012 38.194975, -103.86...",349,10818750,Crowley,241,104,4,0,0,0,0,0,183,166,27,8,0,32,30,50,22,0,10,54,27,11,26,18,13,2,10,9,51,46,42.3,94,73,21,16,5,106,94,12,81,13,252,41,147,64,45326.0,45924.0,15623.0,1939.0,241.0,389.0,62500.0,347,0,2,254,93,0,2,345,312,3,18,12,0,148,145,113,32,0,0,0,0,2,0,1,147,13,73,30,0,25,6,331,72,5,0,8,0,32,27,0,259,0,3,10,8,10,0,1,14,60,81,30,43,3,3,0,0,0,0,0,2,0,13,2,8,0,3,0,0,0,0,0,346,29,61,48,52,9,0,3.71,12,17,14,30,5,14,2,0,0,0,0,349,64,306,196,196,148,48,0,110,349
1,MULTIPOLYGON (((-104.930313 39.856173999999996...,118747,10877290,Thornton,35788,73220,1747,375,5078,105,364,2070,59356,59391,9524,10910,9588,7589,7734,9579,10457,8963,9733,8772,7386,6262,4149,2966,1923,1221,964,1027,34907,10438,31.9,40253,29613,10640,8256,2384,42954,40253,2701,28624,11629,73402,9172,45285,18945,66176.0,74246.0,26566.0,1992.0,884.0,1046.0,207600.0,106292,5168,7287,60826,44063,1403,12455,116959,98496,9641,6093,2213,516,59688,54341,47941,6400,1944,1938,6,222,601,461,2119,57569,3911,11757,13333,13631,11036,3901,113366,33810,2360,2184,8037,7697,6849,5468,1215,79556,44,13382,10495,6523,7992,1579,2639,88,212,28624,2235,779,3297,6951,6950,4415,3206,552,76,51,112,11629,321,294,1686,2840,3199,1596,1280,241,172,117580,10796,19702,34179,7881,4580,425,2.94,3661,3032,3540,4018,3738,5064,6528,4972,2817,1902,981,118129,9129,87086,65525,65349,60590,4759,176,21561,118129
2,"MULTIPOLYGON (((-105.224318 40.057601, -105.21...",99177,10807850,Boulder,8742,82648,786,112,4424,52,181,2232,49955,49222,4194,4057,3732,11447,19882,8680,6401,6197,5833,5449,5063,5298,4022,2710,1807,1557,1253,1595,14190,29122,28.4,41076,17653,23423,13642,9781,43322,41076,2246,20000,21076,55865,2383,13670,39812,56206.0,102379.0,37734.0,1974.0,1061.0,1132.0,489500.0,88743,3851,6583,26605,60707,1431,10434,98244,61498,19271,6827,8835,1813,52461,30663,27546,3117,4679,4651,28,5507,4813,724,6075,46386,9404,20219,7677,3569,3592,1925,96756,40780,1528,794,3206,2952,2573,24986,4741,55976,209,3646,4519,7101,10434,8303,4398,938,3774,20000,898,303,584,991,965,1030,2648,2889,5721,2284,1687,21076,522,648,2348,4677,3921,2636,3434,2349,541,90911,19625,28195,14003,8356,1541,508,2.20,8727,3619,3704,2878,2470,3644,4111,2944,2221,2900,3858,97859,6321,86663,57908,57810,53483,4327,98,28755,97859

gu6r-zvv2 (1249, 77) Census Tracts in Colorado 2010

,the_geom,NAME10,NAMELSAD10,AREALAND,AREAWATR,INTPTLAT,INTPTLON,STATE,COUNTY,TRACT,GEOIDTRACT,POP2010,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_JUVENL,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_R_NOTOCC,V_FORSALE,V_S_NOTOCC,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-107.12846200000011 38.8178610...,9639.0,Census Tract 9639,4262312150,41657300,38.628582,-107.273386,8,51,963900,8051963900,905,36,3.98,847,93.59,1,0.11,8,0.88,2,0.22,0,0.00,0,0.00,11,1.22,480,53.04,425,46.96,146,16.13,154,17.02,82,9.06,49.6,50.3,48.9,390,256,231,25,134,104,2.19,38,352,2.64,51,0,0,0,0,0,51,13,0,38,1348,390,28.93,958,71.07,308,78.97,82,21.03,9,0,22,0,880,1,46
1,MULTIPOLYGON (((-106.9526920000001 38.55070300...,9637.0,Census Tract 9637,14502053,0,38.544337,-106.927026,8,51,963700,8051963700,6124,844,13.78,5060,82.63,35,0.57,26,0.42,34,0.56,2,0.03,13,0.21,110,1.80,3379,55.18,2745,44.82,487,7.95,973,15.89,577,9.42,25.6,24.7,27.7,2446,1063,774,289,1383,853,2.19,625,1821,2.87,760,48,3,0,45,0,712,712,0,0,2784,2446,87.86,338,12.14,1032,42.19,1414,57.81,163,7,26,3,67,0,72
2,MULTIPOLYGON (((-106.5182840000001 38.95151700...,9636.0,Census Tract 9636,3267477050,10725478,38.673896,-106.709626,8,51,963600,8051963600,3794,231,6.09,3491,92.01,7,0.18,12,0.32,20,0.53,0,0.00,0,0.00,33,0.87,1993,52.53,1801,47.47,469,12.36,769,20.27,411,10.83,43.3,42.9,43.8,1628,1083,949,134,545,429,2.31,162,1466,2.77,35,0,0,0,0,0,35,0,0,35,3130,1628,52.01,1502,47.99,1274,78.26,354,21.74,24,3,55,9,1333,1,77

sn6p-34bq (64, 157) Census Counties in Colorado 2016

,pop,the_geom,geoname,geonum,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,479977,"MULTIPOLYGON (((-105.053289 39.856764, -105.05...",Adams,108001,186852,247948,14393,2327,17632,657,1122,9046,241414,238563,37094,38043,37862,31418,32051,37617,39292,36377,33598,31001,30387,27037,22475,17191,10889,7764,5086,4795,133321,43147,33.3,158748,112674,46074,34925,11149,166058,158748,7310,102279,56469,303509,54142,181479,67888,61444,68496,26051,1985,966,1098,216700,406693,22343,50941,249825,152249,4619,73284,473044,398992,34827,26633,10196,2396,235043,209708,182639,27069,8827,8715,112,646,3062,1990,10810,224233,16618,51958,51338,50347,34975,18997,457942,129057,7625,8049,29081,30456,28273,21302,4271,328885,4733,39120,27797,20746,29377,18354,19601,3142,3188,102279,8198,4040,10460,22017,19230,14010,14551,4879,3627,700,567,56469,1794,2268,7951,10585,12757,8690,9049,2100,1275,475099,61265,110104,131457,44770,23301,3633,3.00,18369,14267,15290,15538,13921,18891,24077,15347,9004,8134,5910,476508,49909,359726,254614,254215,238687,15528,399,105112,476508
1,16353,"MULTIPOLYGON (((-106.039354 37.429814, -106.03...",Alamosa,108003,7470,8031,274,204,161,28,11,174,7971,8382,1128,1075,1216,1451,2151,1098,914,854,788,810,948,944,892,788,451,456,247,142,4011,3010,30.2,5946,3652,2294,1814,480,6728,5946,782,3384,2562,9332,1509,5415,2408,32385,46188,18133,1976,529,634,141600,15050,202,1101,9463,5457,130,1303,16136,12859,1039,1547,647,44,6238,5567,4696,871,1,1,0,127,352,26,165,6073,2488,2173,708,423,188,93,15786,5585,311,202,1017,834,809,2310,102,10201,129,715,970,864,1525,798,458,287,982,3384,486,438,920,864,328,169,99,34,42,0,4,2562,623,500,730,325,93,128,48,0,115,15262,4786,6485,3953,2046,1579,276,2.57,1870,874,549,670,409,514,573,207,62,145,73,15910,3037,12685,6956,6956,6351,605,0,5729,15910
2,617668,MULTIPOLYGON (((-104.902671 39.685711999999995...,Arapahoe,108005,115309,382460,62039,1894,33918,1286,1674,19088,303932,313736,40413,42564,43335,38836,39293,45715,46677,42320,45362,41564,42868,40748,34994,26936,17203,12217,8094,8529,151442,52999,36.3,231844,153555,78289,62377,15912,242869,231844,11025,144154,87690,413227,31745,213176,168306,66288,80002,35250,1983,1000,1142,266600,526624,39128,51916,249982,266230,10412,91044,609964,490790,54370,39446,20875,4483,316545,272843,245533,27310,14559,9912,4647,1064,5057,2987,20035,296510,23685,71280,75833,64732,40137,20843,593436,161895,10561,8376,33693,34836,34607,30180,9642,431541,5191,40378,34896,57139,60357,20707,16609,3544,4048,144154,4257,4971,11364,21068,23560,20615,25946,13490,11057,3510,4316,87690,2274,2663,9718,17020,19736,14946,14796,4663,1874,611958,65383,110595,149161,71044,21970,4580,2.64,25836,18916,20542,19800,19192,25557,31290,23923,14540,15642,16606,612295,55751,482697,342792,341161,320538,20623,1631,139905,612295

9cn8-g4er (458, 157) Census Places in Colorado 2014

,geonum,the_geom,geoname,pop,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,10816000,"MULTIPOLYGON (((-104.626524 38.926386, -104.62...",Colorado Springs,433547,73744,302885,25056,1550,12728,866,670,16048,214140,219407,30261,29191,28686,29819,36059,34820,31077,26886,27789,29144,30848,25640,23537,16632,11513,8970,6441,6234,105688,48328,34.4,170273,108739,61534,50022,11512,181832,170273,11559,100106,70167,279531,20186,157737,101608,54228.0,68580.0,29355.0,1982.0,763.0,888.0,208600.0,397862,16767,18918,141273,243715,12874,35685,427535,324454,61300,8895,27439,5447,205845,185005,163606,21399,1978,1894,84,1279,4549,2452,10582,195263,25725,75497,52690,24982,8825,7544,415367,120591,6715,6244,23356,22534,22912,32040,6790,294776,1739,32642,28183,35018,34733,20228,14389,3920,10980,100106,4859,3681,13265,25294,17107,11130,13224,5544,4235,919,848,70167,2262,9239,16499,13032,11791,7639,5729,2348,1628,426061,59126,95405,103921,48476,19364,3576,2.51,27359,17772,16922,15998,14484,17455,21201,14412,9140,8902,6628,420527,49429,339065,231305,221017,199665,21352,10288,107760,420527
1,10862000,"MULTIPOLYGON (((-104.464475 38.282588, -104.45...",Pueblo,107706,54618,47432,2263,507,820,59,187,1820,52619,55087,7283,6908,6950,7084,7722,7243,7325,6603,5895,6142,7207,7226,6610,4980,3525,3323,2676,3004,25101,10846,37.7,43371,25497,17874,15372,2502,48067,43371,4696,24865,18506,71759,10413,47391,13955,34889.0,45168.0,20450.0,1963.0,570.0,725.0,113300.0,102666,1795,3245,72406,29023,1237,5040,106392,84287,16333,2795,2674,303,41319,37623,32239,5384,655,643,12,324,1346,372,999,40320,8796,19744,5322,2359,2648,1451,103435,28203,1842,1661,5234,5809,5684,6930,1043,75232,84,4781,3353,2870,8929,5953,8524,3512,10061,24865,2466,7669,7351,3914,1370,753,693,177,231,90,151,18506,2017,3989,4403,3970,2044,780,408,73,822,103267,24683,38259,24634,16471,8299,1946,2.38,12102,6660,5173,4297,3147,3866,3965,1863,883,928,487,104120,20307,85075,48037,47925,41938,5987,112,37038,104120
2,10818640,"MULTIPOLYGON (((-102.805178 40.858578, -102.80...",Crook,108,16,92,0,0,0,0,0,0,56,52,4,5,6,0,0,7,7,11,12,7,6,15,7,3,9,6,2,1,15,0,48.7,35,26,9,9,0,45,35,10,30,5,93,16,67,10,32083.0,41250.0,18315.0,1939.0,313.0,663.0,74000.0,108,0,0,79,29,0,0,106,100,6,0,0,0,45,44,43,1,0,0,0,0,0,0,1,44,30,2,0,7,0,5,104,12,2,0,3,6,0,1,0,92,0,3,0,0,5,1,3,9,24,30,12,7,3,6,0,2,0,0,0,0,0,5,0,0,4,0,0,1,0,0,0,108,8,33,15,21,0,2,3.09,8,7,6,2,1,1,7,3,0,0,0,108,25,93,46,46,45,1,0,47,108

gafi-svtb (7, 156) Census Congressional Districts in Colorado 2014

,pop,hispanic,the_geom,con_dist,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400T599,r600T799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,754428,213741,MULTIPOLYGON (((-105.14597299975412 39.5774160...,1,431025,62353,4003,24804,537,1234,16731,376773,377655,51144,46452,40451,38750,53036,79323,72774,59808,54310,46934,47088,45014,38308,26824,18203,12963,10679,12367,160420,69413,34.6,320202,161619,158583,123287,35296,342136,320202,21934,168939,151263,524595,68841,227692,228062,54116,71663,35213,1968,831,922,259100,643735,37689,73004,321014,313197,9524,110693,743784,581016,74805,52555,29539,5869,394182,315654,280342,35312,25456,20821,4635,8443,15727,3935,24967,369215,35890,109833,91332,72547,39053,20560,723534,182566,13502,9868,36117,31878,30039,44473,16689,540968,4368,45940,27311,32384,54706,40120,53147,22401,61759,168939,5007,8005,18942,24226,24530,20709,28545,14949,14260,4520,5246,151263,11496,11152,31143,30826,24504,16301,15949,6732,3160,741412,124908,199032,158827,79029,39527,8508,2.31,58100,31645,30554,28024,24411,29435,38409,25420,15530,17689,20985,747409,71506,608997,433735,433340,400225,33115,395,175262,747409
1,721514,174695,MULTIPOLYGON (((-109.06017100009154 38.4627959...,3,515370,5916,8884,4720,494,869,10566,363503,358011,43809,46362,46460,48288,45229,46354,45859,44394,43588,46132,53587,53576,49287,37384,25794,19378,13184,12849,164249,65899,39.3,285432,184049,101383,81746,19637,359131,285432,73699,194537,90895,491366,52708,293573,145085,48972,60423,26871,1983,701,851,202600,677238,13775,30501,352581,318082,6575,44276,713666,586416,74869,24601,25765,2015,328042,278023,238318,39705,7435,6835,600,5229,14064,3639,19652,308390,73813,111884,49361,32082,21089,20161,695943,178000,11422,9112,36994,37494,38479,38729,5770,517943,2417,73215,67323,49821,63425,24679,25432,12342,40477,194537,16140,20184,27050,32699,23185,17542,22073,11687,12359,4887,6731,90895,7403,12051,18158,16614,13574,7602,6388,2570,6535,703601,109992,184558,161425,105652,33618,10273,2.46,54548,32332,30692,27672,23983,29997,35345,20248,11230,10840,8545,711487,94532,575468,367156,366681,334285,32396,475,208312,711487
2,742085,110840,MULTIPOLYGON (((-106.59903200032653 39.0362730...,5,538979,39746,3325,17747,1700,1089,28659,377154,364931,49994,50549,50677,51392,58102,56232,51113,45453,47922,50715,54142,47151,41911,31041,20509,15399,10642,9141,181923,78791,35.3,277862,188657,89205,72892,16313,308486,277862,30624,180618,97244,481371,34981,284682,161708,56038,69117,28718,1984,783,922,212700,692189,24769,25127,241708,427914,22567,49896,732489,573855,86384,16251,46746,9253,343505,300673,265314,35359,2615,2457,158,2041,13643,4052,20481,323024,46597,112236,79810,45600,22810,15971,712623,206676,11336,10911,40703,40105,40052,53610,9959,505947,3762,63854,53586,54273,55944,29527,21061,5907,20572,180618,9543,7643,24607,41263,28656,20279,25195,10644,9220,1953,1615,97244,3331,11365,21139,17019,17312,11789,9040,2931,3318,710882,88821,146408,179096,84851,30177,5718,2.56,41693,27993,26702,26204,24574,29125,36169,23968,15426,14802,11206,698893,83219,579770,383079,355443,322767,32676,27636,196691,698893

qx2d-46a5 (14, 271) Census Core Based Statistical Area in Colorado 2011

,the_geom,OBJECTID,CSAFP,CBSAFP,GEOID,NAME,NAMELSAD,LSAD,MEMI,MTFCC,ALAND,AWATER,INTPTLAT,INTPTLON,Shape_Leng,Shape_Area,LOGRECNO,NAMEACS,CBSA,GEOID_1,POP0711,HISPANIC,WHITE_NH,BLACK_NH,NTVAM_NH,ASIAN_NH,HAWPI_NH,OTHER_NH,TWOPLUS_NH,MALE,FEMALE,AGELESS10,AGELESS18,AGE18_24,AGE25_34,AGE35_44,AGE45_64,AGE65PLUS,MED_AGE,HOUSEHOLDS,FAMILYHH,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSING_UN,OCC_HU,VAC_HU,OWNED,RENTED,POP25PLUS,NOHSDIPL,HSGRAD_SC,BACHL_HGHR,MED_HH_INC,MED_FAM_IN,PER_CAP_IN,MED_YR_BLT,MED_C_RENT,MED_G_RENT,MED_HM_VAL,CITZ_BIRTH,CITZ_NAT,NOT_CITZ,BORN_IN_CO,BRN_OTH_ST,NTV_B_O_US,FOREIGN_B,POP_1P,SAME_HOUSE,SAME_CNTY,SAME_STATE,DIFF_STATE,FRM_ABROAD,WRKRS_16PL,CAR_ALL,CAR_ALONE,CAR_CARPOO,PUBLIC_TRN,PT_BUS,PT_OTHER,BIKE,WALK,TR_OTHER,WRK_HOME,W_16PL_NH,T_LESS_10,T_10_19,T_20_29,T_30_39,T_40_59,T_60_PL,POP_3PL,ENROLLED,PRESCHOOL,KNDRGRTN,GR_1_4,GR_5_8,GR_9_12,UNDERGRAD,GRAD_PROF,N_ENROLLED,BLT_2000_P,B1990_1999,B1980_1989,B1970_1979,B1960_1969,B1950_1959,B1940_1949,B1939_E,OWN_OCC_HU,V_L_50K,V50K_100K,V100K_150K,V150K_200K,V200K_250K,V250K_300K,V300K_400K,V400K_500K,V500K_750K,V750K_1M,V_1M_PLUS,RNT_OCC_HU,RNTL400,R400T599,R600T799,R800T999,R1000T1249,R1250T1499,R1500T1999,R2000PL,RNOCSHR,AGE_0_9,AGE_10_19,AGE_20_29,AGE_30_39,AGE_40_49,AGE_50_59,AGE_60_69,AGE_70_79,AGE_80_PL,PS_Uni,PS_BELOW,ADJ_PS_Uni,ADJ_PS_Pov,AVGHHSIZE,MLOGRECNO,MPOP0711,MHISPANIC,MWHITE_NH,MBLACK_NH,MNTVAM_NH,MASIAN_NH,MHAWPI_NH,MOTHER_NH,MTWOPLUS_N,MMALE,MFEMALE,MAGELESS10,MAGELESS18,MAGE18_24,MAGE25_34,MAGE35_44,MAGE45_64,MAGE65PLUS,MMED_AGE,MHOUSEHOLD,MFAMILYHH,MNONFAMHH,MHHLDRALON,MHHLDR_NAL,MHOUSING_U,MOCC_HU,MVAC_HU,MOWNED,MRENTED,MPOP25PLUS,MNOHSDIPL,MHSGRAD_SC,MBACHL_HGH,MMED_HH_IN,MMED_FAM_I,MPER_CAP_I,MMED_YR_BL,MMED_C_REN,MMED_G_REN,MMED_HM_VA,MCITZ_BIRT,MCITZ_NAT,MNOT_CITZ,MBORN_IN_C,MBRN_OTH_S,MNTV_B_O_U,MFOREIGN_B,MPOP_1P,MSAME_HOUS,MSAME_CNTY,MSAME_STAT,MDIFF_STAT,MFRM_ABROA,MWRKRS_16P,MCAR_ALL,MCAR_ALONE,MCAR_CARPO,MPUBLIC_TR,MPT_BUS,MPT_OTHER,MBIKE,MWALK,MTR_OTHER,MWRK_HOME,MW_16PL_NH,MT_LESS_10,MT_10_19,MT_20_29,MT_30_39,MT_40_59,MT_60_PL,MPOP_3PL,MENROLLED,MPRESCHOOL,MKNDRGRTN,MGR_1_4,MGR_5_8,MGR_9_12,MUNDERGRAD,MGRAD_PROF,MN_ENROLLE,MBLT_2000_,MB1990_199,MB1980_198,MB1970_197,MB1960_196,MB1950_195,MB1940_194,MB1939_E,MOWN_OCC_H,MV_L_50K,MV50K_100K,MV100K_150,MV150K_200,MV200K_250,MV250K_300,MV300K_400,MV400K_500,MV500K_750,MV750K_1M,MV_1M_PLUS,MRNT_OCC_H,MRNTL400,MR400T599,MR600T799,MR800T999,MR1000T124,MR1250T149,MR1500T199,MR2000PL,MRNOCSHR,MAGE_0_9,MAGE_10_19,MAGE_20_29,MAGE_30_39,MAGE_40_49,MAGE_50_59,MAGE_60_69,MAGE_70_79,MAGE_80_PL,MPS_Uni,MPS_BELOW,MADJ_PS_Un,MADJ_PS_Po,MAVGHHSIZE
0,MULTIPOLYGON (((-104.97756000000008 40.0328700...,1,216.0,24540,24540,"Greeley, CO","Greeley, CO Metro Area",M1,1,G3110,10326991873,76554137,40.555794,-104.383649,5.112779,1.106130,9429,"Greeley, CO Metro Area; Colorado",24540,824540,248441,70017,168360,1920,1101,3077,116,303,3547,124560,123881,41083,69422,27084,34894,34330,59380,23331,32.9,88242,62837,25405,19807,5598,95601,88242,7359,62696,25546,151935,22441,90645,38849,55825,65487,25233,1989,674,801,193300,226101,6415,15925,130627,93055,2419,22340,244418,199524,24862,12448,6752,832,117126,105305,92137,13168,739,739,0,971,2489,1726,5896,111230,16102,33947,21565,17171,13175,9270,236761,73290,5085,4376,15751,14146,13839,17491,2602,163471,30516,16522,7936,16161,7424,4624,2504,9914,62696,4307,3642,10162,14950,9667,5821,7172,3069,2442,684,780,25546,2301,3891,5775,4220,3827,1815,1546,585,1586,41083,36720,36129,35583,33358,31038,18559,10064,5907,242360,33351,127373,11901,2.75,9429,0,0,206,233,214,220,57,177,405,220,220,787,1093,931,260,1022,795,755,0.2,771,813,811,876,517,368,771,682,915,792,189,1099,2065,1228,1021,1401,471,1,14,20,2933,1457,804,1172,2039,1985,440,1361,387,3051,2159,1183,1107,296,1300,1333,1451,948,224,224,184,231,350,480,514,1373,901,1367,1161,1033,830,851,466,1154,581,501,671,875,672,989,358,1149,986,832,717,791,439,451,339,666,915,502,404,653,673,536,508,475,340,303,149,227,792,329,445,587,344,416,291,277,177,304,787,772,942,753,733,514,723,30,28,1008,3310,1210,793,0.02
1,MULTIPOLYGON (((-108.23040400000001 38.8777730...,2,NaN,24300,24300,"Grand Junction, CO","Grand Junction, CO Metro Area",M1,1,G3110,8621924957,31466789,39.019492,-108.461837,5.036406,0.900062,9428,"Grand Junction, CO Metro Area; Colorado",24300,824300,144766,18831,120692,826,668,999,142,146,2462,71968,72798,19371,34093,14329,18722,16653,39420,21549,37.9,58288,38621,19667,15262,4405,61969,58288,3681,41928,16360,96344,9805,61394,25145,52986,64412,27680,1982,705,837,222800,138999,2069,3698,68766,69256,977,5767,143055,113912,18536,4710,5629,268,67613,60813,52782,8031,309,306,3,813,1474,827,3377,64236,12602,27388,13020,4180,2163,4883,139423,36430,2677,1931,7443,7153,7804,8204,1218,102993,13130,10498,8808,13512,3727,5208,2119,4967,41928,2272,1853,4759,8454,7938,4984,5660,2530,2522,496,460,16360,1367,1767,3999,3235,2530,1636,722,243,861,19371,18932,20110,17770,17640,21251,14282,9361,6049,142002,18052,74238,7560,2.42,9428,0,0,127,90,163,175,61,97,276,222,222,554,790,630,176,714,744,728,0.3,427,698,788,788,416,339,427,465,778,706,147,695,1521,984,1589,1952,684,2,21,28,3815,682,364,508,1650,1556,209,622,274,1926,1673,604,846,130,1081,1132,1176,611,127,126,159,201,319,202,416,1086,911,1046,905,506,314,498,352,908,372,312,451,469,402,748,241,824,736,580,691,764,351,430,315,416,778,313,285,466,626,580,414,472,339,244,130,122,706,245,306,529,379,403,323,213,116,202,554,567,640,510,523,479,705,30,28,469,2132,902,613,0.02
2,MULTIPOLYGON (((-106.17760400000002 39.6090560...,3,NaN,43540,43540,"Silverthorne, CO","Silverthorne, CO Micro Area",M2,2,G3110,1575642395,28282990,39.621023,-106.137554,2.599537,0.168272,9432,"Silverthorne, CO Micro Area; Colorado",43540,843540,27496,3703,22928,136,48,319,0,92,270,15154,12342,2859,4866,2743,5446,4655,7666,2120,36.3,11001,5896,5105,3357,1748,29574,11001,18573,7545,3456,19887,1053,9046,9788,67915,87295,35218,1984,1091,1163,465200,24030,667,2799,6930,16837,263,3466,27117,22224,1522,1314,1864,193,17120,12800,10880,1920,1213,1213,0,303,1213,210,1381,15739,5023,5353,2618,1335,1000,410,26451,4923,241,272,1000,1141,898,1013,358,21528,2955,8265,6365,9754,1591,306,54,284,7545,284,44,128,353,314,410,1373,1328,1915,830,566,3456,143,105,391,555,594,598,582,195,293,2859,2424,5335,4750,4384,4071,2513,1002,158,27402,2759,17721,1268,2.45,9432,0,0,31,83,60,115,92,100,148,174,174,289,371,380,188,457,395,292,0.5,679,501,520,397,340,83,679,670,532,495,173,309,803,732,4024,4567,2125,2,103,99,23124,484,245,408,580,684,157,468,160,818,541,508,501,130,584,655,613,338,409,409,184,103,398,112,324,658,711,606,548,383,257,196,156,382,144,143,247,223,157,254,173,354,460,583,592,687,273,155,52,102,532,191,165,76,153,140,151,338,234,291,215,171,495,220,182,180,137,225,209,221,102,158,289,284,366,352,343,255,341,19,13,83,1049,490,265,0.15

khe9-7d2c (483, 70) Census Zip Codes SF1 in Colorado 2000

,the_geom,ALAND00,AWATER00,STATE,ZCTA5,NAMESF1,POP2000,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_RS_N_OCC,V_FORSALE,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-104.9333850000001 39.94287500...,16541085,538479,8,80241,80241 5-Digit ZCTA,26367,3497,13.26,21262,80.64,286,1.08,135,0.51,752,2.85,15,0.06,26,0.10,394,1.49,13143,49.85,13224,50.15,1006,3.82,8195,31.08,4797,18.19,31.7,31.6,31.8,8908,7198,6240,958,510,1200,2.93,845,8063,3.25,239,229,0,229,0,10,0,0,10,9148,8908,97.38,240,2.62,7659,85.98,1249,14.02,138,15,57,18,0,12
1,MULTIPOLYGON (((-105.0155170000001 39.88524700...,12589775,295152,8,80260,80260 5-Digit ZCTA,30285,7405,24.45,20325,67.11,503,1.66,266,0.88,1186,3.92,36,0.12,11,0.04,553,1.83,14874,49.11,15411,50.89,3003,9.92,8129,26.84,4879,16.11,31.2,30.5,32.2,12129,7606,5065,2541,1015,3508,2.49,1836,10293,3.08,42,0,0,0,0,42,0,0,42,12585,12129,96.38,456,3.62,8261,68.11,3868,31.89,210,35,114,12,0,85
2,MULTIPOLYGON (((-104.80655900000009 39.7183760...,56646497,145743,8,80011,80011 5-Digit ZCTA,45253,11260,24.88,22677,50.11,7858,17.36,328,0.72,1489,3.29,138,0.30,88,0.19,1415,3.13,22556,49.84,22697,50.16,4111,9.08,13239,29.26,7921,17.50,30.9,30.2,31.8,16552,11098,7353,3745,1088,4366,2.71,2319,14233,3.28,395,102,0,99,3,293,0,191,102,17193,16552,96.27,641,3.73,9963,60.19,6589,39.81,277,52,108,37,0,167

v56b-yh3u (14, 325) Census Core Based Statistical Area in Colorado 2012

,the_geom,OBJECTID,CSAFP,CBSAFP,GEOID,NAME,NAMELSAD,LSAD,MEMI,MTFCC,ALAND,AWATER,INTPTLAT,INTPTLON,Shape_Leng,Shape_Area,CBSA,GEOID_1,NAME_1,LOGRECNO,POP0812,HISPANIC,WHITE_NH,BLACK_NH,NTVAM_NH,ASIAN_NH,HAWPI_NH,OTHER_NH,TWOPLUS_NH,MALE,FEMALE,AGELESS10,AGELESS18,AGE18_24,AGE25_34,AGE35_44,AGE45_64,AGE65PLUS,AGE_0_9,AGE_10_19,AGE_20_29,AGE_30_39,AGE_40_49,AGE_50_59,AGE_60_69,AGE_70_79,AGE_80_PL,MED_AGE,HOUSEHOLDS,FAMILYHH,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSING_UN,OCC_HU,VAC_HU,OWNED,RENTED,POP25PLUS,NOHSDIPL,HSGRAD_SC,BACHL_HGHR,MED_HH_INC,MED_FAM_IN,PER_CAP_IN,MED_YR_BLT,MED_C_RENT,MED_G_RENT,MED_HM_VAL,CITZ_BIRTH,CITZ_NAT,NOT_CITZ,BORN_IN_CO,BRN_OTH_ST,NTV_B_O_US,FOREIGN_B,POP_1P,SAME_HOUSE,SAME_CNTY,SAME_STATE,DIFF_STATE,FRM_ABROAD,WRKRS_16PL,CAR_ALL,CAR_ALONE,CAR_CARPOO,PUBLIC_TRN,PT_BUS,PT_OTHER,BIKE,WALK,TR_OTHER,WRK_HOME,W_16PL_NH,T_LESS_10,T_10_19,T_20_29,T_30_39,T_40_59,T_60_PL,POP_3PL,ENROLLED,PRESCHOOL,KNDRGRTN,GR_1_4,GR_5_8,GR_9_12,UNDERGRAD,GRAD_PROF,N_ENROLLED,BLT_2010_P,B2000_2009,B1990_1999,B1980_1989,B1970_1979,B1960_1969,B1950_1959,B1940_1949,B1939_E,OWN_OCC_HU,V_L_50K,V50K_100K,V100K_150K,V150K_200K,V200K_250K,V250K_300K,V300K_400K,V400K_500K,V500K_750K,V750K_1M,V_1M_PLUS,RNT_OCC_HU,RNTL400,R400T599,R600T799,R800T999,R1000T1249,R1250T1499,R1500T1999,R2000PL,RNOCSHR,PS_Uni,PS_BELOW,PS_BEL150,PUNI_L18,PUNI_65PL,POV_L18,POV_65PL,AVGHHSIZE,HHI_L20K,HHI20_30,HHI30_40,HHI40_50,HHI50_60,HHI60_75,HHI75_100,HHI100_125,HHI125_150,HHI150_200,HHI_200_PL,CIV_NI_POP,DISABLED,POP16_PLS,LABORFORCE,CIV_LF,EMP,UNEMP,ARMEDFRCS,NOT_LF,CIV_NI_P,INSURED,NOT_INS,LOGRECNO_1,MPOP0812,MHISPANIC,MWHITE_NH,MBLACK_NH,MNTVAM_NH,MASIAN_NH,MHAWPI_NH,MOTHER_NH,MTWOPLUS_N,MMALE,MFEMALE,MAGELESS10,MAGELESS18,MAGE18_24,MAGE25_34,MAGE35_44,MAGE45_64,MAGE65PLUS,MAGE_0_9,MAGE_10_19,MAGE_20_29,MAGE_30_39,MAGE_40_49,MAGE_50_59,MAGE_60_69,MAGE_70_79,MAGE_80_PL,MMED_AGE,MHOUSEHOLD,MFAMILYHH,MNONFAMHH,MHHLDRALON,MHHLDR_NAL,MHOUSING_U,MOCC_HU,MVAC_HU,MOWNED,MRENTED,MPOP25PLUS,MNOHSDIPL,MHSGRAD_SC,MBACHL_HGH,MMED_HH_IN,MMED_FAM_I,MPER_CAP_I,MMED_YR_BL,MMED_C_REN,MMED_G_REN,MMED_HM_VA,MCITZ_BIRT,MCITZ_NAT,MNOT_CITZ,MBORN_IN_C,MBRN_OTH_S,MNTV_B_O_U,MFOREIGN_B,MPOP_1P,MSAME_HOUS,MSAME_CNTY,MSAME_STAT,MDIFF_STAT,MFRM_ABROA,MWRKRS_16P,MCAR_ALL,MCAR_ALONE,MCAR_CARPO,MPUBLIC_TR,MPT_BUS,MPT_OTHER,MBIKE,MWALK,MTR_OTHER,MWRK_HOME,MW_16PL_NH,MT_LESS_10,MT_10_19,MT_20_29,MT_30_39,MT_40_59,MT_60_PL,MPOP_3PL,MENROLLED,MPRESCHOOL,MKNDRGRTN,MGR_1_4,MGR_5_8,MGR_9_12,MUNDERGRAD,MGRAD_PROF,MN_ENROLLE,MBLT_2010_,MB2000_201,MB1990_199,MB1980_198,MB1970_197,MB1960_196,MB1950_195,MB1940_194,MB1939_E,MOWN_OCC_H,MV_L_50K,MV50K_100K,MV100K_150,MV150K_200,MV200K_250,MV250K_300,MV300K_400,MV400K_500,MV500K_750,MV750K_1M,MV_1M_PLUS,MRNT_OCC_H,MRNTL400,MR400T599,MR600T799,MR800T999,MR1000T124,MR1250T149,MR1500T199,MR2000PL,MRNOCSHR,MPS_Uni,MPS_BELOW,MPS_BEL150,MPUNI_L18,MPUNI_65PL,MPOV_L18,MPOV_65PL,MAVGHHSIZE,MHHI_L20K,MHHI20_30,MHHI30_40,MHHI40_50,MHHI50_60,MHHI60_75,MHHI75_100,MHHI100_12,MHHI125_15,MHHI150_20,MHHI_200_P,MCIV_NI_PO,MDISABLED,MPOP16_PLS,MLABORFORC,MCIV_LF,MEMP,MUNEMP,MARMEDFRCS,MNOT_LF,MCIV_NI_P,MINSURED,MNOT_INS
0,MULTIPOLYGON (((-105.39784900000011 39.9128860...,1,216.0,19740,19740,"Denver-Aurora-Broomfield, CO","Denver-Aurora-Broomfield, CO Metro Area",M1,1,G3110,21615478549,147608870,39.434281,-104.902369,9.167211,2.276849,19740,32000US0819740,"Denver-Aurora-Broomfield, CO Metro Area; Colorado",9433,2554243,572746,1681721,136719,11489,91557,2655,3911,53445,1270678,1283565,362238,633982,219664,394320,380042,666158,260077,362238,331691,358222,387274,376839,347451,218772,103590,68166,35.7,1000849,631439,369410,295844,73566,1078391,1000849,77542,646567,354282,1700597,179592,861908,659097,62407,77925,33293,1980,828,938,246900,2246353,109817,198073,1100633,1114880,30840,307890,2518554,2053289,212456,157122,80096,15591,1291215,1100816,977729,123087,58467,48750,9717,11445,27652,15010,77825,1213390,112099,314354,293069,248802,166274,78792,2446881,668247,46980,35915,142713,135663,136792,129539,40645,1778634,3240,192440,169836,163510,216315,113322,106808,34001,78919,646567,20673,22499,60889,107400,119157,88427,105471,50726,46119,13477,11729,354282,17734,27382,74124,75728,64724,39658,34608,12110,8214,2522468,305778,503220,626078,253443,105194,21142,2.52,139755,87611,90056,85117,80657,102828,133975,96388,60912,63824,59726,2530914,226137,1987910,1430050,1426296,1312357,113939,3754,557860,2530914,2146324,384590,9433,0,157,738,1642,686,1471,277,736,2336,394,394,2266,3149,2226,451,3252,2640,2605,2266,2212,2222,2324,2315,1762,2538,1506,1365,0.2,2705,3233,2882,3133,1742,732,2705,2629,4327,3266,458,3170,6627,5322,377,630,203,1,5,6,843,5035,2441,4054,5984,4968,1607,4536,1035,7403,5916,4713,2743,1359,4073,4287,4607,2726,1605,1700,661,848,1343,857,2080,4499,2309,4153,3724,3440,2696,2119,1305,3323,1424,1270,2095,1943,1479,2447,1292,3398,399,2276,2642,2059,2473,1849,1797,1126,1583,4327,925,963,1674,2023,2114,1795,1877,1206,1089,626,588,3266,898,1248,2034,2164,1841,1507,1388,669,722,1320,6444,8994,4473,1349,2571,864,0.01,2149,2080,2168,2057,1954,1950,2514,1900,1482,1511,1348,985,3075,1047,3712,3726,3913,2003,509,3779,985,4639,4115
1,MULTIPOLYGON (((-104.94242600000011 38.6498820...,2,NaN,17820,17820,"Colorado Springs, CO","Colorado Springs, CO Metro Area",M1,1,G3110,6951199580,12056121,38.845466,-104.639068,3.776749,0.722487,17820,32000US0817820,"Colorado Springs, CO Metro Area; Colorado",9432,645979,95085,469287,35580,3119,16061,1603,908,24336,322741,323238,93225,166282,69316,90205,84864,169313,65999,93225,92286,97691,82629,93629,86545,56951,27145,15878,34.6,243092,165259,77833,64019,13814,265636,243092,22544,158607,84485,410381,26876,239472,144033,57549,70516,28815,1983,750,884,218100,600888,22811,22280,201150,378417,21321,45091,636919,498508,75916,11528,42994,7973,308279,268540,237945,30595,2827,2712,115,1223,14277,3235,18177,290102,41404,99253,74990,41173,19857,13425,619127,185987,10252,10092,37772,36190,35911,46534,9236,433140,1145,54455,44895,48416,50763,26916,19070,4481,15495,158607,6606,5504,19558,37938,26833,17480,23253,10065,8151,1683,1536,84485,2965,12130,18921,15722,15394,8643,6166,1806,2738,626640,77235,124074,163870,64549,28420,4292,2.58,35695,23457,23525,21718,21945,27124,31429,21853,13874,12947,9525,614774,67340,497597,343714,316721,288077,28644,26993,153883,614774,530642,84132,9432,0,0,358,1034,381,730,218,315,1304,138,138,1148,1613,1377,161,1500,1422,1265,1148,1137,1377,1071,1064,934,1311,755,669,0.1,1224,1596,1602,1443,819,284,1224,1199,1791,1731,124,1241,3668,2806,740,936,302,1,9,10,2009,2308,1041,1534,2946,3298,1139,1833,601,4591,3191,1398,2523,932,2194,2400,2667,1654,550,552,65,213,757,492,972,2098,1439,2126,2143,1608,989,733,667,1763,620,682,983,1109,687,1506,751,1846,224,1048,1222,1171,1314,895,783,473,672,1791,521,480,811,1259,1028,841,921,508,456,262,274,1731,394,809,1044,904,709,676,534,303,318,806,3681,4422,2342,654,1290,420,0.01,1276,1169,1063,897,982,1188,1061,825,831,662,454,889,1628,525,1951,2112,2254,1356,867,1946,889,2386,2124
2,MULTIPOLYGON (((-108.29459600000006 37.2153630...,3,NaN,20420,20420,"Durango, CO","Durango, CO Micro Area",M2,2,G3110,4382658416,19545450,37.287367,-107.839718,3.023109,0.447315,20420,32000US0820420,"Durango, CO Micro Area; Colorado",9434,51443,6119,41297,186,2816,338,39,16,632,26134,25309,5631,10416,6127,6988,6448,15405,6059,5631,6714,7742,6898,6732,8374,5514,2477,1361,37.7,21060,13064,7996,5591,2405,25894,21060,4834,14490,6570,34900,2057,18317,14526,57407,70697,30562,1985,847,971,336800,49915,747,781,18839,30646,430,1528,50797,40103,5921,1546,3058,169,26844,22031,18147,3884,383,340,43,704,1019,412,2295,24549,4944,8684,4957,3387,1429,1148,49598,13525,644,628,2261,2386,2280,4850,476,36073,95,5698,5287,3993,4420,1689,1606,821,2285,14490,1377,542,529,820,1174,1641,3157,2116,1797,698,639,6570,257,409,1326,1164,892,962,807,219,534,49422,5510,9605,10313,5914,1123,273,2.34,2609,2248,2271,1947,1866,2625,2766,1605,1335,966,822,50844,4590,42284,29225,29215,27400,1815,10,13059,50844,41008,9836,9434,0,0,9,39,148,79,54,13,170,83,83,260,361,385,171,431,418,345,260,286,371,342,325,264,364,218,168,0.5,541,440,492,400,336,148,541,498,481,500,108,327,867,679,2873,3246,974,2,37,55,8482,374,168,261,660,619,158,298,146,931,711,382,555,124,605,671,538,589,144,129,86,193,210,145,364,624,457,681,452,349,264,255,139,459,158,153,233,231,184,430,133,459,55,463,437,434,404,283,227,170,300,481,227,152,146,162,190,271,346,253,269,158,138,500,100,134,278,241,194,212,216,129,143,315,750,998,493,160,226,87,0.06,354,374,312,250,316,307,319,215,269,166,140,163,404,146,544,545,582,277,18,537,163,648,605

mxmm-svgz (209, 331) Census County Subdivisions in Colorado 2012

,the_geom,OBJECTID,STATEFP,COUNTYFP,COUSUBFP,COUSUBNS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CNECTAFP,NECTAFP,NCTADVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,Shape_Leng,Shape_Area,COUSUB,GEOID_1,NAME_1,LOGRECNO,POP0812,HISPANIC,WHITE_NH,BLACK_NH,NTVAM_NH,ASIAN_NH,HAWPI_NH,OTHER_NH,TWOPLUS_NH,MALE,FEMALE,AGELESS10,AGELESS18,AGE18_24,AGE25_34,AGE35_44,AGE45_64,AGE65PLUS,AGE_0_9,AGE_10_19,AGE_20_29,AGE_30_39,AGE_40_49,AGE_50_59,AGE_60_69,AGE_70_79,AGE_80_PL,MED_AGE,HOUSEHOLDS,FAMILYHH,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSING_UN,OCC_HU,VAC_HU,OWNED,RENTED,POP25PLUS,NOHSDIPL,HSGRAD_SC,BACHL_HGHR,MED_HH_INC,MED_FAM_IN,PER_CAP_IN,MED_YR_BLT,MED_C_RENT,MED_G_RENT,MED_HM_VAL,CITZ_BIRTH,CITZ_NAT,NOT_CITZ,BORN_IN_CO,BRN_OTH_ST,NTV_B_O_US,FOREIGN_B,POP_1P,SAME_HOUSE,SAME_CNTY,SAME_STATE,DIFF_STATE,FRM_ABROAD,WRKRS_16PL,CAR_ALL,CAR_ALONE,CAR_CARPOO,PUBLIC_TRN,PT_BUS,PT_OTHER,BIKE,WALK,TR_OTHER,WRK_HOME,W_16PL_NH,T_LESS_10,T_10_19,T_20_29,T_30_39,T_40_59,T_60_PL,POP_3PL,ENROLLED,PRESCHOOL,KNDRGRTN,GR_1_4,GR_5_8,GR_9_12,UNDERGRAD,GRAD_PROF,N_ENROLLED,BLT_2010_P,B2000_2009,B1990_1999,B1980_1989,B1970_1979,B1960_1969,B1950_1959,B1940_1949,B1939_E,OWN_OCC_HU,V_L_50K,V50K_100K,V100K_150K,V150K_200K,V200K_250K,V250K_300K,V300K_400K,V400K_500K,V500K_750K,V750K_1M,V_1M_PLUS,RNT_OCC_HU,RNTL400,R400T599,R600T799,R800T999,R1000T1249,R1250T1499,R1500T1999,R2000PL,RNOCSHR,PS_Uni,PS_BELOW,PS_BEL150,PUNI_L18,PUNI_65PL,POV_L18,POV_65PL,AVGHHSIZE,HHI_L20K,HHI20_30,HHI30_40,HHI40_50,HHI50_60,HHI60_75,HHI75_100,HHI100_125,HHI125_150,HHI150_200,HHI_200_PL,CIV_NI_POP,DISABLED,POP16_PLS,LABORFORCE,CIV_LF,EMP,UNEMP,ARMEDFRCS,NOT_LF,CIV_NI_P,INSURED,NOT_INS,LOGRECNO_1,MPOP0812,MHISPANIC,MWHITE_NH,MBLACK_NH,MNTVAM_NH,MASIAN_NH,MHAWPI_NH,MOTHER_NH,MTWOPLUS_N,MMALE,MFEMALE,MAGELESS10,MAGELESS18,MAGE18_24,MAGE25_34,MAGE35_44,MAGE45_64,MAGE65PLUS,MAGE_0_9,MAGE_10_19,MAGE_20_29,MAGE_30_39,MAGE_40_49,MAGE_50_59,MAGE_60_69,MAGE_70_79,MAGE_80_PL,MMED_AGE,MHOUSEHOLD,MFAMILYHH,MNONFAMHH,MHHLDRALON,MHHLDR_NAL,MHOUSING_U,MOCC_HU,MVAC_HU,MOWNED,MRENTED,MPOP25PLUS,MNOHSDIPL,MHSGRAD_SC,MBACHL_HGH,MMED_HH_IN,MMED_FAM_I,MPER_CAP_I,MMED_YR_BL,MMED_C_REN,MMED_G_REN,MMED_HM_VA,MCITZ_BIRT,MCITZ_NAT,MNOT_CITZ,MBORN_IN_C,MBRN_OTH_S,MNTV_B_O_U,MFOREIGN_B,MPOP_1P,MSAME_HOUS,MSAME_CNTY,MSAME_STAT,MDIFF_STAT,MFRM_ABROA,MWRKRS_16P,MCAR_ALL,MCAR_ALONE,MCAR_CARPO,MPUBLIC_TR,MPT_BUS,MPT_OTHER,MBIKE,MWALK,MTR_OTHER,MWRK_HOME,MW_16PL_NH,MT_LESS_10,MT_10_19,MT_20_29,MT_30_39,MT_40_59,MT_60_PL,MPOP_3PL,MENROLLED,MPRESCHOOL,MKNDRGRTN,MGR_1_4,MGR_5_8,MGR_9_12,MUNDERGRAD,MGRAD_PROF,MN_ENROLLE,MBLT_2010_,MB2000_201,MB1990_199,MB1980_198,MB1970_197,MB1960_196,MB1950_195,MB1940_194,MB1939_E,MOWN_OCC_H,MV_L_50K,MV50K_100K,MV100K_150,MV150K_200,MV200K_250,MV250K_300,MV300K_400,MV400K_500,MV500K_750,MV750K_1M,MV_1M_PLUS,MRNT_OCC_H,MRNTL400,MR400T599,MR600T799,MR800T999,MR1000T124,MR1250T149,MR1500T199,MR2000PL,MRNOCSHR,MPS_Uni,MPS_BELOW,MPS_BEL150,MPUNI_L18,MPUNI_65PL,MPOV_L18,MPOV_65PL,MAVGHHSIZE,MHHI_L20K,MHHI20_30,MHHI30_40,MHHI40_50,MHHI50_60,MHHI60_75,MHHI75_100,MHHI100_12,MHHI125_15,MHHI150_20,MHHI_200_P,MCIV_NI_PO,MDISABLED,MPOP16_PLS,MLABORFORC,MCIV_LF,MEMP,MUNEMP,MARMEDFRCS,MNOT_LF,MCIV_NI_P,MINSURED,MNOT_INS
0,MULTIPOLYGON (((-107.48212000000011 37.4278590...,1,8,53,92109,1935504,805392109,Lake City,Lake City CCD,22,Z5,G4040,NaN,NaN,NaN,S,2893573835,15324680,37.811667,-107.383335,2.846950,0.297671,92109,06000US0805392109,"Lake City CCD, Hinsdale County, Colorado",156,790,19,764,0,0,0,0,0,7,357,433,82,89,10,99,14,337,241,82,8,45,63,58,208,188,99,39,56.5,372,245,127,100,27,1525,372,1153,295,77,691,34,355,302,54844,78906,36524,1979,543,846,252700,779,9,2,200,561,18,11,778,655,7,71,45,0,350,184,166,18,0,0,0,23,83,15,45,305,228,23,31,5,0,18,752,53,30,10,4,7,0,1,1,699,0,113,328,292,299,117,127,31,218,295,7,7,23,55,54,28,45,30,26,14,6,77,0,6,16,36,7,0,0,0,12,790,40,156,89,241,0,26,2.10,45,41,45,11,52,25,71,39,14,13,16,790,129,701,378,378,363,15,0,323,790,638,152,156,130,27,128,12,12,12,12,12,6,76,78,43,49,26,47,27,78,51,43,25,34,44,34,67,42,36,20,3.3,55,48,41,41,20,47,55,52,53,30,105,50,82,66,15598,22205,7400,3,81,200,48294,129,12,5,79,98,17,14,128,113,8,73,39,12,77,57,57,15,12,12,24,25,41,17,25,78,69,25,24,14,17,21,121,32,27,12,5,8,12,2,3,107,12,34,56,61,52,38,39,15,50,53,34,22,26,26,27,15,28,22,16,13,7,30,32,23,31,25,11,12,12,12,13,130,27,57,67,48,42,19,0.27,24,27,27,8,31,14,35,27,14,13,15,130,51,107,78,78,80,15,12,69,130,98,67
1,MULTIPOLYGON (((-107.710871 38.845349999999975...,2,8,29,92831,1935542,802992831,Paonia,Paonia CCD,22,Z5,G4040,NaN,NaN,NaN,S,665537178,1163483,38.980032,-107.606054,1.457801,0.069308,92831,06000US0802992831,"Paonia CCD, Delta County, Colorado",120,4023,193,3740,0,25,27,0,10,28,2086,1937,297,820,309,377,467,1268,782,297,601,352,402,628,540,759,276,168,46.5,1699,1202,497,386,111,2024,1699,325,1271,428,2894,279,1785,830,54055,60938,31005,1972,678,874,185700,3906,74,43,2012,1890,4,117,4017,3459,265,68,211,14,1735,1345,988,357,2,2,0,25,93,3,267,1468,455,434,228,169,89,93,3979,829,9,22,216,202,310,52,18,3150,6,208,208,258,409,88,127,145,575,1271,112,118,220,254,295,87,105,30,20,0,30,428,36,35,69,104,68,49,0,0,67,3950,528,801,762,775,190,40,2.33,297,224,104,157,170,231,167,172,64,45,68,4008,430,3400,2053,2053,1868,185,0,1347,4008,3212,796,120,357,98,352,12,41,44,12,15,44,227,195,111,172,119,102,123,194,166,111,144,115,114,141,100,177,97,66,4.7,118,139,109,98,66,105,118,107,131,118,247,137,265,158,8632,5818,6693,3,123,110,19668,357,60,39,250,304,7,70,357,363,208,63,131,15,246,256,246,130,4,4,24,21,56,4,99,258,134,131,103,76,51,50,343,202,9,19,87,87,97,47,15,296,9,87,61,104,129,40,71,65,110,131,74,62,82,79,78,40,50,27,16,12,31,118,40,26,39,58,70,58,12,12,35,355,251,275,168,149,110,37,0.15,88,94,43,76,88,80,71,71,38,30,52,358,122,280,274,274,285,117,12,211,358,312,165
2,MULTIPOLYGON (((-107.94361300000001 38.7914150...,3,8,29,91786,1935487,802991786,Hotchkiss,Hotchkiss CCD,22,Z5,G4040,NaN,NaN,NaN,S,824173015,3380090,38.818357,-107.718273,1.920994,0.085831,91786,06000US0802991786,"Hotchkiss CCD, Delta County, Colorado",119,4960,376,4484,0,10,5,0,0,85,2589,2371,507,1041,358,473,500,1711,877,507,665,498,391,773,761,808,348,209,46.1,2163,1384,779,683,96,2509,2163,346,1501,662,3561,372,2704,485,42995,44543,24058,1978,518,752,236000,4830,62,68,2223,2573,34,130,4892,3882,578,296,131,5,2114,1815,1453,362,5,5,0,0,91,38,165,1949,358,378,369,454,154,236,4782,964,12,42,156,249,301,170,34,3818,0,307,405,413,543,142,84,153,462,1501,78,152,67,170,394,127,176,96,139,31,71,662,35,50,297,64,30,48,0,26,112,4958,645,1326,1039,877,124,99,2.27,487,258,253,346,97,201,238,157,16,35,75,4960,893,4055,2439,2439,2157,282,0,1616,4960,3962,998,119,482,202,493,12,13,13,12,12,58,296,245,155,211,137,110,143,229,177,155,154,153,107,144,158,188,100,78,3.1,161,187,165,157,56,120,161,119,149,151,265,138,324,140,3293,5368,2710,3,84,49,13358,483,84,53,325,466,29,101,482,349,467,147,91,13,248,234,222,147,12,12,24,12,53,44,85,241,133,101,161,140,99,123,436,282,13,40,71,98,136,100,40,276,12,118,136,151,120,61,56,87,133,149,58,64,36,61,115,71,74,62,67,33,68,151,42,37,152,36,21,49,12,30,78,483,228,379,212,159,67,56,0.22,144,100,120,142,51,94,94,70,15,35,45,482,190,312,257,257,246,100,12,244,482,392,193

f3th-4ste (208, 104) Census County Subdivisions SF3 in Colorado 2000

,the_geom,OBJECTID,STATEFP00,COUNTYFP00,COUSUBFP00,COSBIDFP00,NAME00,NAMELSAD00,LSAD00,CLASSFP00,MTFCC00,UR00,FUNCSTAT00,ALAND00,AWATER00,INTPTLAT00,INTPTLON00,Shape_Leng,Shape_Area,STATE,COUNTY,COUSUB,GEOIDCOUSU,NAME10,POP_SF3,HISPANIC,PCTHISP,WHITE_NH,PCTWHITE,BLACK_NH,PCTBLACK,NTV_AM_NH,PCTNTVAM,ASIAN_NH,PCTASIAN,HAWPI_NH,PCTHAW,OTHER_NH,PCTOTHER,TWOPLUS_NH,PCT_TWOP,MALE,PCT_MALE,FEMALE,PCT_FEMALE,AGELESS10,PCT_L10,AGELESS18,PCT_L18,AGE65PLUS,PCT_65PL,HHLDS,FAMHH,MARCOUPFAM,OTH_FAM,MHHLDR_N_W,FHHLDR_N_H,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSINGU,URBANHU,PCT_URBHU,RURALHU,PCT_RURHU,OCCHU,PCTOCC,VACHU,PCTVAC,OWN,PCTOWN,RENT,PCTRENT,TTLPOP25PL,NO_HS_DIPL,PCT_NODIPL,HSGRAD_PL,PCT_HSPLUS,BACHL_HGHR,PCT_BACHPL,MEDHHINC,MEDFAMINC,PERCAPINC,MEDYRBLT,MEDCRENT,MEDGRENT,MEDVAL,POP3PLUS,ENROLLED,PRESCHOOL,KINDRGRTN,GRADE_1_4,GRADE_5_8,GRADE_9_12,UNDERGRAD,GRADSCH,NOTINSCH,NATIVE,PCTNATIVE,FOREIGN,PCTFOREIGN,PVRTY_UNI,IN_POVERTY,PCT_PVRTY
0,MULTIPOLYGON (((-105.0551150000001 40.27637000...,1,8,69,90285,806990285,Berthoud,Berthoud CCD,22,Z5,G4040,M,S,150760824,11121928,40.307584,-105.155254,0.640869,0.017150,8,69,90285,806990285,Berthoud CCD,11053,619,5.60,10271,92.92,0,0.00,5,0.05,91,0.82,5,0.05,0,0.00,62,0.56,5528,50.01,5525,49.99,1396,12.63,3158,28.57,801,7.25,3944,3143,2788,355,138,217,168,633,3311,4091,2302,56.27,1789,43.73,3961,96.82,130,3.18,3389,85.56,572,14.44,7143,411,5.75,6732,94.25,2217,31.04,62096,67276,28073,1980,621,680,217200,10684,3280,168,135,730,889,809,428,121,7404,10776,97.49,277,2.51,11007,343,3.12
1,MULTIPOLYGON (((-105.50408400000009 40.2603740...,2,8,69,91235,806991235,Estes Park,Estes Park CCD,22,Z5,G4040,M,S,1055603526,4070513,40.464535,-105.627735,1.701725,0.112403,8,69,91235,806991235,Estes Park CCD,11018,370,3.36,10544,95.70,23,0.21,7,0.06,26,0.24,0,0.00,0,0.00,48,0.44,5361,48.66,5657,51.34,949,8.61,1898,17.23,2092,18.99,4978,3280,2958,322,108,214,320,1378,3600,7561,4108,54.33,3453,45.67,4989,65.98,2572,34.02,3503,70.21,1486,29.79,8400,466,5.55,7934,94.45,3698,44.02,51026,60160,31419,1975,548,583,241300,10833,2068,164,100,461,417,530,333,63,8765,10556,95.81,462,4.19,10909,388,3.56
2,MULTIPOLYGON (((-105.07286599999996 40.6541810...,3,8,69,91330,806991330,Fort Collins,Fort Collins CCD,22,Z5,G4040,M,S,282546225,24057705,40.580938,-105.089290,1.009997,0.032611,8,69,91330,806991330,Fort Collins CCD,140732,12993,9.23,120194,85.41,1300,0.92,708,0.50,2657,1.89,55,0.04,207,0.15,2618,1.86,70728,50.26,70004,49.74,16550,11.76,30883,21.94,11391,8.09,54397,32087,26084,6003,1993,4010,8505,13805,40592,56496,54409,96.31,2087,3.69,54443,96.37,2053,3.63,32970,60.56,21473,39.44,81836,5808,7.10,76028,92.90,37551,45.89,45298,58501,22531,1979,641,690,161600,135681,51136,2285,1373,7353,7158,6727,21826,4414,84545,133479,94.85,7253,5.15,134966,17275,12.80

9gri-r239 (3532, 157) Census Block Groups in Colorado 2013

,geoname,the_geom,pop,geonum,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,"Block Group 2, Census Tract 2.01, Grand County...","MULTIPOLYGON (((-106.09733 40.346967, -106.095...",1076,1080490002012,8,1044,0,12,6,0,0,6,575,501,16,24,76,60,5,4,114,26,11,218,89,136,61,9,16,56,79,76,176,5,48.3,481,273,208,208,0,3338,481,2857,364,117,895,12,449,434,55987.0,81250.0,33424.0,1981.0,660.0,698.0,359200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,322,830,562,665,193,131,50,585,364,16,0,2,0,6,4,260,13,58,2,3,117,8,21,45,23,13,4,0,0,3,1076,106,200,NaN,NaN,NaN,NaN,2.24,88,25,87,12,40,39,77,96,0,3,14,NaN,NaN,960,651,651,607,44,0,309,NaN
1,"Block Group 1, Census Tract 4, Park County, Co...","MULTIPOLYGON (((-106.033892 39.336231, -106.03...",1047,1080930004001,0,1031,0,0,0,0,0,16,567,480,39,19,16,0,8,14,12,59,113,65,164,207,160,80,46,36,9,0,74,8,55.9,575,364,211,166,45,2922,575,2347,514,61,965,27,510,428,33427.0,80250.0,29676.0,1990.0,NaN,NaN,233100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,763,700,621,564,111,95,16,52,514,41,0,83,90,65,43,37,97,8,11,39,61,0,0,0,35,0,12,0,0,14,1047,360,382,NaN,NaN,NaN,NaN,1.82,223,18,66,24,20,36,87,51,0,38,12,NaN,NaN,973,544,544,504,40,0,429,NaN
2,"Block Group 1, Census Tract 10.10, Larimer Cou...","MULTIPOLYGON (((-105.058162 40.500358, -105.05...",897,1080690010101,30,867,0,0,0,0,0,0,426,471,35,30,29,48,0,30,13,45,43,57,63,145,138,83,69,21,30,18,114,28,56.4,403,353,50,50,0,431,403,28,390,13,755,16,293,446,103542.0,112031.0,55216.0,NaN,NaN,NaN,383800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,20,326,85,0,0,0,0,0,390,0,0,0,16,0,70,130,81,86,7,0,13,0,0,0,0,13,0,0,0,0,897,24,32,NaN,NaN,NaN,NaN,2.23,16,8,19,5,42,5,104,59,42,47,56,NaN,NaN,803,427,427,403,24,0,376,NaN

22bw-ijyi (64, 275) Census ACS Counties in Colorado 2011

,the_geom,OBJECTID,STATEFP,COUNTYFP,COUNTYNS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,Shape_Leng,Shape_Area,LOGRECNO,NAMEACS,GEOID_1,POP0711,HISPANIC,WHITE_NH,BLACK_NH,NTVAM_NH,ASIAN_NH,HAWPI_NH,OTHER_NH,TWOPLUS_NH,MALE,FEMALE,AGELESS10,AGELESS18,AGE18_24,AGE25_34,AGE35_44,AGE45_64,AGE65PLUS,MED_AGE,HOUSEHOLDS,FAMILYHH,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSING_UN,OCC_HU,VAC_HU,OWNED,RENTED,POP25PLUS,NOHSDIPL,HSGRAD_SC,BACHL_HGHR,MED_HH_INC,MED_FAM_IN,PER_CAP_IN,MED_YR_BLT,MED_C_RENT,MED_G_RENT,MED_HM_VAL,CITZ_BIRTH,CITZ_NAT,NOT_CITZ,BORN_IN_CO,BRN_OTH_ST,NTV_B_O_US,FOREIGN_B,POP_1P,SAME_HOUSE,SAME_CNTY,SAME_STATE,DIFF_STATE,FRM_ABROAD,WRKRS_16PL,CAR_ALL,CAR_ALONE,CAR_CARPOO,PUBLIC_TRN,PT_BUS,PT_OTHER,BIKE,WALK,TR_OTHER,WRK_HOME,W_16PL_NH,T_LESS_10,T_10_19,T_20_29,T_30_39,T_40_59,T_60_PL,POP_3PL,ENROLLED,PRESCHOOL,KNDRGRTN,GR_1_4,GR_5_8,GR_9_12,UNDERGRAD,GRAD_PROF,N_ENROLLED,BLT_2000_P,B1990_1999,B1980_1989,B1970_1979,B1960_1969,B1950_1959,B1940_1949,B1939_E,OWN_OCC_HU,V_L_50K,V50K_100K,V100K_150K,V150K_200K,V200K_250K,V250K_300K,V300K_400K,V400K_500K,V500K_750K,V750K_1M,V_1M_PLUS,RNT_OCC_HU,RNTL400,R400T599,R600T799,R800T999,R1000T1249,R1250T1499,R1500T1999,R2000PL,RNOCSHR,AGE_0_9,AGE_10_19,AGE_20_29,AGE_30_39,AGE_40_49,AGE_50_59,AGE_60_69,AGE_70_79,AGE_80_PL,PS_Uni,PS_BELOW,ADJ_PS_Uni,ADJ_PS_Pov,AVGHHSIZE,MLOGRECNO,MPOP0711,MHISPANIC,MWHITE_NH,MBLACK_NH,MNTVAM_NH,MASIAN_NH,MHAWPI_NH,MOTHER_NH,MTWOPLUS_N,MMALE,MFEMALE,MAGELESS10,MAGELESS18,MAGE18_24,MAGE25_34,MAGE35_44,MAGE45_64,MAGE65PLUS,MMED_AGE,MHOUSEHOLD,MFAMILYHH,MNONFAMHH,MHHLDRALON,MHHLDR_NAL,MHOUSING_U,MOCC_HU,MVAC_HU,MOWNED,MRENTED,MPOP25PLUS,MNOHSDIPL,MHSGRAD_SC,MBACHL_HGH,MMED_HH_IN,MMED_FAM_I,MPER_CAP_I,MMED_YR_BL,MMED_C_REN,MMED_G_REN,MMED_HM_VA,MCITZ_BIRT,MCITZ_NAT,MNOT_CITZ,MBORN_IN_C,MBRN_OTH_S,MNTV_B_O_U,MFOREIGN_B,MPOP_1P,MSAME_HOUS,MSAME_CNTY,MSAME_STAT,MDIFF_STAT,MFRM_ABROA,MWRKRS_16P,MCAR_ALL,MCAR_ALONE,MCAR_CARPO,MPUBLIC_TR,MPT_BUS,MPT_OTHER,MBIKE,MWALK,MTR_OTHER,MWRK_HOME,MW_16PL_NH,MT_LESS_10,MT_10_19,MT_20_29,MT_30_39,MT_40_59,MT_60_PL,MPOP_3PL,MENROLLED,MPRESCHOOL,MKNDRGRTN,MGR_1_4,MGR_5_8,MGR_9_12,MUNDERGRAD,MGRAD_PROF,MN_ENROLLE,MBLT_2000_,MB1990_199,MB1980_198,MB1970_197,MB1960_196,MB1950_195,MB1940_194,MB1939_E,MOWN_OCC_H,MV_L_50K,MV50K_100K,MV100K_150,MV150K_200,MV200K_250,MV250K_300,MV300K_400,MV400K_500,MV500K_750,MV750K_1M,MV_1M_PLUS,MRNT_OCC_H,MRNTL400,MR400T599,MR600T799,MR800T999,MR1000T124,MR1250T149,MR1500T199,MR2000PL,MRNOCSHR,MAGE_0_9,MAGE_10_19,MAGE_20_29,MAGE_30_39,MAGE_40_49,MAGE_50_59,MAGE_60_69,MAGE_70_79,MAGE_80_PL,MPS_Uni,MPS_BELOW,MADJ_PS_Un,MADJ_PS_Po,MAVGHHSIZE
0,MULTIPOLYGON (((-106.79968900000004 38.9796500...,1,8,51,198141,8051,Gunnison,Gunnison County,6,H1,G4020,NaN,NaN,NaN,A,8389224620,53172001,38.669679,-107.078108,5.353405,0.873850,39,"Gunnison County, Colorado",8051,15274,1187,13590,88,76,87,0,23,223,8252,7022,1743,2820,2928,2270,2098,3848,1310,33.5,6351,3402,2949,1973,976,11308,6351,4957,3695,2656,9526,694,4353,4479,50073,69250,28862,1981,727,858,338100,14413,208,653,5615,8628,170,861,15119,10555,2459,1013,877,215,8692,5607,4481,1126,158,158,0,928,1281,149,569,8123,4000,2375,708,519,365,156,14888,4662,363,233,635,289,578,2378,186,10226,1771,2249,1740,2909,836,355,235,1213,3695,289,150,102,274,301,456,723,452,432,345,171,2656,96,519,430,732,384,249,121,3,122,1743,2135,3010,2153,2022,2109,1324,491,287,14128,1949,8136,420,2.22,39,0,0,36,44,53,37,92,36,81,124,124,177,275,388,98,246,178,183,1.2,369,297,315,266,208,123,369,342,246,395,158,234,432,363,5873,6949,2341,3,27,49,22520,218,81,213,475,463,75,193,75,598,533,248,327,127,354,440,389,251,80,80,184,235,304,86,130,362,505,335,189,168,130,73,91,415,100,97,148,81,175,292,109,407,258,291,239,365,191,114,120,226,246,158,83,59,110,101,119,161,126,115,103,54,395,154,180,163,191,147,126,66,6,72,177,348,274,190,183,120,169,14,14,262,654,244,139,0.12
1,MULTIPOLYGON (((-102.73931300000008 39.5679840...,2,8,63,198147,8063,Kit Carson,Kit Carson County,6,H1,G4020,NaN,NaN,NaN,A,5596501747,2251930,39.305340,-102.603023,3.285443,0.584674,45,"Kit Carson County, Colorado",8063,8178,1462,6308,262,35,105,3,0,3,4597,3581,991,1842,656,1143,1012,2227,1298,38.7,3003,1982,1021,974,47,3525,3003,522,2113,890,5680,920,3884,876,43194,59350,21674,1967,485,629,115900,7503,62,613,4731,2756,16,675,8086,6852,478,400,301,55,3819,3325,2902,423,1,1,0,2,202,20,269,3550,2003,745,401,230,111,60,7887,1953,170,80,374,418,555,272,84,5934,219,369,236,796,455,399,324,727,2113,320,571,453,313,145,143,82,39,21,26,0,890,112,243,202,96,93,12,5,2,125,991,1094,972,1203,1111,1069,827,567,344,7453,843,3839,427,2.47,45,0,0,92,85,32,86,5,92,4,91,91,111,156,144,106,142,133,131,0.7,146,135,125,126,37,83,146,121,157,133,89,158,306,173,3464,4220,1125,3,74,70,7909,185,34,162,331,373,20,157,47,193,152,125,151,44,199,216,233,99,3,3,184,5,65,16,71,205,270,145,104,76,60,32,69,185,60,52,75,96,109,90,56,180,79,89,59,115,110,91,96,106,157,93,132,98,81,63,53,35,32,18,30,92,133,112,71,125,39,71,18,10,3,53,111,144,130,129,125,75,109,12,12,171,276,221,111,0.10
2,MULTIPOLYGON (((-104.97668300000008 40.0328810...,3,8,123,198177,8123,Weld,Weld County,6,H1,G4020,216.0,24540.0,NaN,A,10326991873,76554137,40.555794,-104.383649,5.112779,1.106130,75,"Weld County, Colorado",8123,248441,70017,168360,1920,1101,3077,116,303,3547,124560,123881,41083,69422,27084,34894,34330,59380,23331,32.9,88242,62837,25405,19807,5598,95601,88242,7359,62696,25546,151935,22441,90645,38849,55825,65487,25233,1989,674,801,193300,226101,6415,15925,130627,93055,2419,22340,244418,199524,24862,12448,6752,832,117126,105305,92137,13168,739,739,0,971,2489,1726,5896,111230,16102,33947,21565,17171,13175,9270,236761,73290,5085,4376,15751,14146,13839,17491,2602,163471,30516,16522,7936,16161,7424,4624,2504,9914,62696,4307,3642,10162,14950,9667,5821,7172,3069,2442,684,780,25546,2301,3891,5775,4220,3827,1815,1546,585,1586,41083,36720,36129,35583,33358,31038,18559,10064,5907,242360,33351,127373,11901,2.75,75,0,0,206,233,214,220,57,177,405,220,220,787,1093,931,260,1022,795,755,0.2,771,813,811,876,517,368,771,682,915,792,189,1099,2065,1228,1021,1401,471,1,14,20,2933,1457,804,1172,2039,1985,440,1361,387,3051,2159,1183,1107,296,1300,1333,1451,948,224,224,184,231,350,480,514,1373,901,1367,1161,1033,830,851,466,1154,581,501,671,875,672,989,358,1149,986,832,717,791,439,451,339,666,915,502,404,653,673,536,508,475,340,303,149,227,792,329,445,587,344,416,291,277,177,304,787,772,942,753,733,514,723,30,28,1008,3310,1210,793,0.02

37uc-bdj5 (526, 156) Census Zip Codes in Colorado 2012

,geoid10,hispanic,the_geom,pop,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400T599,r600T799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,81137,1317,MULTIPOLYGON (((-107.84876900008925 37.0817309...,5483,2996,26,1031,23,0,11,79,2901,2582,394,308,314,514,382,251,327,277,289,506,563,431,363,209,166,104,51,34,1383,529,39.5,2086,1477,609,488,121,2381,2086,295,1462,624,3571,344,2524,703,58500.0,66309.0,25896.0,1984.0,629.0,815.0,207200.0,5442,22,19,2980,2436,26,41,5444,4592,470,45,334,3,2493,2209,1924,285,18,18,0,1,94,33,138,2355,576,586,475,338,248,132,5260,1278,77,54,275,232,389,221,30,3982,13,352,612,351,432,204,105,96,216,1462,217,181,166,136,216,150,169,74,91,23,39,624,36,74,160,127,85,43,31,2,66,5417,665,938,1378,564,225,55,2.60,292,223,187,194,168,345,284,178,92,60,63,5422,694,4353,2749,2749,2536,213,0,1604,5422
1,81325,46,MULTIPOLYGON (((-108.88067199981293 38.1540239...,141,95,0,0,0,0,0,0,69,72,0,37,12,5,0,0,15,19,6,20,0,7,12,0,0,0,8,0,49,5,39.1,50,39,11,11,0,84,50,34,36,14,87,14,63,10,58393.0,59375.0,18306.0,1962.0,NaN,NaN,85000.0,141,0,0,42,99,0,0,141,121,0,0,20,0,55,45,16,29,0,0,0,0,0,0,10,45,0,0,0,29,10,6,141,49,0,0,37,12,0,0,0,92,0,0,9,10,6,21,10,28,0,36,12,6,10,8,0,0,0,0,0,0,0,14,0,0,0,14,0,0,0,0,0,141,27,27,49,8,0,8,2.82,20,0,0,0,14,0,6,10,0,0,0,141,0,92,60,60,55,5,0,32,141
2,81324,46,MULTIPOLYGON (((-109.06811500040692 37.4556949...,1193,1103,0,10,3,2,0,29,667,526,66,72,111,42,25,37,95,78,72,71,71,135,41,99,65,29,33,51,285,31,44.9,518,360,158,158,0,682,518,164,415,103,877,116,621,140,43571.0,57500.0,23216.0,1971.0,496.0,557.0,110200.0,1190,0,3,613,565,12,3,1185,893,154,74,64,0,506,446,407,39,0,0,0,0,22,6,32,474,219,121,10,46,51,27,1182,278,29,7,58,102,51,25,6,904,0,45,119,78,107,67,62,126,78,415,45,136,98,51,27,16,28,6,0,0,8,103,0,45,9,13,4,0,0,0,32,1188,144,242,280,277,52,12,2.30,123,63,66,34,70,34,70,38,3,17,0,1193,232,936,572,572,506,66,0,364,1193

xymp-u28i (64, 157) Census Counties in Colorado 2013

,pop,the_geom,geonum,geoname,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,585333,"MULTIPOLYGON (((-104.898733 39.685587, -104.89...",108005,"Arapahoe County, Colorado",107841,369435,56891,1997,29340,1178,1295,17356,287361,297972,40401,42331,40245,38739,36239,43724,43161,40702,42877,41880,42877,37928,31976,21951,13744,10787,7990,7781,147886,50069,35.9,225552,148229,77323,63684,13639,239158,225552,13606,141460,84092,387378,33305,203826,150247,60651,73649,32595,1982,858,981,230700,497848,34035,53450,229175,259921,8752,87485,577072,464917,50677,38246,19187,4045,291451,252859,227629,25230,13609,9844,3765,1236,4785,3107,15855,275596,24292,66956,69488,59348,38202,17310,560621,157546,9788,7591,33592,31893,33875,30886,9921,403075,1128,40161,34455,55768,61499,22192,16364,3597,3994,141460,4570,6929,15671,27007,26979,18383,19196,8677,7922,2628,3498,84092,1901,5201,15913,19887,17226,10254,9210,2550,1950,580235,69949,117548,145980,60409,24278,4667,2.58,29940,21572,21310,19715,19101,24445,28811,20671,13370,13088,13529,579931,51972,453970,325472,323514,295023,28491,1958,128498,579931
1,619297,"MULTIPOLYGON (((-104.934135 39.700181, -104.93...",108031,"Denver County, Colorado",194513,326215,59829,3625,20727,483,1093,12812,309818,309479,44138,38452,31579,31554,45819,68802,61837,50030,44111,37316,36373,34148,30259,21019,13639,10497,9402,10322,131472,60070,33.8,266069,128046,138023,106828,31195,287735,266069,21666,133651,132418,427755,62265,181979,183511,50313,63705,33251,1965,796,883,249100,521575,30815,66907,259755,253783,8037,97722,610006,471543,67177,42674,23738,4874,319321,251786,222152,29634,22773,19313,3460,7339,14136,3552,19735,299586,28459,92182,75036,56873,30639,16397,592454,150270,10924,8343,29576,24779,24222,37547,14879,442184,2401,38960,19944,24171,41936,34258,45928,20534,59603,133651,3449,7788,17569,20908,17427,14787,21512,11018,12000,3833,3360,132418,10980,11117,30271,27069,20319,12822,12147,4849,2844,607237,116284,178463,129906,63141,38021,7649,2.27,53920,28081,26285,23969,20332,24529,29539,19125,11058,13766,15465,612539,58743,499696,355559,355112,324278,30834,447,144137,612539
2,4383,"MULTIPOLYGON (((-102.665098 40.64535, -102.664...",108095,"Phillips County, Colorado",1087,3196,2,7,15,0,0,76,2278,2105,323,299,305,304,273,158,279,235,250,238,294,338,242,182,112,248,105,198,1097,407,40.4,1668,1162,506,460,46,1900,1668,232,1154,514,2879,416,1978,485,43011,54583,20720,1957,425,595,132700,3850,144,389,2706,1117,27,533,4304,3376,279,418,99,132,1957,1697,1351,346,35,35,0,23,105,2,95,1862,927,427,214,124,128,42,4245,1026,147,39,229,290,227,71,23,3219,13,103,97,140,341,188,201,130,687,1154,141,318,217,209,147,25,35,2,16,36,8,514,63,154,147,16,24,3,0,14,93,4322,858,1484,1097,798,238,99,2.59,383,193,221,179,143,207,214,56,32,16,24,4322,586,3376,2094,2094,1962,132,0,1282,4322

xxfz-y2eq (1, 157) Census in Colorado 2015

,pop,geoname,the_geom,geonum,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,5278906,Colorado,"MULTIPOLYGON (((-109.060253 38.599328, -109.05...",108,1112586,3646224,203276,28448,150165,6886,9354,121967,2648667,2630239,336874,353327,350509,342509,375510,393305,389240,358712,358076,347711,371300,350254,306739,230624,152420,108535,75775,77486,1241856,516873,36.3,2024468,1300972,723496,560467,163029,2261063,2024468,236595,1302266,722202,3520177,327222,1850948,1342007,60629,74826,32217,1982,880,1002,247800,4763134,199542,316230,2254992,2430836,77306,515772,5214280,4214564,492135,261348,210794,35439,2606591,2209901,1962576,247325,82902,70110,12792,34698,77376,27843,173871,2432720,327949,730946,533402,405963,270419,164041,5079041,1395787,88382,70920,280001,279079,274765,325179,77461,3683254,40315,432964,382310,336155,428645,208587,181599,64405,186083,1302266,67608,65567,126629,203934,196087,158792,209370,108744,105395,31565,28575,722202,36632,52825,120857,137031,134824,93310,86049,35413,25261,5161722,653969,1085754,1225562,629269,203466,46434,2.55,288102,186369,188117,177715,161270,209934,267561,186969,115272,125268,117891,5187214,538856,4168824,2852439,2820014,2624436,195578,32425,1316385,5187214

wtpp-eaj8 (64, 76) Census Counties in Colorado 2010

,the_geom,NAME10,NAMELSAD10,AREALAND,AREAWATR,INTPTLAT,INTPTLON,STATE,COUNTY,GEOID,POP2010,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_JUVENL,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_R_NOTOCC,V_FORSALE,V_S_NOTOCC,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-105.0567200000001 40.34928100...,Larimer,Larimer County,6723613490,98295250,40.663091,-105.482131,8,69,8069,299630,31628,10.56,253047,84.45,2259,0.75,1277,0.43,5675,1.89,192,0.06,347,0.12,5205,1.74,148637,49.61,150993,50.39,35541,11.86,64057,21.38,35572,11.87,35.5,34.3,36.8,120295,74993,60320,14673,45302,31187,2.42,18792,101503,2.94,8530,1998,877,56,1063,2,6532,5303,0,1229,132722,120295,90.64,12427,9.36,78741,65.46,41554,34.54,2252,185,1581,281,6765,17,1346
1,MULTIPOLYGON (((-104.1431790000001 37.75833000...,Las Animas,Las Animas County,12361162100,6929979,37.318831,-104.044110,8,71,8071,15507,6446,41.57,8399,54.16,195,1.26,170,1.10,98,0.63,4,0.03,12,0.08,183,1.18,7948,51.25,7559,48.75,2748,17.72,3241,20.90,1751,11.29,43.9,42.5,45.5,6384,4013,2928,1085,2371,2069,2.29,584,5800,2.89,858,601,510,0,91,0,257,173,0,84,8217,6384,77.69,1833,22.31,4473,70.07,1911,29.93,240,15,154,37,645,1,741
2,MULTIPOLYGON (((-105.3688890000001 38.25939900...,Fremont,Fremont County,3970627340,2235395,38.455658,-105.421438,8,43,8043,46824,5770,12.32,37647,80.40,1805,3.85,686,1.47,274,0.59,16,0.03,19,0.04,607,1.30,27032,57.73,19792,42.27,8244,17.61,8211,17.54,4308,9.20,43.6,41.0,47.7,16582,10945,8593,2352,5637,4814,2.30,1499,15083,2.81,8704,8664,8122,98,444,0,40,3,0,37,19242,16582,86.18,2660,13.82,12421,74.91,4161,25.09,380,25,370,100,1053,2,730

nnpy-czzx (208, 73) Census County Subdivisions SF1 in Colorado 2000

,the_geom,NAME00,ALAND00,AWATER00,STATE,COUNTY,COUSUB,GEOID,NAMESF1,POP2000,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_RS_N_OCC,V_FORSALE,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-105.0551150000001 40.27637000...,Berthoud,150760824,11121928,8,69,90285,806990285,Berthoud CCD,11053,672,6.08,10146,91.79,22,0.20,58,0.52,52,0.47,6,0.05,7,0.06,90,0.81,5578,50.47,5475,49.53,803,7.26,3156,28.55,1467,13.27,38.0,37.8,38.2,3961,3156,2755,401,168,637,2.79,301,3660,3.13,7,0,0,0,0,7,0,0,7,4091,3961,96.82,130,3.18,3388,85.53,573,14.47,27,15,24,27,0,37
1,MULTIPOLYGON (((-105.5040840000001 40.26037400...,Estes Park,1055603526,4070513,8,69,91235,806991235,Estes Park CCD,11034,405,3.67,10391,94.17,28,0.25,50,0.45,68,0.62,6,0.05,6,0.05,80,0.73,5427,49.18,5607,50.82,2073,18.79,1929,17.48,958,8.68,45.5,45.0,46.0,4984,3282,2893,389,313,1389,2.18,425,4559,2.64,157,42,0,42,0,115,67,0,48,7566,4984,65.87,2582,34.13,3505,70.33,1479,29.67,132,35,48,2252,0,115
2,MULTIPOLYGON (((-105.0728660000001 40.65418100...,Fort Collins,282546225,24057705,8,69,91330,806991330,Fort Collins CCD,140712,13124,9.33,120062,85.32,1184,0.84,651,0.46,3052,2.17,117,0.08,166,0.12,2356,1.67,70753,50.28,69959,49.72,11405,8.11,31134,22.13,16912,12.02,29.3,28.5,30.4,54421,31784,25488,6296,8840,13797,2.47,10895,43526,3.01,6091,903,361,538,4,5188,4547,0,641,56489,54421,96.34,2068,3.66,32967,60.58,21454,39.42,918,246,397,248,1,258

jjnc-cu9z (3532, 157) Census Block Groups in Colorado 2012

,the_geom,pop,geoname,geonum,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,"MULTIPOLYGON (((-104.884646 39.740156, -104.88...",2226,"Census Tract 007801, Block Group 2",1080010078012,1259,241,177,9,459,29,0,52,1289,937,261,263,164,106,187,301,170,179,173,107,72,73,130,24,14,2,0,0,758,223,26.5,644,366,278,134,144,806,644,162,112,532,1245,626,506,113,29034.0,28667.0,12253.0,1964.0,594.0,614.0,115600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,14,0,39,170,306,151,56,70,112,9,37,16,50,0,0,0,0,0,0,0,532,14,224,159,91,12,25,0,0,7,2226,1087,1292,NaN,NaN,NaN,NaN,3.42,222,117,86,49,85,21,17,14,13,20,0,NaN,NaN,1522,1152,1152,1013,139,0,370,NaN
1,"MULTIPOLYGON (((-104.735055 40.430074, -104.72...",1352,"Census Tract 001300, Block Group 3",1081230013003,542,766,0,0,0,0,0,44,841,511,111,0,87,128,185,174,59,118,39,91,41,50,29,26,32,121,48,13,271,240,29.7,600,368,232,144,88,735,600,135,295,305,841,230,528,83,26705.0,25000.0,18157.0,1970.0,589.0,687.0,130200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,31,0,0,330,265,0,51,58,295,13,61,164,27,16,14,0,0,0,0,0,305,39,71,100,83,12,0,0,0,0,1352,382,691,NaN,NaN,NaN,NaN,2.25,185,129,0,124,51,29,46,36,0,0,0,NaN,NaN,1154,756,756,669,87,0,398,NaN
2,MULTIPOLYGON (((-102.886685066372 36.999257316...,1141,"Census Tract 964600, Block Group 2",1080099646002,44,1059,0,23,12,0,0,3,602,539,55,27,49,124,38,80,10,22,81,99,128,69,72,109,60,39,26,53,225,68,49.7,500,355,145,138,7,705,500,205,365,135,848,103,580,165,43313.0,44511.0,28999.0,1956.0,318.0,439.0,79400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,24,51,47,93,97,96,108,189,365,109,107,24,29,28,17,14,3,17,0,17,135,33,32,16,7,6,0,0,0,41,1141,144,293,NaN,NaN,NaN,NaN,2.28,91,60,71,81,57,34,27,26,22,4,27,NaN,NaN,997,630,630,612,18,0,367,NaN

fifs-d43p (1249, 157) Census Tracts in Colorado 2014

,geonum,geoname,pop,the_geom,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,b2000_2009,blt_2010_p,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,108049000201,2.01,4794,"MULTIPOLYGON (((-106.09733 40.346967, -106.095...",212,4415,77,24,7,0,41,18,2694,2100,345,176,260,202,84,112,290,200,285,451,610,341,682,311,94,195,35,121,912,155,49.4,1911,1298,613,504,109,6004,1911,4093,1529,382,3727,230,2151,1346,59989.0,70179.0,32927.0,1982.0,811.0,867.0,306200.0,4624,109,61,1758,2822,44,170,4738,4165,414,135,24,0,2666,2073,1833,240,0,0,0,7,145,11,430,2236,831,553,356,304,80,112,4582,655,51,39,154,199,158,39,15,3927,833,0,1352,1007,1147,327,386,128,824,1529,77,93,74,146,202,145,441,134,180,23,14,382,27,41,86,66,122,5,10,13,12,4789,298,637,907,756,106,11,2.50,187,104,90,337,238,290,271,227,71,42,54,4794,489,3977,2895,2895,2714,181,0,1082,4794
1,108113968103,9681.03,2262,"MULTIPOLYGON (((-108.199013 37.824504, -108.19...",59,2151,1,0,13,0,0,38,1229,1033,168,152,111,74,44,98,155,155,321,130,235,177,266,123,15,37,1,0,489,60,43.4,940,629,311,163,148,1576,940,636,763,177,1713,27,593,1093,80368.0,82114.0,36937.0,1994.0,1530.0,1592.0,639300.0,2229,19,14,627,1572,30,33,2229,1869,274,21,61,4,1264,954,777,177,14,14,0,50,24,0,222,1042,226,328,312,82,75,19,2214,409,75,31,92,92,80,12,27,1805,458,26,511,310,129,58,13,0,71,763,0,5,0,32,9,57,78,69,236,55,222,177,6,0,0,24,20,18,76,20,13,2233,135,224,489,176,5,0,2.38,61,64,84,76,89,63,161,137,39,99,67,2233,264,1809,1386,1386,1339,47,0,423,2233
2,108123000300,3.00,2028,"MULTIPOLYGON (((-104.706705 40.404671, -104.70...",301,1439,60,32,37,27,0,132,625,1403,0,0,0,1648,353,13,0,6,0,0,0,8,0,0,0,0,0,0,7,1994,19.1,0,0,0,0,0,0,0,0,0,0,27,0,13,14,NaN,NaN,4692.0,NaN,NaN,NaN,NaN,1953,30,45,1334,559,60,75,2028,282,279,1289,171,7,691,407,370,37,0,0,0,0,175,8,101,590,144,303,60,83,0,0,2028,2014,0,0,0,0,0,2007,7,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,2028,88,2028,920,920,723,197,0,1108,2028

v5m6-vhha (1, 157) Census State of Colorado 2013

,geonum,geoname,pop,the_geom,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,108,Colorado,5119329,"MULTIPOLYGON (((-109.060253 38.599328, -109.05...",1064009,3567335,193256,27895,138872,5705,8165,114092,2568343,2550986,339802,351154,337828,340914,360848,378101,368520,351822,353629,359018,371378,337045,284020,201314,135910,100902,74381,72743,1228065,502481,36.1,1977591,1269436,708155,556054,152101,2222782,1977591,245191,1292645,684946,3388783,333037,1800922,1254824,58433,72687,31109,1981,825,939,236200,4623809,182108,313412,2172551,2378485,72773,495520,5054734,4081010,493932,249282,196326,34184,2494794,2112266,1864959,247307,80504,69606,10898,32833,76958,28499,163734,2331060,328756,706294,512342,382953,252599,148116,4919356,1370879,89197,69107,278558,269495,269935,317678,76909,3548477,13063,417754,377626,334987,431688,211807,182054,65104,188699,1292645,67927,68790,138595,221992,205686,153797,191623,96072,92877,27962,27324,684946,36686,60943,134524,137500,122956,73716,67596,25545,25480,5002589,660874,1080765,1212528,569595,211992,44890,2.53,299366,189201,185672,176272,160659,203313,261169,176851,109226,112934,102928,5025295,508331,4023722,2774490,2741518,2509777,231741,32972,1249232,5025295

c6qj-6kx2 (354, 72) Census Places SF1 in Colorado 2000

,the_geom,NAME00,ALAND00,AWATER00,STATE,PLACE,GEOID,NAMESF1,POP2000,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_RS_N_OCC,V_FORSALE,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-104.5036150000001 37.14901500...,Trinidad,16161894,1008,8,78610,878610,Trinidad city,9078,4364,48.07,4393,48.39,43,0.47,117,1.29,37,0.41,5,0.06,8,0.09,111,1.22,4363,48.06,4715,51.94,1717,18.91,2259,24.88,1240,13.66,38.9,37.2,40.5,3701,2334,1614,720,156,1211,2.36,328,3373,2.98,350,201,47,154,0,149,107,0,42,4126,3701,89.70,425,10.30,2352,63.55,1349,36.45,135,56,70,28,0,136
1,MULTIPOLYGON (((-104.5240160000001 37.11800500...,Starkville,179163,0,8,73715,873715,Starkville town,128,82,64.06,32,25.00,0,0.00,4,3.12,0,0.00,0,0.00,0,0.00,10,7.81,63,49.22,65,50.78,13,10.16,35,27.34,23,17.97,35.0,34.5,36.2,42,31,26,5,2,9,3.05,5,37,3.55,0,0,0,0,0,0,0,0,0,53,42,79.25,11,20.75,34,80.95,8,19.05,2,1,3,0,0,5
2,MULTIPOLYGON (((-103.3566270000001 37.24242800...,Kim,793441,0,8,40570,840570,Kim town,65,10,15.38,55,84.62,0,0.00,0,0.00,0,0.00,0,0.00,0,0.00,0,0.00,36,55.38,29,44.62,12,18.46,11,16.92,5,7.69,43.5,38.0,53.5,38,15,14,1,0,23,1.71,0,38,2.80,0,0,0,0,0,0,0,0,0,49,38,77.55,11,22.45,31,81.58,7,18.42,3,0,0,5,0,3

xipb-k5bu (201062, 80) Census Blocks in Colorado 2010

,the_geom,NAME10,UR10,UACE10,UATYP10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,STATE,COUNTY,TRACT,BLOCK,GEOIDBLOCK,POP2010,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_JUVENL,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_R_NOTOCC,V_FORSALE,V_S_NOTOCC,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-104.8705810000001 39.91431300...,Block 1020,U,23527.0,U,1312,0,39.914369,-104.869947,8,1,8535,1020,80010085351020,1,0,0.0,0,0.00,1,100.00,0,0.0,0,0.0,0,0.0,0,0.0,0,0.00,1,100.00,0,0.00,0,0.0,0,0.00,0,0.00,47.5,47.5,0.0,1,0,0,0,1,1,1.00,0,1,0.00,0,0,0,0,0,0,0,0,0,0,1,1,100.00,0,0.00,0,0.00,1,100.00,0,0,0,0,0,0,0
1,MULTIPOLYGON (((-104.8574440000001 39.92146400...,Block 1021,U,23527.0,U,11846,0,39.917451,-104.860125,8,1,8535,1021,80010085351021,0,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0,0,0.0,0,0.00,0,0.00,0,0.00,0,0.0,0,0.00,0,0.00,0.0,0.0,0.0,0,0,0,0,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0.00,0,0.00,0,0.00,0,0,0,0,0,0,0
2,MULTIPOLYGON (((-104.84661200000009 39.9035810...,Block 1068,U,23527.0,U,94928,0,39.901263,-104.847688,8,1,8537,1068,80010085371068,107,29,27.1,71,66.36,1,0.93,0,0.0,0,0.0,0,0.0,0,0.0,6,5.61,53,49.53,54,50.47,3,2.8,35,32.71,24,22.43,35.8,37.8,34.0,31,28,27,1,3,2,3.45,3,28,3.54,0,0,0,0,0,0,0,0,0,0,32,31,96.88,1,3.12,29,93.55,2,6.45,1,0,0,0,0,0,0

94t6-d4wd (14, 76) Census Core Based Statistical Area in Colorado 2010

,the_geom,NAME10,NAMELSAD10,LSAD10,CBSA,GEOCBSA,AREALAND,AREAWATR,INTPTLAT,INTPTLON,POP2010,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_JUVENL,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_R_NOTOCC,V_FORSALE,V_S_NOTOCC,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-105.0567200000001 40.34928100...,"Fort Collins-Loveland, CO","Fort Collins-Loveland, CO Metro Area",M1,22660,822660,6723613490,98295250,40.549689,-105.200206,299630,31628,10.56,253047,84.45,2259,0.75,1277,0.43,5675,1.89,192,0.06,347,0.12,5205,1.74,148637,49.61,150993,50.39,35541,11.86,64057,21.38,35572,11.87,35.5,34.3,36.8,120295,74993,60320,14673,45302,31187,2.42,18792,101503,2.94,8530,1998,877,56,1063,2,6532,5303,0,1229,132722,120295,90.64,12427,9.36,78741,65.46,41554,34.54,2252,185,1581,281,6765,17,1346
1,MULTIPOLYGON (((-103.5737860000001 40.89088700...,"Sterling, CO","Sterling, CO Micro Area",M2,44540,844540,4761813490,16363561,40.662417,-103.130510,22709,3551,15.64,17754,78.18,881,3.88,177,0.78,117,0.52,13,0.06,15,0.07,201,0.89,12924,56.91,9785,43.09,3321,14.62,4542,20.00,2402,10.58,38.4,36.5,42.0,8047,5095,3991,1104,2952,2523,2.34,735,7312,2.91,3904,3459,3286,59,114,0,445,391,0,54,8981,8047,89.60,934,10.40,5460,67.85,2587,32.15,300,8,134,22,92,1,377
2,MULTIPOLYGON (((-106.1776040000001 39.60905600...,"Silverthorne, CO","Silverthorne, CO Micro Area",M2,43540,843540,1575639360,28282990,39.573757,-106.069548,27994,3989,14.25,23158,82.72,208,0.74,55,0.20,269,0.96,13,0.05,31,0.11,271,0.97,15378,54.93,12616,45.07,2158,7.71,4884,17.45,2934,10.48,36.4,35.9,37.1,11754,6553,5593,960,5201,3022,2.36,2745,9009,2.80,273,49,49,0,0,0,224,2,0,222,29842,11754,39.39,18088,60.61,7572,64.42,4182,35.58,1471,194,410,146,15222,1,644

us3j-cyz6 (3278, 102) Census Block Groups SF3 in Colorado 2000

,the_geom,OBJECTID,STATEFP00,COUNTYFP00,TRACTCE00,BLKGRPCE00,BKGPIDFP00,NAMELSAD00,MTFCC00,FUNCSTAT00,ALAND00,AWATER00,INTPTLAT00,INTPTLON00,Shape_Leng,Shape_Area,STATE,COUNTY,TRACT,BLKGRP,GEOIDBG,NAME10,POP_SF3,HISPANIC,PCTHISP,WHITE_NH,PCTWHITE,BLACK_NH,PCTBLACK,NTV_AM_NH,PCTNTVAM,ASIAN_NH,PCTASIAN,HAWPI_NH,PCTHAW,OTHER_NH,PCTOTHER,TWOPLUS_NH,PCT_TWOP,MALE,PCT_MALE,FEMALE,PCT_FEMALE,AGELESS10,PCT_L10,AGELESS18,PCT_L18,AGE65PLUS,PCT_65PL,HHLDS,FAMHH,MARCOUPFAM,OTH_FAM,MHHLDR_N_W,FHHLDR_N_H,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSINGU,URBANHU,PCT_URBHU,RURALHU,PCT_RURHU,OCCHU,PCTOCC,VACHU,PCTVAC,OWN,PCTOWN,RENT,PCTRENT,TTLPOP25PL,NO_HS_DIPL,PCT_NODIPL,HSGRAD_PL,PCT_HSPLUS,BACHL_HGHR,PCT_BACHPL,MEDHHINC,MEDFAMINC,PERCAPINC,MEDYRBLT,MEDCRENT,MEDGRENT,MEDVAL,POP3PLUS,ENROLLED,PRESCHOOL,KINDRGRTN,GRADE_1_4,GRADE_5_8,GRADE_9_12,UNDERGRAD,GRADSCH,NOTINSCH,NATIVE,PCTNATIVE,FOREIGN,PCTFOREIGN,PVRTY_UNI,IN_POVERTY,PCT_PVRTY
0,MULTIPOLYGON (((-105.4825980000001 38.26223100...,1,8,27,980100,3,80279801003,Block Group 3,G5030,S,173321110,1426380,38.194912,-105.440721,0.731397,0.017972,8,27,980100,3,80279801003,Block Group 3,826,40,4.84,768,92.98,2,0.24,8,0.97,0,0.0,0,0.00,0,0.00,8,0.97,432,52.30,394,47.70,74,8.96,162,19.61,161,19.49,391,227,206,21,6,15,9,155,236,607,0,0.00,607,100.00,363,59.80,244,40.20,243,66.94,120,33.06,612,77,12.58,535,87.42,181,29.58,31458,47604,21161,1985,304,358,156400,816,167,4,9,40,45,48,5,16,649,806,97.58,20,2.42,807,137,16.98
1,MULTIPOLYGON (((-104.80979500000011 38.7448290...,2,8,41,4400,9,80410044009,Block Group 9,G5030,S,343939060,143519,38.611451,-104.809621,0.908124,0.035589,8,41,4400,9,80410044009,Block Group 9,10728,1626,15.16,6218,57.96,1979,18.45,152,1.42,215,2.0,131,1.22,31,0.29,376,3.50,7240,67.49,3488,32.51,2185,20.37,2845,26.52,18,0.17,1681,1611,1388,223,45,178,12,58,1623,1850,1847,99.84,3,0.16,1684,91.03,166,8.97,18,1.07,1666,98.93,3837,131,3.41,3706,96.59,596,15.53,34950,34464,12887,1960,685,685,106300,9986,2657,267,235,689,359,272,793,42,7329,10166,94.76,562,5.24,6204,584,9.41
2,MULTIPOLYGON (((-105.22298400000004 38.4475420...,3,8,43,978400,2,80439784002,Block Group 2,G5030,S,1820075,0,38.443482,-105.218306,0.068985,0.000188,8,43,978400,2,80439784002,Block Group 2,863,117,13.56,698,80.88,0,0.00,0,0.00,0,0.0,0,0.00,0,0.00,48,5.56,389,45.08,474,54.92,106,12.28,211,24.45,158,18.31,420,222,134,88,19,69,32,166,254,454,454,100.00,0,0.00,402,88.55,52,11.45,214,53.23,188,46.77,583,60,10.29,523,89.71,48,8.23,25185,34231,20055,1979,352,402,90500,844,188,26,0,57,50,42,13,0,656,837,96.99,26,3.01,857,130,15.17

hcfi-bvst (458, 75) Census Places in Colorado 2010

,the_geom,NAME10,NAMELSAD10,PLACE,GEOPLACE,AREALAND,AREAWATR,INTPTLAT,INTPTLON,POP2010,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_JUVENL,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_R_NOTOCC,V_FORSALE,V_S_NOTOCC,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-104.5212440000001 37.13506500...,Trinidad,Trinidad city,78610,878610,24023442,1008,37.174057,-104.490983,9096,4547,49.99,4201,46.19,69,0.76,88,0.97,68,0.75,4,0.04,5,0.05,114,1.25,4440,48.81,4656,51.19,1466,16.12,2144,23.57,1178,12.95,39.3,38.0,40.6,3774,2270,1473,797,1504,1316,2.31,401,3373,2.97,379,122,31,0,91,0,257,173,0,84,4375,3774,86.26,601,13.74,2364,62.64,1410,37.36,190,13,82,17,42,0,257
1,MULTIPOLYGON (((-104.5242820000001 37.11890900...,Starkville,Starkville town,73715,873715,188783,0,37.116820,-104.523298,59,43,72.88,15,25.42,0,0.00,1,1.69,0,0.00,0,0.00,0,0.00,0,0.00,29,49.15,30,50.85,8,13.56,8,13.56,4,6.78,44.5,41.5,50.0,26,17,12,5,9,8,2.27,3,23,2.76,0,0,0,0,0,0,0,0,0,0,35,26,74.29,9,25.71,17,65.38,9,34.62,0,0,0,0,1,0,8
2,MULTIPOLYGON (((-103.3566650000001 37.24348400...,Kim,Kim town,40570,840570,927702,0,37.247458,-103.353231,74,20,27.03,53,71.62,0,0.00,0,0.00,0,0.00,0,0.00,0,0.00,1,1.35,38,51.35,36,48.65,23,31.08,12,16.22,2,2.70,59.0,58.5,60.0,39,20,17,3,19,18,1.90,1,38,2.70,0,0,0,0,0,0,0,0,0,0,47,39,82.98,8,17.02,31,79.49,8,20.51,0,0,0,0,3,0,5

3ftn-9s6k (526, 156) Census Zip Codes in Colorado 2013

,the_geom,geoid10,hispanic,pop,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400T599,r600T799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,MULTIPOLYGON (((-105.66190999984656 39.7533050...,80476,5,236,230,0,0,0,0,0,1,134,102,14,1,18,8,4,20,26,15,8,31,17,22,28,12,4,8,0,0,38,7,45.5,116,50,66,37,29,223,116,107,77,39,191,5,134,52,45208.0,80714.0,26621.0,1939.0,710.0,838.0,170100.0,228,0,8,91,131,6,8,236,185,42,3,6,0,122,109,96,13,0,0,0,4,9,0,0,122,42,18,20,12,14,16,226,36,4,1,0,15,11,5,0,190,0,4,12,7,22,2,41,0,135,77,0,0,24,26,16,6,2,3,0,0,0,39,6,3,5,13,8,3,0,0,1,229,33,70,31,24,0,0,2.03,11,31,15,12,5,6,20,13,0,3,0,236,11,199,166,166,144,22,0,33,236
1,MULTIPOLYGON (((-106.83013299973811 40.4854829...,80477,392,594,202,0,0,0,0,0,0,390,204,166,0,39,89,40,39,69,38,0,109,0,0,5,0,0,0,0,0,205,129,22.1,102,93,9,9,0,102,102,0,14,88,260,100,82,78,66477.0,46612.0,20770.0,1969.0,729.0,958.0,NaN,494,0,100,369,125,0,100,511,383,128,0,0,0,349,191,22,169,149,149,0,0,0,9,0,349,84,7,60,189,9,0,468,79,40,0,0,39,0,0,0,389,0,9,0,38,0,50,0,5,0,14,0,0,0,0,0,0,0,0,5,9,0,88,0,0,0,60,0,0,0,28,0,594,10,10,205,0,0,0,5.82,0,0,0,38,0,22,33,0,0,0,9,594,89,389,349,349,349,0,0,40,594
2,MULTIPOLYGON (((-105.91417100019146 39.9847100...,80478,0,1651,1538,6,0,101,0,0,6,844,807,0,39,38,105,348,228,14,277,58,90,179,0,56,212,0,7,0,0,110,420,36.2,414,277,137,104,33,1108,414,694,342,72,1121,0,638,483,86996.0,87995.0,31309.0,2001.0,NaN,NaN,562500.0,1486,5,160,166,1320,0,165,1651,999,21,152,474,5,1264,1117,423,694,0,0,0,0,49,0,98,1166,812,176,39,0,9,130,1651,127,0,0,39,38,33,17,0,1524,37,584,139,59,256,33,0,0,0,342,7,0,0,66,0,56,0,0,168,0,45,72,39,0,0,0,0,0,0,33,0,1651,363,369,110,219,0,0,3.83,39,0,0,7,0,62,177,96,0,33,0,1651,55,1541,1264,1264,1264,0,0,277,1651

cuid-432h (1, 73) Census State SF1 in Colorado 2000

,the_geom,REGION00,DIVISION00,STUSPS00,NAME00,ALAND00,AWATER00,STATE,NAMESF1,POP2000,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_RS_N_OCC,V_FORSALE,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-109.04348800000011 37.4846840...,4,8,CO,Colorado,-2147483648,1170104667,8,Colorado,4301261,735601,17.1,3202880,74.46,158443,3.68,28982,0.67,93277,2.17,3845,0.09,5512,0.13,72721,1.69,2165983,50.36,2135278,49.64,416073,9.67,1100795,25.59,605933,14.09,34.3,33.2,35.4,1658238,1084461,858671,225790,137999,435778,2.53,209477,1448761,3.09,102955,52741,30136,18495,4110,50214,23631,8512,18071,1808037,1658238,91.71,149799,8.29,1116137,67.31,542101,32.69,31852,8116,16142,72263,449,20977

xh4c-32wb (1249, 270) Census Tracts in Colorado 2011

,the_geom,OBJECTID,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,Shape_Leng,Shape_Area,LOGRECNO,NAMEACS,GEOID_1,POP0711,HISPANIC,WHITE_NH,BLACK_NH,NTVAM_NH,ASIAN_NH,HAWPI_NH,OTHER_NH,TWOPLUS_NH,MALE,FEMALE,AGELESS10,AGELESS18,AGE18_24,AGE25_34,AGE35_44,AGE45_64,AGE65PLUS,MED_AGE,HOUSEHOLDS,FAMILYHH,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSING_UN,OCC_HU,VAC_HU,OWNED,RENTED,POP25PLUS,NOHSDIPL,HSGRAD_SC,BACHL_HGHR,MED_HH_INC,MED_FAM_IN,PER_CAP_IN,MED_YR_BLT,MED_C_RENT,MED_G_RENT,MED_HM_VAL,CITZ_BIRTH,CITZ_NAT,NOT_CITZ,BORN_IN_CO,BRN_OTH_ST,NTV_B_O_US,FOREIGN_B,POP_1P,SAME_HOUSE,SAME_CNTY,SAME_STATE,DIFF_STATE,FRM_ABROAD,WRKRS_16PL,CAR_ALL,CAR_ALONE,CAR_CARPOO,PUBLIC_TRN,PT_BUS,PT_OTHER,BIKE,WALK,TR_OTHER,WRK_HOME,W_16PL_NH,T_LESS_10,T_10_19,T_20_29,T_30_39,T_40_59,T_60_PL,POP_3PL,ENROLLED,PRESCHOOL,KNDRGRTN,GR_1_4,GR_5_8,GR_9_12,UNDERGRAD,GRAD_PROF,N_ENROLLED,BLT_2000_P,B1990_1999,B1980_1989,B1970_1979,B1960_1969,B1950_1959,B1940_1949,B1939_E,OWN_OCC_HU,V_L_50K,V50K_100K,V100K_150K,V150K_200K,V200K_250K,V250K_300K,V300K_400K,V400K_500K,V500K_750K,V750K_1M,V_1M_PLUS,RNT_OCC_HU,RNTL400,R400T599,R600T799,R800T999,R1000T1249,R1250T1499,R1500T1999,R2000PL,RNOCSHR,AGE_0_9,AGE_10_19,AGE_20_29,AGE_30_39,AGE_40_49,AGE_50_59,AGE_60_69,AGE_70_79,AGE_80_PL,PS_Uni,PS_BELOW,ADJ_PS_Uni,ADJ_PS_Pov,AVGHHSIZE,MLOGRECNO,MPOP0711,MHISPANIC,MWHITE_NH,MBLACK_NH,MNTVAM_NH,MASIAN_NH,MHAWPI_NH,MOTHER_NH,MTWOPLUS_N,MMALE,MFEMALE,MAGELESS10,MAGELESS18,MAGE18_24,MAGE25_34,MAGE35_44,MAGE45_64,MAGE65PLUS,MMED_AGE,MHOUSEHOLD,MFAMILYHH,MNONFAMHH,MHHLDRALON,MHHLDR_NAL,MHOUSING_U,MOCC_HU,MVAC_HU,MOWNED,MRENTED,MPOP25PLUS,MNOHSDIPL,MHSGRAD_SC,MBACHL_HGH,MMED_HH_IN,MMED_FAM_I,MPER_CAP_I,MMED_YR_BL,MMED_C_REN,MMED_G_REN,MMED_HM_VA,MCITZ_BIRT,MCITZ_NAT,MNOT_CITZ,MBORN_IN_C,MBRN_OTH_S,MNTV_B_O_U,MFOREIGN_B,MPOP_1P,MSAME_HOUS,MSAME_CNTY,MSAME_STAT,MDIFF_STAT,MFRM_ABROA,MWRKRS_16P,MCAR_ALL,MCAR_ALONE,MCAR_CARPO,MPUBLIC_TR,MPT_BUS,MPT_OTHER,MBIKE,MWALK,MTR_OTHER,MWRK_HOME,MW_16PL_NH,MT_LESS_10,MT_10_19,MT_20_29,MT_30_39,MT_40_59,MT_60_PL,MPOP_3PL,MENROLLED,MPRESCHOOL,MKNDRGRTN,MGR_1_4,MGR_5_8,MGR_9_12,MUNDERGRAD,MGRAD_PROF,MN_ENROLLE,MBLT_2000_,MB1990_199,MB1980_198,MB1970_197,MB1960_196,MB1950_195,MB1940_194,MB1939_E,MOWN_OCC_H,MV_L_50K,MV50K_100K,MV100K_150,MV150K_200,MV200K_250,MV250K_300,MV300K_400,MV400K_500,MV500K_750,MV750K_1M,MV_1M_PLUS,MRNT_OCC_H,MRNTL400,MR400T599,MR600T799,MR800T999,MR1000T124,MR1250T149,MR1500T199,MR2000PL,MRNOCSHR,MAGE_0_9,MAGE_10_19,MAGE_20_29,MAGE_30_39,MAGE_40_49,MAGE_50_59,MAGE_60_69,MAGE_70_79,MAGE_80_PL,MPS_Uni,MPS_BELOW,MADJ_PS_Un,MADJ_PS_Po,MAVGHHSIZE
0,MULTIPOLYGON (((-106.77386100000005 38.7297810...,1,8,51,963800,8051963800,9638.0,Census Tract 9638,G5020,S,844937425,789241,38.876737,-106.908609,1.584753,0.087786,4374,"Census Tract 9638, Gunnison County, Colorado",8051963800,3674,64,3471,8,0,62,0,0,69,1870,1804,512,653,247,663,808,1111,192,38.9,1653,950,703,432,271,4022,1653,2369,1067,586,2774,20,1154,1600,60625,77411,36881,1982,977,1071,603400,3455,118,101,940,2454,61,219,3656,2845,495,172,121,23,2228,1340,1045,295,81,81,0,298,341,38,130,2098,907,802,187,121,71,10,3605,756,129,63,253,93,71,77,70,2849,736,716,689,1204,263,65,25,324,1067,0,8,46,49,45,86,123,112,156,297,145,586,30,21,95,102,115,106,89,3,25,512,201,436,774,814,571,274,84,8,3674,278,2582,156,2.22,4374,377,64,352,13,92,41,92,92,45,230,232,136,147,145,152,168,158,175,2.7,166,114,150,107,98,137,166,175,143,157,266,319,206,202,6789,14167,4769,3,143,125,158886,370,69,65,203,265,48,80,376,304,276,163,73,29,268,229,182,156,64,64,184,113,116,33,56,278,180,193,88,73,82,93,373,184,73,45,98,45,72,53,47,270,183,143,131,182,91,44,25,79,143,260,185,35,37,31,46,58,61,74,92,49,157,186,94,108,29,79,57,58,6,22,136,88,164,156,154,117,81,10,17,377,164,263,63,0.16
1,"MULTIPOLYGON (((-106.5182840000001 38.951517, ...",2,8,51,963600,8051963600,9636.0,Census Tract 9636,G5020,S,3267473017,10725458,38.673896,-106.709626,4.143010,0.339307,4372,"Census Tract 9636, Gunnison County, Colorado",8051963600,4307,565,3627,0,0,21,0,0,94,2213,2094,522,990,440,513,550,1360,454,39.5,1764,1130,634,488,146,3188,1764,1424,1414,350,2877,206,1211,1460,59939,66792,33505,1984,711,867,329100,3957,19,331,1731,2170,56,350,4239,3319,644,98,29,149,2331,1816,1596,220,0,0,0,22,190,72,231,2100,884,735,223,158,56,44,4193,1197,119,70,106,164,233,450,55,2996,566,623,634,584,247,154,180,200,1414,107,70,21,68,110,221,378,174,191,48,26,350,0,55,41,98,48,41,0,0,67,522,620,501,524,619,829,408,153,131,4223,365,2419,108,2.38,4372,418,312,347,92,92,36,92,92,77,250,252,180,234,155,162,165,186,101,5.4,188,156,150,141,69,147,188,204,196,155,293,280,212,240,7234,6767,5718,4,84,123,33455,375,22,260,247,347,50,259,404,343,354,66,30,158,286,240,252,85,92,92,184,34,153,80,89,290,255,181,92,94,44,41,407,231,60,51,67,69,117,179,77,397,154,157,171,146,104,74,116,98,196,199,52,21,39,65,76,111,102,79,40,22,155,243,148,100,79,56,43,92,92,56,180,175,162,161,158,145,97,11,10,417,284,317,172,0.18
2,MULTIPOLYGON (((-106.88062100000006 38.5418360...,3,8,51,963700,8051963700,9637.0,Census Tract 9637,G5020,S,14502052,0,38.544337,-106.927026,0.257235,0.001499,4373,"Census Tract 9637, Gunnison County, Colorado",8051963700,6123,557,5343,80,58,2,0,23,60,3632,2491,639,1039,2181,903,629,931,440,24.1,2447,955,1492,970,522,2814,2447,367,780,1667,2903,409,1495,999,33919,67656,19153,1976,710,821,225200,5859,43,221,2588,3218,53,264,6091,3347,1314,724,663,43,3520,2044,1544,500,64,64,0,608,649,25,130,3390,2106,762,184,194,137,7,5966,2584,115,99,253,11,224,1823,59,3382,260,625,158,851,265,103,22,530,780,131,25,30,144,119,114,126,72,19,0,0,1667,63,404,294,531,220,102,24,0,29,639,1216,1877,816,414,536,349,161,115,5080,1225,2387,125,2.08,4373,152,287,321,44,51,4,92,36,46,238,190,184,252,366,174,165,181,170,1.2,265,159,268,194,174,249,265,163,178,268,235,279,318,233,7934,18529,2394,2,35,63,40076,256,47,190,378,428,42,192,146,421,358,210,305,70,320,346,312,189,59,59,184,212,197,31,79,325,383,223,109,106,72,93,148,327,69,64,122,18,119,276,59,322,127,216,88,203,116,78,29,181,178,160,187,98,87,81,51,82,46,31,92,92,268,219,160,142,142,125,90,30,92,35,184,327,268,183,115,151,149,12,11,297,488,323,183,0.19

jc8p-yc8f (1249, 157) Census Tracts in Colorado 2015

,geoname,the_geom,pop,geonum,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,9636.0,MULTIPOLYGON (((-107.199895 38.763183999999995...,3674,108051963600,147,3417,0,8,0,0,0,102,1967,1707,182,297,258,129,135,216,219,240,134,289,266,419,425,215,75,58,42,75,833,168,45.6,1563,1112,451,436,15,3146,1563,1583,1273,290,2673,97,1273,1303,58979.0,68466.0,27989.0,1980.0,570.0,711.0,309300.0,3577,23,74,1848,1691,38,97,3626,3391,59,106,67,3,1844,1543,1193,350,15,15,0,29,100,31,126,1718,652,627,161,110,96,72,3545,858,56,65,243,215,172,71,36,2687,0,596,463,513,504,362,171,155,382,1273,40,55,27,121,190,173,329,131,133,43,31,290,0,11,122,17,44,0,19,0,77,3669,344,671,828,465,119,34,2.31,238,136,152,189,91,221,335,80,74,28,19,3674,399,2924,2036,2036,1901,135,0,888,3674
1,9803.0,"MULTIPOLYGON (((-105.121258 39.952389, -105.11...",0,108014980300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,9556.0,"MULTIPOLYGON (((-106.872822 40.975877, -106.87...",1335,108057955600,206,1118,1,3,0,0,0,7,709,626,51,81,64,51,56,48,69,54,92,83,145,148,101,121,52,47,28,44,217,86,50.8,616,360,256,224,32,1262,616,646,418,198,1032,128,717,187,46014.0,55833.0,27938.0,1974.0,527.0,721.0,158000.0,1281,2,52,611,669,1,54,1327,1192,63,59,3,10,754,508,486,22,1,1,0,0,97,26,122,632,349,69,66,50,34,64,1308,238,19,12,73,57,39,37,1,1070,9,143,189,116,270,100,94,45,296,418,52,76,74,43,58,31,45,26,0,4,9,198,0,32,56,15,17,0,0,0,78,1329,155,330,216,292,45,12,2.15,122,64,63,93,44,60,104,36,11,13,6,1330,114,1139,776,776,764,12,0,363,1330

2chb-kzb6 (458, 157) Census Places in Colorado 2016

,pop,the_geom,geoname,geonum,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,public_trn,car_carpoo,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,hhi_l20k,avghhsize,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,2926,MULTIPOLYGON (((-104.904764 39.558237999999996...,Acres Green,10800320,284,2357,25,0,148,2,0,110,1405,1521,124,173,235,195,231,144,228,261,162,186,283,200,195,191,57,28,27,6,644,314,37.7,1098,896,202,140,62,1098,1098,0,991,107,1968,27,1070,871,84717.0,90756.0,33021.0,1975.0,1340.0,1449.0,267900.0,2781,95,50,1168,1596,17,145,2926,2479,63,272,112,0,1767,1498,1437,41,61,11,30,0,69,9,150,1617,321,546,416,117,121,96,2819,821,17,76,128,176,181,177,66,1998,0,0,0,105,967,26,0,0,0,991,11,0,8,42,319,323,260,28,0,0,0,107,0,0,0,28,0,32,39,8,0,2918,161,263,636,309,52,10,52,2.66,27,42,48,96,139,262,239,102,79,12,2926,167,2341,1860,1860,1770,90,0,481,2926
1,1366,"MULTIPOLYGON (((-104.678305 39.739995, -104.66...",Aetna Estates,10800620,913,412,0,0,0,0,14,27,699,667,114,170,181,36,75,70,57,187,192,13,140,65,12,24,19,11,0,0,501,75,33.8,395,368,27,27,0,431,395,36,226,169,790,151,555,84,47132.0,55000.0,15919.0,1992.0,815.0,882.0,29200.0,988,103,275,633,338,17,378,1366,1017,262,87,0,0,612,585,505,0,80,0,0,0,27,0,0,612,27,70,192,62,170,91,1317,452,35,8,147,176,41,45,0,865,7,0,272,94,30,28,0,0,0,226,212,14,0,0,0,0,0,0,0,0,0,169,0,0,0,103,49,0,17,0,0,1366,301,448,501,54,132,7,39,3.46,66,49,46,70,23,53,49,0,0,0,1366,117,876,679,679,612,67,0,197,1366
2,491,"MULTIPOLYGON (((-104.662612 37.402828, -104.66...",Aguilar,10800760,229,262,0,0,0,0,0,0,249,242,5,15,46,56,38,19,0,25,59,22,36,32,15,40,31,32,17,3,104,56,42.9,218,136,82,82,0,288,218,70,109,109,331,90,204,37,36071.0,45938.0,24876.0,1949.0,494.0,643.0,123200.0,462,11,18,323,139,0,29,486,384,45,2,55,0,145,139,111,0,28,0,0,0,6,0,0,145,26,27,40,20,32,0,486,122,0,0,23,38,51,7,3,364,2,38,28,24,31,4,15,16,130,109,27,21,26,17,7,11,0,0,0,0,0,109,13,20,23,16,0,6,0,0,31,491,118,179,104,123,33,7,71,2.25,29,26,8,28,28,2,0,2,19,5,491,131,412,173,173,145,28,0,239,491

9b7x-qm8d (178, 76) Census School Districts in Colorado 2010

,the_geom,NAME10,LOGRADE10,HIGRADE10,SDUNI,GEOSD,AREALAND,AREAWATR,INTPTLAT,INTPTLON,POP2010,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_JUVENL,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_R_NOTOCC,V_FORSALE,V_S_NOTOCC,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-105.3746520000001 38.33689900...,Cotopaxi School District RE-3,PK,12,3120,803120,1324516790,15955,38.392199,-105.626485,2735,100,3.66,2547,93.13,5,0.18,31,1.13,13,0.48,0,0.00,3,0.11,36,1.32,1417,51.81,1318,48.19,711,26.00,366,13.38,187,6.84,55.4,55.7,55.0,1315,892,797,95,423,361,2.08,95,1220,2.48,0,0,0,0,0,0,0,0,0,0,2249,1315,58.47,934,41.53,1138,86.54,177,13.46,35,4,44,15,690,0,146
1,MULTIPOLYGON (((-105.1038230000001 38.44674800...,Cañon City School District RE-1,KG,12,2790,802790,1704553230,209405,38.463093,-105.246790,27601,2944,10.67,23238,84.19,535,1.94,328,1.19,142,0.51,10,0.04,13,0.05,391,1.42,14653,53.09,12948,46.91,5445,19.73,5414,19.62,2892,10.48,44.0,41.2,47.4,10799,6946,5355,1591,3853,3341,2.27,972,9827,2.80,3132,3107,2656,98,353,0,25,3,0,22,12004,10799,89.96,1205,10.04,7773,71.98,3026,28.02,243,15,229,49,274,2,393
2,MULTIPOLYGON (((-105.1038230000001 38.44674800...,Florence School District RE-2,KG,12,3960,803960,958098697,1999268,38.430227,-105.028755,16884,2734,16.19,12230,72.44,1273,7.54,327,1.94,119,0.70,6,0.04,8,0.05,187,1.11,11157,66.08,5727,33.92,2165,12.82,2498,14.80,1250,7.40,41.2,39.5,46.3,4649,3244,2568,676,1405,1150,2.43,443,4206,2.89,5572,5557,5466,0,91,0,15,0,0,15,5189,4649,89.59,540,10.41,3672,78.98,977,21.02,101,6,97,28,102,0,206

sdgy-egf7 (1, 269) Census Combined Statistical Area in Colorado 2011

,the_geom,OBJECTID,CSAFP,GEOID,NAME,NAMELSAD,LSAD,MTFCC,ALAND,AWATER,INTPTLAT,INTPTLON,Shape_Leng,Shape_Area,LOGRECNO,NAMEACS,CSA,GEOID_1,POP0711,HISPANIC,WHITE_NH,BLACK_NH,NTVAM_NH,ASIAN_NH,HAWPI_NH,OTHER_NH,TWOPLUS_NH,MALE,FEMALE,AGELESS10,AGELESS18,AGE18_24,AGE25_34,AGE35_44,AGE45_64,AGE65PLUS,MED_AGE,HOUSEHOLDS,FAMILYHH,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSING_UN,OCC_HU,VAC_HU,OWNED,RENTED,POP25PLUS,NOHSDIPL,HSGRAD_SC,BACHL_HGHR,MED_HH_INC,MED_FAM_IN,PER_CAP_IN,MED_YR_BLT,MED_C_RENT,MED_G_RENT,MED_HM_VAL,CITZ_BIRTH,CITZ_NAT,NOT_CITZ,BORN_IN_CO,BRN_OTH_ST,NTV_B_O_US,FOREIGN_B,POP_1P,SAME_HOUSE,SAME_CNTY,SAME_STATE,DIFF_STATE,FRM_ABROAD,WRKRS_16PL,CAR_ALL,CAR_ALONE,CAR_CARPOO,PUBLIC_TRN,PT_BUS,PT_OTHER,BIKE,WALK,TR_OTHER,WRK_HOME,W_16PL_NH,T_LESS_10,T_10_19,T_20_29,T_30_39,T_40_59,T_60_PL,POP_3PL,ENROLLED,PRESCHOOL,KNDRGRTN,GR_1_4,GR_5_8,GR_9_12,UNDERGRAD,GRAD_PROF,N_ENROLLED,BLT_2000_P,B1990_1999,B1980_1989,B1970_1979,B1960_1969,B1950_1959,B1940_1949,B1939_E,OWN_OCC_HU,V_L_50K,V50K_100K,V100K_150K,V150K_200K,V200K_250K,V250K_300K,V300K_400K,V400K_500K,V500K_750K,V750K_1M,V_1M_PLUS,RNT_OCC_HU,RNTL400,R400T599,R600T799,R800T999,R1000T1249,R1250T1499,R1500T1999,R2000PL,RNOCSHR,AGE_0_9,AGE_10_19,AGE_20_29,AGE_30_39,AGE_40_49,AGE_50_59,AGE_60_69,AGE_70_79,AGE_80_PL,PS_Uni,PS_BELOW,ADJ_PS_Uni,ADJ_PS_Pov,AVGHHSIZE,MLOGRECNO,MPOP0711,MHISPANIC,MWHITE_NH,MBLACK_NH,MNTVAM_NH,MASIAN_NH,MHAWPI_NH,MOTHER_NH,MTWOPLUS_N,MMALE,MFEMALE,MAGELESS10,MAGELESS18,MAGE18_24,MAGE25_34,MAGE35_44,MAGE45_64,MAGE65PLUS,MMED_AGE,MHOUSEHOLD,MFAMILYHH,MNONFAMHH,MHHLDRALON,MHHLDR_NAL,MHOUSING_U,MOCC_HU,MVAC_HU,MOWNED,MRENTED,MPOP25PLUS,MNOHSDIPL,MHSGRAD_SC,MBACHL_HGH,MMED_HH_IN,MMED_FAM_I,MPER_CAP_I,MMED_YR_BL,MMED_C_REN,MMED_G_REN,MMED_HM_VA,MCITZ_BIRT,MCITZ_NAT,MNOT_CITZ,MBORN_IN_C,MBRN_OTH_S,MNTV_B_O_U,MFOREIGN_B,MPOP_1P,MSAME_HOUS,MSAME_CNTY,MSAME_STAT,MDIFF_STAT,MFRM_ABROA,MWRKRS_16P,MCAR_ALL,MCAR_ALONE,MCAR_CARPO,MPUBLIC_TR,MPT_BUS,MPT_OTHER,MBIKE,MWALK,MTR_OTHER,MWRK_HOME,MW_16PL_NH,MT_LESS_10,MT_10_19,MT_20_29,MT_30_39,MT_40_59,MT_60_PL,MPOP_3PL,MENROLLED,MPRESCHOOL,MKNDRGRTN,MGR_1_4,MGR_5_8,MGR_9_12,MUNDERGRAD,MGRAD_PROF,MN_ENROLLE,MBLT_2000_,MB1990_199,MB1980_198,MB1970_197,MB1960_196,MB1950_195,MB1940_194,MB1939_E,MOWN_OCC_H,MV_L_50K,MV50K_100K,MV100K_150,MV150K_200,MV200K_250,MV250K_300,MV300K_400,MV400K_500,MV500K_750,MV750K_1M,MV_1M_PLUS,MRNT_OCC_H,MRNTL400,MR400T599,MR600T799,MR800T999,MR1000T124,MR1250T149,MR1500T199,MR2000PL,MRNOCSHR,MAGE_0_9,MAGE_10_19,MAGE_20_29,MAGE_30_39,MAGE_40_49,MAGE_50_59,MAGE_60_69,MAGE_70_79,MAGE_80_PL,MPS_Uni,MPS_BELOW,MADJ_PS_Un,MADJ_PS_Po,MAVGHHSIZE
0,MULTIPOLYGON (((-105.055089 40.261793000000104...,1,216,216,"Denver-Aurora-Boulder, CO","Denver-Aurora-Boulder, CO CSA",M0,G3100,33824328640,260218695,39.816412,-104.770871,12.072415,3.58552,9480,"Denver-Aurora-Boulder, CO CSA; Colorado",216,8216,3050876,665563,2061400,138038,13469,103735,2633,5524,60514,1519249,1531627,435518,759809,287875,459026,454118,789680,300368,35.4,1196610,757434,439176,346392,92784,1294222,1196610,97612,788257,408353,2003192,212988,1006724,783480,61656,77146,32805,1980,804,911,247900,2693720,120863,236293,1308716,1350098,34906,357156,3007464,2442092,270074,177632,98788,18878,1541496,1302975,1153964,149011,67170,57338,9832,17942,37092,18538,97779,1443717,149595,393403,339953,276538,191729,92499,2921039,815793,55969,42986,169620,159530,164221,174841,48626,2105246,234274,211095,190395,260522,140281,120337,38572,98746,788257,27581,24801,69770,132138,146035,100045,126822,63400,62451,18556,16658,408353,20985,37345,88624,89043,70721,41097,36907,13015,10616,435518,405529,438349,458582,451741,411906,246085,123334,79832,3004770,366463,1690675,154588,2.51,9480,0,0,830,1291,750,1245,279,954,2034,544,544,2328,3300,2875,563,3562,2790,2731,0.1,3021,3576,3182,3187,1756,749,3021,2945,4513,3364,541,3472,6665,5123,362,622,206,1,5,6,815,4957,3012,4308,6614,6804,1634,4768,1277,9122,6669,4271,3443,1386,5727,6316,6097,3367,2138,1925,687,1079,1562,968,2169,6090,2668,4753,4266,3511,3494,2517,1769,3935,1508,1369,2542,2341,1815,3129,1512,4099,3125,2250,2867,2968,1862,1967,1094,1667,4513,1161,994,1763,2420,2053,1634,2212,1436,1408,732,805,3364,999,1631,2277,1912,1943,1345,1386,956,754,2328,2386,2870,2588,2499,1795,2652,57,54,1724,11714,4231,2901,0.01

2ddb-srxn (1, 323) Census Combined Statistical Area in Colorado 2012

,the_geom,OBJECTID,CSAFP,GEOID,NAME,NAMELSAD,LSAD,MTFCC,ALAND,AWATER,INTPTLAT,INTPTLON,Shape_Leng,Shape_Area,CSA,GEOID_1,NAME_1,LOGRECNO,POP0812,HISPANIC,WHITE_NH,BLACK_NH,NTVAM_NH,ASIAN_NH,HAWPI_NH,OTHER_NH,TWOPLUS_NH,MALE,FEMALE,AGELESS10,AGELESS18,AGE18_24,AGE25_34,AGE35_44,AGE45_64,AGE65PLUS,AGE_0_9,AGE_10_19,AGE_20_29,AGE_30_39,AGE_40_49,AGE_50_59,AGE_60_69,AGE_70_79,AGE_80_PL,MED_AGE,HOUSEHOLDS,FAMILYHH,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSING_UN,OCC_HU,VAC_HU,OWNED,RENTED,POP25PLUS,NOHSDIPL,HSGRAD_SC,BACHL_HGHR,MED_HH_INC,MED_FAM_IN,PER_CAP_IN,MED_YR_BLT,MED_C_RENT,MED_G_RENT,MED_HM_VAL,CITZ_BIRTH,CITZ_NAT,NOT_CITZ,BORN_IN_CO,BRN_OTH_ST,NTV_B_O_US,FOREIGN_B,POP_1P,SAME_HOUSE,SAME_CNTY,SAME_STATE,DIFF_STATE,FRM_ABROAD,WRKRS_16PL,CAR_ALL,CAR_ALONE,CAR_CARPOO,PUBLIC_TRN,PT_BUS,PT_OTHER,BIKE,WALK,TR_OTHER,WRK_HOME,W_16PL_NH,T_LESS_10,T_10_19,T_20_29,T_30_39,T_40_59,T_60_PL,POP_3PL,ENROLLED,PRESCHOOL,KNDRGRTN,GR_1_4,GR_5_8,GR_9_12,UNDERGRAD,GRAD_PROF,N_ENROLLED,BLT_2010_P,B2000_2009,B1990_1999,B1980_1989,B1970_1979,B1960_1969,B1950_1959,B1940_1949,B1939_E,OWN_OCC_HU,V_L_50K,V50K_100K,V100K_150K,V150K_200K,V200K_250K,V250K_300K,V300K_400K,V400K_500K,V500K_750K,V750K_1M,V_1M_PLUS,RNT_OCC_HU,RNTL400,R400T599,R600T799,R800T999,R1000T1249,R1250T1499,R1500T1999,R2000PL,RNOCSHR,PS_Uni,PS_BELOW,PS_BEL150,PUNI_L18,PUNI_65PL,POV_L18,POV_65PL,AVGHHSIZE,HHI_L20K,HHI20_30,HHI30_40,HHI40_50,HHI50_60,HHI60_75,HHI75_100,HHI100_125,HHI125_150,HHI150_200,HHI_200_PL,CIV_NI_POP,DISABLED,POP16_PLS,LABORFORCE,CIV_LF,EMP,UNEMP,ARMEDFRCS,NOT_LF,CIV_NI_P,INSURED,NOT_INS,LOGRECNO_1,MPOP0812,MHISPANIC,MWHITE_NH,MBLACK_NH,MNTVAM_NH,MASIAN_NH,MHAWPI_NH,MOTHER_NH,MTWOPLUS_N,MMALE,MFEMALE,MAGELESS10,MAGELESS18,MAGE18_24,MAGE25_34,MAGE35_44,MAGE45_64,MAGE65PLUS,MAGE_0_9,MAGE_10_19,MAGE_20_29,MAGE_30_39,MAGE_40_49,MAGE_50_59,MAGE_60_69,MAGE_70_79,MAGE_80_PL,MMED_AGE,MHOUSEHOLD,MFAMILYHH,MNONFAMHH,MHHLDRALON,MHHLDR_NAL,MHOUSING_U,MOCC_HU,MVAC_HU,MOWNED,MRENTED,MPOP25PLUS,MNOHSDIPL,MHSGRAD_SC,MBACHL_HGH,MMED_HH_IN,MMED_FAM_I,MPER_CAP_I,MMED_YR_BL,MMED_C_REN,MMED_G_REN,MMED_HM_VA,MCITZ_BIRT,MCITZ_NAT,MNOT_CITZ,MBORN_IN_C,MBRN_OTH_S,MNTV_B_O_U,MFOREIGN_B,MPOP_1P,MSAME_HOUS,MSAME_CNTY,MSAME_STAT,MDIFF_STAT,MFRM_ABROA,MWRKRS_16P,MCAR_ALL,MCAR_ALONE,MCAR_CARPO,MPUBLIC_TR,MPT_BUS,MPT_OTHER,MBIKE,MWALK,MTR_OTHER,MWRK_HOME,MW_16PL_NH,MT_LESS_10,MT_10_19,MT_20_29,MT_30_39,MT_40_59,MT_60_PL,MPOP_3PL,MENROLLED,MPRESCHOOL,MKNDRGRTN,MGR_1_4,MGR_5_8,MGR_9_12,MUNDERGRAD,MGRAD_PROF,MN_ENROLLE,MBLT_2010_,MB2000_201,MB1990_199,MB1980_198,MB1970_197,MB1960_196,MB1950_195,MB1940_194,MB1939_E,MOWN_OCC_H,MV_L_50K,MV50K_100K,MV100K_150,MV150K_200,MV200K_250,MV250K_300,MV300K_400,MV400K_500,MV500K_750,MV750K_1M,MV_1M_PLUS,MRNT_OCC_H,MRNTL400,MR400T599,MR600T799,MR800T999,MR1000T124,MR1250T149,MR1500T199,MR2000PL,MRNOCSHR,MPS_Uni,MPS_BELOW,MPS_BEL150,MPUNI_L18,MPUNI_65PL,MPOV_L18,MPOV_65PL,MAVGHHSIZE,MHHI_L20K,MHHI20_30,MHHI30_40,MHHI40_50,MHHI50_60,MHHI60_75,MHHI75_100,MHHI100_12,MHHI125_15,MHHI150_20,MHHI_200_P,MCIV_NI_PO,MDISABLED,MPOP16_PLS,MLABORFORC,MCIV_LF,MEMP,MUNEMP,MARMEDFRCS,MNOT_LF,MCIV_NI_P,MINSURED,MNOT_INS
0,MULTIPOLYGON (((-105.055089 40.261793000000104...,1,216,216,"Denver-Aurora-Boulder, CO","Denver-Aurora-Boulder, CO CSA",M0,G3100,33823599988,260890131,39.816412,-104.770871,12.072456,3.58552,216,34000US08216,"Denver-Aurora-Boulder, CO CSA; Colorado",9490,3105013,684013,2088872,140918,13412,106639,2857,4729,63573,1546983,1558030,437529,766820,291610,468895,455857,807007,314824,437529,411087,445627,463242,452945,422378,263710,126509,81986,35.5,1210463,766438,444025,349583,94442,1301847,1210463,91384,785664,424799,2046583,214231,1022665,809687,62384,78017,33121,1980,837,946,248800,2742393,128345,234275,1330335,1374486,37572,362620,3062353,2480897,275045,183989,102924,19498,1565285,1321782,1172455,149327,67457,57657,9800,19088,37118,18620,101220,1464065,150482,397050,343421,284114,193023,95975,2976665,835596,57627,43606,173449,164688,164877,180407,50942,2141069,4034,239500,212534,192261,261394,136697,118761,38260,98406,785664,28549,27293,73858,129060,137373,102374,126920,63966,61483,18663,16125,424799,21524,32545,85798,90029,78061,47582,42127,16318,10815,3057392,379493,621913,757551,306452,126237,24852,2.53,171254,106589,107910,102747,95831,124298,160944,116888,73253,77799,72950,3076707,272828,2420537,1730240,1726182,1591207,134975,4058,690297,3076707,2616972,459735,9490,0,157,852,1667,788,1607,276,850,2512,422,422,2515,3507,2648,508,3472,2928,2842,2515,2478,2640,2490,2467,1967,2760,1691,1485,0.1,3168,3438,3100,3349,1901,712,3168,2999,4862,3709,504,3534,7280,5742,344,572,183,1,4,5,820,5637,2713,4441,6213,5236,1805,5238,1192,8752,7228,4930,2958,1582,4868,4749,5476,3050,1816,1930,668,1142,1524,932,2422,5099,2779,4693,4167,3548,2717,2247,1354,3628,1461,1373,2246,2211,1700,2838,1521,3686,431,2503,2600,2083,2559,2067,1885,1132,1827,4862,1092,1071,1838,2208,2174,1923,2240,1276,1330,746,638,3709,1023,1382,2143,2204,2028,1675,1654,827,780,1296,6946,9820,4820,1413,2743,908,0.02,2579,2386,2397,2225,2175,2176,2737,1971,1772,1674,1516,1042,3363,1106,4352,4342,4765,2126,522,4493,1042,5079,4555

7yta-8qvv (354, 105) Census Places SF3 in Colorado 2000

,the_geom,OBJECTID,STATEFP00,PLACEFP00,PLCIDFP00,NAME00,NAMELSAD00,LSAD00,CLASSFP00,CPI00,PCICBSA00,PCINECTA00,MTFCC00,UR00,FUNCSTAT00,ALAND00,AWATER00,INTPTLAT00,INTPTLON00,Shape_Leng,Shape_Area,STATE,PLACE,GEOIDPLACE,NAME10,POP_SF3,HISPANIC,PCTHISP,WHITE_NH,PCTWHITE,BLACK_NH,PCTBLACK,NTV_AM_NH,PCTNTVAM,ASIAN_NH,PCTASIAN,HAWPI_NH,PCTHAW,OTHER_NH,PCTOTHER,TWOPLUS_NH,PCT_TWOP,MALE,PCT_MALE,FEMALE,PCT_FEMALE,AGELESS10,PCT_L10,AGELESS18,PCT_L18,AGE65PLUS,PCT_65PL,HHLDS,FAMHH,MARCOUPFAM,OTH_FAM,MHHLDR_N_W,FHHLDR_N_H,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSINGU,URBANHU,PCT_URBHU,RURALHU,PCT_RURHU,OCCHU,PCTOCC,VACHU,PCTVAC,OWN,PCTOWN,RENT,PCTRENT,TTLPOP25PL,NO_HS_DIPL,PCT_NODIPL,HSGRAD_PL,PCT_HSPLUS,BACHL_HGHR,PCT_BACHPL,MEDHHINC,MEDFAMINC,PERCAPINC,MEDYRBLT,MEDCRENT,MEDGRENT,MEDVAL,POP3PLUS,ENROLLED,PRESCHOOL,KINDRGRTN,GRADE_1_4,GRADE_5_8,GRADE_9_12,UNDERGRAD,GRADSCH,NOTINSCH,NATIVE,PCTNATIVE,FOREIGN,PCTFOREIGN,PVRTY_UNI,IN_POVERTY,PCT_PVRTY
0,MULTIPOLYGON (((-104.50361500000001 37.1490150...,1,8,78610,878610,Trinidad,Trinidad city,25,C1,Y,N,N,G4110,M,A,16161894,1008,37.168467,-104.504743,0.525528,0.001640,8,78610,878610,Trinidad city,9017,4307,47.77,4489,49.78,7,0.08,74,0.82,41,0.45,12,0.13,13,0.14,74,0.82,4275,47.41,4742,52.59,1198,13.29,2233,24.76,1818,20.16,3697,2308,1636,672,159,513,165,1224,2473,4106,4062,98.93,44,1.07,3721,90.62,385,9.38,2404,64.61,1317,35.39,5910,1423,24.08,4487,75.92,992,16.79,26681,33992,17271,1946,322,388,86000,8673,2453,186,90,502,531,545,576,23,6220,8803,97.63,214,2.37,8689,1591,18.31
1,MULTIPOLYGON (((-104.52401600000012 37.1180050...,2,8,73715,873715,Starkville,Starkville town,43,C1,N,N,N,G4110,R,A,179163,0,37.116774,-104.523236,0.025910,0.000018,8,73715,873715,Starkville town,149,109,73.15,40,26.85,0,0.00,0,0.00,0,0.00,0,0.00,0,0.00,0,0.00,71,47.65,78,52.35,22,14.77,33,22.15,9,6.04,51,38,34,4,0,4,2,11,40,62,0,0.00,62,100.00,51,82.26,11,17.74,43,84.31,8,15.69,94,21,22.34,73,77.66,3,3.19,42708,50000,14297,1939,258,458,52500,144,41,3,1,11,12,5,9,0,103,145,97.32,4,2.68,149,15,10.07
2,MULTIPOLYGON (((-103.3566270000001 37.24242800...,3,8,40570,840570,Kim,Kim town,43,C1,N,N,N,G4110,R,A,793441,0,37.246594,-103.352930,0.036596,0.000081,8,40570,840570,Kim town,76,19,25.00,57,75.00,0,0.00,0,0.00,0,0.00,0,0.00,0,0.00,0,0.00,40,52.63,36,47.37,3,3.95,8,10.53,10,13.16,47,18,18,0,0,0,0,29,18,56,0,0.00,56,100.00,45,80.36,11,19.64,40,88.89,5,11.11,66,8,12.12,58,87.88,14,21.21,25938,36667,16343,1954,208,358,22500,76,13,0,0,0,5,2,0,6,63,76,100.00,0,0.00,76,11,14.47

fjhv-ruxa (1, 100) Census State SF3 in Colorado 2000

,the_geom,OBJECTID,REGION00,DIVISION00,STATEFP00,STUSPS00,NAME00,LSAD00,MTFCC00,UR00,FUNCSTAT00,ALAND00,AWATER00,INTPTLAT00,INTPTLON00,Shape_Leng,Shape_Area,STATE,NAME10,POP_SF3,HISPANIC,PCTHISP,WHITE_NH,PCTWHITE,BLACK_NH,PCTBLACK,NTV_AM_NH,PCTNTVAM,ASIAN_NH,PCTASIAN,HAWPI_NH,PCTHAW,OTHER_NH,PCTOTHER,TWOPLUS_NH,PCT_TWOP,MALE,PCT_MALE,FEMALE,PCT_FEMALE,AGELESS10,PCT_L10,AGELESS18,PCT_L18,AGE65PLUS,PCT_65PL,HHLDS,FAMHH,MARCOUPFAM,OTH_FAM,MHHLDR_N_W,FHHLDR_N_H,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSINGU,URBANHU,PCT_URBHU,RURALHU,PCT_RURHU,OCCHU,PCTOCC,VACHU,PCTVAC,OWN,PCTOWN,RENT,PCTRENT,TTLPOP25PL,NO_HS_DIPL,PCT_NODIPL,HSGRAD_PL,PCT_HSPLUS,BACHL_HGHR,PCT_BACHPL,MEDHHINC,MEDFAMINC,PERCAPINC,MEDYRBLT,MEDCRENT,MEDGRENT,MEDVAL,POP3PLUS,ENROLLED,PRESCHOOL,KINDRGRTN,GRADE_1_4,GRADE_5_8,GRADE_9_12,UNDERGRAD,GRADSCH,NOTINSCH,NATIVE,PCTNATIVE,FOREIGN,PCTFOREIGN,PVRTY_UNI,IN_POVERTY,PCT_PVRTY,GEOCOMP
0,MULTIPOLYGON (((-109.04348800000007 37.4846840...,1,4,8,8,CO,Colorado,0,G4000,M,A,268430974616,1170104667,38.993575,-105.507774,22.061936,28.039481,8,Colorado,4301261,735099,17.09,3201519,74.43,153932,3.58,29286,0.68,91387,2.12,3655,0.08,5255,0.12,81128,1.89,2163954,50.31,2137307,49.69,604057,14.04,1096790,25.5,415782,9.67,1659308,1092352,875669,216683,64545,152138,131668,435288,1224020,1808037,1482233,81.98,325804,18.02,1658238,91.71,149799,8.29,1116305,67.32,541933,32.68,2776632,363039,13.07,2413593,86.93,907755,32.69,47203,55883,24049,1976,611,671,160100,4123063,1166004,79064,61749,254401,248718,239240,225316,57516,2957059,3931358,91.4,369903,8.6,4202140,388952,9.26,0

tfrg-b5pp (1249, 157) Census Tracts in Colorado 2016

,geonum,pop,geoname,the_geom,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age70_74,age65_69,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,108001008000,6223,80.00,"MULTIPOLYGON (((-104.86594 39.75474, -104.8540...",3072,1501,1319,53,203,0,5,70,3139,3084,603,598,456,641,355,604,271,465,245,463,409,280,329,177,179,86,39,23,2040,613,28.6,1742,1173,569,439,130,1796,1742,54,999,743,3570,1022,2107,441,49898.0,52837.0,18154.0,1955.0,909.0,1032.0,168400.0,4643,270,1310,3062,1556,25,1580,6120,5248,193,387,207,85,2610,2304,1764,540,203,203,0,1,19,21,62,2548,84,664,664,558,327,251,5939,1796,136,36,435,409,596,126,58,4143,0,0,45,63,132,173,901,396,86,999,18,72,335,315,176,83,0,0,0,0,0,743,21,7,199,103,142,64,153,7,47,6185,1370,2322,2002,504,598,37,3.57,270,193,196,214,249,174,249,113,17,60,7,6223,707,4484,2978,2978,2706,272,0,1506,6223
1,108001008506,6365,85.06,"MULTIPOLYGON (((-104.98987 39.914063999999996,...",2159,3801,254,22,125,0,0,4,3207,3158,367,479,348,343,581,789,425,514,289,440,269,439,206,167,190,205,143,171,1407,711,33.4,2592,1216,1376,1145,231,2730,2592,138,454,2138,4247,576,3128,543,34944.0,44659.0,19860.0,1978.0,930.0,1060.0,163200.0,5790,190,385,3343,2353,94,575,6325,4853,821,456,174,21,3062,2626,2317,309,250,250,0,21,88,0,77,2985,309,815,476,733,396,256,6155,1528,43,104,408,291,218,388,76,4627,96,412,264,398,1072,405,51,17,15,454,27,13,107,226,64,0,17,0,0,0,0,2138,105,14,292,439,876,221,126,47,18,6289,1255,2153,1384,840,356,158,2.39,527,511,378,329,170,210,237,168,29,28,5,6312,1385,5136,3332,3332,3090,242,0,1804,6312
2,108001008508,5816,85.08,"MULTIPOLYGON (((-104.958888 39.907543, -104.95...",1491,3865,43,44,271,0,18,84,2935,2881,415,502,489,448,187,438,512,524,411,361,400,418,248,100,234,59,51,19,1692,349,34.0,1939,1420,519,378,141,1992,1939,53,1217,722,3775,384,2430,961,70799.0,76006.0,27305.0,1979.0,1235.0,1378.0,216000.0,5479,110,227,3221,2201,57,337,5750,4861,595,241,53,0,3017,2721,2523,198,72,72,0,9,14,30,171,2846,90,442,549,788,743,234,5557,1651,141,74,417,403,357,116,143,3906,0,162,487,248,1011,50,28,6,0,1217,38,18,122,307,387,221,124,0,0,0,0,722,0,0,8,21,182,292,175,44,0,5744,323,650,1620,463,84,9,3.00,130,101,172,190,214,248,257,240,253,78,56,5816,602,4322,3167,3167,3036,131,0,1155,5816

t3uw-qtqc (458, 157) Census Places in Colorado 2015

,the_geom,pop,geoname,geonum,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,MULTIPOLYGON (((-103.285958 40.557964999999996...,228,Atwood,10803840,0,228,0,0,0,0,0,0,132,96,27,9,18,8,11,25,15,9,0,20,33,8,5,23,13,4,0,0,62,11,37.1,69,52,17,17,0,69,69,0,44,25,155,5,138,12,60469.0,60313.0,26865.0,1939.0,NaN,NaN,213000.0,228,0,0,186,42,0,0,228,228,0,0,0,0,105,89,89,0,0,0,0,0,0,0,16,89,26,28,18,15,0,2,201,35,0,0,9,18,8,0,0,166,0,0,8,0,9,0,8,0,44,44,0,12,4,0,23,0,5,0,0,0,0,25,0,0,9,0,0,0,0,0,16,228,0,15,62,40,0,0,3.30,12,0,21,0,0,13,3,9,0,11,0,228,47,170,105,105,105,0,0,65,228
1,"MULTIPOLYGON (((-108.589076 39.055752, -108.58...",10086,Redlands,10863375,601,9111,29,0,116,0,0,229,5105,4981,454,464,780,611,295,449,349,393,749,435,837,892,1028,912,600,425,184,229,2104,500,50.3,3980,3023,957,693,264,4194,3980,214,3490,490,7482,572,4260,2650,67538.0,76992.0,32109.0,1977.0,1088.0,1235.0,275400.0,9826,147,113,4047,5704,75,260,9997,8859,636,48,344,110,4362,3745,3382,363,4,4,0,0,52,84,477,3885,510,2105,677,134,44,415,9845,2008,152,33,382,726,461,251,3,7837,18,519,690,486,1189,651,430,55,156,3490,130,33,214,469,624,541,690,362,354,57,16,490,0,8,0,44,137,161,12,0,128,10060,747,1098,2078,2350,141,181,2.52,425,337,386,333,299,431,683,432,188,239,227,10086,1271,8313,4793,4793,4441,352,0,3520,10086
2,"MULTIPOLYGON (((-104.517529 39.748404, -104.50...",345867,Aurora,10804000,99640,160245,52886,1317,18007,944,952,11876,169364,176503,27016,26978,24272,22368,24515,27411,27566,24971,24595,22123,21626,20077,17754,12609,8322,5527,4158,3979,91799,33350,33.6,124031,81847,42184,34212,7972,130995,124031,6964,70402,53629,220718,29724,129363,61631,53011.0,61186.0,25115.0,1982.0,882.0,1024.0,189100.0,278070,22842,44955,137718,134210,6142,67797,340612,264518,37387,24227,10902,3578,166961,146472,127900,18572,9804,8533,1271,442,2548,1483,6212,160749,9892,35898,41185,37513,22291,13970,329385,93479,5314,5222,20686,19570,19577,18141,4969,235906,2519,23203,13199,34381,36793,9165,8801,1786,1148,70402,3441,5773,11795,17783,13062,7587,6314,2554,1664,232,197,53629,1271,2602,9218,12092,12138,7810,6479,1133,886,342842,52453,89046,90376,33497,20043,2688,2.77,17281,13659,13511,13343,11819,14561,15617,10257,5519,4928,3536,342885,34903,262968,186457,185008,168912,16096,1449,76511,342885

fr27-d5rz (1, 157) Census State in Colorado 2012

,pop,geonum,the_geom,geoname,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,5042853,108,"MULTIPOLYGON (((-102.04224 36.993083, -102.054...",Colorado,1040478,3528458,190846,27990,134749,5441,7666,107225,2529614,2513239,340829,348656,330838,340530,353131,372044,358805,350827,352616,366354,369628,329302,270950,186348,130072,97556,73333,71034,1220279,493705,36.1,1962753,1259998,702755,554435,148320,2211615,1962753,248862,1293951,668802,3328869,335459,1772504,1220906,58244,72455,31039,1980,802,915,236800,4552899,174877,315077,2129786,2352735,70378,489954,4977054,4021459,482260,247079,192744,33512,2481269,2102911,1850845,252066,80763,70285,10478,32578,75896,28817,160304,2320965,332478,698656,510765,381272,251171,146623,4842352,1348573,89501,69416,275169,264446,267159,308320,74562,3493779,6989,403411,379165,331838,440630,212580,181247,65318,190437,1293951,64133,67726,135408,224141,211373,153166,191949,96211,92888,28664,28292,668802,37508,65839,137941,134878,116307,69759,59286,22495,24789,4927283,633878,1044715,1204622,542669,205865,43960,2.51,299481,186106,184880,174246,162098,205975,256412,176090,108699,109930,98836,4949633,487297,3955983,2749557,2717391,2498972,218419,32166,1206426,4949633

232d-4jxg (1249, 157) Census Tracts in Colorado 2013

,geonum,geoname,pop,the_geom,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,108031004202,"Census Tract 42.02, Denver County, Colorado",3893,"MULTIPOLYGON (((-104.922275 39.743733, -104.92...",230,2907,370,110,98,3,15,160,1806,2087,256,203,165,366,285,109,282,251,254,149,327,485,255,270,111,18,68,39,721,554,40.3,1535,998,537,366,171,1649,1535,114,1411,124,2618,69,635,1914,117837.0,139500.0,58749.0,1939.0,1199.0,1630.0,423300.0,3744,117,32,1074,2566,104,149,3857,3170,200,334,138,15,2240,1709,1543,166,52,52,0,72,117,20,270,1970,211,764,499,307,162,27,3697,1066,61,61,127,146,159,475,37,2631,0,33,18,10,40,27,155,363,1003,1411,10,9,46,105,80,121,271,273,387,69,40,124,0,0,10,10,17,0,54,11,22,3503,223,399,700,506,2,42,2.28,119,72,76,72,51,96,181,145,157,261,305,3877,164,3231,2375,2375,2263,112,0,856,3877
1,108005080000,"Census Tract 800, Arapahoe County, Colorado",3330,"MULTIPOLYGON (((-104.865971 39.711053, -104.86...",855,1295,751,0,347,0,17,65,1527,1803,308,197,146,242,233,325,237,195,211,237,237,270,112,117,133,61,48,21,790,336,34.4,1293,805,488,384,104,1385,1293,92,619,674,2204,237,1606,361,48656.0,53140.0,20239.0,1974.0,594.0,717.0,162700.0,2406,298,626,1321,1054,31,924,3239,2442,360,383,32,22,1612,1303,1166,137,223,211,12,9,29,41,7,1605,89,312,435,388,188,193,3120,745,6,0,136,114,164,273,52,2375,0,17,10,140,939,240,24,0,15,619,35,51,124,301,101,0,7,0,0,0,0,674,0,180,285,80,48,10,41,0,30,3330,742,1342,790,380,302,12,2.58,331,143,120,81,195,156,158,65,31,6,7,3330,274,2642,1947,1947,1645,302,0,695,3330
2,108041001700,"Census Tract 17, El Paso County, Colorado",1844,MULTIPOLYGON (((-104.817546 38.844964999999995...,264,1358,38,4,40,0,0,140,886,958,75,56,36,108,412,131,183,165,91,111,116,138,84,45,13,36,31,13,213,474,32.6,903,355,548,399,149,944,903,41,409,494,1157,82,577,498,35982.0,55568.0,22629.0,1939.0,636.0,679.0,169500.0,1706,92,46,643,1035,28,138,1828,1123,472,55,107,71,1200,844,735,109,10,10,0,144,126,15,61,1139,384,366,261,83,37,8,1807,493,24,6,31,36,73,296,27,1314,0,17,37,53,90,49,46,35,617,409,13,28,108,105,99,22,30,0,0,0,4,494,76,99,127,54,33,33,53,0,19,1844,540,694,213,138,31,35,2.04,284,133,67,95,66,93,103,35,0,27,0,1823,206,1671,1314,1293,1192,101,21,357,1823

f8ak-7nmp (64, 157) Census Counties in Colorado 2014

,pop,the_geom,geoname,geonum,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_60_pl,t_40_59,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,633777,"MULTIPOLYGON (((-104.934135 39.700181, -104.93...",Denver,108031,197760,334981,59987,3775,21774,517,1134,13849,316841,316936,44386,39211,32660,31145,45256,70917,64996,51456,45667,37778,36917,35398,30960,22195,14623,10831,8893,10488,133508,59150,34.0,271054,130387,140667,108602,32065,290624,271054,19570,134843,136211,441119,63613,184602,192904,51800,66522,34423,1965,825,913,257500,532072,33484,68221,264919,259116,8037,101705,624174,480374,67643,44840,26069,5248,329735,260139,229730,30409,22814,19173,3641,7929,14762,3545,20546,309189,29818,94726,76945,60036,17074,30590,606676,152164,11377,8429,30291,25684,23510,38005,14868,454512,4172,39812,19971,23969,41111,34843,46888,20341,59517,134843,4000,7583,16549,19785,17265,14973,22030,12149,12896,4022,3591,136211,11089,9941,28164,28089,21492,14378,14088,6149,2821,621206,113930,180309,132028,65212,36533,7710,2.28,52505,27653,26410,24228,20360,24242,31578,20286,12284,14136,17372,627155,60529,511703,363279,362909,334730,28179,370,148424,627155
1,1389,"MULTIPOLYGON (((-106.872822 40.975877, -106.87...",Jackson,108057,257,1122,1,2,5,0,0,2,750,639,55,116,82,43,34,63,117,58,75,108,139,118,96,114,55,46,30,40,282,48,46.5,644,389,255,231,24,1273,644,629,443,201,1059,164,710,185,45606,58036,25818,1974,527,708,124800,1288,2,99,613,664,11,101,1389,1268,48,32,32,9,777,542,477,65,6,6,0,0,93,18,118,659,318,95,56,55,82,53,1361,280,11,15,110,68,35,40,1,1081,0,128,255,95,247,114,80,55,299,443,85,68,89,40,50,35,41,26,0,3,6,201,3,33,55,16,20,0,0,0,74,1377,203,387,282,285,65,8,2.12,140,64,64,93,45,85,103,20,9,15,6,1377,141,1136,796,796,786,10,0,340,1377
2,147509,"MULTIPOLYGON (((-109.060253 38.599328, -109.05...",Mesa,108077,20161,121600,996,552,893,131,287,2889,73346,74163,9567,9614,9020,10199,10382,9983,9467,8726,7879,8848,10625,10637,9143,7270,5455,4458,3147,3089,33840,14942,38.2,58966,38386,20580,16179,4401,63230,58966,4264,41098,17868,98727,10185,63641,24901,48610,60660,26518,1984,715,841,203200,142434,2075,3000,72310,69356,768,5075,145522,117038,18023,4863,5132,466,66035,58566,51937,6629,256,256,0,972,1866,1036,3339,62696,11217,28767,11586,4516,4296,2314,142095,37108,2381,1778,7512,7415,7575,9414,1033,104987,651,14406,10876,8826,13880,3308,4513,1884,4886,41098,2904,2166,6034,9014,6844,4609,4920,2154,1877,321,255,17868,1552,1918,4243,2942,2868,1807,1217,298,1023,144055,22726,36559,33261,22881,6827,2046,2.44,11101,6745,6736,5583,4853,5874,7101,4631,2363,2471,1508,146218,20108,117078,73943,73943,67168,6775,0,43135,146218

xwky-bmsn (64, 157) Census Counties in Colorado 2012

,the_geom,pop,geonum,geoname,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,"MULTIPOLYGON (((-104.904049 39.625436, -104.90...",574357,108005,Arapahoe,105174,364766,55629,2211,28067,1166,1267,16077,281842,292515,40293,42488,38810,38590,35384,43033,41905,40495,42102,42441,42459,37217,30184,20270,12857,10334,7728,7767,146638,48927,35.7,223747,146752,76995,64531,12464,238160,223747,14413,143158,80589,378792,33815,199197,145780,60400,74070,32845,1982,831,950,230900,487576,32364,54417,223433,255812,8331,86781,566158,460748,47140,36663,17726,3881,288166,251085,225537,25548,13580,9899,3681,1220,4616,3073,14592,273574,24031,66870,69870,58419,37774,16610,549701,153854,9701,7813,33703,30902,33425,29388,8922,395847,550,39415,33989,56011,62253,22258,16519,3310,3855,143158,4207,6725,15449,27839,28096,18368,19845,8679,7660,2826,3464,80589,1819,5940,16759,19643,15414,9391,7703,2277,1643,568999,66945,113912,144576,57167,23054,5014,2.55,30852,20763,21131,19443,19049,24101,28404,20955,13180,12720,13149,568663,49870,444215,320199,318041,292089,25952,2158,124016,568663
1,MULTIPOLYGON (((-106.710775 37.404227999999996...,702,108079,Mineral,15,671,9,5,1,0,0,1,327,375,7,0,14,7,52,20,12,28,7,33,78,89,114,65,105,32,14,25,26,54,60.3,363,220,143,138,5,1311,363,948,305,58,622,24,361,237,52750,67083,42539,1982,684,707,273600,688,7,7,194,488,6,14,695,651,17,21,6,0,361,254,241,13,6,6,0,2,48,0,51,310,160,64,43,19,21,3,695,37,0,0,0,11,8,14,4,658,0,222,232,239,203,100,75,34,206,305,45,11,20,54,8,35,45,11,45,20,11,58,0,8,22,7,0,4,0,0,17,702,47,163,26,241,0,13,1.83,89,33,38,19,29,53,55,29,5,6,7,702,129,681,391,391,370,21,0,290,702
2,MULTIPOLYGON (((-109.04183664011401 38.1530220...,40994,108085,Montrose,8037,31799,186,74,227,49,33,589,20134,20860,2533,3025,2669,2473,1937,2233,2165,2188,2632,2818,3126,2892,2889,2294,1853,1518,894,855,9985,2652,42.6,16732,11646,5086,4228,858,18178,16732,1446,12406,4326,28357,4262,17549,6546,47139,54471,23018,1985,652,816,200900,37990,748,2256,18954,18750,286,3004,40592,33891,3506,1591,1349,255,17689,15885,13094,2791,24,24,0,60,386,235,1099,16590,4416,6554,2109,1096,839,1576,39618,9350,740,863,2088,2177,2397,896,189,30268,8,4182,3750,2106,3581,1298,920,397,1936,12406,1311,876,1400,2588,1908,1297,1437,777,593,72,147,4326,511,575,780,674,983,214,61,65,463,40368,5565,10753,9788,7209,1927,710,2.41,3166,1843,1957,1799,1890,1845,2206,1025,408,311,282,40552,5649,32334,20137,20124,18110,2014,13,12197,40552

5yyk-mqmn (64, 157) Census Counties in Colorado 2015

,the_geom,pop,geonum,geoname,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,"MULTIPOLYGON (((-105.055836 39.625994, -105.05...",552344,108059,Jefferson,83142,435423,5535,2917,13944,269,609,10505,274525,277819,29684,32449,34023,33879,33882,36984,36719,35099,36481,39468,45448,43030,37261,27290,18324,13358,9319,9646,117276,46641,40.4,222892,144412,78480,61606,16874,232477,222892,9585,155713,67179,388427,23268,203465,161694,70164,86565,37065,1977,934,1052,279500,516407,17800,18137,258525,251681,6201,35937,546968,463863,37595,27466,15930,2114,289922,251186,228107,23079,9347,7587,1760,1758,4485,2933,20213,269709,24854,69058,62191,53678,41816,18112,534681,133888,8868,6031,26082,26357,29405,29031,8114,400793,2361,23695,34576,38839,65394,32048,22811,5720,7033,155713,4008,2899,8478,18034,28778,26530,31868,16347,13282,3630,1859,67179,2109,2735,10398,14529,14200,10012,8569,2853,1774,543273,46423,76499,115604,76072,13613,3847,2.44,24274,16234,18886,19083,17127,23377,31982,24181,15384,17073,15291,545981,52495,449317,313044,312852,294390,18462,192,136273,545981
1,"MULTIPOLYGON (((-105.501286 37.598603, -105.49...",6502,108055,Huerfano,2252,4172,20,7,12,0,13,26,3290,3212,106,352,442,228,238,251,325,218,299,322,586,586,681,556,533,308,248,223,1034,332,53.5,3024,1720,1304,1135,169,5116,3024,2092,2207,817,5136,594,3152,1390,31715,43909,23467,1975,434,597,147600,6310,145,47,3495,2732,83,192,6486,5668,312,237,263,6,2156,1720,1399,321,43,43,0,18,246,8,121,2035,704,619,198,180,113,221,6429,1069,35,16,403,249,206,123,37,5360,51,748,851,634,523,260,330,168,1551,2207,253,594,267,277,271,118,167,71,86,45,58,817,115,227,173,90,63,6,0,0,143,6319,1171,2053,1034,1756,197,229,2.08,868,561,324,312,169,284,244,97,30,53,82,6319,1493,5541,2601,2601,2211,390,0,2940,6319
2,"MULTIPOLYGON (((-106.210173 39.103918, -106.20...",16189,108093,Park,916,14635,0,175,156,124,0,183,8525,7664,627,733,871,814,620,569,760,838,1147,1263,1821,1873,1749,1173,776,256,143,156,2774,891,49.4,7319,4502,2817,2318,499,14134,7319,6815,6027,1292,12524,533,8333,3658,56969,69234,31734,1990,858,1088,244800,15497,271,421,5054,10296,147,692,16045,13649,565,1220,580,31,8744,7517,6340,1177,111,86,25,0,100,45,971,7773,847,895,793,968,1988,2282,15806,2925,137,172,572,668,828,355,193,12881,53,3706,3443,2134,2480,1005,454,61,798,6027,287,127,408,1120,1197,863,1263,359,332,20,51,1292,117,94,224,115,195,184,189,119,55,16062,1170,2522,2751,2497,224,125,2.20,929,887,705,615,635,890,1055,673,459,331,140,16041,1644,13829,9380,9347,8822,525,33,4449,16041

xg8m-4prc (178, 327) Census School Districts in Colorado 2012

,the_geom,OBJECTID,STATEFP,UNSDLEA,GEOID,NAME,LSAD,LOGRADE,HIGRADE,MTFCC,SDTYP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,Shape_Leng,Shape_Area,SDUNI,GEOID_1,NAME_1,LOGRECNO,POP0812,HISPANIC,WHITE_NH,BLACK_NH,NTVAM_NH,ASIAN_NH,HAWPI_NH,OTHER_NH,TWOPLUS_NH,MALE,FEMALE,AGELESS10,AGELESS18,AGE18_24,AGE25_34,AGE35_44,AGE45_64,AGE65PLUS,AGE_0_9,AGE_10_19,AGE_20_29,AGE_30_39,AGE_40_49,AGE_50_59,AGE_60_69,AGE_70_79,AGE_80_PL,MED_AGE,HOUSEHOLDS,FAMILYHH,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSING_UN,OCC_HU,VAC_HU,OWNED,RENTED,POP25PLUS,NOHSDIPL,HSGRAD_SC,BACHL_HGHR,MED_HH_INC,MED_FAM_IN,PER_CAP_IN,MED_YR_BLT,MED_C_RENT,MED_G_RENT,MED_HM_VAL,CITZ_BIRTH,CITZ_NAT,NOT_CITZ,BORN_IN_CO,BRN_OTH_ST,NTV_B_O_US,FOREIGN_B,POP_1P,SAME_HOUSE,SAME_CNTY,SAME_STATE,DIFF_STATE,FRM_ABROAD,WRKRS_16PL,CAR_ALL,CAR_ALONE,CAR_CARPOO,PUBLIC_TRN,PT_BUS,PT_OTHER,BIKE,WALK,TR_OTHER,WRK_HOME,W_16PL_NH,T_LESS_10,T_10_19,T_20_29,T_30_39,T_40_59,T_60_PL,POP_3PL,ENROLLED,PRESCHOOL,KNDRGRTN,GR_1_4,GR_5_8,GR_9_12,UNDERGRAD,GRAD_PROF,N_ENROLLED,BLT_2010_P,B2000_2009,B1990_1999,B1980_1989,B1970_1979,B1960_1969,B1950_1959,B1940_1949,B1939_E,OWN_OCC_HU,V_L_50K,V50K_100K,V100K_150K,V150K_200K,V200K_250K,V250K_300K,V300K_400K,V400K_500K,V500K_750K,V750K_1M,V_1M_PLUS,RNT_OCC_HU,RNTL400,R400T599,R600T799,R800T999,R1000T1249,R1250T1499,R1500T1999,R2000PL,RNOCSHR,PS_Uni,PS_BELOW,PS_BEL150,PUNI_L18,PUNI_65PL,POV_L18,POV_65PL,AVGHHSIZE,HHI_L20K,HHI20_30,HHI30_40,HHI40_50,HHI50_60,HHI60_75,HHI75_100,HHI100_125,HHI125_150,HHI150_200,HHI_200_PL,CIV_NI_POP,DISABLED,POP16_PLS,LABORFORCE,CIV_LF,EMP,UNEMP,ARMEDFRCS,NOT_LF,CIV_NI_P,INSURED,NOT_INS,LOGRECNO_1,MPOP0812,MHISPANIC,MWHITE_NH,MBLACK_NH,MNTVAM_NH,MASIAN_NH,MHAWPI_NH,MOTHER_NH,MTWOPLUS_N,MMALE,MFEMALE,MAGELESS10,MAGELESS18,MAGE18_24,MAGE25_34,MAGE35_44,MAGE45_64,MAGE65PLUS,MAGE_0_9,MAGE_10_19,MAGE_20_29,MAGE_30_39,MAGE_40_49,MAGE_50_59,MAGE_60_69,MAGE_70_79,MAGE_80_PL,MMED_AGE,MHOUSEHOLD,MFAMILYHH,MNONFAMHH,MHHLDRALON,MHHLDR_NAL,MHOUSING_U,MOCC_HU,MVAC_HU,MOWNED,MRENTED,MPOP25PLUS,MNOHSDIPL,MHSGRAD_SC,MBACHL_HGH,MMED_HH_IN,MMED_FAM_I,MPER_CAP_I,MMED_YR_BL,MMED_C_REN,MMED_G_REN,MMED_HM_VA,MCITZ_BIRT,MCITZ_NAT,MNOT_CITZ,MBORN_IN_C,MBRN_OTH_S,MNTV_B_O_U,MFOREIGN_B,MPOP_1P,MSAME_HOUS,MSAME_CNTY,MSAME_STAT,MDIFF_STAT,MFRM_ABROA,MWRKRS_16P,MCAR_ALL,MCAR_ALONE,MCAR_CARPO,MPUBLIC_TR,MPT_BUS,MPT_OTHER,MBIKE,MWALK,MTR_OTHER,MWRK_HOME,MW_16PL_NH,MT_LESS_10,MT_10_19,MT_20_29,MT_30_39,MT_40_59,MT_60_PL,MPOP_3PL,MENROLLED,MPRESCHOOL,MKNDRGRTN,MGR_1_4,MGR_5_8,MGR_9_12,MUNDERGRAD,MGRAD_PROF,MN_ENROLLE,MBLT_2010_,MB2000_201,MB1990_199,MB1980_198,MB1970_197,MB1960_196,MB1950_195,MB1940_194,MB1939_E,MOWN_OCC_H,MV_L_50K,MV50K_100K,MV100K_150,MV150K_200,MV200K_250,MV250K_300,MV300K_400,MV400K_500,MV500K_750,MV750K_1M,MV_1M_PLUS,MRNT_OCC_H,MRNTL400,MR400T599,MR600T799,MR800T999,MR1000T124,MR1250T149,MR1500T199,MR2000PL,MRNOCSHR,MPS_Uni,MPS_BELOW,MPS_BEL150,MPUNI_L18,MPUNI_65PL,MPOV_L18,MPOV_65PL,MAVGHHSIZE,MHHI_L20K,MHHI20_30,MHHI30_40,MHHI40_50,MHHI50_60,MHHI60_75,MHHI75_100,MHHI100_12,MHHI125_15,MHHI150_20,MHHI_200_P,MCIV_NI_PO,MDISABLED,MPOP16_PLS,MLABORFORC,MCIV_LF,MEMP,MUNEMP,MARMEDFRCS,MNOT_LF,MCIV_NI_P,MINSURED,MNOT_INS
0,MULTIPOLYGON (((-107.58822100000002 37.9703120...,1,8,4620,804620,Hinsdale County School District RE-1,0,PK,12,G5420,NaN,E,2125045835,11982020,37.910936,-107.255956,2.692110,0.218986,4620,97000US0804620,"Hinsdale County School District RE-1, Colorado",9874,741,19,715,0,0,0,0,0,7,334,407,82,89,10,99,14,315,214,82,8,45,63,58,193,181,81,30,56.1,353,233,120,93,27,1420,353,1067,276,77,642,34,331,277,57250,79531,36696,1979,543,846,255400,730,9,2,192,520,18,11,729,606,7,71,45,0,330,184,166,18,0,0,0,23,83,15,25,305,228,23,31,5,0,18,703,53,30,10,4,7,0,1,1,650,0,110,295,274,280,117,113,31,200,276,0,3,23,55,54,28,45,30,22,14,2,77,0,6,16,36,7,0,0,0,12,741,40,149,89,214,0,26,2.07,38,37,41,11,52,25,71,39,14,13,12,741,110,652,358,358,343,15,0,294,741,598,143,9874,136,27,134,12,12,12,12,12,6,79,81,43,49,26,47,27,76,48,43,25,34,44,34,65,41,33,18,3.4,59,49,41,40,20,52,59,51,55,30,111,50,82,64,18780,19452,7825,3,81,200,49086,135,12,5,79,102,17,14,134,114,8,73,39,12,80,57,57,15,12,12,24,25,41,17,12,78,69,25,24,14,17,21,127,32,27,12,5,8,12,2,3,113,12,33,55,57,53,38,34,15,50,55,34,24,26,26,27,15,28,22,15,13,3,30,32,23,31,25,11,12,12,12,13,136,27,56,67,47,42,19,0.29,21,26,26,8,31,14,35,27,14,13,14,136,50,113,81,81,83,15,12,70,136,97,66
1,MULTIPOLYGON (((-107.48145900000009 37.0838550...,2,8,2190,802190,Archuleta County School District 50-JT,0,KG,12,G5420,NaN,E,4071194013,6825659,37.264828,-107.078993,3.597718,0.414240,2190,97000US0802190,"Archuleta County School District 50-JT, Colorado",9799,11558,2057,9127,9,33,45,9,0,278,5967,5591,1040,2259,966,607,1416,4255,2055,1040,1740,755,943,1652,2102,2098,806,422,47.6,4380,3126,1254,1143,111,8483,4380,4103,3406,974,8333,608,4704,3021,54301,64299,30405,1991,746,901,290200,11231,195,132,3181,7957,93,327,11523,10072,833,111,500,7,5056,4362,3641,721,15,15,0,25,130,54,470,4586,1064,1994,666,169,172,521,11365,2459,212,69,470,703,746,211,48,8906,49,2139,2164,2029,1288,280,132,120,282,3406,157,177,312,373,375,384,734,203,378,145,168,974,74,38,197,275,189,56,40,21,84,11438,989,2306,2225,2017,345,143,2.61,693,426,533,383,417,491,553,311,179,150,244,11472,1570,9629,5910,5910,5267,643,0,3719,11472,8798,2674,9799,217,91,156,17,36,51,18,19,131,188,142,209,283,302,196,279,258,214,209,301,245,238,217,161,218,127,106,1.0,350,277,220,217,51,77,350,356,280,203,281,186,482,336,5923,5655,2999,3,55,71,22822,274,83,124,406,432,56,155,223,400,316,80,196,11,357,376,438,285,19,19,38,31,67,49,159,366,223,432,203,96,81,163,220,295,139,49,123,144,197,152,46,336,35,275,256,292,233,112,74,61,106,280,65,76,115,125,111,112,161,69,110,57,67,203,65,32,99,116,94,43,35,23,53,225,331,595,305,123,143,72,0.20,169,135,154,129,124,122,167,104,81,67,84,229,241,197,312,312,352,199,19,261,229,468,370
2,MULTIPOLYGON (((-105.77069499999998 37.0418820...,3,8,6360,806360,Centennial School District R-1,0,PK,12,G5420,NaN,E,1726938152,5062661,37.136855,-105.447172,1.878730,0.175664,6360,97000US0806360,"Centennial School District R-1, Colorado",9931,1717,1354,317,12,0,0,0,7,27,886,831,166,394,70,97,236,467,453,166,286,60,119,260,203,283,213,127,47.4,719,417,302,299,3,1422,719,703,548,171,1253,334,799,120,21082,27281,17218,1962,372,471,85800,1689,19,9,1310,331,48,28,1703,1531,97,68,7,0,520,458,416,42,14,14,0,0,14,17,17,503,240,76,64,14,39,70,1689,345,15,0,133,101,89,7,0,1344,0,18,158,199,258,100,94,94,501,548,49,294,96,86,10,2,0,6,5,0,0,171,36,54,36,13,0,0,0,0,32,1717,454,741,394,453,201,92,2.39,337,126,27,114,46,25,26,11,0,0,7,1717,557,1346,625,625,537,88,0,721,1717,1406,311,9931,203,153,136,16,12,12,12,8,18,128,113,70,105,60,58,80,106,88,70,94,49,61,91,57,78,56,52,6.0,95,81,80,80,5,63,95,96,73,63,143,107,152,46,3674,24025,3799,9,124,103,4130,216,24,14,209,108,38,32,202,206,86,67,10,12,120,119,117,26,16,16,24,12,15,26,17,122,94,66,49,20,37,55,203,93,22,12,54,49,49,11,12,172,12,20,65,62,75,60,40,53,100,73,31,83,44,49,11,4,12,10,9,12,12,63,41,45,34,17,12,12,12,12,31,203,182,212,123,68,93,39,0.30,90,54,28,61,32,25,19,11,12,12,8,203,99,173,137,137,125,61,12,114,203,162,103

33fk-kb5q (1, 75) Census Combined Statistical Area in Colorado 2010

,the_geom,NAME10,NAMELSAD10,CSA,GEOCSA,AREALAND,AREAWATR,INTPTLAT,INTPTLON,POP2010,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_JUVENL,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_R_NOTOCC,V_FORSALE,V_S_NOTOCC,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-105.0550890000001 40.26179300...,"Denver-Aurora-Boulder, CO","Denver-Aurora-Boulder, CO CSA",216,8216,33824172800,260219033,39.811752,-104.985572,3090874,682087,22.07,2078277,67.24,139653,4.52,14887,0.48,106823,3.46,2962,0.1,4937,0.16,61248,1.98,1538953,49.79,1551921,50.21,309312,10.01,767614,24.83,438491,14.19,35.5,34.7,36.4,1213345,764997,584191,180806,448348,346094,2.51,156375,1056970,3.13,48430,24685,12463,1848,10161,213,23745,16088,267,7390,1302189,1213345,93.18,88844,6.82,783653,64.59,429692,35.41,31706,1648,18464,2992,17263,83,16688

p562-ke9a (178, 273) Census School Districts in Colorado 2011

,the_geom,OBJECTID,STATEFP,UNSDLEA,GEOID,NAME,LSAD,LOGRADE,HIGRADE,MTFCC,SDTYP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,Shape_Leng,Shape_Area,LOGRECNO,NAMEACS,SDUNI,GEOID_1,POP0711,HISPANIC,WHITE_NH,BLACK_NH,NTVAM_NH,ASIAN_NH,HAWPI_NH,OTHER_NH,TWOPLUS_NH,MALE,FEMALE,AGELESS10,AGELESS18,AGE18_24,AGE25_34,AGE35_44,AGE45_64,AGE65PLUS,MED_AGE,HOUSEHOLDS,FAMILYHH,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSING_UN,OCC_HU,VAC_HU,OWNED,RENTED,POP25PLUS,NOHSDIPL,HSGRAD_SC,BACHL_HGHR,MED_HH_INC,MED_FAM_IN,PER_CAP_IN,MED_YR_BLT,MED_C_RENT,MED_G_RENT,MED_HM_VAL,CITZ_BIRTH,CITZ_NAT,NOT_CITZ,BORN_IN_CO,BRN_OTH_ST,NTV_B_O_US,FOREIGN_B,POP_1P,SAME_HOUSE,SAME_CNTY,SAME_STATE,DIFF_STATE,FRM_ABROAD,WRKRS_16PL,CAR_ALL,CAR_ALONE,CAR_CARPOO,PUBLIC_TRN,PT_BUS,PT_OTHER,BIKE,WALK,TR_OTHER,WRK_HOME,W_16PL_NH,T_LESS_10,T_10_19,T_20_29,T_30_39,T_40_59,T_60_PL,POP_3PL,ENROLLED,PRESCHOOL,KNDRGRTN,GR_1_4,GR_5_8,GR_9_12,UNDERGRAD,GRAD_PROF,N_ENROLLED,BLT_2000_P,B1990_1999,B1980_1989,B1970_1979,B1960_1969,B1950_1959,B1940_1949,B1939_E,OWN_OCC_HU,V_L_50K,V50K_100K,V100K_150K,V150K_200K,V200K_250K,V250K_300K,V300K_400K,V400K_500K,V500K_750K,V750K_1M,V_1M_PLUS,RNT_OCC_HU,RNTL400,R400T599,R600T799,R800T999,R1000T1249,R1250T1499,R1500T1999,R2000PL,RNOCSHR,AGE_0_9,AGE_10_19,AGE_20_29,AGE_30_39,AGE_40_49,AGE_50_59,AGE_60_69,AGE_70_79,AGE_80_PL,PS_Uni,PS_BELOW,ADJ_PS_Uni,ADJ_PS_Pov,AVGHHSIZE,MLOGRECNO,MPOP0711,MHISPANIC,MWHITE_NH,MBLACK_NH,MNTVAM_NH,MASIAN_NH,MHAWPI_NH,MOTHER_NH,MTWOPLUS_N,MMALE,MFEMALE,MAGELESS10,MAGELESS18,MAGE18_24,MAGE25_34,MAGE35_44,MAGE45_64,MAGE65PLUS,MMED_AGE,MHOUSEHOLD,MFAMILYHH,MNONFAMHH,MHHLDRALON,MHHLDR_NAL,MHOUSING_U,MOCC_HU,MVAC_HU,MOWNED,MRENTED,MPOP25PLUS,MNOHSDIPL,MHSGRAD_SC,MBACHL_HGH,MMED_HH_IN,MMED_FAM_I,MPER_CAP_I,MMED_YR_BL,MMED_C_REN,MMED_G_REN,MMED_HM_VA,MCITZ_BIRT,MCITZ_NAT,MNOT_CITZ,MBORN_IN_C,MBRN_OTH_S,MNTV_B_O_U,MFOREIGN_B,MPOP_1P,MSAME_HOUS,MSAME_CNTY,MSAME_STAT,MDIFF_STAT,MFRM_ABROA,MWRKRS_16P,MCAR_ALL,MCAR_ALONE,MCAR_CARPO,MPUBLIC_TR,MPT_BUS,MPT_OTHER,MBIKE,MWALK,MTR_OTHER,MWRK_HOME,MW_16PL_NH,MT_LESS_10,MT_10_19,MT_20_29,MT_30_39,MT_40_59,MT_60_PL,MPOP_3PL,MENROLLED,MPRESCHOOL,MKNDRGRTN,MGR_1_4,MGR_5_8,MGR_9_12,MUNDERGRAD,MGRAD_PROF,MN_ENROLLE,MBLT_2000_,MB1990_199,MB1980_198,MB1970_197,MB1960_196,MB1950_195,MB1940_194,MB1939_E,MOWN_OCC_H,MV_L_50K,MV50K_100K,MV100K_150,MV150K_200,MV200K_250,MV250K_300,MV300K_400,MV400K_500,MV500K_750,MV750K_1M,MV_1M_PLUS,MRNT_OCC_H,MRNTL400,MR400T599,MR600T799,MR800T999,MR1000T124,MR1250T149,MR1500T199,MR2000PL,MRNOCSHR,MAGE_0_9,MAGE_10_19,MAGE_20_29,MAGE_30_39,MAGE_40_49,MAGE_50_59,MAGE_60_69,MAGE_70_79,MAGE_80_PL,MPS_Uni,MPS_BELOW,MADJ_PS_Un,MADJ_PS_Po,MAVGHHSIZE
0,MULTIPOLYGON (((-102.77984300000013 40.4636660...,1,8,4560,804560,Haxtun School District RE-2J,0,PK,12,G5420,NaN,E,967326498,20904,40.587662,-102.597930,2.492300,0.102908,10015,"Haxtun School District RE-2J, Colorado",4560,804560,1626,11,1562,0,7,5,10,0,31,849,777,201,409,82,138,175,456,366,45.3,676,445,231,209,22,807,676,131,527,149,1135,94,731,310,45000,59635,22611,1954,379,667,122000,1602,22,2,1151,445,6,24,1606,1494,40,27,42,3,706,612,496,116,0,0,0,10,33,2,49,657,240,169,75,76,75,22,1587,393,43,25,77,110,94,37,7,1194,65,60,26,133,55,107,37,324,527,66,157,107,103,51,24,10,3,3,0,3,149,19,30,36,22,15,5,0,0,22,201,240,104,149,233,252,137,189,121,1597,149,765,80,2.36,10015,151,11,149,92,10,5,16,92,17,87,84,42,61,134,39,38,61,54,2.6,57,51,46,44,13,57,57,49,53,37,97,228,78,109,3905,2964,2268,4,53,77,17374,178,19,3,137,64,8,19,146,133,27,18,34,5,101,92,74,42,92,92,184,11,19,4,22,100,50,47,27,28,48,15,145,61,21,15,27,28,30,25,7,110,36,23,18,33,24,32,16,56,53,161,38,30,34,19,19,10,4,5,92,4,37,184,17,94,22,15,6,92,92,17,42,46,136,35,46,44,32,8,8,152,68,122,97,0.14
1,MULTIPOLYGON (((-102.38752000000004 40.7638550...,2,8,4710,804710,Holyoke School District RE-1J,0,KG,12,G5420,NaN,E,1364165691,309318,40.563755,-102.253956,2.382610,0.145089,10020,"Holyoke School District RE-1J, Colorado",4710,804710,2833,784,1991,1,17,0,0,0,40,1328,1505,409,746,246,284,382,670,505,41.2,1147,771,376,357,19,1323,1147,176,804,343,1841,334,1236,271,43984,52083,19995,1956,408,580,118500,2388,162,283,1645,743,0,445,2785,2188,394,83,53,67,1310,1115,880,235,0,0,0,32,27,13,123,1187,541,303,200,94,30,19,2758,709,63,34,194,207,122,63,26,2049,39,70,64,308,126,150,150,416,804,121,238,207,105,55,39,7,5,27,0,0,343,36,128,72,20,6,7,0,21,53,409,409,309,245,475,303,301,207,175,2785,389,1328,133,2.43,10020,148,86,181,3,11,92,92,92,28,95,94,67,100,110,64,80,107,86,1.9,90,76,90,90,15,71,90,88,82,86,110,258,154,149,5591,5294,1937,7,21,48,24554,220,108,96,157,131,92,87,149,215,178,41,46,92,117,113,104,62,92,92,184,22,21,15,57,116,96,75,82,49,19,95,148,93,35,27,45,61,47,42,24,145,29,35,39,88,59,60,53,98,82,140,74,59,40,31,34,9,7,22,92,92,86,161,67,35,23,11,12,92,27,34,67,81,111,66,87,67,76,10,10,145,229,130,50,0.17
2,MULTIPOLYGON (((-102.40038600000013 40.7347710...,3,8,4860,804860,Julesburg School District RE-1,0,PK,12,G5420,NaN,E,636911328,36263,40.873236,-102.195708,1.740957,0.068039,10025,"Julesburg School District RE-1, Colorado",4860,804860,1558,122,1391,5,0,12,0,0,28,751,807,112,292,103,64,157,523,419,51.9,689,412,277,253,24,908,689,219,510,179,1163,174,803,186,34830,51786,22684,1948,290,482,86600,1524,1,33,754,762,8,34,1548,1262,124,103,55,4,657,530,459,71,8,8,0,0,59,0,60,597,288,145,62,34,54,14,1532,336,27,3,75,87,89,37,18,1196,16,40,59,157,39,113,132,352,510,80,232,98,33,28,7,17,6,3,6,0,179,75,37,31,13,4,0,0,5,14,112,207,93,120,201,291,214,185,135,1511,229,733,120,2.18,10025,101,56,110,6,92,12,92,92,29,80,62,32,57,99,22,47,71,59,3.2,66,55,50,42,18,77,66,56,59,48,80,105,84,136,4122,9183,2402,4,111,239,4848,138,4,30,95,94,8,30,101,96,64,56,27,7,81,68,66,24,10,10,184,92,28,92,18,77,56,38,30,18,24,13,102,56,16,4,26,31,28,22,15,87,94,20,29,46,17,26,38,71,59,133,41,27,17,17,8,18,6,5,6,92,48,99,22,94,92,6,92,92,7,18,32,49,99,38,49,54,39,8,9,114,105,87,45,0.16

3djr-p9q9 (7, 156) Census Congressional Districts in Colorado 2015

,the_geom,con_dist,hispanic,pop,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400T599,r600T799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,MULTIPOLYGON (((-109.06020399981469 38.2782380...,3,176885,723937,514574,5935,9219,4858,595,1038,10833,364145,359792,43573,45975,46523,47746,45517,45900,46056,45004,42921,45143,52320,54247,50297,40093,26500,20029,12806,13287,163263,66071,39.5,284880,183374,101506,81143,20363,359619,284880,74739,192383,92497,494603,52160,294283,148160,49013,60581,26980,1983,702,854,201800,679123,14683,30131,354915,317338,6870,44814,715623,590062,70644,25558,27108,2251,328487,278528,240578,37950,6950,6327,623,5577,14449,3644,19339,309148,70931,112375,50913,32384,21617,20928,698546,175893,11267,8972,36554,37346,38117,37874,5763,522653,140,3329,75013,67701,49716,62091,24523,25267,12000,192383,15241,20368,27348,32407,22834,17036,22276,11237,12228,4883,2928,92497,7629,12015,18461,17047,13410,8297,6901,1883,396,706561,111353,185736,160518,109895,34577,10488,2.48,53890,32072,31645,27086,23650,29925,34700,20950,11287,10726,8949,714305,97804,578376,366107,365608,335231,30377,499,212269,714305
1,MULTIPOLYGON (((-106.65295500037291 40.3646909...,2,77939,757740,631201,6173,2134,22558,808,1414,15513,381656,376084,37617,42972,45898,54294,74717,51351,49988,47179,50271,49381,56056,55782,48121,35463,22620,15025,10274,10731,153047,102451,37.3,298554,185352,113202,77224,35978,361568,298554,63014,199095,99459,502242,20130,217345,264767,69304,89400,37817,1985,1047,1149,326100,702141,24430,31169,270909,421365,9867,55599,750401,594266,75075,38792,36303,5965,399443,314672,282358,32314,13475,13096,379,13812,15002,4646,37836,361607,55404,123117,71587,47578,38457,25464,735528,218728,11392,8511,34832,36912,35561,75133,16387,516800,709,6116,65366,75914,59909,79782,30525,15144,5785,199095,8685,2900,7196,19521,27323,24102,37649,24053,30195,10142,4374,99459,3047,4080,10878,18067,19954,15031,16278,5859,1279,738366,87950,134918,151391,92107,15336,4419,2.47,37885,24088,24586,23274,21224,29381,40385,29404,19532,24259,24536,752718,60993,622886,434002,433569,407981,25588,433,188884,752718
2,MULTIPOLYGON (((-106.59903200032653 39.0362730...,5,114262,751270,542886,40432,3344,18438,2165,1322,28421,382471,368799,50006,49876,51782,51472,59743,57150,52952,46131,47488,48790,53954,48480,42522,32808,21975,15936,10992,9213,182448,80431,35.2,282631,192839,89792,73146,16646,313506,282631,30875,181460,101171,488391,33267,288728,166396,56622,69244,29033,1984,816,957,216700,701484,25766,24020,247159,431420,22905,49786,741823,579096,89514,17074,47486,8653,349413,307576,271494,36082,2611,2439,172,2160,12464,4040,20562,328851,45065,113864,83784,46034,22852,17252,722409,208026,11876,10886,39880,40788,40972,53532,10092,514383,476,5848,64840,53993,55549,55624,29754,21120,5608,181460,9293,7518,23893,40250,29313,20919,25721,10943,9637,2235,1066,101171,3284,10942,20716,17724,18067,13512,10558,2169,679,721397,85388,147078,179804,88897,28654,6004,2.56,40378,28336,28090,26391,25007,30255,36689,25041,15395,15091,11958,708379,86480,588430,386433,358190,328295,29895,28243,201997,708379

rntb-5cdp (1, 272) Census State in Colorado 2011

,the_geom,OBJECTID,REGION,DIVISION,STATEFP,STATENS,GEOID,STUSPS,NAME,LSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,Shape_Leng,Shape_Area,LOGRECNO,NAMEACS,GEOID_1,POP0711,HISPANIC,WHITE_NH,BLACK_NH,NTVAM_NH,ASIAN_NH,HAWPI_NH,OTHER_NH,TWOPLUS_NH,MALE,FEMALE,AGELESS10,AGELESS18,AGE18_24,AGE25_34,AGE35_44,AGE45_64,AGE65PLUS,MED_AGE,HOUSEHOLDS,FAMILYHH,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSING_UN,OCC_HU,VAC_HU,OWNED,RENTED,POP25PLUS,NOHSDIPL,HSGRAD_SC,BACHL_HGHR,MED_HH_INC,MED_FAM_IN,PER_CAP_IN,MED_YR_BLT,MED_C_RENT,MED_G_RENT,MED_HM_VAL,CITZ_BIRTH,CITZ_NAT,NOT_CITZ,BORN_IN_CO,BRN_OTH_ST,NTV_B_O_US,FOREIGN_B,POP_1P,SAME_HOUSE,SAME_CNTY,SAME_STATE,DIFF_STATE,FRM_ABROAD,WRKRS_16PL,CAR_ALL,CAR_ALONE,CAR_CARPOO,PUBLIC_TRN,PT_BUS,PT_OTHER,BIKE,WALK,TR_OTHER,WRK_HOME,W_16PL_NH,T_LESS_10,T_10_19,T_20_29,T_30_39,T_40_59,T_60_PL,POP_3PL,ENROLLED,PRESCHOOL,KNDRGRTN,GR_1_4,GR_5_8,GR_9_12,UNDERGRAD,GRAD_PROF,N_ENROLLED,BLT_2000_P,B1990_1999,B1980_1989,B1970_1979,B1960_1969,B1950_1959,B1940_1949,B1939_E,OWN_OCC_HU,V_L_50K,V50K_100K,V100K_150K,V150K_200K,V200K_250K,V250K_300K,V300K_400K,V400K_500K,V500K_750K,V750K_1M,V_1M_PLUS,RNT_OCC_HU,RNTL400,R400T599,R600T799,R800T999,R1000T1249,R1250T1499,R1500T1999,R2000PL,RNOCSHR,AGE_0_9,AGE_10_19,AGE_20_29,AGE_30_39,AGE_40_49,AGE_50_59,AGE_60_69,AGE_70_79,AGE_80_PL,PS_Uni,PS_BELOW,ADJ_PS_Uni,ADJ_PS_Pov,AVGHHSIZE,MLOGRECNO,MPOP0711,MHISPANIC,MWHITE_NH,MBLACK_NH,MNTVAM_NH,MASIAN_NH,MHAWPI_NH,MOTHER_NH,MTWOPLUS_N,MMALE,MFEMALE,MAGELESS10,MAGELESS18,MAGE18_24,MAGE25_34,MAGE35_44,MAGE45_64,MAGE65PLUS,MMED_AGE,MHOUSEHOLD,MFAMILYHH,MNONFAMHH,MHHLDRALON,MHHLDR_NAL,MHOUSING_U,MOCC_HU,MVAC_HU,MOWNED,MRENTED,MPOP25PLUS,MNOHSDIPL,MHSGRAD_SC,MBACHL_HGH,MMED_HH_IN,MMED_FAM_I,MPER_CAP_I,MMED_YR_BL,MMED_C_REN,MMED_G_REN,MMED_HM_VA,MCITZ_BIRT,MCITZ_NAT,MNOT_CITZ,MBORN_IN_C,MBRN_OTH_S,MNTV_B_O_U,MFOREIGN_B,MPOP_1P,MSAME_HOUS,MSAME_CNTY,MSAME_STAT,MDIFF_STAT,MFRM_ABROA,MWRKRS_16P,MCAR_ALL,MCAR_ALONE,MCAR_CARPO,MPUBLIC_TR,MPT_BUS,MPT_OTHER,MBIKE,MWALK,MTR_OTHER,MWRK_HOME,MW_16PL_NH,MT_LESS_10,MT_10_19,MT_20_29,MT_30_39,MT_40_59,MT_60_PL,MPOP_3PL,MENROLLED,MPRESCHOOL,MKNDRGRTN,MGR_1_4,MGR_5_8,MGR_9_12,MUNDERGRAD,MGRAD_PROF,MN_ENROLLE,MBLT_2000_,MB1990_199,MB1980_198,MB1970_197,MB1960_196,MB1950_195,MB1940_194,MB1939_E,MOWN_OCC_H,MV_L_50K,MV50K_100K,MV100K_150,MV150K_200,MV200K_250,MV250K_300,MV300K_400,MV400K_500,MV500K_750,MV750K_1M,MV_1M_PLUS,MRNT_OCC_H,MRNTL400,MR400T599,MR600T799,MR800T999,MR1000T124,MR1250T149,MR1500T199,MR2000PL,MRNOCSHR,MAGE_0_9,MAGE_10_19,MAGE_20_29,MAGE_30_39,MAGE_40_49,MAGE_50_59,MAGE_60_69,MAGE_70_79,MAGE_80_PL,MPS_Uni,MPS_BELOW,MADJ_PS_Un,MADJ_PS_Po,MAVGHHSIZE
0,MULTIPOLYGON (((-109.04348800000007 37.4846840...,1,4,8,8,1779779,8,CO,Colorado,0,G4000,A,268432070430,1170100349,38.993878,-105.508316,22.028148,28.039507,1,Colorado,8,4966061,1011545,3491019,186206,28240,132102,5204,8423,103322,2489370,2476691,685825,1212540,488096,715257,703322,1311970,534876,35.9,1941193,1246419,694774,549281,145493,2197823,1941193,256630,1295906,645287,3265425,336899,1743400,1185126,57685,71721,30816,1980,771,883,236700,4482846,164576,318639,2098058,2317809,66979,483215,4899398,3957989,478233,240279,190304,32593,2455116,2083576,1831614,251962,80390,69928,10462,30647,75173,28950,156380,2298736,333610,692273,506593,372975,249863,143422,4763572,1321417,87232,67921,270761,258592,268008,297777,71126,3442155,389698,377193,329848,443164,215887,183673,66212,192148,1295906,60824,65290,131649,227458,221599,148454,191939,95543,94625,28997,29528,645287,37388,72088,141399,132162,106098,61943,50826,18427,24956,685825,665693,714199,702819,721989,682440,429843,222179,141074,4852160,607727,2692137,254473,2.5,1,0,0,1075,1671,1026,1411,454,1106,2386,1106,1106,2764,3951,3914,1163,4590,3880,3670,0.1,5005,5396,4453,4626,2576,570,5005,4872,7722,4896,1083,4253,8546,6676,312,411,181,1,4,4,620,6398,3350,5429,9873,9489,2119,5910,1659,11625,9418,5182,4782,2026,7075,7915,7651,3814,2274,2001,729,1455,2135,1262,2914,7432,4122,6223,5175,4306,4145,3025,2254,5112,1939,1788,3071,2772,2087,3542,2019,5164,3719,3130,3821,3918,2437,2370,1446,2257,7722,1696,1477,2475,3265,2762,2168,2862,1876,1873,1038,1075,4896,1353,1910,2897,2522,2446,1822,1688,1114,1155,2764,2977,3887,3407,3256,2545,3555,66,63,1351,16034,5569,3752,0.01

6gtx-i289 (209, 277) Census County Subdivisions in Colorado 2011

,the_geom,OBJECTID,STATEFP,COUNTYFP,COUSUBFP,COUSUBNS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CNECTAFP,NECTAFP,NCTADVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,Shape_Leng,Shape_Area,LOGRECNO,NAMEACS,COUSUB,GEOID_1,POP0711,HISPANIC,WHITE_NH,BLACK_NH,NTVAM_NH,ASIAN_NH,HAWPI_NH,OTHER_NH,TWOPLUS_NH,MALE,FEMALE,AGELESS10,AGELESS18,AGE18_24,AGE25_34,AGE35_44,AGE45_64,AGE65PLUS,MED_AGE,HOUSEHOLDS,FAMILYHH,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSING_UN,OCC_HU,VAC_HU,OWNED,RENTED,POP25PLUS,NOHSDIPL,HSGRAD_SC,BACHL_HGHR,MED_HH_INC,MED_FAM_IN,PER_CAP_IN,MED_YR_BLT,MED_C_RENT,MED_G_RENT,MED_HM_VAL,CITZ_BIRTH,CITZ_NAT,NOT_CITZ,BORN_IN_CO,BRN_OTH_ST,NTV_B_O_US,FOREIGN_B,POP_1P,SAME_HOUSE,SAME_CNTY,SAME_STATE,DIFF_STATE,FRM_ABROAD,WRKRS_16PL,CAR_ALL,CAR_ALONE,CAR_CARPOO,PUBLIC_TRN,PT_BUS,PT_OTHER,BIKE,WALK,TR_OTHER,WRK_HOME,W_16PL_NH,T_LESS_10,T_10_19,T_20_29,T_30_39,T_40_59,T_60_PL,POP_3PL,ENROLLED,PRESCHOOL,KNDRGRTN,GR_1_4,GR_5_8,GR_9_12,UNDERGRAD,GRAD_PROF,N_ENROLLED,BLT_2000_P,B1990_1999,B1980_1989,B1970_1979,B1960_1969,B1950_1959,B1940_1949,B1939_E,OWN_OCC_HU,V_L_50K,V50K_100K,V100K_150K,V150K_200K,V200K_250K,V250K_300K,V300K_400K,V400K_500K,V500K_750K,V750K_1M,V_1M_PLUS,RNT_OCC_HU,RNTL400,R400T599,R600T799,R800T999,R1000T1249,R1250T1499,R1500T1999,R2000PL,RNOCSHR,AGE_0_9,AGE_10_19,AGE_20_29,AGE_30_39,AGE_40_49,AGE_50_59,AGE_60_69,AGE_70_79,AGE_80_PL,PS_Uni,PS_BELOW,ADJ_PS_Uni,ADJ_PS_Pov,AVGHHSIZE,MLOGRECNO,MPOP0711,MHISPANIC,MWHITE_NH,MBLACK_NH,MNTVAM_NH,MASIAN_NH,MHAWPI_NH,MOTHER_NH,MTWOPLUS_N,MMALE,MFEMALE,MAGELESS10,MAGELESS18,MAGE18_24,MAGE25_34,MAGE35_44,MAGE45_64,MAGE65PLUS,MMED_AGE,MHOUSEHOLD,MFAMILYHH,MNONFAMHH,MHHLDRALON,MHHLDR_NAL,MHOUSING_U,MOCC_HU,MVAC_HU,MOWNED,MRENTED,MPOP25PLUS,MNOHSDIPL,MHSGRAD_SC,MBACHL_HGH,MMED_HH_IN,MMED_FAM_I,MPER_CAP_I,MMED_YR_BL,MMED_C_REN,MMED_G_REN,MMED_HM_VA,MCITZ_BIRT,MCITZ_NAT,MNOT_CITZ,MBORN_IN_C,MBRN_OTH_S,MNTV_B_O_U,MFOREIGN_B,MPOP_1P,MSAME_HOUS,MSAME_CNTY,MSAME_STAT,MDIFF_STAT,MFRM_ABROA,MWRKRS_16P,MCAR_ALL,MCAR_ALONE,MCAR_CARPO,MPUBLIC_TR,MPT_BUS,MPT_OTHER,MBIKE,MWALK,MTR_OTHER,MWRK_HOME,MW_16PL_NH,MT_LESS_10,MT_10_19,MT_20_29,MT_30_39,MT_40_59,MT_60_PL,MPOP_3PL,MENROLLED,MPRESCHOOL,MKNDRGRTN,MGR_1_4,MGR_5_8,MGR_9_12,MUNDERGRAD,MGRAD_PROF,MN_ENROLLE,MBLT_2000_,MB1990_199,MB1980_198,MB1970_197,MB1960_196,MB1950_195,MB1940_194,MB1939_E,MOWN_OCC_H,MV_L_50K,MV50K_100K,MV100K_150,MV150K_200,MV200K_250,MV250K_300,MV300K_400,MV400K_500,MV500K_750,MV750K_1M,MV_1M_PLUS,MRNT_OCC_H,MRNTL400,MR400T599,MR600T799,MR800T999,MR1000T124,MR1250T149,MR1500T199,MR2000PL,MRNOCSHR,MAGE_0_9,MAGE_10_19,MAGE_20_29,MAGE_30_39,MAGE_40_49,MAGE_50_59,MAGE_60_69,MAGE_70_79,MAGE_80_PL,MPS_Uni,MPS_BELOW,MADJ_PS_Un,MADJ_PS_Po,MAVGHHSIZE
0,MULTIPOLYGON (((-107.14355700000009 38.8143300...,1,8,51,93363,1935570,805193363,Somerset,Somerset CCD,22,Z5,G4040,NaN,NaN,NaN,S,1743885904,2411558,38.948748,-107.322788,2.194422,0.181487,155,"Somerset CCD, Gunnison County, Colorado",93363,805193363,678,0,658,0,18,2,0,0,0,313,365,61,112,31,75,81,269,110,48.5,287,202,85,61,24,544,287,257,273,14,535,58,235,242,65586,74773,42402,1980,1047,1594,338100,675,3,0,221,454,0,3,641,616,6,19,0,0,336,303,229,74,0,0,0,0,3,14,16,320,5,70,61,46,53,85,636,104,0,1,18,21,34,28,2,532,84,129,59,161,31,0,8,72,273,51,38,0,2,5,15,67,53,42,0,0,14,3,0,0,1,1,0,8,0,1,61,77,55,27,157,85,146,42,28,659,31,425,18,2.30,155,177,92,175,92,26,5,92,92,92,109,106,106,116,209,58,106,134,196,10.3,79,75,52,45,19,102,79,88,83,16,153,323,101,205,33432,19353,25081,10,466,1138,88838,218,9,92,103,126,92,9,155,157,13,37,92,92,116,114,85,54,92,92,184,92,4,21,20,113,5,59,43,108,36,60,153,71,92,3,25,31,40,38,3,151,58,56,48,77,34,92,15,63,83,231,192,130,92,6,18,42,52,25,92,92,16,225,184,184,10,4,92,13,92,4,106,109,192,94,71,40,123,15,15,179,40,219,185,0.36
1,MULTIPOLYGON (((-107.00062200000012 38.3237670...,2,8,51,93211,1935562,805193211,Sapinero,Sapinero CCD,22,Z5,G4040,NaN,NaN,NaN,S,2518426222,39245744,38.405241,-107.288269,2.325349,0.263772,154,"Sapinero CCD, Gunnison County, Colorado",93211,805193211,492,1,491,0,0,0,0,0,0,224,268,9,26,29,116,30,177,114,54.8,200,165,35,22,13,740,200,540,161,39,437,1,258,178,44500,70625,30503,1986,0,0,346600,467,25,0,135,332,0,25,492,428,0,0,64,0,277,104,67,37,13,13,0,0,98,0,62,215,98,6,53,0,48,10,488,21,0,0,5,0,16,0,0,467,125,156,200,109,30,33,0,87,161,0,9,5,11,22,20,29,41,24,0,0,39,0,39,0,0,0,0,0,0,0,9,21,141,12,18,88,147,51,5,492,50,323,13,2.31,154,181,11,184,92,92,92,92,92,92,81,116,131,185,209,164,24,149,212,10.2,83,80,29,26,15,122,83,133,60,58,169,356,83,213,63098,58428,11025,4,0,0,101733,224,30,92,81,170,92,30,181,148,92,92,71,92,156,89,52,51,30,30,184,92,133,92,50,155,137,92,73,130,43,94,180,21,92,92,8,92,19,92,92,180,58,87,96,82,32,40,92,65,60,260,185,92,94,22,23,26,34,26,92,92,58,243,170,184,92,92,92,92,92,92,131,161,212,131,132,54,143,12,14,181,59,274,244,0.33
2,"MULTIPOLYGON (((-106.5182840000001 38.951517, ...",3,8,51,91672,1935481,805191672,Gunnison,Gunnison CCD,22,Z5,G4040,NaN,NaN,NaN,S,3281951152,10725458,38.673896,-106.709626,3.883746,0.340803,153,"Gunnison CCD, Gunnison County, Colorado",91672,805191672,10430,1122,8970,80,58,23,0,23,154,5845,4585,1161,2029,2621,1416,1179,2291,894,28.7,4211,2085,2126,1458,668,6002,4211,1791,2194,2017,5780,615,2706,2459,45544,67025,25079,1979,710,830,290600,9816,62,552,4319,5388,109,614,10330,6666,1958,822,692,192,5851,3860,3140,720,64,64,0,630,839,97,361,5490,2990,1497,407,352,193,51,10159,3781,234,169,359,175,457,2273,114,6378,826,1248,792,1435,512,257,202,730,2194,238,95,51,212,229,335,504,246,210,48,26,2017,63,459,335,629,268,143,24,0,96,1161,1836,2378,1340,1033,1365,757,314,246,9303,1590,4806,233,2.21,153,413,66,401,44,51,36,92,36,78,266,288,214,301,384,192,222,204,166,1.5,349,249,280,219,186,189,349,270,225,364,357,234,398,333,5793,6108,2452,2,29,54,22792,417,53,212,495,516,63,192,403,553,507,215,312,143,399,400,378,214,59,59,184,218,263,84,116,410,452,282,134,146,90,44,425,400,100,83,142,70,148,293,99,522,191,229,187,258,158,97,120,212,225,151,61,41,95,101,95,133,113,83,40,22,364,219,167,151,180,135,101,30,92,67,214,350,296,216,174,152,144,13,13,503,593,333,112,0.13

gvnt-p2w8 (63, 102) Census Counties SF3 in Colorado 2000

,the_geom,OBJECTID,STATEFP00,COUNTYFP00,CNTYIDFP00,NAME00,NAMELSAD00,LSAD00,CLASSFP00,MTFCC00,UR00,FUNCSTAT00,ALAND00,AWATER00,INTPTLAT00,INTPTLON00,Shape_Leng,Shape_Area,STATE,COUNTY,GEOID,NAME10,POP_SF3,HISPANIC,PCTHISP,WHITE_NH,PCTWHITE,BLACK_NH,PCTBLACK,NTV_AM_NH,PCTNTVAM,ASIAN_NH,PCTASIAN,HAWPI_NH,PCTHAW,OTHER_NH,PCTOTHER,TWOPLUS_NH,PCT_TWOP,MALE,PCT_MALE,FEMALE,PCT_FEMALE,AGELESS10,PCT_L10,AGELESS18,PCT_L18,AGE65PLUS,PCT_65PL,HHLDS,FAMHH,MARCOUPFAM,OTH_FAM,MHHLDR_N_W,FHHLDR_N_H,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSINGU,URBANHU,PCT_URBHU,RURALHU,PCT_RURHU,OCCHU,PCTOCC,VACHU,PCTVAC,OWN,PCTOWN,RENT,PCTRENT,TTLPOP25PL,NO_HS_DIPL,PCT_NODIPL,HSGRAD_PL,PCT_HSPLUS,BACHL_HGHR,PCT_BACHPL,MEDHHINC,MEDFAMINC,PERCAPINC,MEDYRBLT,MEDCRENT,MEDGRENT,MEDVAL,POP3PLUS,ENROLLED,PRESCHOOL,KINDRGRTN,GRADE_1_4,GRADE_5_8,GRADE_9_12,UNDERGRAD,GRADSCH,NOTINSCH,NATIVE,PCTNATIVE,FOREIGN,PCTFOREIGN,PVRTY_UNI,IN_POVERTY,PCT_PVRTY
0,MULTIPOLYGON (((-105.16615000000012 39.9140470...,1,8,13,8013,Boulder,Boulder County,6,H1,G4020,M,A,1908733293,36715760,40.086632,-105.359073,2.141113,0.205450,8,13,8013,Boulder County,291288,30368,10.43,243414,83.56,2163,0.74,1348,0.46,8927,3.06,200,0.07,347,0.12,4521,1.55,146894,50.43,144394,49.57,36562,12.55,66563,22.85,22739,7.81,114793,69546,57160,12386,3764,8622,15180,30067,84726,119900,107291,89.48,12609,10.52,114680,95.65,5220,4.35,74249,64.74,40431,35.26,186126,13404,7.20,172722,92.80,97499,52.38,55861,70572,28976,1977,764,825,231000,280710,90124,5709,3983,15374,15154,14247,27255,8402,190586,264009,90.64,27279,9.36,282582,26818,9.49
1,MULTIPOLYGON (((-105.05672000000003 40.3492810...,2,8,69,8069,Larimer,Larimer County,6,H1,G4020,M,A,6723614521,98295250,40.663091,-105.482131,3.899742,0.726515,8,69,8069,Larimer County,251494,20631,8.20,220432,87.65,1534,0.61,1155,0.46,3523,1.40,85,0.03,226,0.09,3908,1.55,125668,49.97,125826,50.03,31279,12.44,59416,23.63,24032,9.56,97128,63682,53388,10294,3411,6883,10755,22691,74437,105392,88049,83.54,17343,16.46,97164,92.19,8228,7.81,65744,67.66,31420,32.34,156426,12013,7.68,144413,92.32,61828,39.53,48655,58866,23689,1979,622,678,168200,242637,80102,4384,2968,14044,13919,13403,25744,5640,162535,240785,95.74,10709,4.26,244843,22600,9.23
2,MULTIPOLYGON (((-104.14317900000013 37.7583300...,3,8,71,8071,Las Animas,Las Animas County,6,H1,G4020,M,A,12361162110,6929979,37.318831,-104.044110,5.537916,1.257227,8,71,8071,Las Animas County,15207,6348,41.74,8385,55.14,17,0.11,148,0.97,60,0.39,25,0.16,32,0.21,192,1.26,7395,48.63,7812,51.37,1882,12.38,3686,24.24,2865,18.84,6155,4085,3083,1002,294,708,237,1833,4322,7629,4242,55.60,3387,44.40,6173,80.91,1456,19.09,4344,70.37,1829,29.63,10279,2379,23.14,7900,76.86,1668,16.23,28273,34072,16829,1953,316,397,86300,14688,3954,253,181,890,889,856,836,49,10734,14850,97.65,357,2.35,14873,2573,17.30

yqfw-dg5f (1249, 157) Census Tracts in Colorado 2012

,pop,the_geom,geoname,geonum,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,3435,"MULTIPOLYGON (((-106.632446 40.312925, -106.63...",1.00,108049000100,454,2894,0,1,65,0,0,21,1704,1731,310,158,285,218,205,307,136,309,214,198,426,276,194,75,43,34,34,13,876,300,36.7,1124,723,401,360,41,1954,1124,830,846,278,2259,229,1451,579,59683.0,66571.0,25670.0,1979.0,774.0,947.0,236900.0,3285,69,81,1592,1689,4,150,3408,2779,388,137,104,0,1882,1545,1186,359,6,6,0,33,103,0,195,1687,482,274,53,286,385,207,3290,731,82,32,109,213,192,103,0,2559,0,252,406,285,431,162,151,69,198,846,84,24,41,156,160,152,117,13,61,13,25,278,3,44,23,60,71,7,12,0,58,3418,293,559,872,187,39,5,3.01,116,73,101,144,136,168,190,91,64,25,16,3422,214,2643,2018,2018,1899,119,0,625,3422
1,3575,"MULTIPOLYGON (((-104.680949 37.496021, -104.68...",9609.00,108055960900,540,2808,5,38,4,0,14,166,1745,1830,110,86,132,108,72,65,47,76,180,219,293,386,621,299,359,208,52,262,411,97,60.1,1906,1080,826,723,103,3489,1906,1583,1571,335,3067,308,1721,1038,39469.0,59697.0,32002.0,1985.0,546.0,780.0,221800.0,3392,84,99,1250,2132,10,183,3556,3057,144,158,185,12,1397,1040,832,208,20,20,0,15,90,24,208,1189,287,274,170,134,147,177,3476,390,11,0,89,97,71,72,50,3086,10,410,1000,661,469,198,160,37,544,1571,91,185,197,192,276,108,145,72,120,38,147,335,35,18,88,36,54,0,3,0,101,3431,557,926,377,1070,124,88,1.80,479,199,292,148,108,162,267,119,38,21,73,3449,720,3240,1544,1544,1425,119,0,1696,3449
2,2783,MULTIPOLYGON (((-106.190553863626 40.997607017...,24.02,108069002402,12,2607,124,0,0,0,0,40,1548,1235,35,123,73,150,23,75,52,131,159,193,319,383,342,281,264,108,60,12,314,90,55.6,1350,921,429,420,9,2351,1350,1001,1183,167,2379,76,1255,1048,62090.0,81583.0,42027.0,1985.0,685.0,735.0,270600.0,2757,26,0,789,1957,11,26,2769,2535,80,88,66,0,1274,1036,890,146,0,0,0,15,73,0,150,1124,97,78,225,202,295,227,2756,457,52,0,82,48,108,126,41,2299,0,362,679,290,437,115,202,96,170,1183,83,65,6,188,201,118,148,144,125,57,48,167,13,17,28,38,9,0,0,0,62,2727,98,450,314,725,0,42,1.95,161,137,141,98,82,159,152,213,25,114,68,2783,239,2552,1479,1479,1371,108,0,1073,2783

x5e5-npqm (1, 78) Census State in Colorado 2010

,the_geom,REGION10,DIVISION10,STATEFP10,STUSPS10,NAME10,STATE,AREALAND,AREAWATR,INTPTLAT,INTPTLON,POP2010,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_JUVENL,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_R_NOTOCC,V_FORSALE,V_S_NOTOCC,V_SEASONAL,V_MIGRANT,V_OTHER,GEOCOMP
0,MULTIPOLYGON (((-109.04348800000011 37.4846840...,4,8,8,CO,Colorado,8,268431246000,1170101260,38.993575,-105.507774,5029196,1038687,20.65,3520793,70.01,188778,3.75,31244,0.62,135564,2.7,5661,0.11,7622,0.15,100847,2.01,2520662,50.12,2508534,49.88,549625,10.93,1225609,24.37,692563,13.77,36.1,35.1,37.1,1972868,1261527,971397,290130,711341,550794,2.49,248578,1724290,3.08,115878,61591,40568,2645,18079,299,54287,29952,10945,13390,2212898,1972868,89.15,240030,10.85,1293100,65.54,679768,34.46,57644,3058,32673,5418,101965,524,38748,0

8vnm-57r6 (1062, 73) Census Tracts SF1 in Colorado 2000

,the_geom,NAME00,ALAND00,AWATER00,STATE,COUNTY,TRACT,GEOIDTR,NAMESF1,POP2000,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_RS_N_OCC,V_FORSALE,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-107.12846200000011 38.8178610...,9639.0,-2147483648,41657300,8,51,963900,8051963900,Census Tract 9639,862,31,3.60,794,92.11,1,0.12,8,0.93,6,0.70,1,0.12,4,0.46,17,1.97,462,53.60,400,46.40,100,11.60,170,19.72,97,11.25,43.0,41.9,43.3,358,242,217,25,29,87,2.35,37,321,2.81,20,8,0,0,8,12,0,0,12,1084,358,33.03,726,66.97,266,74.30,92,25.70,12,7,8,682,0,17
1,MULTIPOLYGON (((-106.9526920000001 38.55070300...,9637.0,14476213,0,8,51,963700,8051963700,Census Tract 9637,5686,385,6.77,5117,89.99,35,0.62,31,0.55,26,0.46,1,0.02,4,0.07,87,1.53,3090,54.34,2596,45.66,438,7.70,859,15.11,472,8.30,24.0,23.6,24.8,2218,976,739,237,511,731,2.16,580,1638,2.81,896,31,30,1,0,865,826,0,39,2418,2218,91.73,200,8.27,975,43.96,1243,56.04,77,16,18,60,1,28
2,MULTIPOLYGON (((-106.5182840000001 38.95151700...,9636.0,-2147483648,10739992,8,51,963600,8051963600,Census Tract 9636,3871,189,4.88,3595,92.87,15,0.39,16,0.41,25,0.65,1,0.03,4,0.10,26,0.67,2025,52.31,1846,47.69,342,8.83,925,23.90,436,11.26,38.0,37.4,38.4,1535,1067,962,105,140,328,2.48,171,1364,2.92,58,0,0,0,0,58,52,0,6,2736,1535,56.10,1201,43.90,1161,75.64,374,24.36,19,13,30,1104,1,34

nbfg-y9mh (3278, 73) Census Block Groups SF1 in Colorado 2000

,the_geom,ALAND00,AWATER00,STATE,COUNTY,TRACT,BLKGRP,GEOIDBG,NAMESF1,POP2000,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_RS_N_OCC,V_FORSALE,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-105.4825980000001 38.26223100...,173321110,1426380,8,27,980100,3,80279801003,Block Group 3,801,27,3.37,744,92.88,2,0.25,7,0.87,1,0.12,0,0.00,0,0.00,20,2.50,398,49.69,403,50.31,125,15.61,162,20.22,79,9.86,45.7,45.9,45.5,354,233,205,28,12,109,2.24,24,330,2.77,7,7,7,0,0,0,0,0,0,600,354,59.00,246,41.00,246,69.49,108,30.51,9,2,10,210,0,15
1,MULTIPOLYGON (((-104.8097950000001 38.74482900...,343939060,143519,8,41,4400,9,80410044009,Block Group 9,10728,1644,15.32,6210,57.89,2065,19.25,153,1.43,227,2.12,79,0.74,30,0.28,320,2.98,7135,66.51,3593,33.49,9,0.08,2910,27.13,2241,20.89,22.2,22.2,21.9,1684,1626,1439,187,5,53,3.70,95,1589,3.74,4493,0,0,0,0,4493,0,4493,0,1850,1684,91.03,166,8.97,21,1.25,1663,98.75,132,9,0,3,0,22
2,MULTIPOLYGON (((-105.22298400000011 38.4475420...,1820075,0,8,43,978400,2,80439784002,Block Group 2,855,86,10.06,716,83.74,2,0.23,15,1.75,11,1.29,0,0.00,0,0.00,25,2.92,419,49.01,436,50.99,144,16.84,211,24.68,115,13.45,38.7,37.3,39.9,398,212,158,54,24,162,2.15,38,360,2.96,0,0,0,0,0,0,0,0,0,443,398,89.84,45,10.16,237,59.55,161,40.45,19,0,1,9,0,16

6fg8-f8c5 (7, 156) Census Congressional Districts in Colorado 2016

,pop,hispanic,con_dist,the_geom,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400T599,r600T799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,786253,219694,1,MULTIPOLYGON (((-105.14597299975412 39.5774160...,452415,64416,3637,25857,330,1733,18171,393201,393052,51305,47848,41936,38629,52053,83684,80158,63177,56274,48164,47423,46554,41268,30946,20191,14278,10207,12158,163424,68347,34.8,330841,168312,162529,124321,38208,351422,330841,20581,173044,157797,554482,68881,233562,252039,58507,75209,37392,1969,947,1044,292300,672298,39865,74090,330171,331800,10327,113955,775768,614650,71383,51751,32989,4995,419676,333818,300155,33663,26845,21214,5631,8491,17192,4245,29085,390591,36289,111864,95245,80244,44711,22238,754184,182443,13411,9634,37648,33124,29876,41869,16881,571741,3267,8414,43965,27991,32205,55139,40337,54238,23146,173044,4678,5993,13690,21183,23323,20869,30859,19749,19973,5959,3944,157797,11081,7913,23564,29700,28198,20247,22837,7358,1946,773410,118413,190517,161897,85879,36817,8410,2.33,53951,30788,29608,28257,25860,31782,39814,27561,17915,20970,24335,779565,73850,637664,452351,451904,427184,24720,447,185313,779565
1,771980,80545,2,MULTIPOLYGON (((-106.65295500037291 40.3646909...,640659,6275,2348,23910,747,1738,15758,389221,382759,37735,43280,46116,55045,75796,53085,51091,49000,49939,49923,54768,56456,49387,38995,23636,16063,10718,10947,153999,103973,37.4,302634,188350,114284,77195,37089,365287,302634,62653,201922,100712,514008,19498,220609,273901,72006,91982,38922,1985,1097,1200,347100,714637,25386,31957,276106,428270,10261,57343,764925,604416,76965,39822,37304,6418,409150,321188,289055,32133,13287,12790,497,14085,15748,4837,40005,369145,55715,124216,75094,48630,40232,25258,749891,219041,11433,8523,35115,36916,35733,74536,16785,530850,2879,8665,65528,76345,60351,78626,30525,15073,5702,201922,8282,3042,6128,16341,24588,23489,40564,26346,32839,11628,5225,100712,2972,3997,9956,16356,19181,16372,18856,6469,1632,751506,85106,131428,152059,98479,14023,5051,2.48,36231,24004,23723,22940,21257,29157,41965,30186,20814,25338,27019,767006,63238,636380,441434,440992,417836,23156,442,194946,767006
2,727398,177350,3,MULTIPOLYGON (((-109.06020399981469 38.2782380...,517155,5856,9802,4745,640,979,10871,365564,361834,42342,45908,45975,47571,46905,45598,46364,44994,42454,44367,51311,53733,52045,42668,28145,20297,13141,13580,161607,67094,39.8,285590,183052,102538,81772,20766,361301,285590,75711,191971,93619,498697,51454,298933,148310,49977,62171,27431,1983,710,865,207500,682665,14628,30105,359731,316001,6933,44733,719318,594193,69514,27040,26150,2421,331975,280865,244632,36233,6747,6384,363,5222,14622,3776,20743,311232,70996,113050,51372,32150,22206,21458,702639,173974,10342,8767,36961,36715,37620,37921,5648,528665,1037,4405,74876,67749,49897,62683,24655,24796,12051,191971,14970,19590,26646,31389,22602,17305,23024,12122,12904,5339,2545,93619,7827,11287,18725,16621,14338,8489,7077,2185,464,710613,112933,186350,159110,115145,34452,10868,2.49,53350,31926,31221,26346,23183,30165,35349,21913,11809,11147,9181,718419,99259,583696,367026,366691,339386,27305,335,216670,718419

hxnu-kp2f (209, 76) Census County Subdivisions in Colorado 2010

,the_geom,NAME10,NAMELSAD10,COUNTY,COUSUB,GEOCOUSUB,AREALAND,AREAWATR,INTPTLAT,INTPTLON,POP2010,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_JUVENL,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_R_NOTOCC,V_FORSALE,V_S_NOTOCC,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-105.0551150000001 40.27637000...,Berthoud,Berthoud CCD,69,90285,890285,150759368,11121928,40.307584,-105.155254,11509,803,6.98,10384,90.23,26,0.23,53,0.46,97,0.84,12,0.10,13,0.11,121,1.05,5700,49.53,5809,50.47,1420,12.34,2715,23.59,1212,10.53,45.1,44.9,45.3,4349,3285,2818,467,1064,859,2.59,374,3975,2.98,226,69,0,0,69,0,157,0,0,157,4571,4349,95.14,222,4.86,3658,84.11,691,15.89,36,2,65,10,48,0,61
1,MULTIPOLYGON (((-105.5040840000001 40.26037400...,Estes Park,Estes Park CCD,69,91235,891235,1055603530,4070513,40.464535,-105.627735,11309,1049,9.28,9928,87.79,43,0.38,30,0.27,106,0.94,5,0.04,5,0.04,143,1.26,5474,48.40,5835,51.60,2793,24.70,1768,15.63,914,8.08,52.4,51.7,53.0,5251,3352,2988,364,1899,1628,2.10,378,4873,2.58,296,37,0,0,37,0,259,0,0,259,8741,5251,60.07,3490,39.93,3812,72.60,1439,27.40,284,24,177,18,2854,11,122
2,MULTIPOLYGON (((-105.0728660000001 40.65418100...,Fort Collins,Fort Collins CCD,69,91330,891330,282546225,24057705,40.580938,-105.089290,157849,17724,11.23,130153,82.45,1586,1.00,683,0.43,4150,2.63,112,0.07,229,0.15,3212,2.03,79022,50.06,78827,49.94,14888,9.43,31160,19.74,17557,11.12,30.4,29.7,31.3,63703,34911,27073,7838,28792,17962,2.37,13306,50397,2.96,7122,1445,867,56,522,0,5677,5303,0,374,66727,63703,95.47,3024,4.53,36165,56.77,27538,43.23,1298,105,564,144,418,0,495

6hee-tnp6 (3532, 157) Census Block Groups in Colorado 2015

,pop,the_geom,geonum,geoname,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,654,"MULTIPOLYGON (((-108.62594 39.91802, -108.6245...",1081039511002,2,89,522,13,28,0,0,0,2,323,331,24,44,4,24,90,41,103,22,25,64,31,62,41,5,38,25,0,11,82,104,34.0,185,114,71,65,6,316,185,131,150,35,468,0,270,198,83375.0,NaN,24343.0,1981.0,NaN,NaN,318600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,42,58,34,77,0,0,0,76,150,0,0,10,15,7,35,43,0,23,6,11,35,0,22,0,0,0,0,0,0,13,654,191,216,NaN,NaN,NaN,NaN,2.15,29,0,38,0,0,22,42,43,11,0,0,NaN,NaN,582,407,407,349,58,0,175,NaN
1,196,"MULTIPOLYGON (((-106.87331 38.671502, -106.870...",1080519636001,1,5,125,0,0,0,0,0,66,160,36,0,0,70,0,0,0,0,0,0,29,51,0,31,11,0,0,4,0,70,0,49.0,84,71,13,13,0,580,84,496,32,52,126,0,62,64,NaN,NaN,21032.0,1978.0,NaN,NaN,453300.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,48,63,161,99,121,0,20,68,32,8,0,0,0,0,0,0,15,9,0,0,52,0,0,0,0,0,0,0,0,52,196,66,82,NaN,NaN,NaN,NaN,2.33,40,0,4,0,9,0,31,0,0,0,0,NaN,NaN,126,98,98,98,0,0,28,NaN
2,1038,"MULTIPOLYGON (((-104.922289 39.769236, -104.91...",1080310041024,4,9,186,771,0,15,0,0,57,537,501,113,125,92,45,31,70,49,95,24,37,88,108,33,9,55,7,35,22,367,39,33.6,363,204,159,114,45,406,363,43,160,203,632,98,414,120,26458.0,NaN,17622.0,1956.0,881.0,1092.0,196800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,9,28,18,42,261,38,10,160,8,0,26,50,52,9,15,0,0,0,0,203,30,0,9,34,64,0,48,8,10,1038,336,618,NaN,NaN,NaN,NaN,2.86,134,71,10,16,21,52,35,0,0,19,5,NaN,NaN,708,405,405,334,71,0,303,NaN

kfm9-mvzv (3532, 77) Census Block Groups in Colorado 2010

,the_geom,NAME10,AREALAND,AREAWATR,INTPTLAT,INTPTLON,STATE,COUNTY,TRACT,BLKGRP,GEOIDBG,POP2010,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_JUVENL,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_R_NOTOCC,V_FORSALE,V_S_NOTOCC,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-104.5146160000001 37.16120100...,Block Group 3,2161767,0,37.156654,-104.510833,8,71,400,3,80710004003,861,477,55.40,358,41.58,2,0.23,4,0.46,9,1.05,1,0.12,3,0.35,7,0.81,408,47.39,453,52.61,148,17.19,210,24.39,117,13.59,38.3,36.9,39.8,385,219,126,93,166,141,2.19,49,336,2.85,16,0,0,0,0,0,16,0,0,16,461,385,83.51,76,16.49,194,50.39,191,49.61,46,2,7,2,6,0,13
1,MULTIPOLYGON (((-104.4805720000001 37.00530600...,Block Group 2,93736110,0,37.067648,-104.480023,8,71,400,2,80710004002,764,302,39.53,452,59.16,3,0.39,1,0.13,1,0.13,0,0.00,0,0.00,5,0.65,354,46.34,410,53.66,185,24.21,166,21.73,77,10.08,45.8,45.8,45.8,332,225,176,49,107,96,2.30,23,309,2.79,0,0,0,0,0,0,0,0,0,0,367,332,90.46,35,9.54,272,81.93,60,18.07,6,0,10,1,6,0,12
2,MULTIPOLYGON (((-104.8365240000001 37.17387200...,Block Group 2,1056031660,908820,37.107925,-104.955343,8,71,300,2,80710003002,671,220,32.79,426,63.49,0,0.00,6,0.89,7,1.04,0,0.00,2,0.30,10,1.49,348,51.86,323,48.14,144,21.46,121,18.03,72,10.73,53.3,53.5,53.2,309,200,160,40,109,96,2.17,18,291,2.70,0,0,0,0,0,0,0,0,0,0,549,309,56.28,240,43.72,238,77.02,71,22.98,17,0,10,1,160,0,52

ueer-yycc (458, 275) Census Places in Colorado 2011

,the_geom,OBJECTID,STATEFP,PLACEFP,PLACENS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,PCICBSA,PCINECTA,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,Shape_Leng,Shape_Area,LOGRECNO,NAMEACS,PLACE,GEOID_1,POP0711,HISPANIC,WHITE_NH,BLACK_NH,NTVAM_NH,ASIAN_NH,HAWPI_NH,OTHER_NH,TWOPLUS_NH,MALE,FEMALE,AGELESS10,AGELESS18,AGE18_24,AGE25_34,AGE35_44,AGE45_64,AGE65PLUS,MED_AGE,HOUSEHOLDS,FAMILYHH,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSING_UN,OCC_HU,VAC_HU,OWNED,RENTED,POP25PLUS,NOHSDIPL,HSGRAD_SC,BACHL_HGHR,MED_HH_INC,MED_FAM_IN,PER_CAP_IN,MED_YR_BLT,MED_C_RENT,MED_G_RENT,MED_HM_VAL,CITZ_BIRTH,CITZ_NAT,NOT_CITZ,BORN_IN_CO,BRN_OTH_ST,NTV_B_O_US,FOREIGN_B,POP_1P,SAME_HOUSE,SAME_CNTY,SAME_STATE,DIFF_STATE,FRM_ABROAD,WRKRS_16PL,CAR_ALL,CAR_ALONE,CAR_CARPOO,PUBLIC_TRN,PT_BUS,PT_OTHER,BIKE,WALK,TR_OTHER,WRK_HOME,W_16PL_NH,T_LESS_10,T_10_19,T_20_29,T_30_39,T_40_59,T_60_PL,POP_3PL,ENROLLED,PRESCHOOL,KNDRGRTN,GR_1_4,GR_5_8,GR_9_12,UNDERGRAD,GRAD_PROF,N_ENROLLED,BLT_2000_P,B1990_1999,B1980_1989,B1970_1979,B1960_1969,B1950_1959,B1940_1949,B1939_E,OWN_OCC_HU,V_L_50K,V50K_100K,V100K_150K,V150K_200K,V200K_250K,V250K_300K,V300K_400K,V400K_500K,V500K_750K,V750K_1M,V_1M_PLUS,RNT_OCC_HU,RNTL400,R400T599,R600T799,R800T999,R1000T1249,R1250T1499,R1500T1999,R2000PL,RNOCSHR,AGE_0_9,AGE_10_19,AGE_20_29,AGE_30_39,AGE_40_49,AGE_50_59,AGE_60_69,AGE_70_79,AGE_80_PL,PS_Uni,PS_BELOW,ADJ_PS_Uni,ADJ_PS_Pov,AVGHHSIZE,MLOGRECNO,MPOP0711,MHISPANIC,MWHITE_NH,MBLACK_NH,MNTVAM_NH,MASIAN_NH,MHAWPI_NH,MOTHER_NH,MTWOPLUS_N,MMALE,MFEMALE,MAGELESS10,MAGELESS18,MAGE18_24,MAGE25_34,MAGE35_44,MAGE45_64,MAGE65PLUS,MMED_AGE,MHOUSEHOLD,MFAMILYHH,MNONFAMHH,MHHLDRALON,MHHLDR_NAL,MHOUSING_U,MOCC_HU,MVAC_HU,MOWNED,MRENTED,MPOP25PLUS,MNOHSDIPL,MHSGRAD_SC,MBACHL_HGH,MMED_HH_IN,MMED_FAM_I,MPER_CAP_I,MMED_YR_BL,MMED_C_REN,MMED_G_REN,MMED_HM_VA,MCITZ_BIRT,MCITZ_NAT,MNOT_CITZ,MBORN_IN_C,MBRN_OTH_S,MNTV_B_O_U,MFOREIGN_B,MPOP_1P,MSAME_HOUS,MSAME_CNTY,MSAME_STAT,MDIFF_STAT,MFRM_ABROA,MWRKRS_16P,MCAR_ALL,MCAR_ALONE,MCAR_CARPO,MPUBLIC_TR,MPT_BUS,MPT_OTHER,MBIKE,MWALK,MTR_OTHER,MWRK_HOME,MW_16PL_NH,MT_LESS_10,MT_10_19,MT_20_29,MT_30_39,MT_40_59,MT_60_PL,MPOP_3PL,MENROLLED,MPRESCHOOL,MKNDRGRTN,MGR_1_4,MGR_5_8,MGR_9_12,MUNDERGRAD,MGRAD_PROF,MN_ENROLLE,MBLT_2000_,MB1990_199,MB1980_198,MB1970_197,MB1960_196,MB1950_195,MB1940_194,MB1939_E,MOWN_OCC_H,MV_L_50K,MV50K_100K,MV100K_150,MV150K_200,MV200K_250,MV250K_300,MV300K_400,MV400K_500,MV500K_750,MV750K_1M,MV_1M_PLUS,MRNT_OCC_H,MRNTL400,MR400T599,MR600T799,MR800T999,MR1000T124,MR1250T149,MR1500T199,MR2000PL,MRNOCSHR,MAGE_0_9,MAGE_10_19,MAGE_20_29,MAGE_30_39,MAGE_40_49,MAGE_50_59,MAGE_60_69,MAGE_70_79,MAGE_80_PL,MPS_Uni,MPS_BELOW,MADJ_PS_Un,MADJ_PS_Po,MAVGHHSIZE
0,MULTIPOLYGON (((-106.98112900000011 38.8734530...,1,8,18310,2412385,818310,Crested Butte,Crested Butte town,43,C1,N,N,G4110,A,2179997,0,38.867736,-106.977266,0.091389,0.000226,8987,"Crested Butte town, Colorado",18310,818310,1482,36,1414,0,0,20,0,0,12,759,723,181,250,130,375,329,380,18,34.8,709,327,382,207,175,1143,709,434,385,324,1102,10,420,672,56583,59779,37094,1977,935,1034,650900,1394,12,76,332,1013,49,88,1464,1167,179,35,69,14,974,327,274,53,38,38,0,298,246,31,34,940,606,257,28,26,13,10,1448,271,13,13,112,32,16,51,34,1177,77,249,147,313,51,25,13,268,385,0,8,12,27,26,24,30,16,82,114,46,324,0,12,54,83,58,54,50,3,10,181,74,262,418,265,211,67,4,0,1482,201,1084,143,2.08,8987,317,36,300,92,92,26,92,92,20,184,170,73,83,150,117,95,81,261,2.7,137,91,98,61,68,150,137,98,90,106,227,345,138,160,12579,13291,8588,2,133,157,138543,292,14,52,109,229,45,56,311,259,88,35,55,21,220,94,76,37,33,33,184,113,95,30,24,225,149,96,95,95,16,93,304,97,16,15,58,25,21,43,26,249,43,68,61,102,37,24,17,68,90,260,185,94,28,24,23,31,19,45,52,23,106,243,131,136,29,47,40,36,6,12,73,40,168,111,82,62,97,17,19,317,147,170,62,0.24
1,MULTIPOLYGON (((-102.42129900000002 39.3061340...,6,8,6530,2411684,806530,Bethune,Bethune town,43,C1,N,N,G4110,A,419628,0,39.303822,-102.423414,0.028225,0.000044,8921,"Bethune town, Colorado",6530,806530,300,166,134,0,0,0,0,0,0,166,134,72,119,25,39,32,59,26,25.5,72,62,10,10,0,81,72,9,53,19,156,30,110,16,43571,43929,16089,1980,471,571,59500,201,8,91,145,56,0,99,300,283,14,3,0,0,131,124,106,18,0,0,0,0,2,2,3,128,10,98,2,17,1,0,284,113,0,17,33,23,31,9,0,171,0,22,19,12,5,10,4,9,53,17,18,18,0,0,0,0,0,0,0,0,19,1,10,4,0,0,0,0,0,4,72,62,33,28,47,21,25,6,6,300,91,130,20,4.17,8921,116,107,58,92,92,92,92,92,92,63,63,99,103,207,28,18,25,226,8.8,25,23,12,12,92,26,25,11,21,15,48,292,35,185,16459,20301,5173,9,172,51,51724,151,12,60,65,27,92,64,116,115,17,5,92,92,45,42,39,17,92,92,184,92,6,4,5,44,10,43,92,93,92,130,107,62,92,19,26,25,27,14,92,61,130,16,15,10,8,13,5,8,21,160,160,18,130,92,92,92,92,92,92,92,15,225,131,159,92,92,92,92,92,7,99,98,186,18,23,15,131,10,17,116,121,210,206,1.18
2,MULTIPOLYGON (((-104.93308200000011 40.4781210...,14,8,85485,2413496,885485,Windsor,Windsor town,43,C1,N,N,G4110,A,63298788,819125,40.477555,-104.916800,1.450782,0.006808,9338,"Windsor town, Colorado",85485,885485,17988,1922,15135,80,169,263,25,47,347,8972,9016,3567,5433,1081,2512,2794,4660,1508,34.9,6379,4917,1462,1175,287,6839,6379,460,4998,1381,11474,531,6108,4835,78013,84802,32647,1998,843,984,264200,17263,270,455,7872,9243,148,725,17726,14541,1535,827,794,29,9230,7926,7209,717,0,0,0,54,59,166,1025,8205,1469,2241,2236,1289,356,614,17067,4890,589,448,1379,1021,798,493,162,12177,3114,1566,451,1073,121,130,90,294,4998,87,25,226,1067,944,529,679,648,686,52,55,1381,58,215,231,181,264,182,99,96,55,3567,2220,1910,3032,2228,2679,1310,582,460,17822,457,9963,214,2.80,9338,48,659,713,84,123,174,41,91,185,323,325,418,523,252,313,317,422,250,1.6,250,215,259,236,113,297,250,181,334,240,374,251,540,436,5181,7677,1501,1,149,101,15732,342,150,282,631,609,104,301,128,579,403,403,264,37,418,449,390,211,92,92,184,58,43,119,225,444,305,318,389,262,147,174,220,404,193,167,226,205,204,127,90,389,292,219,147,189,73,111,68,107,334,198,186,123,203,189,138,149,148,132,37,55,240,189,156,133,56,122,111,83,68,49,418,346,307,332,285,300,242,17,17,138,301,588,167,0.11

7m6d-cpmt (1, 157) Census in Colorado 2016

,the_geom,geonum,pop,geoname,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,"MULTIPOLYGON (((-109.060253 38.599328, -109.05...",108,5359295,Colorado,1132292,3696127,207585,28804,154498,6530,10120,123339,2689636,2669659,335492,355338,351831,345616,380668,399840,398170,368212,356154,349296,369242,356419,314977,248399,160843,113623,77015,78160,1246181,522764,36.4,2051616,1318973,732643,563422,169221,2284863,2051616,233247,1320617,730999,3590350,323691,1876929,1389730,62520,77130,33230,1982,929,1057,264600,4834851,206682,317762,2294446,2461186,79219,524444,5295835,4292465,490044,265185,213586,34555,2673188,2259162,2010669,248493,83995,69291,14704,34240,79845,28227,187719,2485469,329329,738191,546801,420327,282720,168101,5159317,1394890,86731,71122,282927,280541,276496,319001,78072,3764427,62743,431585,385704,336677,430163,208131,182284,63224,184352,1320617,65013,60820,111749,186277,188918,162751,228971,126421,121849,36569,31279,730999,36050,46304,107941,130930,137204,101445,102673,42894,25558,5241057,637938,1064125,1229418,663010,193212,48933,2.56,278065,184015,184111,175903,162904,211250,276255,194355,122056,133864,128838,5267878,550037,4245559,2897359,2864224,2692529,171695,33135,1348200,5267878

r87x-h98m (141040, 75) Census Blocks in Colorado 2000

,the_geom,UR00,ALAND00,AWATER00,STATE,COUNTY,TRACT,BLKGRP,BLOCK,GEOIDBLOCK,NAMESF1,POP2000,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_RS_N_OCC,V_FORSALE,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-105.0290230000001 39.93500800...,U,42130,0,8,1,8516,2,2018,80010085162018,Block 2018,0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.00,0,0.0,0,0.0,0,0.00,0,0.00,0,0.00,0,0.00,0,0.00,0,0.00,0.0,0.0,0.0,0,0,0,0,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0.0,0,0.0,0,0.0,0,0,0,0,0,0
1,MULTIPOLYGON (((-105.0472560000001 39.92676600...,U,16112,0,8,1,8515,1,1081,80010085151081,Block 1081,60,6,10.00,43,71.67,0,0.0,0,0.0,5,8.33,0,0.0,0,0.0,6,10.00,29,48.33,31,51.67,1,1.67,24,40.00,17,28.33,30.7,30.8,30.5,17,15,15,0,0,2,3.53,0,17,3.87,0,0,0,0,0,0,0,0,0,17,17,100.0,0,0.0,17,100.0,0,0.0,0,0,0,0,0,0
2,MULTIPOLYGON (((-105.0268170000001 39.94266800...,U,42709,0,8,1,8516,2,2003,80010085162003,Block 2003,55,4,7.27,43,78.18,0,0.0,0,0.0,6,10.91,0,0.0,0,0.0,2,3.64,26,47.27,29,52.73,2,3.64,15,27.27,11,20.00,34.8,34.0,35.5,23,14,10,4,1,8,2.39,3,20,3.07,0,0,0,0,0,0,0,0,0,23,23,100.0,0,0.0,21,91.3,2,8.7,0,0,0,0,0,0

4zf4-r52a (458, 157) Census Places in Colorado 2013

,geoname,geonum,pop,the_geom,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r800t999,r600t799,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,"Aurora city, Colorado",10804000,332820,"MULTIPOLYGON (((-104.517529 39.748404, -104.50...",96574,155840,50970,1199,15947,778,421,11091,164051,168769,28247,26522,22604,21920,22952,26521,26612,24825,22695,21493,21131,19147,16740,11716,6977,5416,3830,3472,90532,31713,33.3,122035,79836,42199,34340,7859,130682,122035,8647,70618,51417,210575,29774,125276,55525,50987.0,58794.0,24173.0,1982.0,819.0,947.0,176500.0,264851,21254,46715,127651,132117,5083,67969,327054,251892,36074,25393,10822,2873,157119,137581,119389,18192,9107,8093,1014,588,2797,1588,5458,151661,9933,34210,38046,36119,22087,11266,315405,89666,5195,4784,20752,17944,18552,17719,4720,225739,751,22925,12880,34262,37264,10895,8767,1772,1166,70618,3547,6749,14144,19253,12551,6151,4553,2023,1289,218,140,51417,1063,3888,12958,10676,9972,6158,4833,966,903,330018,55124,92756,89233,30420,21261,2774,2.71,18959,14320,13674,12760,11767,13347,15050,9603,5407,4382,2766,329650,33255,251205,179447,177781,158576,19205,1666,71758,329650
1,"Ovid town, Colorado",10856475,323,"MULTIPOLYGON (((-102.392458 40.962044, -102.38...",55,253,5,0,1,0,0,9,154,169,14,7,15,14,44,28,9,8,17,15,35,35,18,24,9,17,6,8,43,51,46.7,142,87,55,49,6,173,142,31,97,45,229,44,159,26,32500.0,54063.0,20843.0,1939.0,335.0,505.0,45000.0,307,1,15,186,121,0,16,323,221,24,39,34,5,159,132,97,35,0,0,0,1,21,0,5,154,64,30,19,9,27,5,318,45,7,1,4,17,10,4,2,273,0,0,5,10,18,0,26,22,92,97,55,31,7,2,2,0,0,0,0,0,0,45,13,14,0,16,0,0,0,0,2,323,55,77,43,64,3,10,2.27,44,15,22,9,16,14,9,6,5,0,2,323,51,281,184,184,163,21,0,97,323
2,"Padroni CDP, Colorado",10856695,189,MULTIPOLYGON (((-103.181368 40.789373999999995...,0,185,0,0,0,0,0,4,154,35,0,45,15,0,9,14,50,41,0,0,4,0,4,7,0,0,0,0,60,9,30.7,31,27,4,4,0,39,31,8,31,0,120,48,68,4,43672.0,43984.0,15281.0,1939.0,NaN,NaN,52300.0,189,0,0,85,104,0,0,189,148,41,0,0,0,75,75,45,30,0,0,0,0,0,0,0,75,4,30,41,0,0,0,189,60,0,15,45,0,0,0,0,129,0,0,0,4,4,0,0,0,31,31,11,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,189,4,94,60,7,0,0,6.10,4,0,4,16,0,7,0,0,0,0,0,189,34,129,84,84,75,9,0,45,189

v4w4-3yz8 (63, 72) Census Counties SF1 in Colorado 2000

,the_geom,NAME00,ALAND00,AWATER00,STATE,COUNTY,GEOID,NAMESF1,POP2000,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_RS_N_OCC,V_FORSALE,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-105.1661500000001 39.91404700...,Boulder,1908733293,36715760,8,13,8013,Boulder County,291288,30456,10.46,243512,83.60,2393,0.82,1206,0.41,8834,3.03,147,0.05,439,0.15,4301,1.48,147264,50.56,144024,49.44,22670,7.78,66837,22.95,36302,12.46,33.4,32.3,34.6,114680,68787,56087,12700,15755,30138,2.47,20077,94603,3.03,8513,1737,597,1091,49,6776,6165,0,611,119900,114680,95.65,5220,4.35,74237,64.73,40443,35.27,1431,433,573,2026,2,755
1,MULTIPOLYGON (((-105.0567200000001 40.34928100...,Larimer,-2147483648,98295250,8,69,8069,Larimer County,251494,20811,8.27,220159,87.54,1511,0.60,1171,0.47,3840,1.53,152,0.06,234,0.09,3616,1.44,125654,49.96,125840,50.04,24037,9.56,59755,23.76,31741,12.62,33.2,31.9,34.6,97164,63197,52121,11076,11256,22711,2.52,14830,82334,2.99,7120,1448,361,1066,21,5672,4614,0,1058,105392,97164,92.19,8228,7.81,65767,67.69,31397,32.31,1334,448,795,4870,11,770
2,MULTIPOLYGON (((-104.1431790000001 37.75833000...,Las Animas,-2147483648,6929979,8,71,8071,Las Animas County,15207,6304,41.45,8387,55.15,52,0.34,161,1.06,53,0.35,13,0.09,16,0.11,221,1.45,7441,48.93,7766,51.07,2732,17.97,3687,24.25,1893,12.45,40.9,39.8,42.0,6173,4095,3081,1014,246,1832,2.40,486,5687,2.97,391,201,47,154,0,190,107,0,83,7629,6173,80.91,1456,19.09,4360,70.63,1813,29.37,175,95,150,626,3,407

6ddv-3hk2 (3532, 267) Census Block Groups in Colorado 2011

,the_geom,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,GEOID,NAMELSAD,ALAND,AWATER,INTPTLAT,INTPTLON,Shape_Leng,Shape_Area,LOGRECNO,NAMEACS,GEOID_1,POP0711,HISPANIC,WHITE_NH,BLACK_NH,NTVAM_NH,ASIAN_NH,HAWPI_NH,OTHER_NH,TWOPLUS_NH,MALE,FEMALE,AGELESS10,AGELESS18,AGE18_24,AGE25_34,AGE35_44,AGE45_64,AGE65PLUS,MED_AGE,HOUSEHOLDS,FAMILYHH,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSING_UN,OCC_HU,VAC_HU,OWNED,RENTED,POP25PLUS,NOHSDIPL,HSGRAD_SC,BACHL_HGHR,MED_HH_INC,MED_FAM_IN,PER_CAP_IN,MED_YR_BLT,MED_C_RENT,MED_G_RENT,MED_HM_VAL,CITZ_BIRTH,CITZ_NAT,NOT_CITZ,BORN_IN_CO,BRN_OTH_ST,NTV_B_O_US,FOREIGN_B,POP_1P,SAME_HOUSE,SAME_CNTY,SAME_STATE,DIFF_STATE,FRM_ABROAD,WRKRS_16PL,CAR_ALL,CAR_ALONE,CAR_CARPOO,PUBLIC_TRN,PT_BUS,PT_OTHER,BIKE,WALK,TR_OTHER,WRK_HOME,W_16PL_NH,T_LESS_10,T_10_19,T_20_29,T_30_39,T_40_59,T_60_PL,POP_3PL,ENROLLED,PRESCHOOL,KNDRGRTN,GR_1_4,GR_5_8,GR_9_12,UNDERGRAD,GRAD_PROF,N_ENROLLED,BLT_2000_P,B1990_1999,B1980_1989,B1970_1979,B1960_1969,B1950_1959,B1940_1949,B1939_E,OWN_OCC_HU,V_L_50K,V50K_100K,V100K_150K,V150K_200K,V200K_250K,V250K_300K,V300K_400K,V400K_500K,V500K_750K,V750K_1M,V_1M_PLUS,RNT_OCC_HU,RNTL400,R400T599,R600T799,R800T999,R1000T1249,R1250T1499,R1500T1999,R2000PL,RNOCSHR,AGE_0_9,AGE_10_19,AGE_20_29,AGE_30_39,AGE_40_49,AGE_50_59,AGE_60_69,AGE_70_79,AGE_80_PL,PS_Uni,PS_BELOW,ADJ_PS_Uni,ADJ_PS_Pov,AVGHHSIZE,MLOGRECNO,MPOP0711,MHISPANIC,MWHITE_NH,MBLACK_NH,MNTVAM_NH,MASIAN_NH,MHAWPI_NH,MOTHER_NH,MTWOPLUS_N,MMALE,MFEMALE,MAGELESS10,MAGELESS18,MAGE18_24,MAGE25_34,MAGE35_44,MAGE45_64,MAGE65PLUS,MMED_AGE,MHOUSEHOLD,MFAMILYHH,MNONFAMHH,MHHLDRALON,MHHLDR_NAL,MHOUSING_U,MOCC_HU,MVAC_HU,MOWNED,MRENTED,MPOP25PLUS,MNOHSDIPL,MHSGRAD_SC,MBACHL_HGH,MMED_HH_IN,MMED_FAM_I,MPER_CAP_I,MMED_YR_BL,MMED_C_REN,MMED_G_REN,MMED_HM_VA,MCITZ_BIRT,MCITZ_NAT,MNOT_CITZ,MBORN_IN_C,MBRN_OTH_S,MNTV_B_O_U,MFOREIGN_B,MPOP_1P,MSAME_HOUS,MSAME_CNTY,MSAME_STAT,MDIFF_STAT,MFRM_ABROA,MWRKRS_16P,MCAR_ALL,MCAR_ALONE,MCAR_CARPO,MPUBLIC_TR,MPT_BUS,MPT_OTHER,MBIKE,MWALK,MTR_OTHER,MWRK_HOME,MW_16PL_NH,MT_LESS_10,MT_10_19,MT_20_29,MT_30_39,MT_40_59,MT_60_PL,MPOP_3PL,MENROLLED,MPRESCHOOL,MKNDRGRTN,MGR_1_4,MGR_5_8,MGR_9_12,MUNDERGRAD,MGRAD_PROF,MN_ENROLLE,MBLT_2000_,MB1990_199,MB1980_198,MB1970_197,MB1960_196,MB1950_195,MB1940_194,MB1939_E,MOWN_OCC_H,MV_L_50K,MV50K_100K,MV100K_150,MV150K_200,MV200K_250,MV250K_300,MV300K_400,MV400K_500,MV500K_750,MV750K_1M,MV_1M_PLUS,MRNT_OCC_H,MRNTL400,MR400T599,MR600T799,MR800T999,MR1000T124,MR1250T149,MR1500T199,MR2000PL,MRNOCSHR,MAGE_0_9,MAGE_10_19,MAGE_20_29,MAGE_30_39,MAGE_40_49,MAGE_50_59,MAGE_60_69,MAGE_70_79,MAGE_80_PL,MPS_Uni,MPS_BELOW,MADJ_PS_Un,MADJ_PS_Po,MAVGHHSIZE
0,MULTIPOLYGON (((-106.77291200000006 38.7312530...,8,51,963800,1,80519638001,Block Group 1,761714497,789241,38.879869,-106.934068,2.318486,0.079152,7031,"Block Group 1, Census Tract 9638, Gunnison Cou...",80519638001,443,2,342,0,0,42,0,0,57,244,199,35,84,14,12,79,188,66,50.6,186,143,43,43,0,673,186,487,148,38,345,0,168,177,49138,61513,35149,1989,525,775,1000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122,54,21,47,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,207,120,104,116,25,33,12,56,148,0,0,0,15,8,0,15,15,11,0,84,38,10,0,18,0,0,0,10,0,0,35,49,26,0,102,94,114,15,8,443,17,NaN,NaN,2.37,7031,129,5,110,92,92,38,92,92,42,77,68,134,190,244,160,141,120,265,8.7,57,50,41,41,92,150,57,152,53,36,99,368,152,199,17027,34564,15822,8,767,854,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61,43,97,50,130,130,130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120,71,75,87,29,36,18,62,53,260,206,130,95,10,92,25,22,17,92,42,36,226,184,162,92,92,92,17,92,92,134,187,227,184,59,56,171,17,17,129,30,NaN,NaN,0.48
1,MULTIPOLYGON (((-106.97895900000013 38.8742070...,8,51,963800,3,80519638003,Block Group 3,1311102,0,38.862885,-106.967471,0.062528,0.000136,7033,"Block Group 3, Census Tract 9638, Gunnison Cou...",80519638003,612,9,590,0,0,13,0,0,0,307,305,101,139,30,160,126,157,0,34.3,286,135,151,62,89,372,286,86,157,129,443,8,78,357,58382,63036,26069,1982,994,1229,733100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,336,232,78,14,12,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,113,71,135,12,15,0,9,157,0,0,0,23,0,0,12,9,37,56,20,129,0,8,15,36,6,31,30,3,0,101,39,96,170,109,63,34,0,0,612,72,NaN,NaN,2.13,7033,186,9,177,92,92,23,92,92,92,112,111,60,114,187,79,58,51,319,3.8,80,52,59,37,49,87,80,43,58,57,134,357,188,191,7943,14248,4058,6,293,467,165842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120,98,42,93,93,130,130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,48,41,65,18,17,92,14,58,260,206,130,96,92,92,20,18,26,35,16,57,243,160,131,92,12,30,30,6,92,60,134,172,71,51,29,185,19,19,186,79,NaN,NaN,0.30
2,MULTIPOLYGON (((-106.88060300000001 38.5415960...,8,51,963600,3,80519636003,Block Group 3,891529541,122909,38.489104,-106.611525,2.069517,0.092084,7020,"Block Group 3, Census Tract 9636, Gunnison Cou...",80519636003,627,0,621,0,0,0,0,0,6,362,265,119,159,12,0,126,266,64,47.5,328,136,192,177,15,492,328,164,270,58,456,0,289,167,64490,91250,38400,1979,668,837,307500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,312,77,108,102,7,0,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43,115,81,96,52,0,42,63,270,18,14,0,12,47,41,40,57,15,0,26,58,0,0,12,46,0,0,0,0,0,119,52,0,11,148,191,75,17,14,627,0,NaN,NaN,1.91,7020,280,92,279,92,92,92,92,92,12,175,126,180,228,244,184,141,187,210,14.6,113,81,107,104,23,131,113,86,104,70,145,368,170,213,22699,61652,8327,8,233,202,113756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,124,79,68,76,93,130,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35,72,78,74,42,92,50,60,104,226,185,130,94,53,37,36,79,16,92,22,70,243,184,160,68,92,92,92,92,92,180,169,260,160,148,79,166,15,14,280,184,NaN,NaN,0.56

ty6r-gpdz (7, 156) Census Congressional Districts in Colorado 2013

,pop,con_dist,hispanic,the_geom,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400T599,r600T799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,740254,1,211732,MULTIPOLYGON (((-105.14597299975412 39.5774160...,421720,62138,3859,23514,490,1235,15566,369560,370694,50896,45833,39284,39543,53437,77470,69514,58160,52740,47254,46514,43811,37291,25515,16904,12505,11238,12345,158636,70357,34.5,315635,159272,156363,121825,34538,339671,315635,24036,168154,147481,511261,67591,225307,218363,52491,69630,34106,1968,801,889,251100,633317,34797,72140,316288,307428,9601,106937,729868,573298,74052,49926,27094,5498,384187,307616,273250,34366,25293,20801,4492,7853,15397,4032,23996,360191,35067,107529,89759,69386,38791,19659,709570,180941,12838,9998,35420,30862,30997,44044,16782,528629,2458,44922,27417,32575,56162,39509,52068,22636,61924,168154,4340,8210,19901,25732,25460,20600,27839,13545,13247,4299,4981,147481,11343,12563,33710,29859,23243,14394,13856,5364,3149,727681,127151,196822,156873,76563,40988,8596,2.30,59949,32515,30261,27789,24422,29660,35964,24218,14826,17352,18679,733095,69627,597117,427053,426557,390074,36483,496,170064,733095
1,720369,3,173130,MULTIPOLYGON (((-109.06025600041404 38.4932539...,515899,5559,8597,4979,515,1027,10663,362662,357707,45280,46311,46607,49190,45131,46723,45094,43299,45442,48577,54335,53544,47105,34802,24835,18665,13141,12288,166316,66203,39.2,283906,185002,98904,79867,19037,356668,283906,72762,196661,87245,487850,54277,291626,141947,49265,59835,26626,1982,703,848,205000,674738,13539,32092,350181,318272,6285,45631,712546,584633,75820,24461,25186,2446,328331,277726,236509,41217,7351,6775,576,5104,13971,3869,20310,308021,74985,110929,49189,30900,21175,20843,694084,178431,11838,9174,37219,37488,39056,37979,5677,515653,1472,69516,67527,49177,64621,24898,25968,12569,40920,196661,15954,20710,26393,32901,23838,17922,21778,12065,12795,5061,7244,87245,7233,11820,17514,15028,12937,7100,6478,2713,6422,702732,107157,179769,163855,100890,33622,9906,2.47,54292,31790,30051,27590,24763,30128,35070,20496,10893,10322,8511,710198,91809,572749,368521,367872,334256,33616,649,204228,710198
2,729855,5,106795,MULTIPOLYGON (((-106.59903200032653 39.0362730...,533132,38732,3811,16988,1807,1160,27430,370352,359503,49538,51531,48561,50943,56049,54324,49510,44197,49099,52638,53932,46156,40605,29067,19471,14882,10542,8810,179944,76678,35.5,274713,185681,89032,73033,15999,306054,274713,31341,179636,95077,473233,33897,280514,158822,55421,68696,28279,1983,760,894,211700,680973,24696,24186,234560,424231,22182,48882,720407,567714,82032,14671,46391,9599,337963,294614,260197,34417,2721,2542,179,1884,14880,3697,20167,317796,47609,110029,78696,43624,22050,15788,700977,202492,11613,10915,40903,38916,39120,51220,9805,498485,2353,62153,52466,54739,56238,30404,21110,5849,20742,179636,8893,7325,24033,42776,29090,19637,25057,10565,8636,1880,1744,95077,3576,12871,21337,16608,17476,10120,7685,2297,3107,698132,86622,143221,177263,80751,30225,5529,2.55,41298,28114,27424,25949,24166,28996,35942,23647,14955,13848,10374,685668,79264,569254,377561,349616,316789,32827,27945,191693,685668

iku4-4bpx (3532, 157) Census Block Groups in Colorado 2016

,the_geom,pop,geonum,geoname,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,"MULTIPOLYGON (((-104.996632 39.903307, -104.99...",592,1080010093232,2,137,338,36,0,81,0,0,0,302,290,82,71,58,19,57,72,76,77,18,0,34,6,5,17,0,0,0,0,224,63,25.5,254,103,151,124,27,276,254,22,0,254,305,30,234,41,30294.0,NaN,15851.0,1981.0,762.0,862.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,36,119,70,25,26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,254,15,0,99,37,84,19,0,0,0,592,157,304,NaN,NaN,NaN,NaN,2.33,83,42,17,27,62,0,23,0,0,0,0,NaN,NaN,381,284,284,274,10,0,97,NaN
1,"MULTIPOLYGON (((-105.053036 39.892187, -105.05...",2597,1080010094092,2,130,2172,98,145,52,0,0,0,1302,1295,114,98,229,70,87,51,175,212,197,234,158,175,206,189,129,49,37,187,498,100,45.7,1240,707,533,434,99,1272,1240,32,847,393,1999,64,1024,911,96071.0,NaN,52145.0,2000.0,1219.0,1259.0,282100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27,636,174,121,303,0,0,11,0,847,26,0,25,82,173,183,94,21,222,9,12,393,0,0,0,42,143,112,39,42,15,2597,73,118,NaN,NaN,NaN,NaN,2.09,73,106,33,165,41,50,196,273,51,106,146,NaN,NaN,2099,1334,1334,1334,0,0,765,NaN
2,"MULTIPOLYGON (((-105.040549 39.841801, -105.03...",635,1080010096032,2,0,635,0,0,0,0,0,0,272,363,0,0,112,29,0,0,77,136,29,40,39,58,31,23,0,0,49,12,112,29,39.1,262,175,87,74,13,275,262,13,205,57,494,55,381,58,85326.0,NaN,29130.0,1953.0,NaN,NaN,134300.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,36,141,66,32,205,29,0,98,44,22,0,0,0,12,0,0,57,0,0,0,0,0,57,0,0,0,635,15,29,NaN,NaN,NaN,NaN,2.42,36,12,31,7,29,0,75,72,0,0,0,NaN,NaN,523,375,375,352,23,0,148,NaN

cmkv-zd4f (3532, 157) Census Block Groups in Colorado 2014

,the_geom,geoname,geonum,pop,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v300k_400k,v250k_300k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,"MULTIPOLYGON (((-108.71085 38.358774, -108.709...",1,1080859661001,1112,72,972,0,3,0,0,0,65,533,579,59,51,71,74,59,10,34,77,48,51,139,130,122,73,35,37,8,34,224,90,50.9,485,325,160,129,31,608,485,123,356,129,798,99,569,130,47188.0,60208.0,25372.0,1975.0,579.0,771.0,150000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,59,129,63,114,59,52,19,113,356,61,59,58,79,32,30,11,6,17,0,3,129,3,23,27,27,11,0,0,0,38,1105,241,325,NaN,NaN,NaN,NaN,2.29,121,66,37,37,41,49,49,26,29,28,2,NaN,NaN,910,551,551,459,92,0,359,NaN
1,"MULTIPOLYGON (((-107.91409 40.46055, -107.9126...",2,1080810006002,913,34,817,0,8,0,50,0,4,568,345,36,39,80,34,14,0,60,40,5,88,79,161,128,41,24,59,15,10,181,22,52.5,340,269,71,61,10,615,340,275,299,41,710,19,606,85,57845.0,59526.0,26548.0,1979.0,2001.0,2001.0,263400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,92,135,67,140,24,4,35,118,299,16,36,0,81,5,72,43,27,10,0,9,41,0,0,0,0,4,0,0,25,12,913,39,67,NaN,NaN,NaN,NaN,2.69,40,17,48,30,60,23,77,19,14,7,5,NaN,NaN,749,461,461,437,24,0,288,NaN
2,"MULTIPOLYGON (((-104.99936 39.649397, -104.987...",2,1080050060002,578,52,526,0,0,0,0,0,0,285,293,7,18,39,29,24,17,91,7,68,30,85,27,20,24,33,26,18,15,85,32,43.4,270,131,139,131,8,293,270,23,175,95,461,61,267,133,57143.0,58375.0,29735.0,1955.0,930.0,1059.0,214000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,27,17,37,0,122,35,55,175,10,7,0,47,84,0,19,8,0,0,0,95,0,13,20,0,34,0,15,0,13,578,13,41,NaN,NaN,NaN,NaN,2.14,38,17,28,35,28,39,29,37,19,0,0,NaN,NaN,500,316,316,296,20,0,184,NaN

bd44-na6d (483, 98) Census Zip Codes SF3 in Colorado 2000

,the_geom,OBJECTID,STATEFP00,ZCTA5CE00,GEOID00,CLASSFP00,MTFCC00,FUNCSTAT00,ALAND00,AWATER00,INTPTLAT00,INTPTLON00,PARTFLG00,Shape_Leng,Shape_Area,STATE,ZCTA5,NAME10,POP_SF3,HISPANIC,PCTHISP,WHITE_NH,PCTWHITE,BLACK_NH,PCTBLACK,NTV_AM_NH,PCTNTVAM,ASIAN_NH,PCTASIAN,HAWPI_NH,PCTHAW,OTHER_NH,PCTOTHER,TWOPLUS_NH,PCT_TWOP,MALE,PCT_MALE,FEMALE,PCT_FEMALE,AGELESS10,PCT_L10,AGELESS18,PCT_L18,AGE65PLUS,PCT_65PL,HHLDS,FAMHH,MARCOUPFAM,OTH_FAM,MHHLDR_N_W,FHHLDR_N_H,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSINGU,URBANHU,PCT_URBHU,RURALHU,PCT_RURHU,OCCHU,PCTOCC,VACHU,PCTVAC,OWN,PCTOWN,RENT,PCTRENT,TTLPOP25PL,NO_HS_DIPL,PCT_NODIPL,HSGRAD_PL,PCT_HSPLUS,BACHL_HGHR,PCT_BACHPL,MEDHHINC,MEDFAMINC,PERCAPINC,MEDYRBLT,MEDCRENT,MEDGRENT,MEDVAL,POP3PLUS,ENROLLED,PRESCHOOL,KINDRGRTN,GRADE_1_4,GRADE_5_8,GRADE_9_12,UNDERGRAD,GRADSCH,NOTINSCH,NATIVE,PCTNATIVE,FOREIGN,PCTFOREIGN,PVRTY_UNI,IN_POVERTY,PCT_PVRTY
0,MULTIPOLYGON (((-104.93338499999997 39.9428750...,1,8,80241,880241,B5,G6350,S,16541085,538479,39.929518,-104.954808,N,0.245636,0.001799,8,80241,80241 5-Digit ZCTA,26677,3640,13.64,21364,80.08,396,1.48,114,0.43,550,2.06,26,0.10,9,0.03,578,2.17,13318,49.92,13359,50.08,4591,17.21,8132,30.48,1031,3.86,9106,7408,6426,982,261,721,457,1241,7865,9185,9185,100.00,0,0.00,8931,97.23,254,2.77,7674,85.93,1257,14.07,16560,1051,6.35,15509,93.65,5135,31.01,68618,72264,26724,1994,845,942,191700,25393,8129,687,350,1988,1843,1589,1297,375,17264,25389,95.17,1288,4.83,26398,615,2.33
1,MULTIPOLYGON (((-105.01551699999997 39.8852470...,2,8,80260,880260,B5,G6350,S,12589775,295152,39.866889,-105.010636,N,0.168020,0.001356,8,80260,80260 5-Digit ZCTA,30417,7500,24.66,20165,66.30,571,1.88,258,0.85,1299,4.27,15,0.05,24,0.08,585,1.92,15020,49.38,15397,50.62,4943,16.25,8145,26.78,3067,10.08,12174,7666,5455,2211,647,1564,988,3520,8654,12620,12620,100.00,0,0.00,12174,96.47,446,3.53,8269,67.92,3905,32.08,18788,4554,24.24,14234,75.76,2208,11.75,37468,41380,17441,1979,640,708,57900,28931,7192,485,475,1970,1645,1333,1123,161,21739,27318,89.81,3099,10.19,30194,3182,10.54
2,MULTIPOLYGON (((-104.80655900000009 39.7183760...,4,8,80011,880011,B5,G6350,S,56646497,145743,39.744318,-104.787923,N,0.550904,0.005968,8,80011,80011 5-Digit ZCTA,44951,11245,25.02,22476,50.00,7719,17.17,434,0.97,1362,3.03,38,0.08,45,0.10,1632,3.63,22444,49.93,22507,50.07,8072,17.96,13077,29.09,4110,9.14,16499,11181,7698,3483,868,2615,943,4375,12124,17009,16897,99.34,112,0.66,16458,96.76,551,3.24,9881,60.04,6577,39.96,27012,6075,22.49,20937,77.51,3705,13.72,39053,42976,16654,1973,567,627,123700,42455,11752,785,742,3382,2625,2385,1617,216,30703,37262,82.89,7689,17.11,44374,5579,12.57

p674-r4hf (1062, 101) Census Tracts SF3 in Colorado 2000

,the_geom,OBJECTID,STATEFP00,COUNTYFP00,TRACTCE00,CTIDFP00,NAME00,NAMELSAD00,MTFCC00,FUNCSTAT00,ALAND00,AWATER00,INTPTLAT00,INTPTLON00,Shape_Leng,Shape_Area,STATE,COUNTY,TRACT,GEOIDTR,NAME10,POP_SF3,HISPANIC,PCTHISP,WHITE_NH,PCTWHITE,BLACK_NH,PCTBLACK,NTV_AM_NH,PCTNTVAM,ASIAN_NH,PCTASIAN,HAWPI_NH,PCTHAW,OTHER_NH,PCTOTHER,TWOPLUS_NH,PCT_TWOP,MALE,PCT_MALE,FEMALE,PCT_FEMALE,AGELESS10,PCT_L10,AGELESS18,PCT_L18,AGE65PLUS,PCT_65PL,HHLDS,FAMHH,MARCOUPFAM,OTH_FAM,MHHLDR_N_W,FHHLDR_N_H,NONFAMHH,HHLDRALONE,HHLDR_NALN,HOUSINGU,URBANHU,PCT_URBHU,RURALHU,PCT_RURHU,OCCHU,PCTOCC,VACHU,PCTVAC,OWN,PCTOWN,RENT,PCTRENT,TTLPOP25PL,NO_HS_DIPL,PCT_NODIPL,HSGRAD_PL,PCT_HSPLUS,BACHL_HGHR,PCT_BACHPL,MEDHHINC,MEDFAMINC,PERCAPINC,MEDYRBLT,MEDCRENT,MEDGRENT,MEDVAL,POP3PLUS,ENROLLED,PRESCHOOL,KINDRGRTN,GRADE_1_4,GRADE_5_8,GRADE_9_12,UNDERGRAD,GRADSCH,NOTINSCH,NATIVE,PCTNATIVE,FOREIGN,PCTFOREIGN,PVRTY_UNI,IN_POVERTY,PCT_PVRTY
0,MULTIPOLYGON (((-107.12846200000006 38.8178609...,1,8,51,963900,8051963900,9639.0,Census Tract 9639,G5020,S,4262314987,41657300,38.628582,-107.273386,3.837140,0.445259,8,51,963900,8051963900,Census Tract 9639,782,34,4.35,739,94.50,0,0.00,0,0.00,0,0.00,0,0.0,9,1.15,0,0.00,434,55.50,348,44.50,44,5.63,71,9.08,103,13.17,414,234,231,3,1,2,21,159,255,1065,0,0.00,1065,100.00,340,31.92,725,68.08,240,70.59,100,29.41,668,72,10.78,596,89.22,187,27.99,35987,46181,25434,1979,483,544,210700,765,73,0,0,27,10,19,9,8,692,757,96.80,25,3.20,782,56,7.16
1,MULTIPOLYGON (((-106.95269200000011 38.5507030...,2,8,51,963700,8051963700,9637.0,Census Tract 9637,G5020,S,14476213,0,38.544346,-106.927069,0.256895,0.001496,8,51,963700,8051963700,Census Tract 9637,5686,343,6.03,5128,90.19,59,1.04,31,0.55,21,0.37,0,0.0,11,0.19,93,1.64,3131,55.07,2555,44.93,459,8.07,860,15.12,412,7.25,2215,1020,768,252,86,166,473,722,1493,2418,2418,100.00,0,0.00,2218,91.73,200,8.27,977,44.05,1241,55.95,2653,240,9.05,2413,90.95,1012,38.15,26729,42614,15694,1971,446,496,139900,5546,2747,84,42,197,178,224,1996,26,2799,5544,97.50,142,2.50,4812,1106,22.98
2,"MULTIPOLYGON (((-106.5182840000001 38.951517, ...",3,8,51,963600,8051963600,9636.0,Census Tract 9636,G5020,S,3320042122,10739992,38.673896,-106.709626,4.024958,0.344752,8,51,963600,8051963600,Census Tract 9636,3871,184,4.75,3601,93.03,6,0.15,18,0.46,4,0.10,0,0.0,0,0.00,58,1.50,2005,51.80,1866,48.20,479,12.37,935,24.15,335,8.65,1541,1072,981,91,19,72,138,331,1210,2736,399,14.58,2337,85.42,1535,56.10,1201,43.90,1166,75.96,369,24.04,2618,148,5.65,2470,94.35,1005,38.39,47028,55539,22339,1979,469,543,180200,3761,1154,65,102,233,202,251,249,52,2607,3750,96.87,121,3.13,3807,348,9.14

mqbr-wyyb (1, 157) Census in Colorado 2014

,pop,the_geom,geoname,geonum,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,5197580,"MULTIPOLYGON (((-109.060253 38.599328, -109.05...",Colorado,108,1088602,3605199,198952,28452,143581,5921,7963,118910,2608270,2589310,337435,352695,344661,341735,367651,385593,378791,355630,355020,351550,372616,344010,295848,214879,144269,105138,74722,75337,1234697,509480,36.2,1998314,1282425,715889,560361,155528,2238624,1998314,240310,1295048,703266,3453403,332246,1827473,1293684,59448,73817,31674,1981,848,969,239400,4690377,192391,314812,2212968,2402164,75245,507203,5133849,4139324,497646,257863,203700,35316,2544021,2157410,1907274,250136,82367,70380,11987,33553,76376,27947,166368,2377653,328644,720723,517659,396871,259022,154734,4998019,1388718,88938,70606,279389,275611,271312,325375,77487,3609301,23814,429203,378604,334185,428767,209978,182318,64634,187121,1295048,70143,67138,136423,215484,200845,155554,197540,99600,96774,28641,26906,703266,36922,55774,127783,139089,128861,82817,76375,29764,25881,5079529,663861,1095466,1218579,598714,208902,45544,2.54,295537,188690,185732,176480,160263,204968,263329,180627,112904,119480,110304,5105164,526054,4094922,2811701,2779944,2560703,219241,31757,1283221,5105164

jd2b-7gyb (526, 156) Census Zip Codes in Colorado 2015

,geoid10,hispanic,the_geom,pop,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400T599,r600T799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_p
0,80476,5,MULTIPOLYGON (((-105.92508499987281 39.6794199...,253,247,0,0,0,0,0,1,139,114,10,5,9,11,4,18,14,21,13,34,15,22,19,24,13,21,0,0,31,8,47.0,125,66,59,38,21,206,125,81,87,38,214,4,131,79,46250.0,79167.0,33168.0,1939.0,681.0,863.0,183700.0,250,0,3,87,160,3,3,253,199,34,13,7,0,131,111,107,4,3,3,0,5,9,0,3,128,42,25,20,6,23,12,246,33,3,1,4,7,13,5,0,213,0,7,10,9,10,21,22,0,127,87,0,2,23,27,10,7,5,13,0,0,0,38,0,7,4,17,6,3,0,0,1,249,27,62,27,58,0,3,2.02,13,22,20,12,1,16,8,10,12,11,0,253,16,224,156,156,149,7,0,68,253
1,80477,117,MULTIPOLYGON (((-106.82821600036812 40.4871999...,273,156,0,0,0,0,0,0,158,115,0,0,51,75,0,15,0,29,0,29,12,20,5,0,21,16,0,0,78,48,28.7,93,77,16,16,0,93,93,0,64,29,147,0,61,86,NaN,NaN,46049.0,1949.0,NaN,NaN,847200.0,273,0,0,123,150,0,0,273,185,88,0,0,0,150,32,32,0,77,77,0,33,0,8,0,150,38,27,29,48,8,0,273,78,0,0,0,51,27,0,0,195,0,8,0,37,0,0,0,26,22,64,0,0,0,0,0,0,8,0,17,18,21,29,0,0,0,29,0,0,0,0,0,273,9,9,78,37,0,0,2.94,0,0,8,29,0,0,5,0,10,12,29,273,48,222,150,150,150,0,0,72,273
2,80478,0,MULTIPOLYGON (((-105.91747200043244 40.0054129...,1541,1416,15,0,102,0,0,8,894,647,24,0,41,131,318,139,34,161,41,195,131,100,51,175,0,0,0,0,150,364,36.5,442,282,160,136,24,1120,442,678,382,60,1027,0,532,495,87581.0,88072.0,28960.0,1998.0,NaN,NaN,NaN,1390,8,143,249,1141,0,151,1517,1019,67,112,310,9,1093,964,430,534,6,6,0,0,73,0,50,1043,610,296,36,0,7,94,1517,163,0,0,0,41,91,31,0,1354,35,499,128,39,309,66,0,0,44,382,0,44,0,38,130,0,0,0,128,0,42,60,0,0,0,0,36,0,0,24,0,1541,459,467,150,175,55,0,3.24,82,0,0,51,0,48,160,77,0,24,0,1541,0,1446,1157,1157,1113,44,0,289,1541

wcvg-8vki (526, 73) Census Zip Codes in Colorado 2010

,the_geom,NAME10,ZIPCODE,AREALAND,AREAWATR,INTPTLAT,INTPTLON,POP2010,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_JUVENL,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_R_NOTOCC,V_FORSALE,V_S_NOTOCC,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-105.0089030000001 40.00029000...,ZCTA5 80023,80023,45657286,566048,39.970697,-105.017826,15415,1085,7.04,12744,82.67,142,0.92,31,0.20,1084,7.03,14,0.09,10,0.06,305,1.98,7529,48.84,7886,51.16,1705,11.06,4446,28.84,2741,17.78,39.1,38.5,39.7,5658,4400,3969,431,1258,1037,2.72,356,5302,3.12,0,0,0,0,0,0,0,0,0,0,6024,5658,93.92,366,6.08,5085,89.87,573,10.13,79,3,140,32,71,0,41
1,MULTIPOLYGON (((-104.9270340000001 39.79105400...,ZCTA5 80022,80022,119260445,708605,39.862866,-104.874466,42699,22218,52.03,17689,41.43,1177,2.76,209,0.49,667,1.56,26,0.06,68,0.16,645,1.51,21689,50.80,21010,49.20,3010,7.05,13741,32.18,8486,19.87,30.7,30.7,30.8,13380,10097,7205,2892,3283,2470,3.16,1997,11383,3.61,420,201,0,10,191,0,219,0,0,219,14343,13380,93.29,963,6.71,8855,66.18,4525,33.82,264,17,267,34,33,0,348
2,MULTIPOLYGON (((-104.2651050000001 39.72109500...,ZCTA5 80103,80103,727992115,16612998,39.724905,-104.162592,2458,225,9.15,2136,86.90,24,0.98,22,0.90,10,0.41,2,0.08,1,0.04,38,1.55,1246,50.69,1212,49.31,269,10.94,671,27.30,334,13.59,40.2,40.9,39.7,902,664,542,122,238,196,2.73,78,824,3.20,0,0,0,0,0,0,0,0,0,0,1002,902,90.02,100,9.98,681,75.50,221,24.50,9,1,26,3,9,2,50

In [64]:
print(len(yes))
print(len(no))

71
21

In [67]:
df.head(10)

,the_geom,NAME10,ZIPCODE,AREALAND,AREAWATR,INTPTLAT,INTPTLON,POP2010,HISPANIC,PCT_HISP,WHITE_NH,PCT_WHITE,BLACK_NH,PCT_BLACK,AMERIND_NH,PCT_AMIND,ASIAN_NH,PCT_ASIAN,HAWPAC_NH,PCT_HAWPI,OTHER_NH,PCT_OTHER,MULT_NH,PCT_MULT,MALE,PCT_MALE,FEMALE,PCT_FEM,AGE65PLUS,PCT_65PLUS,AGEUNDER18,PCT_U18,AGEUNDER10,PCT_U10,MED_AGE,MED_MALE,MED_FEMALE,HOUSEHOLDS,FAMILY_HH,HUSB_WIFE,OTH_FAMILY,NON_FAM,HH_ALONE,AVG_HH,HH_W_NONR,HH_N_NONR,AVG_FAM,GQ_POP,GQ_INST,GQ_CORREC,GQ_JUVENL,GQ_NURS,GQ_OT_INST,GQ_NONINST,GQ_COLLEGE,GQ_MILTRY,GQ_O_NONI,HOUSING_UN,OCCUPIED,PCT_OCC,VACANT,PCT_VAC,OWNER,PCT_OWN,RENTER,PCT_RENT,V_FORRENT,V_R_NOTOCC,V_FORSALE,V_S_NOTOCC,V_SEASONAL,V_MIGRANT,V_OTHER
0,MULTIPOLYGON (((-105.0089030000001 40.00029000...,ZCTA5 80023,80023,45657286,566048,39.970697,-105.017826,15415,1085,7.04,12744,82.67,142,0.92,31,0.20,1084,7.03,14,0.09,10,0.06,305,1.98,7529,48.84,7886,51.16,1705,11.06,4446,28.84,2741,17.78,39.1,38.5,39.7,5658,4400,3969,431,1258,1037,2.72,356,5302,3.12,0,0,0,0,0,0,0,0,0,0,6024,5658,93.92,366,6.08,5085,89.87,573,10.13,79,3,140,32,71,0,41
1,MULTIPOLYGON (((-104.9270340000001 39.79105400...,ZCTA5 80022,80022,119260445,708605,39.862866,-104.874466,42699,22218,52.03,17689,41.43,1177,2.76,209,0.49,667,1.56,26,0.06,68,0.16,645,1.51,21689,50.80,21010,49.20,3010,7.05,13741,32.18,8486,19.87,30.7,30.7,30.8,13380,10097,7205,2892,3283,2470,3.16,1997,11383,3.61,420,201,0,10,191,0,219,0,0,219,14343,13380,93.29,963,6.71,8855,66.18,4525,33.82,264,17,267,34,33,0,348
2,MULTIPOLYGON (((-104.2651050000001 39.72109500...,ZCTA5 80103,80103,727992115,16612998,39.724905,-104.162592,2458,225,9.15,2136,86.90,24,0.98,22,0.90,10,0.41,2,0.08,1,0.04,38,1.55,1246,50.69,1212,49.31,269,10.94,671,27.30,334,13.59,40.2,40.9,39.7,902,664,542,122,238,196,2.73,78,824,3.20,0,0,0,0,0,0,0,0,0,0,1002,902,90.02,100,9.98,681,75.50,221,24.50,9,1,26,3,9,2,50
3,MULTIPOLYGON (((-103.8916620000001 39.86975200...,ZCTA5 80701,80701,1573752900,5996004,40.236980,-103.807123,16042,6190,38.59,8833,55.06,689,4.29,57,0.36,101,0.63,7,0.04,19,0.12,146,0.91,8023,50.01,8019,49.99,2042,12.73,4684,29.20,2669,16.64,33.6,32.8,34.5,5718,4055,3052,1003,1663,1390,2.77,582,5136,3.30,191,176,98,0,78,0,15,0,0,15,6180,5718,92.52,462,7.48,3693,64.59,2025,35.41,175,7,82,5,45,5,143
4,MULTIPOLYGON (((-104.8469320000001 39.75488900...,ZCTA5 80010,80010,14283218,31534,39.739249,-104.864054,39728,22817,57.43,8757,22.04,5482,13.80,241,0.61,1339,3.37,113,0.28,69,0.17,910,2.29,21035,52.95,18693,47.05,2830,7.12,12197,30.70,7620,19.18,29.6,29.8,29.5,12767,8208,4925,3283,4559,3413,3.02,2465,10302,3.73,1143,826,429,27,370,0,317,0,0,317,14334,12767,89.07,1567,10.93,4693,36.76,8074,63.24,934,23,235,13,21,0,341
5,MULTIPOLYGON (((-106.03933900000011 37.4623490...,ZCTA5 81101,81101,1060256710,1615149,37.476233,-105.819178,14675,6997,47.68,7040,47.97,137,0.93,130,0.89,125,0.85,6,0.04,29,0.20,211,1.44,7356,50.13,7319,49.87,1643,11.20,3625,24.70,2160,14.72,32.3,31.3,33.6,5668,3568,2511,1057,2100,1720,2.46,669,4999,3.08,740,276,227,0,49,0,464,407,0,57,6133,5668,92.42,465,7.58,3388,59.77,2280,40.23,141,8,53,28,95,6,134
6,MULTIPOLYGON (((-104.8314850000001 39.67491300...,ZCTA5 80012,80012,20111206,0,39.700204,-104.837528,46665,15512,33.24,17133,36.71,9922,21.26,221,0.47,2216,4.75,138,0.30,92,0.20,1431,3.07,23038,49.37,23627,50.63,4790,10.26,12345,26.45,7422,15.90,32.8,31.7,34.0,18115,11043,6951,4092,7072,5754,2.56,2517,15598,3.27,302,273,18,65,190,0,29,0,0,29,19634,18115,92.26,1519,7.74,8916,49.22,9199,50.78,737,23,247,28,30,0,454
7,MULTIPOLYGON (((-104.8099460000001 39.66584500...,ZCTA5 80013,80013,36229567,0,39.659591,-104.775014,69588,12672,18.21,40506,58.21,8762,12.59,340,0.49,4415,6.34,220,0.32,130,0.19,2543,3.65,34426,49.47,35162,50.53,4137,5.94,19626,28.20,10870,15.62,33.6,32.9,34.4,24791,18148,13539,4609,6643,5138,2.81,2983,21808,3.26,26,0,0,0,0,0,26,0,0,26,26047,24791,95.18,1256,4.82,18492,74.59,6299,25.41,492,23,404,62,34,0,241
8,MULTIPOLYGON (((-102.3282360000001 37.55727400...,ZCTA5 81084,81084,623875684,5021405,37.585812,-102.428252,137,14,10.22,122,89.05,0,0.00,1,0.73,0,0.00,0,0.00,0,0.00,0,0.00,76,55.47,61,44.53,34,24.82,25,18.25,13,9.49,49.5,52.0,47.8,65,39,36,3,26,26,2.11,1,64,2.82,0,0,0,0,0,0,0,0,0,0,98,65,66.33,33,33.67,47,72.31,18,27.69,1,0,0,3,1,0,28
9,MULTIPOLYGON (((-105.92828300000009 37.2685300...,ZCTA5 81151,81151,580586512,599956,37.201657,-105.680782,1470,540,36.73,899,61.16,2,0.14,13,0.88,1,0.07,0,0.00,2,0.14,13,0.88,731,49.73,739,50.27,202,13.74,463,31.50,268,18.23,34.4,35.7,32.4,528,394,311,83,134,123,2.78,31,497,3.30,0,0,0,0,0,0,0,0,0,0,656,528,80.49,128,19.51,420,79.55,108,20.45,4,0,4,3,37,0,80

In [117]:
ids = []
names = []
shapes = []
datadict = []


for id,dct in data.items():
    print(id,dct["name"],dct["shape"])
    ids.append(id)
    names.append(dct["name"])
    shapes.append(dct["shape"])
    datadict.append(dct["data"])

n53p-giqe Census Places in Colorado 2012 (455, 157)
gu6r-zvv2 Census Tracts in Colorado 2010 (1249, 77)
sn6p-34bq Census Counties in Colorado 2016 (64, 157)
9cn8-g4er Census Places in Colorado 2014 (458, 157)
gafi-svtb Census Congressional Districts in Colorado 2014 (7, 156)
qx2d-46a5 Census Core Based Statistical Area in Colorado 2011 (14, 271)
khe9-7d2c Census Zip Codes SF1 in Colorado 2000 (483, 70)
v56b-yh3u Census Core Based Statistical Area in Colorado 2012 (14, 325)
mxmm-svgz Census County Subdivisions in Colorado 2012 (209, 331)
f3th-4ste Census County Subdivisions SF3 in Colorado 2000 (208, 104)
9gri-r239 Census Block Groups in Colorado 2013 (3532, 157)
22bw-ijyi Census ACS Counties in Colorado 2011 (64, 275)
37uc-bdj5 Census Zip Codes in Colorado 2012 (526, 156)
xymp-u28i Census Counties in Colorado 2013 (64, 157)
xxfz-y2eq Census in Colorado 2015 (1, 157)
wtpp-eaj8 Census Counties in Colorado 2010 (64, 76)
nnpy-czzx Census County Subdivisions SF1 in Colorado 2000 (208, 73)
jjnc-cu9z Census Block Groups in Colorado 2012 (3532, 157)
fifs-d43p Census Tracts in Colorado 2014 (1249, 157)
v5m6-vhha Census State of Colorado 2013 (1, 157)
c6qj-6kx2 Census Places SF1 in Colorado 2000 (354, 72)
xipb-k5bu Census Blocks in Colorado 2010 (201062, 80)
94t6-d4wd Census Core Based Statistical Area in Colorado 2010 (14, 76)
us3j-cyz6 Census Block Groups SF3 in Colorado 2000 (3278, 102)
hcfi-bvst Census Places in Colorado 2010 (458, 75)
3ftn-9s6k Census Zip Codes in Colorado 2013 (526, 156)
cuid-432h Census State SF1 in Colorado 2000 (1, 73)
xh4c-32wb Census Tracts in Colorado 2011 (1249, 270)
jc8p-yc8f Census Tracts in Colorado 2015 (1249, 157)
2chb-kzb6 Census Places in Colorado 2016 (458, 157)
9b7x-qm8d Census School Districts in Colorado 2010 (178, 76)
sdgy-egf7 Census Combined Statistical Area in Colorado 2011 (1, 269)
2ddb-srxn Census Combined Statistical Area in Colorado 2012 (1, 323)
7yta-8qvv Census Places SF3 in Colorado 2000 (354, 105)
fjhv-ruxa Census State SF3 in Colorado 2000 (1, 100)
tfrg-b5pp Census Tracts in Colorado 2016 (1249, 157)
t3uw-qtqc Census Places in Colorado 2015 (458, 157)
fr27-d5rz Census State in Colorado 2012 (1, 157)
232d-4jxg Census Tracts in Colorado 2013 (1249, 157)
f8ak-7nmp Census Counties in Colorado 2014 (64, 157)
xwky-bmsn Census Counties in Colorado 2012 (64, 157)
5yyk-mqmn Census Counties in Colorado 2015 (64, 157)
xg8m-4prc Census School Districts in Colorado 2012 (178, 327)
33fk-kb5q Census Combined Statistical Area in Colorado 2010 (1, 75)
p562-ke9a Census School Districts in Colorado 2011 (178, 273)
3djr-p9q9 Census Congressional Districts in Colorado 2015 (7, 156)
rntb-5cdp Census State in Colorado 2011 (1, 272)
6gtx-i289 Census County Subdivisions in Colorado 2011 (209, 277)
gvnt-p2w8 Census Counties SF3 in Colorado 2000 (63, 102)
yqfw-dg5f Census Tracts in Colorado 2012 (1249, 157)
x5e5-npqm Census State in Colorado 2010 (1, 78)
8vnm-57r6 Census Tracts SF1 in Colorado 2000 (1062, 73)
nbfg-y9mh Census Block Groups SF1 in Colorado 2000 (3278, 73)
6fg8-f8c5 Census Congressional Districts in Colorado 2016 (7, 156)
hxnu-kp2f Census County Subdivisions in Colorado 2010 (209, 76)
6hee-tnp6 Census Block Groups in Colorado 2015 (3532, 157)
kfm9-mvzv Census Block Groups in Colorado 2010 (3532, 77)
ueer-yycc Census Places in Colorado 2011 (458, 275)
7m6d-cpmt Census in Colorado 2016 (1, 157)
r87x-h98m Census Blocks in Colorado 2000 (141040, 75)
4zf4-r52a Census Places in Colorado 2013 (458, 157)
v4w4-3yz8 Census Counties SF1 in Colorado 2000 (63, 72)
6ddv-3hk2 Census Block Groups in Colorado 2011 (3532, 267)
ty6r-gpdz Census Congressional Districts in Colorado 2013 (7, 156)
iku4-4bpx Census Block Groups in Colorado 2016 (3532, 157)
cmkv-zd4f Census Block Groups in Colorado 2014 (3532, 157)
bd44-na6d Census Zip Codes SF3 in Colorado 2000 (483, 98)
p674-r4hf Census Tracts SF3 in Colorado 2000 (1062, 101)
mqbr-wyyb Census in Colorado 2014 (1, 157)
jd2b-7gyb Census Zip Codes in Colorado 2015 (526, 156)
wcvg-8vki Census Zip Codes in Colorado 2010 (526, 73)

In [119]:
newdf = pd.DataFrame(
    {"s4x4":ids,
    "name":names,
    "shape":shapes,
    "data":datadict})

In [22]:
newdf.to_csv("census_summary.csv")

NameError: name 'newdf' is not defined

In [ ]:
for index,row in newdf.iterrows():
    print(row["data"].head())

In [96]:
test = pd.DataFrame(data)

In [97]:
test.to_csv("census_summary.csv")

In [29]:
pd.read_csv("https://data.colorado.gov/api/views/ph72-axst/rows.csv?accessType=DOWNLOAD")

,the_geom,geoname,geonum,pop,hispanic,white_nh,black_nh,ntvam_nh,asian_nh,hawpi_nh,other_nh,twoplus_nh,male,female,ageless5,age5_9,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,age50_54,age55_59,age60_64,age65_69,age70_74,age75_79,age80_84,age85pl,ageless18,age18_24,med_age,households,familyhh,nonfamhh,hhldralone,hhldr_naln,housing_un,occ_hu,vac_hu,owned,rented,pop25plus,nohsdipl,hsgrad_sc,bachl_hghr,med_hh_inc,med_fam_in,per_cap_in,med_yr_blt,med_c_rent,med_g_rent,med_hm_val,citz_birth,citz_nat,not_citz,born_in_co,brn_oth_st,ntv_b_o_us,foreign_b,pop_1p,same_house,same_cnty,same_state,diff_state,frm_abroad,wrkrs_16pl,car_all,car_alone,car_carpoo,public_trn,pt_bus,pt_other,bike,walk,tr_other,wrk_home,w_16pl_nh,t_less_10,t_10_19,t_20_29,t_30_39,t_40_59,t_60_pl,pop_3pl,enrolled,preschool,kndrgrtn,gr_1_4,gr_5_8,gr_9_12,undergrad,grad_prof,n_enrolled,blt_2010_p,b2000_2009,b1990_1999,b1980_1989,b1970_1979,b1960_1969,b1950_1959,b1940_1949,b1939_e,own_occ_hu,v_l_50k,v50k_100k,v100k_150k,v150k_200k,v200k_250k,v250k_300k,v300k_400k,v400k_500k,v500k_750k,v750k_1m,v_1m_plus,rnt_occ_hu,rntl400,r400t599,r600t799,r800t999,r1000t1249,r1250t1499,r1500t1999,r2000pl,rnocshr,ps_uni,ps_below,ps_bel150,tot_l18,puni_65pl,pov_l18,pov_65pl,avghhsize,hhi_l20k,hhi20_30,hhi30_40,hhi40_50,hhi50_60,hhi60_75,hhi75_100,hhi100_125,hhi125_150,hhi150_200,hhi200_pl,civ_ni_pop,disabled,pop16_pls,laborforce,civ_lf,emp,unemp,armedfrcs,not_lf,civ_ni_
0,"MULTIPOLYGON (((-109.060253 38.599328, -109.05...",Colorado,108,5531141,1184794,3778212,216732,30131,169556,7480,10352,133884,2780831,2750310,335199,355399,359334,354630,377987,426632,422525,390194,359083,357390,357964,363001,331165,268440,187391,121791,79953,83063,1259819,522730,36.6,2113387,1351683,761704,578532,183172,2352202,2113387,238815,1371145,742242,3748592,322718,1920982,1504892,68811,84540,36415,1983,1078,1196,313600,4988164,224034,318943,2351275,2551674,85215,542977,5467766,4464444,467576,275839,225216,34691,2822072,2374938,2125477,249461,86516,67401,19115,33829,80354,28221,218214,2603858,326205,757858,571526,453440,309029,185800,5331855,1396806,88085,70447,284619,284891,284520,306341,77903,3935049,124974,424374,392256,341166,437144,204884,179513,63720,184171,1371145,55833,49731,79507,141644,161206,160409,274043,177995,176206,53332,41239,742242,34250,33472,75720,108504,136174,117297,142127,69793,24905,5409817,590504,990886,1242689,725423,168248,54227,2.56,254215,165261,175957,168560,163943,212739,288416,212974,145127,159913,166282,5439267,575430,4409148,3012312,2978700,2839374,139326,33612,1396836,5439267

In [34]:
from itables import init_notebook_mode
init_notebook_mode(all_interactive=True)

In [23]:
df = pd.read_csv("census_summary.csv")

In [24]:
df.head(100)

,Unnamed: 0,s4x4,name,shape,data
0,0,n53p-giqe,Census Places in Colorado 2012,"(455, 157)",th...
1,1,gu6r-zvv2,Census Tracts in Colorado 2010,"(1249, 77)",th...
2,2,sn6p-34bq,Census Counties in Colorado 2016,"(64, 157)",pop ...
3,3,9cn8-g4er,Census Places in Colorado 2014,"(458, 157)",geonum ...
4,4,gafi-svtb,Census Congressional Districts in Colorado 2014,"(7, 156)",pop hispanic ...
5,5,qx2d-46a5,Census Core Based Statistical Area in Colorado...,"(14, 271)",th...
6,6,khe9-7d2c,Census Zip Codes SF1 in Colorado 2000,"(483, 70)",th...
7,7,v56b-yh3u,Census Core Based Statistical Area in Colorado...,"(14, 325)",th...
8,8,mxmm-svgz,Census County Subdivisions in Colorado 2012,"(209, 331)",th...
9,9,f3th-4ste,Census County Subdivisions SF3 in Colorado 2000,"(208, 104)",th...
10,10,9gri-r239,Census Block Groups in Colorado 2013,"(3532, 157)",g...
11,11,22bw-ijyi,Census ACS Counties in Colorado 2011,"(64, 275)",th...
12,12,37uc-bdj5,Census Zip Codes in Colorado 2012,"(526, 156)",geoid10 hispanic ...
13,13,xymp-u28i,Census Counties in Colorado 2013,"(64, 157)",pop ...
14,14,xxfz-y2eq,Census in Colorado 2015,"(1, 157)",pop geoname ...
15,15,wtpp-eaj8,Census Counties in Colorado 2010,"(64, 76)",th...
16,16,nnpy-czzx,Census County Subdivisions SF1 in Colorado 2000,"(208, 73)",th...
17,17,jjnc-cu9z,Census Block Groups in Colorado 2012,"(3532, 157)",th...
18,18,fifs-d43p,Census Tracts in Colorado 2014,"(1249, 157)",geonum geoname pop \\n0 10804900...
19,19,v5m6-vhha,Census State of Colorado 2013,"(1, 157)",geonum geoname pop \\n0 108 Co...
20,20,c6qj-6kx2,Census Places SF1 in Colorado 2000,"(354, 72)",th...
21,21,xipb-k5bu,Census Blocks in Colorado 2010,"(201062, 80)",th...
22,22,94t6-d4wd,Census Core Based Statistical Area in Colorado...,"(14, 76)",th...
23,23,us3j-cyz6,Census Block Groups SF3 in Colorado 2000,"(3278, 102)",th...
24,24,hcfi-bvst,Census Places in Colorado 2010,"(458, 75)",th...
25,25,3ftn-9s6k,Census Zip Codes in Colorado 2013,"(526, 156)",th...
26,26,cuid-432h,Census State SF1 in Colorado 2000,"(1, 73)",th...
27,27,xh4c-32wb,Census Tracts in Colorado 2011,"(1249, 270)",th...
28,28,jc8p-yc8f,Census Tracts in Colorado 2015,"(1249, 157)",geoname ...
29,29,2chb-kzb6,Census Places in Colorado 2016,"(458, 157)",pop ...
30,30,9b7x-qm8d,Census School Districts in Colorado 2010,"(178, 76)",th...
31,31,sdgy-egf7,Census Combined Statistical Area in Colorado 2011,"(1, 269)",th...
32,32,2ddb-srxn,Census Combined Statistical Area in Colorado 2012,"(1, 323)",th...
33,33,7yta-8qvv,Census Places SF3 in Colorado 2000,"(354, 105)",th...
34,34,fjhv-ruxa,Census State SF3 in Colorado 2000,"(1, 100)",th...
35,35,tfrg-b5pp,Census Tracts in Colorado 2016,"(1249, 157)",geonum pop geoname \\n0 10800100...
36,36,t3uw-qtqc,Census Places in Colorado 2015,"(458, 157)",th...
37,37,fr27-d5rz,Census State in Colorado 2012,"(1, 157)",pop geonum ...
38,38,232d-4jxg,Census Tracts in Colorado 2013,"(1249, 157)",geonum ...
39,39,f8ak-7nmp,Census Counties in Colorado 2014,"(64, 157)",pop ...
40,40,xwky-bmsn,Census Counties in Colorado 2012,"(64, 157)",th...
41,41,5yyk-mqmn,Census Counties in Colorado 2015,"(64, 157)",th...
42,42,xg8m-4prc,Census School Districts in Colorado 2012,"(178, 327)",th...
43,43,33fk-kb5q,Census Combined Statistical Area in Colorado 2010,"(1, 75)",th...
44,44,p562-ke9a,Census School Districts in Colorado 2011,"(178, 273)",th...
45,45,3djr-p9q9,Census Congressional Districts in Colorado 2015,"(7, 156)",th...
46,46,rntb-5cdp,Census State in Colorado 2011,"(1, 272)",th...
47,47,6gtx-i289,Census County Subdivisions in Colorado 2011,"(209, 277)",th...
48,48,gvnt-p2w8,Census Counties SF3 in Colorado 2000,"(63, 102)",th...
49,49,yqfw-dg5f,Census Tracts in Colorado 2012,"(1249, 157)",pop ...
50,50,x5e5-npqm,Census State in Colorado 2010,"(1, 78)",th...
51,51,8vnm-57r6,Census Tracts SF1 in Colorado 2000,"(1062, 73)",th...
52,52,nbfg-y9mh,Census Block Groups SF1 in Colorado 2000,"(3278, 73)",th...
53,53,6fg8-f8c5,Census Congressional Districts in Colorado 2016,"(7, 156)",pop hispanic con_dist \\n0 786253 ...
54,54,hxnu-kp2f,Census County Subdivisions in Colorado 2010,"(209, 76)",th...
55,55,6hee-tnp6,Census Block Groups in Colorado 2015,"(3532, 157)",pop ...
56,56,kfm9-mvzv,Census Block Groups in Colorado 2010,"(3532, 77)",th...
57,57,ueer-yycc,Census Places in Colorado 2011,"(458, 275)",th...
58,58,7m6d-cpmt,Census in Colorado 2016,"(1, 157)",th...
59,59,r87x-h98m,Census Blocks in Colorado 2000,"(141040, 75)",th...
60,60,4zf4-r52a,Census Places in Colorado 2013,"(458, 157)",geoname geonum pop \\...
61,61,v4w4-3yz8,Census Counties SF1 in Colorado 2000,"(63, 72)",th...
62,62,6ddv-3hk2,Census Block Groups in Colorado 2011,"(3532, 267)",th...
63,63,ty6r-gpdz,Census Congressional Districts in Colorado 2013,"(7, 156)",pop con_dist hispanic \\n0 740254 ...
64,64,iku4-4bpx,Census Block Groups in Colorado 2016,"(3532, 157)",th...
65,65,cmkv-zd4f,Census Block Groups in Colorado 2014,"(3532, 157)",th...
66,66,bd44-na6d,Census Zip Codes SF3 in Colorado 2000,"(483, 98)",th...
67,67,p674-r4hf,Census Tracts SF3 in Colorado 2000,"(1062, 101)",th...
68,68,mqbr-wyyb,Census in Colorado 2014,"(1, 157)",pop ...
69,69,jd2b-7gyb,Census Zip Codes in Colorado 2015,"(526, 156)",geoid10 hispanic ...
70,70,wcvg-8vki,Census Zip Codes in Colorado 2010,"(526, 73)",th...

In [25]:
df.shape

(71, 5)

In [38]:
ans = True
while ans :
    ans = input("enter 4x4 to remove")

enter 4x4 to remove 4x42
enter 4x4 to remove False
enter 4x4 to remove

In [29]:
df.columns

RangeIndex(start=0, stop=71, step=1)

In [26]:
df.columns = ["Name","Shape","Data"]

ValueError: Length mismatch: Expected axis has 71 elements, new values have 3 elements

In [112]:
df["Data"].head()

Unnamed: 0                                                 data
n53p-giqe                                                 th...
gu6r-zvv2                                                 th...
sn6p-34bq           pop                                     ...
9cn8-g4er          geonum                                   ...
Name: Data, dtype: object

In [30]:
yes

[]

In [54]:
def getFields(w4x4=""):
    '''Reads the Inventory google sheet and getsthe fields by 4x4 dataset id and by the title'''
    bic_etl_home = os.getenv('bic_etl_home')
    print("------------")
    print("Get Fields starting",bic_etl_home)
    print("------------")

## Add the bic_etl/general/script directory to path 
    sys.path.insert(0, os.path.join(bic_etl_home, 'general', 'scripts'))

    SERVICE_ACCOUNT_FILE = os.path.join("/home","joe", 'work',"client_secret.json")
    print(SERVICE_ACCOUNT_FILE)
    scope = ['https://www.googleapis.com/auth/spreadsheets.readonly',
             "https://www.googleapis.com/auth/drive"]

    creds = ServiceAccountCredentials.from_json_keyfile_name(SERVICE_ACCOUNT_FILE,
     scope)
    client = gspread.authorize(creds)

    fields_sheet = client.open('BIC Data Inventory and Metadata').worksheet(
        'MetadataRepository')
    
    print("field sheet",fields_sheet)

    dfFields = pd.DataFrame(fields_sheet.get_all_records(head=3))
    
    fields = {}
    for index,row in dfFields.iterrows():
        s4x4 = row["Socrata Link"].strip()
        a4x4 = row["API 4x4"].strip()
        fields[s4x4] = a4x4
  
    return fields

fields = getFields()

------------
Get Fields starting /home/joe/bic_etl
------------
/home/joe/work/client_secret.json
field sheet <Worksheet 'MetadataRepository' id:323813469>

In [55]:
fields

{'rifs-n6ib': 'rifs-n6ib',
 'c8jj-hcxj': 'nigi-mnyx',
 '82s5-cpkk': '82s5-cpkk',
 'n55r-9hud': 'n55r-9hud',
 'ms6b-y4xc': 'ms6b-y4xc',
 'e6e8-qmi7': 'px7t-j3xt',
 'hxf8-ab6k': 'yt5k-hawq',
 'p8m4-v33g': 'vgwh-ygn3',
 'g53r-j5td': '6pd5-jdur',
 'jnj7-fw37': 'jnj7-fw37',
 'gyeb-jc69': '9gxp-sqz6',
 'u2t6-bfhr': 'iw7e-tqkz',
 'cjkq-q9ih': 'iaz7-gn2p',
 '4e3w-qire': 'da3r-y7xz',
 'busm-qa5b': 'vu7j-izta',
 '2cpa-vbur': 'udxx-a7kq',
 'bu8h-8sux': 'suda-myfn',
 'pt2g-89wc': '7rd3-4hgz',
 'bynd-i2hj': 'cy35-ndjp',
 'k3gg-hhc8': 'k3gg-hhc8',
 'x8tb-f3vh': 'x8tb-f3vh',
 '2yhn-3dbj': '2yhn-3dbj',
 '6kn4-89kh': '6kn4-89kh',
 '869n-zj3f': '869n-zj3f',
 'sqs8-2un5': 'sqs8-2un5',
 '3sm5-jtur': '3sm5-jtur',
 'ehk3-i5tr': 'ehk3-i5tr',
 'v9m8-x8dh': 'v9m8-x8dh',
 'j7a3-jgd3': 'j7a3-jgd3',
 'kapc-ib6e': 'ii5c-5549',
 'htyp-tqzh': 'htyp-tqzh',
 'ier5-5ms2': 'ier5-5ms2',
 'pwjb-9dd5': 'pwjb-9dd5',
 '9pwz-gi5v': 'ic4i-9zku',
 'd4s4-xqg6': '394i-tr5f',
 'msap-49q7': 'msap-49q7',
 'wz8h-dap6': 'wz8h-dap6',
 'g62i-kdzu': 'g62i-kdzu',
 'ifza-iedd': 'ifza-iedd',
 'y6w6-igw6': 'y6w6-igw6',
 'hysf-mrke': 'hysf-mrke',
 'n9gj-cjub': 'n9gj-cjub',
 'qtga-qgdf': 'qtga-qgdf',
 's9wt-dsfz': 's9wt-dsfz',
 'xi27-7j3e': 'xi27-7j3e',
 '6ntv-x37b': '6ntv-x37b',
 'd6t8-xish': 'tkre-uiwn',
 'hbkb-4hbj': 'pij9-wuvb',
 'pdd3-umrz': '35ps-yuib',
 'rjvq-j29g': 'kq2r-s8hw',
 'fe4v-h3pk': 'smy5-uetg',
 'ax6t-kdim': 'qzw4-fgg6',
 'h5yt-egtp': 'tzjn-r68r',
 'kch9-6p6i': 'd2hz-7rd9',
 'nd6a-59yu': 'jkz5-7nit',
 'wx84-he7r': 'trzr-qjr4',
 '4zse-6bnw': 'qzbt-feti',
 'e7wz-djhw': 'e7wz-djhw',
 '34aw-ny67': '34aw-ny67',
 'k4uv-yvnk': 'ubw3-w6rt',
 'tuvj-xz3m': 'tuvj-xz3m',
 's7ct-nf65': '3ck3-ek9d',
 '35k5-cv8s': 'dm35-83um',
 'bqa5-gr84': '4xaw-3ja7',
 'eqsm-7ah7': 'wkgc-9sne',
 'g89g-muvw': 'kr2z-56yf',
 'gcmk-9nwy': '37vx-jsnr',
 'gxnn-wthy': 'a2bk-zr8i',
 'casm-dbbj': 'hu3b-43c7',
 '2z9k-uy4q': 'pg4y-bhfp',
 '5wyf-xqw7': 'aatx-m2pf',
 'ew9y-6tv9': 'nj9v-fjwa',
 'w6kb-3vsj': 'duaz-bid8',
 'wwhd-vg25': '5kgu-ujzf',
 'fdcw-ei67': 'ymw6-c5vm',
 '37wu-kn3g': 'p3jp-z4tq',
 '7jm9-f28m': 'yvrn-kew4',
 'hyr8-d3v9': 'aaag-hy62',
 'mr4v-jz8u': 'vjpn-wxi8',
 '3qtu-edua': '26xp-8dwd',
 'q2av-rpr5': '9rpm-ca44',
 'wwbh-7bpa': 'i3cf-f6qs',
 'icqv-mi3c': 'j6pz-h6b7',
 'd3m2-b6we': '32mi-brje',
 'ej2c-jkvh': 'h28s-f3n9',
 'u7sb-g482': 'bhcc-9bdx',
 'x5bw-ax3d': 'wj25-kxs8',
 'q2qp-xhnj': 'rk4k-4n2k',
 'n5ku-eixc': 'n5ku-eixc',
 'rkmy-yymq': 'rkmy-yymq',
 '2kvt-7ybu': '2kvt-7ybu',
 '7nuk-vzhq': 'g749-y462',
 'dnyf-3m59': 'ibqw-39av',
 'ihbp-hi2s': 'kp53-5p45',
 '7bzf-viss': 'py3d-8rcb',
 '67vn-ijga': 'ahgn-r8s5',
 'gemu-wyf3': 'whvu-66s7',
 '9syq-9vv5': 'xv9c-7iqh',
 'trm9-dm4m': '2ivx-wb7h',
 '49ck-u67r': 'bw7c-66ew',
 'uhup-hcc4': 'k5jg-kjbh',
 'd6bh-7i9s': '4rpn-vqpu',
 '7amf-p4uj': 'q2m8-2gk3',
 'skxn-j975': 'skxn-j975',
 'xs2v-uzeg': 'i7qk-ahka',
 '6aqe-63uq': '6aqe-63uq',
 '4h6z-rhfw': '4hz3-qup8',
 '3bgg-gcfa': 'sms6-dzsz',
 'ue4w-dnyi': 'ue4w-dnyi',
 '4vf9-vbyi': '4vf9-vbyi',
 '56kc-gpid': '56kc-gpid',
 'fbn4-ype4': 'fbn4-ype4',
 '2h6w-z9ry': 'phvc-rwei',
 '7sv7-7d5a': 'ddci-aui8',
 'uksn-8qya': 'fv4u-jgb3',
 'qvrk-xsmj': 'nxhx-5jh3',
 'e7ye-tasg': 'ah2h-6fx9',
 '8hx8-24k6': 'meem-5sxj',
 't8ag-kzkw': '3p4c-fm5u',
 'sfvq-tb9q': 'fsyh-pm89',
 'mguq-rjzb': '9mid-gqwm',
 'hpem-wb68': '2tib-gtif',
 'j8pu-22qi': 'ywaw-cfpm',
 'cdva-fnp3': 'df48-rqfu',
 'gi9w-h59d': 'dgjp-iua8',
 'nbem-wipy': 'ezkd-u92f',
 '9ghp-7fx6': '36jf-z7v4',
 'uiuh-m69w': 'vigw-75nf',
 'dx5q-y5je': 'iqyg-cdrz',
 '3b56-km3g': '3b56-km3g',
 'x5dz-rik8': 'x5dz-rik8',
 'uzf4-3qtt': 'uzf4-3qtt',
 'bk6n-e4g7': 'bk6n-e4g7',
 '4j38-u7sj': '4j38-u7sj',
 'emmy-a4kg': 'neii-3ga4',
 'vqzj-5nyt': '2jqz-wx74',
 'gh3v-k494': '8i9r-ecqh',
 '4qh9-evw6': 'sb9m-ecvv',
 'x238-vje7': 'sqxp-g37g',
 'inae-mki6': 'inae-mki6',
 'hwz6-96jc': '',
 'j6g4-gayk': 'j6g4-gayk',
 '6vnq-az4b': '6vnq-az4b',
 '2e5i-5hfy': 'ci9y-twe5',
 'ya69-n6ta': 'fc73-cgrc',
 'nymn-sjs9': 'nxsb-d2uu',
 'et6s-ufjm': '4y5q-y4pt',
 'uir2-bpe7': 'nbrq-f8ym',
 'itzi-4q6v': 'xxgw-kkry',
 'q2iw-kpix': 'q2iw-kpix',
 '7s5z-vewr': 'idu3-cuww',
 '3kjc-z9fd': '3kjc-z9fd',
 'mqid-8hv2': 'auv6-u3qc',
 'ffjg-bf34': 'ffjg-bf34',
 'iuxm-ddzz': 'iuxm-ddzz',
 'bjhg-77mf': 'bjhg-77mf',
 'ucnv-vw74': 'ucnv-vw74',
 '86h6-mdkh': '86h6-mdkh',
 'tbmm-ubn9': 'tbmm-ubn9',
 'q56w-zzzm': 'q56w-zzzm',
 'ph72-axst': 'ph72-axst',
 'smjm-6h6g': 'smjm-6h6g',
 'ekih-pydt': 'ekih-pydt',
 'ge9s-ra8y': 'ge9s-ra8y',
 'spwe-6ca7': 'spwe-6ca7',
 'jwbw-xb7i': 'jwbw-xb7i',
 'qjuy-fmh4': 'qjuy-fmh4',
 'cj4m-96y8': 'cj4m-96y8',
 '7t53-5gfx': '7t53-5gfx',
 'xum2-smvh': 'xum2-smvh',
 '8j3i-rjn4': '8j3i-rjn4',
 'rt7b-823p': 'rt7b-823p',
 't2jr-8j7z': 't2jr-8j7z',
 'xpi4-stak': 'xpi4-stak',
 '33q3-djk8': '33q3-djk8',
 'g598-t929': 'g598-t929',
 '3u6n-menq': '3u6n-menq',
 'jycn-t6wi': 'jycn-t6wi',
 '7i2s-r6pd': '7i2s-r6pd',
 'aevh-apr2': 'aevh-apr2',
 'ewkj-ipn7': 'ewkj-ipn7',
 'ty5m-9xub': 'ty5m-9xub',
 'qten-sdpn': 'qten-sdpn',
 'vcag-iwy7': 'vcag-iwy7',
 'mqbr-wyyb': 'wwwp-4j5y',
 '7m6d-cpmt': 'grnx-2zwm',
 'ab5h-juwk': 'tz69-nqfv',
 'wv7f-qjj7': 'tek5-fkv6',
 'rwak-e74e': '55mv-2ynf',
 'v4as-sthd': '3wx6-h3cs',
 'ty6r-gpdz': 'kchu-pwtk',
 'gafi-svtb': 's35f-5c94',
 '3djr-p9q9': 'tukx-q8v8',
 '6fg8-f8c5': 'jz4n-qus2',
 '2chb-kzb6': 'mwv9-ygsf',
 'iku4-4bpx': '594w-hhep',
 'sn6p-34bq': 'eghh-ua8y',
 'tfrg-b5pp': 'umwy-67rm',
 '37uc-bdj5': 'fcyp-mtss',
 '3ftn-9s6k': '3yjp-6a33',
 'jd2b-7gyb': 'v6qp-6csn',
 'chpv-m4xq': 've36-qdic',
 'tn2f-pf3u': 'ue2w-bebj',
 '232d-4jxg': 'bxxi-pypt',
 '4zf4-r52a': 'vdki-aa5n',
 '9gri-r239': 'muph-8jnm',
 'v5m6-vhha': '8hh9-tn7j',
 'xymp-u28i': 'm3j7-raj9',
 '5yyk-mqmn': 't48m-528x',
 '6hee-tnp6': 'rz4c-na6y',
 'jc8p-yc8f': 'ws3z-urxq',
 't3uw-qtqc': 'gtau-pbhu',
 'xxfz-y2eq': '7e99-m9fd',
 '2p2k-iq7f': 's28a-3huk',
 'chnk-j6e5': 'r5py-vgrn',
 'cmr9-ue2w': 'yifv-9mje',
 'hwir-8ay9': 'ufkp-k5vs',
 'ixu8-bvqa': 'g6ci-vc3b',
 'mvn7-a28c': 'qwt4-f2pv',
 '9cn8-g4er': 'n5xr-summ',
 'f8ak-7nmp': 'wshk-29g7',
 'fifs-d43p': 'dwez-qzwp',
 'vne4-cwmy': '4t5f-mp2t',
 'cmkv-zd4f': 'adbb-iu37',
 '3thw-b7wj': '7myi-3bh6',
 '853a-s2qz': '5ku5-3ak6',
 '9h8i-6khx': 'q8mv-cahs',
 'd6bs-3kgu': 'rkr9-nd87',
 'dm2a-biqr': '7rar-v5z8',
 'esrk-9vjd': 'mm2p-ag5w',
 'fwb5-rzg5': '2h36-cxjh',
 'knbf-ggf2': '6mdp-xw2u',
 'ua3v-vcuh': '9s32-6t85',
 'wxzv-xh9i': 'nq9j-ybu4',
 '2ddb-srxn': 'a5gi-9pma',
 'fr27-d5rz': 'vx8e-g83x',
 'n53p-giqe': 'kt3p-393c',
 'p562-ke9a': 'k2sh-64zx',
 'qx2d-46a5': 'a85s-zxvh',
 'rntb-5cdp': '2rrq-heiy',
 'sdgy-egf7': 'rxks-zb9z',
 'ueer-yycc': 'rue4-ebee',
 'v56b-yh3u': 'kd4i-r65w',
 'xg8m-4prc': '2czt-qzar',
 '22bw-ijyi': '4mk5-vv45',
 '6gtx-i289': '7qc8-fj3p',
 'jjnc-cu9z': 'pgs5-k2ve',
 'mxmm-svgz': 'etbc-tkgn',
 'xh4c-32wb': 'jppe-46v2',
 'xwky-bmsn': 'f4n4-vnyx',
 'yqfw-dg5f': '385d-6w27',
 '6ddv-3hk2': 'ic5a-quwv',
 'r87x-h98m': 'kyzd-u4zr',
 '7yta-8qvv': 'jiwb-nqtz',
 '8vnm-57r6': 'ibr4-saca',
 'bd44-na6d': 'vy7p-ixjg',
 'c6qj-6kx2': 'k73m-yqwy',
 'cuid-432h': 'jfqj-df4i',
 'f3th-4ste': 'ivcq-5wnv',
 'fjhv-ruxa': '8d8p-eabg',
 'gvnt-p2w8': 'xf9x-4vrx',
 'khe9-7d2c': 'eu3v-3d3m',
 'nbfg-y9mh': 'm6cj-y4yw',
 'nnpy-czzx': '85u5-cuz2',
 'p674-r4hf': 'ehbb-wpcw',
 'us3j-cyz6': 'vefd-xfvu',
 'v4w4-3yz8': 'sbcg-h3as',
 'xipb-k5bu': '49x6-nvb5',
 '33fk-kb5q': '5733-dk6i',
 '94t6-d4wd': 'uzap-vkkz',
 '9b7x-qm8d': 'q9ua-9k3d',
 'gu6r-zvv2': 'rt3s-2378',
 'hcfi-bvst': 'gx4f-gkav',
 'hxnu-kp2f': 'imy5-eits',
 'kfm9-mvzv': '93kh-r488',
 'wcvg-8vki': '7jyi-58ux',
 'wtpp-eaj8': 'jkfh-gi5i',
 'x5e5-npqm': 'bv6m-vkmf',
 '5qqr-23dz': '9ucd-vbp8',
 'u943-ics6': 'vhut-u4rz',
 'q5vp-adf3': 'tv8u-hswn',
 '349y-twqi': 'ymww-exmk',
 'e4mf-ggwf': 'e4mf-ggwf',
 'a58g-ce2r': 'a58g-ce2r',
 '68n7-r6rp': '4wg3-tqyq',
 'ipm7-5rxr': 'ph23-52ee',
 'k26c-fz5q': 'hymk-uc38',
 'knby-gpaw': 'jeme-vzwk',
 'n5sw-qzbs': '92i4-sq8f',
 'u4xw-xiec': 'swg4-buem',
 'vewn-5ajx': '8i97-peax',
 'x2jf-bvk8': 'yha9-4ccf',
 'xb4j-dshc': 'mbbw-b2d6',
 'rkuy-jxyz': 'rkuy-jxyz',
 'm9tc-zgz8': 'm9tc-zgz8',
 '4am6-w6u4': 'xa32-xrhn',
 '4ykn-tg5h': '4eit-nuxn',
 'pxgq-s7pg': 'pxgq-s7pg',
 'vqx7-fwxd': 'vqx7-fwxd',
 'f325-6r9c': 'sdj2-eu7g',
 'rtw9-6tit': 'gjan-8bvh',
 '8upq-58vz': 'x6nk-8epw',
 'wffy-3uut': '8d38-bpb6',
 'unz2-68bn': 'kw3i-nbzq',
 'rpvk-ifh4': 'm2xu-8h22',
 'nxw4-ev8w': '3j8c-74kv',
 'jd4d-pcwx': 'qsdh-79ii',
 'e86d-vx82': 'g9ic-qkrx',
 'pfjr-vhp3': 'tad2-pzgf',
 'yree-6k9x': 'xtzv-jp5p',
 'fph6-vi4y': 'd7g2-77vf',
 'ii3b-uafi': 'qp93-8k7d',
 '5s6g-ze7t': 'b3y4-fgw8',
 'wpcp-usqg': 'a9xs-cha8',
 'yajv-ea35': 'smwj-ct9m',
 '9bzu-nqxb': 'cke2-rfdy',
 'fypu-tup4': 'u5s6-q8vu',
 '443p-eijy': 'ah76-cwyd',
 'team-3ugz': 'c7ve-fkni',
 'xiem-he2v': '',
 '6ad7-gqy3': 'yw89-ab4q',
 'ap62-sav4': '72ay-gvmj',
 '73ay-2ues': '73ay-2ues',
 '8ant-mn9d': '8ant-mn9d',
 'cx7q-izrb': 'p8vj-f8bc',
 '4yw9-a5y6': '4yw9-a5y6',
 'xwar-3geb': 'xwar-3geb',
 'ue5s-8u8t': 'he3j-mqae',
 '4jjg-g3yq': 'xv5c-h458',
 'cdkn-c7n9': 'tvek-dibi',
 'e4ky-6g2n': 'uxyf-4dfg',
 '8pk9-mh2i': 'xyh2-p9cg',
 'hb4b-8v4q': 'ffh6-n4ga',
 'mv3v-5qet': 'mwga-t3nx',
 'evkd-zgn4': 'j6yj-kaid',
 'sc9q-ryk8': '',
 '5ccs-vx79': '',
 'knn6-7fy9': '32h9-64b2',
 'mev7-qffb': 'mev7-qffb',
 'qifa-4jur': 'qifa-4jur',
 'sacq-tw7c': 'sacq-tw7c',
 '7tmk-3ibe': '7tmk-3ibe',
 '9fte-yff6': '9fte-yff6',
 '3ka2-m6zm': '3ka2-m6zm',
 'ceje-t3ek': 'ceje-t3ek',
 'afm6-vyyp': 'afm6-vyyp',
 '24hn-nv39': '24hn-nv39',
 'y2yv-a2wp': 'y2yv-a2wp',
 'b7zn-sry4': 'b7zn-sry4',
 'kr2r-j5ik': 'kr2r-j5ik',
 '3j7e-ezpr': '3j7e-ezpr',
 'u9u9-cq2s': 'u9u9-cq2s',
 'abdb-jtwc': 'abdb-jtwc',
 'mdbi-p4c8': 'mdbi-p4c8',
 't3k6-vndx': 't3k6-vndx',
 'rcw7-6npp': 'rcw7-6npp',
 'nwd2-s3kd': 'nwd2-s3kd',
 'd2cu-rhft': 'd2cu-rhft',
 '42wt-sxkv': '42wt-sxkv',
 '6exr-8xkn': '6exr-8xkn',
 'wyy2-wvrc': 'wyy2-wvrc',
 'w2w7-ggyk': 'w2w7-ggyk',
 '8pmi-n437': '8pmi-n437',
 't5eg-ziay': 't5eg-ziay',
 'yvwz-kj9z': 'yvwz-kj9z',
 'eeb6-6s76': 'eeb6-6s76',
 '72dx-vrxk': '72dx-vrxk',
 'ccz9-ggrb': 'ccz9-ggrb',
 'an2q-gwrx': 'an2q-gwrx',
 'jr8i-33tp': 'jr8i-33tp',
 'cr6z-hn4e': 'cr6z-hn4e',
 '2sn7-naei': '2sn7-naei',
 'sshp-3kyq': 'sshp-3kyq',
 'q7ri-3nsu': 'q7ri-3nsu',
 'f3vc-vat3': 'f3vc-vat3',
 'mpff-jbkx': 'mpff-jbkx',
 'wnau-xrqi': 'wnau-xrqi',
 '66zf-qjdd': '66zf-qjdd',
 '23sa-se52': '23sa-se52',
 '74qa-79bk': '74qa-79bk',
 'dsw3-mrn4': 'dsw3-mrn4',
 'sys8-yyuf': 'sys8-yyuf',
 'npnz-8mvz': 'npnz-8mvz',
 'sxfp-qxs6': 'sxfp-qxs6',
 'v4jc-jbmt': 'v4jc-jbmt',
 'be63-q8yz': 'be63-q8yz',
 'u56p-777a': 'u56p-777a',
 'j3me-5ifv': 'j3me-5ifv',
 'bxgy-dnjp': 'bxgy-dnjp',
 'xz8z-8s8e': 'xz8z-8s8e',
 'x88m-3a2j': 'x88m-3a2j',
 'u6xi-qwn3': 'u6xi-qwn3',
 'mxfq-jecf': 'mxfq-jecf',
 'ujgg-3rdh': 'ujgg-3rdh',
 'ytai-hin3': 'ytai-hin3',
 'sn8z-q44h': 'sn8z-q44h',
 'druy-a38s': 'druy-a38s',
 '2mk-94p9': '2mk-94p9',
 '35y-dxds': '35y-dxds',
 'xi5f-mkzt': 'xi5f-mkzt'}

In [50]:
SERVICE_ACCOUNT_FILE = os.path.join("/home","joe", 'work',"client_secret.json")
print(SERVICE_ACCOUNT_FILE)
scope = ['https://www.googleapis.com/auth/spreadsheets.readonly',
         "https://www.googleapis.com/auth/drive"]

creds = ServiceAccountCredentials.from_json_keyfile_name(SERVICE_ACCOUNT_FILE,
 scope)
client = gspread.authorize(creds)

fields_sheet = client.open('BIC Data Inventory and Metadata').worksheet(
    'MetadataRepository')

print("field sheet",fields_sheet)

dfFields = pd.DataFrame(fields_sheet.get_all_records(head=3))

/home/joe/work/client_secret.json
field sheet <Worksheet 'MetadataRepository' id:323813469>

In [52]:
dfFields.columns

Index(['Dataset Title', 'Short Description', 'Category', 'Keywords',
       'License Type', 'Data Provider', 'Data Provided by', 'Source Link',
       'State Steward', 'Citation', 'Agency Program Page',
       'Agency Data Series Page', 'Business Contact and Phone',
       'Technical Contact and Phone', 'Data Source', 'Unit of Analysis',
       'Granularity Coverage', 'Geographic Extent and Division',
       'Collection Mode', 'Collection Methodology',
       'Data Collection Instrument', 'Date of Initial Dataset Creation',
       'Field Names, comma delimited', 'Oldest Record in Dataset',
       'Newest Record in Dataset', 'Long Description', 'Data Dictionary',
       'Additional Metadata', 'Technical Documentation',
       'Data Quality Certification',
       'Applicable Information Quality Guideline Designation',
       'Stewardship Plan', 'Collection Method', 'Horizontal Accuracy',
       'Horizontal Coordinate System', 'Update Schedule', 'Update Method',
       'Source Update Schedule', 'Update Type',
       'Total Records at Initial Publish', 'Row Class RDF',
       'Subject Column RDF', 'Single Row', 'Row Count (11/20/17)',
       'Total Fields at Initial Publish',
       'FIle Size at Initial Publish or as of 3-1-2016',
       'Expected approximate increase in record count at update',
       'Date Published to CIM', 'GoCode FY Published to CIM', 'Socrata Link',
       'API 4x4', 'Web Display Coordinate System',
       'Coordinate System Disclaimer', 'Related Datasets',
       'Quarter of Gov FY Published'],
      dtype='object')

In [49]:
a[1]

['CIM Category ->',
 'General Information',
 '',
 '',
 'Licensing & Attribution',
 '',
 '',
 '',
 '',
 'Contributing Agency Information',
 '',
 '',
 '',
 '',
 '',
 'Dataset Coverage',
 '',
 '',
 'Data Description',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'Additional Dataset Documentation',
 '',
 '',
 'Data Quality',
 '',
 '',
 'Geospatial',
 '',
 '',
 'Data Updates',
 '',
 '',
 '',
 '',
 'Semantics & RDF',
 '',
 '',
 'Internal Data',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '']

In [9]:
dfCIMMapCen[['UID', 'Name', 'Owner','Audience','Type']].to_csv("Map_Datasets_Census.csv",index=False)